### ISSUE TITLE
weinre 是根据什么判断 html 的？

### ISSUE THREAD

**Issue by stevieyu** [avwo/whistle#10]
系统是 mac，没开防火墙，使用weinre时,targets 是none,貌似要写手动写weinre的 js 才可以用,
```html
<script src="http://x.x.x.x:8901/target/target-script-min.js#anonymous"></script>
```

**Comment by avwo** [comment]
根据响应的content-type，你看下请求有没有匹配到规则，还有weinre的id有没有弄错

**Comment by yzm629** [comment]
如果没设weinre id的话不是默认全部只要是html都注入的吗？

**Comment by avwo** [comment]
默认是anonymous

**Comment by stevieyu** [comment]
anonymous 的话 html 类型貌似并不会注入weinre

**Comment by avwo** [comment]
看下响应头有没有content-type: text/html，如果没有是不会自动注入weinre的脚本

**Comment by stevieyu** [comment]
![image](https://cloud.githubusercontent.com/assets/8325201/18944613/027b1834-8659-11e6-961e-b9237e618507.png)
访问开源中国，这个的头是有 content-type: text/html
![image](https://cloud.githubusercontent.com/assets/8325201/18944633/1cb1bd8e-8659-11e6-8d62-fae8d9fe150d.png)
weiner 却只是这样 network 一片空白

**Comment by avwo** [comment]
应该是规则没有匹配上，如果匹配上url会加粗，你怎么设置规则的。

这边试了下可以的，你试试这个：

```
www.oschina.net weinre://
```

**Comment by stevieyu** [comment]
啥规则都没写,我的想法是不写规则，作用于全部属于 html 的页面

**Comment by avwo** [comment]
如果要所有html生效可以用正则匹配：
```
/./ weinre://
```

whistle不仅仅做weinre这个事情，还有很多功能，还是需要用户自己配置具体需要哪些功能

**Comment by stevieyu** [comment]
谢谢，可以了，主要是不想每个网址都配一遍，
还有带 ip 跟端口的规则怎么写？ 
192.168.199.82 weinre://
192.168.199.82:1111 weinre://
上面这两种规则写法都不行

**Comment by avwo** [comment]
前面不加协议，whistle会认为是在配置host(whistle的host可以带端口)
 ```
weinre:// http://192.168.199.82 http://192.168.199.82:1111 https://192.168.199.82 https://192.168.199.82:1111
```

**Comment by stevieyu** [comment]
谢谢您的盛情解答，我用 `/192.168.199.82/ weinre://` 解决了
