### ISSUE TITLE
URL中 '#' 字符转义

### ISSUE THREAD

**Issue by elvinn** [avwo/whistle#100]
对于如下的规则：

```
redirect://http://m.ke.qq.com/exam/#/?fleid=10000 ke.qq.com/course/239351 
```

重定向的 URL 中 `#` 会被识别为注释，从而造成规则不生效的情况。

**Comment by elvinn** [comment]
目前的解决方法是在 rules 中添加如下规则：
```
redirect://{redirect.txt} ke.qq.com/course/239351
```

然后在 values 中添加如下 `redirect.txt`:

**Comment by avwo** [comment]
主要原因是 `#` 在Rules里面是一个注释符，可以把内容放在Values中的某个key，通过对应的key引入，这样whistle在解析Rules的时候就不会过滤掉
