### ISSUE TITLE
 "Accept-Encoding" 丢失参数

### ISSUE THREAD

**Issue by 8763232** [avwo/whistle#1001]
原始是 "Accept-Encoding":"gzip, deflate",
经过whistle后就变成 "Accept-Encoding":"gzip",
导致服务器拒绝访问。

**Comment by avwo** [comment]
https://github.com/avwo/whistle/issues/950

**Comment by 8763232** [comment]
> #950

现在出现因为这个导致服务器拒绝请求，直接跳转到404

**Comment by avwo** [comment]
服务器限制了压缩算法？链接发我看下
