### ISSUE TITLE
socket connect timeout

### ISSUE THREAD

**Issue by sedationh** [avwo/whistle#1003]
<img width="1255" alt="image" src="https://github.com/avwo/whistle/assets/56129212/68318c64-5320-43dd-9625-3b51d2ade079">

不确定复现的充分条件

必要条件是开着 Whistle 的 Set As System Proxy一段时间，使用部分网页会出现问题，如 Google 搜索

**Comment by sedationh** [comment]
另外用的是 https://github.com/avwo/whistle-client，但感觉和客户端没什么关系，就提这里了

**Comment by avwo** [comment]
有用翻墙软件吗

**Comment by sedationh** [comment]
本机无，用的公司内网那边会有相关服务，有无定位方法，下次复现我查查看

**Comment by avwo** [comment]
这个是建立连接时报错，跟你本机网络环境有关，找下你们运维查下本地服务的日志。
