### ISSUE TITLE
rule生效问题

### ISSUE THREAD

**Issue by canjieChen** [avwo/whistle#1004]
hi大佬，我发现rules的生效在不同mac上有不同的表现

我在mac A上可以同时生效多个rule，而在mac B上却只能同时生效一个rule

这个事情让我十分的困扰，麻烦帮忙check下，是否帮忙处理下，感谢感谢！！！！

QQ：3387124537

**Comment by avwo** [comment]
参考下这个：https://github.com/avwo/whistle/issues/976

**Comment by canjieChen** [comment]
> 参考下这个：#976

不是哦，你引用的这是在一个rule里面的匹配

我的问题是多个rule怎么同时生效，如图，一个rule被enable，另一个rule就被disable
<img width="277" alt="image" src="https://github.com/avwo/whistle/assets/25762935/03b49522-fb62-42df-b462-492c12512804">

**Comment by avwo** [comment]
从上到下，Default 优先级最低
