### ISSUE TITLE
使用@链接到本地文件的规则扩展是否可以及时更新

### ISSUE THREAD

**Issue by backrunner** [avwo/whistle#1008]
背景：

目前项目在开发调试中会启动多个devServer到不同的端口，我通过一个webpack插件在编译完成后自动生成代理规则，对同一个目录路径下的不同js文件分流到对应的devServer上，规则是一个本地的txt，用 `@` 导入到whistle中。

按照 [https://github.com/avwo/whistle/issues/277](https://github.com/avwo/whistle/issues/277) 的说法，目前whistle是10秒检查、更新一次本地文件，这会导致代码修改、重新编译之后，HMR不能及时拉到最新的chunk（代理规则没有及时更新，回来404）。

诉求：

希望对本地文件能够用 fs.watch / chokidar 之类的手段实现及时的更新，这样只需要稍稍推迟 HMR 就能满足诉求，10s对于自动化生成代理规则的项目来说有点太长了。

**Comment by avwo** [comment]
需要实时可以用插件，参考：https://github.com/whistle-plugins/examples/tree/master/whistle.test-rules

**Comment by backrunner** [comment]
> https://github.com/whistle-plugins/examples/tree/master/whistle.test-rules

感觉有一些多此一举，本质上我并没有新增什么功能和规则，只是为了规避一个10s的生效时间。本身whistle的编辑器内是即时生效的，基于本地文件的规则拓展却不可以，也有一点反直觉。

**Comment by avwo** [comment]
这么设计的目的是在保证大部分应用场景下，让 Whistle 的扩展可控，这里如果不控制远程规则的加载频率，用户这种规则设置多势必对性能造成影响且不可控。
对特殊的应用场景，Whistle 也提供了插件扩展，可以随心所欲的根据自己业务需要扩展功能，插件是独立进程理论上不会影响 Whistle 的主进程。

**Comment by backrunner** [comment]
https://github.com/backrunner/whistle.local-rules
好吧，自己写了一个插件处理了，后面有伙伴有类似问题可以直接沿用
