### ISSUE TITLE
 手机代理后浏览器就打不开页面了

### ISSUE THREAD

**Issue by tangyuan4ou** [avwo/whistle#101]
mac电脑  安卓手机  两个设备同一网络下  手机配置了代理之后无法访问页面

**Comment by avwo** [comment]
mac的防火墙关掉试试

**Comment by tangyuan4ou** [comment]
是关掉的。。。。

**Comment by avwo** [comment]
用哪个ip配置代理，试下执行 `w2 restart -H yourProxyIp`

**Comment by tangyuan4ou** [comment]
![image](https://user-images.githubusercontent.com/20010865/34376961-b2d61176-eb29-11e7-91bc-8e0dee58075f.png)
报错，代理我是直接下的谷歌插件whistle-for-chrome插件
端口和ip都是默认的

**Comment by avwo** [comment]
`w2 restart -H 10.100.33.71` ，然后在pc上打开 [http://10.100.33.71:8899](http://10.100.33.71:8899/)访问，试下手机能不能正常访问

**Comment by tangyuan4ou** [comment]
哎  还是不好使

**Comment by jellyhui** [comment]
请问这个问题有解决办法吗？ 目前所查到的回答，都未能解决。

**Comment by avwo** [comment]
更新下whistle 看下这个 https://github.com/avwo/whistle/issues/78

**Comment by avwo** [comment]
家里还是公司的网络，公司网络问下你们公司的运维

**Comment by jellyhui** [comment]
刚好趁周末，在家里也试了，也是不行。甚至去借了别人的Wi-Fi也去尝试了，还是手机连上代理就无网络了。

**Comment by avwo** [comment]
代理的ip有没问题配对

**Comment by kentpan** [comment]
是mac本吗？配置代理后无法浏览，无法抓包可以试试 sudo w2 start

**Comment by avwo** [comment]
尽量不要sudo启动

**Comment by li1164267803** [comment]
2023年了，这个问题偶尔就会发生，还不知道是什么导致的，上一秒还在用，下一秒说什么都连接不上不来，没有网络
