### ISSUE TITLE
X-Forwarded-For Header 浏览器插件，配置`x-forwarded-for`字段无效

### ISSUE THREAD

**Issue by luguiqing** [avwo/whistle#1010]
谷歌插件 [X-Forwarded-For Header](https://chrome.google.com/webstore/detail/x-forwarded-for-header/hkghghbnihliadkabmlcmcgmffllglin)， 可以修改如下图headers头， 但是`x-forwarded-for`字段修改无效；

![image](https://github.com/avwo/whistle/assets/20262570/4baedf2d-ddae-4595-8df6-b50352b83c0c)

请教下两个问题：

1. 是因为 内置`forwardedFor`配置，所以才导致该请求头`x-forwarded-for`无法正常透传吗？
2. 目前通过 `reqScript` 的形式来实现该效果，有其他好的推荐方式吗？
```javascript
# forwardedFor.js
if (headers['x-remote-addr']) {
   rules.push('* forwardedFor://' + headers['x-remote-addr'])
}

```

**Comment by avwo** [comment]
两者不要混用

**Comment by luguiqing** [comment]
好的，谢谢
