### ISSUE TITLE
DNS Lookup fail

### ISSUE THREAD

**Issue by Yanado2122** [avwo/whistle#1017]
DNS Lookup Failed
From: whistle@2.9.60
Node: v21.4.0
Host: xxxMacBook-Pro.local
Date: 12/8/2023, 4:14:50 PM
Error: getaddrinfo ENOTFOUND [ipv6 address]
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:107:26)

google worked fine, when I open a IPV6 address with Whistle proxy, it failed,  close proxy worked fine.

**Comment by avwo** [comment]
Click the `Online` button in the upper right corner, and check `IPv6-only network` to try：
<img width="118" alt="image" src="https://github.com/avwo/whistle/assets/11450939/81dc7ac2-a41d-43bf-b391-a0e7c80373c1">

<img width="349" alt="image" src="https://github.com/avwo/whistle/assets/11450939/1f4a7200-a8db-4322-8a2a-7801b0749c48">

**Comment by Yanado2122** [comment]
open IPv6-only network, restart Whistle, still fail, 
有没有什么方便可以帮助定位问题，或者查看是否本地node环境问题？

**Comment by avwo** [comment]
应该是你本机网络问题，看下安装了什么软件，或者重启电脑试试。

**Comment by avwo** [comment]
已修复，更新下 Whistle
