### ISSUE TITLE
Hard-coded key in HMAC 

### ISSUE THREAD

**Issue by tianjk99** [avwo/whistle#1018]
Please check if there is any problem with using fixed key.

1. bin/util.js, line 163

The presence of a hardcoded key in the HMAC implementation introduces vulnerabilities that can compromise the security of our application. Using a fixed key may reduce security and easily cause key exposure, difficulty in key rotation, and encryption failure. For enhanced security, it is recommended to remove hardcoded passwords and store key securely using industry-standard practices such as hashing and salting.

**Comment by avwo** [comment]
This is only used to generate temporary file names, there will be no security issues.
