### ISSUE TITLE
mac proxy https报错

### ISSUE THREAD

**Issue by ganker-vito** [avwo/whistle#1023]
证书没问题
![image](https://github.com/avwo/whistle/assets/59476777/4902f143-2251-43ac-9fc7-e967ee281079)

访问https报错
![image](https://github.com/avwo/whistle/assets/59476777/23a4a2b4-8837-4ec0-898f-40c546be1282)

switchOmega配置如下
<img width="1144" alt="image" src="https://github.com/avwo/whistle/assets/59476777/d3a2677e-8f05-41c6-b801-48ba7c29da2a">

client https设置
![image](https://github.com/avwo/whistle/assets/59476777/8219447b-5763-4d7f-aa8c-74663bbd4e2d)

尝试多种办法均无法抓包https

**Comment by avwo** [comment]
这是浏览器还是某个客户端的请求？客户端请求有可能是 ssl pinning 导致的

**Comment by ganker-vito** [comment]
> 这是浏览器还是某个客户端的请求？客户端请求有可能是 ssl pinning 导致的

浏览器的，我本身有启在其他端口的clashx, clashx和whistle都不是系统代理。这个是否有影响呢？

**Comment by ganker-vito** [comment]
> > 这是浏览器还是某个客户端的请求？客户端请求有可能是 ssl pinning 导致的
> 
> 浏览器的，我本身有启在其他端口的clashx, clashx和whistle都不是系统代理。这个是否有影响呢？

在windows上试过了，可以抓https。mac上不知道为啥就是不行

**Comment by avwo** [comment]
用命令行 `w2 ca` 安装根证书试试

**Comment by ganker-vito** [comment]
> 用命令行 `w2 ca` 安装根证书试试

试过了，也不行

**Comment by avwo** [comment]
用什么浏览器？

**Comment by ganker-vito** [comment]
> 用什么浏览器？

chrome
证书目前搜出来是这样子的
![image](https://github.com/avwo/whistle/assets/59476777/46778587-cb07-4678-b911-dac928d03632)

**Comment by ganker-vito** [comment]
> 用什么浏览器？

chrome

**Comment by ganker-vito** [comment]
> 用什么浏览器？

![image](https://github.com/avwo/whistle/assets/59476777/1b6e3016-8076-4b6c-9390-0c22c879bd30)

![image](https://github.com/avwo/whistle/assets/59476777/c331023a-63bc-430b-8d79-05e6f24b19c0)

在chrome的setting搜证书
<img width="933" alt="image" src="https://github.com/avwo/whistle/assets/59476777/859f0efb-58f7-4ec3-9f4a-1021e0614a9a">

感觉不像是证书的原因，但是也找不到啥其他原因 很尴尬

**Comment by ganker-vito** [comment]
> 用什么浏览器？

开系统代理，用safari正常。 但是chrome就不行。 感觉是chrome设置的原因？

**Comment by ganker-vito** [comment]
> > 用什么浏览器？
> 
> 开系统代理，用safari正常。 但是chrome就不行。 感觉是chrome设置的原因？

<img width="836" alt="image" src="https://github.com/avwo/whistle/assets/59476777/a79ba390-6707-4cc1-904d-7ddab0fb56a6">
