### ISSUE TITLE
可以在operator-uri中使用正则吗？

### ISSUE THREAD

**Issue by imadentive** [avwo/whistle#103]
例如xxx.com/web/m/js/52.aaa.js file:///User/username/m/js/52.bbb.js,
在操作uri中匹配以52开头的文件名，子匹配不适用。

**Comment by avwo** [comment]
只能自己通过url来设置，可以试试这个：[reqScript](https://avwo.github.io/whistle/rules/reqScript.html)

**Comment by imadentive** [comment]
已经试过了reqScript方法了，还是无法实现。谢谢。实现的前提还是要operator-uri中能使用正则。

**Comment by avwo** [comment]
用插件实现，可以自己通过node操作本地文件再动态设置规则：
插件开发文档：[https://avwo.github.io/whistle/plugins.html](https://avwo.github.io/whistle/plugins.html)
示例：[https://github.com/whistle-plugins](https://github.com/whistle-plugins)
或者直接用插件[whistle.script](https://github.com/whistle-plugins/whistle.script)实现
