### ISSUE TITLE
代理localhost没问题，为什么代理127.0.0.1请求会504

### ISSUE THREAD

**Issue by mxy2316868975javascript** [avwo/whistle#1030]
本地hosts文件配置
127.0.0.1 localhost

现象
![image](https://github.com/avwo/whistle/assets/15233384/7eff2d70-bf0a-4e21-932d-da777b26347b)
![image](https://github.com/avwo/whistle/assets/15233384/75d160b7-2010-4fe6-aad3-b7eda0ccf617)

**Comment by avwo** [comment]
看下响应内容是什么

**Comment by mxy2316868975javascript** [comment]
> 看下响应内容是什么

没有响应内容一直pending，127.0.0.1换成localhost就，可以请问原因有哪些

**Comment by avwo** [comment]
whistle 里面可以看到 `127.0.0.1` 的请求吗，再看下服务端有没有现在请求的域名

**Comment by mxy2316868975javascript** [comment]
> whistle 里面可以看到 `127.0.0.1` 的请求吗，再看下服务端有没有现在请求的域名

whistle里可以看到请求，pending一段时间后显示504， 服务端有请求的域名

**Comment by avwo** [comment]
规则里面的 `127.0.0.1:3000` 改成 `http://localhost:3000` 试试

**Comment by mxy2316868975javascript** [comment]
> 规则里面的 `127.0.0.1:3000` 改成 `http://localhost:3000` 试试

改成localhost没问题，想问的是用127.0.0.1为什么不行的原因，以及解决方案

**Comment by avwo** [comment]
看下 devServer 的 allowedHosts 配置

**Comment by mxy2316868975javascript** [comment]
> devServer 的 allowedHosts

allowedHosts: 'all'

**Comment by eiinu** [comment]
遇到了完全相反的情况，127.0.0.1 可以，localhost 不行😂

```
DNS Lookup Failed
From: whistle@2.9.61
Node: v18.17.1
Host: ******
Date: 2024/2/6 09:18:19
Error: getaddrinfo ENOTFOUND loaclhost
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:108:26)
```
