### ISSUE TITLE
whistle的rules中是否能引用系统环境变量或node的process.env?

### ISSUE THREAD

**Issue by northwang-lucky** [avwo/whistle#1032]
whistle的rules中是否能引用系统环境变量或node的process.env?

**Comment by avwo** [comment]
看下文档里面的模板字符串：https://wproxy.org/whistle/data.html
可以在模板字符串里面通过 `${env.xxx}`  读取 process.env 里面的值，如：
``` txt
www.test.com/path/to file://`(${env.path})`
```

**Comment by northwang-lucky** [comment]
好的，谢谢~
不过我刚看了下文档，[https://wproxy.org/whistle/data.html](https://wproxy.org/whistle/data.html) 这个里面确实没有提到过这个用法~
感谢回答~

**Comment by avwo** [comment]
欢迎提 PR
