### ISSUE TITLE
linux 平台无法抓包

### ISSUE THREAD

**Issue by ponponon** [avwo/whistle#1037]
我在 ubuntu22.04 和 debian12 都测试了，运行 `w2 restart --init` 会下面的内容

```shell
─➤  w2 restart --init
[i] whistle@2.9.63 restarted
[i] 1. use your device to visit the following URL list, gets the IP of the URL you can access:
       http://127.0.0.1:8899/
       http://192.168.31.245:8899/
       http://172.26.0.1:8899/
       http://172.21.2.1:8899/
       http://172.21.3.1:8899/
       http://172.21.1.1:8899/
       http://172.21.0.1:8899/
       http://172.21.10.1:8899/
       Note: If all the above URLs are unable to access, check the firewall settings
             For help see https://github.com/avwo/whistle
[i] 2. set the HTTP proxy on your device with the above IP & PORT(8899)
[i] 3. use Chrome to visit http://local.whistlejs.com/ to get started
Platform linux is unsupported to set global proxy for now.
Platform linux is unsupported to install root CA for now.

```

且无法抓包，手机访问某些网站直接无法访问，w2 web 界面上也看不到对应的包

＞ 已经在手机上安装 rootca.pro 证书

![图片](https://github.com/avwo/whistle/assets/38725104/2312a15a-1ccb-4d0d-aba1-76f5305ddcaf)

但是把 w2跑在 mac 下面就是一切正常，w2没有异常输出，手机的数据也可以被 mac 上的 w2 抓包到

```shell
╭─ponponon@MBP13ARM ~
╰─➤  w2 restart                                                                                                                                                                                       130 ↵
[i] whistle@2.9.61 restarted
[i] 1. use your device to visit the following URL list, gets the IP of the URL you can access:
       http://127.0.0.1:8899/
       http://192.168.31.103:8899/
       Note: If all the above URLs are unable to access, check the firewall settings
             For help see https://github.com/avwo/whistle
[i] 2. set the HTTP proxy on your device with the above IP & PORT(8899)
[i] 3. use Chrome to visit http://local.whistlejs.com/ to get started

```

**Comment by avwo** [comment]
linux 要自己手动安装根证书 https://wproxy.org/whistle/webui/https.html

**Comment by ponponon** [comment]
> > linux 要自己手动安装根证书 https://wproxy.org/whistle/webui/https.html
> 
> linux 下使用 Whistle， 去哪里下载 rootCA.crt
> 
> https://wproxy.org/whistle/webui/https.html 这个教程只说要下载 rootCA.crt ，但是没说 linux 下怎么下载。上面只有一个二维码，我的 linux 服务器也没有摄像头呀

我知道了，先启动 w2

```shell
─➤  w2 start --init
[!] whistle@2.9.63 is running
[i] 1. use your device to visit the following URL list, gets the IP of the URL you can access:
       http://127.0.0.1:8899/
       http://192.168.168.42:8899/
       Note: If all the above URLs are unable to access, check the firewall settings
             For help see https://github.com/avwo/whistle
[i] 2. set the HTTP proxy on your device with the above IP & PORT(8899)
[i] 3. use Chrome to visit http://local.whistlejs.com/ to get started
Platform linux is unsupported to set global proxy for now.
Platform linux is unsupported to install root CA for now.
```

然后找个浏览器打开上面的地址，然后选择 HTTPS

<img width="1080" alt="图片" src="https://github.com/avwo/whistle/assets/38725104/8761700b-b91f-470a-a268-58a19aa97b32">

在点击二维码，就会自动下载

<img width="667" alt="图片" src="https://github.com/avwo/whistle/assets/38725104/c7b128a3-013c-4a16-ba0d-d61efed0fd51">

**Comment by ponponon** [comment]
> linux 要自己手动安装根证书 https://wproxy.org/whistle/webui/https.html

但是我给 linux 安装了 rootCA.crt ，然后 linux 上的 w2 还是看不到手机的流量包

```shell
╰─➤  ll /usr/share/ca-certificates/ | grep root
1080550 drwxr-xr-x      2    -      - root root  17 1月  14:11 mozilla
1106254 .rw-r--r--      1 1.5k      8 root root  18 1月  18:27 rootCA.crt
(wechatimagesearch-BoMovYbH) ╭─pon@wechat-console ~/code/work/vobile-it/wechatimagesearch  ‹master*› 
╰─➤  cd /usr/share/ca-certificates/
(wechatimagesearch-BoMovYbH) ╭─pon@wechat-console /usr/share/ca-certificates  
╰─➤  su -
密码： 
root@wechat-console:~# reboot^C
root@wechat-console:~# ^C
root@wechat-console:~# echo "rootCA.crt" >> /etc/ca-certificates.conf && update-ca-certificates^C
root@wechat-console:~# cd /usr/share/ca-certificates/
root@wechat-console:/usr/share/ca-certificates# 
root@wechat-console:/usr/share/ca-certificates# 
root@wechat-console:/usr/share/ca-certificates# 
root@wechat-console:/usr/share/ca-certificates# echo "rootCA.crt" >> /etc/ca-certificates.conf && update-ca-certificates
Updating certificates in /etc/ssl/certs...
0 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d...
done.
root@wechat-console:/usr/share/ca-certificates# trust list | grep -i whistle
    label: whistle.1705573127768146
```

这个也勾选了

<img width="584" alt="图片" src="https://github.com/avwo/whistle/assets/38725104/6fec0005-e5a9-4407-916e-3d3910c0705a">

**Comment by ponponon** [comment]
> ssl pinning 暂时无常规解

是不是我要抓取的这些，只能是 w2+mac 或者 w2+win 才行？因为 mac 下我验证过是正常的，但是想把 w2 部署到 linux 服务器的时候，发现 w2 抓不到之前部署在 mac 上的那种包了

**Comment by ponponon** [comment]
我发现可以抓包了

<img width="1552" alt="图片" src="https://github.com/avwo/whistle/assets/38725104/44782636-3901-47c0-9d40-7f692ff65606">

解决办法是，我的小米14 上的 rootca.pro 的证书是来自 mac 上的 w2

然后我把小米14 上的证书都删除（清除凭证）

重新打开浏览器输入 rootca.pro 下载 debian12 上的 rootCA.crt 再安装就好了，就能抓包了

![图片](https://github.com/avwo/whistle/assets/38725104/2a018500-6761-4822-ada7-ef151448476e)

所以如果重新安装了 w2，是不是 rootCA.crt  证书内容会发生变化需要重新安装？

**Comment by ponponon** [comment]
> ssl pinning 暂时无常规解

如果重新安装了 w2，是不是 rootCA.crt 证书内容会发生变化需要重新安装？

**Comment by avwo** [comment]
不需要

**Comment by ponponon** [comment]
<img width="1143" alt="图片" src="https://github.com/avwo/whistle/assets/38725104/ce3cebc2-7930-4400-af65-cb37f2d9fb79">

我对比了一下现在新的 rootCA.crt 内容和之前在 mac 上生成的 rootCA.crt ，发现内容是不一样的

**Comment by ponponon** [comment]
> <img alt="图片" width="1143" src="https://private-user-images.githubusercontent.com/38725104/297721456-ce3cebc2-7930-4400-af65-cb37f2d9fb79.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDU1NzcwMTUsIm5iZiI6MTcwNTU3NjcxNSwicGF0aCI6Ii8zODcyNTEwNC8yOTc3MjE0NTYtY2UzY2ViYzItNzkzMC00NDAwLWFmNjUtY2IzN2YyZDlmYjc5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTE4VDExMTgzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZkNjAwMzg2N2JkNTI1ZDVlZTQxYzU3OWIzZDY0MTdkMTAxMDFjMDJhMzQyZWUxODQ1ZTJiYjg0ODU3Y2VjZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.LGhM2kYFEuZvVV4UIJ2Gzr3mHg37oZ_zp8p12a68SJg">
> 
> 我对比了一下现在新的 linux 上的 rootCA.crt 内容和之前在 mac 上生成的 rootCA.crt ，发现内容是不一样的

是不同机器会生成的 rootCA.crt 会不一样，还是不同操作系统生成的 rootCA.crt 会不一样？

**Comment by avwo** [comment]
对，不同机器或同一系统不同账号不同
