### ISSUE TITLE
请问有没有导出功能

### ISSUE THREAD

**Issue by shoaly** [avwo/whistle#104]
比如一次抓包结束之后, 把若干个请求全部导出成一个文件, 方便日后重新打开

**Comment by avwo** [comment]
支持的，选中要导出的请求(按Ctrl或Shift键可以多选)，然后鼠标hover到 `Network` 菜单就有导出功能，可以导出成Fiddler的saz或whistle的txt文件

**Comment by avwo** [comment]
最新版本的whistle，通过右键菜单也可以导入导出抓包数据

**Comment by xiaowanzixll** [comment]
是有导出功能，但为什么导出的txt文件跟fiddler不一样呢，都是被编码过了，有什么方式解码吗？

**Comment by avwo** [comment]
如果要fiddler读取，可以导出saz格式
![image](https://user-images.githubusercontent.com/11450939/95563196-aad96480-0a4f-11eb-95dd-12eb5ebd92aa.png)
