### ISSUE TITLE
mock无法保存value值

### ISSUE THREAD

**Issue by nmvjhd** [avwo/whistle#1040]
![image](https://github.com/avwo/whistle/assets/4507241/26684fe8-769b-4105-b87e-23ed5a45f3ec)
mock功能，使用key value保存时无法保存value值，保存成system file是好的，但是system file不如key value修改起来方便，希望给修复下。whistle版本是最新2.9.63

**Comment by avwo** [comment]
最新版支持在 Rules 编辑器里面 `按住Ctrl[Command] + 鼠标点击文件路径` 快速编辑临时文件和 Values
