### ISSUE TITLE
network的某个请求中，mock修改响应数据，默认选择存储在系统文件中，生成的temp文件夹在哪里呢？

### ISSUE THREAD

**Issue by lz1084342435** [avwo/whistle#1042]
![image](https://github.com/avwo/whistle/assets/31875849/8fa56305-ddfa-4989-b6f5-2fbd389c86fd)
mac系统，没有找到对应的文件夹，但是配置的规则确实生效

**Comment by avwo** [comment]
`~/.WhistleAppData/temp_files` 这里面的文件不要乱动
