### ISSUE TITLE
connect协议的http请求无法解析

### ISSUE THREAD

**Issue by firear** [avwo/whistle#1043]
如果不勾选“Capture TUNNEL CONNECTS”，目前无法解析connect协议的http请求。
可以类似Fiddler将“Capture TUNNEL CONNECTS”选项改为“Capture HTTPS Connections”.

不勾选时也可以解析connect协议的http代理请求,但不拦截tls协议，勾选时才拦截tls协议。

**Comment by avwo** [comment]
加个规则试试：
``` txt
* enable://forHttp
```

**Comment by firear** [comment]
> 加个规则试试：
> 
> ```
> * enable://forHttp
> ```

测了，web端还是只能看到connect。

**Comment by avwo** [comment]
`Capture TUNNEL CONNECTS` 这个要钩上

**Comment by firear** [comment]
勾上的话本来就可以正常拦截http，不用加规则；但是勾上同时会拦截https,我不想拦截https，因为客户端不可控他不信任我证书。
fiddler就没有这个问题。

**Comment by avwo** [comment]
钩上并在 Rules 配置规则 `* enable://forHttp` 试了吗

**Comment by firear** [comment]
> 钩上并在 Rules 配置规则 `* enable://forHttp` 试了吗

试了 果然可以 多谢大佬！
