### ISSUE TITLE
底部的日志过滤文本框能支持正则表达式过滤不，没有正则过滤日志太麻烦了

### ISSUE THREAD

**Issue by nmvjhd** [avwo/whistle#1044]
![image](https://github.com/avwo/whistle/assets/4507241/031087bc-28af-419c-a585-a862cc576b53)
请求过滤文本框是支持使用正则表达式过滤的，但是日志过滤文本框似乎不支持，需要同时过滤几条日志太麻烦了，希望能加入支持。

**Comment by avwo** [comment]
试试 `/xxx/i`

**Comment by nmvjhd** [comment]
![image](https://github.com/avwo/whistle/assets/4507241/44e4430d-5402-4cf6-a2dd-d731f9cbe86c)
见上图，就是这么写的，左边的可以，右边的不行

**Comment by avwo** [comment]
下个版本加上

**Comment by avwo** [comment]
已支持，重新安装 Whistle 并重启试试 `npm i -g whistle && w2 restart`
