### ISSUE TITLE
是否可以让whistle通过系统代理或指定代理访问网络？

### ISSUE THREAD

**Issue by XM-8JD2** [avwo/whistle#1045]
如题，我希望本地程序连接到whistle后可以通过指定的代理连接网络

同时还想请教一下是否有中文UI可用

**Comment by avwo** [comment]
https://wproxy.org/whistle/rules/proxy.html
https://wproxy.org/whistle/rules/socks.html
https://wproxy.org/whistle/rules/pac.html
