### ISSUE TITLE
websocket下如何自动解压数据流？websocket框架存在未知的bug？

### ISSUE THREAD

**Issue by NKajima** [avwo/whistle#1048]
当客户端、服务器设置的websocket头为：
Sec-WebSocket-Extensions | permessage-deflate

（deflate算法）

frames框架内侦测到被压缩的数据将不会自动解压同时任何信息都看不到（被压缩的也看不到 不知道是不是bug?）

在overview可查看到Compressed | Yes
![image](https://github.com/avwo/whistle/assets/37041791/c3ab5125-8a78-4c19-a093-d0ede6b379ba)

**Comment by avwo** [comment]
有外网链接吗

**Comment by NKajima** [comment]
> 有外网链接吗

我用其他的抓包软件（比如Charles）
是可以抓住来的，只是不会自动解压
需要自己写一个手动的deflate解压器

是可以正常解压出来的。

这个很明显是whistle有bug。
长度不为空，系统也真的到压缩了，但是hex，text看不到任何数据（空的），连被压缩前的都看不到
（我是抓的安卓app，代理到whistle）

**Comment by avwo** [comment]
抓包数据导出来看下

**Comment by avwo** [comment]
解析失败应该看不到后续的数据，把抓包数据导出发我看下

**Comment by NKajima** [comment]
![image](https://github.com/avwo/whistle/assets/37041791/20baf836-e100-4108-a503-faa9481e35f4)
[websocket_problem.txt](https://github.com/avwo/whistle/files/14632892/websocket_problem.txt)

here

**Comment by NKajima** [comment]
> 解析失败应该看不到后续的数据，把抓包数据导出发我看下

见上面回复

**Comment by avwo** [comment]
看了下应该是解压的问题，压缩数据不完整导致解压器一直在等待，你能不能把其它抓包工具获取的解压前二进制内容或base64文本发我

**Comment by avwo** [comment]
重新安装 Whistle 并重启 `w2 restart`，新版新增 `wss://xxx disable://wsDecompress` 禁止解压数据
