### ISSUE TITLE
公网ip+端口 报错 socket connect timeout

### ISSUE THREAD

**Issue by FoolYang** [avwo/whistle#1051]
我在一台云服务部署的whistle，启动后；
在我本地电脑访问 http://公网ip:8899，显示如下

From: whistle@2.9.66
Node: v16.20.2
Host: hwsg-xxxxxxx
Date: 3/19/2024, 10:03:02 PM
Error: socket connect timeout
    at retry (/usr/local/lib/node_modules/whistle/lib/inspectors/res.js:546:34)
    at Timeout._onTimeout (/usr/local/lib/node_modules/whistle/lib/inspectors/res.js:668:31)
    at listOnTimeout (node:internal/timers:559:17)
    at processTimers (node:internal/timers:502:7)
    
已知 
我本地电脑和云服务网络正常，8899端口也放开了；

通过 python3 -m http.server 8899 测试端口，本机是可以正常访问的；我认为 端口和网络是正常的；

但是本地电脑 curl -I http://公网ip:8899/，就返回502，具体如下
HTTP/1.1 502 Bad Gateway
content-type: text/html; charset=utf8
x-server: whistle
Date: Tue, 19 Mar 2024 09:24:59 GMT
Connection: keep-alive
Keep-Alive: timeout=5

辛苦帮忙看看，还有可能是什么原因，非常感谢～
（我在网络上查询，有人说检查下whistle的配置，但我没有找到配置文件，如果可以指出配置文件目录，也十分感谢～）

**Comment by avwo** [comment]
加个启动参数 `w2 restart -l "公网IP"`

**Comment by FoolYang** [comment]
@avwo 非常感谢，启动加参数后 可以打开页面了；
但是抓不到包，手机代理配置正常，就是没有任何请求；请问这个 可能是什么原因呢？

ps：主界面右上角 online选项  里面看起来是有数据的；但是没有请求显示出来

![20240320-105301](https://github.com/avwo/whistle/assets/28344942/41991d4c-f49c-4000-b673-ef2c073a998c)

**Comment by avwo** [comment]
Requests 不是为 0 吗？

**Comment by FoolYang** [comment]
@avwo 感谢回复；
request确实是0，total的158；但我手机确实设置代理了，就是没抓到请求；不知道是什么原因

还有一个背景是：
whistle部署在我自己的阿里云服务器，直接w2 start启动，我本地电脑就可以打开代理首页，也能正常抓包；
但部署在公司的华为云服务器，w2 start启动是打不开代理首页的，需要加 -l 公网ip的启动参数才行；而且首页过滤不到请求；不知道这两个有什么区别

**Comment by avwo** [comment]
1. All Requests 包含抓包界面的请求
2. 手机配置代理后浏览器请求正常吗

**Comment by FoolYang** [comment]
@avwo 手机配置代理后，浏览器显示网络异常；但我手机是已经安装了证书的，并且迁移到系统目录下了

**Comment by FoolYang** [comment]
知道原因了，是因为服务器限制了ip来源导致，感谢大佬知道～
