### ISSUE TITLE
whistle是否支持重定向功能?

### ISSUE THREAD

**Issue by zuibunan** [avwo/whistle#106]
目前whistle可以将请求转发到指定的地址
转发后返回的结果虽然是期望的内容
但是
页面的域名依然是转发前的域名

```
/http:\/\/test.com/(.*)/i  http://192.168.3.25/$1
```

如上配置，页面的域名依然是`test.com`，而不是`192.168.3.25`

在帮助文档中也没有找到redirect相关功能的说明

**Comment by zuibunan** [comment]
试了下，支持redirect，但是文档中没找到
```
/http:\/\/test.com/(.*)/i  redirect://http://192.168.3.25/$1
```

**Comment by avwo** [comment]
用最新版的whistle，也可以这么配：`^test.com/*** redirect://http://192.168.3.25/$1` ，这块文档这周会补上去
