### ISSUE TITLE
whistle作为socks server使用时，抓到的链接显示的都是IP

### ISSUE THREAD

**Issue by TangJhan** [avwo/whistle#1060]
whistle作为socks server使用时，抓到的链接显示的都是IP，有没有办法显示成域名的形式呢?
（1）启动whistle
`./whistle.js run -M socks --socksPort 9991`
（2）抓包的数据
![image](https://github.com/avwo/whistle/assets/22863892/cfaa67dd-45a7-4939-97d0-d52697135cf5)

**Comment by avwo** [comment]
配个规则：
``` txt
* enable://capture
```
