### ISSUE TITLE
访问任意端口打开的都是whistle，直接访问不走代理是正常的

### ISSUE THREAD

**Issue by aogg** [avwo/whistle#1065]
<img width="1050" alt="image" src="https://github.com/avwo/whistle/assets/8998031/3115aef0-6ab9-46c5-aa59-0bef17ca8e39">

走代理也是返回whistle， 输出
```
<!DOCTYPE html> <html> <head> <meta charset="UTF-8"> <meta name="google" value="notranslate"> <link rel="shortcut icon" href="img/favicon.ico" /> <title>Whistle Web Debugger</title> </head> <body style="overscroll-behavior-x: none;"> <div id="container" class="main"></div> <script src="js/index.js?v=2.9.41"></script> </body> </html>

```

docker部署下
如果启动一个全新的共享之前数据文件夹就没问题，如果还是之前的端口就有问题，就算关闭所有规则也是有问题

直接访问不走代理是正常的

**Comment by avwo** [comment]
whistle 内部请求是不是也走了系统代理？

**Comment by aogg** [comment]
容器下没有配置系统代理，

取消，其他相同，就变正常
--dnsServer 192.168.31.171 

容器下换个容器指定的端口也正常了

**Comment by aogg** [comment]
还有那些不正常的请求都是不会显示在请求列表上的

现在经过不断地变换容器和端口和参数，好像又正常

你这代理经常出现这情况啊，用了这么多年，经常偶发

**Comment by avwo** [comment]
什么是不正常请求？这个是你 Docker 设置问题，跟 Whistle 没关系，别乱设置系统代理

**Comment by aogg** [comment]
没有设置系统代理
