### ISSUE TITLE
插入一段 script 标签是否支持给标签添加 type 属性？

### ISSUE THREAD

**Issue by yiliang114** [avwo/whistle#1066]
使用方式：

![image](https://github.com/avwo/whistle/assets/11473889/12262d99-3291-4f7c-8c0f-6174091a5a9e)

如截图中的使用方式，会默认在 html 中添加一段 script 标签，但是似乎仅限于 script 标签，而不能为 script 标签添加 type、async 等属性

![image](https://github.com/avwo/whistle/assets/11473889/b5c87264-816e-4083-8f5b-7732d38203bd)

目前似乎还不支持？

https://github.com/avwo/whistle/blob/d8991cf569288e6979632477248ced28a46c9862/lib/inspectors/weinre.js#L9C5-L9C21

**Comment by avwo** [comment]
js 注入还不支持，可以试试 html 协议：https://wproxy.org/whistle/rules/htmlAppend.html

**Comment by yiliang114** [comment]
普通的 js 直接被 script 标签包裹嵌入没有问题，但是如果 js 代码中包含 import 之类的 es 代码，script 标签上需要带上 type="module" 才可以执行，否则嵌入的 js 执行就出错了。

**Comment by avwo** [comment]
下个版本加上，你先用 https://wproxy.org/whistle/rules/htmlAppend.html 嵌入

**Comment by yiliang114** [comment]
> 下个版本加上，你先用 https://wproxy.org/whistle/rules/htmlAppend.html 嵌入

🙇‍♂️

**Comment by avwo** [comment]
重新安装 Whistle 并重启，可以通过 `lineProps://module` 设置 type:
``` txt
https://xxx js://xxx lineProps://module
```
