### ISSUE TITLE
编码相异文件被同向处理导致乱码

### ISSUE THREAD

**Issue by Fredida** [avwo/whistle#1067]
配置规则`https://xxx.xxx file://yyy`，接着访问`https://xxx.xxx/index.html`，该文件为utf-8编码正常显示，而该文件用<script>标签引入的`https://xxx.xxx/aaa.js`却基于相异编码（比如GB18030），此时whistle向浏览器发送的response head中指定`charset=utf-8`，浏览器显示中文部分乱码，请问这个问题可以考虑为两者哪方的问题呢？

**Comment by avwo** [comment]
`https://xxx.xxx file://yyy resCharset://GB18030 `
