### ISSUE TITLE
自定义脚本中能否提供写入values的接口?

### ISSUE THREAD

**Issue by sangle7** [avwo/whistle#107]
想要修改body中指定字段, 目前方式是使用 reqScript 自定义一段脚本, 但在这个过程中遇到一些问题: 
rules.push('url reqBody://{key}'); 
这里只支持本地文件路径或是 values 中的 key , 但在脚本中只能读取 values 无法写入, 脚本中也无法require fs等模块...造成body无法替换的问题, 能否提供一个写入values的接口?

**Comment by avwo** [comment]
好用这个插件试试：https://github.com/whistle-plugins/whistle.script

**Comment by avwo** [comment]
新版版本已经支持：https://avwo.github.io/whistle/rules/reqScript.html
