### ISSUE TITLE
代理的接口有部分接口是404状态返回，确认接口没拼错

### ISSUE THREAD

**Issue by qq88310566** [avwo/whistle#1072]
<img width="495" alt="test" src="https://github.com/avwo/whistle/assets/22065972/4a9e77c1-def2-4f93-96b2-28392775e8db">

**Comment by avwo** [comment]
用 Whistle 抓包看下请求的 Server Ip

**Comment by qq88310566** [comment]
> 用 Whistle 抓包看下请求的 Server Ip
<img width="322" alt="1" src="https://github.com/avwo/whistle/assets/22065972/1d63b403-67f4-4c44-8fdb-accf0b1ce302">
这个serverIp是本地启动的服务器是不对的是吗

**Comment by qq88310566** [comment]
> 用 Whistle 抓包看下请求的 Server Ip

为什么服务器ip不对呢？怎么是本地的服务器ip，不是远程服务器的ip的

**Comment by avwo** [comment]
看下 Overview 匹配到什么规则，如果没有匹配到规则，看下系统的 hosts 文件配了什么

**Comment by qq88310566** [comment]
> 看下 Overview 匹配到什么规则，如果没有匹配到规则，看下系统的 hosts 文件配了什么

overview里面匹配到的是test.com 127.0.0.1:8080 
系统的hosts文件没有配东西
SwitchyOmega是
<img width="850" alt="2" src="https://github.com/avwo/whistle/assets/22065972/f17df69f-53ea-4924-b82b-db0b69dd09cf">

**Comment by avwo** [comment]
这是 whistle 规则里面配的

**Comment by qq88310566** [comment]
> 这是 whistle 规则里面配的

是我要增加这个忽略这个匹配规则
<img width="567" alt="3" src="https://github.com/avwo/whistle/assets/22065972/df148455-ade3-44ce-bd22-4399f897fc13">

**Comment by avwo** [comment]
看下：
1. 配置了哪些 Rules 
2. 安装了哪些插件

**Comment by qq88310566** [comment]
> 看下：
> 
> 1. 配置了哪些 Rules
> 2. 安装了哪些插件
规则是这样配置的
<img width="468" alt="4" src="https://github.com/avwo/whistle/assets/22065972/f866ff3f-5d01-49d8-84c6-b9306c70d8a1">

插件是安装了官网说的
<img width="1035" alt="5" src="https://github.com/avwo/whistle/assets/22065972/227b44be-7e19-4ced-979e-ba91ab0da70c">
<img width="1129" alt="6" src="https://github.com/avwo/whistle/assets/22065972/9da7e1f0-9262-4f39-b369-c3a98a0e4b1c">

**Comment by avwo** [comment]
先了解下怎么启停 whistle 规则
