### ISSUE TITLE
规则求教：匹配版本号

### ISSUE THREAD

**Issue by May-Sweet** [avwo/whistle#1073]
如下，可以匹配这个接口下所有的请求吗？（域名和版本号可能会变）
https://xxx.xxxapi.rabbit.com/3/8.0.77/commentapi/getSelfByBizKey
https://xxx.xxxapi.rabbit.com/1/8.0.78/commentapi/getSelfByBizKey

**Comment by avwo** [comment]
通配符 `^***/commentapi/getSelfByBizKey` 或正则 `/commentapi/getSelfByBizKey/`，如果需要获取后面的路径可以通过以下方式：
``` txt
^***/commentapi/getSelfByBizKey/*** file:///xxx/$1
或
//commentapi/getSelfByBizKey/(.*)/ file:///xxx/$1
```
参考：https://wproxy.org/whistle/pattern.html
