### ISSUE TITLE
【求助】android代理whistle，会出现图片、视频上传失败的情况，只要把代理关了就可以上传成功了

### ISSUE THREAD

**Issue by May-Sweet** [avwo/whistle#1074]
ps：ios连接whistle代理不会出现这种情况，并且只有android代理whistle有这种情况，我用charles代理android就不会出现图片视频上传失败的情况

**Comment by avwo** [comment]
估计是 ssl pinning 问题，Whistle 的 Network 上看下有没有 captureError

**Comment by May-Sweet** [comment]
有的，这个有什么办法解决吗大佬

**Comment by avwo** [comment]
看下是哪些域名，可以通过以下规则禁用 Capture：
``` txt
disable://capture 域名1 域名2
```

**Comment by May-Sweet** [comment]
这个禁用规则加在哪里呀，我放在Exclude Filter里可以吗

**Comment by May-Sweet** [comment]
感谢大佬，已经可以了

**Comment by May-Sweet** [comment]
再次感谢大佬～撒花～真的非常非常感谢～
