### ISSUE TITLE
华为鸿蒙可以安装whistle证书吗

### ISSUE THREAD

**Issue by May-Sweet** [avwo/whistle#1076]
我扫描whistle证书页面一直打不开

**Comment by avwo** [comment]
手机要先设置代理

**Comment by zhoujingchun** [comment]
> 我扫描whistle证书页面一直打不开

请问下解决了吗 我设置了代理 还是打不开

**Comment by avwo** [comment]
换个格式试试：

http://rootca.pro/cer

<img width="338" alt="image" src="https://github.com/user-attachments/assets/1cd13d42-7f32-4990-8eca-14f9fb39a57e">

**Comment by v2-lab** [comment]
https抓包有问题

**Comment by avwo** [comment]
细说

**Comment by lstoryc** [comment]
> https抓包有问题

我发现无法解析，有办法吗?

**Comment by avwo** [comment]
.cer 后缀也不行吗
