### ISSUE TITLE
whistle设置了代理之后手机说无法连接到互联网

### ISSUE THREAD

**Issue by hana2644** [avwo/whistle#1078]

**Comment by avwo** [comment]
安装根证书没：https://wproxy.org/whistle/webui/https.html

**Comment by hana2644** [comment]
> 安装根证书没：https://wproxy.org/whistle/webui/https.html

安装了的
<img width="351" alt="575fb93cf5e5d98eb731457737f7215" src="https://github.com/avwo/whistle/assets/59785766/fe6123ef-c4cb-4fbf-a7df-2b81d2755a37">

**Comment by avwo** [comment]
pc上是不是有多个ip，换个ip试试

**Comment by hana2644** [comment]
> pc上是不是有多个ip，手机代理配置换个ip试试

这两个都尝试了还是不行
<img width="716" alt="12e10af6d43a3b158dad005584cdc27" src="https://github.com/avwo/whistle/assets/59785766/07b9ad02-a97d-4eb0-aa09-b9afc79b2b28">

**Comment by avwo** [comment]
https://github.com/avwo/whistle/issues/272
https://github.com/avwo/whistle/issues/737

**Comment by hana2644** [comment]
> #272 #737

我设置成8080成功了，感谢
https://github.com/avwo/whistle/issues/78
