### ISSUE TITLE
2.9.70 版本rule（规则）优先级发生变化，在之前版本配置的规则失效

### ISSUE THREAD

**Issue by Fredida** [avwo/whistle#1079]
以下两条规则，配置顺序如下：
`/https://domain.com/path\d\d/filename file://X:\dir1\filename`
`https://domain.com file://X:\dir2`
在2.9.69版本中会安从上到下优先级依次变低的顺序进行匹配
而更新至2.9.70版本后本在最前优先级更高的正则规则被忽略，直接匹配了在下面的全domain规则，导致大量在2.9.69配置的规则失效。

**Comment by Fredida** [comment]
抱歉，又经过一番测试，发现是因为在Settings中选取了Back rules first导致的越下的规则越优先。

可以考虑修改一下描述吗？读到Back rules first时脑海中先想到的意思是Back(up) rules first，以为选取该项后每次修改规则会自动备份之前的旧规则。

**Comment by avwo** [comment]
`Back rules first` 的意思是后面的规则优先

**Comment by avwo** [comment]
可以重新安装，新版本加强了提醒
