### ISSUE TITLE
No such file or directory

### ISSUE THREAD

**Issue by Juskinbo** [avwo/whistle#1082]
# Environment
Macbook Pro M1 Pro
macOS 14.5
Whistle version: 2.9.71 (Installed from brew)
# Problem
When I enter `w2 proxy`, it will show this error.
<img width="622" alt="image" src="https://github.com/avwo/whistle/assets/54654557/332b7c94-6cd0-4ac1-bbd1-8aacd5198927">
But it doesn't affect the use.

**Comment by avwo** [comment]
用 npm i -g whistle 安装才能用 `w2 proxy`，brew 自动删除安装包里面的 x64 模块（虽然该模块也可以在 arm64 平台上运行，我再看下怎么解决）
