### ISSUE TITLE
/cgi-bin/get-data 的 ids 参数元素过多，导致 URI 地址过长 414 状态码

### ISSUE THREAD

**Issue by fjqingyou** [avwo/whistle#1084]
管理界面中出现了请求更新失败。

请求 URL:https://whistle.luyouqi.lan/cgi-bin/get-data?clientId=1716223098917-4&startLogTime=-2&startSvrLogTime=1716222225770-25&ids=1716223085375-287%2C1716223085755-288%2C1716223085866-289%2C1716223085986-290%2C1716223086102-291%2C1716223086220-292%2C1716223086340-293%2C1716223086464-294%2C1716223086583-295%2C1716223086699-296%2C1716223086812-297%2C1716223086930-298%2C1716223087049-299%2C1716223087171-300%2C1716223087295-301%2C1716223087407-302%2C1716223087562-303%2C1716223087795-304%2C1716223087969-305%2C1716223088148-306%2C1716223088309-307%2C1716223088518-308%2C1716223088681-309%2C1716223088830-310%2C1716223088938-311%2C1716223089046-312%2C1716223089154-313%2C1716223089263-314%2C1716223096426-315%2C1716223096825-316%2C1716223096943-317%2C1716223097079-318%2C1716223097208-319%2C1716223097324-320%2C1716223097446-321%2C1716223097560-322%2C1716223097681-323%2C1716223097797-324%2C1716223097913-325%2C1716223098031-326%2C1716223098478-329%2C1716223098602-330%2C1716223098731-331%2C1716223104276-332%2C1716223104405-333&startTime=1716223104405-333&dumpCount=0&lastRowId=1716223104405-333&logId=&count=20&_=1716223092287
请求方法:GET
状态代码:414 Request-URI Too Large
似乎 ids 元素过多了！

出现该问题时一般发生在短时间内发起了大量请求时。whistle 的管理端不再好像离线似的灰色掉了。需要重新 F5 刷新页面才能恢复！

**Comment by avwo** [comment]
这个是你们网关返回的吗

**Comment by fjqingyou** [comment]
我补充下我的使用环境
whistle 我是  -l whistle.luyouqi.lan 部署在了 openwrt 路由器中，路由器中还部署了 privoxy、nginx
电脑中 edge -> Proxy SwitchyOmega 扩展插件 -> privoxy -> 根据识别*.luyouqi.lan -> nginx -> 识别 whistle.luyouqi.lan 转发 whistle
实际是哪个环节返回的。晚上回去后我再验证下！

**Comment by avwo** [comment]
https://zhuanlan.zhihu.com/p/616704585

**Comment by fjqingyou** [comment]
通过隧道进行远程测试。在 nginx 中添加 client_header_buffer_size 1m; 配置之后确实解决了此问题！
感谢！

**Comment by avwo** [comment]
建议调小点（比如： 32k）避免 DDOS 攻击
