### ISSUE TITLE
Error: socket connect timeout

### ISSUE THREAD

**Issue by jarvislin94** [avwo/whistle#1086]
这是代理规则：

https://abc.com/api/ https://abc.com/api/
https://abc.com/ http://localhost:5174/
wss://abc.com/ ws://localhost:5174/

Omega插件：
![image](https://github.com/avwo/whistle/assets/12573233/574ee1b9-9b47-49d6-ba60-778a8f9d3ced)
![image](https://github.com/avwo/whistle/assets/12573233/095e7d76-9d50-46b4-8e33-5a62d79ed0a6)
![image](https://github.com/avwo/whistle/assets/12573233/e397eefa-d35b-42a0-a2f4-3f952fd6ce4e)

问题：
每次 https://abc.com/api/xxx 的请求都会报Error: socket connect timeout，偶尔几次能通。其它 https://abc.com/xxx 的请求正常。帮忙看一下🙏
![image](https://github.com/avwo/whistle/assets/12573233/d078a7a1-87f0-4214-9e51-c28f12d891cd)

**Comment by avwo** [comment]
你机器网络问题

**Comment by JackZong** [comment]
> 你机器网络问题

应该不是，换了个代理工具是可以的

**Comment by avwo** [comment]
先把 SwitchyOmega 设置成直接请求，再用 Chrome 访问  https://abc.com/api/xxx  试试

**Comment by JackZong** [comment]
> 先把 SwitchyOmega 设置成直接请求，再用 Chrome 访问 https://abc.com/api/xxx 试试

直接请求可以访问

**Comment by avwo** [comment]
你电脑有安装什么监控软件没，如果有确认下会不会对 node 进程造成干扰

**Comment by JackZong** [comment]
> 你电脑有安装什么监控软件没，如果有确认下会不会对 node 进程造成干扰

好像只有一个clash

**Comment by avwo** [comment]
clash的端口是什么

**Comment by JackZong** [comment]
> clash的端口是什么

export https_proxy=http://127.0.0.1:7890 http_proxy=http://127.0.0.1:7890 all_proxy=socks5://127.0.0.1:7890

7890

**Comment by avwo** [comment]
Whistle 配个规则试试 `* proxy://127.0.0.1:7890`
