### ISSUE TITLE
请问 resReplace 的 Values中 如果想将”a: 1“ 替换成”a: 2“ 要如何处理

### ISSUE THREAD

**Issue by fuxichen** [avwo/whistle#1089]
请问 resReplace 的 Values中 如果想将”a: 1“ 替换成”a: 2“ 要如何处理
我试了下，Values中写
```json5
{
"a": "aReplace", // 可以替换
"a:": "aReplace", // 可以替换
"a: ": "aReplace", // 不可以替换， 比前面多了个空格
"a: 1": "aReplace", // 不可以替换
}
```

**Comment by avwo** [comment]
看下 body 里面的原始内容长什么样的，`resReplace://pattern=value` 跟 js 里面的 `str.replace(pattern, value)` 逻辑类似。

**Comment by fuxichen** [comment]
> 看下 body 里面的原始内容长什么样的，`resReplace://pattern=value` 跟 js 里面的 `str.replace(pattern, value)` 逻辑类似。

非常抱歉，是我的问题，我在whistle中下载了原始内容是"a:1"没有空格，浏览器控制台开了格式化，导致我看到的是“a: 1”。
谢谢
