### ISSUE TITLE
whistle不设置代理，直接作为mock服务器调用，可以使用https吗

### ISSUE THREAD

**Issue by Shawn1** [avwo/whistle#1092]
whistle不设置代理，直接使用ip和端口请求作为mock服务器使用时，怎么设置https域名？
或者说怎么解决在https项目中，调用whistle的http接口，被拦截的问题。

**Comment by avwo** [comment]
Whistle 支持作为 https server 使用：
``` sh
w2 restart --httpsPort 443
```
试试看能不能满足需求，但推荐通过代理访问。

**Comment by Shawn1** [comment]
好的，感谢。我试试
