### ISSUE TITLE
Mac电脑开启梯子VPN后，代理不生效

### ISSUE THREAD

**Issue by Eacolt** [avwo/whistle#1094]
Mac M1笔记本macbook pro，安装whistle独立的程序，开启whistle后，查看mac上的网络-代理，发现网页代理的端口被覆盖为8899，这时候是可以代理成功的，可是一旦开启我的VPN梯子，系统网页代理又被覆盖为梯子的端口了，这时候就代理都失败了，如何解决？

**Comment by avwo** [comment]
用了什么 vpn 客户端？

**Comment by avwo** [comment]
系统代理或浏览器代理跟 vpn 冲突可以这么处理：请求 -> Chroe 插件或系统代理 -> Whistle - 配置 proxy 或 socks -> VPN。
或自己网上搜解决方法
