### ISSUE TITLE
想删除请求url的某个字段，规则怎么写？

### ISSUE THREAD

**Issue by xiaowanzixll** [avwo/whistle#1095]
举个列子，比如：想去掉请求url的sign=8029db12345，规则怎么写？
test.com/api/abc?ts=17176&nonce=FFF&sign=8029db12345

期望发出的请求是：
test.com/api/abc?ts=17176&nonce=FFF

**Comment by xiaowanzixll** [comment]
或者把sign=8029db12345  替换成其它字段：如test.com/api/abc?ts=17176&nonce=FFF&sign1=3452242也行

**Comment by avwo** [comment]
试试：
1. `test.com/api/abc urlParams://sign=`
2. `test.com/api/abc pathReplace://(/sign[^&]+/=)`

参考：
https://wproxy.org/whistle/rules/urlParams.html
https://wproxy.org/whistle/rules/pathReplace.html

**Comment by avwo** [comment]
最新版本支持 `test.com/api/abc delete://query.sign`

**Comment by yao206cc** [comment]
如果是路径呢 如何使用delete://path?

**Comment by avwo** [comment]
路径用替换即可 `a.b.c/path1/to1 a.b.c/to1`
