### ISSUE TITLE
关于 Weinre 的 `httpSocket._sendQueued is not a function` 报错

### ISSUE THREAD

**Issue by cp0725** [avwo/whistle#1097]
mac 客户端，开启了 Weinre 调试，出现如下错误，有没有朋友遇到相似情况，怀疑是node版本问题，顺便问下 whistle 的 mac 客户端可以制定 node 版本吗？
![image](https://github.com/avwo/whistle/assets/21350916/9fd48997-ec1a-48df-934f-d63fd4905c87)

**Comment by avwo** [comment]
不支持，node 版本是集成在 electron 里面的，我看下我这边能不能重现

**Comment by avwo** [comment]
更新下客户端试试
