### ISSUE TITLE
SSE mock support

### ISSUE THREAD

**Issue by RichDavidMu** [avwo/whistle#1099]
Is there any plan to provide SSE mock support ?

**Comment by avwo** [comment]
看下这个插件能不能解决你的问题：https://github.com/whistle-plugins/whistle.vase

**Comment by avwo** [comment]
vase:
<img width="357" alt="image" src="https://github.com/user-attachments/assets/d21589f2-b808-4662-98ae-909bc86730d8">

Rules:
<img width="331" alt="image" src="https://github.com/user-attachments/assets/174a5f29-9b02-4c93-9e5f-fd9fe3276117">

效果：
<img width="363" alt="image" src="https://github.com/user-attachments/assets/6ee79642-44ba-4bcb-86e1-bb1cf977e27a">

**Comment by zjians** [comment]
https://www.npmjs.com/package/whistle.sse-mock
这个插件直接可以mock sse这种的流式数据
