### ISSUE TITLE
Network 面板只能抓到 CONNECT 请求

### ISSUE THREAD

**Issue by leozdgao** [avwo/whistle#11]
![image](https://cloud.githubusercontent.com/assets/8381024/19042487/d8b33c0c-89be-11e6-92b7-426530892da6.png)

![image](https://cloud.githubusercontent.com/assets/8381024/19042531/fbcb7b96-89be-11e6-8f88-0c4ddc9ae4c0.png)

**Comment by avwo** [comment]
安装下根证书后开启拦截https 
https://whistle.gitbooks.io/help/content/webui/https.html

**Comment by leozdgao** [comment]
已解决
