### ISSUE TITLE
node 20.11.0 安装whistle报错

### ISSUE THREAD

**Issue by YuYongzhi** [avwo/whistle#1103]
» npm i -g whistle

changed 118 packages in 1s

12 packages are looking for funding
  run `npm fund` for details
thread 'main' panicked at src/run/npm.rs:160:54:
called `Result::unwrap()` on an `Err` value: Error { kind: PermissionDenied, message: "Permission denied (os error 13)" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by tangzixuan** [comment]
我在用node20版本环境也有问题，试着用node v16版本，我是ok的

**Comment by avwo** [comment]
权限问题，重新安装 node 试试，或者用 `sudo npm i -g whistle`（慎用）
