### ISSUE TITLE
有无命令或者API可以获取到当前激活的规则

### ISSUE THREAD

**Issue by fantian007** [avwo/whistle#1105]
rules 列表有很多 rules，想知道当前被激活的是哪个

**Comment by fantian007** [comment]
还有 Enable, Disable 的能力 可以通过 控制台命令 来调用吗？

**Comment by avwo** [comment]
两种实现方式：
1. 通过 cgi：`http://127.0.0.1:8899/cgi-bin/rules/list` 获取规则列表，这个需要知道 Whistle 的 IP和端口
2. 通过安装插件获取 https://github.com/avwo/whistle/blob/master/lib/plugins/load-plugin.js#L1553 ，插件再写到本地，或提供接口、命令行命令等方式

**Comment by fantian007** [comment]
`typescript
const  ret = whistle({
      port: this.port,
      httpPort: this.httpPort,
      httpsPort: this.httpPort,
      uiport: this.port,
      allowMultipleChoice: false,
      baseDir: this.baseDir
    });
`
这种方式启动服务之后，怎么停止服务？

**Comment by avwo** [comment]
建议用 https://github.com/avwo/pfork 起一个独立进程运行 whistle，参考 nohost 的实现：https://github.com/Tencent/nohost/blob/master/lib/main/whistleMgr.js
