### ISSUE TITLE
"Accept-Encoding" 丢失，导致minio返回400

### ISSUE THREAD

**Issue by devraw** [avwo/whistle#1107]
Minio的请求会使用Accept-Encoding作为签名参数，经过whistle代理时，Accept-Encoding请求头缺失，导致返回400，希望尽可能保留原始的请求参数

![image](https://github.com/avwo/whistle/assets/46481086/c4062f7f-f1f1-4507-b1bd-90e002ccab61)

![image](https://github.com/avwo/whistle/assets/46481086/8bbf24b2-6f72-4ae3-a471-784510e56627)

**Comment by avwo** [comment]
可以，下个版本做下调整

**Comment by avwo** [comment]
更新whistle试试

**Comment by devraw** [comment]
可以了，感谢
