### ISSUE TITLE
更新了最新版本，但第二天来变成了1.6版本（版本自动回退）

### ISSUE THREAD

**Issue by jxDeveloper** [avwo/whistle#111]
遇到了两次这样，我明明更新到最新版本了，但是下次打开，就会弹出框，说我的版本还是1.6，需要更新。而且两次都是说我的版本是1.6。启动的时候，也是显示1.6 started。

**Comment by avwo** [comment]
可能原因是你更新过Node导致npm的全局目录变了，whistle安装到新目录，但老目录的whistle及其命令行文件还存在导致 `w2 restart` 找到老目录的模块，你可以用 `which w2` (如果是Windows用git bash)找到 `w2` 命令对应的文件，把该文件删掉即可。

**Comment by jxDeveloper** [comment]
@avwo 非常感谢，是我装了6.11.3和8.9.3两个版本的node，切换node版本时，造成了这种问题。在6.11.3的node下启动w2是最新版的，可能我当初是该node下更新的？切换到8.9.3的node下启动w2时，w2为1.6版本。而且w2的路径也不同
