### ISSUE TITLE
证书相关问题咨询

### ISSUE THREAD

**Issue by fantian007** [avwo/whistle#1111]
证书有效期是10 年吗？
证书过期了用 w2 ca 会安装新证书吗？
未过期的话，w2 ca 也会安装一个新的证书吗？
可以自定义证书有效期吗？
socket 代理 是通过 Socks 代理？Http 代理？

-------
还有大佬知道怎么检测 whistle 的证书到底安装到系统里没有？用什么方法检测呢？

**Comment by avwo** [comment]
1. 根证书有效期是 10 年，10年后如果过期，重新安装 Whistle 并重启 + `w2 ca` 可以重新安装根证书
2. 普通证书有效期1年
3. Whistle 没有检测系统是否安装根证书，具体如何检测我也没去了解过

**Comment by fantian007** [comment]
socket 可以转发吗？是走的 Socks 代理吗？

**Comment by fantian007** [comment]
如果想转发、操作 https 数据，安装了普通证书，还需要根证书吗？

**Comment by avwo** [comment]
不需要，可以通过 `HTTPS > View all custom certificates` 菜单上传证书
<img width="415" alt="image" src="https://github.com/user-attachments/assets/f3e5bc91-5c2d-4ea9-8180-816a24bcbe70">

**Comment by fantian007** [comment]
whistle 会为每个请求动态生成证书吗？证书的域名那就是动态的。
如果 -z 加载自定义证书，是不是就只能对固定的域名进行代理了，不能对随便一个域名进行代理了？

**Comment by avwo** [comment]
可以，支持用自己的根证书，名字命名为 `root.key` 和 `root.crt` 即可
