### ISSUE TITLE
可以提供点击页面元素打印log的功能吗

### ISSUE THREAD

**Issue by May-Sweet** [avwo/whistle#1116]
比如：点击提交按钮，控制台可以打印自定义的“mock提交点击log”

**Comment by avwo** [comment]
哪个页面，最好截个图

**Comment by May-Sweet** [comment]
<img width="1145" alt="image" src="https://github.com/user-attachments/assets/8ed331fa-5d49-432d-b6ee-cba30ffc8dd2">
现在的实现好像是以页面维度来的，可以细化到，针对页面的某个点击事件做log打印吗？
比如一个登录页面的“登录”按钮，可以自定义一个click事件的log

**Comment by avwo** [comment]
这个可以通过 jsPrepend 注入 js 自己实现
