### ISSUE TITLE
停止的时候自动关闭系统代理

### ISSUE THREAD

**Issue by weitfly** [avwo/whistle#1117]
在 windows 上启用代理：`w2 start --init` ，此时会自动打开手动设置代理，如下图：
<img width="595" alt="image" src="https://github.com/user-attachments/assets/12e9a905-c459-4b18-87cb-bc6a8c3f204a">

但是在 `w2 stop` 时并没有自动关闭代理服务器，仍然是开启状态：
<img width="593" alt="image" src="https://github.com/user-attachments/assets/52b801ec-0faf-499c-9a45-12f23df1cd05">

关闭后如果不手动去设置里关闭代理服务器，就导致无法上网，建议可以在停止时自动关闭代理服务器，体验更优：
<img width="594" alt="image" src="https://github.com/user-attachments/assets/45fee24f-ea3c-4233-a550-aa0a266f67b5">

**Comment by avwo** [comment]
可以通过命令行 `w2 proxy 0` 或直接使用客户端：https://github.com/avwo/whistle-client
