### ISSUE TITLE
localhost destination didn't work properly on dual stack network

### ISSUE THREAD

**Issue by fython** [avwo/whistle#1118]
## Problems

Example whistle rules:

```
xxx.yyy.com/example/ localhost:30473
```

While I'm on an IPv4/v6 dual stack network, rules with `localhost` destination didn't
work properly. It shows connect ECONNREFUSED 127.0.0.1:30473 like the following screenshot:

<img width="556" alt="image" src="https://github.com/user-attachments/assets/0e8fe542-57fa-4aab-a5ce-9357e0550231">

And I can't see any incoming request logs in target vite server debug logs (`vite serve --debug`).

If I access `localhost:30473` in the Chrome browser directly, it just works normally. 
 (`127.0.0.1:30473` doesn't work)

BTW, the contents of my `/etc/hosts`:

```
127.0.0.1	localhost
255.255.255.255	broadcasthost
::1             localhost
```

### Attempts

I tried to replace `localhost` with `[::1]` IPv6 loopback address in destination like this:

```
xxx.yyy.com/example/ [::1]:30473
```

It fixed in my case!

### Expect

Maybe there is a problem here that make whistle/Node.js unable to handle these requests on an IPv4/v6 dual stack network.

Is it possible to make `localhost` domain in destination work normally?

## Environments

- OS: macOS Sonoma 14.4.1 (Apple Silicon)
- Node.js: v20.15.1
- Browser: Chrome 126.0.6478.183 (arm64)
- whistle: 2.9.79 (installed by pnpm)

**Comment by avwo** [comment]
https://nodejs.org/docs/latest/api/dns.html#dnslookuphostname-options-callback

<img width="800" alt="image" src="https://github.com/user-attachments/assets/c46d7490-4faa-4fd8-8603-8ad4776f04c0">


<img width="800" alt="image" src="https://github.com/user-attachments/assets/ed18fe9d-13fb-4b66-ae15-a192384f7176">

**Comment by fython** [comment]
@avwo Thanks! I will try this setting later. Looks like it explains my situation perfectly.

**Comment by fython** [comment]
<img width="285" alt="image" src="https://github.com/user-attachments/assets/9169aca6-6889-4f6f-a7c5-2d984894bbc0">

I found that "IPv6-first network" option is unavailable on my MacBook.

**Comment by avwo** [comment]
Node >= `22.1.0` is required
