### ISSUE TITLE
100 秒左右这里是有个超时吗？

### ISSUE THREAD

**Issue by yangg** [avwo/whistle#1119]
![image](https://github.com/user-attachments/assets/6627a6ab-ac1b-4918-9a19-fe36cbc75975)
![image](https://github.com/user-attachments/assets/1adad120-e577-482f-9a4f-f57700116e7e)
[error.txt](https://github.com/user-attachments/files/16402878/error.txt)

```
# Revese proxy ollama to catpure traffic
ollamaproxy.com http://192.168.0.206:11434
```

现在是反代 ollama的，想查出输出有没问题及usage,结果很多这种，请问下 100 秒时是不是默认超时了，不用代理时日志里显示半个小时的都有，所以本身 100 秒没有超时的

**Comment by avwo** [comment]
默认是超过 6 分钟没有数据流动算超时，你这种像是客户端主动 abort 掉的

**Comment by yangg** [comment]
> 默认是超过 6 分钟没有数据流动算超时，你这种像是客户端主动 abort 掉的

好的，请问下这个 6 分钟有配置吗？

**Comment by avwo** [comment]
通过命令行可以修改，但不建议去动它，你的问题跟这个没关系
