### ISSUE TITLE
2.9.80版本好像会导致微信提示网络不稳定

### ISSUE THREAD

**Issue by meteor0027** [avwo/whistle#1121]
升级到2.9.80版本，IOS微信会提示网络不稳定红色横幅，我几台苹果手机都是这样，重新降级到2.9.79后，恢复正常了，不知道是不是个例

**Comment by meteor0027** [comment]
抓包无报错

**Comment by meteor0027** [comment]
微信提示网络不稳定红色横幅，收发普通消息是可以的，但是我发现微信里面的服务通知消息收不到，关闭代理后立即可以收到

**Comment by avwo** [comment]
我这边试了没问题，你换回 2.9.80 看下有没有 Tunnel to 的请求

**Comment by avwo** [comment]
更新 Whistle
