### ISSUE TITLE
【建议】URL可以选择只显示路径，不显示参数

### ISSUE THREAD

**Issue by MrSongzj** [avwo/whistle#1123]
GET 请求的 URL 显示了路径和参数，通过肉眼很难快速找到想要观察的 URL（一般通过路径的最后的部分来查找）。
而且个人觉得在 URL 部分显示参数意义不大，因为正常来说都会通过右侧的详细面板来查看。
希望可以添加一个开关来控制URL是否显示参数，或者 URL 就不显示参数。
![企业微信截图_a1a647fb-4bd8-402b-8607-68d2be8482b7](https://github.com/user-attachments/assets/2f5fdf63-618c-4804-b83f-1eca0d527ac9)

**Comment by avwo** [comment]
安装最新版本并重启，可以通过 Network / Settings 设置：

<img width="610" alt="image" src="https://github.com/user-attachments/assets/c86b1276-c33d-4cf4-b8f4-d95b86fa62e8">
