### ISSUE TITLE
Network 界面能不能去掉额外功能，只保留列表展示

### ISSUE THREAD

**Issue by fantian007** [avwo/whistle#1124]
![image](https://github.com/user-attachments/assets/10db3ad8-c2c9-4f59-852f-43da35dc625d)
如图，想去掉红色的部分，保留列表和右侧面板，想嵌入 iframe 中使用，只查看

能不能 url 上加个参数，例如：http://localhost:9001/#network?sample=1 ，这样

**Comment by avwo** [comment]
启动 network 模式：`w2 restart -M network`

**Comment by fantian007** [comment]
能不能将 
![image](https://github.com/user-attachments/assets/a352d90f-4138-4bc9-8d84-367184bec8f8)
这部分也去掉

**Comment by avwo** [comment]
去掉这些你怎么导出导入，开启解析 https 请求

**Comment by fantian007** [comment]
通过 whistle.js 启动设置的参数，后台进程设置好了，就是嵌入界面查看一下抓包，不需要其它操作了

**Comment by avwo** [comment]
试试 `http://localhost:9001/?hideMenus=1#network `

**Comment by fantian007** [comment]
可以了，大佬🐂啊
