### ISSUE TITLE
升级至v2.9.81后无法代理HTTPS，证书未生效

### ISSUE THREAD

**Issue by kanchenhao** [avwo/whistle#1128]
从v2.9.67升级至v2.9.81无法进行HTTPS代理，证书未生效，回退至v2.9.67版本可以正常使用

node版本：v18.14

**Comment by avwo** [comment]
报什么错

**Comment by kanchenhao** [comment]
哪里可以查看报错日志，whistle.log中没有相关日志

**Comment by avwo** [comment]
看下抓包列表有报错吗

**Comment by avwo** [comment]
看下抓包列表有报错吗

**Comment by kanchenhao** [comment]
network面板没有抓到请求，明天去公司再看下

**Comment by liyipeng3** [comment]
同问，类似的问题，是https+ip，好像2.9.81不会走代理了，看在2.9.82加了标志位，想问下应该怎样开启？

**Comment by avwo** [comment]
`* enable://captureIp`

**Comment by liyipeng3** [comment]
> `* enable://captureIp`

get，谢谢

**Comment by avwo** [comment]
> ![image](https://private-user-images.githubusercontent.com/525478/368411400-5f056589-053b-49cc-b41e-5fdb9a5a1b15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MzE5ODIsIm5iZiI6MTcyNjYzMTY4MiwicGF0aCI6Ii81MjU0NzgvMzY4NDExNDAwLTVmMDU2NTg5LTA1M2ItNDljYy1iNDFlLTVmZGI5YTVhMWIxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwMzU0NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYzlkODNjZTlhNmFiYzA2M2FjMTUyMTRjNmMxNWFhNjdjODk1ODFmZWU0MTFlNjllNWZkYzk0NDczYzVkMzQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T11fiui15oAFr17SLNPG_c58pq5sQVkzOgB4oW8X6YQ) 这就是没有开启captureIp吗？能否默认就开启啊

更新下 whistle

**Comment by mapleshadow** [comment]
> > ![image](https://private-user-images.githubusercontent.com/525478/368411400-5f056589-053b-49cc-b41e-5fdb9a5a1b15.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY2MzE5ODIsIm5iZiI6MTcyNjYzMTY4MiwicGF0aCI6Ii81MjU0NzgvMzY4NDExNDAwLTVmMDU2NTg5LTA1M2ItNDljYy1iNDFlLTVmZGI5YTVhMWIxNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE4JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxOFQwMzU0NDJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYzlkODNjZTlhNmFiYzA2M2FjMTUyMTRjNmMxNWFhNjdjODk1ODFmZWU0MTFlNjllNWZkYzk0NDczYzVkMzQxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.T11fiui15oAFr17SLNPG_c58pq5sQVkzOgB4oW8X6YQ) 这就是没有开启captureIp吗？能否默认就开启啊
> 
> 更新下 whistle

可以了，正常了
