### ISSUE TITLE
子路径、子域名

### ISSUE THREAD

**Issue by GitHub4LP** [avwo/whistle#1129]
能否帮助一下，子路径变成子域名、子域名变成子路径该怎么做

另外header中以:开始结尾的header键怎么转发时丢了

**Comment by avwo** [comment]
第一个问题没看明白，h2 中冒号开头的请求或响应头没有丢失，统一按普通 http 协议招人，

**Comment by GitHub4LP** [comment]
> 第一个问题没看明白，h2 中冒号开头的请求或响应头没有丢失，统一按普通 http 协议显示，

example.com/a/b/c?x=x&y=y  变成 c.b.a.example.com/?x=x&y=y

c.b.a.example.com/?x=x&y=y  变成  example.com/a/b/c?x=x&y=y

**Comment by avwo** [comment]
配置规则 `example.com/a/b/c c.b.a.example.com` 即可
