### ISSUE TITLE
Response data too large to show

### ISSUE THREAD

**Issue by Wangggym** [avwo/whistle#1131]
![image](https://github.com/user-attachments/assets/2f5aaadb-9687-4931-aac0-3cb54630353a)

**Comment by avwo** [comment]
可以通过规则`* enable://bigData` 放开上限，不过慎用

**Comment by Wangggym** [comment]
这个是占内存吗？ @avwo

**Comment by avwo** [comment]
会增加内存占用，可以缩小作用范围 `domain enable://bigData`

**Comment by Wangggym** [comment]
<img width="748" alt="image" src="https://github.com/user-attachments/assets/61329ca6-b6c6-4dc8-b56e-d8fa3da2dde5">
clear 会直接清除内容占用？^

**Comment by avwo** [comment]
会清除浏览器的内存占用，代理有自己的清理机制
