### ISSUE TITLE
npm下载不成功了，有个依赖版本找不到

### ISSUE THREAD

**Issue by xiaoy4007** [avwo/whistle#1132]
现在npm下载不成功了，有个依赖版本找不到No matching version found for basic-auth@1.0.0 能解决一下吗

**Comment by avwo** [comment]
没依赖这个npm包，把错误信息发出来看下

**Comment by xiaoy4007** [comment]
![image](https://github.com/user-attachments/assets/d7a90da7-53fe-439d-a635-cbbe85d76aa6)
这个，你看看

**Comment by xiaoy4007** [comment]
找到问题了，镜像源的问题
