### ISSUE TITLE
配置了全局的whistle代理，结果连接不到docker中的数据库了

### ISSUE THREAD

**Issue by mhpsy** [avwo/whistle#1134]
![image](https://github.com/user-attachments/assets/fb7d8d31-eca0-4794-8a43-73c78e277848)

这是我系统代理

![image](https://github.com/user-attachments/assets/f2747ca6-6eb9-4790-931a-7453d3a57fec)

这是我用docker启动的postgresql数据库

然后我有配置一个规则 全部转发到clash
* socks://127.0.0.1:7890

结果就是我现在本地无法用localhost连接到docker启动的数据库

**我如果给本机的代理直接指向clash，不使用whistle就可以连接到**

我不清楚该如何排查，我可以提供更多的信息，但是我不知道该如何提供，有需要的信息可以讲

**Comment by avwo** [comment]
Whistle可以抓到数据库的请求吗

**Comment by mhpsy** [comment]
> Whistle可以抓到数据库的请求吗

按理说数据库的通讯没有走http之类的(我一直以来的认知，没有求证)

我也不清楚问题出在哪里，我使用的是https://hub.docker.com/_/adminer这个去链接的数据库

我现在放弃折腾了，换了其他的方式没有在使用whistle了。
