### ISSUE TITLE
mac系统配置全局代理不生效

### ISSUE THREAD

**Issue by ssunwanru** [avwo/whistle#1135]
使用node安装最新版的2.9.82，以及使用客户端https://github.com/avwo/whistle-client/releases 的1.2.5版本都不行
操作系统：macOS Sonoma 14.5

配置：
![image](https://github.com/user-attachments/assets/026ae808-6ad2-4858-ae3d-6fb7eee86abb)
![image](https://github.com/user-attachments/assets/05d3dbe8-576b-4fd7-b571-ce03990ed9db)

使用SwitchyOmega，通过浏览器访问可以生效

帮忙指引下～

**Comment by EOMHH** [comment]
请问 这边解决了吗？ 我也遇到这个问题了

**Comment by LauGaHo** [comment]
我也是遇到这个问题，全局代理不生效在 MacOS 中

**Comment by avwo** [comment]
设置不成功都是这个系统版本吗

**Comment by LauGaHo** [comment]
我是 Sonoma 14.6 版本

**Comment by ssunwanru** [comment]
还没有解决

**Comment by avwo** [comment]
等我找台 Sonoma 14.6 版本的机器看下

**Comment by avwo** [comment]
我这边升级到 15 也是可以正常设置代理

**Comment by ssunwanru** [comment]
请教下，全局代理的效果，预期应该是ping或者程序里去请求某个域名，这种场景都可以走到代理是吗？

**Comment by avwo** [comment]
PC 浏览器一般都可以，ping 不行，客户端请求不一定可以（要看客户端是否有支持走系统代理）
