### ISSUE TITLE
safari 代理

### ISSUE THREAD

**Issue by LauGaHo** [avwo/whistle#1136]
我通过 `w2 proxy` 设置了全局代理，然后想通过 Safari 测试一下是否走了全局代理，但是还是不行，但是我在 chrome 中使用 omega 确实可以的，想知道如何为 Safari 设置

**Comment by avwo** [comment]
应该会走系统代理，这个自己网上搜下

**Comment by LauGaHo** [comment]
> 应该会走系统代理，这个自己网上搜下

w2 proxy 不是设置系统代理的吗？

**Comment by avwo** [comment]
Mac 吗，我这边是正常的，看下系统的 HTTP 和 HTTPS proxy 有没有都设置成功
