### ISSUE TITLE
麻烦支持下换行，如果规则过长就需要了

### ISSUE THREAD

**Issue by aogg** [avwo/whistle#1138]
最后如果有\就代表当前行未结束，这样子

**.proxy_sslip.**.sslip.io http://qwe-proxy.common-all:80 reqHeaders://`host=${reqHeaders.host}` excludeFilter://exclude.**.192.168.22.1.sslip.io excludeFilter://**.122.222.0.210.sslip.io  excludeFilter://**.10.5.5.1.sslip.io excludeFilter://**.192.168.131.*.sslip.io

**Comment by avwo** [comment]
当行太长可以写成下面这种（会自动通过空格拼接成单行）：
``` txt
line`
xxxxx
xxxxx
xxxxx xxxx
xxxxx
xxx xxxx
`
```

**Comment by aogg** [comment]
成功，必须line`没有空格，而且没有语法提示
