### ISSUE TITLE
已经停止抓包，结果还是不断的请求，不合理

### ISSUE THREAD

**Issue by aogg** [avwo/whistle#1139]
<img width="1436" alt="image" src="https://github.com/user-attachments/assets/b25e00fb-09dc-4401-8491-3d5202372fed">

**Comment by avwo** [comment]
这个不仅仅是获取抓包数据，还有插件、系统等信息

**Comment by aogg** [comment]
他一直请求影响我看日志，而且正常不关闭窗口的，一直请求，nodejs不是天生支持ws的吗？要不改改

**Comment by aogg** [comment]
而且每次当前浏览器打开全局代理，每次都给你自己的请求占用日志列表，每次新应用都需要排除这个请求路径

**Comment by avwo** [comment]
只能手动排除下

**Comment by aogg** [comment]
是二次代理到别的代理，别的代理可没日志排除，麻烦很多
