### ISSUE TITLE
建议：ca证书可以做成magisk模块的方式吗，方便android手机使用

### ISSUE THREAD

**Issue by mapleshadow** [avwo/whistle#1141]
有几个好处，一是突破例如miui等系统限制，直接让证书成为根证书。二是安全，用的时候开启，不用的时候可以关闭，不需要导入、卸载等操作。
目前安卓系统的reqable调试工具就是采用的这种方式

**Comment by avwo** [comment]
这个怎么操作？

**Comment by avwo** [comment]
这个不需要 Whistle 特殊处理，执行下载证书后，按照这个文档操作即可：https://blog.csdn.net/chiehfeng/article/details/134033846
