### ISSUE TITLE
2.9.83 无法保存规则、值，无法修改插件，提示403

### ISSUE THREAD

**Issue by devraw** [avwo/whistle#1143]
![image](https://github.com/user-attachments/assets/4592bcaa-a6c5-43c5-806e-8e99d1be2530)
![image](https://github.com/user-attachments/assets/152bf9a1-1e3c-4f52-be8b-b1c041b5e3ce)
![image](https://github.com/user-attachments/assets/450c0f09-b325-4d38-8cb6-6a3d069bb09a)

无法创建规则，操作全部提示403

**Comment by MrLeo** [comment]
+1

**Comment by devraw** [comment]
> 重新下载客户端并安装：https://github.com/avwo/whistle-client/releases/tag/v1.2.6

可以了

**Comment by avwo** [comment]
再重新安装下，1.2.6 版本依赖的 Whistle@2.9.84 有 bug
