### ISSUE TITLE
升级到最新版后无法代理本地前端项目（localhost）

### ISSUE THREAD

**Issue by imwangpan** [avwo/whistle#1145]
whistle 版本 2.9.83
Node: v20.15.0

报错信息：
Error: connect ECONNREFUSED 127.0.0.1:10087
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1606:16)

前端项目本地服务：
localhost:10087

whistle Rules 中配置规则：
xxx.com localhost:10087

在浏览器中访问 xxx.com，出现上面的报错，之前版本是正常的，升级后不可用。

**Comment by avwo** [comment]
这个服务 127.0.0.1:10087 没起来

**Comment by imwangpan** [comment]
> 这个服务 127.0.0.1:10087 没起来

是的，前端项目起的服务是 localhost。
请问 whistle 新版本为啥不能直接代理到 localhost 了，这是出于什么策略考虑的？现在除了降级还有什么方法吗？

**Comment by k1ngbanana** [comment]
我也遇到类似的问题
https://10.201.xxx.yyy:4200 proxy://aaa:bbb@xxx.yyy.space:1010

这个代理设置(抹去了真实ip和代理用户账号和密码)，在2.6.68的版本是正常的，更新到2.9.84之后无法正常使用。

**Comment by avwo** [comment]
新版默认不解析域名为 IP 的 https 请求，可以把 https 改成 http，或配置规则 `* enable://captureIp`

**Comment by imwangpan** [comment]
回退到旧版本 2.9.64 解决了这个问题。有同样问题的人不要升级新版。

**Comment by avwo** [comment]
抓包看下，不应该不可以

**Comment by mapleshadow** [comment]
不能默认* enable://captureIp吗？新版变得太麻烦了

**Comment by avwo** [comment]
我看下

**Comment by avwo** [comment]
> > 这个服务 127.0.0.1:10087 没起来
> 
> 是的，前端项目起的服务是 localhost。 请问 whistle 新版本为啥不能直接代理到 localhost 了，这是出于什么策略考虑的？现在除了降级还有什么方法吗？

你本地前端服务的 localhost 指向的是 `::1` 而不是 `127.0.0.1`，有以下几种解决方案：
1. 把规则改成 `xxx.com [::1]:10087`
2. 前端服务启动时用 `127.0.0.1` 代替 localhost（推荐该方案，因为 localhost 是一个域名，指向哪个 ip 是由系统 hosts 决定，如果系统 hosts 没配的话，其行为是不确定的）
3. 系统 hosts 新增 `127.0.0.1 localhost`
4. 降低 Node 版本，详见：https://github.com/avwo/whistle/blob/master/CHANGELOG.md#v2973

**Comment by basicButtons** [comment]
Use the 2.9.64 version fix, no break change plz.

**Comment by avwo** [comment]
> 不能默认* enable://captureIp吗？新版变得太麻烦了

更新下 Whistle

**Comment by chrislai-11** [comment]
@avwo 本地默认node16，更新了版本，依旧无法代理localhost和127.0.0.1

**Comment by avwo** [comment]
> localhost

https://github.com/avwo/whistle/issues/266

**Comment by chrislai-11** [comment]
Hello, 这是Chrisl赖梓萌的邮箱。我已经收到你的邮件啦~我会尽快回复哒！
