### ISSUE TITLE
TCP stack exited with code 139 (Segmentation fault) 无法抓包

### ISSUE THREAD

**Issue by fewpiwork** [avwo/whistle#1147]
<img width="1375" alt="image" src="https://github.com/user-attachments/assets/6bc29dc7-dcf7-43b1-8712-03806a305cdf">

网站 https://app.uniswap.org/swap

好奇怪的问题 其他都很正常呐

**Comment by avwo** [comment]
是不是 cookie 太长了，清除 cookie 或用隐身模式访问看看
