### ISSUE TITLE
为什么添加statusCode后就不返回response了

### ISSUE THREAD

**Issue by dxcqcv** [avwo/whistle#1152]
`/.*\/v0\/oauth\/api?.*/  resCors://enable  fake://script:/path` 这样会正常返回mock内容

但
`/.*\/v0\/oauth\/api?.*/ statusCode://400  resCors://enable  fake://script:/path` 这样只会返回状态400，不会返回mock的res了

现在希望返回400状态的时候同时也能返回mock的res，应该如何配置？

**Comment by avwo** [comment]
用 `replaceStatus://400`、`statusCode` 直接返回不会继续向上请求
