### ISSUE TITLE
Inspector 当 Url 过长时在Firefox上会发生Overflow

### ISSUE THREAD

**Issue by sleetdrop** [avwo/whistle#1153]
**版本**
whistle 2.9.85
firefox 131.0b9 

**问题截图**
<img width="576" alt="Screenshot 2024-09-26 at 17 54 42" src="https://github.com/user-attachments/assets/f7c96500-be41-466e-8cc3-63612a9cc87f">

**发生flow的element**
<img width="342" alt="Screenshot 2024-09-26 at 17 56 14" src="https://github.com/user-attachments/assets/3895ed9b-48a8-4b95-8023-7b04b3fdbb61">

**Comment by avwo** [comment]
用 chrome 浏览器看看

**Comment by avwo** [comment]
已修复，重启安装 Whistle 并重启
