### ISSUE TITLE
Breakpoints / Intercept

### ISSUE THREAD

**Issue by redkit75** [avwo/whistle#1154]
你好，

有时由于 CSRF 保护机制，相同 URL 的相同请求会失败。

可以添加类似于 Charles Proxy 中的 Breakpoints 或 BurpSuite 中的 Intercept 这样的功能吗？如果在开启状态时能够编辑请求，那将是一个非常棒的功能。

**Comment by avwo** [comment]
你是要动态注入 csrf 的 token，这个不需要断点功能，配置 Whistle 规则也可以实现
