### ISSUE TITLE
如何支持另一台机器访问 9001

### ISSUE THREAD

**Issue by fantian007** [avwo/whistle#1155]
`whistle(
          {
            host: '0.0.0.0',
            realHost: '0.0.0.0'
          }`
这样设置之后，另一台服务器通过 ip:8899 无法访问 UI 界面，不设置 host 也不能访问，怎么才能访问到

**Comment by fantian007** [comment]
算我瞎说的

**Comment by fantian007** [comment]
8899 不支持本机以外的其它主机访问？

**Comment by avwo** [comment]
Whistle 默认没做这个限制，这个跟你们的网络或防火墙有关，换个端口试试比如 8080
