### ISSUE TITLE
建议增加一个解释报文中包含JSON字符串的功能

### ISSUE THREAD

**Issue by lfire** [avwo/whistle#1156]
<img width="643" alt="image" src="https://github.com/user-attachments/assets/9bb11d26-4c10-4e0a-ac1d-2d83edc01dec">

如图中，报文中返回有json字段包含另一个json串的数据，建议可以增加一个解释该串的功能，便于格式化查看。

**Comment by avwo** [comment]
可以支持，我也正考虑这个问题

**Comment by avwo** [comment]
重新安装 Whistle 并重启，新版右键菜单 `Inspect Value` 可以查看当前 Value 对应的 JSON 对象
