### ISSUE TITLE
New Version on mac M1 can not search in values tab 

### ISSUE THREAD

**Issue by jackykinho** [avwo/whistle#1158]
![Screenshot 2024-10-18 at 10 37 21 AM](https://github.com/user-attachments/assets/8616f244-6e48-49cb-84e7-815d2ffad0a9)

**Comment by avwo** [comment]
这个是[客户端](https://github.com/avwo/whistle-client)问题，我看下怎么处理

**Comment by jackykinho** [comment]
M3 also

**Comment by avwo** [comment]
你们先 focus 到 Values 再用快捷键 `cmd + G` 搜索试试

**Comment by avwo** [comment]
已支持，更新下客户端 https://github.com/avwo/whistle-client
