### ISSUE TITLE
[BUG] GET请求request body没有透传

### ISSUE THREAD

**Issue by fuminchao-at-coupang** [avwo/whistle#1159]
att.

**Comment by avwo** [comment]
get 请求没有 request body

**Comment by fuminchao-at-coupang** [comment]
可以有。协议并没有强制规定
https://stackoverflow.com/questions/978061/http-get-with-request-body
而且作为一个man-in-middle, 我认为应该尽可能还原上下游的payload

**Comment by fuminchao-at-coupang** [comment]
比如，golang的标准库http就没有限制GET的body

**Comment by fuminchao-at-coupang** [comment]
另外curl也支持GET发送body
所以请考虑支持一下

**Comment by avwo** [comment]
node 做了限制，暂时绕不过，你们怎么会用 get 请求发送 body？

**Comment by fuminchao-at-coupang** [comment]
我们在调用ES的API
https://www.elastic.co/guide/en/elasticsearch/reference/current/filter-search-results.html
![image](https://github.com/user-attachments/assets/d9aa3617-ffbb-4c8a-930b-ac6d42258692)

**Comment by avwo** [comment]
目前用 Node API 发送 HTTP 请求时会自动忽略 GET 请求的 body，这个问题暂时无解，不过最新的标准貌似把 GET 请求要忽略内容的部分删了，得等后续 Node 版本看看是否会放宽这个限制。
