### ISSUE TITLE
有没有可能用这样一种方法解决无法设置代理的情形

### ISSUE THREAD

**Issue by shoaly** [avwo/whistle#116]
比如我要访问并调试 www.baidu.com, 现在的做法是 在本地开一个 whistle的代理, 然后 通过代理访问baidu.com的时候 whistle可以借助 rules 能够将很多静态资源替换成本地的, 弊端是必须要设置代理

所以我在想这样, 比如开放一个端口8900, 通过8900端口的所有http请求,默认转发到www.baidu.com的80端口, 之后的调试就很简单了, 只需要访问 localhost:8900, 然后就能读到www.baidu.com所有资源, 借助rules 重定向 biadu.com下面的某些js 到本地js , 完成调试功能. 这样就可以不用开代理了.

**Comment by avwo** [comment]
现在也可以实现，配下规则：
```
http://127.0.0.1 https://www.baidu.com
```
访问 [http://127.0.0.1:8888/-/](http://127.0.0.1:8888/-/) 或 [http://127.0.0.1:8888/_/](http://127.0.0.1:8888/_/)，即路径前面加个 `-`  或 `_`

但这种方式不适合所有页面，如果有js里面有做域名判断或者页面的里面的请有做referer校验就会有问题

**Comment by shoaly** [comment]
你是真的秀.... 文档. 
不过写错了, 如果默认端口是8899的话 应该是访问  http://127.0.0.1:8899/-/  吧
刚刚试验了可行, 可行确实迈不过referer.  感谢夜猫子
