### ISSUE TITLE
同域名，用路径路由来区分不同环境，可能吗？

### ISSUE THREAD

**Issue by lizyChy0329** [avwo/whistle#1161]
假如有这样的一个线上映射 172.18.7.65 www.abb.com

单纯依靠 whistle 能做到

http://www.abb.com/index.html 是线上环境

http://www.abb.com/api/getSetting 是测试环境吗？

**Comment by avwo** [comment]
Whistle 支持匹配域名、路径、通配符、正则等，可以这么配：`172.18.7.65 www.abb.com/api/getSetting`

**Comment by lizyChy0329** [comment]
谢谢，原来我以为需要是同一个域名 www.abb.com 有两套映射逻辑，原来不需要，统统映射到 指定 IP，然后会根据路径路由自动解析。想岔了

**Comment by avwo** [comment]
https://wproxy.org/whistle/mode.html
