### ISSUE TITLE
values 是否支持默认值

### ISSUE THREAD

**Issue by DiamondYuan** [avwo/whistle#1163]
https://www.qq.com  proxy:127.0.0.1:{LOCAL_PORT}
https://www.qq.com  proxy:127.0.0.1:8000

如何实现下面的规则

1. LOCAL_PORT 有数据的时候，读取上一条
2. LOCAL_PORT 没数据的时候，请求 127.0.0.1:8000

**Comment by avwo** [comment]
可以用插件或 reqScript：https://wproxy.org/whistle/rules/reqScript.html
```` txt
https://www.qq.com/ reqScript://{config.js}
``` config.js
const port = getValue('LOCAL_PORT')?.trim() || 8000;
rules.push(`https://www.qq.com/ proxy:127.0.0.1:${port}`);
```
````
