### ISSUE TITLE
使用//log 功能时，点清除按钮之后，之前的log 信息还会展现

### ISSUE THREAD

**Issue by fengyangbj-kanyun** [avwo/whistle#1165]
在使用// log 展示页面打印的日志信息时，当点击
![image](https://github.com/user-attachments/assets/7734997a-5560-4618-84c5-a7379819418e) 清除按钮进行日志清除，后面页面重新打印日志时，被清除的日志信息又展示出来，可不可以在清除之后，被清除的log 信息就不需要再展示了。

**Comment by avwo** [comment]
已修复，安装最新版本
