### ISSUE TITLE
mac上xcode自带的ios模拟器里的websocket请求抓不到

### ISSUE THREAD

**Issue by catshub** [avwo/whistle#1167]
mac上xcode自带的ios模拟器里的websocket请求抓不到
![image](https://github.com/user-attachments/assets/68f21c18-f540-48b7-a71e-8336dc9017e5)

模拟器里https/http的请求能正常抓到

**Comment by avwo** [comment]
看下是不是这个问题：https://github.com/avwo/whistle/issues/662
