### ISSUE TITLE
命令行可以配置 添加 删除 映射规则吗

### ISSUE THREAD

**Issue by zhper** [avwo/whistle#1169]
目前是不是只能通过 w2 add [filePath] 来添加文件里的规则，我通过怎么样的命令，才能实现给这个规则 disable 呢，或者切换到其他的规则去，或者能不能有这样的命令，比如，w2 add rule "xxxx xxxx" 增加规则，w2 remove rule "xxxx xxxxx" 删除规则

**Comment by avwo** [comment]
Whistle 暂时不会支持这么细的命令行操作，你可以自定义插件，用插件来设置规则，再通过命令行操作插件的方式实现
