### ISSUE TITLE
ajax请求时类型识别错误

### ISSUE THREAD

**Issue by 74sharlock** [avwo/whistle#117]
抱歉打扰了。

这边ajax请求时，request header的accept本来是<code>application/json, text/plain,  \*/\* </code>
但是抓包时，type变成了 <code>text/html</code>
![2018-01-24 15 37 13](https://user-images.githubusercontent.com/7920399/35319860-a5aa715a-011c-11e8-941f-243c14f5afb2.png)
![2018-01-24 15 39 55](https://user-images.githubusercontent.com/7920399/35319921-e0d7eafa-011c-11e8-9fd5-985a268589a6.png)

由于我还设置了<code>weinre</code>，现在导致接口数据也被注入了js，然后解析数据出错
![2018-01-24 15 40 33](https://user-images.githubusercontent.com/7920399/35319977-12bf9a0e-011d-11e8-8e10-e5fd28d8e81c.png)

请问是否是我忽略了什么？
这边请求类型是如何识别的？

**Comment by avwo** [comment]
这条ajax请求响应头 `Content-Type` 设置成了 `text/html`，导致whistle识别为html内容把weinre的脚本注入进去了；这种返回json数据的请求响应头 `Content-Type`  应该设置为 `application/json` ，否则可能会有安全问题。

**Comment by 74sharlock** [comment]
感谢回复。

我一开始没有弄清楚，以为是<b>request header</b>的<code>Content-type</code>设置为<code>application/json</code>就可以了

![2018-01-24 16 53 40](https://user-images.githubusercontent.com/7920399/35323116-6d31a928-0127-11e8-94f7-8c0ad566d563.png)

然而实际上是<b>response header</b>存在问题

![2018-01-24 16 57 36](https://user-images.githubusercontent.com/7920399/35323240-d4b33f1c-0127-11e8-9cb1-8bbe5ed70684.png)

我已经要求后端去改正，我觉得很可能是这个原因。

请稍等，容我测试之后再来反馈。

**Comment by 74sharlock** [comment]
@avwo 十分感谢，问题已经解决了。
