### ISSUE TITLE
规则超长的写法

### ISSUE THREAD

**Issue by 2089764** [avwo/whistle#1170]
如果规则特别长 如何使用换行来实现
如 下面的 axxx bxxx 很多就会一行超长。又不想写多个。有没有更好维护的写法呢
/test-(cn|na).918x.cn/cgi/(axxx|bxxx|cxxxx|.......) http://127.0.0.1/xxxxx

**Comment by avwo** [comment]
https://github.com/avwo/whistle/issues/1138
