### ISSUE TITLE
nacos的grpc请求返回aborted

### ISSUE THREAD

**Issue by devraw** [avwo/whistle#1173]
现象：
经过whistle代理时，nacos的接口/Request/request，部分正常，部分显示aborted
而接口/BiRequestStream/requestBiStream则基本上都是aborted，
导致程序无法启动

![image](https://github.com/user-attachments/assets/5bfe04ec-0210-4844-a2c8-10ac93cc3617)

![image](https://github.com/user-attachments/assets/c2d0fa0c-8bdf-4c45-bcc5-d8798c631cec)

当使用fiddler代理时，显示为tunnel 请求，程序能正常启动
![image](https://github.com/user-attachments/assets/ac82a73a-5195-4f03-8099-823ce994acba)

**Comment by avwo** [comment]
配置规则试试：
``` txt
127.0.0.1:9848 disable://capture
```

**Comment by devraw** [comment]
> 配置规则试试：
> 
> ```
> 127.0.0.1:9848 disable://capture
> ```

目前是这样处理了，还想了解下whistle后续能否兼容此类请求

**Comment by avwo** [comment]
本身是支持的，我这边怎么复现这个问题？

**Comment by devraw** [comment]
> 本身是支持的，我这边怎么复现这个问题？

需要配置好java环境，我这边用的是jdk17
1、下载[nacos-server](https://github.com/alibaba/nacos/releases/download/2.4.3/nacos-server-2.4.3.zip)并解压，进入bin目录，通过命令 `.\startup.cmd -m standalone`启动nacos服务端

2、下载编译好的jar程序，demo-001.zip、demo-002.zip，并分别修改名称为demo.zip.001、demo.zip.002，用解压工具（如7z）解压得到demo.jar
[demo-001.zip](https://github.com/user-attachments/files/17826174/demo-001.zip)
[demo-002.zip](https://github.com/user-attachments/files/17826176/demo-002.zip)
![image](https://github.com/user-attachments/assets/adbb8573-14d7-4b46-8af1-2453ff19defd)

3、通过代理启动`java "-Dhttps.proxyHost=127.0.0.1" "-Dhttps.proxyPort=8888" "-Dhttp.nonProxyHosts=" -jar demo.jar`，程序会报错然后退出，此时可以看到whistle的请求返回aborted
![image](https://github.com/user-attachments/assets/d7fe1af8-ce38-45c4-b88c-c7fe96a84b9f)
![image](https://github.com/user-attachments/assets/c20a3b4c-b035-45b9-95f3-b8744d686d27)
![image](https://github.com/user-attachments/assets/b1fdaedc-ef8b-4814-bc1f-d8fa43cfaf94)

4、不通过代理启动，`java -jar demo.jar`, 程序最后会打印`启动成功`
![image](https://github.com/user-attachments/assets/b5e60593-8019-48dc-a2f9-240923741f4e)
![image](https://github.com/user-attachments/assets/8c0bf563-5547-48a9-91b6-0e8e17c8addb)

**Comment by avwo** [comment]
有空我看下

**Comment by avwo** [comment]
@devraw demo1.zip demo2.zip 解不开

**Comment by devraw** [comment]
> @devraw demo1.zip demo2.zip 解不开

需要重命名的，因为github不允许上传001、002这些后缀的文件。
demo-001.zip 重命名为 demo.zip.001
demo-002.zip 重命名为 demo.zip.002

然后再用解压工具打开demo.zip.001，这时就可以解压了
![image](https://github.com/user-attachments/assets/a7a6179c-8d31-4705-a430-4659fa3cfa39)
![image](https://github.com/user-attachments/assets/81cf59c4-bbe0-4201-97da-952d3e7c4f6d)

**Comment by avwo** [comment]
配置下面的规则强制使用 http2 看看：
``` txt
127.0.0.1:9848 enable://h2
```

**Comment by devraw** [comment]
> ```
> 127.0.0.1:9848
> ```

还是不行，首次启动demo.jar时，BiRequestStream/requestBiStream 会出现一个报错的
![image](https://github.com/user-attachments/assets/08f12ede-4564-4c3c-b8fc-78afb6e31add)

再次启动demo.jar时，BiRequestStream/requestBiStream就全部报错了
![image](https://github.com/user-attachments/assets/d6a96380-a6ab-4059-8ada-d020b5448936)

**Comment by avwo** [comment]
mac 怎么运行你这个 demo

**Comment by devraw** [comment]
> mac 怎么运行你这个 demo

参考 [这篇教程](https://juejin.cn/post/7121727970028290079)，配置好java环境，就可以运行了

**Comment by avwo** [comment]
解压出来的 jar 包有问题，demo1 demo2 你直接发我邮箱

**Comment by devraw** [comment]
> 解压出来的 jar 包有问题，demo1 demo2 你直接发我邮箱

前几天发了

**Comment by avwo** [comment]
我这里报的这个错误，什么原因导致的

<img width="1243" alt="image" src="https://github.com/user-attachments/assets/659dc89b-410f-4579-ac83-811fee50fabd">

<img width="1541" alt="image" src="https://github.com/user-attachments/assets/b26193d2-5568-43ad-88d4-f40e7884641f">

**Comment by avwo** [comment]
可以重现了，下个版本修复

**Comment by avwo** [comment]
更新下 whistle 再试试

**Comment by devraw** [comment]
> 更新下 whistle 再试试

更新后正常了，谢谢

**Comment by devraw** [comment]
刚发现disable://timeout 好像不生效，大概5分钟左右会断开
![image](https://github.com/user-attachments/assets/cc788b5d-4119-47e1-9a56-c16756331478)

**Comment by avwo** [comment]
长时间没有数据通信断开也是合理的，客户端不是会自动重连码

**Comment by devraw** [comment]
这个倒是影响不大，要是disable://timeout这个能生效就更好了，毕竟没有报错日志看起来会舒服点

**Comment by devraw** [comment]
> 这是一个全局设置，不支持针对单个请求放开

whistle-client 在哪里设置

**Comment by avwo** [comment]
whistle-client 不支持设置这个参数，建议你们程序加个心跳

**Comment by avwo** [comment]
更新下 whistle 或 whistle-client，超时问题解决了
