### ISSUE TITLE
whistle可以抓websoket协议，可以抓到TCP的吗？如果可以？应该怎么做？

### ISSUE THREAD

**Issue by xiaowanzixll** [avwo/whistle#1177]

**Comment by avwo** [comment]
可以，需要将 tcp 请求通过隧道代理的方式转到 whistle，如果是 node 可以参考这个的实现： https://github.com/avwo/lack-proxy

**Comment by xiaowanzixll** [comment]
这是需要研发的代码程序里设置么？我用的APP抓取websoket，就跟正常抓去http或https一样操作就可以了，但TCP的好像需要换工具wireshark

**Comment by avwo** [comment]
tpc 需要手动编码将请求代理到 whistle，系统不支持代理这类请求。只是查看传输内容的话可以用 wireshark
