### ISSUE TITLE
请问我自己的程序可以获取到抓包后的结果吗？

### ISSUE THREAD

**Issue by ifeisier** [avwo/whistle#1180]
请问我自己的程序可以获取到抓包后的结果吗？

**Comment by avwo** [comment]
可以啊，你程序时用语言什么写的

**Comment by ifeisier** [comment]
> 可以啊，你程序时用语言什么写的

Java。

请问有资料吗？

**Comment by avwo** [comment]
你网上搜下 java 程序怎么设置 http 代理

**Comment by beifen886** [comment]
> 你网上搜下 java 程序怎么设置 http 代理

我的想法是，通过你的这个工具抓包，然后你的这个工具将抓包结果推送到我的程序。

**Comment by ifeisier** [comment]
> 你网上搜下 java 程序怎么设置 http 代理

我的想法是，通过你的这个工具抓包，然后你的这个工具将抓包结果推送到我的程序。

**Comment by avwo** [comment]
可以通过插件获取抓包数据，再发送到指定服务器，参考 whistle.autosave 的实现：https://github.com/whistle-plugins/whistle.autosave

**Comment by ifeisier** [comment]
> 可以通过插件获取抓包数据，再发送到指定服务器，参考 whistle.autosave 的实现：https://github.com/whistle-plugins/whistle.autosave

好的 谢谢
