### ISSUE TITLE
User-Agent会丢失

### ISSUE THREAD

**Issue by Tencent-arondan** [avwo/whistle#1182]
当我使用whistle抓包的时候，在我的app中打开任意H5页面，Header中的User-Agent会丢失。
而如果我使用其他抓包工具，例如fiddler就不会有这个问题，以及我尝试过不连接whistle抓包时，后端服务接收到的请求是有User-Agent的。
我们页面通常需要根据User-Agent做一些判断，所以这个问题导致了我们在抓包时，页面的处理逻辑会发生异常。
版本：2.9.30

**Comment by avwo** [comment]
之前有人反馈过类似的问题，后来发现是因为 Whistle 支持 HTTP2 ，而 APP 采用 HTTP2 请求时客户端没把 UA 带过来，配下面规则强制关掉指定域名的 HTTP2 试试：
``` txt
域名 disable://http2
```

**Comment by avwo** [comment]
更新下 whistle 试试，可以不用降级到 http1.1
