### ISSUE TITLE
pipe://加载的插件，怎么带参数reqRead的服务里面？

### ISSUE THREAD

**Issue by lkswqyfn** [avwo/whistle#1184]
我尝试使用@关键字，放在globalValue里面，发现resWrite resRead reqWrite都能读取到值，但是resRead这个服务globalValue的数据一直是空。请问我要怎样才能将我需要的参数到过去插件里面。

**Comment by avwo** [comment]
不要用 `@`，可以用 `pipe://pluginName(value)`，在插件里可以通过 `req.originalReq.pipeValue` 获取
