### ISSUE TITLE
【咨询】whistle支持多少个设备同时代理抓包连接，或者如何修改最大连接数

### ISSUE THREAD

**Issue by Teslax2025** [avwo/whistle#1188]
我的mac 安装了whistle ，但是我需要同时多台设备代理到这个IP上进行抓包，请问最大支持多少，如何修改，多台设备同时代理是否有其他影响

**Comment by avwo** [comment]
主要看并发量，多人使用可以用 nohost：https://github.com/Tencent/nohost
