### ISSUE TITLE
文档中 plugins 部分 markdown 语法渲染不当

### ISSUE THREAD

**Issue by elvinn** [avwo/whistle#121]
[文档中 plugins 部分](https://avwo.github.io/whistle/plugins.html) markdowm 语法中列表的渲染层级有问题，如下图所示：
![image](https://user-images.githubusercontent.com/28722527/36593295-03577054-18d4-11e8-9daa-ab86371bdbfa.png)

![image](https://user-images.githubusercontent.com/28722527/36593304-0b5f71d4-18d4-11e8-9173-954dfaf10625.png)

**Comment by avwo** [comment]
已经fix
