### ISSUE TITLE
socks 代理配置后无效

### ISSUE THREAD

**Issue by snadn** [avwo/whistle#122]
![image](https://user-images.githubusercontent.com/1269858/36599676-222a0480-18eb-11e8-8c08-c69719f72b0d.png)

如图，配置了规则 `172.19.1.* socks://127.0.0.1:1087`, 但在浏览器里访问却出现了502响应

**Comment by snadn** [comment]
代理是起了的，直接走浏览器的socks代理是OK的。是socksv5协议

**Comment by echopi** [comment]
@snadn 可以提供一下 bug 复现的步骤吗

**Comment by snadn** [comment]
1. 使用 securecrt 连接服务器 a，并配置端口动态转发，转发本地端口 1085 。服务器 a 可访问服务器 b，本地不能访问服务器 b
![image](https://user-images.githubusercontent.com/1269858/36728661-7ceb13d2-1bfc-11e8-9a87-0953da4596a6.png)

2. 使用 chrome 插件 SwitchyOmega 配置 socks5 代理，通过该配置可以访问服务器 b
![image](https://user-images.githubusercontent.com/1269858/36728555-15ff4bd4-1bfc-11e8-9477-de9681a67b2a.png)
3. whistle 配置 rule `[服务器 b ip] socks://127.0.0.1:1085`，然后浏览器访问服务器 b，出现 502

**Comment by echopi** [comment]
hi @snadn ：

截图是我本地尝试还原你的操作，whistle 转发应该是没问题的。

![image](https://user-images.githubusercontent.com/16034964/36737005-f2ccd62c-1c14-11e8-9432-9f5e2c49222f.png)

你可以看看启动 socks 服务指定的 ip，可以试试绑定 127.0.0.1

**Comment by snadn** [comment]
@echopi 试了一下，如果访问的 url 没有 port，也就是用默认的 80 端口是 ok 的（你的就是这种情况），但如果有指定端口，就不行（我试的时候有端口）。

**Comment by echopi** [comment]
@snadn 带端口的确实存在问题，代码已经提交了，@avwo 在下个版本发布修复这个问题
