### ISSUE TITLE
Mac下拦截https请求出错

### ISSUE THREAD

**Issue by C860** [avwo/whistle#123]
- 问题描述：
whistle无法正常代理https请求，拦截到的是https请求，转发出去的实际上是http请求，由于服务器端不支持http请求，导致请求失败。

- 测试用例：https://hkwx.cqeee.cn:28010/hkh5/goods/preQuery?code=xxxxxx

- 测试结果：
能够拦截https请求，但是代理出去的请求头是http请求，由于协议不对，请求超时，whistle把请求置为502，以下是请求头：
```
GET /hkh5/goods/preQuery?code=xxxxxx HTTP/1.1
Host: hkwx.cqeee.cn:28010
Connection: keep-alive
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,*/*;q=0.8
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (Linux; Android 6.0; Custom Phone - 6.0.0 - API 23 - 768x1280 Build/MRA58K; wv) AppleWebKit/537.36 (KHTML, like Gecko) Version/4.0 Chrome/44.0.2403.119 Mobile Safari/537.36 MicroMessenger/6.6.1.1220(0x26060135) NetType/WIFI Language/zh_HK
Accept-Encoding: gzip
Accept-Language: zh-HK,en-US;q=0.8
x-forwarded-for: 192.168.57.1
```
以下是服务器无响应之后，whistle提示的response内容：
```
HTTP/1.1 502 Bad Gateway


From: whistle@1.8.8
Node: v9.3.0
Date: 2018-2-24 10:54:13
Error: Timeout
    at Timeout.emitTimeoutError [as _onTimeout] (/Users/user/.nvm/versions/node/v9.3.0/lib/node_modules/whistle/lib/inspectors/data.js:268:43)
    at ontimeout (timers.js:466:11)
    at tryOnTimeout (timers.js:304:5)
    at Timer.listOnTimeout (timers.js:264:5)
```
预期返回的请求头应为：
```
HTTP/1.1 200 OK
Date: Sat, 24 Feb 2018 02:51:09 GMT
Content-Length: 31
Connection: keep-alive
Cache-Control: no-cache

{"retCode":"10000","retMsg":""}
```

- 测试环境：
操作系统：`macOS High Sierra v10.13.3`
node版本：`9.3.0`
whistle版本：`1.8.8`

**Comment by avwo** [comment]
我这边试了下没有这个问题，在`Network>Overview>All rules`看下是不是匹配到自己设置的规则

**Comment by C860** [comment]
没有匹配到其它规则

**Comment by avwo** [comment]
用鼠标右键点击对应请求导成 `.txt` 格式的文件发给我看看：
![image](https://user-images.githubusercontent.com/11450939/36625176-9f22c1ec-1955-11e8-91ac-8a61da52c82a.png)

**Comment by C860** [comment]
[httpstest.txt](https://github.com/avwo/whistle/files/1754002/httpstest.txt)
@avwo

**Comment by avwo** [comment]
换个网络看看，我这边重现不了：
[hkwx.cqeee.cn.txt](https://github.com/avwo/whistle/files/1754063/hkwx.cqeee.cn.txt)

**Comment by C860** [comment]
网络原因导致访问链路走不通，已解决
