### ISSUE TITLE
reqReplace中 替换请求文本内容 的格式是什么?

### ISSUE THREAD

**Issue by shoaly** [avwo/whistle#125]
是下面这种格式吗? 正则写成 b=.*&: b=new_value 好像匹配不到, 想要替换请求中b的值
a=1&b=2&c=3

**Comment by avwo** [comment]
`/((?:^|&)b=)[^&]+/: $1new_value`

**Comment by shoaly** [comment]
可以console.log 或者什么地方能debug到日志吗, 我想看看看捕获到的req是什么样子的... 不行就只能去找源代码了..

**Comment by avwo** [comment]
界面 `Network` -> `右侧点击Log` -> `Server`可以查看`console`的输出信息

**Comment by shoaly** [comment]
麻烦在问问, 像这种  str: replacement 替换模式支持 函数吗? 类似...
/regex/ig: function(req_string){ return req_string; }

**Comment by avwo** [comment]
对
