### ISSUE TITLE
如何把ws的message实时存储到本地？

### ISSUE THREAD

**Issue by kent2017** [avwo/whistle#128]
fiddler里可以写js脚本，实时把ws的message存到本地文件，whistle有这样的功能码

**Comment by avwo** [comment]
目前可以在Network里面Export的txt格式文件里面就包含Frames，要通过脚本实时存储，可以用如下插件：
https://github.com/whistle-plugins/whistle.script
具体实现也可以参考：[利用whistle调试websocket和socket请求](http://imweb.io/topic/5a11b1b8ef79bc941c30d91a)
