### ISSUE TITLE
是否有启动配置文件？

### ISSUE THREAD

**Issue by leohxj** [avwo/whistle#13]
我在文档中 [安装启动](https://avwo.github.io/whistle/install.html) 章节，没有看到启动 w2 的配置，所有的启停相关命令都是在命令行下直接完成。

我建议可以维护一个针对项目启动的配置文件，在 `w2 start` 的时候可以默认指定，帮助用户减化命令行下的启动命令输入。

**Comment by avwo** [comment]
https://github.com/avwo/whistle/tree/master/assets/launcher
