### ISSUE TITLE
能否指定DNS服务器？

### ISSUE THREAD

**Issue by edsion1107** [avwo/whistle#132]
w2 restart-H xxxx.com
错误信息如下：
From: whistle@1.9.2
Node: v8.10.0
Date: 2018-3-21 14:10:25
Error: getaddrinfo ENOTFOUND xxxx.com
    at errnoException (dns.js:50:10)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:92:26)

看异常应该是dns查询过程中出错了吧？能否加一个参数，指定使用的dns服务器？

**Comment by avwo** [comment]
-H是绑定网卡的，https://nodejs.org/dist/latest-v8.x/docs/api/net.html#net_server_listen_port_host_backlog_callback
