### ISSUE TITLE
远程服务器同时有公网和内网IP的问题

### ISSUE THREAD

**Issue by edsion1107** [avwo/whistle#133]
w2 restart  -H xxxx.com
错误信息如下：
From: whistle@1.9.2
Node: v8.10.0
Date: 2018-3-21 14:19:07
Error: listen EADDRNOTAVAIL 111.231.xxx.xxx:8899
    at Object._errnoException (util.js:1022:11)
    at _exceptionWithHostPort (util.js:1044:20)
    at Server.setupListenHandle [as _listen2] (net.js:1350:19)
    at listenInCluster (net.js:1408:12)
    at GetAddrInfoReqWrap.doListen [as callback] (net.js:1517:7)
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:97:10)

ifconfig的结果是：
eth0      Link encap:Ethernet  HWaddr 52:54:00:56:f1:6c
          inet addr:10.105.xxx.xxx  Bcast:10.105.255.255  Mask:255.255.192.0
          UP BROADCAST RUNNING MULTICAST  MTU:1500  Metric:1
          RX packets:5573425 errors:0 dropped:0 overruns:0 frame:0
          TX packets:5488646 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1000
          RX bytes:684619679 (684.6 MB)  TX bytes:733691741 (733.6 MB)

lo        Link encap:Local Loopback
          inet addr:127.0.0.1  Mask:255.0.0.0
          UP LOOPBACK RUNNING  MTU:65536  Metric:1
          RX packets:8002 errors:0 dropped:0 overruns:0 frame:0
          TX packets:8002 errors:0 dropped:0 overruns:0 carrier:0
          collisions:0 txqueuelen:1
          RX bytes:9189811 (9.1 MB)  TX bytes:9189811 (9.1 MB)

应该是我有一个111.231.xxx.xxx的公网IP，使用ifconfig是查询不到的，只能查到内网IP：10.105.xxx.xxx。
只能指定host是0.0.0.0了吗？会不会有其它问题……

**Comment by avwo** [comment]
这个ip不是你本机网卡的

**Comment by Yakovtam** [comment]
我也遇到了同样的问题，
我在阿里云服务器上使用whistle，
whistle启动时默认以私有ip启动，
通过公网的ip无法访问whistle，
求解决办法
