### ISSUE TITLE
能否像anyproxy一样做为模块使用?

### ISSUE THREAD

**Issue by trim21** [avwo/whistle#135]
anyproxy可以做为一个模块使用 比如

```
const AnyProxy = require('anyproxy')

const options = {
    port: 8001,
    rule: require('./rule.js')
}

const proxyServer = new AnyProxy.ProxyServer(options)
proxyServer.start()
```

看了一下whistle相关的文档,没找到类似的用法,请问一下有类似的用法说明或者例子?

**Comment by avwo** [comment]
直接`const startWhistle = require('whistle')`引用 即可，这块文档不全，参考下这个：[https://github.com/avwo/koa-whistle/blob/master/lib/start.js](https://github.com/avwo/koa-whistle/blob/master/lib/start.js)

PS：建议通过插件的方式扩展功能，更方便共享给大家使用，具体可以参考：[如何开发插件](https://avwo.github.io/whistle/plugins.html)及例子[https://github.com/whistle-plugins](https://github.com/whistle-plugins)

**Comment by Trim21** [comment]
感谢,还有几个问题请教一下

我看到[whistle-plugins](https://github.com/whistle-plugins)里面有一个[whistle.helloworld](https://github.com/whistle-plugins/whistle.helloworld) 其中看到wss,但是我实际使用的时候发现看不到wss,而且会造成ws和wss链接断开,在requests里报错
```
Error: Aborted
    at execCallback (pooo\node_modules\whistle\lib\https\index.js:449:15)
    at Socket.destroy (pooo\node_modules\whistle\lib\https\index.js:436:7)
    at emitOne (events.js:115:13)
    at Socket.emit (events.js:210:7)
    at TCP._handle.close [as _onclose] (net.js:547:12)
```
是因为whistle的更新已经看不到ws和wss了吗?

options能否直接设置` Capture HTTPS CONNECTs`,而不需要在网页上手动点一下?

**Comment by avwo** [comment]
helloworld这个插件的代码比较老，可能有些兼容性问题，这周重新更新，可以参考下[https://github.com/whistle-plugins/whistle.script](https://github.com/whistle-plugins/whistle.script)。

要通过参数开启https抓包，可以通过设置一些特殊的属性实现：
```js
const startWhistle = require('whistle');
const proxy = startWhistle(options);
proxy.rulesUtil.properties.set('interceptHttpsConnects', true);
```
看了下，跟你提到的anyproxy不太一样，whistle是以配置为主，插件扩展为辅的一套完整的web调试代理解决方案，基本上[现有的规则](https://avwo.github.io/whistle/rules/)可以满足绝大部日常的开发需求，不需要自己写代码一个个实现，一般只需简单配置，如果需要实现一些跟业务相关的功能可以通过[插件实现](https://avwo.github.io/whistle/plugins.html)，如：[whistle.script](https://github.com/whistle-plugins/whistle.script)、[whistle.vase](https://github.com/whistle-plugins/whistle.vase)、[whistle.combo](https://github.com/whistle-plugins/whistle.combo)等，你也可以在插件中用anyproxy来管理操作对应的请求。
