### ISSUE TITLE
Chrome 插件无法正常使用

### ISSUE THREAD

**Issue by jovey-zheng** [avwo/whistle#139]
打开之后显示是这样的：
![image](https://user-images.githubusercontent.com/9565245/38223223-5aa73a36-371c-11e8-955c-0f64ecd9eca5.png)

**Comment by avwo** [comment]
下架的具体原因未知，先用switchyomega代替，具体参考 https://github.com/avwo/whistle-for-chrome

**Comment by avwo** [comment]
推荐用[proxifier代替](https://github.com/avwo/whistle-for-chrome)
