### ISSUE TITLE
能否一个pattern映射到多个本地文件？

### ISSUE THREAD

**Issue by mapleeit** [avwo/whistle#14]
hi，请问下：

seajs combo情况下
会有这样的请求
http://img.weiyun.com/c/=/club/weiyun/js/publics/seajs/sea.js,/club/weiyun/js/publics/seajs-plugins/seajs-combo.js?max_age=31104000
需要映射到两个文件路径：
{filepath}/club/weiyun/js/publics/seajs/sea.js
{filepath}/club/weiyun/js/publics/seajs-plugins/seajs-combo.js

这种能不能实现？

**Comment by avwo** [comment]
这个插件[https://github.com/whistle-plugins/whistle.tianma](https://github.com/whistle-plugins/whistle.tianma)可以处理[http://style.aliunicorn.com/js/6v/??lib/arale/cookie/cookie.js,lib/arale/class/class.js,lib/arale/events/events.js,lib/arale/base/base.js](http://style.aliunicorn.com/js/6v/??lib/arale/cookie/cookie.js,lib/arale/class/class.js,lib/arale/events/events.js,lib/arale/base/base.js)这种形式的combo请求


你说的这种可以自己实现一个插件

**Comment by mapleeit** [comment]
多谢，我看一下这个插件
