### ISSUE TITLE
使用 shadowrocket 设置 http 代理，无法使用

### ISSUE THREAD

**Issue by maxming2333** [avwo/whistle#141]
同样是代码服务 charles 和 whistle 开启了代理

shadowrocket 设置 http 代理，开启全局代理模式

发现只有 charles 代理服务可以正常运行，并且可以 map 请求

但是 whistle 就没办法处理请求，手机也load不出来网页，qq也离线

![image](https://user-images.githubusercontent.com/8816730/38464557-31d343b4-3b42-11e8-9188-6cf8304267bb.png)

![image](https://user-images.githubusercontent.com/8816730/38464558-34b0bb16-3b42-11e8-8ba6-5b66246ca9b9.png)

![image](https://user-images.githubusercontent.com/8816730/38464560-3808b6ba-3b42-11e8-9130-463e305d8dde.png)

![image](https://user-images.githubusercontent.com/8816730/38464561-399b1cde-3b42-11e8-98ef-c4e071738a8e.png)

**Comment by echopi** [comment]
我这边跟你一样的客户端测试的，功能ok的，你看看是不是证书问题 http://wproxy.org/whistle/webui/https.html @maxming2333

**Comment by maxming2333** [comment]
还是不行，只要开启 https 代理，qq就离线

不知道是不是因为我同时安装了 `shadowrocket`  `charles`  `whistle` 这3个证书，导致他们之间有互相干扰的情况呢

![image](https://user-images.githubusercontent.com/8816730/38465939-430af750-3b54-11e8-9d16-5aa79c4ec995.png)

![image](https://user-images.githubusercontent.com/8816730/38465949-6669f4da-3b54-11e8-9c1d-edf8a3643f96.png)

![image](https://user-images.githubusercontent.com/8816730/38465950-68d81eae-3b54-11e8-860a-e8a59962735b.png)

**Comment by maxming2333** [comment]
我理解是 `shadowrocket` 通过安装的 `shadowrocket` 证书解密了流量，

然后把流量转发到 http 服务器（即 `whistle`）

然后 `whistle` 再对流量进行规则匹配

如果是这种模链路，为啥 `whistle` 还需要开启代理 https 流量开关呢

**Comment by avwo** [comment]
在APP上购买了shadowrocket，发现跟你的长的不一样，你试下在浏览器里面能不能正常访问http和https，如果https不行，可以试着去掉拦截https的勾选再试试能不能正常访问，然后把Network里面显示的请求选中右键导出给我看下。
![image](https://user-images.githubusercontent.com/11450939/38467216-9d11c3ba-3b67-11e8-84ae-494f1f74f6b8.png)

**Comment by maxming2333** [comment]
没有勾选 `Capture HTTPS CONNECTs` 就不会有问题

[qq-no-https.txt](https://github.com/avwo/whistle/files/1936568/qq-no-https.txt)

这个是我导出滴

**Comment by maxming2333** [comment]
当我开启 `Capture HTTPS CONNECTs`  qq就立马出现断网标示了

[qq-https.txt](https://github.com/avwo/whistle/files/1936573/qq-https.txt)

这个是开启 https 后导出滴

**Comment by maxming2333** [comment]
现在前提是，我手机上同时装了 `shadowrocket` 和 `whistle` 的证书

并且我 macos 上也装了 `whistle` 的证书

但是现在就是一开启 `Capture HTTPS CONNECTs` 就有问题了

**Comment by avwo** [comment]
关掉shadowrocket ，直接配手机的系统代理试试

**Comment by maxming2333** [comment]
直接用系统的是可以滴

[qq-system-https.txt](https://github.com/avwo/whistle/files/1936669/qq-system.txt)

但是在 ios 下设置不方便，所以需要使用 `shadowrocket` 这种软件开快速开关
