### ISSUE TITLE
同一个host中append多个js

### ISSUE THREAD

**Issue by mathgo** [avwo/whistle#143]
比如CDN上一个JS文件http.js，然后本地需要注入的一个文件inject.js。

我尝试了：

```
xxx.com js://https://xxx.cdn.com/http.js
xxx.com js:///Users/xxx/inject.js
```

以及

```
xxx.com js://https://xxx.cdn.com/http.js js:///Users/xxx/inject.js
```

我的inject.js均未生效。

采用的方案是把CDN的内容手动copy到我的inject.js前面，很不优雅。

**Comment by avwo** [comment]
用[htmlAppend](http://wproxy.org/whistle/rules/htmlAppend.html)试试

	xxx.com htmlAppend://{inject.html}

Values里面的 `inject.html` 内容（也可以放在本地的 `/Users/xxx/inject.html` 文件）：

	<script src="https://xxx.cdn.com/http1.js"></script>
	<script src="https://xxx.cdn.com/http2.js"></script>
	<script src="https://xxx.cdn.com/httpN.js"></script>

**Comment by lujqme** [comment]
我看 [配置方式](http://wproxy.org/whistle/mode.html)  的传统组合方式中提到   pattern operatorURI1 operatorURI2 operatorURIN   不知道是不是我说的这种方式？

另外建议增加一下，如果多个html注入的话照这么说也要都写在一起了，不美观。
