### ISSUE TITLE
可否让未匹配到的请求走系统代理？

### ISSUE THREAD

**Issue by latel** [avwo/whistle#145]
现在好像未匹配的请求全部是直接请求，没有走我系统代理里配置的pac，
我有个脚本会在公司网络和家庭网络切换时自动启用和禁用pac代理。
如果用让未匹配的规则都走whistle的pac://插件时回到家里就没法直接上网了。

**Comment by avwo** [comment]
需要自己自动插件实现，或者用 https://github.com/whistle-plugins/whistle.script
