### ISSUE TITLE
mac下无法完成HTTPS抓包

### ISSUE THREAD

**Issue by danielding** [avwo/whistle#15]
已经按照教程 https://avwo.github.io/whistle/webui/https.html
安装好证书，但访问https网站还是无法抓包，在network中没有相关请求
麻烦看下

**Comment by avwo** [comment]
打开Mac的根证书对话框，在右上角搜索`whistle`，看看证书是否安装成功(有x表示没信任通过)：https://zhidao.baidu.com/question/1768195217863444340.html

**Comment by danielding** [comment]
<img width="734" alt="screen shot 2016-10-31 at 2 01 22 pm" src="https://cloud.githubusercontent.com/assets/1400115/19845499/9036bf20-9f72-11e6-8223-ed63e689dad2.png">
信任了，请看截图~

**Comment by avwo** [comment]
勾上：菜单栏->Https->**Intercept HTTPS CONNECTS**: ![拦截HTTPS](https://avwo.github.io/whistle/img/https.gif)

**Comment by danielding** [comment]
勾选了啊，你的教程我认真看过三遍了。
之后我用chrome访问 https://www.baidu.com ，在network中没有抓包内容。
http的包，是可以正常抓到的

**Comment by avwo** [comment]
加QQ群：462558941

**Comment by danielding** [comment]
问题已定位：mac系统代理中，只设置了http走whistle，https未设置走whistle

错误设置见下图
<img width="405" alt="screen shot 2016-10-31 at 4 10 55 pm" src="https://cloud.githubusercontent.com/assets/1400115/19847863/9eccb4b0-9f84-11e6-9ee8-620e3ef241d7.png">

解决办法：把secure web proxy(https)也勾选上

此外，也可以通过此项目作者的chrome插件做浏览器代理，就不用设置系统代理了。
插件地址：https://chrome.google.com/webstore/detail/whistle/bokhoonoeoodkdhbdhlgaodjdcnbcpdl

**Comment by liaohaoxiang** [comment]
可以了,感谢

**Comment by xiang0308** [comment]
> 问题已定位：mac系统代理中，只设置了http走whistle，https未设置走whistle
> 
> 错误设置见下图
> <img alt="screen shot 2016-10-31 at 4 10 55 pm" width="405" src="https://cloud.githubusercontent.com/assets/1400115/19847863/9eccb4b0-9f84-11e6-9ee8-620e3ef241d7.png">
> 
> 解决办法：把secure web proxy(https)也勾选上，并设置好代理IP和端口
> 
> 此外，也可以通过此项目作者的chrome插件做浏览器代理，就不用设置系统代理了。
> 插件地址：https://chrome.google.com/webstore/detail/whistle/bokhoonoeoodkdhbdhlgaodjdcnbcpdl

secure web proxy(https)也勾选上 , 好像还是不行？

![Uploading proxy.jpg…]()

**Comment by xiang0308** [comment]
按教程和上面所说的 都操作过了，还是不能抓包？ 还需要设置什么吗？

**Comment by IcyW** [comment]
解决了：

![image](https://user-images.githubusercontent.com/16513834/124922622-3fe3ab00-e02c-11eb-91a0-3f9d3ccd8a35.png)
