### ISSUE TITLE
部署在公共服务器上时，不支持多人协作，同时浏览和编辑规则？

### ISSUE THREAD

**Issue by dong2590** [avwo/whistle#153]
我们将`whislte`部署在公共服务器上，但是发现刚开始大家都能访问，但过不了几分钟，就只有一个人能正常浏览编辑规则，其它人均不能访问，我们排除出网络等问题，想了解下，目前是没有`多人协作`这种机制吧？如果没有，我们需要如何改造就能支持呢？

**Comment by avwo** [comment]
1. 部署在公共服务器也是支持多人同时浏览和编辑，只是可能会相互覆盖，不应该出现你说的这种情况，方便的话截图我看下
2. 我们部门正在使用基于whistle插件开发的一个多任务版本，支持多人多环境，这边有一些功能要调整，预计下个月开源

**Comment by dong2590** [comment]
抱歉，我们目前没有再次尝试了，暂时也规避了类似的用法了，当然也还是蛮期待多任务版本，加油～ 👍

**Comment by avwo** [comment]
https://github.com/nohosts/nohost
