### ISSUE TITLE
json中unint64的数值会丢失精度

### ISSUE THREAD

**Issue by boafantasy** [avwo/whistle#156]
Version: 1.9.11
应该是node中一个普遍的问题

如
"id": 4635776828531280071 在resopnse中会显示成
"id": 4635776828531280000

**Comment by avwo** [comment]
下周会发个版本(`v1.10.0`)顺带fix这个问题。

**Comment by avwo** [comment]
重新安装下whistle http://wproxy.org/whistle/update.html

**Comment by boafantasy** [comment]
把数字转成字符串了啊,好吧,好像只有这个方案了

**Comment by boafantasy** [comment]
哦,不好意思,看错了,原来chrome 调试工具也有这个bug
