### ISSUE TITLE
 真正请求失败后，操作值不会返回

### ISSUE THREAD

**Issue by starInEcust** [avwo/whistle#158]
http://srv.test.com/ec/service/credentials/record/search resBody://{fitness.queryRecommendCompositeInfo}

比如有以上匹配模式，当匹配到之后，但是实际请求http://srv.test.com/ec/service/credentials/record/search 并不存在的时候，无法得到{fitness.queryRecommendCompositeInfo}的值，得到的和实际请求一样都是302.

是不是要把head也替换掉 换成200

**Comment by avwo** [comment]
`302`是没有响应内容，你是不是想实现本地替换功能：https://juejin.im/post/5ae890a5f265da0b9526e507

**Comment by starInEcust** [comment]
@avwo 那不就不能放在values里了，我倒是发现了直接放在本地文件是可以的- - 就是感觉怪怪的。

**Comment by starInEcust** [comment]
Access-Control-Allow-Credentials: true
Access-Control-Allow-Headers: x-requested-with,Content-Type
Access-Control-Allow-Methods: GET,POST,PUT,DELETE,OPTIONS
Access-Control-Allow-Origin: *****
Access-Control-Max-Age: 3600

这个response header 怎么设置呢- -

**Comment by avwo** [comment]
http://wproxy.org/whistle/rules/resCors.html

**Comment by starInEcust** [comment]
我去加你的群算了，我就是想在测试环境接口还没上的时候去验证一些功能。

/credentials\/detail\/search/ resCors://* file:///Users/star/code/pingan/perro/mockData/detail.search.json 
改成这样也不行
