### ISSUE TITLE
请问之前的插件为何从应用市场下线了呢？

### ISSUE THREAD

**Issue by xunuo** [avwo/whistle#159]
请问之前的插件为何从应用市场下线了呢？ 我想做一个类似的工具方便用户开关代理使用，增加代理对他们太难了。

**Comment by avwo** [comment]
没说具体原因，大概意思是 `违反了 Chrome 网上应用店政策` ，尝试改了一些默认行为提交还是被拒。
> 我想做一个类似的工具方便用户开关代理使用，增加代理对他们太难了。

太好了，你做好后把github地址或Chrome商店的地址发我，我更新到文档里面。

**Comment by avwo** [comment]
https://github.com/avwo/whistle/issues/192

**Comment by junchengkj** [comment]
我做了一个 Chrome 插件可以快速切换代理，附带了代理功能
https://chrome.google.com/webstore/detail/whistler/jkohblcpemjicbcaicciplcddbfiajkf

**Comment by Quilljou** [comment]
我做了一个 Chrome 插件可以快速切换规则，增加了代理功能
https://chrome.google.com/webstore/detail/whistler/jkohblcpemjicbcaicciplcddbfiajkf

**Comment by avwo** [comment]
@Quilljou 单独建个issue
