### ISSUE TITLE
点击clear All Sessions,清除后请求列表后又再原样展示

### ISSUE THREAD

**Issue by dong2590** [avwo/whistle#16]
操作系统:windows 7 
node版本:v5.10.1
whistle版本:v1.1.2

描述如题或者参见gif,抱歉不能给出全部截屏,可以关注序号为32的中止请求,清除多次列表后,又反复出现了
![gif](https://cloud.githubusercontent.com/assets/1455816/19893885/c9c2126c-a085-11e6-863a-fd25aa7d4c3f.gif)

**Comment by avwo** [comment]
这周末发的版本会fix这个问题
