### ISSUE TITLE
请问如果我想安装whistle后默认为用户内置一些rule，请问如何操作好呢？

### ISSUE THREAD

**Issue by xunuo** [avwo/whistle#160]
目前的想法是开发一个app（用electron）然后把whistle内置进去，用户打开后默认开启whistle，然后里面是默认内置rules的，请问有什么api或方法可以做到么？

**Comment by avwo** [comment]
启动whistle时设置rules可以有两种方式：
1. 启动whistle时，通过参数传进去，参考[koa-whistle](https://github.com/avwo/koa-whistle/blob/master/lib/start.js#L28)
2. 也可以自己写个插件，插件根目录里面可以设置`rules.txt`文件或者通过`rulesServer`动态设置规则，参考插件[whistle.script](https://github.com/whistle-plugins/whistle.script/blob/master/lib/rulesServer.js)

**Comment by avwo** [comment]
参考下这个应用的实现：https://github.com/nohosts/nohost
