### ISSUE TITLE
请问我想在所有的返回请求（response）中增加一段脚本或替换一部分内容，请问如何实现呢？

### ISSUE THREAD

**Issue by xunuo** [avwo/whistle#161]
请问如何实现呢？

**Comment by avwo** [comment]
根据请求响应类型可以有多种方式，具体参考[协议列表](http://wproxy.org/whistle/rules/):

1. 本地替换：
![image](https://user-images.githubusercontent.com/11450939/40006997-4e0edc2a-57ce-11e8-9f50-7f7deddddba7.png)
2. 在请求响应内容前面、后面或替换整个内容：
![image](https://user-images.githubusercontent.com/11450939/40007041-652556f0-57ce-11e8-9b85-1508626481a2.png)
3. 注入html、js、css：
![image](https://user-images.githubusercontent.com/11450939/40007062-707fdbd8-57ce-11e8-9863-9c39ef59c147.png)
4. 通过类似String.replace的方式替换指定字符串：
![image](https://user-images.githubusercontent.com/11450939/40007081-7a73c4b0-57ce-11e8-9921-f7019b89dc4f.png)
5. 替换表单或json、jsonp类型的请求响应内容：
![image](https://user-images.githubusercontent.com/11450939/40007104-83e3e002-57ce-11e8-8694-734bcd04e6ce.png)

**Comment by xunuo** [comment]
谢谢！
