### ISSUE TITLE
请问对应启动的关闭方法是什么呢？

### ISSUE THREAD

**Issue by xunuo** [avwo/whistle#163]
使用以下代码启动很好用。
`
const start = (options) => {
  return new Promise((resolve) => {
    startWhistle(options, resolve);
  }).then(function(args){...
`

但是如何关闭呢？

**Comment by avwo** [comment]
只能杀进程，事实上开着也没问题，关掉代理设置就可以

**Comment by xunuo** [comment]
谢谢，因为内嵌在了electron里面，所以杀进程会把application给一起杀掉，如果有关闭服务的方法就好了，我看到代码中似乎不止起了一个8899端口，8899应该是众多服务的一个统一对外端口对么？

**Comment by xunuo** [comment]
@avwo 如果方便，能否钉钉协助一下呢 :) i'm AE F2Eer in RU :)

**Comment by avwo** [comment]
是的，除了8899端口，其它端口都可以是随机的
