### ISSUE TITLE
Network页面，出现大量接口请求后，滑动鼠标滚轮时，接口URL会消失，然后又出现

### ISSUE THREAD

**Issue by iBobbySun** [avwo/whistle#164]
浏览器：Chrome 66
操作步骤：Newwork页面，有大量接口请求出现后，滑动一下鼠标滚轮，有大概1秒钟的时间，有部分接口的URL会消失，然后再过1秒，URL又会出现。
![1](https://user-images.githubusercontent.com/3349339/40164112-441afdce-59eb-11e8-8267-4de2e5a4f11f.png)
![2](https://user-images.githubusercontent.com/3349339/40164124-518043fc-59eb-11e8-98ab-1f6d1f322d1e.png)

**Comment by avwo** [comment]
这个是为了提升列表性能做的优化。
