### ISSUE TITLE
[建议]能否将抓取到的请求结果按http路径树展示

### ISSUE THREAD

**Issue by boafantasy** [avwo/whistle#165]
好吧,我就是想要一个类似charles的请求展示功能,  有些页面有轮询接口,一会想要的请求就刷没了

**Comment by avwo** [comment]
这个我先评估下使用场景，或者看看有没有什么替代方案。

**Comment by broven** [comment]
+1

**Comment by anderson916** [comment]
+1

**Comment by lizy0329** [comment]
现在 whistle 就是这点不够好，导致内部推广困难，测试抗拒。
还有一个点就是 APIs 有点多，压缩一半甚至更多就容易推广点

**Comment by avwo** [comment]
@lizy0329 协议多主要为了覆盖各种应用场景，你们关注一些常用的即可，比如设置hosts、本地替换、修改请求内容、修改cookie、注入脚本等等。

**Comment by lizy0329** [comment]
> @lizy0329 协议多主要为了覆盖各种应用场景，你们关注一些常用的即可，比如设置hosts、本地替换、修改请求内容、修改cookie、注入脚本等等。

能够通过传参的方式调用不同协议？

**Comment by avwo** [comment]
可以通过插件实现

**Comment by xiaowanzixll** [comment]
> 可以通过插件实现

哪个插件可以实现？

**Comment by avwo** [comment]
谁可以帮忙实现类似charles的这种树型react组件

**Comment by p2227** [comment]
+1

**Comment by grsky360** [comment]
+1

**Comment by avwo** [comment]
更新下 Whistle：https://wproxy.org/whistle/update.html
