### ISSUE TITLE
【建议】写个dockerfile吧

### ISSUE THREAD

**Issue by tomtrije** [avwo/whistle#166]
整到docker里去，这样“携带”方便，哈，还可以部署到自己的server上玩

**Comment by echopi** [comment]
你写一个给我们试试玩一下

**Comment by avwo** [comment]
@echopi 有空看下，可以弄个docker镜像

**Comment by echopi** [comment]
@tomtrije 小伙子 这个能满足你的需求不？

https://github.com/echopi/whistle-container

**Comment by tomtrije** [comment]
well done

**Comment by alanwei43** [comment]
> @tomtrije 小伙子 这个能满足你的需求不？
> 
> https://github.com/echopi/whistle-container

我看了下你运行的时候必须使用 `-p 8899:8899`，也就是必须占用主机的8899端口，当使用`-P`参数随机分配一个端口的时候，访问报这个错误，有解决办法吗？

```
From: whistle@2.3.1
Node: v12.13.1
Date: 12/18/2019, 2:09:37 PM
Error: connect ECONNREFUSED 127.0.0.1:32771
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1129:14)


Reload this page
```

**Comment by echopi** [comment]
随机端口估计不行，需要把容器的端口暴露出来
