### ISSUE TITLE
resBody://{value}  内容过多无法保存

### ISSUE THREAD

**Issue by dong2590** [avwo/whistle#170]
> Whislte Versoin:1.10.3
> Node: v8.11.2

一直使用 value 方式来调试
```
/key/ resBody://{value}
```

value 的 JSON 文本有 1.4M 时，无法保存，提示弹框如下：
![image](https://user-images.githubusercontent.com/1455816/40772718-61f71ce8-64f3-11e8-8e08-502ee0e89413.png)

调整为路径方式可以避开这个问题
```
/key/ resBody:///Users/xxxx/value.json
```
这里猜测是文本内容过多导致，但提示与场景不太符合，麻烦确认下

**Comment by avwo** [comment]
这个是whistle做的限制，浏览器处理大文本会有性能问题，建议用本地文件存储，提示这块我优化下。
