### ISSUE TITLE
需求来了：i18n和rule云同步

### ISSUE THREAD

**Issue by tomtrije** [avwo/whistle#171]
嗯，不要怀疑，我就是来找茬的，哈哈哈哈。
切入正题：
1、虽然就这么几个简单的词，也都认识，但是为了保持和浏览器界面风格统一，我还是喜欢我大汉语。来个切语言功能吧，嘿嘿，估计你得撸一遍了。
2、rule实在好用，但因为好用，可能以后规则会越来越多……数据最宝贵，虽然现在是服务端存储数据，但是还是希望这种珍贵的数据能有个外接同步备份的功能（手工备份到云端即可）。希望支持的云端：OneDrive（国内那些太不靠谱了）

**Comment by echopi** [comment]
关于同步功能的想法：whistle 要做的应该是把数据定时同步到某个目录，你的云端自己去同步相应目录的数据。

**Comment by avwo** [comment]
@echopi 说的是一种方法；另一方面 `whistle v1.11.x` 可以开放接口供插件实现。

**Comment by tomtrije** [comment]
嗯，方法可以不论，主要是要重视这份数据。

**Comment by echopi** [comment]
whistle 开放数据接口后，还是需要你去设置同步，你是期望哪个方式来实现

**Comment by tomtrije** [comment]
@echopi 怎么省事怎么来，哈。我觉得插件的方式挺好的，这样可以有多套数据源，而且这个不是核心功能，当大家贡献插件后，变相实现了。

**Comment by eshion** [comment]
配置数据能同步很有用，支持作者实现这个功能👍

**Comment by MrLaibin** [comment]
现在可以实现了吗

**Comment by avwo** [comment]
v1.6 版本会加上支持插件获取及修改规则的功能

**Comment by avwo** [comment]
已经支持，后面放出文档

**Comment by dingtwo** [comment]
所以 i18n 还会做吗

**Comment by avwo** [comment]
暂时不会，看后续情况再说。
