### ISSUE TITLE
关于命令行中mode参数的使用

### ISSUE THREAD

**Issue by AckmeYe** [avwo/whistle#172]
一直在用这款基于nodejs的Proxy工具，很是喜欢，已经完全代替了fiddler，在这里很感谢作者的无私付出。
看到w2 help的输出中有--mode的参数，但是却没有看到相关的文档，只是简单的一句`set the way of starting the whistle mode`，就希望可以有更详情点的使用说明啦~

**Comment by teal-front** [comment]
恩，不知道multiEnv是干嘛用的 /::+

**Comment by avwo** [comment]
这个是给插件扩展使用，一般用户可以忽略，等文档写好我们会推出一个支持多用户的插件

**Comment by teal-front** [comment]
恩，现在在mac倒是可以在多用户间使用不同的端口。如下所示，B用户使用8899端口时，得明确指定config目录名。  
A用户： `w2 start -p 8888`
B用户： `w2 start -p 8899 -D /Users/B/.WhistleAppData`


产品经理经常是用SwithHosts来切环境，然后浏览器经常存在host缓存，所以就想用运行多个whistle实例来充当多个环境的代理。

**Comment by avwo** [comment]
https://github.com/nohosts/nohost
