### ISSUE TITLE
关闭或重启非默认端口的实例会报错

### ISSUE THREAD

**Issue by carterzk** [avwo/whistle#174]
![image](https://user-images.githubusercontent.com/9526402/41388135-23c599ca-6fbd-11e8-8a1f-b914624b1c56.png)

开启多实例后，非默认端口的实例无法使用命令个行来关闭。而且重启会报错

**Comment by avwo** [comment]
启动时加了 `-S xxx`，重启或关闭时也要把这个带上 `w2 restart -S xxx`
