### ISSUE TITLE
Respose body显示数据的提议

### ISSUE THREAD

**Issue by NKajima** [avwo/whistle#175]
希望有个选项，Respose body遇到不可转换为纯文本的byte希望可以把返回数据全部转化为hex格式或者是base64编码，这样好处理非明文数据。（可以加个提示，该数据已被编码化以确保正常显示。）

//我记得FireFox的F12似乎是这么做的，转Base64
//这对不是全纯文本的数据能快速处理一些

Thanks a lot.

**Comment by avwo** [comment]
已经支持图片缓存预览(>= `v1.10.10`)，[重新安装下whistle](http://wproxy.org/whistle/update.html)。
其它非文本数据否要显示二进制内容，目前还没想到什么应用场景，大家如果有这块的应用场景可以提下。

**Comment by avwo** [comment]
这个加上不会很麻烦，放到后面版本迭代，得先了解下大家的需求，看下怎么做更合适

**Comment by NKajima** [comment]
好的

**Comment by avwo** [comment]
[更新下whistle](http://wproxy.org/whistle/update.html)
