### ISSUE TITLE
开启Https拦截移动端代理失效.

### ISSUE THREAD

**Issue by wbsch52** [avwo/whistle#177]
按照文档步骤配置,IOS安装完证书并信任后, 勾选 "Capture HTTPS CONNECTs" 这项后移动端所有请求都发不出去, 取消勾选 "Capture HTTPS CONNECTs" 后, 可以正常访问 whistle后台也能正常抓包, 但是抓不到Https了.

**Comment by avwo** [comment]
iOS 10.3 之后需要手动信任自定义根证书，设置路径：Settings > General > About > Certificate Trust Testings

[![image](https://user-images.githubusercontent.com/11450939/42012356-5633c590-7aca-11e8-8de7-ed21965e9d91.png)](http://wproxy.org/whistle/webui/https.html)

**Comment by wbsch52** [comment]
问题已经解决, 是我疏忽了漏了这一步. 再次感谢
