### ISSUE TITLE
iphone 扫描https 那个二维码的时候网页无法显示无法下载

### ISSUE THREAD

**Issue by HZZformGD** [avwo/whistle#178]
iphone 扫描https 那个二维码的时候网页无法显示无法下载，后来通过mac 上下载好的证书放到线上去 然后再下载就成功了， 也安装了， 然后 setting里面也把信任开关也打开了，但是手机无法抓包任何链接，手机也挂了代理

**Comment by avwo** [comment]
手机要设置好代理才可以通过二维码下载证书，看下是不是防火墙的问题：https://github.com/avwo/whistle/issues/78

**Comment by HZZformGD** [comment]
解决了。 不是代理问题 代理设置过， 后来直接吧电脑上下载的证书 放在自己线上的服务器上，然后用safari 去访问就可以了

**Comment by avwo** [comment]
参考下这个issue： https://github.com/avwo/whistle/issues/181
