### ISSUE TITLE
[建议]Request和Response内容在同一个面板上展示

### ISSUE THREAD

**Issue by luoweihua7** [avwo/whistle#180]
是否有计划将Request和Response内容在同一个面板上展示。
跟fiddler一样。
方便查看请求和响应，有些时候方便快速定位问题，而不需要频繁切换2个tab来看请求数据和响应数据 #

**Comment by avwo** [comment]
很好的建议，可以支持，这周发 `v1.11.0` 版本把 `Request` 和 `Response` 这两个Tab页合并到 `Inspectors` 里面，把 `Response/Frames` 提到跟 `Inspectors` 同级，最迟下周一(7.9)更新，可以看到最新版本的界面。
![image](https://user-images.githubusercontent.com/11450939/42233289-b4c184f0-7f23-11e8-80ad-3b641631462d.png)

**Comment by avwo** [comment]
[更新下whistle](http://wproxy.org/whistle/update.html)
