### ISSUE TITLE
https 证书下载二维码导致不能下载

### ISSUE THREAD

**Issue by maxming2333** [avwo/whistle#184]
android 手机连上了代理后，然后去扫 https 证书的 二维码

![image](https://user-images.githubusercontent.com/8816730/42555395-ae674462-851a-11e8-88ff-2881dfb824d5.png)

确实跳转到了 `http://rootca.pro/` 也有下载 `crt` 文件的提示

但是就是一直下载不下来，最后就直接下载失败

最终的解决办法就是找到自己的 ip

然后把 `http://xx.xx.xx.xx:8899/cgi-bin/rootca` 变二维码

然后再让手机扫描，这样才能正确的把 `crt` 下载下来

**Comment by avwo** [comment]
配好手机代理后，访问http网站看下whistle 能不能抓到包，如果可以，再试下用系统自带浏览器或Chrome 访问 http://rootca.pro

**Comment by maxming2333** [comment]
可以带你 http 网站，

用 chrome 访问  http://rootca.pro 是可以正常下载并且安装证书滴

但是自带浏览器下输入 http://rootca.pro

会有下载弹窗，如图

![image](https://user-images.githubusercontent.com/8816730/42562115-73154216-852d-11e8-890c-68e1d7977153.png)

然后点击下载后，就一直在连接，没办法下载，如图

![image](https://user-images.githubusercontent.com/8816730/42562145-88604d8c-852d-11e8-9a66-fad17f48e343.png)

最终下载失败

![image](https://user-images.githubusercontent.com/8816730/42562155-925d2c1a-852d-11e8-8640-b98695ce6cba.png)


我在想是不是因为自带浏览器默认开启了 `迅雷加速` 导致滴？

**Comment by jojo1900** [comment]
不要用自带浏览器，换其他浏览器就好了，我换了Edge，立马下载下来
