### ISSUE TITLE
Network列表下方的 Filter 能否支持更复杂的过滤条件？

### ISSUE THREAD

**Issue by zuibunan** [avwo/whistle#189]
Network列表下方的 Filter 过滤功能有些简单

有时候一个代理多个人使用

但我只想看到自己机器发出的网络请求

如果在Settings按钮上的filter里增加过滤，会影响其他人看到的结果

如果底部也能支持更复杂的过滤条件，就能提供一些方便，否则每个人都要自己安装代理，还得安装证书，有些麻烦

**Comment by avwo** [comment]
支持用正则 `!/xx/` 或 `/xx/`，其它高级搜索看下这个图：
![filter](https://raw.githubusercontent.com/avwo/whistleui/master/img/network.png)

**Comment by zuibunan** [comment]
@avwo 谢谢！已解决！

ps:
我看说明文档上写的是settings里支持更复杂的过滤，刚开始在Network下方试了没成功还以为不支持

http://wproxy.org/whistle/webui/settings.html
