### ISSUE TITLE
whistle 可以像nginx过滤指定的文本类型指向不同的代理地址吗？

### ISSUE THREAD

**Issue by a526672351** [avwo/whistle#19]

**Comment by avwo** [comment]
两种方式：
1. 插件实现(推荐)：[插件开发](https://avwo.github.io/whistle/plugins.html)
2. 使用dispatch协议(dispatch通过在url请求参数里面增加新的参数来匹配不同的规则)：[dispatch](https://avwo.github.io/whistle/rules/dispatch.html)

**Comment by a526672351** [comment]
有没有考虑实现一个，这样用户比较便捷使用。

**Comment by avwo** [comment]
等后续版本

**Comment by avwo** [comment]
更新版本：[v1.2.0+](https://avwo.github.io/whistle/update.html)
参考新增协议: [rulesFile](https://avwo.github.io/whistle/rules/rulesFile.html)
