### ISSUE TITLE
whistle启动以后一直掉线

### ISSUE THREAD

**Issue by yanaca** [avwo/whistle#190]
昨天电脑重启以后，通过chrome打开whistle一会儿online，一会儿offline。 把whistle和proxy卸载重装以后依然会出现。重启也无效。防火墙一直是关闭的，近期没有更新过chrome，版本是60.0.3112.90（正式版本）（64 位），求指教。

**Comment by avwo** [comment]
[更新whistle](http://wproxy.org/whistle/update.html)，如果还有问题，试试设置下注册表：https://github.com/request/request/issues/210#issuecomment-234630155

**Comment by yanaca** [comment]
最新版本也会。之前启动whistle以后本地ip有变过，不确定是否有关系。刚重启电脑以后恢复了。感谢大神、
