### ISSUE TITLE
抓不到小程序开发工具发出的请求

### ISSUE THREAD

**Issue by Yilene** [avwo/whistle#191]
小程序开发工具 发出的请求抓不到具体的请求和返回数据

![_1ab5b0bf-1008-433f-a40c-fb992807265d](https://user-images.githubusercontent.com/14181808/43199522-dc1e68f6-9044-11e8-8ebd-f6a8dbb6730d.png)

**Comment by avwo** [comment]
安装证书，开启拦截https请求：http://wproxy.org/whistle/webui/https.html

**Comment by hoyangtsai** [comment]
+1
已經在微信開發工具設置手動代理、安裝證書，確實無法在netwrok面板顯示cdn資源的請求
