### ISSUE TITLE
做了一个whistle第三方chrome插件，欢迎试用

### ISSUE THREAD

**Issue by thesadboy** [avwo/whistle#192]
[whistle 第三方插件](https://chrome.google.com/webstore/detail/whistle-rules-plugin-by-n/ibhpjiafjijjpofblhamncmhlicfcofm) chrome 快速切换规则插件，欢迎试用，哈哈

**Comment by avwo** [comment]
能不能把代理设置这块也加上

**Comment by thesadboy** [comment]
@avwo 感觉这块好像没有太大的必要，毕竟还是在原有的界面去设置比较方便一点，哈哈，那块popup页面的话做太重好像不是很好，下面就有个更多设置就直接跳转到对应的界面去了

**Comment by avwo** [comment]
这个插件用来快速切换规则还是挺方便，我说的是设置Chrome的代理，之前做过一个，后来不知什么原因被禁了：https://github.com/avwo/whistle-for-chrome

**Comment by thesadboy** [comment]
@avwo 了解了，哈哈，我瞅瞅

**Comment by thesadboy** [comment]
@avwo 新上了一个版本，看看

**Comment by Pain-and-Love** [comment]
如果可以设置 【开启全局系统代理】 就好了。

**Comment by xiaobebe** [comment]
被Chrome下线了呀朋友！

**Comment by avwo** [comment]
@xiaobebe 用这个试试 https://github.com/avwo/whistle/issues/405

**Comment by thesadboy** [comment]
> 被Chrome下线了呀朋友！

重新提交审核看看，chrome这个审核太坑爹了。。

**Comment by thesadboy** [comment]
> 被Chrome下线了呀朋友！

已重新上架了。。。。

**Comment by thesadboy** [comment]
@avwo 已重新上架
