### ISSUE TITLE
http://local.whistlejs.com/#network 无法访问

### ISSUE THREAD

**Issue by Ouyangan** [avwo/whistle#193]
服务启动正常,使用chromewhistlejs插件,http://127.0.0.1:8899/可以访问,但是换成域名则不行

console报错:
Uncaught TypeError: Cannot read property 'parentNode' of undefined
    at cs.js:26
    at cs.js:27

**Comment by avwo** [comment]
配代理后才能用域名访问

**Comment by Ouyangan** [comment]
感谢~是我设置多个代理端口,未启用whistle代理
