### ISSUE TITLE
请问规则匹配里面有没有单向匹配的选择？

### ISSUE THREAD

**Issue by flyweights** [avwo/whistle#194]
例子：
 127.0.0.1:8080 aaa.bbb.com  
 是把我所有请求里的 127.0.0.1:8080 转为 aaa.bbb.com
 但是我的环境里面刚好有用到 aaa.bbb.com，它又把aaa.bbb.com 转为了127.0.0.1:8080
请问规则匹配里面有没有单向匹配的选择？

**Comment by avwo** [comment]
你这种配置只会对 `aaa.bbb.com` 生效，不会对 `127.0.0.1:8080` 生效，要对 `127.0.0.1:8080`生效可以配成 `http://127.0.0.1:8080 www.qq.com`
