### ISSUE TITLE
capture https connections to specific websites

### ISSUE THREAD

**Issue by davisbra** [avwo/whistle#196]
How can I capture https connection to a specific websites url?
I want to capture only predefined https address , how can I do this?

**Comment by avwo** [comment]
www.test.com enable://capture

**Comment by davisbra** [comment]
I want to edit source code and add a website name to capture https connection,which source file I must edit?
for example I want to capture connections to https://www.github.com when https capturing enabled 
how can I do this?
can you tell me more about this?
thanks
