### ISSUE TITLE
如何让别人使用我的代理时先输入密码？

### ISSUE THREAD

**Issue by xiaobebe** [avwo/whistle#199]
如何让别人使用我的代理时先输入密码？
请问有办法解决吗？

**Comment by avwo** [comment]
可以用[whistle.proxyauth](https://github.com/whistle-plugins/whistle.proxyauth)这个插件，或者按照上面的方式自己开发一个。

**Comment by pen9un** [comment]
@avwo 启动参数设置：-n username -w password这个可以限制后台界面的访问，Whislte的代理是否也能设置用户名密码呢，如给浏览器设置Whistle的代理时除了设置IP127.0.0.1和端口号8899，还需要设置用户名username和密码password才可以访问。请问怎么操作或怎么实现，谢谢！

**Comment by avwo** [comment]
https://github.com/whistle-plugins/whistle.proxyauth

**Comment by pen9un** [comment]
@avwo 收到，可以实现，谢谢！

**Comment by huanshiwushuang** [comment]
> https://github.com/whistle-plugins/whistle.proxyauth

似乎这个插件实现的密码验证 不能通过whistle内置的proxy或者http-proxy 实现自动登录?
需要打开网页的时候,手动输入用户名和密码
我在手机山通过 postern 设置的代理服务器,也是如此.
是否有其他更好的插件替代呢?或者是我没掌握到如何使用这个whistle.proxyauth?

**Comment by avwo** [comment]
这个是限制访问whistle 的请求，如果要转发到上层代理，可以通过 proxy://name:pass@host:port 设置密码

**Comment by huanshiwushuang** [comment]
> 这个是限制访问whistle 的请求，如果要转发到上层代理，可以通过 proxy://name:pass@host:port 设置密码

给whistle1 设置了密码，是否能够在另一个whistle2 这样  proxy://name:pass@whistle1:8899  访问whistle1

**Comment by avwo** [comment]
可以

**Comment by huanshiwushuang** [comment]
> 可以
whistle1：/./ whistle.proxyauth://name:pass
whistle2：/./ proxy://name:pass@ip:port
尽管我这样做了，但是浏览器仍然向我询问密码

**Comment by Su-yj** [comment]
> > 可以
> > whistle1：/./ whistle.proxyauth://name:pass
> > whistle2：/./ proxy://name:pass@ip:port
> > 尽管我这样做了，但是浏览器仍然向我询问密码

请问这问题有解决方法吗？
我也是有这样的需求，每个代理请求必须带上账号密码来验证。
但proxuauth这插件只是对浏览器第一次打开时验证而已，后面都不会再继续校验账号密码。

希望达到的效果是，在每次代理连接时校验。如python的requests：
```python
requests.get(url, proxies={'http': 'http://username:password@ip:host', 'https': 'http://username:password@ip:host'})
```

但目前 https://github.com/whistle-plugins/whistle.proxyauth 是无法满足这一需求的

**Comment by avwo** [comment]
参考 whistle.proxyauth 自己写插件实现

**Comment by lonnywong** [comment]
@avwo 
在使用 http 代理时，可能会需要用户名和密码，这个很常见。
那么 whistle 作为一个 http 代理，能否也要求客户端输入用户名和密码呢？

**Comment by avwo** [comment]
启动参数 -n test -w 123

**Comment by lonnywong** [comment]
> 启动参数 -n test -w 123

好像不起作用的样子，`-n test -w 123` 只是让访问控制台时要输入密码。

在客户端设置 whistle 为 http 代理时，不需入密码也能使用 whistle 作为代理 。

**Comment by avwo** [comment]
https://github.com/whistle-plugins/whistle.proxyauth

**Comment by lonnywong** [comment]
> https://github.com/whistle-plugins/whistle.proxyauth

这个并不能适配代理客户端输入用户名和密码的场景。

![65E2B9D1-8436-4976-A7D8-AAA0167AE488](https://user-images.githubusercontent.com/20320324/163837646-e4833037-b13a-4063-ae2b-ea184fce8b02.jpeg)

**Comment by zgr0629** [comment]
上面提到的插件应该是还没有解决标准http代理帐号密码的问题

**Comment by avwo** [comment]
> > https://github.com/whistle-plugins/whistle.proxyauth
> 
> 这个并不能适配代理客户端输入用户名和密码的场景。
> 
> ![65E2B9D1-8436-4976-A7D8-AAA0167AE488](https://user-images.githubusercontent.com/20320324/163837646-e4833037-b13a-4063-ae2b-ea184fce8b02.jpeg)

这里设置得用户名和密码不会带到请求里，可以自己网上搜搜原因。
