### ISSUE TITLE
长时间开着代理，替换的请求会无法得到

### ISSUE THREAD

**Issue by jruif** [avwo/whistle#2]
RT，现在我得到的解决是重启代理就好了。

**Comment by avwo** [comment]
是配置失效了，还是请求发不出去，whistle的[Network](http://local.whistlejs.com/#network)能看到请求吗？

**Comment by jruif** [comment]
是请求得不到响应，请求也是能看到的。
这事overview
-------------
> Url	http://xxx.com/static/js/vendor.js
> Real Url	http://127.0.0.1:3100/static/js/vendor.js
> Method	GET
> Http Version	1.1
> Status Code	aborted
> Status Message	
> Host IP	127.0.0.1
> Client IP	127.0.0.1
> Request Length	0
> Content Length	
> Start Date	2016/2/25 下午4:53:37
> DNS Lookup	0ms
> Request Sent	1ms
> Response Headers	36001ms
> Content Download	36001ms
----------
> rule	http://xxx.com/static http://127.0.0.1:3100/static/

**Comment by avwo** [comment]
我重试了下没有出现你说的情况，从这些信息来看，是[http://127.0.0.1:3100/static/xxx](http://127.0.0.1:3100/static/xxx)一直hold着没有返回，下次出现这种情况，直接访问[http://127.0.0.1:3100/static/xxx](http://127.0.0.1:3100/static/xxx)看下是否正常，或者重启下你本地的静态服务器看看。

PS：如果只是替换本地静态文件，可以用这两个功能：[file](https://github.com/avwo/whistle/wiki/%E5%8A%9F%E8%83%BD%E5%88%97%E8%A1%A8#file) 或 [xfile](https://github.com/avwo/whistle/wiki/%E5%8A%9F%E8%83%BD%E5%88%97%E8%A1%A8#xfile)

有问题可以加QQ群反馈：462558941

**Comment by avwo** [comment]
@jruif 你本地服务器用什么搭建的？初步定位是tcp连接复用导致的问题，对某些服务器会出现这种情况，如果出现这个问题的域名，可以先用 `xxx.yyy.com disable://keepAlive` 对特定域名禁用tcp连接复用，后面我再发新的版本fix这个问题

**Comment by jruif** [comment]
自己使用node搭建的本地测试服务器。

**Comment by avwo** [comment]
已fix，[更新whistle](https://github.com/avwo/whistle/wiki/%E6%9B%B4%E6%96%B0whistle)
