### ISSUE TITLE
安装根证书：缺少此客户端证书的私钥，或私钥无效。

### ISSUE THREAD

**Issue by ghost** [avwo/whistle#20]
我是ubuntu，用chromium导入rootCA报了这个错误：缺少此客户端证书的私钥，或私钥无效。

**Comment by echopi** [comment]
@owyowoo 看到类似问题，看看[这个方案](https://github.com/XX-net/XX-Net/issues/3911#issuecomment-234158553)能不能work

**Comment by echopi** [comment]
摘自上面链接，步骤如下：

Go to Chrome's 'Settings' via the right hand button or this URL in address bar

chrome://chrome/settings/

> Show advanced Settings > Manage certificates > Authorities > Import , browse to the certificate you saved (e.g. www.scaryscary.com.pem) and import

Tick 'trust this Ceritificate for identifying web sites', Ok.
