### ISSUE TITLE
每次都需要配置很多才能使用么？

### ISSUE THREAD

**Issue by mansonami** [avwo/whistle#200]
新人：每次都需要配置很多才能使用么？

**Comment by avwo** [comment]
主要是 设置代理 和 安装根证书，步骤是可以简化，有空研究下或着看看有什么好的第三方工具来协助做这个事情。

**Comment by mansonami** [comment]
感谢回答。能不能写个简单简单配置，可以抓github的例子，高级的地方按照例子就好配置了。

**Comment by avwo** [comment]
按文档操作一遍
