### ISSUE TITLE
可以支持https代理吗？

### ISSUE THREAD

**Issue by snadn** [avwo/whistle#201]
目前支持的代理有 http 和 socks，可否增加对 https 代理的支持？

**Comment by echopi** [comment]
文档：http://wproxy.org/whistle/webui/https.html

**Comment by snadn** [comment]
@echopi 不是指支持抓https的包，而是支持https的代理。类似支持规则：

```hosts
https://github.com socks://127.0.0.1:1080 # 已有规则
https://github.com http-proxy://myproxy.com # 已有规则
https://github.com https-proxy://myproxy.com # 期望支持的规则
```

**Comment by avwo** [comment]
@snadn 你那边有什么应用场景，https-proxy很少用到

**Comment by snadn** [comment]
@avwo 确实很少用到，场景就是我偶尔把 `whistle` 当本地代理用，访问的部分页面得用我服务器的https代理。

**Comment by avwo** [comment]
你的https代理用什么搭的，我这边搭一个试试

**Comment by snadn** [comment]
@avwo caddy

**Comment by avwo** [comment]
更新下whistle，`v1.12.3`版本开始支持[https-proxy](http://wproxy.org/whistle/rules/https-proxy.html)

**Comment by snadn** [comment]
@avwo 验证了一下，无 basic auth 的时候可以，有 basic auth 的时候 407。 应该是 basic auth 的配置未生效。

**Comment by avwo** [comment]
确实会有这个问题，[更新下whistle](http://wproxy.org/whistle/update.html)

**Comment by snadn** [comment]
最新的 ok 了！
