### ISSUE TITLE
取非匹配问题

### ISSUE THREAD

**Issue by lxjwlt** [avwo/whistle#203]
设置规则：

```
* proxy://127.0.0.1:12759
!/jpg$/ host://1.1.1.1
```

访问`xxx/xx.jpg`，最终指向：

```
Server IP: 1.1.1.1
Server Port: 12759
```

port指向12759，但ip却指向1.1.1.1

**Comment by avwo** [comment]
这里的 `1.1.1.1` 是代理服务器 `proxy://127.0.0.1:12759` 地址匹配到，因为没有设置类似 `!/jpg$/ 1.1.1.1:9999`  这样的端口，所以会延用proxy设置的端口 `12759`

**Comment by lxjwlt** [comment]
@avwo `!/jpg$/` 的意思是，所有不包含`jpg`的URL都匹配 1.1.1.1 服务器，是这样吧？ 当我访问`xxx/xx.jpg`的时候，正确情况下应该访问127.0.0.1吧？但最终server IP 却走到了1.1.1.1

端口12759是符合预期的

**Comment by avwo** [comment]
因为你配了代理，代理地址也会解析host

**Comment by avwo** [comment]
```
* proxy://127.0.0.1:12759
!/(jpg|:12759\/)$/ 1.1.1.1
```
PS: 注意根URL后面有个 `/`
