### ISSUE TITLE
win10 https一直不行

### ISSUE THREAD

**Issue by fhqdgv** [avwo/whistle#204]
证书按照文档装了N多次，一打开网页就显示“此网站无法提供安全连接”，用http就正常
whistle@1.12.2 started
node v8.11.4

**Comment by avwo** [comment]
安装证书第二步要选择 `浏览 -> 受信任的根证书颁发机构 `
![ca](http://wproxy.org/whistle/img/windows_rootca.jpeg)

**Comment by fhqdgv** [comment]
谢谢回复，我之前就是这样安装的 证书也确实安装成功了  但就是访问不了

**Comment by avwo** [comment]
可以不restart，重新打开浏览器也可以，好的，我这边加个提醒
