### ISSUE TITLE
Maximum size of users for each port

### ISSUE THREAD

**Issue by davidjanson2020** [avwo/whistle#207]
what is the maximum size of users can connect to a port ?
and what is the maximum count of instance can run whistle in different ports?

**Comment by avwo** [comment]
whistle is a debugging tool. It is not recommended for use in the production environment. There are no specific tests for how many people can connect it on the sametime, but it is okay for our department to share a public whistle with more than 200 people.

**Comment by avwo** [comment]
https://github.com/nohosts/nohost
