### ISSUE TITLE
可否实现whistle rules的共享 

### ISSUE THREAD

**Issue by chongtianHong** [avwo/whistle#208]
如题，麻烦帮忙解答一下，谢谢

**Comment by avwo** [comment]
在规则列表中，右键可以导入导出（如果按 `shift` 再点击 `Import` 可以远程导入）：
![image](https://user-images.githubusercontent.com/11450939/45014119-00144200-b050-11e8-9cf1-df3105d629bb.png)

**Comment by chongtianHong** [comment]
请问在哪里修改导出的文件路径，现在导出的是在C:\Users\xxx\Downloads目录下。

**Comment by avwo** [comment]
这个是Chrome默认下载目录，自己看下怎么修改这个目录地址

**Comment by chongtianHong** [comment]
好的，谢谢您的解答~

**Comment by a526672351** [comment]
@avwo 可以兼容switch host 远程.txt格式文件吗？

**Comment by avwo** [comment]
兼容的
