### ISSUE TITLE
mac chrome 代理 https 出现 socket hang up

### ISSUE THREAD

**Issue by flycj** [avwo/whistle#211]
环境：mac os 10.13.6 
whistle : 1.12.5
node : v9.11.1
chrome : 68.0.3440.106
代理工具：SwitchyOmega
代理配置：http  127.0.0.1 8899

代理http 网站正常，但是最近网站升级为https 后， 按照https://whistle.gitbooks.io/help/content/webui/https.html 这个说明安装了 证书
然后选上 Capture HTTPS CONNECTs
打开浏览器，出现：

From: whistle@1.12.5
Node: v9.11.1
Date: 2018-9-7 10:05:20
Error: socket hang up
    at TLSSocket.onConnectEnd (_tls_wrap.js:1083:19)
    at Object.onceWrapper (events.js:272:13)
    at TLSSocket.emit (events.js:185:15)
    at endReadableNT (_stream_readable.js:1106:12)
    at process._tickCallback (internal/process/next_tick.js:178:19)

Reload this page

请问怎么处理呢？

**Comment by flycj** [comment]
whistle 的请求列表
![image](https://user-images.githubusercontent.com/5103045/45194811-3b4c8600-b287-11e8-90da-b902552f6c8d.png)
下面是配置
![image](https://user-images.githubusercontent.com/5103045/45194833-5c14db80-b287-11e8-9593-976e6d981d7b.png)

**Comment by avwo** [comment]
把配置改成 `static.pkg.cn 127.0.0.1:3030` 试试

**Comment by flycj** [comment]
![image](https://user-images.githubusercontent.com/5103045/45197605-c2ecc180-b294-11e8-8507-36f51645b0b3.png)
改了之后
![image](https://user-images.githubusercontent.com/5103045/45197625-dbf57280-b294-11e8-851e-e1ea2ec84b7e.png)
网站出现这个情况
访问这个网址 http://local.whistlejs.com/#network
![image](https://user-images.githubusercontent.com/5103045/45197655-fd565e80-b294-11e8-977c-5759333b3643.png)

**Comment by flycj** [comment]
w2 restart 端口是 8899
![image](https://user-images.githubusercontent.com/5103045/45197785-b1f08000-b295-11e8-90cd-ab7ff0e4593d.png)

**Comment by avwo** [comment]
代理配置的端口为8899，不是3030，用http访问试试

**Comment by flycj** [comment]
现在网站强制把http 转为 https了

**Comment by flycj** [comment]
没转https 前，配置一切都正常的，对了 ，这个代理https 需要要服务器支持TLS1.2 吗，因为服务器是win2003的，不支持TLS1.2

**Comment by flycj** [comment]
我改了 static.pkg.cn host://127.0.0.1:3030 试过，还是同样的错误

**Comment by avwo** [comment]
有可能，网上搜下怎么解决
