### ISSUE TITLE
不能配合proxifier 使用吗？

### ISSUE THREAD

**Issue by xiaobebe** [avwo/whistle#212]
我现在在开发一个Electron应用，需要使用whistle做一些mock数据。

但是发现没有好的代理方式，使用proxifier代理后却发现无法访问到。

**Comment by xiaobebe** [comment]
我是Mac系统，代理的本地文件，然后提醒DNS解析错误。

![image](https://user-images.githubusercontent.com/19386356/45256572-d13cf980-b3ca-11e8-9ba7-774f97ae56d4.png)

**Comment by avwo** [comment]
本地替换用 http://wproxy.org/whistle/rules/rule/file.html

**Comment by xiaobebe** [comment]
```
http://api.com/getNewUser xfile:///Users/ado/Code/electron-react-three-wall/mock/getNewUser.json
```

我是这样配置的，然后想配合proxifier使用，发现访问不到

**Comment by xiaobebe** [comment]
我试了一下，其他的都可以代理。
就是file代理不了。

![image](https://user-images.githubusercontent.com/19386356/45261418-4a246b80-b434-11e8-8f56-ce5b969db971.png)

**Comment by avwo** [comment]
xfile本地没匹配文件会自动请求线上，请求线上的时候，你这个域名没配dns所以报这个错，用file试试，且在Overview里面看看有没有匹配到规则

**Comment by xiaobebe** [comment]
```
http://apidddddddddd.com/getNewUser file:///Users/ado/Code/electron-react-three-wall/mock/getNewUser.json
```

使用了这样的规则。使用proxifier代理了全局。然后终端输入：

```
curl -G http://apidddddddddd.com/getNewUser
```

返回结果：

```
Acurl: (56) Recv failure: Connection reset by peer
```
