### ISSUE TITLE
Mac上配置开机重启whistle 提示 zsh: 1: command not found: whistle

### ISSUE THREAD

**Issue by ianhu92** [avwo/whistle#213]
Mac上配置开机重启whistle
提示:
The action “Run Shell Script” encountered an error: “zsh:1: command not found: whistle”

**Comment by avwo** [comment]
是全局安装的吗，看下安装路径，不行的话自己配个PATH

**Comment by ianhu92** [comment]
是通过npm -g 全局安装的，terminal里输入 whistle 能找到。但是这个放到mac应用程序里面的，双击就会报错。
不太清楚双击是以什么方式执行的。。

**Comment by avwo** [comment]
zsh的问题，配下path

**Comment by ianhu92** [comment]
自己通过Automator重写了脚本，生成应用 解决了。
`NVM_DIR=$HOME/.nvm
PATH=$PATH:$NVM_DIR/current/bin:/usr/local/bin
whistle restart`
我是通过nvm安装的node，在脚本里自己指定下node和whistle的path之后就可以执行了。

**Comment by Yuiffy** [comment]
同样问题，我也是nvm里的node里装的whistle，用Automator打开应用程序里的whistle，改代码：
```
NVM_DIR=$HOME/.nvm
PATH=$PATH:$NVM_DIR/versions/node/v13.10.1/bin:/usr/local/bin
whistle restart
```
因为我好像没有```$NVM_DIR/current```目录
