### ISSUE TITLE
it's not work in chrome69，升级了chrome69部分无法工作？

### ISSUE THREAD

**Issue by chenqipc** [avwo/whistle#216]
^myhost/***/$%7Bstyle_server_uri%7D/***  https://myhost/$2
i use this rule in my setting, recently i found it not worked in chrome69. I try to rewirte the setting,but it also not worked, so i downgrade the chrome to 68, it worked agin.   chrome69 is a grate verision i think, i want use whistle in chrome69. Thank you very much, hope your response.thank you.

我一直使用上边的规则，但是最近发现它在Chrome69无法工作，我尝试重写配置，但还是无法工作，我把Chrome降级到68，然后规则生效。我觉得Chrome69看起来不错，我想在Chrome69使用我们的whistle。谢谢，期待您的回复。

**Comment by avwo** [comment]
可以的，检查下请求有没有匹配规则
![image](https://user-images.githubusercontent.com/11450939/45675806-c1f44380-bb62-11e8-85af-f5430f3b3ab8.png)
