### ISSUE TITLE
文档拼写错误反馈

### ISSUE THREAD

**Issue by greatcl** [avwo/whistle#217]
1. [安装启动页面](https://whistle.gitbooks.io/help/content/install.html)
`4. 配置代理` => `2. 默认端口...`里, 启动时 写成了 **启动是**
2. [Composer页面](https://whistle.gitbooks.io/help/content/webui/composer.html)
页面标题写成**Componser**了

**Comment by avwo** [comment]
感谢反馈，已经fix，gitbook上的文档已经迁到：http://wproxy.org/whistle/ ，不要再用gitbook上的文档
