### ISSUE TITLE
启动多个实例后。只有一个whistle能抓到https请求

### ISSUE THREAD

**Issue by carterzk** [avwo/whistle#218]
1、启动多个whistle实例，端口分别为9901,9902
2、用ios水果机安装证书后，链接9901进行代理，https请求正常
3、改为9902进行代理，https无法请求。
4、重新装证书后，还是上述问题。
请问这个是什么问题。
另外从咨询下哪里能看到whistle自身的系统日志。

**Comment by avwo** [comment]
不要用连续端口，尽量间隔3个端口号 9902 9905

**Comment by carterzk** [comment]
试了下。我这里间隔大概10个端口号才正常抓取https；为何会有这种问题呢。。

**Comment by avwo** [comment]
里面会起一些内部服务，像webui，它们会先检测下个端口有没有被占用，如果没有就拿来用，有的话就找一个随机端口

**Comment by avwo** [comment]
https://github.com/nohosts/nohost
