### ISSUE TITLE
pc上chrome安装证书无效

### ISSUE THREAD

**Issue by dong2590** [avwo/whistle#22]
环境
os: windows 7 64bit
nodejs:v5.10.0

![qq 20161124145836](https://cloud.githubusercontent.com/assets/1455816/20589317/a346f1b0-b256-11e6-9998-1c2cdbfc571d.png)
如图，在pc上访问https站点时被知证书无效。
 @安装证书`rootCA.crt`时，确认保存在**受信任的根证书颁发机构**中，问题出现在pc上，Android和iOS都正常，麻烦 @avwo 解答，多谢：）

==============我是分隔线============
现在问题解决了，麻烦@avwo 关闭这个issue，
**解决方法贴在这，供参考**

问题原因：域账号无法添加`rootCA.crt`，至**受信任的根证书颁发机构**证书列表中

步骤：
1. [取消证书验证](https://technet.microsoft.com/zh-cn/library/cc754841(v=ws.11).aspx#BKMK_managedomain)
![1](https://cloud.githubusercontent.com/assets/1455816/20594904/df90a802-b272-11e6-8520-a615c452ee6b.jpg)

2.[导入证书](https://technet.microsoft.com/zh-cn/library/cc754841(v=ws.11).aspx#BKMK_addlocal)

3.全选证书目的：打开IE -> Internet选项 -> 内容 -> 证书 ->高级
![2](https://cloud.githubusercontent.com/assets/1455816/20594948/08a103fe-b273-11e6-9f15-ee89c93bfcd9.png)

经过以上步骤，问题解决了

**Comment by avwo** [comment]
没把rootCA.crt安装到“受信任的根证书颁发机构”，参考这个：[http://program.most.gov.cn/cert/ca.htm](http://program.most.gov.cn/cert/ca.htm)

注意选择安装路径这个步骤：
![选择安装路径](http://program.most.gov.cn/cert/ima/5.gif)

**Comment by dong2590** [comment]
我确实是安装在**受信任的根证书颁发机构**中了，试过多次了，百思不得其解……

**Comment by avwo** [comment]
把其它路径的whistle根证书清除干净：IE -> Internet选项 -> 内容 -> 证书

**Comment by dong2590** [comment]
问题原因找到了，机器入过公司域，使用域账号登录，策略限制无法将证书加入“受信任的根证书颁发机构”中，虽然显示导入成功，但无法在证书列表中找到。
