### ISSUE TITLE
reqCookies 操作协议不生效

### ISSUE THREAD

**Issue by zarkin404** [avwo/whistle#220]
1、在 Rules 中配置规则 `local.test   reqCookies://{test.json}`
2、在 Values 中添加文件 `test.json`，并在其中添加键值对`status: 1`
3、访问 local.test，请求头部中的 cookies 并没有 `status=1` 字样

**Comment by avwo** [comment]
这种修改是在请求中间做的，要在whistle 的Network 才能看到，Chrome 自带开发者工具是看不到的
