### ISSUE TITLE
请教一下whistle.script怎么指定代理呢？

### ISSUE THREAD

**Issue by Mackerly** [avwo/whistle#222]
我又来啦，请问在使用whistle.script的时候，要怎么设置rule才能走http/socks代理呢？？直接在rule里面添加 /google/ http://ssr:port 提示500error.
`exports.handleRequest = function* (ctx, next) {
   
 };`

**Comment by avwo** [comment]
script 里面有全局的request对象，可以通过 const r = request.defaults({ proxy: ’http://proxyHost:proxyPort’})的方式获取带代理的request 对象，让后在handleRequest方法里面获取请求url，headers, method灯自己构造请求，看下文档里面代码的注释，socks要自己引入模块实现

**Comment by avwo** [comment]
新版whistle插件的请求可以走回whistle，很容易实现各种代理，等有空再把 https://github.com/whistle-plugins/whistle.script 改造下。

**Comment by avwo** [comment]
Transfer to https://github.com/whistle-plugins/whistle.script/issues/11
