### ISSUE TITLE
ios上抓不到ws请求

### ISSUE THREAD

**Issue by fengguangke** [avwo/whistle#224]
同一个app应用，Android是可以抓到ws请求，ios就是不行，无解。HTTP\HTTPS的请求都可以正常抓到请求

**Comment by avwo** [comment]
先确认下iOS的websocket请求是不是正常发出，还有如果APP里面嵌得是h5页面，用浏览器打开页面试试看能不能抓到。

**Comment by fengguangke** [comment]
> 先确认下iOS的websocket请求是不是正常发出，还有如果APP里面嵌得是h5页面，用浏览器打开页面试试看能不能抓到。

请求是正常发出的，应用可以正常使用，我们嵌入不是H5，是react native应用，但Android又是可以正常抓到ws请求
