### ISSUE TITLE
兼容shadowsocks？

### ISSUE THREAD

**Issue by GoToBoy** [avwo/whistle#225]
1、关闭shadowsocks会清空代理设置
2、使用shadowsocks，抓不到请求包

<img width="597" alt="image" src="https://user-images.githubusercontent.com/2384105/47065720-907c9f80-d216-11e8-9ac7-4331df38da19.png">

<img width="674" alt="image" src="https://user-images.githubusercontent.com/2384105/47065733-9d998e80-d216-11e8-8927-f8eab2b909e4.png">

**Comment by avwo** [comment]
`Web Proxy (HTTP)` 和 `Secure Web Proxy (HTTPS)` 都要配上并勾选，**其它的配置都要去掉勾选**，如果你要用shadowsocks，可以在whistle里用[socks](http://wproxy.org/whistle/rules/socks.html)把对应请转发到shadowsocks的客户端
![image](https://user-images.githubusercontent.com/11450939/47068595-4815af80-d21f-11e8-923e-b87c0518e849.png)

**Comment by GoToBoy** [comment]
谢谢，现在用proxifier代理成功

**Comment by tanghengvip** [comment]
> `Web Proxy (HTTP)` 和 `Secure Web Proxy (HTTPS)` 都要配上并勾选，**其它的配置都要去掉勾选**，也可以用proxifier代替配置系统代理：https://github.com/avwo/whistle-for-chrome
> PS：如果你要用shadowsocks，可以在whistle里用[socks](http://wproxy.org/whistle/rules/socks.html)把对应请转发到shadowsocks的客户端
> ![image](https://user-images.githubusercontent.com/11450939/47068595-4815af80-d21f-11e8-923e-b87c0518e849.png)

谢谢！！！

**Comment by avwo** [comment]
用最新版本，启动时可以设置 socks 端口 `--socksPort 1080`
