### ISSUE TITLE
如果遇到无法访问whistle文档，尝试下用https访问：https://wproxy.org/

### ISSUE THREAD

**Issue by avwo** [avwo/whistle#226]
RT: https://wproxy.org/

**Comment by avwo** [comment]
如果还是访问不了，直接访问github上的文档仓库：https://github.com/avwo/whistle/blob/master/docs/zh/SUMMARY.md

**Comment by iFwu** [comment]
这个是什么原因造成的呢？是 wproxy.org 对 whistle 代理做了检测吗？我让 whistle 连接另一个代理，结果是可以访问

**Comment by avwo** [comment]
跟whistle无关，可能跟带proxy关键词有关，具体原因还未知。

**Comment by iFwu** [comment]
我有空用底层抓包工具看下～

**Comment by iFwu** [comment]
Hello, @avwo @aaronzw01 
我已经定位到了该问题的原因，这是深层次的网络屏蔽导致的（Great Firewall）。
具体表现为：
wproxy.org为一个CNAME指向到avwo.github.io的记录，该记录有如下字段：
```
Name:	avwo.github.io
Address: 185.199.110.153
Name:	avwo.github.io
Address: 185.199.108.153
Name:	avwo.github.io
Address: 185.199.109.153
Name:	avwo.github.io
Address: 185.199.111.153
```
（顺序可能会改变）

而出现问题的IP地址是185.199.108.153，任何发往该域名80端口的TCP连接在第一次握手时会直接被Firewall给RST掉。
也就是说，如果你手动设置wproxy.org的host为185.199.108.153，则在未翻墙的情况下，会无法访问。

故解决方法很简单：翻墙。然而Whistle并不是一个翻墙代理，所以真的很难让这个网页在Whistle开启的情况下进行访问（除非使用VPN Tunnel，如IPSec等）。

至于为什么在Whistle代理下就特别容易无法访问（如果关闭Whistle，就可以访问），我觉得可能是Whistle接管了dns处理，然后node.js的dns处理与浏览器行为不一致（比如CNAME可能只会返回排序最前面的IP地址，也就是185.199.108.153，这部分要扒V8源码了）导致的，浏览器可能在某CNAME的IP无法访问时自动尝试连接另一个IP，而Whistle并未作此处理（也可以做，但没必要，毕竟不是一个通用Client）。

**Comment by avwo** [comment]
多谢分享，后面尝试把中文文档部署在国内的服务器，并去掉github上的cname，沿用wproxy.org域名，英文文档还是放avwo.github.io，看下能否解决这个问题
