### ISSUE TITLE
锚点模式下的url#匹配问题

### ISSUE THREAD

**Issue by HZZformGD** [avwo/whistle#227]
锚点模式下的url#匹配问题 
rules 里面这么写
`hostname://{url} js://{manhua.js}`

values 里面
 
`url` 内容 `http://www.test.com/spa/details/wxindex/wx.php#/artcleDetails/225`

`manhua.js` 内容 `alert('a');`

匹配无效 想问下 怎么写rules 才是正确的

**Comment by avwo** [comment]
hash不会发到后台

**Comment by avwo** [comment]
路径里面的#及后面还有字符串不会带到server，你用Chrome的开发者工具抓包看看就清楚了

**Comment by xiaogeneral** [comment]
> 路径里面的#及后面还有字符串不会带到server，你用Chrome的开发者工具抓包看看就清楚了

原来是这样的，谢谢大佬的指点
