### ISSUE TITLE
Node v11.0.0&v11.1.0 版本的timer模块有bug，会导致whistle卡死，暂不要使用v11版本

### ISSUE THREAD

**Issue by avwo** [avwo/whistle#231]
详细内容参见：https://github.com/nodejs/node/issues/23860

**Comment by apapirovski** [comment]
@avwo I just tested this package against 11.1.0 and I couldn't reproduce. Could you provide a test case that fails on 11.1.0?

**Comment by avwo** [comment]
`Node 11.2.0` 版本开始可以正常使用
