### ISSUE TITLE
.io 域名无法抓取log

### ISSUE THREAD

**Issue by xluos** [avwo/whistle#232]
我想查看GitHub Page在手机页面的log时，发现配置了
`[xluos.github.io](url) log://`刷新过后也无法抓到这个页面的log输出。其他页面使用都是正常的，不知道这是否是一个bug

**Comment by avwo** [comment]
你是不是配错了
![image](https://user-images.githubusercontent.com/11450939/47615358-cf4d0800-dae8-11e8-9a5c-c4858f965e8e.png)
![image](https://user-images.githubusercontent.com/11450939/47615361-d83dd980-dae8-11e8-894c-f4c32000cdff.png)

![image](https://user-images.githubusercontent.com/11450939/47615351-c52b0980-dae8-11e8-807c-397b59c713cc.png)

**Comment by xluos** [comment]
@avwo 确实是配置的问题，实际上我要抓取log的页面是带路径的，之前我以为 `xluos.github.io  log://`这样配置可以抓到所有的该域名下的log。当我看到你的例子时突然意识到测试时用的例子全部都是首页可能是没有匹配路径的原因。使用`xluos.github.io*  log://`之后就可以正常抓到我需要的log信息了。不知我的理解是否正确
