### ISSUE TITLE
升级之后，老的请求转发配置失效

### ISSUE THREAD

**Issue by lichenbuliren** [avwo/whistle#233]
如题：
老的请求转发配置如下：
```
http://www.abc.com/cgi-bin/ http://ip:port/cgi-bin/ hostname://www.abc.com/
```

**Comment by avwo** [comment]
`hostname://xxx` 用 `reqHeaders://host=xxx` 代替
上面配置可以改成这样：
```
www.abc.com/cgi-bin/ ip:port
```

**Comment by lichenbuliren** [comment]
> `hostname://xxx` 用 `reqHeaders://host=xxx` 代替
> 上面配置可以改成这样：
> 
> ```
> www.abc.com/cgi-bin/ ip:port
> ```

感谢，按照这个提示配置通过了
