### ISSUE TITLE
whistle开启并打开代理后，无法访问http://wproxy.org/whistle。关闭代理就可以访问

### ISSUE THREAD

**Issue by aaronzw01** [avwo/whistle#236]
如题。
@avwo 
![w2-1](https://user-images.githubusercontent.com/44826284/48109439-6ef55d80-e282-11e8-8926-9dcad08ed6bd.png)
版本：
whistle：1.13.1
Node: v10.13.0
Port: 8899
chrome: 66.0.3359.117

**Comment by aaronzw01** [comment]
自己占一楼，辛苦avenwu了。

**Comment by avwo** [comment]
试试 https://wproxy.org/whistle
原因参考：https://github.com/avwo/whistle/issues/226
