### ISSUE TITLE
一直在不断请求

### ISSUE THREAD

**Issue by Wfhe2016** [avwo/whistle#237]
http://192.168.1.192:8899/cgi-bin/get-data?clientId=1541734489168-1&startLogTime=-2&startSvrLogTime=-2&ids=1541734562743-37&startTime=1541734562743-37&dumpCount=0&lastRowId=1541734562743-37&logId=&count=20&_=1541734489109

**Comment by avwo** [comment]
这个是whistle界面在轮询请求后台的数据，不用管它
