### ISSUE TITLE
当抓的包数量达到一定数量的时候，页面感觉比较卡

### ISSUE THREAD

**Issue by whxaxes** [avwo/whistle#238]
Hi，发现当抓的包数量比较多，比如超过一屏的时候（ 四十多个 ），发现页面就会开始感觉不流畅了，点击各个请求都有感觉有延迟。而当抓包有几百个的时候，卡顿就更严重了，滚动到下一屏的时候再点击请求延迟更是非常明显，还有点击 overview、inspectors 那些按钮也有卡顿感，基本上鼠标点击到有反应都得 1 ~ 2 秒。

我的硬件设备应该是没啥问题的，18 款 15 寸的 mbp ，浏览器是 chrome 。

虽然说可以通过清空请求来缓解，但是还是希望能更流畅一些，这个有计划优化一下体验么？

**Comment by avwo** [comment]
你是不是切到Inspectors里面的TextView了，web页面的textarea展示文本性能不是很好，这里已经做过一些优化，我看下怎么更好解决这个问题。
![image](https://user-images.githubusercontent.com/11450939/48400587-bd629a80-e761-11e8-9dea-49c3e993bd01.png)

**Comment by whxaxes** [comment]
@avwo  没有切到 textview 的情况下也会，就是请求数量比较多的时候点击各个请求有卡顿（ 从鼠标点击到请求一栏变颜色，起码要 1 秒以上，这种导致的延迟感还是蛮明显的 ）

**Comment by avwo** [comment]
新版做了些优化，会比之前性能好些，重新安装下whistle后，`w2 restart` 重启试试

**Comment by whxaxes** [comment]
@avwo  好的，我试一下，感谢

**Comment by yulanggong** [comment]
我看了下 network 表格部分的实现，所有的数据都渲染成了 DOM，这样如果条目变多，表格的渲染就会变得很慢，可以考虑优化成只渲染能看到的部分 DOM。
安利一个组件，看看有用不 https://github.com/bvaughn/react-virtualized

**Comment by avwo** [comment]
@yulanggong 非常感谢，我先看看，UI性能后续版本会持续优化
