### ISSUE TITLE
在设置请求转发时无法匹配不同路径的问题

### ISSUE THREAD

**Issue by xiaogeneral** [avwo/whistle#242]
现在有这样一个场景：一个nginx服务器上设置了多个前端项目的转发，例如192.28.82.112测试服务器上配置了store-h5和class-h5这两个前端项目(基于vue的spa项目)的转发，现在我想把192.28.82.112/store-h5/的请求代理到本地服务进行移动端的调试，但在whistle的rules设置里，`http://192.28.82.112/store-h5/ 172.28.80.105:8082/store-h5/`后转发失败，设置为`http://192.28.82.112 http://172.28.80.105:8082`才会转发成功，这个时候如果我想同时调试class-h5项目的话，就没法进行了。。。

**Comment by avwo** [comment]
第一个规则应该没问题，请求导出发我看下

**Comment by xiaogeneral** [comment]
> 第一个规则应该没问题，请求导出发我看下

问题细节已发您邮箱，辛苦看下。。。
