### ISSUE TITLE
设置https捕获后，在手机中app中，无法跳转https的链接

### ISSUE THREAD

**Issue by tian2008** [avwo/whistle#245]
代理服务器设置https捕获后，安卓8.1.0手机设置网络经过代理服务器（手机中已安装证书）。在手机app里的页面用 js 跳转 https 链接，无法完成跳转。例如：location.href = 'https://www.baidu.com';  而且在代理控制台的 network tab中也看不到请求的发送，这是什么原因导致的？只有手机APP中会有这问题，手机中的浏览器无问题。

**Comment by avwo** [comment]
http://wproxy.org/whistle/questions.html
