### ISSUE TITLE
node v11.4.0 运行会有警告 NODE_TLS_REJECT_UNAUTHORIZED 需要设置为 0

### ISSUE THREAD

**Issue by vkingw** [avwo/whistle#246]
node version ：v11.4.0

在node v11.3.0 和 v11.4.0 下运行会有警告，如下：

(node:28353) Warning: Setting the NODE_TLS_REJECT_UNAUTHORIZED environment variable to '0' makes TLS connections and HTTPS requests insecure by disabling certificate verification.

如何能消除这个警告呢？

**Comment by avwo** [comment]
**试试用 `w2 start` 启动**，<del>不要用 `w2 run` </del>。
这个是新版本的Node加强了安全提醒，主要防止一些恶意软件，程序里面是无法去掉这种警告。

**Comment by vkingw** [comment]
@avwo 如果用w2 run 启动是没有警告的，不过显示如下：

➜ w2 run
[i] whistle@1.13.5 started
[i] 1. use your device to visit the following URL list, gets the IP of the URL you can access:
       http://127.0.0.1:8899/
       http://192.168.10.189:8899/
       Note: If all the above URLs are unable to access, check the firewall settings
             For help see https://github.com/avwo/whistle
[i] 2. configure your device to use whistle as its HTTP and HTTPS proxy on IP:8899
[i] 3. use Chrome to visit http://local.whistlejs.com/ to get started
Press [Ctrl+C] to stop whistle...
[i] whistle@1.13.5 started
[i] 1. use your device to visit the following URL list, gets the IP of the URL you can access:
       http://127.0.0.1:8899/
       http://192.168.10.189:8899/
       Note: If all the above URLs are unable to access, check the firewall settings
             For help see https://github.com/avwo/whistle
[i] 2. configure your device to use whistle as its HTTP and HTTPS proxy on IP:8899
[i] 3. use Chrome to visit http://local.whistlejs.com/ to get started
Press [Ctrl+C] to stop whistle...

2次信息，难道启动了2次？

用w2 start 就会有问题中提到的警告。

😂

**Comment by vkingw** [comment]
@avwo 非常感谢😁

**Comment by avwo** [comment]
更正一下，程序是可以通过 `process.emitWarning = () => {}`  禁用该警告，已经fix，等下周 `v1.13.6` 版本一起带出去。
