### ISSUE TITLE
设置HTTPS代理时遇到问题需要帮助

### ISSUE THREAD

**Issue by pen9un** [avwo/whistle#249]
同一个带用户名密码的HTTPS代理，用Proxifier设置HTTPS代理并进行转发，可以访问目标IP站，IP站形如10.134.*.*，内网服务器，用Whistle设置这个代理不能使用，用浏览器插件Proxy SwitchyOmega挂这个代理也不能访问，访问www.baidu.com网站也不能访问，这个应该不是Whistle的问题，但不清楚对于此种代理该如何用Whistle设置代理使用，找不到出现这个问题的原因，也找不到解决方案，所以特寻求作者或其他同仁的帮助，看能否提供一些思路、解决方案，谢谢！ @avwo @Others

**Comment by pen9un** [comment]
@avwo 代理服务器有支持https协议也有支持http协议，目前测试的是目标IP站是https的，形如：https://10.134.xx.xx:8888/，有多个代理服务器，根据域名设置使用不同的代理服务器（VPN）的角色，感谢回复

**Comment by avwo** [comment]
https://wproxy.org/whistle/rules/proxy.html
https://wproxy.org/whistle/rules/https-proxy.html
https://wproxy.org/whistle/rules/socks.html

**Comment by pen9un** [comment]
Whistle的文档有详细阅读，包括上面代理相关的，Issues里相关的问题也有查阅，现在的情况如下：
首先代理服务器是HTTPS代理，带用户名密码，配置规则如下：
`10.134.xx.xx https-proxy://用户名:密码@IP:端口`，
同样的代理服务器Proxifier设置了代理服务器配置了转发规则（访问10.134.xx.xx时使用这个代理）后访问https://10.134.xx.xx:8888可以正常访问这个目标网站，用Whistle配置了上述规则，浏览器设置了Whistle的代理，访问目标网站时就不能访问，一直是一个加载中的状态

**Comment by avwo** [comment]
改成 `10.134.xx.xx http-proxy://用户名:密码@IP:端口` 试试
