### ISSUE TITLE
https是否可以自定义客户端证书

### ISSUE THREAD

**Issue by VeryLazyBoy** [avwo/whistle#250]
对于双向验证的https, 服务器会验证客户端证书，whistle发送https请求时，可以发送自定义的证书吗？

**Comment by avwo** [comment]
新建一个目录(`/xxx/ssl`)，把自定义证书放到此目录，证书必须后缀为`.crt`格式，每个证书的key和crt文件名称必须一致(如：`test.key`、`test.crt`，支持多域名证书，如果是根证书名字必须为 `root.key`、`root.crt`)，启动是时加启动参数 `w2 start -z /xxx/ssl` 即可

**Comment by VeryLazyBoy** [comment]
@avwo , 你好，`w2 start -z /xxx/ssl` 好像没有效果，whistle还是不能发送客户端证书给https服务器。我在一个在线测试客户端证书的[网站](https://server.cryptomix.com/secure/) 测试，显示:
![image](https://user-images.githubusercontent.com/18899212/51425599-4e019f00-1c19-11e9-850a-f6041b567e57.png)

**Comment by avwo** [comment]
应该是你证书有问题，打开crt格式的证书，看看有没有这个字段

**Comment by avwo** [comment]
应该是你证书有问题，打开crt格式的证书看看有没有以下字段
![image](https://user-images.githubusercontent.com/11450939/51425832-5a3b2b80-1c1c-11e9-9a5e-98055e99f524.png)

**Comment by avwo** [comment]
有密钥吗，类似  `xxx.key`

**Comment by VeryLazyBoy** [comment]
有，这是证书和密钥：[client.zip](https://github.com/avwo/whistle/files/2775642/client.zip)。我不知道是我证书使用不正确，还是whistle这边的问题

**Comment by avwo** [comment]
whistle的这个功能我们这边一直在用，不会有问题的，你这证书没有 `DNS Name` 字段，明显不对
![image](https://user-images.githubusercontent.com/11450939/51435750-03842f00-1cba-11e9-859d-f1abc88685fc.png)

**Comment by amplatzer** [comment]
应该是这类提取出来的证书都不带DNS Name字段， 而Whistle是根据该字段来判断要使用哪个证书的。 
如果Whistle 能支持自定义匹配哪些Domain 使用哪个证书就好了。 貌似burpsuite有类似功能 ？

**Comment by avwo** [comment]
Chrome浏览器强制需要DNS name字段

**Comment by amplatzer** [comment]
> Chrome浏览器强制需要DNS name字段，不用DNS name 自定义Domain跟直接使用whistle 生成的证书效果是一样的

@avwo  似乎对作者的需求理解有些偏差，我来试着整理下
1. 楼主是在分析某APP
2. 但是这个APP有做SSL 双向证书认证
3. Whistle 的 -z 参数只是使用自定义的服务端证书(对APP而言)
4. App 通过 中间人Whistle 访问最终Server时， Server 要求校验客户端证书。 (即楼主提取出来的)
5. Whistle 貌似不支持使用客户端证书？

**Comment by avwo** [comment]
现在还不支持，对需要双向验证的域名可以通过 xxx.yyy.com disable://capture
禁用中间人功能

**Comment by amplatzer** [comment]
我猜楼主的应用场景就是要修改报文 ，禁用中间人就没意义啦  XD， 期待更新 。

**Comment by amplatzer** [comment]
请参考Charles>SSL proxy settings > client certificate 的设置。

目前我的作法是 whistle 做规则 ， 用 http-proxy://IP:PORT 转发到上层Charles 代理上。 :-)

**Comment by avwo** [comment]
> 有，这是证书和密钥：client.zip。我不知道是我证书使用不正确，还是whistle这边的问题
@VeryLazyBoy 本周 whistle 会支持设置客户端证书，但上面的客户端证书有问题，你能不能单独发我一个正常的。

**Comment by VeryLazyBoy** [comment]
@avwo , 抱歉，我的证书已经找不到了。

**Comment by avwo** [comment]
重新安装 whistle 并重启，详见：https://wproxy.org/whistle/custom-certs.html
