### ISSUE TITLE
Android微信7.0中访问https页面会有安全警告

### ISSUE THREAD

**Issue by zuibunan** [avwo/whistle#251]
![image](https://user-images.githubusercontent.com/3386786/50467686-36027b00-09df-11e9-8a18-2674129c0f91.png)

开启了拦截https后，微信内访问https页面就会有弹框警告，以前的版本中不会弹框
尝试了重新安装PC端根证书和手机端证书，还是不行

此外，某些网站安全校验可能比较严格，开启拦截https后，内容无法正常加载，如知乎，美团

**Comment by avwo** [comment]
手机浏览器可以正常访问么？有些app做了ssl pinning 这种确实没法抓包，自己app如果没法抓包看看下这个：https://wproxy.org/whistle/questions.html

**Comment by zuibunan** [comment]
@avwo  我的系统是魅族Flyme6.3.0.0A，Android7.0系统，系统自带浏览器v7.7.2访问https站点会弹框提示证书有问题，点击继续可以访问，但图片资源都不显示

**Comment by avwo** [comment]
自带浏览器有问题，应该是根证书没安装好，重新安装下根证书后重启浏览器试试

**Comment by zuibunan** [comment]
@avwo  还是不行，自带浏览器以前可以，好像最近升级后不行了

**Comment by hezhizheng** [comment]
> 是升级系统，还是升级whistle导致的问题？

1. 安卓系统 7.0 以下版本，不管微信任意版本，都会信任系统提供的证书
2. 安卓系统 7.0 以上版本，微信 7.0 以下版本，微信会信任系统提供的证书
3. 安卓系统 7.0 以上版本，微信 7.0 以上版本，微信只信任它自己配置的证书列表
v2ex 上有这样的回答。。。。。

**Comment by ChanceYu** [comment]
我也曾经遇到你这样的问题。最后我的解决方法是，在公众号页面使用 `http` 协议打开对应的页面，而非 `https`，这样就可以代理到PC本地了。还有一种调试方法是使用 SSH 隧道代理调试。

**Comment by avwo** [comment]
@ChanceYu 这里ssh代理跟http代理没区别，也解决不了https证书问题

**Comment by avwo** [comment]
### 这个问题微信那边已经在解决，后续版本可能会支持。

**Comment by zuibunan** [comment]
@

> ### 这个问题微信那边已经在解决，后续版本可能会支持。
@avwo 
请问，微信那边有什么进展吗？

**Comment by avwo** [comment]
更新下微信，已经支持了

**Comment by zuibunan** [comment]
> 更新下微信，已经支持了

👍
