### ISSUE TITLE
同一个Whislte代理，Win7下访问HTTPS网站正常，XP下不能访问

### ISSUE THREAD

**Issue by pen9un** [avwo/whistle#252]
在局域网内的一台Win10 64位电脑上启动了Whistle代理，开启了"Capture HTTPS CONNECTs"选项，
另一台Win7 64位电脑上安装了Whislte的证书（在受信任的根证书颁发机构下），设置了Whistle的代理服务，访问带HTTPS百度网站：https://www.baidu.com，展现过程如下：
![image](https://user-images.githubusercontent.com/20841959/50766614-dea0bc80-12b4-11e9-8f0d-c92dd0ca1e1b.png)
![image](https://user-images.githubusercontent.com/20841959/50766703-2de6ed00-12b5-11e9-9a7b-bbb6cbcfd785.png)
百度可以访问，其它HTTPS的网站也可以访问，HTTP网站也可以正常访问。

同局域网下另一台XP 32位电脑，同样安装了Whislte证书，确认也安装在了受信任的根证书颁发机构下，设置了Win10 64位电脑上的Whistle代理，同样访问带HTTPS百度网站：https://www.baidu.com，不能访问，过程如下：
安装证书：
![image](https://user-images.githubusercontent.com/20841959/50766913-eb71e000-12b5-11e9-9f4e-bec9b952814f.png)
访问百度：
![image](https://user-images.githubusercontent.com/20841959/50767038-5fac8380-12b6-11e9-8942-e42f2f7afd44.png)
Whistle请求日志：
![image](https://user-images.githubusercontent.com/20841959/50767114-94b8d600-12b6-11e9-8040-49fe4f7ce914.png)
带HTTPS的百度网站不能访问，其它HTTPS网站也是同样的问题，但是HTTP的网站可以正常访问，用另外一个XP 32位虚拟机执行同样的操作，也是一样的现象。

请教下这种问题怎么解决，非常感谢！
@avwo @其他同仁

**Comment by avwo** [comment]
XP不支持tls>=1.1，网上搜下有没有解决方法 https://zhidao.baidu.com/question/2140170305311920828.html?entrytime=1546864121147&word=Windows%20xp%20tls&ms=1&rid=9211449452870483453&from=singlemessage&isappinstalled=0

**Comment by pen9un** [comment]
@avwo 感谢回复，特别感谢！
补充说明问题：进一步测试后，发现只有XP系统的**IE浏览器**不能通过Whistle代理访问HTTPS网站，但是基于**Chrome内核**的360系浏览器和Chrome浏览器是可以通过Whistle代理访问HTTPS网站，Whistle也能正常捕获到HTTPS的数据包，请问这个是什么问题？
上面关于XP不支持tls>=1.1的问题也有尝试，没有解决。
再次感谢百忙之中给于解答，谢谢！
