### ISSUE TITLE
whistle weinre:// 读取不到样式

### ISSUE THREAD

**Issue by 303182519** [avwo/whistle#253]
你可以代理这个页面看看http://hd.huya.com/h5/faith_badge/index.html?pid=50019474
查看规则的样式没有

**Comment by avwo** [comment]
确实有问题，weinre读取的样式不全，后面我看下怎么解决。

**Comment by echopi** [comment]
@303182519 你可以截个图看看是什么情况吗 我测试了一些机器，没有这个问题

**Comment by avwo** [comment]
试下这个插件： https://github.com/liriliri/whistle.chii
