### ISSUE TITLE
希望能增加一个通过命令行导出包的命令

### ISSUE THREAD

**Issue by sunmynet** [avwo/whistle#255]
我是从Fiddler迁移过来的用户。用whistle抓包，包是来自于安卓上的APP。通过各种测试，whistle是服务器上唯一可用的工具，非常感谢whistle这个工具。
但是我希望能随时自动保存包到服务器，Fiddler中有AutoSave这个功能，可以规定间隔时间自动保存包，我也希望whistle能有这个功能。或者增加一个通过命令行导出包的命令也可以。

**Comment by avwo** [comment]
可以用插件实现，下周我出个demo：https://wproxy.org/whistle/plugins.html

**Comment by sunmynet** [comment]
万分感谢!

**Comment by avwo** [comment]
这个插件可以实现简单的自动保存抓包数据到本地目录 https://github.com/whistle-plugins/whistle.autosave ，需要更复杂的功能可以参考该插件自己写个whistle插件。

**Comment by sunmynet** [comment]
@avwo .　　正在拜读Wu先生的code, 如有问题再向您请教
