### ISSUE TITLE
ios下 log上报Error实例丢失message信息

### ISSUE THREAD

**Issue by kaisey** [avwo/whistle#257]
## 问题描述
在配置了log协议，在ios 12下，上报error时，发现e.stack里没有包含e.message的信息，因为上报的stack没有关键的message信息，导致错误很难看懂

## 可能原因：
如图是调试log内嵌的代码

![image](https://user-images.githubusercontent.com/3821483/51113449-f17b3a00-183c-11e9-882d-e098a84e7cfa.png)

**Comment by avwo** [comment]
好的，下个版本fix
