### ISSUE TITLE
访问本地 127.0.0.1 的服务，连续刷新多次后，会访问不了服务

### ISSUE THREAD

**Issue by fzred** [avwo/whistle#26]
hi
访问本地 127.0.0.1 的服务，连续刷新多次后，会访问不了服务，chrome报错 Failed to load resource: net::ERR_EMPTY_RESPONSE 
运行
```bash
w2 restart
```
后又能正常访问服务。连续刷新又会出现上述问题。
如果是访问非 127.0.0.1 的服务就不会有这问题

**Comment by avwo** [comment]
我这边试了下没有重现，有可能是Chrome代理插件的问题，用Firefox设置下whistle的代理试试看会不会有这个问题

**Comment by fzred** [comment]
应该跟chomr代理插件没关系，我用android手机代理到whistle的端口8899，刷新几次后也是一样的情况，基本是必现的。
Whistle Version: 1.2.1
Nodejs Version: 5.9.0

**Comment by mackxu** [comment]
升级后，我也遇到提主的情况
Whistle Version: 1.11.0

**Comment by avwo** [comment]
试试启动时绑定指定网卡 w2 restart -H 127.0.0.1

**Comment by avwo** [comment]
[更新whistle](http://wproxy.org/whistle/update.html)，如果还有问题，试试设置下注册表：https://github.com/request/request/issues/210#issuecomment-234630155
