### ISSUE TITLE
unsafe header "Content-Length"

### ISSUE THREAD

**Issue by winnieBear** [avwo/whistle#263]

**Comment by avwo** [comment]
具体什么问题？

**Comment by winnieBear** [comment]
当调试远程页面时，控制台会报错“target-script-min.js:2950 Refused to get unsafe header "Content-Length"，主要是target-script-min.js的1950行的“contentLength = xhr.getResponseHeader("Content-Length");“执行报错

**Comment by winnieBear** [comment]
另外，使用log协议调试页面时，文档中提到的
![image](https://user-images.githubusercontent.com/7059683/51783345-29ef1200-2173-11e9-9515-3a0f0cf3e1f7.png)，找不到是怎么回事

**Comment by avwo** [comment]
这块文档有点问题，晚上改下

**Comment by avwo** [comment]
更新whistle 后重启试试，主要原因是浏览器不再允许获取响应头的content-length，log这块文档有点问题，晚点改下，这个表示一个id方便过滤。
