### ISSUE TITLE
proxy报错： tunneling socket could not be established & SSL routines:ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by pen9un** [avwo/whistle#264]
使用Whistle对一个内网IP分别设置了http-proxy和socks代理，分别有如下报错，

10.xxx.xxx.xxx http-proxy://username:password@39.106.xxx.xxx:8000
`From: whistle@1.13.15
Node: v11.1.0
Date: 2019-1-28 11:12:19
Error: tunneling socket could not be established, cause=socket hang up
    at ClientRequest.onError (C:\Users\john\AppData\Roaming\npm\node_modules\whistle\node_modules\hagent\lib\agent.js:150:17)
    at Object.onceWrapper (events.js:273:13)
    at ClientRequest.emit (events.js:182:13)
    at Socket.socketOnEnd (_http_client.js:433:9)
    at Socket.emit (events.js:187:15)
    at endReadableNT (_stream_readable.js:1094:12)
    at process.internalTickCallback (internal/process/next_tick.js:72:19)

Reload this page`

10.xxx.xxx.xxxsocks://username:password@39.106.xxx.xxx:8001

`From: whistle@1.13.15
Node: v11.1.0
Date: 2019-1-28 10:41:47
Error: write EPROTO 1980:error:1408F10B:SSL routines:ssl3_get_record:wrong version number:openssl\ssl\record\ssl3_record.c:252:

    at WriteWrap.afterWrite [as oncomplete] (net.js:792:14)

Reload this page`

设置https-proxy代理，网站一直是加载中的状态，无响应。

同样的http代理，
在IE下设置代理IP和端口号，访问目标网站，在认证窗口输入账号密码可以正常访问目标网站；
用Proxifier设置此代理服务器，并配置账号密码，访问目标网站也可以正常访问。

麻烦解答下这种问题怎么处理，谢谢！

**Comment by pen9un** [comment]
@avwo

**Comment by avwo** [comment]
Node v11.1.0版本有问题升级下Node再试试

**Comment by avwo** [comment]
前面一个根本就没连上，检查下ip和端口有没有配错，或者取代用户名和密码试试，后面这个看起来像是用https访问http server，改成http协议试试

**Comment by pen9un** [comment]
@avwo 
感谢忙碌之中给予解答。
已确定IP、端口号、账号密码是正确的，如果账号密码不正确，浏览器会出现如下提示：
![image](https://user-images.githubusercontent.com/20841959/51831037-2fdc2300-232c-11e9-8325-94a371cc8b26.png)

上述前面一个http-proxy代理和后面的socks代理是对同一目标网站配置的两个不同方式的代理，目前是分别设置socks代理和http-proxy代理后都不能正常访问，错误见前述，Whistle面板记录日志如下：
![image](https://user-images.githubusercontent.com/20841959/51831359-e3ddae00-232c-11e9-9429-077a6c5a0533.png)

**Comment by avwo** [comment]
难道是 `proxy-authorization` 大小写问题，你们公司内网用什么做代理服务器。

**Comment by pen9un** [comment]
小年快乐！小年快乐！不清楚用的是什么代理服务器，家里网络不能访问代理服务器，明天上班后第一时间看一下，谢谢！

**Comment by lap888** [comment]
set http_proxy=

set https_proxy=

yarn config delete proxy

npm config rm https-proxy

npm config rm proxy

npm config set registry "https://registry.npmjs.org"
