### ISSUE TITLE
通配符进行域名代理后，http请求头中的host格式不正确，导致webpack的devServer提示“Invalid Host Header”

### ISSUE THREAD

**Issue by guojiao** [avwo/whistle#265]
* 正常请求的host字段
![image](https://user-images.githubusercontent.com/9874927/51880229-6dcf5a80-23b1-11e9-9dd0-aebc399d8c4e.png)
-----
* whistle使用通配符模式用本地服务代理线上服务
代理配置：
``
*.aa.cn/bb/ localhost:8800/bb/
``
代理后请求的host字段
![image](https://user-images.githubusercontent.com/9874927/51880333-e209fe00-23b1-11e9-8d7c-2a5f396ebeff.png)

**Comment by avwo** [comment]
这种是请求替换，不是配hosts，可以改成这样：
```
*.aa.cn/bb host://localhost:8800
# 或
*.aa.cn/bb 127.0.0.1:8800
```

**Comment by guojiao** [comment]
> 这种是请求替换，不是配hosts，可以改成这样：
> 
> ```
> *.aa.cn/bb host://localhost:8800
> # 或
> *.aa.cn/bb 127.0.0.1:8800
> ```

标题描述有误。本地项目在进行请求替换时，如何配置才能让host显示为`localhost:8800`

**Comment by avwo** [comment]
不好意思，之前没注意看到请求头冒号问题，之前的版本已经fix，最好重新安装下whistle后重启
