### ISSUE TITLE
Linux下安装whistle后，使用w2或whistle命令，提示command not found？

### ISSUE THREAD

**Issue by eryueweb** [avwo/whistle#268]
![image](https://user-images.githubusercontent.com/16875336/53084564-0cc41e00-353c-11e9-82b3-ad4ea0c0c36f.png)

**Comment by avwo** [comment]
path没配好

**Comment by whitetrident** [comment]
感觉是npm全局命令没有安装好，linux下建议直接安装nrm再用nrm来安装node，这样全局安装也可以了
