### ISSUE TITLE
开启了苹果的ATS后无法抓HTTPS包

### ISSUE THREAD

**Issue by ssfyn** [avwo/whistle#27]
应用开启了苹果的ATS后无法抓HTTPS包

**Comment by tttlkkkl** [comment]
谢谢你，我暂时还用不到。

2016-12-30 

yehong0000 



发件人：ssfyn <notifications@github.com>
发送时间：2016-12-29 22:13
主题：[avwo/whistle] 开启了苹果的ATS后无法抓HTTPS包 (#27)
收件人："avwo/whistle"<whistle@noreply.github.com>
抄送："Subscribed"<subscribed@noreply.github.com>

应用开启了苹果的ATS后无法抓HTTPS包

**Comment by avwo** [comment]
iOS的APP开启ATS后，webview只支持HTTPS连接，且HTTPS的加密密钥长度不能小于2048，低版本Node生成2048位密钥效率很低，所以原来whistle只支持了1024位，现在Node版本完全可以胜任2048位的密钥，如何把whistle的根证书密钥切换的2048位，可以参考：[关于ATS](https://avwo.github.io/whistle/ats.html)
