### ISSUE TITLE
mac 系统升级到 10.14.3之后 电脑端没问题，手机端无法代理，提示无法连接到服务器

### ISSUE THREAD

**Issue by MarryJia** [avwo/whistle#272]
mac 系统重装升级到10.14.3之后，whistle电脑端代理没问题，手机ios端和安卓端都无法实现代理，提示无法连接到服务器 ，把mac的防火墙关闭也不行，试了charles 手机可以实现代理

**Comment by avwo** [comment]
把端口改成8888试试，`w2 restart -p 8888`

**Comment by MarryJia** [comment]
> 把端口改成8888试试，`w2 restart -p 8888`

谢谢 改成8888可以了
