### ISSUE TITLE
whistle有提供一个socks proxy server吗？

### ISSUE THREAD

**Issue by xiaomingplus** [avwo/whistle#273]
启动的说明里看起来只提供了http和https的proxy服务，想问下有没有提供一个socks 的proxy，用于配置这里:

![image](https://user-images.githubusercontent.com/7547308/54261859-cb0d1d00-45a7-11e9-9925-82f7961c1f83.png)

**Comment by avwo** [comment]
目前不支持，这个有什么应用场景？

**Comment by xiaomingplus** [comment]
有一些应用只支持设置sockes连接，比如 telegram

**Comment by xiaomingplus** [comment]
charles 是支持提供一个socks的服务出来的

**Comment by avwo** [comment]
可以考虑支持，手上还有一些新功能，完成后再着手支持该功能

**Comment by xiaomingplus** [comment]
好吧~感谢~

**Comment by kotori2** [comment]
我遇到的情况是
iOS上部分应用不走系统的HTTP代理，这时候只能通过VPN把整个系统的流量转换成SOCKS5，但是貌似市面上没几个抓包工具提供SOCKS传入

**Comment by avwo** [comment]
更新下whistle ，新版可以通过命令行参数 -socksPort 1080 设置socks5 server 端口

**Comment by shihuajushi12** [comment]
root@kali:~# w2 start  -p 20002 -socksPort 1080

  error: unknown option `-o'
请问这个是什么问题！

**Comment by shihuajushi12** [comment]
有没有一个配置手册，比如在ｌｉｎｕｘ里面是不是用ｉｐｔａｂｌｅ把所有流量劫持到ｓｏｃｋｓ里面，然后代理给whistle.

**Comment by avwo** [comment]
自己网上搜下，记得把方法同步出来

**Comment by shihuajushi12** [comment]
好的，搞了一天，没什么效果！

**Comment by zgq354** [comment]
> 更新下whistle ，新版可以通过命令行参数 -socksPort 1080 设置socks5 server 端口

应该是 `--socksPort 1080`，大佬手滑少打了个 -
参见文档：https://github.com/avwo/whistle/blob/74d0658e70b035dd6e8e4207f571055650869054/docs/zh/options.md

**Comment by TwinkleSevenStream** [comment]
通过iptables可以直接转发所有本地发出的请求到whistle，具体步骤如下：
1. 开启iptables的ip转发和本地转发：`sysctl -w net.ipv4.ip_forward=1 net.ipv4.conf.eth0.route_localnet=1`
2. 设置nat表的OUTPUT链：`iptables -t nat -A OUTPUT -p tcp -j DNAT --to-destination $target_ip:$target_port`
3. 设置nat表的POSTROUTING链：`iptables -t nat -A POSTROUTING -p tcp -d $target_ip --dport $target_port -j SNAT --to-source $instence_ip`
其中$target_ip和$target_port为whistle实例的ip地址和监听端口，$instence_ip为本地机器请求whistle时的ip（一般为eth0的ip地址，可用ifconfig查看）

**Comment by TwinkleSevenStream** [comment]
> 通过iptables可以直接转发所有本地发出的请求到whistle，具体步骤如下：

我的使用场景是：两台实例机器，在同一个局域网内，分别为A(ip=172.18.0.2)，B(ip=172.18.0.3)，A机器上运行了服务A-Service(port=6600)和whistle(port=8899)，B机器上运行了服务B-Service(port=7700)。
其中B-Service的部分逻辑会通过http请求localhost:6601，但B机器的6601没有运行任何进程，我需要将B-Service=>localhost:6601的请求转发到whistle，再由whistle转发到A-Service。即B-Service(172.18.0.3:7700)=>A-Service(172.18.0.2:7701)
（注意：该需求可以直接用iptables转发而不需要经过whistle，该示例是为了说明经过whistle转发的情况）
在B机器进行如下设置：
1. 开启ipatbles的转发`sysctl -w net.ipv4.ip_forward=1 net.ipv4.conf.eth0.route_localnet=1`
2. 将本地生成的请求转发到A机器的whistle：
    - `iptables -t nat -A OUTPUT -p tcp -j DNAT --to-destination 172.18.0.2:8899`
    - `iptables -t nat -A POSTROUTING -p tcp -d 172.18.0.2 --dport 8899 -j SNAT --to-source 172.18.0.3`
这样设置后，B-Service=>localhost:6601的请求就会被转发到whistle，可以经过whistle规则转发到127.0.0.1:6600的A-Service（因为whistle和A-Service都在A机器，因此直接127.0.0.1）
