### ISSUE TITLE
为什么没有类似anyproxy指定rule file的option的功能？

### ISSUE THREAD

**Issue by kunsun** [avwo/whistle#274]
anyproxy可以这样指定规则文件：
`anyProxy -p 8001 -w 8002 -s --ignore-unauthorized-ssl -r ./server/proxy-server.js`
请问在whistle中该如何实现？

**Comment by avwo** [comment]
你想实现什么功能？和anyproxy不一样，需要转变下用法，whistle是基于配置实现对请求的操作，不需要你写逻辑代码，如：
```
# 配置host
www.test.com/xxx 127.0.0.1

# 本地替换
www.test.com/xxx file:///Usr/abc

# 上游代理
**.test.com proxy://test.proxy.com:8888

# 修改请求头
pattern reqHeaders://x-test=abc

# 等等

```

whistle的规则基本上覆盖操作请求响应的各个部分： http://wproxy.org/whistle/rules/

同时也支持插件扩展：

1. https://wproxy.org/whistle/plugins.html
2. https://github.com/whistle-plugins

你可以把anyproxy打包成whistle的一个插件，或者自己开发一个满足自身需要的插件，或者用现成的插件：https://github.com/whistle-plugins/whistle.script

**Comment by avwo** [comment]
你想实现什么功能？和anyproxy不一样，需要转变下用法，whistle是基于配置实现对请求的操作，不需要你写逻辑代码，如：
```
# 配置host
www.test.com/xxx 127.0.0.1

# 本地替换
www.test.com/xxx file:///Usr/abc

# 上游代理
**.test.com proxy://test.proxy.com:8888

# 注入weinre
www.test.com/xxx weinre://id

# 修改请求头
pattern reqHeaders://x-test=abc

# 等等

```

whistle的规则基本上覆盖操作请求响应的各个部分： http://wproxy.org/whistle/rules/

同时也支持插件扩展：

1. https://wproxy.org/whistle/plugins.html
2. https://github.com/whistle-plugins

你可以把anyproxy打包成whistle的一个插件，或者自己开发一个满足自身需要的插件，或者用现成的插件：https://github.com/whistle-plugins/whistle.script

**Comment by kunsun** [comment]
明白了，刚切到whistle，思路还没转过来
