### ISSUE TITLE
Whistle 是否有提供 reload configuration 的功能？

### ISSUE THREAD

**Issue by forrestchang** [avwo/whistle#277]
目前想要从本地写入到配置文件里，但是 Whistle 需要 restart 才能够读取写入的配置，想问一下是否支持直接 reload 配置的功能？在代码里面好像没有找到，如果不支持，考虑可以提一个 reload configuration 的 PR。

**Comment by avwo** [comment]
可以在Rules里面配置 `@localFilePath` 或者 `@remoteUrl` 的方式引入规则，whistle会自动检测文件变跟并自动加载规则，详见：http://wproxy.org/whistle/rules/@.html ，也可以用插件自定义加载规则
![image](https://user-images.githubusercontent.com/11450939/55062189-66c28100-50b0-11e9-907a-b9e6c897a385.png)

**Comment by avwo** [comment]
如果想实现自动配置项目规则，建议在项目根目录建一个 `.whistle.js` 文件，把项目规则放到该文件，后面执行通过在项目根目录执行  `w2 add` 即可自动添加好项目规则，参见：https://wproxy.org/whistle/cli.html

**Comment by forrestchang** [comment]
> 可以在Rules里面配置 `@localFilePath` 或者 `@remoteUrl` 的方式引入规则，whistle会自动检测文件变跟并自动加载规则，详见：http://wproxy.org/whistle/rules/@.html ，也可以用插件自定义加载规则
> ![image](https://user-images.githubusercontent.com/11450939/55062189-66c28100-50b0-11e9-907a-b9e6c897a385.png)

多谢回复，速度好快！

另外，Whistle 自动检测是实时的嘛？还是定时（比如 1 分钟检测一次）？

**Comment by avwo** [comment]
10多秒检测一次，用户感受基本上是实时的
