### ISSUE TITLE
如何实现相同host不同路径对应不同的本地端口

### ISSUE THREAD

**Issue by GeekaholicLin** [avwo/whistle#278]
一个项目划分为用户端与管理端，对应的本地端口分别为8890和8891。想实现www.demo.com指向127.0.0.1:8890，www.demo.com/admin/xxx指向127.0.0.1:8891/xxxx，但是用下边的配置没有作用，需要如何改进配置呢？

```bash
http://www.demo.com host://127.0.0.1:8890
http://www.demo.com/admin/*** proxy://127.0.0.1:8891/$1
/http:\/\/www\.demo\.com\/(?!admin\/)/ proxy://127.0.0.1:8890
```

**Comment by avwo** [comment]
whistle默认匹配优先顺序是从上到下：
``` txt
www.demo.com/admin/ http://127.0.0.1:8891/
www.demo.com http://127.0.0.1:8890
```
上述配置表示（先匹配第一个规则，匹配不到才匹配第二个规则）：
1. `www.demo.com/admin/` 及其所有子路径 `www.demo.com/admin/...` 的请求都转成 `http://127.0.0.1:8891/...`
2. 其它 `www.demo.com` 域名的请求都转成 `http://127.0.0.1:8890/...`

**Comment by GeekaholicLin** [comment]
soga! 是我想复杂了，感谢～🙏

**Comment by avwo** [comment]
补充下，配host和请求转发的区别：

1. 配host：
	``` txt
	pattern 127.0.0.1:5566
	# 或
	pattern host://www.test.com:5566
	127.0.0.1:5566 pattern
	```
2. 转发：
	``` txt
	www.test.com/xxx www.qq.com/abc
	# 上述配置会自动补齐协议及剩余路径
	# 如： `https://www.test.com/xxx/path/to` -> `https://www.qq.com/abc/path/to`
	
	# 限制协议
	https://www.test.com/xxx www.qq.com/abc
	www.test.com/xxx https://www.qq.com/abc
	```
PS：配host的话，请求url不会变，只是建立连接的服务器ip或端口变了；转发的话请求url会变成新的url。

3. 转发 + 配置新路径的host
	``` txt
	www.test.com/xxx www.qq.com/abc
	www.qq.com/abc 127.0.0.1:5566
	```

**Comment by GeekaholicLin** [comment]
> 配host的话，请求url不会变，只是建立连接的服务器ip或端口变了；转发的话请求url会变成新的url。

以第三个配置为例，www.test.com/xxx 会 被 whistle 替换成 www.qq.com/abc，而 www.qq.com/abc 会因为 host 配置，在 dns 解析的时候解析成 127.0.0.1:5566，最终后台收到的请求是 www.qq.com/abc ？

另外，转发和 whistle 协议列表中的 proxy 有什么区别吗？我把 http:// 替换为 proxy:// 后，对于一些其他路径（看样子是在 node 层有做另外一层代理的路径）会报 502 错误。

**Comment by avwo** [comment]
> 以第三个配置为例，www.test.com/xxx 会 被 whistle 替换成 www.qq.com/abc，而 www.qq.com/abc 会因为 host 配置，在 dns 解析的时候解析成 127.0.0.1:5566，最终后台收到的请求是 www.qq.com/abc ？

**是的**

proxy是用来设置代理，只能设置 `proxy://ip(或域名):端口`  或 `proxy://ip(或域名):端口?host=ip:port` ，前者形对于http请求和设置host一样，其它情形不管是http和https、websocket都走的是tunnel代理，要求接收服务器是一个http代理才可以

**Comment by GeekaholicLin** [comment]
感谢解答，感觉清晰了一点，谢谢～
