### ISSUE TITLE
Couldn't able to receive websocket data, always shows Method as "Connect" & Host as "Tunnel to"

### ISSUE THREAD

**Issue by sankar2389** [avwo/whistle#279]
Couldn't able to receive websocket data, always shows Method as "Connect" & Host as "Tunnel to"
![Whistle](https://user-images.githubusercontent.com/10666209/55611585-90139900-57a3-11e9-9495-3452e1c74df9.png)

**Comment by avwo** [comment]
https://wproxy.org/whistle/webui/https.html

**Comment by sankar2389** [comment]
@avwo Thanks a lot, now it works
