### ISSUE TITLE
能否把包保存成fiddler的saz格式？

### ISSUE THREAD

**Issue by mapleeit** [avwo/whistle#28]

**Comment by avwo** [comment]
开发中...，v1.3.0版本开始会支持导入导出Fiddler2/Fiddler4的saz格式文件

**Comment by mapleeit** [comment]
好的，期待！

**Comment by mapleeit** [comment]
我看到发布1.3了，但是没有看到导出saz的入口呢，这个要怎么做呢

**Comment by avwo** [comment]
### 导出(两种方式)：

1. 打开Network页面 -> 鼠标hover到(或者点击)Network菜单的下拉菜单可以看到`Export selected sessions (Fiddler)` 菜单项，点击该菜单项可以把选中的数据导成saz文件。
2. 选中要导出的sessions，按 `Ctrl[Command] + S`选择文件类型，再按`Ctrl[Command] + S`或`Confirm按钮`

### 导入(三种方式)：
1. 点击`Import sessions`，并选择要导入的文件
2. 把saz(txt)文件拖到页面
3. 快捷键 `Ctrl[Command] + I`，并选择要导入的文件

**Comment by mapleeit** [comment]
明白，再次感谢
