### ISSUE TITLE
无法从文件中 import values 

### ISSUE THREAD

**Issue by huruji** [avwo/whistle#285]
**操作步骤**：同步两台电脑的 values 配置，export 文件后，在另一台电脑上无法导入，有如下提示：
![image](https://user-images.githubusercontent.com/15937065/57211752-fe9e7d80-7013-11e9-8f58-67db93a401ba.png)

**whistle 版本**：1.13.25

**浏览器版本**：Chrome 73.0

**操作系统**：macOS Mojave 10.14

**需要导入的 values 配置文件大小**：32 kb

辛苦解答一下~~

**Comment by avwo** [comment]
之前调整代码有个依赖文件路径搞错了，eslint居然没居然没检测出来，晚上发个版本解决这个问题

**Comment by huruji** [comment]
🌹
