### ISSUE TITLE
a copy caused typo

### ISSUE THREAD

**Issue by KingMario** [avwo/whistle#286]
https://github.com/avwo/whistle/blob/e0e41d6111061c2e555a6ea38a66c9cce1b867a2/biz/webui/htdocs/src/js/editor.js#L104

The property name should not be _showLineNumber in the showLineWrapping method.

And I'd like to recommend you to set both line numbers and line wrapping settings to default.

**Comment by avwo** [comment]
重新安装whistle后重启
![image](https://user-images.githubusercontent.com/11450939/57294207-814d3880-70f9-11e9-9df5-606ba727c28f.png)
