### ISSUE TITLE
关于 uiServer 的问题

### ISSUE THREAD

**Issue by huruji** [avwo/whistle#288]
hi，我在[文档插件开发]()一节中看到 whistle 设计的7中 server 中包括 uiServer

> uiServer: whistle插件的界面，可以通过特定的url访问

请问这里的意思是指，我可以开发一个插件来通过形如 `http://127.0.0.1:8899/mypage` 来访问插件内定义的页面吗？有类似的例子吗？

劳烦解答，辛苦～

**Comment by avwo** [comment]
http://127.0.0.1:8899/whistle.xxx
，可以直接在whistle 界面的Plugins打开

**Comment by huruji** [comment]
感谢 🌹 ，我试试
