### ISSUE TITLE
希望能增加一个配置导入导出的功能

### ISSUE THREAD

**Issue by lwdgit** [avwo/whistle#29]

**Comment by avwo** [comment]
预计下周发布的版本(v1.3.0)会支持导入导出功能

**Comment by avwo** [comment]
已支持**导入、导出**txt文件或者Fiddler的saz文件，[安装最新版的whistle](https://avwo.github.io/whistle/update.html)，在[Network](http://local.whistlejs.com/#network)页面上方的`Network`菜单按钮的下拉菜单里面可以看到导入导出的功能，也支持拖拽的形式导入。

**Comment by cos2004** [comment]
我猜楼主期待的是导入导出“Rules”和“Values”的功能，还有插件的一些配置数据，比如vase的mock配置。我也非常希望作者能加入这个功能

**Comment by avwo** [comment]
可以加，后面的版本加上这个功能

**Comment by avwo** [comment]
最新版本中已经支持，[重新安装下whistle](https://avwo.github.io/whistle/update.html)，可以右键菜单导入导出

**Comment by pasicopan** [comment]
导出格式能不能支持多种格式？例如chrome 的har，或者允许插件重写？

**Comment by avwo** [comment]
支持导出 har
<img width="595" alt="image" src="https://github.com/avwo/whistle/assets/11450939/0f24d686-c725-4f0c-9ee6-378c9d0a2122">
