### ISSUE TITLE
network 面板 filter 无效

### ISSUE THREAD

**Issue by maxming2333** [avwo/whistle#292]
### 信息

```
Node: v10.15.3
Whistle: v1.14.7
```

#### 0x001

我想在 `network` 面板中用 `filter`  过滤掉 `CONNECT` 类型请求（已安装 HTTPS 证书）

配置如下：

![image](https://user-images.githubusercontent.com/8816730/58742863-c561fd80-8459-11e9-9bee-5415a53ef22d.png)

以前的版本可以，但是现在没办法做到

截图：

![image](https://user-images.githubusercontent.com/8816730/58742888-736da780-845a-11e9-94fc-ac1b60527a44.png)

#### 0x002

目前 `network` 界面比较卡顿，之前几个版本貌似挺流畅滴

```
Google Chrome: v74.0.3729.169 (64bit)
```

**Comment by avwo** [comment]
> 0x001 无法通过请求方法过滤

这是个bug，取错对象，已经fix，周一左右发个版本


> 0x002 页面相较前几个版本性能比较差

界面这块最近调整不大，看下你电脑上起的服务是不是变多了？界面的性能已做了不少优化，不过切实还有很大优化的空间，会持续优化。

**Comment by maxming2333** [comment]
👍
