### ISSUE TITLE
最近在试着吧whistle.nohost部署到服务器上，遇到一些问题

### ISSUE THREAD

**Issue by pangmingming** [avwo/whistle#293]
whistle.nohost的帮助文档好像只有码云上的详细点，其他都是404，我按步骤配置后，注入whistle.nohost:// *.ke.qq.com ke.qq.com *.url.cn，并未出现相应的小圆点，是因为我没有安装证书吗？不知道问题出在哪里，

**Comment by avwo** [comment]
没安装证书, 更新下 whistle 和 whistle.nohost，可以把现有域名的证书放到 `~/.WhistleAppData/custom_certs` 目录下即可

**Comment by pangmingming** [comment]
但是我测试的是页面时http,http也需要安装证书吗？

**Comment by avwo** [comment]
域名是不是配错了，这个是 `ke.qq.com` 的域名

**Comment by pangmingming** [comment]
没有，不是用ke.qq.com测试的，whistle.nohost:// dev-test.hibossapp.com *.img1.cfcdn.club。打开http://dev-test.hibossapp.com/home，没有反应。。

**Comment by avwo** [comment]
改用 https://github.com/nohosts/nohost
