### ISSUE TITLE
1.14.9 版本在mac上无法使用

### ISSUE THREAD

**Issue by lumixraku** [avwo/whistle#294]
Mac OS 10.14 
whistle 1.14.9

换了多个端口，8899  8888 8080，  在start 之后端口均没有被占用。 Linux可以。

**Comment by avwo** [comment]
重启下电脑试试

**Comment by lumixraku** [comment]
重启过  杀毒软件也卸载了  防火墙也确认关闭

**Comment by avwo** [comment]
删除目录 ~/.startingAppData 重启

**Comment by lumixraku** [comment]
尝试后发现start命令后至少端口有被占用， 但是还是无法访问。
~/.startingAppData 中实际上是空的   

其实我只想把之前的配置捞出来， 不知道这个配置是不是只存在于 localstorage 中还是有什么目录下有。

**Comment by avwo** [comment]
之前的配置在 `~/.WhistleAppData` 目录

**Comment by avwo** [comment]
这里面可能涉及两个问题：
1. `w2 start` 无效，可能是因为之前用了 `sudo w2 start` 导致的文件权限问题，尽量**不要用** `sudo` 启动whistle，如果用了后面都要用sudo，或者修改下目录 `~/.startingAppData` 和 `~/.WhistleAppData` 里面所有目录及文件的权限
2. 启动后无法访问，可能是代理配置问题，参考：https://github.com/avwo/whistle-for-chrome ；如果是远程无法访问可能是防火墙问题，参考：https://github.com/avwo/whistle/issues/78
