### ISSUE TITLE
升级whistle后，不能启动服务，不能进入web管理界面

### ISSUE THREAD

**Issue by sfesh2012** [avwo/whistle#295]
![image](https://user-images.githubusercontent.com/3196516/59617741-7c988d00-9159-11e9-88fe-ccb81a1867fc.png)

**Comment by sfesh2012** [comment]
1.13.17是可以的

![image](https://user-images.githubusercontent.com/3196516/59618241-6212e380-915a-11e9-9555-3c44a073297c.png)

**Comment by sfesh2012** [comment]
亲测，v1.13.18就不可以， v1.13.17以下就可以。

**Comment by avwo** [comment]
都用8080端口启动后看下，或者重启下机器

**Comment by luozuxiong** [comment]
悲剧了，手抖升级了一下，结果访问不了了

**Comment by avwo** [comment]
@luozuxiong 报什么错

**Comment by avwo** [comment]
原因查到了，`Node 11.0 ~ 11.5` 期间带版本有bug，不支持 [--max-http-header-size](https://nodejs.org/dist/latest-v10.x/docs/api/cli.html#cli_max_http_header_size_size)，导致whistle启动失败，可以用以下两种方式修复此问题：
1. 【推荐】更新Node到最新到 [v12 或 v10](https://nodejs.org/en/) 版本
2. 重新安装下whistle并重启

**Comment by sfesh2012** [comment]
可以了，感谢回复！
