### ISSUE TITLE
android 手机 termux环境中无法启动，nginx等web服务器能启动

### ISSUE THREAD

**Issue by yangfanyu** [avwo/whistle#296]

**Comment by yangfanyu** [comment]
同一台android 的termux环境中无法正常监听端口，android 手机 termux中 nginx等其他的服务器能启动，手动编写的node 服务脚本也能启动

**Comment by yangfanyu** [comment]
![6951561065467_ pic_hd](https://user-images.githubusercontent.com/17940584/59882351-926db280-93e4-11e9-9678-1c47a2a64968.jpg)
![6961561065582_ pic_hd](https://user-images.githubusercontent.com/17940584/59882368-9b5e8400-93e4-11e9-9a0b-18426b916beb.jpg)
![6971561065626_ pic_hd](https://user-images.githubusercontent.com/17940584/59882390-aca79080-93e4-11e9-9576-8866e5427e33.jpg)

**Comment by avwo** [comment]
可能 android 上的 node 是阉割版，暂时没有需求考虑兼容 android 版本，确实有较普遍的应用场景再说

**Comment by altmangood** [comment]
@avwo 也有遇到同样的问题，经过我最近的测试，我发现在Termux 里面使用chroot启动一个 Linux Distro之后，能运行成功。

这个可能不是Node版本被阉割的问题，这个也是标准node源码编译过来的，我感觉是一些网络层的三方库或者原生库在创建socket的时候有权限或者什么报错。因为netstatus -tupln 确实没看到 8899 创建，但是w2 start 没有报错。

@avwo 这个问题我能大概看哪几个文件或者模块，我去调试下。 另外启动过程是否有啥日志可以开起来？

**Comment by altmangood** [comment]
@yangfanyu 你后面解决了吗？
