### ISSUE TITLE
weinre无法使用

### ISSUE THREAD

**Issue by augustVino** [avwo/whistle#297]
![image](https://user-images.githubusercontent.com/29117984/60244691-8191d500-98ed-11e9-9434-d18667d95d06.png)

**Comment by avwo** [comment]
我这可以啊，你怎么配置的
![image](https://user-images.githubusercontent.com/11450939/60245259-d1bd6700-98ee-11e9-86d2-14c70fb679fe.png)

![image](https://user-images.githubusercontent.com/11450939/60245239-c407e180-98ee-11e9-9141-d693c6deb673.png)

**Comment by avwo** [comment]
可以在Network的Overview里面看下请求有没有匹配规则
![image](https://user-images.githubusercontent.com/11450939/60245356-07625000-98ef-11e9-8e29-8ba8f341d08f.png)

**Comment by augustVino** [comment]
好了好了  匹配规则拼错了。。  多谢！！
