### ISSUE TITLE
能否通过开发插件的方式在inspector中的response界面增加一些数据解密的界面

### ISSUE THREAD

**Issue by WinChua** [avwo/whistle#299]
![image](https://user-images.githubusercontent.com/11592887/60560915-4fb4be80-9d84-11e9-8964-9f710ae401cb.png)

你好，我抓包的时候，因为回包有加密，回包body在inspector界面中查看，就只能看到一些二进制数据，我想知道能否通过我自己开发插件的方式在这里的response界面中添加数据解密功能？
如果有的话，有一些文档吗？

**Comment by avwo** [comment]
可以在插件里面加两个管道，分别用于解包（rexRead）组包（rexWrite），这块来不及更新上文档，周末我写个demo
![image](https://user-images.githubusercontent.com/11450939/60565042-8692d080-9d94-11e9-9d71-45f23c8afcec.png)
http://wproxy.org/whistle/plugins.html

**Comment by WinChua** [comment]
麻烦你了，谢谢

**Comment by Foolment** [comment]
请问这里有进展吗？或者能否具体说明一下插件怎么写？我也有类似的需求

**Comment by sirius60111** [comment]
有同样的需求，请问怎么实现呢？

**Comment by avwo** [comment]
参考下这个 https://github.com/whistle-plugins/examples/blob/master/README.md
