### ISSUE TITLE
编写自定义插件时，无法输出开发log

### ISSUE THREAD

**Issue by shenlm203** [avwo/whistle#3]
在开发自定义插件的时候， 遇到一个问题：我想临时输出开发日志， 却没有方法可以输出。 

由于插件是由whistle来调用的，whistle对于自定义插件中的console.log等日志信息，没有给予输出，给开发插件带来一定的不便。 建议增加一个whislte的调试模式， 可以便捷地输出自定义插件的相关日志信息， 便于插件开发者调试。

**Comment by avwo** [comment]
[更新到最新版本](https://github.com/avwo/whistle/wiki/%E6%9B%B4%E6%96%B0whistle)，并用命令行`w2 run`启动，即可在命令行看到插件`console.log`的输出的信息(只能用console.log，其它console的API暂不支持)
