### ISSUE TITLE
[Feature Request] wildcard match for words

### ISSUE THREAD

**Issue by KingMario** [avwo/whistle#300]
Please add a wildcard `$` match for words so that it will only match the path part that doesn't contain dots(`.`) and backslashes(`/`).

This will be very handy for frontend routing to be matched to index.html in an SPA.

If the wildcard is provided, the user can set this kind of rules.

```
# this rule will match /catalog/toy/product/toy-car
# but won't match /assets/css/icons/blank.svg

^/$/$/$/$ file:///path/to/project/index.html
```

Furthermore, please add `$$` and `$$$` to make it more flexible.

Thanks.

**Comment by avwo** [comment]
see https://stackoverflow.com/questions/317760/how-to-get-url-hash-from-server-side

**Comment by avwo** [comment]
you can use RegExp instead of, such as: `/^\w+://[^/]+(/[^./]+){5}/?(\?.*)?$ file:///path/to/project/index.html`

**Comment by KingMario** [comment]
i'll give it a try. thx
