### ISSUE TITLE
weinre出现target后, 过几秒又消失了？

### ISSUE THREAD

**Issue by wuyafeiJS** [avwo/whistle#304]
如题，然后刷新被监听的页面又出现了，然后再消失。完全没有时间调试

**Comment by avwo** [comment]
换个页面试试，看看是不是页面问题

**Comment by lyc8023** [comment]
我的也是这样的，而且elements的Dom结构完全点不动了，感觉就是断开连接了，后续操作都是没法调试的。

**Comment by avwo** [comment]
怎么重现？

**Comment by lyc8023** [comment]
我试了一下访问m.baidu.com打开 weinre 是可以一直连接的的，但是访问自己的项目地址打开weinre没一会就断开了也就调试不了，项目用的vue写的，有没有可能跟不停发送arms监控请求有关系

**Comment by lyc8023** [comment]
我试了几下初步排查原因可能是因为项目用了阿里云的arms监控，频繁发送监控请求导致的。

**Comment by avwo** [comment]
![image](https://user-images.githubusercontent.com/11450939/80214114-d49efa80-866c-11ea-9bd0-92501cc0133b.png)

**Comment by avwo** [comment]
试下这个插件： https://github.com/liriliri/whistle.chii
