### ISSUE TITLE
internal-proxy 支持隐藏真实host，发送http请求

### ISSUE THREAD

**Issue by hxfdarling** [avwo/whistle#307]
例如配置一下规则：
```txt
baidu.com internal-proxy://my-whistle.proxy.com
```

发起的请求头应该应该是这样：
```
host: my-whistle.proxy.com
x-forward-host: baidu.com
```

当远端whistle(即:my-whistle.proxy.com)收到代理请求后，应该通过`x-forward-host`处理来转发规则（忽略host)，即将请求头转换为：

```
host: baidu.com
```

> 该方式可以穿透不支持connect 的 nginx 反向代理服务器

**Comment by avwo** [comment]
更新下whistle：

* internal-proxy://my-whistle.proxy.com:80 reqHeaders://`(host=my-whistle.proxy.com&x-forwarded-host=${url.host})`

如果 `x-forwarded-for` 跟 nginx 的配置冲突，可以用优先级更高的 `x-whistle-real-host` 代替
