### ISSUE TITLE
无法设置抓取https流量

### ISSUE THREAD

**Issue by amitbha** [avwo/whistle#308]
证书已经安装，但在设置里没看到开启抓取https的选项，如图所示：
![0728-1935](https://user-images.githubusercontent.com/4060625/62006113-e94a7280-b16e-11e9-98ff-b9411621ef6e.jpg)

whistle@1.15.12

**Comment by amitbha** [comment]
chrome和firefox都试过，都没有开启的选项

**Comment by avwo** [comment]
要手动开启

**Comment by amitbha** [comment]
我抓取的是微信PC版的流量

1. 装完证书，勾选“Capture Tunnel connects”无效，所有流量看上去都是http，且内容无法查看，都是乱码
![fs-19-07-29 08 42](https://user-images.githubusercontent.com/4060625/62015295-e38b7600-b1dc-11e9-8cec-2c49807ecf0f.png)

2. 怀疑是没有开启https，就仔细看了下帮助。帮助文档里的截图有“Intercept HTTPS connects”，但我的设置里却没有
![fs-19-07-29 08 32](https://user-images.githubusercontent.com/4060625/62015210-fe111f80-b1db-11e9-8590-c6eb5367cc38.png)

**Comment by avwo** [comment]
勾选 `Capture Tunnel CONNECTs ` 即可，这块文档忘了重新截图，勾选后，如果没看到正常的https请求可以重启下浏览器或whistle
