### ISSUE TITLE
通过url过滤指定header的network数据

### ISSUE THREAD

**Issue by RockyRen** [avwo/whistle#309]
例如: http://127.0.0.1:8899#network?cookie=12345&host=www.qq.com
过滤出cookie包含12345，和host为www.qq.com的network数据

**Comment by avwo** [comment]
重新安装下whistle，可以通过 `#network?name=key&value=val&name1=key1&value1=val2&...&name5=key5&value5=val5` 最多设置过滤请求头的 6个条件
