### ISSUE TITLE
能不能把响应内容替换成时间戳或随机数

### ISSUE THREAD

**Issue by BabyCY** [avwo/whistle#31]
比如 test.html 里面有个<script src="test.js"></script>,我想拦截这个test.js,但是因为有缓存，所以浏览器不会发起请求，拦截失败。因此，想要替换成<script src="test.js?时间戳"></script>，这样就能发起请求了。

**Comment by avwo** [comment]
可以直接禁用某些url的缓存：[disable](https://avwo.github.io/whistle/rules/disable.html)

如果要加时间戳比较麻烦：用[ruleFile](https://avwo.github.io/whistle/rules/rulesFile.html)动态生成时间戳及[resReplace](https://avwo.github.io/whistle/rules/resReplace.html)规则做内容替换

**Comment by BabyCY** [comment]
pc端还好，主要是移动端开发比较麻烦，有些根本清不了缓存，像微信的缓存就很恶心，fiddler就可以写js表达式，charles也不行。这个功能还是很需要的

**Comment by avwo** [comment]
可以通过[插件](https://avwo.github.io/whistle/plugins.html)或[ruleFile](https://avwo.github.io/whistle/rules/rulesFile.html)结合[resReplace](https://avwo.github.io/whistle/rules/resReplace.html)动态生成规则做这个事情

**Comment by BabyCY** [comment]
好的，谢谢
