### ISSUE TITLE
Hostname does not parse correctly

### ISSUE THREAD

**Issue by fuminchao** [avwo/whistle#310]
Found in 1.15.10

```curl -X GET "http://baidu.com?xxx=123%20asdf" -H "Host: baidu.com:80" -x http://127.0.0.1:8899 -i```

```
HTTP/1.1 502 Bad Gateway
X-Powered-By: Express
content-type: text/html; charset=utf8
server: whistle
Date: Fri, 02 Aug 2019 02:27:31 GMT
Connection: keep-alive
Transfer-Encoding: chunked

<pre>
DNS Lookup Failed
From: whistle@1.15.10
Node: v10.15.3
Date: 8/2/2019, 10:27:31 AM
Error: getaddrinfo ENOTFOUND asdf
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (dns.js:56:26)
```

**Comment by avwo** [comment]
[Update whistle and restart](https://wproxy.org/whistle/update.html)

**Comment by fuminchao** [comment]
@avwo 
Still be reproducible in 1.15.14

**Comment by avwo** [comment]
Ok, I know what the problem is. I will release a version tonight to fix this problem.

**Comment by avwo** [comment]
Already fixed, [update whistle and restart](https://wproxy.org/whistle/update.html)

**Comment by fuminchao** [comment]
good job
