### ISSUE TITLE
文档"匹配原则" 一章有个链接错误

### ISSUE THREAD

**Issue by helinjiang** [avwo/whistle#313]
http://wproxy.org/whistle/principle.html

第一行的 “协议列表” 地址是 404 ，貌似正确的地址应该是  http://wproxy.org/whistle/rules/ ？

还有另外一处
![image](https://user-images.githubusercontent.com/13464168/62676151-5b774e80-b9dc-11e9-893d-9c3dd4edd24e.png)

**Comment by avwo** [comment]
多谢指正，你也可以直接改后提个 pr https://github.com/avwo/whistle/tree/master/docs/zh
