### ISSUE TITLE
接口返回报文解析错误

### ISSUE THREAD

**Issue by fairytaildhk** [avwo/whistle#315]
From: whistle@1.15.7
Node: v10.16.0
Date: 2019-8-9 11:45:02 AM
Error: incorrect header check
    at Zlib.zlibOnError [as onerror] (zlib.js:162:17)

**Comment by fairytaildhk** [comment]
> From: whistle@1.15.7
> Node: v10.16.0
> Date: 2019-8-9 11:45:02 AM
> Error: incorrect header check
> at Zlib.zlibOnError [as onerror] (zlib.js:162:17)

返回的headers
Date: Fri, 09 Aug 2019 05:59:09 GMT
Content-Type: application/json;charset=UTF-8
Transfer-Encoding: chunked
Connection: keep-alive
Content-Encoding: gzip

**Comment by avwo** [comment]
gzip无法解压问题，是线上对url吗？发我看下，或者你可以先禁用gzip `域名 delete://req.headers.accept-encoding`

**Comment by fairytaildhk** [comment]
> gzip无法解压问题，是线上对url吗？发我看下，或者你可以先禁用gzip `域名 delete://req.headers.accept-encoding`，直接使用 `pattern disable://gzip` 也行

**Comment by fairytaildhk** [comment]
加到rules里吗？我刚才试了一下不行
这是线上的url
是我们公司的app

**Comment by avwo** [comment]
对，加到Rules里面，`www.xxx.com disable://gzip`，`www.xxx.com` 表示你们url的域名

**Comment by fairytaildhk** [comment]
app.poizon.com disable://gzip
加了不行，我用其他抓包工具都ok
毒app

**Comment by bilibiliou** [comment]
我也遇到这样的问题了

**Comment by bilibiliou** [comment]
也是公司的app

**Comment by avwo** [comment]
更新下node试试，或者问下你们公司的APP的gzip有什么特殊除了

**Comment by bilibiliou** [comment]
charles 能抓到... @avwo

**Comment by aix3** [comment]
我也遇到了, 但是我是请求 body 解析错误, iOS 系统
```
From: whistle@2.5.6
 Node: v12.16.3
 Date: 12/2/2020, 10:00:41 AM
 Error: incorrect header check at Zlib.zlibOnError [as onerror] (zlib.js:180:17)	
```

**Comment by avwo** [comment]
更新下 whistle

**Comment by bilibiliou** [comment]
这个问题我这边解决了，原因是客户端的同学把发请求的jsbrigde 的请求头写错了，建议排查一下请求链路过程中请求头是否有错别字，非法的请求头之类的 @avwo @aix3

**Comment by aix3** [comment]
更新最新版本之后解决了, 感谢 @avwo @bilibiliou
