### ISSUE TITLE
关于证书过期时间的问题

### ISSUE THREAD

**Issue by winderica** [avwo/whistle#316]
测试环境：
* Android 9.0
* Chrome 76.0.3809.111
* whistle 1.16.2

抓https的时候发现chrome报`NET::ERR_CERT_VALIDITY_TOO_LONG`，找到了类似的[issue](https://github.com/mitmproxy/mitmproxy/issues/3273)，提到了是过期时间的问题。
自己签了一个1年过期的根证书，还是报同样的错。
翻了下源码，发现是[这一行](https://github.com/avwo/whistle/blob/master/lib/https/ca.js#L330)把过期时间设置成了10年后，手动改成1年就可以了。

**Comment by avwo** [comment]
多谢反馈，下个版本解决这个问题，你可以提个pr，把普通证书有效期改成2年

**Comment by winderica** [comment]
感谢回复，pr稍后就提。

**Comment by avwo** [comment]
重新安装whistle再重启试试

**Comment by winderica** [comment]
改成2年（总的duration是36个月）好像还是太长了，1年（24个月）是没问题的，reopen。
chrome的限制好像比39个月的标准更严格。

**Comment by avwo** [comment]
更新后重启whistle 了没，把浏览器也重启一下

**Comment by winderica** [comment]
都重启了。
在chromium源码里找到了[判断的逻辑](https://chromium.googlesource.com/chromium/src/+/refs/heads/master/net/cert/cert_verify_proc.cc#900)，2018年3月1日后的过期时间被限制在了825天（27个月）以内。
验证了一下确实是这样的：
![exp](https://user-images.githubusercontent.com/13536040/63522134-5a8d0380-c52a-11e9-80e8-80a0edf8b0ba.png)

**Comment by avwo** [comment]
好的，可以改成1年，测试ok重新提个pr

**Comment by winderica** [comment]
现在应该没问题了。

**Comment by LeoEatle** [comment]
升级whistle后似乎要重新安装证书才能生效

**Comment by avwo** [comment]
不需要的，这个不影响根证书。
