### ISSUE TITLE
请问有计划支持http2抓包吗?

### ISSUE THREAD

**Issue by dong2590** [avwo/whistle#32]
@avwo

**Comment by avwo** [comment]
这个可以支持，现在http2应用还比较少，你那边有应用场景么

**Comment by dong2590** [comment]
我们目前有在尝试，如果有计划支持就太好了：）

**Comment by teabyii** [comment]
我这边也有需要使用 http2 的场景，如果能够支持就太好了。
感谢作者开发一个这么棒的工具。

**Comment by avwo** [comment]
这个要等 `whistle v2.0` 版本才可以支持，具体发布时间我这边要规划下，到时再同步到这个issue。

**Comment by zhuscat** [comment]
@avwo 不知道目前的进展情况如何呢

**Comment by avwo** [comment]
今年下半年支持

**Comment by avwo** [comment]
see #333
