### ISSUE TITLE
麻烦请教下whistle怎么做到PASSTHROUGH

### ISSUE THREAD

**Issue by tvc-components** [avwo/whistle#320]
用其他代理的时候，局域网的时候https证书无法被代理，但是whistle可以，想问下作者的实现思路。是dns的问题还是证书的问题，再或者是其他的问题，大概猜的这几点。

**Comment by avwo** [comment]
要装代理的根证书才行

**Comment by tvc-components** [comment]
证书装过了。。。我想问的是作者如何处理的ssl握手过程中证书异常然后继续请求的问题。我看了whistle和node-mitm-proxy的一部分源码，都是通过起一个https server处理ssl证书，然后起一个request，去代理请求的，但是node-mitm-proxy在我说的情况下就无法代理，whistle可以，但是whistle内部处理逻辑太多了，不知道是哪里的处理起效了，所以想问下作者。

**Comment by avwo** [comment]
可能你们的请求不支持sni导致的，whistle 会判断下你的请求带sni没，如果没有会单独起个server处理

**Comment by tvc-components** [comment]
好的谢谢，我先确认下SNI的支持情况。

**Comment by tvc-components** [comment]
又填了一个坑，确实是不支持SNI，然后通过openssl看了下 SSL握手的证书 TLSv1/SSLv3, Cipher is RC4-SHA
另外我看了下确实https server 也启动成功了，但是最后还是会因为ssl版本问题爆出一些错误，这种情况是怎么处理的呢。

**Comment by avwo** [comment]
升级下node试试

**Comment by tvc-components** [comment]
v10.1.0 挺高的了。我再看看吧。
