### ISSUE TITLE
安卓，安装并且信任证书后，还是有部分浏览器出现当前证书不可信

### ISSUE THREAD

**Issue by Maxxxz** [avwo/whistle#321]
1、确认安卓手机已经安装好证书（qq和微信能抓到https）
2、确认qq浏览器内部导入了用户证书（另一台电脑安装下的证书可以抓到qq浏览器的https请求）
3、qq浏览器报错：当前证书不可信且证书链长度为1，可能是服务器没有配置完整证书链，是否信任并继续访问？
4、同一台电脑的证书，安装到ios下一切正常
请问下是证书的问题吗？是否可以重新生成证书？

**Comment by avwo** [comment]
Android碎片化比较严重，有些浏览器不支持自定义根证书，可以直接在whistle的 `~/.WhistleAppData/custom_certs` 放正式证书，或者把系统root，或者尽量用Chrome等支持自定义根证书等浏览器

**Comment by Maxxxz** [comment]
后续继续试了下，安卓QQ浏览器确实没有导入证书，也查问到相关人证实了，
之前某次成功应该是不小心看错了，抱歉

**Comment by MarcCaesars** [comment]
> Android碎片化比较严重，有些浏览器不支持自定义根证书，可以直接在whistle的 `~/.WhistleAppData/custom_certs` 放正式证书，或者把系统root，或者尽量用Chrome等支持自定义根证书等浏览器

正式证书指的是线上域名对应的crt和key文件吗？例如example.com对应的真实的example.crt(带有root/中间人/使用者三个CA的证书)和example.key文件？假如一个页面的静态文件在CDN域名下，还需要引入对应CDN域名的证书，对吗？
辛苦解答下~

**Comment by avwo** [comment]
对，就是服务里面配置的 crt 和 key 文件
