### ISSUE TITLE
证书来自不可信的授权中心

### ISSUE THREAD

**Issue by hxlniada** [avwo/whistle#322]
部分手机上出现证书不信任的问题
其中一个为：

手机：小米MIX2
系统：MIUI 10.2

类似于：

![image](https://user-images.githubusercontent.com/3838586/63855767-c233ca80-c9d2-11e9-97d0-c1db72a61f93.png)

请问该如何解决

**Comment by avwo** [comment]
https://github.com/avwo/whistle/issues/321
