### ISSUE TITLE
关于 IP 端口配置的问题

### ISSUE THREAD

**Issue by treadpit** [avwo/whistle#323]
### 在 whistle 里配置：

![image](https://user-images.githubusercontent.com/10692855/64065648-9f0f5200-cc42-11e9-9398-8563d55ab6f5.png)

### 本地8000端口服务可以正常访问：
![image](https://user-images.githubusercontent.com/10692855/64065651-a33b6f80-cc42-11e9-8c59-c2a8b7ef5868.png)

### 使用域名mytest.com则不能正常访问
![image](https://user-images.githubusercontent.com/10692855/64065653-a59dc980-cc42-11e9-8dae-d8508c818b14.png)

**Comment by avwo** [comment]
用启动参数 -L my test.com

**Comment by treadpit** [comment]
感谢回复！ 

我按照[文档快速上手那里](http://wproxy.org/whistle/quickstart.html)，看到是直接配置端口即可的，这个还需要加启动参数？是指在w2启动时，如下？

```bash
w2 start -L mytest.com
```
这样启动后仍然无效呢，另外如果是转发端口是需要启动参数，如果是多个端口转发该如何处理呢？

**Comment by avwo** [comment]
mytest.com域名的dns指向你要访问的服务器了吗

**Comment by treadpit** [comment]
什么都没干现在莫名其妙的又好了，可以将 mytest.com 指向 127.0.0.1:8000 了，感谢 🍉

另外有个疑问请教下，如下配置，`www.ifeng.com` 生效，而 `www.baidu.com` 不生效，这是为什么呢？
```
127.0.0.1:8000 www.baidu.com
127.0.0.1:8000 www.ifeng.com
```

**Comment by treadpit** [comment]
查到原因了，因为本地host之前有个干扰了
