### ISSUE TITLE
【UI需求】Inspectors面板是否可添加url和query查看

### ISSUE THREAD

**Issue by kaivean** [avwo/whistle#326]
![image](https://user-images.githubusercontent.com/3810606/65216296-fd617f00-dae2-11e9-804a-bd37395124fc.png)

如图：在Overview面版有URL地址，在Inspectors面版没有URL。那么每次操作查看URL和请求头很麻烦，需要两个面板来回切。

是不是可以考虑：在Inspectors在加一个url，同时最好在Inspectors的子面板Headers里，能有query查看，这样就不用来回切，这样可以在点击切换请求列表的不同请求时，快速看到信息

3ks

**Comment by avwo** [comment]
1. `Query` 可以在 `WebForms` 里面查看
2. 下个版本可以在 `Inspectors ` 加个 URL 字段

**Comment by kaivean** [comment]
> 1. `Query` 可以在 `WebForms` 里面查看
> 2. 下个版本可以在 `Inspectors ` 加个 URL 字段

1.

**Comment by kaivean** [comment]
query是否可以想开发者工具一样，也在一个页面里

**Comment by avwo** [comment]
小屏幕放不下，切个tab的体验也还可以啊

**Comment by avwo** [comment]
重新安装下whistle并重启
