### ISSUE TITLE
请问，最新版本是否支持tls1.3

### ISSUE THREAD

**Issue by njnuzhao** [avwo/whistle#327]
你好，我待测试的APP默认采用tls1.3，whistle的最新版本支持tls1.3的流量分析吗？谢谢

**Comment by avwo** [comment]
这个跟node版本有关，可以分别试下Node 10,  11,  12

**Comment by njnuzhao** [comment]
谢谢回复。
最近在用burpsuite，其tls支持与java版本有关。但是它仅支持和server端采用tls1.3，但是与客户端不支持tls1.3.
如果node支持tls1.3，那么whistle不会又类似于burpsuite的情况吧？

谢谢关注

**Comment by avwo** [comment]
只要Node支持就可以

**Comment by njnuzhao** [comment]
谢谢回复。我采用最新的node.js，但是没有成功，还请麻烦看下是什么原因，非常感谢。详细步骤如下
1. 下载最新的node.js，版本号如下v12.10.0
![1](https://user-images.githubusercontent.com/55618084/65373277-db682800-dcad-11e9-894b-255c348844b5.png)

2. 安装whistle并启动，开启捕获https流量
npm install whistle -g --registry=https://registry.npm.taobao.org
whistle run -p 8888

3. Android手机导入证书，可成功捕获https流量如下所示
![2](https://user-images.githubusercontent.com/55618084/65373290-09e60300-dcae-11e9-9868-9bb248071e58.png)

4. 采用该网站办法https://developer.ibm.com/blogs/migrating-to-tls13-in-nodejs/设置环境变量，开启默认支持tls1.3  
NODE_OPTIONS=--tls-max-v1.3（添加至/etc/profile）

5. 启动Android APP，无法通信成功，采用wireshark抓包发现，whistle认为客户端APP协议版本号不一致，如下所示
![3](https://user-images.githubusercontent.com/55618084/65373332-b1fbcc00-dcae-11e9-90ad-bd02170b420a.png)

**Comment by avwo** [comment]
也就是说客户端如果强制要求证书版本为tls1.3，就无法和whistle 正常建立连接？我这边怎么重现？事实上连接的建立过程是node做的，whistle 只是提供证书校验连接合法性，证书应该和tls的版本无关，或者换个系统或Node版本试试。

**Comment by avwo** [comment]
用最新版的 whistle 和 node
