### ISSUE TITLE
predefined parameters for plugins

### ISSUE THREAD

**Issue by davisbra** [avwo/whistle#328]
hi
is it possible to add predefined parameters for plugins when starting new instance?
for example when running new instance enable autosave plugin and give a directory to log files in this command:
w2 start -p 1080 -S data1080   -D datad1080

**Comment by avwo** [comment]
You can pass the data to the plugin via the command line argument `-e stringifyData` and get it in the plugin via:
``` js
module.xxxServer = (server, options) => { 
  cosole.log(options.config.extra);
}
```
