### ISSUE TITLE
Get 请求带有花括号时会自动转码导致无法匹配规则

### ISSUE THREAD

**Issue by zarkin404** [avwo/whistle#329]
当发起一个 get 请求时，如果 url 的参数带有花括号，会自动解析成 %7B 和 %7D，导致无法匹配规则。

譬如请求的 url 如下：
http://foobar.com/test.html?map=[{%22unit_id%22:21,%22dep_id%22:4380,%22schedule_id%22:%2224a5151d8731e9faa2952ed54fc35d178a3480ce24%22}]

whistle 拦截到请求就会变成：
http://foobar.com/test.html?map=[%7B%22unit_id%22:21,%22dep_id%22:4380,%22schedule_id%22:%2224a5151d8731e9faa2952ed54fc35d178a3480ce24%22%7D]

**Comment by avwo** [comment]
重新安装下 whistle 并重启

**Comment by zarkin404** [comment]
嗯，可以了。
