### ISSUE TITLE
很好的软件，话说监听端口协议能用https吗。。。

### ISSUE THREAD

**Issue by OneWizard** [avwo/whistle#33]
有些软件限制不能用http协议代理，比如我想Proxifier只接管某一程序到whistle，接http有限制。。。
或者有啥比较方便的转http到https的？

**Comment by avwo** [comment]
一般软件都会支持http代理，可以试下把系统的各种协议都设成whistle的ip和端口看下或者把软件名称发我看下，whistle本身是支持http转成https，只要配置类似 `http://www.baidu.com/ https://www.baidu.com/` 即可，有关开启https拦截及安装根证书可以参考：[https://avwo.github.io/whistle/webui/https.html](https://avwo.github.io/whistle/webui/https.html)

**Comment by OneWizard** [comment]
谢谢，目前排查后发现是Privoxy的问题，程序个例，可能是时候换个代理调度了，whistle感觉很不错
要是方便备份整个配置就好了

**Comment by avwo** [comment]
看下这几个：

1. [reqWrite](https://avwo.github.io/whistle/rules/reqWrite.html)
2. [resWrite](https://avwo.github.io/whistle/rules/resWrite.html)
3. [reqWriteRaw](https://avwo.github.io/whistle/rules/reqWriteRaw.html)
4. [resWriteRaw](https://avwo.github.io/whistle/rules/resWriteRaw.html)
5. [exportsUrl](https://avwo.github.io/whistle/rules/exportsUrl.html)
6. [exports](https://avwo.github.io/whistle/rules/exports.html)
