### ISSUE TITLE
【稳定性】MacOS下，代理隧道频繁不响应

### ISSUE THREAD

**Issue by Lucien-X** [avwo/whistle#330]
在MacOS下运行
```shell
w2 start
```
之后，时不时会出现代理隧道长时间不响应的问题
```shell
w2 restart
```
之后又恢复了，没直接进程序debug，不知道是不是消息阻塞堆积导致的。

总是要手动重启有点烦

**Comment by avwo** [comment]
whistle可以抓到响应慢的请求的包吗，看下是不是上游服务响应比较慢？可以用最新版的 Node 和 whistle 试试。

**Comment by Lucien-X** [comment]
@avwo 可以排除上游服务的问题，node 版本是 11.0.0，whistle版本是1.16.10。
我先升级下最新版本1.16.13试试

**Comment by avwo** [comment]
https://github.com/avwo/whistle/issues/231

**Comment by Lucien-X** [comment]
@avwo
升级了Node到12版本，貌似没问题了。
建议将这个版本提醒加在文档中醒目的地方，
已经安装了node的开发者们大多不会care自己当前的node版本。

**Comment by avwo** [comment]
后续可以在文档或启动命令行加提醒。
进程监控对于单用户版本意义不大，后面会推出基于 whistle 的多用户版本倒可以考虑加上这个功能

**Comment by Lucien-X** [comment]
> 后续可以在文档或启动命令行加提醒。
> 进程监控对于单用户版本意义不大，后面会推出基于 whistle 的多用户版本倒可以考虑加上这个功能

老哥稳，期待哈哈。我先关issue了
