### ISSUE TITLE
怎么实现像anyproxy一样通过js自由修改res的内容

### ISSUE THREAD

**Issue by timedcy** [avwo/whistle#332]
怎么实现像anyproxy一样通过js自由修改res的内容,可以读写req res
比如anyproxy的方法， 如* beforeSendResponse(requestDetail, responseDetail)

**Comment by avwo** [comment]
修改请求可以通过插件实现，可以有两种方式：
1. whistle直接把整个请求转个插件，全部交给插件处理（相当于自己处理请求）
2. 或者通过插件的rulesServer及pipe功能，动态设置规则及编码修改请求响应内容
具体参见：https://wproxy.org/whistle/plugins.html
