### ISSUE TITLE
whistle 2.0 已发布，开始支持 HTTP/2

### ISSUE THREAD

**Issue by avwo** [avwo/whistle#333]
whistle 2.0 版本开始全面支持 HTTP/2，大幅提升了性能，建议大家及时[更新 whistle](https://wproxy.org/whistle/update.html)。由于 Node 从 `v10.10.0` 开始才正式支持 HTTP/2 请求，且前期几个版本存在bug（ https://github.com/nodejs/node/issues/24037 、 https://github.com/nodejs/node/issues/24470 ），大家务必将本地的 Node 更新到 [`LTS >= v10.16.0 ` 或 `Stable >= v12.12.0`](https://nodejs.org/) 的最新版本。

**Comment by avwo** [comment]
请更新到 `v2.1.0` 版本，修复了h2请求 url 替换路径拼接有误到问题

**Comment by yangxiangfu** [comment]
升级到了2.1.2好像抓不了https的包

**Comment by avwo** [comment]
看下代理插件的配置，还有是否开启捕获https请求

**Comment by JiyuShao** [comment]
> 升级到了2.1.2好像抓不了https的包
我也是一样的问题, 降级到 v2.1.0 后可以抓 https
试了另外一个 Mac 装 v2.1.2  则是好的.

**Comment by avwo** [comment]
更新下node试试
