### ISSUE TITLE
微信下可以打开https,但是企业微信提示证书不可信!

### ISSUE THREAD

**Issue by snoopy83101** [avwo/whistle#334]
![image](https://user-images.githubusercontent.com/24613784/66969726-552cdf00-f0bd-11e9-851b-ebe12dd09255.png)

**Comment by snoopy83101** [comment]
是华为 mate20
证书肯定已经安装了, 在微信的"文件传输助手"中点击可以打开https
但是在企业微信的"文件传输助手"中打开就是这样的.
开发企业微信遇到阻碍了.有什么解决办法吗?

**Comment by snoopy83101** [comment]
是华为 mate20
证书肯定已经安装了, 在微信的"文件传输助手"中点击可以打开https
但是在企业微信的"文件传输助手"中打开就是这样的.
开发企业微信遇到阻碍了.有什么解决办法吗?

**Comment by avwo** [comment]
这个得让企业微信支持自定义根证书，参考下 https://github.com/avwo/whistle/issues/251

**Comment by snoopy83101** [comment]
@avwo 感谢! 我查看了#251, 但不幸的是, 那是等微信自己意识到问题然后发布了新的版本才解决的, 现在很明显企业微信没有意识到这个问题,  在这之前, 如何才能让企业微信支持自定义根证书?

**Comment by avwo** [comment]
这个我跟企业微信的同事反馈看看，如果有正式的证书，可以通过在whistle添加自定义证书解决，放在 `~/.WhistleAppData/custom_certs` 目录重启即可。

**Comment by gaoshijun1993** [comment]
@avwo 请问使用socks5协议理论上能够实现不安装证书的情况下实现代理吗?

**Comment by avwo** [comment]
可以代理，但看不到请求响应内容

**Comment by avwo** [comment]
更新的企业微信版本
