### ISSUE TITLE
whistle更新到v2.1.0之后，总是掉线

### ISSUE THREAD

**Issue by zhulemomo** [avwo/whistle#335]
更新之前都是没问题的，更新之后，whistle开始总掉线，尤其代理页面，刷新几次之后就会掉线，再次w2 start又能恢复连接，然后又掉线，反复这样。证书也已经重新安装了，还是无效，防火墙也都关了，麻烦帮看下是什么原因？
系统：MacOS v10.14.6
Chrome：77.0.3865.120

whistle的现象如下，处于offline的状态：
![企业微信截图_ce370623-ba36-4023-b369-92a6949f67cf](https://user-images.githubusercontent.com/20922408/66987135-bd49e800-f0f2-11e9-90e9-78ba470b88e6.png)
下面是node版本和whistle版本
![企业微信截图_4f2b9b1d-f732-4ce1-9d1c-692c9eb119ba](https://user-images.githubusercontent.com/20922408/66987240-f6825800-f0f2-11e9-9cfa-cf099756690e.png)

**Comment by avwo** [comment]
更新下node试试

**Comment by zhulemomo** [comment]
感谢大神，好使了。
