### ISSUE TITLE
多个团队成员使用配置不同端口配置了好像不生效？

### ISSUE THREAD

**Issue by yangxiangfu** [avwo/whistle#337]
w2 start -p 5501 -P 5501

直接用这样的命令就可以么？ 配置了好像没生效
![image](https://user-images.githubusercontent.com/4188833/67192161-a9b9bc80-f425-11e9-83d8-7e6f44dc63bc.png)

**Comment by avwo** [comment]
多用户版本可以用这个插件：https://www.npmjs.com/package/whistle.nohost ，或者等半个月左右时间，我们会推出一个更加简单的 npm 包实现多用户功能

**Comment by yangxiangfu** [comment]
是迁移了吗 帮助文档页面404了

**Comment by yangxiangfu** [comment]
多用户版本的有计划什么时候更新吗

**Comment by avwo** [comment]
预计下周

**Comment by gaoshijun1993** [comment]
@avwo 请问什么时候更新😂

**Comment by avwo** [comment]
https://github.com/nohosts/nohost
