### ISSUE TITLE
WebSocket只能查看握手请求,无法查看帧数据吗?

### ISSUE THREAD

**Issue by dong2590** [avwo/whistle#34]
@avwo 麻烦答疑下,谢谢.

**Comment by avwo** [comment]
目前只能看到请url和请求响应头；传输内容要等后续的插件，还在开发中，预计最快下个月可以发布

**Comment by hfdiao** [comment]
websocket 终于有盼头了...等了好久这个功能

**Comment by dong2590** [comment]
@avwo 请问这个功能进度如何了？还有盼头吗？

**Comment by avwo** [comment]
本地已经拉了个分支在做这个事情，先用这个插件[whistle.script](https://github.com/whistle-plugins/whistle.script)撑段时间，`v1.6.0` 会直接在whistle上内置这个功能，可以支持抓包、拦截、修改、构造WebSocket请求

**Comment by dong2590** [comment]
好的，多谢啦，已经用上了whistle.script插件了，不过指南关于websocket配置中有些错误

> 设置WebSocket请求的规则(需要开启HTTPs拦截):
 exports.handleWebSocket = (ctx) => {
   // ctx.fullUrl 可以获取请求url
   // ctx.headers 可以获取请求头
   // ctx.options 里面包含一些特殊的请求头字段，分别可以获取一些额外信息，如请求方法、设置的规则等
   this.rules = '127.0.0.1 echo.websocket.org';
 };

上述`exports.handleWebSocket` 应该是 `exports.handleRequestRules `

**Comment by avwo** [comment]
是我写错了，你直接提个pr把它改下，后续有问题也可以提pr

**Comment by avwo** [comment]
应该是 `handleWebsocketRules`

**Comment by avwo** [comment]
更新到最新版本即可：https://avwo.github.io/whistle/update.html
