### ISSUE TITLE
可以同时开启多个服务吗

### ISSUE THREAD

**Issue by gaoshijun1993** [avwo/whistle#344]
rt, 想在同一台机器代理同一个域名到多个不同端口,因此需要支持开启多个服务

**Comment by avwo** [comment]
最近两周会发布多用户版本

**Comment by yangxiangfu** [comment]
> 最近两周会发布多用户版本

这个功能这周可以体验么

**Comment by yangxiangfu** [comment]
> 最近两周会发布多用户版本

这个功能可以用了吗

**Comment by avwo** [comment]
https://github.com/nohosts/nohost
