### ISSUE TITLE
代理到本地后找不到的资源可以返回原先线上的资源吗？

### ISSUE THREAD

**Issue by sileiHard** [avwo/whistle#346]

**Comment by avwo** [comment]
用 [xfile](https://wproxy.org/whistle/rules/rule/file.html)

**Comment by sileiHard** [comment]
那如果是本地ip呢？
比如www.test.com 192.168.105.1:3000
里面有一些资源在本地端口读取不到

**Comment by avwo** [comment]
`www.test.com 192.168.105.1:3000 excludeFilter://regexp `  过滤掉匹配 regexp 的url
