### ISSUE TITLE
请问有什么方法，可以把我电脑上的Chrome模拟界面代理到手机上吗？

### ISSUE THREAD

**Issue by zhulemomo** [avwo/whistle#347]
也就是说，手机上显示的页面跟电脑上Chrome显示的界面是同步的，电脑上的Chrome做了什么操作，手机上也同步展示。
请问目前的代理方法能做到吗？还是说可以通过编写插件的方式实现？如果通过插件能实现的话，插件要怎么写呢？
麻烦指教~

**Comment by avwo** [comment]
这个需要系统支持，纯js实现还没见过
