### ISSUE TITLE
像下面nginx这样转发怎么配置？

### ISSUE THREAD

**Issue by a526672351** [avwo/whistle#35]
location  ~.*\.(gif|jpg|jpeg|png|bmp|swf|ico|js|css|html)$
        {
            root   html;
            proxy_pass http://127.0.0.1:8080;
        }
        location / {
            root   html;
            proxy_pass http://192.168.30.118:8877;

        }

**Comment by avwo** [comment]
用[rulesFile](https://avwo.github.io/whistle/rules/rulesFile.html)关联脚本文件或[Values](https://avwo.github.io/whistle/webui/values.html)里面设置的脚本，利用脚本判断url及请求的headers动态设置规则，如：`www.test.com rules:///User/xxx/test.js`

**Comment by a526672351** [comment]
看了加入了rulesFile ，文档不是好清晰，能根据上面nginx配置写个Dome吗？

**Comment by avwo** [comment]
test.js: 

```
url = url.replace(/\?.*$/, '');
if (/^https?:/.test(url)) {
  var index = url.indexOf('://') + 3;
  url = url.substring(index);
  index = url.indexOf('/');
  if (index === -1) {
    host = url;
    url = '/';
  } else {
    host = url.substring(0, index);
    url = url.substring(index);
  }
  var isRoot = url === '/';
  if (isRoot || /\.(gif|jpg|jpeg|png|bmp|swf|ico|js|css|html)$/i.test(url)) {
    rules.push(host + ' http://' + host);
    rules.push(host + ' ' + (isRoot ? '192.168.30.118:8877' : '127.0.0.1:8080'));
  }
}
```
示例图：

![rulesFile](http://p1.bqimg.com/567571/2122da0b9a02a3c8.png)

**Comment by avwo** [comment]
`protocol://{test.js}` 表示取Values中`test.js`的值，`protocol:///User/xxx/test.js` 表示取本地文件 `/User/xxx/test.js` 的值

**Comment by a526672351** [comment]
刚测试了，不行，报错
Date: 2017-03-10 08:55:55.676
Error: connect ECONNREFUSED 127.0.0.1:80
    at Object.exports._errnoException (util.js:873:11)
    at exports._exceptionWithHostPort (util.js:896:20)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1077:14)

**Comment by a526672351** [comment]
直接修改为这样了
url = url.replace(/\?.*$/, '');
if (/^https?:/.test(url)) {
  var index = url.indexOf('://') + 3;
  url = url.substring(index);
  index = url.indexOf('/');
  if (index === -1) {
    host = url;
    url = '/';
  } else {
    host = url.substring(0, index);
    url = url.substring(index);
  }
  var isRoot = url === '/';
  if (isRoot || /\.(gif|jpg|jpeg|png|bmp|swf|ico|js|css|html)$/i.test(url)) {
   // rules.push(host + ' http://' + host);
   // rules.push(host + ' ' + (isRoot ? '192.168.30.118:8877' : '127.0.0.1:8080'));
    rules.push(host + ' http://' +  '127.0.0.1:8080');
  }else{
    rules.push(host + ' http://' +  '192.168.30.118:8877');
  }
}

**Comment by avwo** [comment]
可以用正则解决：

```
# 以域名 www.test.com 为例
# 把https请求转成http
https://www.test.com http://www.test.com
# 把根路径的请求转发到指定的ip和端口
/^https?:\/\/www\.test\.com(:\d*)?\/?(\?|$)/ 192.168.30.118:8877
# 处理后缀为gif|jpg|jpeg|png|bmp|swf|ico|js|css|html的请求
/^https?:\/\/www\.test\.com(:\d*)?\/\.(gif|jpg|jpeg|png|bmp|swf|ico|js|css|html)(\?|$)/ 127.0.0.1:8080

```

**Comment by a526672351** [comment]
刚测试了，目前配置直接正则，不起效果

**Comment by avwo** [comment]
怎么配的，发我看下

**Comment by avwo** [comment]
# 以域名 www.test.com 为例
# 把https请求转成http
https://www.test.com http://www.test.com
# 把根路径的请求转发到指定的ip和端口
/^https?:\/\/www\.test\.com(:\d*)?\/?(\?|$)/ 192.168.30.118:8877
# 处理后缀为gif|jpg|jpeg|png|bmp|swf|ico|js|css|html的请求
/^https?:\/\/www\.test\.com(:\d*)?\/[^?]*\.(gif|jpg|jpeg|png|bmp|swf|ico|js|css|html)(\?|$)/i 127.0.0.1:8080

**Comment by a526672351** [comment]
我是这样配置，还是真实地址IP了，不起作用，我访问的是http，不是https直接配置如下：
#Rules
www.test.com  rulesFile://{rulesFile.txt} 

#rulesFile.txt：
# 以域名 www.test.com 为例
# 把https请求转成http
https://www.test.com http://www.test.com
# 把根路径的请求转发到指定的ip和端口
/^http?:\/\/test\.test\.com(:\d*)?\/?(\?|$)/ 192.168.30.118:8877
# 处理后缀为gif|jpg|jpeg|png|bmp|swf|ico|js|css|html的请求
/^http?:\/\/test\.test\.com(:\d*)?\/\.(gif|jpg|jpeg|png|bmp|swf|ico|js|css|html)(\?|$)/i 127.0.0.1:8080

**Comment by avwo** [comment]
最后这条规则改下：

```
/^https?:\/\/www\.test\.com(:\d*)?\/[^?]*\.(gif|jpg|jpeg|png|bmp|swf|ico|js|css|html)(\?|$)/i 127.0.0.1:8080
```

**Comment by a526672351** [comment]
测试了，我在w2的网络监控看到了，域名IP无法转发，还是指向源地址，没有效果

**Comment by avwo** [comment]
加QQ群：462558941

**Comment by yukiyuki1900** [comment]
我现在也同样遇到这个问题，使用配置：

/^http:\/\/www\.subtest\.test\.com(:\d*)?\/[^?]*\.(gif|jpg|jpeg|png|bmp|swf|ico|js|css|html)(\?|$)/i 192.170.30.12

无法转发到IP地址，还是指向原地址，请问这个问题是怎么解决的？

**Comment by avwo** [comment]
`/^http://www.subtest.test.com(:\d*)?/[^?]*.(gif|jpg|jpeg|png|bmp|swf|ico|js|css|html)(\?|$)/i 192.170.30.12` 最后一个问号要转义

**Comment by yukiyuki1900** [comment]
我的url是http://subtest.test.com/view/page?query=%E5%88%98%E5%BE%B7%E5%8D%8E&refer=abc

然后我配的规则是：

/^http:\/\/www\. subtest\.test\.com(:\d*)?\/?(\?|$)/  192.170.30.12

还是没法命中，请问这个配置是否正确呢？

**Comment by avwo** [comment]
匹配方式很多种，不一定用正则，尽量用合适的方式：[https://avwo.github.io/whistle/pattern.html](https://avwo.github.io/whistle/pattern.html)

正则有点问题：`(?|$)` -> `(\?|$)` 

下面这种就可以：

```
192.170.30.12 http://subtest.test.com/view/page 
```
