### ISSUE TITLE
通过whistle访问另一个whistle的管理页面时经常无法连接

### ISSUE THREAD

**Issue by deepjia** [avwo/whistle#352]
通过whistle无法访问另一个whistle的管理页面时（均为 whislte 2.2.4）
经常无法连接，有很多 `/...whistle-path.5b6af7b9884e1165.../` 的访问失败
![image](https://user-images.githubusercontent.com/1452602/69037252-808b4c80-0a22-11ea-847c-b9273660d7f9.png)

**Comment by avwo** [comment]
你是怎么访问的
