### ISSUE TITLE
期望能够支持location.hash = '#rules?ruleName=test' 直接切换Rules下面的不同规则

### ISSUE THREAD

**Issue by hxfdarling** [avwo/whistle#354]
1. 通过location.hash = '#rules?ruleName=test' ，直接切换到Rules 并且选中规则名称为test的规则
2. 如果通过点击规则列表切换规则名称，hash也应当同时变化为目标规则名例如，切换到all，那么hash就变成#rules?ruleName=all

**Comment by avwo** [comment]
更新下whistle

**Comment by hxfdarling** [comment]
还是有些问题，通过点击列表切换后，hash没有变更，导致赋值切换到a，点击切换到b，再赋值切换到a不能生效，建议环境名变化和hash保持一致，同时不要清理原来的参数比如location.hash = ‘#rules?ip=xx’  切换a应该只是修改参数,location.hash=‘#rules?ip=xx&rulesName=a'

2019年11月21日 22:53，avenwu <notifications@github.com<mailto:notifications@github.com>> 写道：


更新下whistle
