### ISSUE TITLE
如何配置socks规则?

### ISSUE THREAD

**Issue by gaoshijun1993** [avwo/whistle#356]
使用场景:客户端使用shadowsocks配置代理,使用socks协议,这样就不用在客户端安装证书
翻了文档和issuce似乎是支持socks协议的代理但是规则要怎样配置呢?

尝试了 test.com socks://xxx.xxx.xxx.xxx 的方式似乎是把请求代理到了另外个 服务器

**Comment by avwo** [comment]
你是想把 whistle 作为 socks server 使用吗，启动时加个参数即可 `--socksPort 1080`

**Comment by gaoshijun1993** [comment]
@avwo 是的,看了下通过w2 start --socksPort 貌似没有开启socks server

**Comment by echopi** [comment]
whistle as socks server, 学习了，我本地试过 OK 的 

![image](https://user-images.githubusercontent.com/16034964/70052368-1a9be900-160e-11ea-8e27-3dbc2a45843b.png)
