### ISSUE TITLE
[feature request] auto set callback

### ISSUE THREAD

**Issue by wolfsilver** [avwo/whistle#361]
Add a rule to auto set callback.
Config a json type value. If callback parameter in url, then wrap value with callback and return. Otherwise return the value directly.

**Comment by avwo** [comment]
http://wproxy.org/whistle/rules/rule/tpl.html
![image](https://user-images.githubusercontent.com/11450939/69961006-cd544480-1545-11ea-9a67-6216458d4ce2.png)

**Comment by wolfsilver** [comment]
Sorry I didn't say it clearly.
I mean when I set a value as `{a: 1234}`. If there is `callback=test` in the url, return 
```
test({a: 1234})
```
If not, return 
```
{a: 1234}
```

Auto return json or jsonp.

**Comment by avwo** [comment]
http://wproxy.org/whistle/plugins.html or http://wproxy.org/whistle/rules/reqScript.html

**Comment by echopi** [comment]
@wolfsilver `resScript` can make it:

```txt
pattern resScript://{res_script.js} 
```
`res_script.js` value:

```js
if (/[&?](callback|jsonp)=([^]+)/.test(url)) {
  	values['js_preappend.txt'] = `${RegExp.$2}(`;
  	values['res_append.txt'] = ')'
	rules.push(`${url} resType://js`);
  	rules.push(`${url} resPrepend://{js_preappend.txt}`);
	rules.push(`${url} resAppend://{res_append.txt}`);
}
```

**Comment by wolfsilver** [comment]
```
/callback=/  resScript://{res_script.js}
```
not a elegant way, but works fine.
Thanks.

jiewei.ljw <notifications@github.com> 于2019年12月3日周二 下午1:02写道：

**Comment by wolfsilver** [comment]
> @wolfsilver `resScript` can make it:
> 
> ```
> pattern resScript://{res_script.js} 
> ```
> 
> `res_script.js` value:
> 
> ```js
> if (/[&?](callback|jsonp)=([^&]+)/.test(url)) {
>   	values['js_preappend.txt'] = `${RegExp.$2}(`;
>   	values['res_append.txt'] = ')'
> 	rules.push(`${url} resType://js`);
>   	rules.push(`${url} resPrepend://{js_preappend.txt}`);
> 	rules.push(`${url} resAppend://{res_append.txt}`);
> }
> ```

```
/callback=/  resScript://{res_script.js}
```
not a elegant way, but works fine.
Thanks.

**Comment by wolfsilver** [comment]
> http://wproxy.org/whistle/plugins.html or http://wproxy.org/whistle/rules/reqScript.html

Implemented a plugin `whistle.xxtpl` to solve this.
`resScript` needs a lot of rule to set.

usage: 
```
pattern xxtpl://{res.json}
```
