### ISSUE TITLE
【建议】whistle加上『workflow工作流』扩展方式

### ISSUE THREAD

**Issue by onekb** [avwo/whistle#363]
macOS下有一款很好用的工具叫『Alfred』该工具有点像macOS里的spotlight聚焦。

它特别之处在于可以添加『workflow』扩展，比如可以翻译、转码、甚至下载文件。

以上这些功能『Alfred』本身不具有这样的操作，实现这些工作是通过扩展的方式实现。

扩展的项目，可以用任意语言实现，比如php、nodejs、Python、甚至shell脚本等都可以。

其流程是通过『Alfred』获取到用户输入的内容，通过终端cli调用对应的扩展入口文件。

比如用户输入内容abc，运行的应用是php，执行的文件是/usr/index.php。

则相当于在终端里输入（注：『Alfred』会把用户输入的内容xml编码）

> php /usr/index.php \<xml\>abc\<xml\> 

然后index.php执行后 echo出 xml编码后的内容返回给『Alfred』供其输出内容。

同理，whistle如果实现后，可以降低特定扩展的要求，比如resWorkflow则是把回来的内容丢给扩展工作流处理后，再返回给浏览器。工作的内容可以是另存为、记录日志、线上内容线下调试等操作。
至于resWorkflow://还是怎么样的协议命名格式，你们比我专业。

最后感谢whistle团队的无私辛勤付出。

以上

**Comment by echopi** [comment]
是说希望通过Alfred实现whistle插件的功能吗？我的理解，whistle插件和工作流还有一些差异，工作流是一些固定操作的快捷实现，whistle插件则是扩展功能。

**Comment by onekb** [comment]
> 是说希望通过Alfred实现whistle插件的功能吗？我的理解，whistle插件和工作流还有一些差异，工作流是一些固定操作的快捷实现，whistle插件则是扩展功能。

不是这个意思，我的意思是Alfred的扩展逻辑很简单，whistle的扩展也加上类似的这种扩展方式。也支持把『请求/响应』结果放到shell里执行并返回数据。

**Comment by echopi** [comment]
> 把『请求/响应』放到shell执行

这里是不是先写好一个shell命令？写完之后，whistle通过node调用拿到结果？是这么个流程吗？

if yes，感觉是把问题搞复杂了。

一种更好的体验应该是尽量都在whistle的webui全部操作完，我看 @avwo 有一个[whitsle.script](https://github.com/whistle-plugins/whistle.script#%E6%93%8D%E4%BD%9C%E8%AF%B7%E6%B1%82) 的插件，是不是更简单一些？
