### ISSUE TITLE
pipe 能否支持自定义方法，而不是去制作插件

### ISSUE THREAD

**Issue by laoergege** [avwo/whistle#364]
最近刚入用了whistle ，发觉为了 pipe 下响应数据，特么还得搞个插件，对新手，whistle 学习成本不知又高了。。。。

**Comment by avwo** [comment]
whistle 提供的内置操作可以满足大部分需求，实在不满足再用插件，开发插件可以用脚手架 https://github.com/avwo/lack

**Comment by avwo** [comment]
有空再改造下whistle.script，你也可以开发一个插件实现上述能力
