### ISSUE TITLE
【需求】期望能够提供选项，对目标站点的证书启用校验

### ISSUE THREAD

**Issue by snadn** [avwo/whistle#368]
因为 whistle 非常好用，目前已经将其当作一个简单的代理在用。

因为本地安装了根证书的原因，所有的 https 请求在浏览器都是成为合法的请求。然而，从个人使用安全的角度，期望目标站点的证书出问题的时候，whistle 能够终止请求或者给出提示，而不是转成一个合法的请求，屏蔽掉了相关的安全风险。

所以，能否提供一个选项，开启对目标站点证书的校验？非法则终止请求，或者给出提示。

**Comment by avwo** [comment]
可以通过配置实现：
``` txt
www.legal.com enable://capture
www.illegal.com enable://abort 
# 也可以返回403
www.illegal.com statusCode://403
```

**Comment by snadn** [comment]
@avwo 期望的是一种通用的代理策略，而不是针对某个网站的特殊规则。因为我的使用背景是把 whistle 当代理在用。

比如，我访问 github ，正常情况下证书是合法的。但可能因为我连接的网络被中间人攻击，证书被替换了，这时候如果我使用 whistle 在访问，期望能够得到提示。

**Comment by avwo** [comment]
如果是有中间人，请求自动中断吗？

**Comment by snadn** [comment]
自动中断是一种处理方式，也可以算是一种 “严格模式” 吧，现成的参考就是浏览器对非法证书页面的处理。
而在实现方式上是一个全局开关，还是一个规则，就需要熟悉项目的你们来决策了。

**Comment by avwo** [comment]
可以，我看下

**Comment by avwo** [comment]
重装安装whistle ，启动时加命令行参数 -M safe

**Comment by deepjia** [comment]
-M safe 似乎没有体现在文档里
