### ISSUE TITLE
设置请求速度reqSpeed无效

### ISSUE THREAD

**Issue by licongwell** [avwo/whistle#369]
经过测试，发现reqDelay resDelay reqSpeed 都可以起作用，唯独reqSpeed无效，把reqSpeed设置成2，加载速度还是没啥变化，理论上设置成2kb/s 网页会打开很慢的

**Comment by avwo** [comment]
没有请求内容吧

**Comment by licongwell** [comment]
请求速度设置很慢，下载静态资源，css,js,图片那些理论上应该会很慢的，但是还是很快就下载下来了。只有设置了reqSpeed很小后，静态资源就会下载明显变慢。
