### ISSUE TITLE
filter 协议失效，无法再按照 header 条件（包括 h/reqH/resH）过滤

### ISSUE THREAD

**Issue by WavinFlag** [avwo/whistle#372]
我有一条规则
```
line`
^http://example.com/static/***
http://localhost:3000/$1
includeFilter://reqH:referer=http://example.com
`
```

但是其中对请求头部的 filter 根本不起作用，当请求 referer 为其他 URL 或者没有 referer 的时候，这条规则仍然应用了，即仍然向我返回 localhost:3000 上的内容。

顺便，尝试 `includeFilter://*/**/blabla.js` 时，这条 filter 是生效的。

whistle 版本：2.4.2

**Comment by avwo** [comment]
这周发个版本fix这个问题， `url1 url2` 直接的匹配可以不用通配符匹配方式，它们会自动拼接剩余路径，如 `^http://example.com/static/*** http://localhost:3000/$1` 等价于 `http://example.com/static/ http://localhost:3000/`

**Comment by avwo** [comment]
重新安装 whistle 并重启试试
