### ISSUE TITLE
OPENSSL_internal:UNSUPPORTED_PROTOCOL

### ISSUE THREAD

**Issue by xcodebuild** [avwo/whistle#373]
```js
From: whistle@2.4.2
Node: v12.8.1
Date: 2019/12/25 下午4:58:59
Error: write EPROTO 140683778838504:error:100000f0:SSL routines:OPENSSL_internal:UNSUPPORTED_PROTOCOL:../../third_party/boringssl/src/ssl/handshake_client.cc:569:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:83:16)
```

访问 https://pbdw.ebank.cmbchina.com/cbmresource/8/cemxzm/bg1.png 时出现

**Comment by avwo** [comment]
升级下node看看

**Comment by xcodebuild** [comment]
实际上是 `electron`，升级 `electron` 到 `8.0.0-beta3`（`node 12.13.0`）仍然存在这个问题

不过看起来是 `electron` 使用 `boringssl` 造成的特定问题，和 `node` 无关

https://github.com/cypress-io/cypress/issues/5446

**Comment by xcodebuild** [comment]
然而 node 升级到 LTS 同样存在这个问题：

```
From: whistle@2.4.6
Node: v12.14.1
Date: 2020-1-14 21:25:53
Error: write EPROTO 4393782720:error:1425F102:SSL routines:ssl_choose_client_version:unsupported protocol:../deps/openssl/openssl/ssl/statem/statem_lib.c:1929:

    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:87:16)
```

只是报错不太一样

**Comment by xcodebuild** [comment]
related to https://github.com/nodejs/node/issues/27384

加上 `--tls-v1.0` 即可，因为我是 `require('whistle')` 使用的所以漏了这个参数

**Comment by panzhangguo** [comment]
> related to [nodejs/node#27384](https://github.com/nodejs/node/issues/27384)
> 
> 加上 `--tls-v1.0` 即可，因为我是 `require('whistle')` 使用的所以漏了这个参数

兄弟，怎么弄啊？加在哪里呢？完整的可以看下吗

**Comment by avwo** [comment]
https://github.com/avwo/starting/blob/master/lib/cli.js#L206
