### ISSUE TITLE
SyntaxError: Unexpected token '<'

### ISSUE THREAD

**Issue by MissLlq** [avwo/whistle#377]
报错信息如下：
```
Date: 2020/1/2 下午5:10:37
SyntaxError: Unexpected token '<'
Unexpected token '<'
Page Url: http://**.cmfurl.cn/gjj/#/?Vlog=Y
User Agent: Mozilla/5.0 (iPhone; CPU iPhone OS 13_1_2 like Mac OS X) AppleWebKit/605.1.15 (KHTML, like Gecko) Mobile/15E148 MPBank/7.5.0 iPhone/13.1.2 Scale/3.0 AID/VXdF7ifNEFjE0rlkocs85Aljzwo= SID/lAvi3BAusTMd4dRxoqe5gSmXDnk= WebView/WKWebView APPTag/1.0(N;44;321) 
```

页面可以代理过来，但获取vue节点#app的内容时报错。琢磨了好久无法解决，麻烦帮忙看一下是什么原因！

**Comment by avwo** [comment]
这个应该是加载脚本时返回 html 了，看下是不是出现 404 了

**Comment by MissLlq** [comment]
是的，加载的js文件，显示的type值是text/html ,但是没有报404。

**Comment by avwo** [comment]
看下请求发哪去了，是不是配了host 或者 本地替换 导致的

**Comment by MissLlq** [comment]
能否加我微信（llq763572886），我截图给你看，这样效率比较高。🙏🙏🙏

**Comment by MissLlq** [comment]
这是Whistle的配置：
http://*.cmburl.cn/gjj/  127.0.0.1:8080
http://*.cmburl.cn/gjj/ log://
http://*.cmburl.cn/sockjs-node 127.0.0.1:8080
http://*.cmburl.cn/gjj/  whistle.inspect://

这是vue.config.js的配置：
module.exports = {
  publicPath: "./",
  outputDir: "dist",
  devServer: {
    open: true, 
    host: "0.0.0.0",
    port: 8080,
    hot: true,
  }
}

**Comment by echopi** [comment]
> 是的，加载的js文件，显示的type值是text/html ,但是没有报404。

可以尝试给js文件设置正确的 content type，如果是默认返回text/html ，可以在whistle.inspect之前，加一个 `pattern resType://js` 的规则

**Comment by MissLlq** [comment]
问题解决了，是我本地的Whistle rules写错了，应该是rule匹配却因为少了一个`/`，Whistle默认转成了host匹配，所以文件找不到。
本地打包好的js文件放在`127.0.0.1:8080/`目录下，即通过`127.0.0.1:8080/*.js`能加载成功，如果通过路径为`127.0.0.1:8080/gjj/*.js`就找不到，找不到时默认返回index.html文件，html文件以js格式解析所以报SyntaxError: Unexpected token '<'，因为html文件是以`<!DOCTYPE html>`开头；

配置问题解析：
         rules配置：`**.cmburl.cn/gjj/  127.0.0.1:8080` (错误)
改成：
         rules配置：`**.cmburl.cn/gjj/  127.0.0.1:8080/`（正确）
即可。

错误的rules配置，相当于请求`**.cmburl.cn/gjj/` 中的js文件时代理到`127.0.0.1:8080/gjj`中查找相应的js文件。这是host匹配，`127.0.0.1:8080`匹配`**.cmburl.cn`

正确的rules配置，相当于请求`**.cmburl.cn/gjj/` 中的js文件时代理到`127.0.0.1:8080/`中查找相应的js文件。这是rule匹配，`127.0.0.1:8080/`匹配`**.cmburl.cn/gjj/`

**Comment by avwo** [comment]
host 和 URL 替换的区别参考下这篇文章：https://juejin.im/post/5e14445be51d45415a66754a
