### ISSUE TITLE
json字符串字段在Inspectors中影响性能

### ISSUE THREAD

**Issue by Bacra** [avwo/whistle#381]
json中的某个字段，如果是字符串，又特别长的时候，显示会极度影响性能

**Comment by avwo** [comment]
是JSONView还是Text？这块是有考虑这种情况，把链接发我看下

**Comment by Bacra** [comment]
JSONView，单个字符串在 385k  (二进制文件base64，或其他大的数据) 以上，会很明显感觉到展开的时候，有卡顿

**Comment by avwo** [comment]
更新whistle
