### ISSUE TITLE
weinre成功连接手机后只加载出顶层dom,未能加载出全部结构树

### ISSUE THREAD

**Issue by fengyuyizai** [avwo/whistle#384]
环境
whistle: 2.4.7
mac: macOS Catalina 10.15.2
node: 12.13.0
测试机: iphone 12.4.1

问题详细描述:
正常启动whistle,  手机代理到本机8899, 随后测试机打开页面, 代理成功, 电脑打开weinre(此处连接失败率极高), 成功连接, 选择target, 打开elements, 仅仅解析了顶层dom

![image](https://user-images.githubusercontent.com/26406641/72589973-aad08c00-3937-11ea-901a-5413be0c6fed.png)

随后我不断点击下侧的dom层,切到那层dom后, 再次回退到顶层dom,以此循环
![image](https://user-images.githubusercontent.com/26406641/72590059-dce1ee00-3937-11ea-8f70-865527ac26b3.png)

![image](https://user-images.githubusercontent.com/26406641/72590850-b2913000-3939-11ea-9e9e-fb957766e436.jpg)

最终dom下一层打开,如果想查看所有dom, 那么几乎要这样大量循环操作 但是这样子做效率特别低, 是否是逻辑出现问题.

我之前版本是2.4.6, 最开始接触这个系统时候觉得发现新大陆, 这块功能也是正常的, 但是中间隔了几天没有,再次打开,变成了这个样子

以下是配置代码:
```
# test74

# 74
10.0.7.74 www.example.com

weinre://74 www.example.com
log://74 www.example.com

www.example.com/app/v1/activity/get_activity_list file://{get_activity_list.json}
```

虽然weinre是内嵌在whistle中, 但是作为whistle的重要组成部分, 期望能解决这个问题!

**Comment by avwo** [comment]
这块逻辑很久没动过，应该跟版本没关系，简单试了下pc上是ok的，有空我看看什么原因，你也可以自己看看什么问题

**Comment by echopi** [comment]
@fengyuyizai 做了一些测试：Android Chrome比iOS Safari 稳定一些，但都可以正常工作。

建议使用性能好一些的iOS或者Andriod:
1. iPhone 有些机子如6 网络性能不佳
2. dom结构通过协议从浏览器拉回来，性能好点的测试机速度会快些

**Comment by avwo** [comment]
试下这个插件： https://github.com/liriliri/whistle.chii
