### ISSUE TITLE
抓https包的时候无法联网

### ISSUE THREAD

**Issue by YeFei572** [avwo/whistle#385]
> 1.Capture HTTPS CONNECTs：开启Https拦截功能，只有勾上这个checkbox及装好根证书，whistle才能看到HTTPS、Websocket的请求

按照文档操作，当勾选checkbox后直接导致整个app无法上网，尝试过多个app，比如b站的app，安居客等，
手机系统为`小米6`
当关掉checkbox的时候app恢复正常，然后所有的https请求全部变成了http请求，并且显示：
![image](https://user-images.githubusercontent.com/26360338/72678977-a944c680-3ae5-11ea-9f3e-f0ceadfaa5cf.png)

**Comment by avwo** [comment]
https://wproxy.org/whistle/questions.html

**Comment by YeFei572** [comment]
读过文档才来提的issue

**Comment by avwo** [comment]
android app可以设置支不支持用户自定义证书，除非 root，否则无法绕过，或者用 iOS  代替

**Comment by YeFei572** [comment]
如果我用模拟器可否绕过这一关卡？
发现目前有些可以抓到bilibili的，有些抓不到
