### ISSUE TITLE
resMerge 填写值的类型

### ISSUE THREAD

**Issue by zhaoxm469** [avwo/whistle#389]
我用这种方法 改一下 请求的响应  resMerge://(code=200) 想返回Number类型的200 
可是返回的结果 是 String类型的 200 
![image](https://user-images.githubusercontent.com/26950016/75302260-3400aa00-5878-11ea-8234-48249e68dd32.png)
需要怎么设置呀？？

**Comment by avwo** [comment]
resMerge://({“code”:200})

**Comment by zhaoxm469** [comment]
好的 感谢回复

**Comment by avwo** [comment]
也可以用内嵌的方式，这种会自动转换数字：
```` txt
``` test
code: 200
test: 201
```
resMerge://{test}
````
