### ISSUE TITLE
DNS Lookup Failed

### ISSUE THREAD

**Issue by jazzhuang** [avwo/whistle#39]
在mac下，设置网络https代理为127.0.0.1  8899后；
chrome访问，一起正常，抓包也没有问题；
但是使用chrome的插件postman工具发起相同的请求后，提示错误如下：
![image](https://cloud.githubusercontent.com/assets/1787270/25428072/35384876-2aa7-11e7-9c1f-6e07148a09a7.png)

**Comment by avwo** [comment]
用whistle抓包看下request的raw data

**Comment by jazzhuang** [comment]
我找到原因了：
由于request中，header的Host设置为了null；
whistle会拿  这header属性进行发送请求，而不是拿url中的xxx.com作为目标请求地址。

**Comment by avwo** [comment]
下个版fix

**Comment by avwo** [comment]
怎么重现这个问题？
