### ISSUE TITLE
[feature request]network 支持structure模式

### ISSUE THREAD

**Issue by broven** [avwo/whistle#390]
支持类似charles 这种抓包展现方式
![image](https://user-images.githubusercontent.com/12854613/75462655-84365400-59bf-11ea-9cc5-df0a80e02bde.png)

看看需求怎么样, 有人想要没, 有人想搞没, 有人想要没人有时间弄的的话 我发一个PR

**Comment by avwo** [comment]
欢迎PR

**Comment by avwo** [comment]
Duplicate of #165
