### ISSUE TITLE
升级到2.4.12后很容易崩溃

### ISSUE THREAD

**Issue by lumixraku** [avwo/whistle#391]
所有tab 页按钮都变为灰色了
大概代理只能坚持5秒...
且端口没有监听 
更换端口也没能解决这个问题  还是很容易出现刚才的情况

**Comment by avwo** [comment]
看下启动目录有没有人whistle.log 文件，或者用 w2 run 运行看看报什么错，建议用新版本的node

**Comment by lumixraku** [comment]
好的  下次抓到了贴上来
