### ISSUE TITLE
macos10.15.3 无法安装whistle的https证书

### ISSUE THREAD

**Issue by LincWong** [avwo/whistle#392]
nodejs版本：10.13.0

故障起因：
今天升级whistle到**最新版本**后，无法抓https包。删除钥匙串证书后，重新从rootca.pro下载新的证书，但是下载下来的crt文件无法添加到mac的钥匙串证书里面去。老版本的crt文件可以。

尝试解决：
降级到1.4，rootca.pro下载的crt证书文件也无法安装了。

望解惑

**Comment by avwo** [comment]
安装后要确认，看文档或者网上搜下怎么安装

**Comment by LincWong** [comment]
由于有用到custom自定义证书，导致下载的证书在安卓机上无法安装。

删除自定义证书后，重新下载证书安装修复问题。
