### ISSUE TITLE
english docs?

### ISSUE THREAD

**Issue by shirshak55** [avwo/whistle#393]
I don't know chinese but is there any english docs?

https://wproxy.org/whistle/

**Comment by echopi** [comment]
@shirshak55 working on it, so stay tuned

**Comment by lizy0329** [comment]
> I don't know chinese but is there any english docs?
> 
> https://wproxy.org/whistle/

I want to know that What proxy tools to use now？Fiddler？Charles？

**Comment by shirshak55** [comment]
I use proxyman . I used to use charles.

**Comment by bittu** [comment]
Sorry if i missed english version docs as this is marked as completed may i get english version docs please.
