### ISSUE TITLE
socks协议不稳定

### ISSUE THREAD

**Issue by alsotang** [avwo/whistle#394]
```shell
$ w2 version
2.4.12
```

前段时间在家里远程办公，我通过 `socks://127.0.0.1:1080 *.google.com` 来使用我本地的shadowsocks（以下简称ss）。每隔五六个小时之后，访问google就会显示『正在等待 google.com 的响应』然后就卡住了。需要 `w2 restart` 才能继续工作。

长期以来我使用 chrome 插件 SwitchyOmega 来使用这个socks5代理，则不会出现类似的不稳定现象。所以我判断这个问题是whistle导致的。

另外：w2的http代理功能还是比较稳定的，平时在公司使用 `/./ proxy://127.0.0.1:12639` 没出现过类似的掉线情况。

**Comment by alsotang** [comment]
也可能是我的socks那里域名写得不全，先忽略。。

**Comment by JingLMalan** [comment]
> 也可能是我的socks那里域名写得不全，先忽略。。

自问自答了一番😁
