### ISSUE TITLE
能否支持response内容检索

### ISSUE THREAD

**Issue by SheepYoung** [avwo/whistle#396]
#### 能否支持response内容检索
开发app的时候， 需要看看接口返回的某个字段，比如是json格式的或者其他格式的

**Comment by avwo** [comment]
过滤框输入：b:keyword 
https://wproxy.org/whistle/webui/network.html

**Comment by SheepYoung** [comment]
多谢， 文档需要更新了~~

2020年3月13日 18:16，avenwu <notifications@github.com<mailto:notifications@github.com>> 写道：



过滤框输入：b:keyword
https://wproxy.org/whistle/webui/network.html
