### ISSUE TITLE
做了一个whistle第三方uTools插件，欢迎试用

### ISSUE THREAD

**Issue by MrLeo** [avwo/whistle#398]
![8omCcQ.png](https://s1.ax1x.com/2020/03/22/8omCcQ.png)
![8om3H1.png](https://s1.ax1x.com/2020/03/22/8om3H1.png)

> 项目地址：[utools-whistle](https://github.com/MrLeo/utools-whistle)
> 
> 关于我：[xuebin.me](https://xuebin.me)

**Comment by aogg** [comment]
搞个开机启动吧，每次都需要手动启动

**Comment by avwo** [comment]
https://github.com/avwo/whistle/tree/master/assets/launcher

**Comment by MrLeo** [comment]
我是用PM2来管理的

**Comment by jinjinwa** [comment]
跟我科学上网的代理端口冲突了
