### ISSUE TITLE
返回的Content-Type为application/octet-stream时的处理

### ISSUE THREAD

**Issue by jazzhuang** [avwo/whistle#40]
当返回的header属性Content-Type为application/octet-stream时，建议可以尝试以文本的方式展示；

注：像postman这样的工具会正常展示哦。

当前表现：
![image](https://cloud.githubusercontent.com/assets/1787270/25471405/83b38724-2b59-11e7-9736-17b06db372f6.png)
![image](https://cloud.githubusercontent.com/assets/1787270/25471431/9cca4216-2b59-11e7-8c95-f17df95f6655.png)

**Comment by avwo** [comment]
内存、硬盘空间及常用性考虑，whistle只显示纯文本(xml, js, css, html, text, json等)，如果要查看其它类型的数据，可以用[resWrite](https://avwo.github.io/whistle/rules/resWrite.html)、[resWriteRaw](https://avwo.github.io/whistle/rules/resWriteRaw.html)
