### ISSUE TITLE
主界面的Filter里，能否在Network Columns添加自定义的列，显示消息中的特定字段

### ISSUE THREAD

**Issue by tidus5** [avwo/whistle#400]
如题。可否实现将 消息解码的特定信息，在主界面展示呢？

**Comment by avwo** [comment]
是显示内容还是头部信息，能不能举个具体的应用场景？

**Comment by tidus5** [comment]
比如说项目内，消息是 Protobuf  或者 AMF 之类编码的。
解码出来其中一个字段是method， 代表这条消息的方法名。
如果能把方法名 单独展示到左边NetWork栏，这样看起来就比较直观
这样直接搜索查找某个方法名也会比较方便。

**Comment by avwo** [comment]
重新安装下 whistle 并重启：https://wproxy.org/whistle/rules/style.html
