### ISSUE TITLE
若干疑问、建议

### ISSUE THREAD

**Issue by hktalent** [avwo/whistle#403]
## 疑问
* 1、插件能否修改现有的界面，增加、减少列，增加鼠标提示？
* 2、能否像burp那样发送repeat，修改请求、响应的头和数据？
* 3、能否设置全局的请求头信息，例如cookie？
* 4、如何设置注入制定的js文件、或片段到html，或js文件中？例如beef

## 建议
* 1、能否支持多个被动代理工具
```
例如同时启动了burp、appscan、zap、x-ray
他们的二级代理都是whistle
但是whistle会将请求都同时分发给上述若干工具的代理，并携带特定头信息
以便这些工具再次请求whistle时，通过特定头信息直接返回结果，避免多次向服务器请求
也就是whistle只请求一次，同时为若干被动代理工具提供二次代理服务

```

**Comment by avwo** [comment]
都支持：
1. 可以增减自定义列：https://wproxy.org/whistle/rules/style.html
2. 可以 Replay 及 Composer ，详见 Network 上方菜单及右键菜单
3. 就是一个匹配问题，`* reqHeaders://data` 或 `* reqCookies://data`（匹配所有请求） ，详见：https://wproxy.org/whistle/rules/
4. 可以，同3，也封装成插件，这样其他人安装即可用，如：https://github.com/whistle-plugins/whistle.inspect
5. 支持配置上游代理：https://wproxy.org/whistle/rules/
![image](https://user-images.githubusercontent.com/11450939/78974533-c2896c00-7b44-11ea-8623-515379b26695.png)

**Comment by hktalent** [comment]
docker内运行报错了，能否提供docker版本啊，规避各种环境复杂的问题
使用者自己通过-v映射自己的插件进去@avwo 

另外，同时为若干个 需要被动代理的工具 提供二次代理时，确定只想目标服务器发送一次请求嘛？
不会每个被动代理都请求来都往真实目标服务器请求一次嘛？
@avwo 

```
docker run -v $mtx/../tools/whistle:/usr/local/lib/node_modules -p 8899:8899  -it node:8.9.4-alpine /bin/sh

~ # npm install whistle -g --registry=https://registry.npm.taobao.org
/usr/local/bin/wproxy -> /usr/local/lib/node_modules/whistle/bin/whistle.js
npm ERR! path /usr/local/lib/node_modules/whistle/bin/whistle.js
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! syscall chmod
npm ERR! enoent ENOENT: no such file or directory, chmod '/usr/local/lib/node_modules/whistle/bin/whistle.js'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-04-10T08_07_51_367Z-debug.log

```

**Comment by hktalent** [comment]
docker默认环境请求头信息无法直接修改
建议默认功能支持修改，像burp一样
等和burp差不多，我愿意赞助money哦😀

@avwo

**Comment by avwo** [comment]
修改请求头是最基本需求，肯定支持，whistle所有操作都是配置的。
安装错误你看下是不是机器的网络问题导致安装失败，你可以先本地试试看。

**Comment by hktalent** [comment]
@avwo 能否结合“如何给多个被动代理工具提供仅一次请求的<被动代理>服务？“
做一个图文教程啊？

- 1、burp、appscan、zap、x-ray上的二次代理都设置指向whistle
- 2、如何确认whistle正对多个代理的相同请求都基于缓存直接返回呢？

**Comment by avwo** [comment]
不能完全明白你想做什么，你可以把 whistle 当成一个既可以转发请求，也可以直接处理请求的服务，理论上涉及请求的，什么都可以做。
