### ISSUE TITLE
做了一个快速切换 Whistle 规则的插件，欢迎试用

### ISSUE THREAD

**Issue by Quilljou** [avwo/whistle#405]
[chrome商店地址](https://chrome.google.com/webstore/detail/whistler/jkohblcpemjicbcaicciplcddbfiajkf)
[crx下载](https://github.com/Quilljou/whistler/releases)
支持代理到 Whistle，支持代理的同时分流了科学上网流量，欢迎试用

**Comment by avwo** [comment]
**做得挺好的，不仅功能完善，UI看起来也很舒服。**

遇到两个小问题：
1.  `Whistle UI 端口` 配置可以去掉，有点多余，会增加用户配置成本，一般代理端口可以访问，UI 肯定也可以访问了。
2. 修改端口后要重新切换下面的代理开关才能生效。

![image](https://user-images.githubusercontent.com/11450939/79087393-b3d3cc80-7d71-11ea-8ff5-d42e485208fc.png)

**Comment by Quilljou** [comment]
> **做得挺好的，不仅功能完善，UI看起来也很舒服。**
> 
> 遇到两个小问题：
> 
> 1. `Whistle UI 端口` 配置可以去掉，有点多余，会增加用户配置成本，一般代理端口可以访问，UI 肯定也可以访问了。
> 2. 修改端口后要重新切换下面的代理开关才能生效。
> 
> ![image](https://user-images.githubusercontent.com/11450939/79087393-b3d3cc80-7d71-11ea-8ff5-d42e485208fc.png)

1. UI 端口配置用来打开 Whistle 网页端，因为 Whistle 可以配置这个端口，插件这边也同步了配置，也提供了默认配置
2. 这个我重新发个版本

**Comment by avwo** [comment]
👍，Whistle UI端口对用户有点多余，直接通过代理端口也可以访问，且容易造成用户切换端口时忘了改UI端口而出现问题。

**Comment by avwo** [comment]
`PAC自动分流` 建议默认关上（PAC脚本能支持自定义那就更好了），像我们公司访问外网需要经过代理，默认开 `PAC自动分流` 会导致某些网站功能不可用：
> 点击左下角 Whistle 图标自动切换到抓包界面这个功能很棒

![image](https://user-images.githubusercontent.com/11450939/79099767-76823580-7d97-11ea-92e1-6bcd097aa45c.png)

**Comment by Quilljou** [comment]
> 👍，Whistle UI端口对用户有点多余，直接通过代理端口也可以访问，且容易造成用户切换端口时忘了改UI端口而出现问题。

嗯，去掉了UI端口的设置。估计会自己设置UI端口的用户应该很少。等 Chrome 商店审核了

**Comment by Quilljou** [comment]
> `PAC自动分流` 建议默认关上（PAC脚本能支持自定义那就更好了），像我们公司访问外网需要经过代理，默认开 `PAC自动分流` 会导致某些网站功能不可用：
可以默认关上。PAC脚本自定义 用这个功能的应该比较少，后续有需求再加上

**Comment by avwo** [comment]
类似 switchyomega 的自动切换模式会有用到，比如我们这边内网系统支持快速登录，但快速登录客户端严格限制了登录页面的请求需要从浏览器发出才行，不能经过代理转发，所以我们一般用 switchyomega 的自动切换模式把快速登录页面的域名直接请求到公司的客户端。
![image](https://user-images.githubusercontent.com/11450939/79117253-36ce4480-7dbd-11ea-92c4-b9ed7640a90b.png)

**Comment by Quilljou** [comment]
貌似自定义PAC脚本确实可以支持你这个需求。但是自己写PAC脚本会比较难受吧，切换了端口的话还得改 PAC 脚本，有翻墙的需求的话得基于 gfwlist 的 PAC 去自定义。如果可以接受可以支持下

**Comment by avwo** [comment]
如果可以提供类似 switchyomega 的简单配置最好，实在不行用pac也是可以接受的，至少能解决现有问题。

**Comment by Quilljou** [comment]
更新了一个版本，支持了自定义 pac 脚本

**Comment by deepjia** [comment]
关闭/重新开启 Default 规则时，把 Default 规则给清除了

**Comment by Quilljou** [comment]
> 关闭/重新开启 Default 规则时，把 Default 规则给清除了

My bad. 发了个新版在审核了

**Comment by Pain-and-Love** [comment]
如果本地没有启动 whistle, 它会自动帮忙启动嘛？

**Comment by Quilljou** [comment]
> 如果可以设置 【是否开启系统代理】 就更好了

Chrome扩展貌似没有 设置为系统代理 的能力

**Comment by lizy0329** [comment]
这个有啥用？SwitchyOmega 的 auto switch 能够替代大部分功能？
