### ISSUE TITLE
拦截请求后怎么阻止请求呢？

### ISSUE THREAD

**Issue by lyc8023** [avwo/whistle#406]
项目里用了阿里云arms监控，会不停的发送请求，可以拦截到相关请求，不在network面板显示

![image](https://user-images.githubusercontent.com/47591031/79318841-1ecfff80-7f3a-11ea-837a-01823efa44fa.png)
但是我打开 weinre 后，请求太多导致weinre的network卡死，而且elment的dom节点选择也只能选择顶层，然后没多久target 就断开连接了
有没有办法拦截到这个请求后，禁止继续请求呢

**Comment by avwo** [comment]
1. 直接返回200，并加缓存试试
``` txt
arms-retcode.aliyuncs.xxx statusCode://200 cache://300000
```
> 域名自己补齐，如果请求有随机数，可以把缓存去掉

2. 如果阿里云监控脚本是一个单独外链，用 `url  statusCode://200` 置空
3. 如果阿里云监控脚本是注入的，可以用 `resReplace` 把阿里云的监控脚本破坏掉：https://wproxy.org/whistle/rules/resReplace.html

**Comment by lyc8023** [comment]
万分感谢，不过我们这个是npm安装的，打包到 app.js里了，我把这个单独打包试一下

**Comment by lyc8023** [comment]
https://test.imonkey.xueersi.com/static/monkey-math/experienceClass?user_id=1838&client_id=212101&platform=ios&wxinstall=1&aliinstall=1&app_version=1.0.1
在移动端我正常打开页面的时候，页面vconsole 很流畅且Network就几个请求
![image](https://user-images.githubusercontent.com/47591031/79331114-44b2cf80-7f4d-11ea-8c4a-4452d7933cd8.png)

用了whistle代理后，就特别卡，等一会点击vconsole可以看到network里面有很多请求，为甚么这个arms的请求这么多。。后面的还有whistle-path错误

![image](https://user-images.githubusercontent.com/47591031/79331114-44b2cf80-7f4d-11ea-8c4a-4452d7933cd8.png)

**Comment by avwo** [comment]
这个是 weinre 的请求，你是不是注入了 weinre 和 vConsole，vConsole 先不要和 weinre 同时使用看看

**Comment by lyc8023** [comment]
我把项目里面的vConsole关掉了，然后weinre的target可以一直保持连接状态，点击dom也能很快 展开了，一切都正常，除了console面板一直打印，点击console面板 没多久就卡死导致断开连接
![image](https://user-images.githubusercontent.com/47591031/79333692-8e9db480-7f51-11ea-978b-35612ea9053b.png)

**Comment by avwo** [comment]
不需要在构建时打包 vConsole，可以用这个 whistle 插件动态注入：https://github.com/whistle-plugins/whistle.inspect

**Comment by lyc8023** [comment]
嗯嗯，我那个问题是访问app内嵌h5时出现的，正常浏览器访问是没有问题的，谢谢您的热情帮助🌹🌹🌹

**Comment by lyc8023** [comment]
昨天那个不断打印输出导致weinre卡死的这个应该是whistle打印的，截图里面有 `/...whistle-path.5b6af7b9884e1165...///weinre:8899/ws/target/`
我看源码里面也是有相关拼接的url， 
`config.WEBUI_PATH = '/...whistle-path.5b6af7b9884e1165...///';`
`var weinrePath = config.WEBUI_PATH + 'weinre.' + config.port;`
想了解一下什么情况会导致不断打印

**Comment by avwo** [comment]
vConsole 和 weinre 不要同时使用，上面不是说了吗
