### ISSUE TITLE
Header 太大时请求会挂掉

### ISSUE THREAD

**Issue by xcodebuild** [avwo/whistle#407]
https://github.com/alibaba/lightproxy/issues/92

![image](https://user-images.githubusercontent.com/5436704/79411095-918db900-7fd4-11ea-87d1-ce742e8cf51b.png)

**Comment by avwo** [comment]
Node 限制 `请求URL+ headers` 大小不能超过 8k，可以通过启动命令行参数自定义大小，参考：https://github.com/avwo/starting/blob/master/lib/cli.js#L201 和 https://nodejs.org/dist/latest-v12.x/docs/api/cli.html#cli_max_http_header_size_size
