### ISSUE TITLE
iPhone上安装证书时有坑

### ISSUE THREAD

**Issue by teal-front** [avwo/whistle#41]
作者应该强调下要用Safari下载安装证书，因为我之前用Chrome下载会提示文件没有对应的打开方式，换成微信传文件，同时提示没有对应的打开方式。 后来试了下Safari就会提示安装了。这个地方好坑，费了我一个多小时。

**Comment by echopi** [comment]
@teal-front https://avwo.github.io/whistle/webui/https.html 文档

**Comment by teal-front** [comment]
@echopi 其实文档上确实是有说IOS要用Safari去安装，但习惯性的用了Chrome，就怎么也安装不了。最后还是用Safari才能安装，所以想说可以在文档上着重强调下用Safari。。
