### ISSUE TITLE
网页操作面板中, values中保存的json导出问题

### ISSUE THREAD

**Issue by fengyuyizai** [avwo/whistle#410]
操作系统 mac
whistle版本号: 2.4.6

![image](https://user-images.githubusercontent.com/26406641/79951763-dff6f800-84ab-11ea-9a66-444a716c5aa1.png)
例如该图片是导出面板

直接点comfirm的话

![image](https://user-images.githubusercontent.com/26406641/79951990-43812580-84ac-11ea-8e30-1cc26679f966.png)
会直接导出一个txt文件, 而不是json文件, 而且丧失json原有格式

如果多选, 则将多个json文件融合为一个, 一并导出为一个txt文件

期望作者能关注下问题

**Comment by avwo** [comment]
只是后缀采用 `.txt`，方便文本编辑器打开，你是不是安装了专门插件json的软件，选择自定义打开方式试试？

**Comment by fengyuyizai** [comment]
没有, 只是vscode编辑器, 但是导出的txt

```
{
  "get_user_info.json": "{\n\n\t\"data\": {\n\t\t\"baseInfo\": {\n\t\t\t\"userId\": 12125525,\n\t\t\t\"icon\": \"\",\n\t\t\t\"mobile\": \"17694896254\",\n\t\t\t\"userName\": \"风雨\"\n\t\t},\n\t\t\"memberType\": {},\n\t\t\"bankCard\": {},\n\n\t\t\"verifyInfo\": {},\n\t\t\"userAsset\": {\n\t\t\t\"hasTradePassword\": 1\n\t\t},\n\t\t\"userExtend\": {}\n\t}\n}"
}
```

**Comment by avwo** [comment]
导出的数据本来就不是用来直接编辑的，可以自己做个编辑页面或者导入到whistle里面编辑
