### ISSUE TITLE
规则目录 -S newStorageDir 能使用绝对路径吗？

### ISSUE THREAD

**Issue by painty** [avwo/whistle#411]
系统：Windows10，执行以下命令

```bash
w2 start -S "D:/whistle-another" -p 1080
```

配置文件期望地址：
D:/whistle-another
实际在：
C:\Users\UserName\\.WhistleAppData\\.whistle\custom_dirs\D%3A%2Fwhistle-another

**Comment by avwo** [comment]
试试 `-D baseDir -S newStorage`

**Comment by painty** [comment]
> 试试 `-D baseDir -S newStorage`

`-D baseDir` 可以实现需要的效果，怪我没有认真看 -help 文档，感谢！
