### ISSUE TITLE
vue-router hash 链接不能跳转

### ISSUE THREAD

**Issue by lizy0329** [avwo/whistle#414]
https://van.xxx.cn/content/wap/safe redirect://https://lifestyle.xxx.cn/#/video/17836/0

这样的规则无法识别后面的 “#/video/17836/0”，导致只能跳转到 https://lifestyle.xxx.cn

可以告诉我怎样才能跳转到正确的链接吗？

**Comment by avwo** [comment]
```` txt
``` videoUrl
https://lifestyle.xxx.cn/#/video/17836/0
```
https://van.xxx.cn/content/wap/safe redirect://{videoUrl}
````

**Comment by lizy0329** [comment]
谢谢，新技能get

**Comment by avwo** [comment]
https://wproxy.org/whistle/data.html
