### ISSUE TITLE
[webui] darkmode 支持

### ISSUE THREAD

**Issue by xcodebuild** [avwo/whistle#417]
是否考虑通过 `prefers-color-scheme: dark` 支持 darkmode？目前在 LightProxy 的 darkmode 下看起来比较奇怪

![image](https://user-images.githubusercontent.com/5436704/80803354-96618800-8be4-11ea-8f16-63ec7fa55f8b.png)

**Comment by avwo** [comment]
遇到的问题：插件界面如何自动切换到 DarkMode？

**Comment by avwo** [comment]
该 issue 短时间无法解决暂时关闭，目前实现方案无法做到兼容插件界面需要等待：
1. 浏览器支持通过 css 自动转换到 darkmode （类似通过滤镜置灰效果）
2. 插件提供统一的 UI 库

**Comment by KrabsWong** [comment]
一个低成本，但有些暴力的实现方式

```css
html[theme="dark-model"] {
  filter: invert(1) hue-rotate(-180deg);
}
```

效果如下
<img width="2032" alt="image" src="https://github.com/avwo/whistle/assets/12368943/f7a16aa3-1d48-457f-b21d-d9fcd7caed39">


主流的桌面浏览器支持的还可以
<img width="1438" alt="image" src="https://github.com/avwo/whistle/assets/12368943/0528449b-c3cc-4cc9-a58c-a3854425ced3">
<img width="1457" alt="image" src="https://github.com/avwo/whistle/assets/12368943/90417356-bdd2-4a16-a18f-2cb2bb148a3c">

**Comment by avwo** [comment]
不错，我试试看

**Comment by DeHby** [comment]
> 不错，我试试看

你好 请问现在支持了吗？

**Comment by avwo** [comment]
已支持，要用最新版本，如果没效果，可以通过右上角 / Online / 去掉 `Disable dark mode`
