### ISSUE TITLE
现在能抓WebSocket的包了吗

### ISSUE THREAD

**Issue by lijunhuawhu** [avwo/whistle#42]
想抓websocket的包，但是现在好像还看不到，能看到http和https的包。不知道现在的版本支持抓websocket的包吗？

**Comment by avwo** [comment]
现在还不支持，最快下个月可以通过插件支持

**Comment by YY030913** [comment]
Websocket抓包有新进展了？

**Comment by avwo** [comment]
下周发1.6版本，支持websocket及socket请求抓包

**Comment by avwo** [comment]
`v1.6.0`版本已经支持，[更新到最新版本](https://avwo.github.io/whistle/update.html)，如何使用看下[WebSocket帮助文档](https://avwo.github.io/whistle/webui/websocket.html)。
