### ISSUE TITLE
设置了host映射后，用域名访问本地很慢，要很久才能打开

### ISSUE THREAD

**Issue by fanguyun214** [avwo/whistle#420]
angular项目，设置了host映射后，用域名访问本地很慢，要很久才能打开，甚至打不开，直接修改本地host就很快

**Comment by avwo** [comment]
node、whistle、规则配置发下

**Comment by fanguyun214** [comment]
> node、whistle、规则配置发下
# host映射
http://shop12345678.m.xiaodianpu.com 127.0.0.1:4200

node服务，基于angular-cli的启动
ng serve --host 0.0.0.0 --disableHostCheck=true

**Comment by fanguyun214** [comment]
我本地运行时，将编译方式改为--aot，移动端代理就很快了
ng serve --host 0.0.0.0 --disableHostCheck=true --aot

**Comment by avwo** [comment]
这种慢的问题应该是本地server响应比较慢，自己看下什么原因导致的。

> 我本地运行时，将编译方式改为--aot，移动端代理就很快了
> ng serve --host 0.0.0.0 --disableHostCheck=true --aot
