### ISSUE TITLE
从2.5.4升级到2.5.5后style协议好像有一个功能退化

### ISSUE THREAD

**Issue by huzhenghui** [avwo/whistle#421]
受影响的规则是这样的
请求的时候设置样式，并指定响应脚本
```
tunnel://**:443 style://{proxy.request.pass.style}
tunnel://**:443 resScript://{proxy.response.js}
```
响应脚本`proxy.response.js`如下
```
if('200' == statusCode) {
	rules.push(url + ' style://{proxy.response.200.style}');
} else if('404' == statusCode) {
	rules.push(url + ' style://{proxy.response.404.style}');
}
```
之前在2.5.4版本的时候，以及之前的版本，请求的时候设置`proxy.request.pass.style`样式，几秒钟请求完成后相应的设置`proxy.response.200.style`或者`proxy.response.404.style`。视觉效果类似于浏览器中开发者模式中的网络视图。今天升级到2.5.5后，发现功能失效了。后面设置的style出现在`all Rules`匹配表中，但是没有变化，仍旧是第一个style的效果。
或者您告诉我开发结构文档在哪里，我尝试调试一下。谢谢您对开源的贡献。

**Comment by avwo** [comment]
`2.5.5` 版本改了个匹配顺序，有点问题，已经修复，重新安装下whistle。

**Comment by huzhenghui** [comment]
非常感谢
