### ISSUE TITLE
替换请求包时，请求头中content-length被删除

### ISSUE THREAD

**Issue by joyczc** [avwo/whistle#422]
复现条件：content-type = application/x-www-form-urlencoded

**Comment by avwo** [comment]
性能考虑whistle 采用流得方式修改内容，而不是把所有内容加载到内存再修改，所以无法计算修改后的内容大小，删除content-length后node会自动转成chunked的方式，这个一般不会有什么影响？

**Comment by joyczc** [comment]
影响：有些cgi遇到content-length丢失，会返回412错误（Precondition Failed）

疑问：如果content-length是 multipart/form-data 这类，请求头中的content-length还能继续保留？

**Comment by avwo** [comment]
可以开发个插件专门设置content-length https://wproxy.org/whistle/plugins.html

**Comment by joyczc** [comment]
好的多谢
我这边了解到cgi返回412的具体原因是，请求经过了一层proxy，proxy不支持chunked，所以拒绝了请求
