### ISSUE TITLE
使用whistle重放包会修改body数据，例如\r\n\r\n会被修改成\n\n

### ISSUE THREAD

**Issue by WinChua** [avwo/whistle#423]
测试过程中发现, whistle在重放post请求的时候, 会修改body的数据，主要是：
body中的\r\n\r\n会被修改成\n\n, 附件是相应的case
[case.gz](https://github.com/avwo/whistle/files/4607280/case.gz)

这里whistle在重放的时候，不应该修改原包body的数据？

**Comment by avwo** [comment]
重新安装并重启
