### ISSUE TITLE
w2 stop -- [!] No running whistle

### ISSUE THREAD

**Issue by fewpiwork** [avwo/whistle#424]
root@iZj6c3ecgho1eg9x5stywsZ:/www/wwwroot/w2# w2 stop
[!] No running whistle
root@iZj6c3ecgho1eg9x5stywsZ:/www/wwwroot/w2# w2 status
All running whistle:
  1. port: 8899, storage: /www/wwwroot/w2
root@iZj6c3ecgho1eg9x5stywsZ:/www/wwwroot/w2# 

centos 7 x64 & debian 9 x64

都有这样的问题 请问有什么替代方式吗?

**Comment by avwo** [comment]
w2 stop -S  /www/wwwroot/w2
