### ISSUE TITLE
匹配的优先级是什么样的呢

### ISSUE THREAD

**Issue by fewpiwork** [avwo/whistle#426]
/config\.js/i file:///www/wwwroot/m2/config.js disable://cache ignore://* //ignore先生效了..无法替换js

/./ statusCode://200

我的意图是, 替换config.js 禁止其余的代理请求..因为是部署在云端使用的..不想被代理扫描器扫了去...

**Comment by avwo** [comment]
默认从上到下。
`ignore://*` 表示忽略所有规则，可以 `ignore://*|-file` 这种方式排除需要的规则。本地替换默认没有cache，第一条规则保留 `/config.js/i file:///www/wwwroot/m2/config.js` 即可

**Comment by fewpiwork** [comment]
请问是这样填写吗.. - -!

/config.js/i file:///www/wwwroot/m2/config.js
/./ statusCode://200 ignore://*|-file

**Comment by avwo** [comment]
``` txt
/config.js/i file:///www/wwwroot/m2/config.js
/./ statusCode://200 ignore://file
```
或
``` txt
/config.js/i file:///www/wwwroot/m2/config.js
/./ statusCode://200 excludeFilter:///config.js/i
```

**Comment by avwo** [comment]
`file` 和 `statusCode` 两个协议会冲突，优先采用容易实现的 `statusCode`，
如果要两个协议同时生效可以用 `replaceStatus` 代替。

**Comment by avwo** [comment]
重新安装并重启
