### ISSUE TITLE
a 'delete' can not proxy，request length = 0 ? return length is required

### ISSUE THREAD

**Issue by yordidi** [avwo/whistle#428]
![whistle-proxy](https://user-images.githubusercontent.com/13449526/82797845-3fc93000-9eaa-11ea-93a2-21c37166e8b1.png)
and my rule is
 /admin\.dev\.browser\.miui\.com\/panel\/[^napi]{?}[^api]{?}\// http://127.0.0.1:9001/panel/

**Comment by avwo** [comment]
有没有匹配修改请求内容的规则

**Comment by avwo** [comment]
你是用 whistle 的 Composer 构造的请求？重新安装下 whistle 并重启试试。
