### ISSUE TITLE
iOS下uc浏览器设置ws代理不生效

### ISSUE THREAD

**Issue by jndxzqc** [avwo/whistle#429]
iOS下uc浏览器设置ws代理不生效，safari正常

**Comment by avwo** [comment]
可以啊，你在 https://m.ke.qq.com/course/list?label_filter=%5B%5D&mt=1001&time_tab=2 里面打开一个直播课程看看

**Comment by avwo** [comment]
跟UC同事确认了，UC浏览器的 https 请求不走系统代理，直接走了云端加速，导致 whistle 无法抓到 https 请求，后面看下他们能否加个开关让开发者可以关闭此功能（目前设置里面有该选项，但貌似没有效果）

**Comment by lizy0329** [comment]
啧啧啧，UC
