### ISSUE TITLE
chrome更新到v58后，https的根证书无法使用了

### ISSUE THREAD

**Issue by gaocong1990** [avwo/whistle#43]
chrome更新到v58后，https的根证书无法使用了，目前怎么解决

**Comment by avwo** [comment]
更新whistle到最新版本 `npm i -g whistle`再重启试试看，如果不行启动的时候加个参数 `w2 restart -A` 重新生成根证书，再安装下新的根证书

**Comment by gaocong1990** [comment]
更新到最新版本可以了，谢谢

**Comment by chenxiaochun** [comment]
我的也无法使用了，下面是我的开发环境：
```
nodejs@v7.10.0
whistle@1.4.21
Mac Chrome版本：60.0.3112.90（正式版本） （64 位）
```

**Comment by avwo** [comment]
报什么错，w2 restart -A，重启后参考上面重新安装下根证书看看

**Comment by chenxiaochun** [comment]
没有报错。也反复按照上面的步骤操作过了。难道是我的使用姿势不对，我再查查。

**Comment by avwo** [comment]
https://github.com/avwo/whistle/issues/44

**Comment by echopi** [comment]
我的版本跟你基本一样，检查下证书，可以把 whistle 的证书都删了重新装一下最新的，再手动信任试试

![image](https://user-images.githubusercontent.com/16034964/28959917-1daacc34-792f-11e7-9aa1-833f4c564fb2.png)
