### ISSUE TITLE
请求响应慢时出现长时间 pending

### ISSUE THREAD

**Issue by xcodebuild** [avwo/whistle#432]
相关 Issue: https://github.com/alibaba/lightproxy/issues/142

> 使用 http://slowwly.robertomurray.co.uk/delay/3000/url/http://www.baidu.com 测试确实如此，反应为 3s 以上的 pending，但是最后加载完成后正确显示为 TTFB。

> ![image](https://user-images.githubusercontent.com/5436704/83016645-e2251700-a054-11ea-8ee2-7504f727f331.png)

**Comment by avwo** [comment]
这个url直接请求也很慢。

**Comment by xcodebuild** [comment]
@avwo 是的，这个请求就是专门 pause 3s 的 mock 请求

不过好像确实和我想象的不一样，不管是直接请求后端还是通过代理，都会显示 pending 状态，实际上请求已经发起只是在等待后端响应。

这么看来应该是 Devtools 的问题，相关的 Chrome 反馈：https://support.google.com/chrome/thread/49442697?hl=en
