### ISSUE TITLE
微博扫码进入whistle代理网页失败

### ISSUE THREAD

**Issue by CarryOnHxy** [avwo/whistle#433]
如题，h5页面需要在微博内打开，页面使用whistle代理后扫码进去，直接报'无法连接服务器'的提示，https证书已经在本地浏览器安装过了。
![image](https://user-images.githubusercontent.com/41328326/83393907-300d9680-a42a-11ea-8e7f-69cefa926845.png)
大佬求助！

**Comment by avwo** [comment]
可能证书问题，去掉下面这个勾选看看，如果正常那就是证书问题，这个除非有正式的证书，不然没法解决：

![image](https://user-images.githubusercontent.com/11450939/83394802-c68e8780-a42b-11ea-8138-1194758c0027.png)

**Comment by CarryOnHxy** [comment]
> 可能证书问题，去掉下面这个勾选看看，如果正常那就是证书问题，这个除非有正式的证书，不然没法解决：
> 
> ![image](https://user-images.githubusercontent.com/11450939/83394802-c68e8780-a42b-11ea-8138-1194758c0027.png)

将这个勾去掉后确实可以访问了，如果照你说的那样页面上的https请求且不是无法成功响应了

**Comment by avwo** [comment]
用iOS访问吧，Android这种情况需要app配置个参数：

![image](https://user-images.githubusercontent.com/11450939/83396225-3aca2a80-a42e-11ea-942d-07b427099f53.png)

https://developer.android.com/training/articles/security-config#base-config
