### ISSUE TITLE
jsAppend/jsPrepend 支持动态values吗？

### ISSUE THREAD

**Issue by djunny** [avwo/whistle#438]
规则：

baidu.com resScript://{cookie.js} jsPrepend://{tmp.js}

因为某些原因，有网站 cookie 设置了httponly，导致js无法获取

目前想法：

cookie.js

```
var cookieJSON = JSON.stringify({cookie:headers.cookie});
values['tmp.js'] = `document.write(${cookieJSON})`;

```

jsPrepend 似乎读不到 tmp.js ?

**Comment by avwo** [comment]
可以用模板字符串：https://wproxy.org/whistle/data.html

```` txt
``` cookie.js
var allCookies = `${reqH.cookie}`;
alert(allCookies);
```

www.baidu.com jsPrepend://`{cookie.js}`
````
> `cookie.js` 也可以放到 Values 里面
