### ISSUE TITLE
dns-over-https 支持

### ISSUE THREAD

**Issue by xcodebuild** [avwo/whistle#439]
大部分浏览器目前已经支持或者正在支持  DOH（dns-over-https）：https://support.mozilla.org/en-US/kb/firefox-dns-over-https

但是经过代理的流量无法使用浏览器端的 DOH，考虑在 whistle 中支持 DOH

**Comment by avwo** [comment]
目前 node 并不支持这个特性，不影响使用等话，等后续支持再加上。

**Comment by xcodebuild** [comment]
由于 `dns-over-https` 本质上就是个 `https` 请求，所以可能不会在 `nodejs` 层面支持

例如 `curl http://dns.alidns.com/resolve\?name\=www.taobao.com.\&type\=1`

```json
{"Status":0,"TC":false,"RD":true,"RA":true,"AD":false,"CD":false,"Question":{"name":"www.taobao.com.","type":1},"Answer":[{"name":"www.taobao.com.","TTL":31,"type":5,"data":"www.taobao.com.danuoyi.tbcache.com."},{"name":"www.taobao.com.danuoyi.tbcache.com.","TTL":31,"type":1,"data":"101.37.183.171"},{"name":"www.taobao.com.danuoyi.tbcache.com.","TTL":31,"type":1,"data":"101.37.183.170"}]}
```

不过肯定是不影响使用的，只是一个 feature request

**Comment by avwo** [comment]
更新下 Whistle：https://github.com/avwo/whistle/blob/master/CHANGELOG.md#v276
