### ISSUE TITLE
不设置代理，通过直接访问w2主机+代理端口进行代理的尝试

### ISSUE THREAD

**Issue by pzai01** [avwo/whistle#440]
目前的现状：
1.将代理端口和ui端口分开设置，通过代理端口访问w2的主机，还是会进入到webui，这个是出于什么考虑
2.设置pureProxy模式，按照文档所说，会将ui的请求也当普通请求来对待，但是从抓包界面并不能看到这个请求

考虑不配置代理，直接通过w2主机+代理端口+path/query的方式，进入到规则做代理
例如：https://192.168.39.100:8899?url=www.abc.com  ==>   www.abc.com
这样可以省去电脑或者手机的代理的配置工作

**Comment by avwo** [comment]
这种其实会增加用户的使用成本，有些app的webview或页面里面的请求url不好修改

**Comment by pzai01** [comment]
> 这种其实会增加用户的使用成本，有些app的webview或页面里面的请求url不好修改

1. 这种成本我理解可以通过技术手段屏蔽掉，但是各种代理的配置这个手工操作没办法很好的屏蔽掉（当然对于浏览器来说，可以有一些插件来完成）
以两个场景为例：
- 针对h5页面，比如pc端将这个拼接好的url，生成二维码，使用手机扫码直接进入页面，这样手机其实感觉不到代理的存在，但是实际上代理是发挥了作用，尤其是对于那种很多体验用户还是比较便捷；
- 对于webview的情况，往往这个webview的src，我们是可以控制的，比如针对调试/测试环境，我们可以对这个webview的src进行一些特殊拼接工作

2.能够针对性的对请求进行代理/抓包，减少代理服务器的负荷
3.比较灵活，通过url+固定规则就可以实现一些快捷的代理工作

实现上面我简单的看了下w2的入口代码，考虑能否通过一个白名单路径来区分webui和代理，比如https://192.168.39.100:8899/proxy ,只要是proxy路径的，都认为是直接代理，而不认为是webui内部路径（ps：我是使用whitsle搭建的内部的公共代理调试服务器）

**Comment by avwo** [comment]
支持通过 `-` 区分 webui 和代理：https://192.168.39.100:8899/-/xxx
结合 whistle 的模板字符串功能可以实现上述功能：https://wproxy.org/whistle/data.html

**Comment by pzai01** [comment]
> 支持通过 `-` 区分 webui 和代理：https://192.168.39.100:8899/-/xxx
> 结合 whistle 的模板字符串功能可以实现上述功能：https://wproxy.org/whistle/data.html

这个尝试过，但是发现这样的访问，会直接302又回到webui界面了

**Comment by avwo** [comment]
配个规则，类似：`192.168.39.100:8899/ https://www.baidu.com`

**Comment by pzai01** [comment]
> 配个规则，类似：`192.168.39.100:8899/ https://www.baidu.com`

👍可以了，之前302是规则配置的不对，之前是这么配置的：`192.168.39.100:8899/-/abc https://www.baidu.com`，

另外反馈一个现象：手机通过pac脚本最后路由到代理里面来，抓包的时候，https的内容显示TUNNEL CONNECTs，https证书是装过的

**Comment by avwo** [comment]
看下文档，要开启拦截
