### ISSUE TITLE
复制粘贴不能正确选中规则

### ISSUE THREAD

**Issue by yy249357** [avwo/whistle#441]
使用的是mac系统, chrome浏览器，在rules窗口编辑规则时, 光标经常发生闪动，难以正常选中文本，且多行文本不能正确的复制粘贴。

**Comment by avwo** [comment]
chrome什么版本？

**Comment by yy249357** [comment]
> chrome什么版本？

版本 83.0.4103.116（正式版本） （64 位）

**Comment by avwo** [comment]
![image](https://user-images.githubusercontent.com/11450939/86251679-c3cab200-bbe4-11ea-8f94-22c5fde6abd5.png)
我这边没你你说的这种问题，重新安装whistle，并重启看看

**Comment by yy249357** [comment]
@avwo 今天找到了原因，通过样式观察那些选中的行都是position: relative;  选中时div会发生闪动。  结果发现是chrome上面装的别的插件导致的，把插件tampermonkey油猴关掉后就正常了。
