### ISSUE TITLE
whistle 突然没有了同步本地host的配置项？

### ISSUE THREAD

**Issue by lizy0329** [avwo/whistle#445]
Version: 2.5.11
System Version: Win 10
Question: 同步配置消失了！
Expect: 同步配置出现

![企业微信截图_20200702103523.png](https://i.loli.net/2020/07/02/drqHGjxLNQpOPnf.png)

**Comment by avwo** [comment]
去掉了，两者同时使用容易产生问题

**Comment by lizy0329** [comment]
> 去掉了，两者同时使用容易产生问题

那意味着我修改更改本地 host 需要额外安装 SwitchHosts 了？

**Comment by avwo** [comment]
直接在 whistle 上配置hosts就可以

**Comment by lizy0329** [comment]
> 直接在 whistle 上配置hosts就可以

现在我是通过 SwitchyOmega -> whistle 来代理的。
但总有些场景需要用 系统级别的 hosts 来代理，例如一些桌面应用需要使用代理时，就无法使用 whistle

在之前，通过勾选浏览器中 whistle 的“同步本地hosts”就可以达到目的。

**Comment by avwo** [comment]
桌面应用可以用 proxifier 代理到 whistle

**Comment by lizy0329** [comment]
> 桌面应用可以用 proxifier 代理到 whistle

也是个方法~也就是说 同步本地 host 这个功能不会再有了？还是计划以全新面貌上线？
