### ISSUE TITLE
已经信任了证书 但是却说 net::ERR_CERT_AUTHORITY_INVALID

### ISSUE THREAD

**Issue by lumixraku** [avwo/whistle#449]
已经信任了证书 但是却说 net::ERR_CERT_AUTHORITY_INVALID。

是因为证书的时间太长的缘故吗？  我看证书有效期是 10 年。

**Comment by lumixraku** [comment]
emmm 即使把证书有效期设置为1年还是如此
![image](https://user-images.githubusercontent.com/6280941/86578485-749ecb80-bfae-11ea-95f0-70fb9596187c.png)


![image](https://user-images.githubusercontent.com/6280941/86578520-82ece780-bfae-11ea-90ef-21b3d3f5b141.png)

**Comment by avwo** [comment]
127.0.0.1 请求不走代理，可以通过下面的方式，改用域名访问：
``` txt
www.xxx.com https://127.0.0.1:3000
```
