### ISSUE TITLE
resWrite 抓取的图片本地无法打开

### ISSUE THREAD

**Issue by dofy** [avwo/whistle#451]
规则：

```
^*.douban*.com/*** resWrite:///Users/USERNAME/whistle/write/douban/$2/$1/$3
```

Web Debuger 中可以看到图片请求状态码为 200，且可以预览

![请求状态](https://user-images.githubusercontent.com/344197/87404853-42feb380-c5f1-11ea-94c4-0b7a3d01f6b9.png)

![Web Debuger 文件预览](https://user-images.githubusercontent.com/344197/87404908-5ad63780-c5f1-11ea-9faa-0ccf41e87a2c.png)

但实际抓取文件无法打开或预览

![本地抓取文件](https://user-images.githubusercontent.com/344197/87405157-a1c42d00-c5f1-11ea-89a3-798ce1ecc680.png)

**Comment by avwo** [comment]
更新下 whistle
