### ISSUE TITLE
log插件打印的内容时序不能保证，建议增加显示毫秒时间

### ISSUE THREAD

**Issue by latel** [avwo/whistle#452]
![image](https://user-images.githubusercontent.com/5621862/87521173-9981f580-c6b6-11ea-8e72-2e345fa4a192.png)

![image](https://user-images.githubusercontent.com/5621862/87521209-a56db780-c6b6-11ea-9d01-74edfc67dbc6.png)

**Comment by avwo** [comment]
更新下 whistle
