### ISSUE TITLE
replaceStatus和statusCode有什么区别？

### ISSUE THREAD

**Issue by lancelodliu** [avwo/whistle#453]
看到文档http://wproxy.org/whistle/rules/replaceStatus.html 中提到了这2者的区别，但不是特别理解“请求响应后再修改状态码”。

在本地调试React项目localhost:3000的api时，代理是通过`http-proxy-middleware`配置到w2的。如果w2对应的url rule配置`replaceStatus://200`，就会无限循环接收到localhost:3000发来的相同请求，而配置成`statusCode://200`就没有问题。故有此疑问，谢谢。

**Comment by avwo** [comment]
`replaceStatus` 是替换后台响应的状态码，`statusCode` 是直接响应指定的状态码（请求不会到后台）
