### ISSUE TITLE
https流量代理到本地

### ISSUE THREAD

**Issue by yuwanlin** [avwo/whistle#454]
**场景：**
我的电脑浏览器装了https的证书，并且我的手机也安装了whistle证书。同一局域网下，手机wifi代理地址设为电脑ip，电脑上whistle页面可以抓到https的请求。

这时候，我本地开启了一个8080端口的服务器。我想将https的请求转发到我本地的http://127.0.0.1:8080。这个通过whistle应该如何配置。

**尝试：**
我尝试了 `care.test.seewo.com proxy://127.0.0.1:8080` ，它这一将http流量代理到本地8080，但是对于https的流量，显示 `socket could not be established. cause-socket hang up`

想知道可以通过whistle配置达到我的需求吗？

**Comment by avwo** [comment]
care.test.seewo.com http://127.0.0.1:8080

**Comment by yuwanlin** [comment]
> care.test.seewo.com http://127.0.0.1:8080

原来这么简单就可以。 后者直接使用http/https 和proxy: / https-proxy 有什么区别吗？因为在我的场景中proxy: 不行，而直接使用http:// 就可以

**Comment by avwo** [comment]
> > care.test.seewo.com http://127.0.0.1:8080
> 
> 原来这么简单就可以。 后者直接使用http/https 和proxy: / https-proxy 有什么区别吗？因为在我的场景中proxy: 不行，而直接使用http:// 就可以

请求代理服务器才用 `proxy://host:port`
