### ISSUE TITLE
Centos 7 启动w2 一定时间后，代理无法访问。 

### ISSUE THREAD

**Issue by pacez** [avwo/whistle#457]
在Centos 7 下启动W2 过段时间后， 代理无法访问。 w2 status没有显示任何问题。 w2 restart后，立即可用。
必现问题， 隔段时间我都需要重启一次，已更新最新版。

**Comment by avwo** [comment]
看下启动的当前目录有没有 whistle.log 这个文件。

**Comment by pacez** [comment]
没有这个log文件，我也看了文档，也想找该文件。 在运行w2 start的目录下， 但并没有发现whistle.log文件。

**Comment by pacez** [comment]
> 看下启动的当前目录有没有 whistle.log 这个文件。

没有这个log文件，我看了你写的官方文档，也想找该文件。 但是在运行w2 start的目录下， 但并没有发现whistle.log文件。
是我查找方式不对吗？ 我理解这个文件是生成在我运行w2 start命令所在的目录下。

**Comment by pacez** [comment]
最后根据作者提示，升级nodejs 到 v12后修复此问题。
