### ISSUE TITLE
whistle IOS 设置代理之后下载不了 HTTPS 证书

### ISSUE THREAD

**Issue by GpingFeng** [avwo/whistle#459]
根据提示 [官方提示](http://wproxy.org/whistle/webui/online.html) 设置了代理，打开手机 Safari，提示 “Safari 浏览器打不开网页，因为服务器已停止响应”

![image](https://user-images.githubusercontent.com/20135760/89119487-68405c80-d4e1-11ea-9974-cf95ebbc02c2.png)

同时按照官方提示，已经把 HTTPS 拦截功能去掉了

![image](https://user-images.githubusercontent.com/20135760/89119433-231c2a80-d4e1-11ea-8b04-3b2af9ffbc4b.png)

![image](https://user-images.githubusercontent.com/20135760/89119439-316a4680-d4e1-11ea-993f-047e3d7d8937.png)

根据issue中其他答案，防火墙关闭了还是不行，设置了其他端口 8888 或者 8080 也不行

手机版本：IOS 13.5.1

mac: 10.15.5

whistle 2.5.14

**Comment by avwo** [comment]
电脑和手机是不是在同一网络，或者网络有没有访问限制

**Comment by GpingFeng** [comment]
@avwo 电脑和手机是在同一网络。很有可能是网络问题，我在公司可以安装成功，家里的网络不行，这种情况可以通过什么方法排查

**Comment by avwo** [comment]
不设置代理的时候试下能不能直接通过ip访问，启动命令行参数有提醒。
