### ISSUE TITLE
Mac terminal  curl / wget / node 无法代理

### ISSUE THREAD

**Issue by xinshangshangxin** [avwo/whistle#46]
浏览器中设置了系统代理之后, 可以代理
但是当使用curl / wget 或者 node中使用request, 则无法代理

使用 proxifier全局代理之后, nodejs 陷入死循环

请问有什么好的解决方案吗?

**Comment by avwo** [comment]
试试这个
https://zm10.sm-tc.cn/?src=l4uLj8XQ0IiIiNGeloqHlp6R0ZyQktCejYuWnJOa0I%2FSzcfLy8vKydGXi5KT&uid=a2e611ebc1cc7336dcb0b3adae5c987a&hid=bb6c854ab810f85587f4c60078884180&pos=8&cid=9&time=1497240345012&from=click&restype=1&pagetype=0200000000000400&bu=structure_web_kv&query=curl%E8%AE%BE%E7%BD%AE%E4%BB%A3%E7%90%86&mode=&v=1&uc_param_str=dnntnwvepffrgibijbprsvdsdichei

**Comment by xinshangshangxin** [comment]
node中使用request的呢?

**Comment by avwo** [comment]
const r = request.defaults({ proxy: 'http://127.0.0.1:8899' });

https://github.com/request/request#streaming

**Comment by avwo** [comment]
也可以参考这里面的实现 https://github.com/avwo/koa-whistle

**Comment by xinshangshangxin** [comment]
不合理啊, 难道我还要区分正式环境 和 测试环境, 来修改代码?
如果是系统级别的host, 是不需要的

**Comment by avwo** [comment]
操作系统设置的系统代理是指浏览器代理，app内部的请求要做指定代理需要自己用代码实现，一般是加个配置界面让用户自己填写；用proxifier全局代理到同台机器的whistle不可取，会造成whistle发出的请求又被proxifier代理回来，造成死循环。

**Comment by xinshangshangxin** [comment]
那样的话感觉有点绕了, 原来只要开启proxifier 就可以代理全部了
现在还需要配置, 有点麻烦了

另外, 系统host配合nginx 也是可以达到效果, 虽然有点麻烦, 但是不需要修改原有实现

**Comment by avwo** [comment]
whistle和proxifier不要在同一台机器运行就可以

**Comment by xinshangshangxin** [comment]
好吧, 最后还是 搭配 nginx + host

利用host 决定哪个域名需要转发到本地, 然后nginx 配置`default_server` 转发到 `127.0.0.1:8899`
最后利用 whistle 来决定 真正的转发

感觉太绕了....
