### ISSUE TITLE
官网的例子没看明白，pathReplace要怎么用？

### ISSUE THREAD

**Issue by B1anker** [avwo/whistle#460]
设置values
![image](https://user-images.githubusercontent.com/17514962/89261831-5259a580-d661-11ea-8b0f-abb559f89843.png)
设置规则
![image](https://user-images.githubusercontent.com/17514962/89261990-8fbe3300-d661-11ea-94cd-b38ab6bdb929.png)
然后访问，并没有什么用
![image](https://user-images.githubusercontent.com/17514962/89262074-b5e3d300-d661-11ea-8bad-717cdb751357.png)

**Comment by avwo** [comment]
`pathReplace://{test}` 取 `Values` 的值要用 `{key}`，`Values` 的值也可以内嵌到 `Rules` 里面：
```` txt
``` test
...aaa
...bbb
```
pattern protocol://{test}
````

**Comment by B1anker** [comment]
> `pathReplace://{test}` 取 `Values` 的值要用 `{key}`，`Values` 的值也可以内嵌到 `Rules` 里面：
> 
> ```
> ``` test
> ...aaa
> ...bbb
> ```
> pattern protocol://{test}
> ```

可以了，要用{}包起来，感谢 @avwo
