### ISSUE TITLE
【electron】node: bad option: --tls-min-v1.0

### ISSUE THREAD

**Issue by yeehone** [avwo/whistle#461]
## 问题描述：
参照 https://github.com/nohosts/client 使用 electron 构建客户端。
构建成功运行客户端过程中发现插件 rulesServer 执行逻辑不符合预期，没有进入对应的server 逻辑。同样的插件在本地 nodejs 环境下运行ok。

## 问题定位：
通过调试发现，https://github.com/avwo/whistle/blob/master/lib/plugins/index.js#L396
loadPlugin 时 p.fork 回调 err 为 `node: bad option: --tls-min-v1.0`
https://github.com/avwo/pfork/blob/master/lib/index.js#L88
尝试修改不添加 `--tls-min-v1.0`，运行成功。

目测和这个 issue 相关：https://github.com/electron/electron/issues/21511

附：
electron 版本：`v7.3.2`
whistle 版本：`v2.5.14`

**Comment by xcodebuild** [comment]
`--tls-min-v1.0` 是 `node` 的参数，不是 `electron` 的，要在 `electron` 中使用需要用 `ELECTRON_RUN_AS_NODE=1` 指定以 node 模式运行

https://github.com/alibaba/lightproxy/blob/6734da9d41eb327ceaff5f86c1568a864d93652e/src/main/api.ts#L57-L69

**Comment by yeehone** [comment]
了解是 `node` 的参数。

我这里的背景是参考了 https://github.com/nohosts/client 项目代码，简单的在 electron 里 [startWhistle](https://github.com/nohosts/client/blob/master/app/lib/index.js#L73-L78)，然后借助 whistle 插件连接 nohost 服务。

https://github.com/alibaba/lightproxy/blob/6734da9d41eb327ceaff5f86c1568a864d93652e/src/main/api.ts#L57-L69
这个参考是自己 spawn 的时候，我这是 whistle 去 spawn的。。ps. 这里代码有 typo... spawn 打错了

或许应该改一下 https://github.com/nohosts/client 的例子代码。。不然不熟悉 `electron` 和 `whistle` 得翻源码来查问题

最后采用这样的方式处理了：
```js
// for plugin process fork in electron
process.env.ELECTRON_RUN_AS_NODE = 1;
process.env.PFORK_EXEC_PATH = process.execPath;

startWhistle({
  port,
  // mode: 'pureProxy|multiEnv',
  storage: 'nohost-client',
  pluginPaths: [path.join(__dirname, '../node_modules')],
}, resolve);
```
