### ISSUE TITLE
Error: Client network socket disconnected before secure TLS connection was established

### ISSUE THREAD

**Issue by broven** [avwo/whistle#462]
今天使用whistle代理内网的域名时, 发现都挂了, 报错如下
```
<pre>
From: whistle@2.5.11
Node: v10.16.3
Date: 8/5/2020, 11:11:44 AM
Error: Client network socket disconnected before secure TLS connection was established
    at TLSSocket.onConnectEnd (_tls_wrap.js:1095:19)
    at Object.onceWrapper (events.js:286:20)
    at TLSSocket.emit (events.js:203:15)
    at endReadableNT (_stream_readable.js:1145:12)
    at process._tickCallback (internal/process/next_tick.js:63:19)


<a href="javascript:;" onclick="location.reload()">Reload this page</a>
</pre>
```
由于是内网域名, 抱歉没有写例子

不过找到一个相似的issue, 不知道是不是这个问题
https://github.com/googleapis/nodejs-bigquery/issues/624#issuecomment-605621594

**Comment by avwo** [comment]
node升到12看看

**Comment by broven** [comment]
应该不是whistle的问题, 那个域名 node相关应用https都走不通, 已经交给那个应用的同学排查了.

**Comment by avwo** [comment]
ref: https://github.com/nodejs/node/issues/34719

**Comment by avwo** [comment]
重新安装whistle，并重启看看

**Comment by li-xianfeng** [comment]
@avwo  @broven 请问此问题有确切的解决方案吗，今天遇到相同的报错，打开whistle不设置任何代理规则，访问接口出现这个报错，关闭whistle则请求正常；

错误信息如下：

From: whistle@2.5.12
Node: v12.14.1
Date: 8/17/2020, 7:09:26 PM
Error: Client network socket disconnected before secure TLS connection was established
    at connResetException (internal/errors.js:570:14)
    at TLSSocket.onConnectEnd (_tls_wrap.js:1361:19)
    at Object.onceWrapper (events.js:312:28)
    at TLSSocket.emit (events.js:228:7)
    at endReadableNT (_stream_readable.js:1185:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:21)

**Comment by avwo** [comment]
更新下whistle

**Comment by li-xianfeng** [comment]
> 更新下whistle

感谢，升级whistle到v2.5.16解决了；
开始使用的是lightproxy，升级lightproxy后问题还在，应该是lightproxy内部还没升级whistle;

**Comment by xcodebuild** [comment]
lightproxy 的 `beta` 版本也已经更新了，近今天会 release 最新版

**Comment by xcodebuild** [comment]
@li-xianfeng lightproxy 也已经升级 `whistle` 到 `2.5.17`，对应的 `lightproxy` 版本为 `1.1.33`，更新到最新版解决

**Comment by missMHWGO** [comment]
node 12.16.1
whistle 2.5.21
依然报这个错。。。请问有什么解决方法吗？

**Comment by dennisleung** [comment]
升级后如果还是复现的话可以检查下域名的A记录配置

**Comment by avwo** [comment]
更新下 Whistle 试试
