### ISSUE TITLE
如何转发一个不能访问的资源

### ISSUE THREAD

**Issue by jasonwong331** [avwo/whistle#463]
例如我没科学上网的情况 https://www.google.com/recaptcha/api.js 这个js资源是请求不到
我想把这个请求不到的资源指向到本地资源获取，是否能做到吗？

**Comment by avwo** [comment]
https://github.com/avwo/whistle/blob/master/docs/zh/rules/rule/file.md

**Comment by jasonwong331** [comment]
> https://github.com/avwo/whistle/blob/master/docs/zh/rules/rule/file.md

不行呢，用Chrome访问不到，用狐火只能http的情况下能访问，https不能访问

**Comment by avwo** [comment]
https://github.com/avwo/whistle/blob/master/docs/zh/webui/https.md

**Comment by jasonwong331** [comment]
> https://github.com/avwo/whistle/blob/master/docs/zh/webui/https.md

可以了谢谢，原来是我没开拦截https功能
