### ISSUE TITLE
导出全部 Values 时会自动添加一项叫 Export All Values 的 Value

### ISSUE THREAD

**Issue by dofy** [avwo/whistle#464]
Chrome 84.0.4147.105
macOS 11.0 Beta版（20A5343i）
whistle 2.5.14

导出前：
![导出前](https://user-images.githubusercontent.com/344197/89497523-148a8780-d7ef-11ea-88ee-ab1334f6edc7.png)

导出后：
![导出后](https://user-images.githubusercontent.com/344197/89497545-21a77680-d7ef-11ea-837e-88399c09f65b.png)

导出内容：
```json
{
  "prodigyWritePath": "/Users/seven/Works/prodigy/whistle/write-v3",
  "Export All Values": ""
}
```

**Comment by avwo** [comment]
下个版本修复

**Comment by avwo** [comment]
重新安装下 whistle，并重启
