### ISSUE TITLE
url匹配问题

### ISSUE THREAD

**Issue by jasonwong331** [avwo/whistle#465]
https://www.aaaaa.com/bbb/*?v=1  js:///xxxxx.js
*号那里是想匹配任何字符串，我用*号发现不可以，怎么才能匹配呢

**Comment by avwo** [comment]
^https://www.aaaaa.com/bbb/**?v=1
https://github.com/avwo/whistle/tree/master/docs/zh

**Comment by jasonwong331** [comment]
可以了，感谢
