### ISSUE TITLE
pureProxy模式疑问

### ISSUE THREAD

**Issue by jasonwong331** [avwo/whistle#466]
设置了pureProxy模式，不设置代理，通过代理服务器访问普通网站
例如：192.168.1.1:8899/-/ https:www.baidu.com
但发现network面板捉取不到百度相关的https的信息，是不是需要在这台代理服务器上也要安装whistle根证书？

**Comment by avwo** [comment]
不要开启 拦截https

**Comment by jasonwong331** [comment]
> 不要开启 拦截https

不要开启Capture TUNNEL CONNECTs ？ 不是拦截https需要勾选吗，我试了不勾选也不可以

**Comment by avwo** [comment]
你要实现什么功能

**Comment by jasonwong331** [comment]
> 你要实现什么功能

我看到一个issues尝试不设置代理，直接通过服务器转发代理。这样能是实现对客户端来说体验会提高很多
例如通过开启pureProxy模式，客户端不设置代理直接访问代理服务器192.168.1.1:8899/-/ ，通过规则转向到目标域名，但需要拦截https的一些请求

**Comment by avwo** [comment]
这种可以不用装证书，用http请求https即可，也不用purePoxy模式

**Comment by jasonwong331** [comment]
> 这种可以不用装证书，用http请求https即可，也不用purePoxy模式

1.客户端没设置代理，我规则这样设置：
192.168.1.1:8899/-/abc https:www.baidu.com
页面返回302 ，显示Cannot GET /abc
2.成功跳转到目标域名后，需要拦截https做一些预处理
这两点能做吗，大神能否给个思路，感谢！

**Comment by avwo** [comment]
试试
``` txt
192.168.1.1:8899/ https://`(${url.path.replace(/)})`
```

http://192.168.1.1:8899/-/www.baidu.com

![image](https://user-images.githubusercontent.com/11450939/89747889-5b2ff880-daf3-11ea-9c59-ed95bd311453.png)

**Comment by jasonwong331** [comment]
> 192.168.1.1:8899/ https://`(${url.path.replace(/)})`

这样可以，但为什么在network面板拦截不到baidu相关的请求呢？
![1597166350653](https://user-images.githubusercontent.com/46738798/89928081-e0252a00-dc39-11ea-82fe-44871a9ffcfa.jpg)

**Comment by avwo** [comment]
要在Overview里面的 Real Url才能看到

**Comment by jasonwong331** [comment]
> 要在Overview里面的 Real Url才能看到

你所讲的是设置 X-Real-Id 吗？
