### ISSUE TITLE
非同域下的Http2资源不加载

### ISSUE THREAD

**Issue by xluos** [avwo/whistle#467]
连接代理后有些浏览器不加载非同域下的https2的资源，原因未知。连接代理时使用chrome浏览正常，QQ浏览器，safari，小米自带浏览器均会出现资源资源不加载的问题。
下图中dll这个js加载正常，其他几个在static域名下的资源不会加载。如果单独访问资源地址又是可以拿到内容的，w2的network面板也能看到
![image](https://user-images.githubusercontent.com/23625189/89860350-d669db00-dbd5-11ea-9c83-598401202dbb.png)

**Comment by avwo** [comment]
根证书安装了吗

**Comment by xluos** [comment]
安装了，可以看到页面和dll这个js的内容都可以看到。其他资源连请求都没有

**Comment by xluos** [comment]
解决了应该还是安卓7+的问题，虽然页面的请求可以看到单其他几个h2的资源还是加载不出来的，也没有弹提示什么的。
root后把证书放到系统目录下就正常了
