### ISSUE TITLE
请问有快速切换环境的方式吗?

### ISSUE THREAD

**Issue by yy249357** [avwo/whistle#468]
平时开发时要写多套规则, 如: 
正式环境:   https://www.test.com/  http://localhost:8080/
                   https://www.test.com/api/xxx  http://localhost:8080/api/$1
preview环境:  https://www.preview.test.com/  http://localhost:8080/
                        https://www.preview.test.com/api/xxx  http://localhost:8080/api/$1
staging环境:  https://www.staging.test.com/  http://localhost:8080/
           https://www.staging.test.com/api/xxxx  http://localhost:8080/api/$1
当规则过多时，就会不方便,  能否统一写成类似变量的那种规则呢?
${env}  http://localhost:8080/
${env}/api/xxx  http://localhost:8080/$1

这里env是环境变量, 每次只需要替换就行,  env = https://www.test.com/ 或 https://www.preview.test.com/ 或 https://www.staging.test.com/

**Comment by avwo** [comment]
可以用插件实现，类似：
``` txt
**.test.com whistle.xxxenv://pre
```
参考：https://github.com/whistle-plugins/whistle.autopac

**Comment by yy249357** [comment]
老师, 不会用whistle.autopac怎么办。
<img width="216" alt="Jietu20200811-223550" src="https://user-images.githubusercontent.com/15326742/89910606-068b9b00-dc23-11ea-94fe-1bad96e0b413.png">

今天晚上用通配符间接的解决了配置规则多的问题。
