### ISSUE TITLE
请教一下如何实现cookiePathRewrite的效果

### ISSUE THREAD

**Issue by linzhongxian** [avwo/whistle#469]
例如www.a.com/a转发到www.a.com/b，/b的后台返回的cookie的path是/b，我想把这个path改成/a，大概要怎样写呢

**Comment by avwo** [comment]
https://wproxy.org/whistle/rules/headerReplace.html

**Comment by linzhongxian** [comment]
> https://wproxy.org/whistle/rules/headerReplace.html

原来用headerReplace就可以了，我还一直纠结在resScript和resCookies，感谢

**Comment by linzhongxian** [comment]
发现headerReplace的pattern如果有=号会被qs错误地解析
例如 `headerReplace://res.set-cookie:/\bpath=[^;]%2b(;|\s*$)/=path=/b` 在 parseQuery 方法中会被解析成
`{ '/\bpath' : '[^;]+(;|\s*$)/=path=/b' }` 导致匹配不上

**Comment by avwo** [comment]
````txt
``` replaceCookies
/\bpath=[^;]%2b(;|\s*$)/: path=/b
```
pattern headerReplace://{replaceCookies}
````

**Comment by linzhongxian** [comment]
> ```
> ``` replaceCookies
> /\bpath=[^;]%2b(;|\s*$)/: path=/b
> ```
> pattern headerReplace://{replaceCookies}
> ```

这个好像也不起作用，我看到 resolveHeaderReplacement 方法拿的是 matcher 的值，就是 `headerReplace://{replaceCookies}`

**Comment by avwo** [comment]
上面我搞错了，encodeURIComponent('=') 试试，也可以 key 和 value 同时  encodeURIComponent：
``` txt
headerReplace://res.set-cookie:/\bpath%3D[^;]%2b(;|\s*$)/=path=/b
```

**Comment by linzhongxian** [comment]
> 上面我搞错了，encodeURIComponent('=') 试试，也可以 key 和 value 同时 encodeURIComponent：
> 
> ```
> headerReplace://res.set-cookie:/\bpath%3D[^;]%2b(;|\s*$)/=path=/b
> ```

这个可以了，感谢
