### ISSUE TITLE
使用 whistle 代理 cloudflare 资源时，提示证书过期

### ISSUE THREAD

**Issue by jinwei233** [avwo/whistle#47]
https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.1/MathJax.js?config=TeX-AMS-MML_SVG

![image](https://user-images.githubusercontent.com/243645/27164629-1948d4aa-51c1-11e7-8e08-f407593b608d.png)

**Comment by avwo** [comment]
该域名 `cdnjs.cloudflare.com` 的证书被吊销了，只支持 `*.cloudflare.com` 泛域名的证书， 先用规则
```
cdnjs.cloudflare.com disable://intercept
```
 把这个域名请求的https拦截禁用掉，等后续版本再解决这类问题

**Comment by avwo** [comment]
[更新下whistle](https://avwo.github.io/whistle/update.html)
