### ISSUE TITLE
插件rulesServer内如何获取pattern

### ISSUE THREAD

**Issue by sunzongzheng** [avwo/whistle#473]
我现在想实现这样的插件：
用法：`test.com static-forward://http://127.0.0.1:8082`
插件功能：满足某个条件时，直连，否则转发到`http://127.0.0.1:8082`
````js
exports.rulesServer = (server, options) => {
    server.on('request', (req, res) => {
        const oReq = req.originalReq;

        if (oReq.headers['sec-fetch-dest'] === 'empty') {
            res.end();
        } else {
            // 转发到http://127.0.0.1:8082
            // 这里怎么写？
            // 我能想到的是res.end(`${oReq.pattern} ${oReq.ruleValue}`); 
            // 可是看文档以及打印req发现无法获取到pattern
        }
    })
}
````

**Comment by avwo** [comment]
可以通过 `oReq.relativeUrl` 获取去除 `pattern` 的相对路径。

你这个不需要插件，可以用 [filter](https://wproxy.org/whistle/rules/filter.html)：
``` txt
test.com http://127.0.0.1:8082 excludeFilter://reqH.sec-fetch-dest=empty
```

**Comment by sunzongzheng** [comment]
是这样吗：
````js
res.end(`${oReq.relativeUrl} ${oReq.ruleValue}`)
````

假如我的原始规则是：`test.com static-forward://http://127.0.0.1:8082`
我访问的地址是：`test.com/a`
拿到的relativeUrl就是：`/a`
此时如果按照上面来写返回的就是：`/a http://127.0.0.1:8082`
我测试此时似乎没有按照预期把`test.com/a`打到`http://127.0.0.1:8082/a`上


`test.com http://127.0.0.1:8082 excludeFilter://reqH:sec-fetch-dest=empty`这个确实可用，我还是想做成插件的形式，感觉给别人使用的成本会低一些，也利于后续维护 :relaxed:

**Comment by avwo** [comment]
自己做拼接，pattern可以写成 * 或者 用fullUrl减去relativeUrl作为pattern

**Comment by sunzongzheng** [comment]
了解了，感谢~
