### ISSUE TITLE
建议在composer界面的history中加上包重命名的功能

### ISSUE THREAD

**Issue by WinChua** [avwo/whistle#474]
![image](https://user-images.githubusercontent.com/11592887/90854498-ad083680-e3af-11ea-8b1c-a7b689fe6523.png)
个人觉得加上包重命名的话，能够快速定位到历史的包。
或者有没有已有的类似功能？

**Comment by avwo** [comment]
把请求body显示出来了，看下能否满足需求
![image](https://user-images.githubusercontent.com/11450939/91852564-9b6a3d00-ec93-11ea-86cc-8c351ff5060e.png)
