### ISSUE TITLE
whistle插件内部无法进行网络请求

### ISSUE THREAD

**Issue by jayjliang** [avwo/whistle#482]
版本：whistle@2.5.4
表现：
From: whistle@2.5.4
Node: v11.0.0
Date: 2020-9-7 21:35:29
Error: connect ECONNREFUSED 127.0.0.1:40501
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1117:14)
问题：在开发一个whistle插件，插件内部会进行额外的http请求，这里使用request库请求，发现没有任何反应，whistle返回如上
单独写一个文件去用node执行是可以的，请问这里有文档可以说明这个问题或者如何解决～

**Comment by avwo** [comment]
不要用node11

**Comment by jayjliang** [comment]
你好，切换至12版本的node错误仍然是一样的
From: whistle@2.5.21
Node: v12.18.3
Date: 2020-9-8 9:35:35 ├F10: AM┤
Error: connect ECONNREFUSED 127.0.0.1:40501
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)
不知道是不是因为在公司内部导致的，whistle内请求会读取一些代理之类的吗

**Comment by avwo** [comment]
tx？是不是用了免代理模式，需要改成默认pac模式。

**Comment by jayjliang** [comment]
不是，在ali
直接用node test.js的方式是可以的，但是在whistle内部就不行
不知道whistle有没有什么配置项

**Comment by avwo** [comment]
`127.0.0.1:40501` 这个是你自己起的本地服务吗

**Comment by jayjliang** [comment]
不是，找到原因了，是因为网络请求代码有报错
request(requestUrl, (err, _res, body) => {
        if (err || _res.statusCode !== 200) {
          console.log('err', err);
          abort();
          return;
        }
        response(req, res, '200', result.join(''));
})
client.on('error', abort);
这里的client不存在导致的，只是这个报错比较迷惑，应该是whistle捕获了错误但是没有打印出来吧
抱歉打扰了
