### ISSUE TITLE
WebSocket 抓包 opcode=4 时显示 no handler for opcode 4 且不显示每个 message

### ISSUE THREAD

**Issue by vikyd** [avwo/whistle#483]
环境：

- Mac：10.15.4
- Whistle：2.5.21
- Node：v12.13.1
- VSCode：1.48.2

Whistle 抓包结果 ↓：

![image](https://user-images.githubusercontent.com/2208880/92446134-f21dcc80-f1e7-11ea-9feb-4d34c814f8fc.png)

Wireshark 同时抓包的结果表明此 WebSocket 是在有效持续进行中的 ↓：

![image](https://user-images.githubusercontent.com/2208880/92446317-3c9f4900-f1e8-11ea-8e8d-354c10d8e464.png)

根据 [The WebSocket Protocol](https://tools.ietf.org/html/rfc6455#section-5.2) 规范，`opcode=4` 是自定义帧数据类型，估计 Whistle 未知这些 message 的解码方式所以无法显示？

建议：即使无法解码私有协议 `opcode=4` 的 message 信息，但若不影响区分每个 message，建议增加显示 WebSocket 每个 message 的功能（不管能否正确解码）

**Comment by avwo** [comment]
`opcode = 3~7` 为保留（自定义）帧，理论上帧结构也可以自定义，无法统一处理
