### ISSUE TITLE
Enable HTTP/2 无法开启

### ISSUE THREAD

**Issue by hqqxxf** [avwo/whistle#484]
提示node版本过低，但是我电脑上的node版本是12.18.3，已经是最新版本了

**Comment by avwo** [comment]
更新whistle

**Comment by hqqxxf** [comment]
如果我的node版本是10.16.3，应该怎么办

**Comment by hqqxxf** [comment]
> 更新whistle

如果我的node版本是10.16.3，应该怎么办

**Comment by avwo** [comment]
低版本Node有bug，不支持
