### ISSUE TITLE
response是否可以增加一键展开及收起的功能

### ISSUE THREAD

**Issue by TANCANJIE** [avwo/whistle#485]
类似于chrome devtool查看网络请求，在请求右键有个expand recursivly及collapse children
![企业微信截图_20200914160956](https://user-images.githubusercontent.com/35122233/93060535-de211180-f6a4-11ea-9c51-4c830df64ba0.png)

**Comment by avwo** [comment]
`expand recursivly` 可以直接查看格式后的文本：
![image](https://user-images.githubusercontent.com/11450939/94409943-63c6b600-01a9-11eb-8801-509d341d7687.png)
![image](https://user-images.githubusercontent.com/11450939/94409955-69bc9700-01a9-11eb-8b01-9c73515ae4d9.png)

**Comment by avwo** [comment]
右键菜单增加 `Collapse Parent` 功能，看看能否满足需求：
![image](https://user-images.githubusercontent.com/11450939/97420655-8f72c280-1946-11eb-8e1f-1f3727f792d7.png)
