### ISSUE TITLE
requestBody乱码如何解决

### ISSUE THREAD

**Issue by caoxingwang** [avwo/whistle#489]
mac下运行，requestBody乱码该如何解决
<img width="588" alt="6eadb91df4f00b4f3f7d3d8052647016" src="https://user-images.githubusercontent.com/50133632/93319150-1c076c80-f842-11ea-847f-dae506b53aa0.PNG">

**Comment by avwo** [comment]
默认是文本类型，可以查看二进制 HexView ，或自己对请求内容进行解析及还原：https://github.com/whistle-plugins/examples/tree/master/whistle.test-pipe
