### ISSUE TITLE
不能通过路由器端口映射的方式访问

### ISSUE THREAD

**Issue by hhs66317** [avwo/whistle#491]
- A:  工作机IP：172.17.18.253   
- B:  路由器IP：172.17.19.7【WAN】、192.168.88.1【LAN】
  - C  服务器:  在路由器B网络中，IP：192.168.88.192，whistle 安装在C中，保持默认的8899端口
  - D  测试机：在路由器B网络中，IP：192.168.88.200

在路由器B中进行端口映射，将WAN口的8899映射到192.168.88.192的8899

此时从A直接访问 http://172.17.19.7:8899 无法正常打开WEB UI，界面现实
```
From: whistle@2.5.21
Node: v12.18.4
Date: 9/18/2020, 2:31:46 PM
Error: connect ECONNREFUSED 172.17.19.7:8899
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1141:16)


Reload this page
```
在D中直接访问 http://192.168.88.192 是没问题的，可以正常打开 WEB UI的

**Comment by avwo** [comment]
如果想用域名或非本机IP访问whistle界面，可以用 `w2 restart -l 172.17.19.7` 强制指定下本地 ui 的 host，
