### ISSUE TITLE
插件中部分字段缺失

### ISSUE THREAD

**Issue by leveryd** [avwo/whistle#493]
whistle.autosave插件，保存的请求，偶尔的会有 rawHeaderNames 字段有的时候缺失。

![image](https://user-images.githubusercontent.com/1846319/93847556-ca476200-fcd9-11ea-8d01-a3607c57af2a.png)

预期每个请求的rawHeaderNames应该都存在一个json串

**Comment by avwo** [comment]
http2请求这个为空字符串没问题。

**Comment by leveryd** [comment]
> http2请求这个为空字符串没问题。

如果这里为空，因为req.headers的key都是小写，所以就没有办法知道原始请求头的key值的大小写了吧？

另外截图中的GET请求  https://www.baidu.com/home/msg/data/personalcontent 怎么看出来是http2请求的？

**Comment by avwo** [comment]
Chrome开发者工具的Network看下

**Comment by avwo** [comment]
key值不变。
