### ISSUE TITLE
手机端配置PAC之后，https解析问题

### ISSUE THREAD

**Issue by nsioo** [avwo/whistle#494]
手机直接使用ip+端口方式设置代理，可以解析https，但改为pac方式配置后，https直接走tunnel了。

证书已安装，设置已勾选。

pac配置
function FindProxyForURL(url, host){

  url  = url.toLowerCase();
  host = host.toLowerCase();

  if (
    shExpMatch(url,"*amemv.com/aweme/v*") ||
    shExpMatch(host, "*.amemv.com")
  ){
      return "PROXY xx.xx.xx.xx:8097; ";
  }

  return "DIRECT";

}

**Comment by avwo** [comment]
iOS是OK的，是不是Android机型太老证书版本有问题，换个手机看看。

**Comment by nsioo** [comment]
部分机型存在、设备问题
