### ISSUE TITLE
报错【ERR_INVALID_HTTP_TOKEN】

### ISSUE THREAD

**Issue by hqqxxf** [avwo/whistle#497]
![image](https://user-images.githubusercontent.com/11484241/94361495-3dd8dd00-00e7-11eb-9f92-93cee90a2617.png)
![image](https://user-images.githubusercontent.com/11484241/94361504-492c0880-00e7-11eb-9517-45c0bf13b251.png)

From: whistle@2.5.21 Node: v10.16.3 Date: 2020-9-27 5:35:23 PM TypeError [ERR_INVALID_HTTP_TOKEN]: Header name must be a valid HTTP token ["Time "] at processHeader (_http_outgoing.js:397:5) at ServerResponse._storeHeader (_http_outgoing.js:312:9) at ServerResponse.writeHead (_http_server.js:271:8) at ...
请问这是什么原因？
链接是：http://xxx.com:8014/s?word=xxx

**Comment by hqqxxf** [comment]
@avwo

**Comment by avwo** [comment]
响应头是不是有中文或其它非latin1字符？

**Comment by hqqxxf** [comment]
> 响应头是不是有中文或其它非latin1字符？

没有
![Uploading image.png…]()

**Comment by hqqxxf** [comment]
> 响应头是不是有中文或其它非latin1字符？

并没有

**Comment by avwo** [comment]
![image](https://user-images.githubusercontent.com/11450939/94364844-d75fb900-00fe-11eb-98b9-173a81dbd484.png) key里面有空格。

**Comment by hqqxxf** [comment]
![image](https://user-images.githubusercontent.com/11484241/94390897-a0cd8100-0186-11eb-875c-aaace84db761.png)
没发现空格。不用whistle代理访问链接是没问题的，请问可以修复吗？

**Comment by hqqxxf** [comment]
> ![image](https://user-images.githubusercontent.com/11450939/94364844-d75fb900-00fe-11eb-98b9-173a81dbd484.png) key里面有空格。

不用whistle代理访问链接是没问题的，请问可以修复吗？

**Comment by avwo** [comment]
node对http头字符要求比较严格，重新安装下whistle并重启试试，如果不行就等下个版本强制更新第三方依赖。

**Comment by hqqxxf** [comment]
> node对http头字符要求比较严格，重新安装下whistle并重启试试，如果不行就等下个版本强制更新第三方依赖。
> 
> > 用 npm 或 cnpm 应该可以更新

更新过，不行。下个版本预计什么时候发？

**Comment by hqqxxf** [comment]
> node对http头字符要求比较严格，重新安装下whistle并重启试试，如果不行就等下个版本强制更新第三方依赖。
> 
> > 用 npm 或 cnpm 应该可以更新

更新到最新版本2.5.22可以了，感谢~
