### ISSUE TITLE
为什么我通过连接whistle连接代理，安卓手机端显示乱码？修改resType还是不行。

### ISSUE THREAD

**Issue by 954324919** [avwo/whistle#5]
我试了很多办法都没有解决，求大神解决。

**Comment by 954324919** [comment]
已解决，客户端默认Content-Type写死的，在连接代理后会默认变为content-type，导致，客户端无法匹配编码规则，走默认的编码规则，最终出现乱码。客户端应该兼容不区分大小写，而代理工具也应该是兼容大小写，一点建议，哈哈。

**Comment by avwo** [comment]
[http协议(4.2 Message Headers)](http://www.ietf.org/rfc/rfc2616.txt)的头部字段名称是`case-insensitive `，也就是大小不敏感，浏览器和一些比较通用的库都会自动处理，自己在程序中获取头部字段要注意下先把头部字段名称统一转成小写或者大写再获取
