### ISSUE TITLE
能否支持多端口开启多进程独立工作？

### ISSUE THREAD

**Issue by lndj** [avwo/whistle#50]
配置公用没关系，但是前端显示能否完全独立呢？

**Comment by avwo** [comment]
(https://avwo.github.io/whistle/install.html)[https://avwo.github.io/whistle/install.html]，看下后面的 **启动多个whistle**

**Comment by lndj** [comment]
多谢。

**Comment by zuibunan** [comment]
> https://avwo.github.io/whistle/install.html，看下后面的 **启动多个whistle**

现在文档上没有启动多个实例的说明了

**Comment by avwo** [comment]
https://wproxy.org/whistle/cli.html
