### ISSUE TITLE
whistle 能否一次性把请求头，请求内容，响应头，响应内容一起导出？

### ISSUE THREAD

**Issue by xiaowanzixll** [avwo/whistle#500]
whistle 导出的txt内容，请求内容和响应内容被编码过了，能否去掉编码，类似fiddler的保存选中的会话功能：右键-save-selected session-as txt

**Comment by avwo** [comment]
内容采用base64编码，主要是为了方便存储二进制内容，想自定义保存内容，可以参考 https://github.com/whistle-plugins/whistle.autosave 自己用插件实现。
