### ISSUE TITLE
http 代理的问题，用户名的解析以及 Host 字段的问题

### ISSUE THREAD

**Issue by luckyyyyy** [avwo/whistle#501]
两个问题

第一个问题 当用户名是 user/name:password@ip 的时候解析就出错了，暂时估计无解，建议找个占位符解决。
第二个问题 为什么 host 和 实际链接的域对不上？

实测 cURL 发出的是对的上的
curl -v -X POST https://api.tapd.cn/tcase_categories -x 192.168.51.102:19999

![image](https://user-images.githubusercontent.com/9210430/95594194-34ebf200-0a7d-11eb-8023-56f2e071a4dc.png)

**Comment by luckyyyyy** [comment]
第二个问题 频繁的时候会出现 req 被覆盖了？

**Comment by avwo** [comment]
1. 出什么错误
2. 以 PATH 为准，但怎么重现这个问题？

**Comment by luckyyyyy** [comment]
> * 出什么错误
> * 以 PATH 为准，但怎么重现这个问题？

第一个问题由于url.pares解析出错，导致整个系统相当于挂了，报的错已经无关紧要了，报错的信息也是不对的，测试可以这样写

* proxy://smc/123:1223@192.168.50.49:19999


第二个问题复现很简单，有频繁的请求的时候一定复现，可以联系我远程演示下。

**Comment by avwo** [comment]
1. 斜线被当成路径分隔符了，可以用 `encodeURIComponent` 编码成 `proxy://smc%2F123:1223@192.168.50.49:19999`
2. 加下QQ群：`46255894`

**Comment by luckyyyyy** [comment]
> 1. 斜线被当成路径分隔符了，可以用 `encodeURIComponent` 编码成 `proxy://smc%2F123:1223@192.168.50.49:19999`
> 2. 加下QQ群：`46255894`
加微信了，QQ群好像给错了？

**Comment by avwo** [comment]
代理头设置有点问题（不影响使用），更新下whistle。
