### ISSUE TITLE
Capture TUNNEL CONNECTs 勾选后，在微信中不能查看 h5 与小程序的数据包

### ISSUE THREAD

**Issue by mouyong** [avwo/whistle#502]
![image](https://user-images.githubusercontent.com/10336437/95658844-0e4abb80-0b50-11eb-9f2c-c7c1cdfba91f.png)

**Comment by mouyong** [comment]
![image](https://user-images.githubusercontent.com/10336437/95659206-fd02ae80-0b51-11eb-9f8c-aa86d9fae548.png)


防火墙已暂时关闭。

当启用 https 捕获时，无法联网 #385

**Comment by avwo** [comment]
每个ip 都试一遍看看

**Comment by avwo** [comment]
这个是网络自身问题，问下公司运维怎么解决。

**Comment by mouyong** [comment]
> 每个ip 都试一遍看看

其他 ip 不属于路由器分配的 ip。是不能使用的。

安卓中不能看数据，似乎同事的 ios 在他电脑上可以看。

**Comment by avwo** [comment]
android可能不走系统代理，用iOS吧
