### ISSUE TITLE
 Automatically merge the same header fields

### ISSUE THREAD

**Issue by weiban511** [avwo/whistle#503]
original request:
![image](https://user-images.githubusercontent.com/57676703/95715278-29c2dd00-0c9c-11eb-8cc0-d019aec9d7cc.png)

after whistle:
![image](https://user-images.githubusercontent.com/57676703/95715040-c0db6500-0c9b-11eb-92e7-28b7c2175401.png)

**Comment by avwo** [comment]
The Node server will automatically merge the value of the custom request header with the same key name with comma.
