### ISSUE TITLE
文件上传等大数据时看不到请求内容

### ISSUE THREAD

**Issue by heiby** [avwo/whistle#504]
提示Request data too large to show
<img width="587" alt="企业微信截图_18d0e41a-3e5e-47e2-ad12-f74e3c4c4a03" src="https://user-images.githubusercontent.com/4581299/95983439-2ffbb980-0e54-11eb-81f9-eb9d3f019127.png">

**Comment by avwo** [comment]
不支持显示大文件，可以用reqWrite写到本地文件
