### ISSUE TITLE
【源码修改】whistle从自定义header头部，获取后端服务器地址进行转发，能提供下修改思路么？

### ISSUE THREAD

**Issue by arlingtonroad** [avwo/whistle#505]
基于2.5.20版本进行修改的。
nginx转发请求到whistle，协议是http。

**Comment by avwo** [comment]
不需要修改whistle，直接把nginx请求转发到whistle即可

**Comment by arlingtonroad** [comment]
您的意思是不需要将后端地址放在某个自定义header头部，直接通过proxy_pass到http://127.0.0.1:8899（nginx和whistle同机部署）就可以了？
但是我有一个疑问，如果后端是https协议的请求，nginx直接通过proxy_pass把https请求转发到whistle也可以？

**Comment by avwo** [comment]
试试看就知道
