### ISSUE TITLE
请问怎么过滤某种类型的请求

### ISSUE THREAD

**Issue by lwgpshit** [avwo/whistle#509]
比如过滤png图片的请求

**Comment by avwo** [comment]
https://github.com/avwo/whistle/blob/master/docs/zh/rules/filter.md 根据url后缀或响应类型

**Comment by lwgpshit** [comment]
能给个具体例子吗，比如过滤png图片

**Comment by avwo** [comment]
`www.qq.com status://404 includeFilter://resH.content-type=image/`

**Comment by xiaowanzixll** [comment]
> https://github.com/avwo/whistle/blob/master/docs/zh/rules/filter.md 根据url后缀或响应类型

怎么根据url后缀来匹配呀

**Comment by xiaowanzixll** [comment]
* excludeFilter://h:content-type=application/json
* excludeFilter://m:option
排除所有的content-type=application/json的请求，或者排除所有请求是option，没有生效，是什么原因

**Comment by avwo** [comment]
少了个 s

**Comment by xiaowanzixll** [comment]
> 少了个 s

![image](https://user-images.githubusercontent.com/21018415/99624762-c9c51080-2a69-11eb-8077-6b6affe263aa.png)
我本地这样写的，还是过滤不了，是不是excludeFilter不能这么用，* excludeFilter://m:OPTIONS

**Comment by avwo** [comment]
这个要放规则后面，不能单独一行

**Comment by xiaowanzixll** [comment]
> 你要排除什么规则，这个要放规则后面，不能单独一行，如：`* file://(hello) excludeFilter://m:options`

我只想把凡是options的请求都排除掉，excludeFilter前面没有规则怎么办？

**Comment by xiaowanzixll** [comment]
> > 你要排除什么规则，这个要放规则后面，不能单独一行，如：`* file://(hello) excludeFilter://m:options`
> 
> 我只想把凡是options的请求都排除掉，excludeFilter前面没有规则怎么办？

这前面非得指定个域名名么？

**Comment by avwo** [comment]
不是啊，按自己的想法配下试试就知道

**Comment by xclidongbo** [comment]
这个排除，卵用没有。

**Comment by avwo** [comment]
> 这个排除，卵用没有。

你怎么设置的，规则贴出来看下

**Comment by xclidongbo** [comment]
遇到作者了。。。感谢提供这么好的工具。
