### ISSUE TITLE
No running whistle.

### ISSUE THREAD

**Issue by aogg** [avwo/whistle#513]
![image](https://user-images.githubusercontent.com/8998031/98257544-c2f2c400-1fba-11eb-9a37-6fc896c174b1.png)

**Comment by aogg** [comment]
![image](https://user-images.githubusercontent.com/8998031/98258272-a014df80-1fbb-11eb-80d2-b3590adcac0a.png)
现在就是无法use了，add也不行

说来为什么不提供更简单的非界面添加规则的方式，麻烦的很

**Comment by aogg** [comment]
![image](https://user-images.githubusercontent.com/8998031/98258933-698b9480-1fbc-11eb-8562-64ad2930aae5.png)

**Comment by aogg** [comment]
还有感觉w2 run 就无法识别w2 status，应该是bug吧，不应该必须用w2 start。
一用docker部署，这个项目的bug就很多

**Comment by avwo** [comment]
不是bug，w2 run不会在本地记录进程信息

**Comment by aogg** [comment]
可是这样docker环境就没有守护进程了，搞多个参数start也不会进入后台吧

**Comment by avwo** [comment]
可以用 node 执行模块里面的 index.js启动

**Comment by aogg** [comment]
> 可以用 node 执行模块里面的 index.js启动

这没看懂，有没完整命令

**Comment by avwo** [comment]
用最新版本，docker可以这么启动
``` sh
w2 run -M prod
```
