### ISSUE TITLE
ui界面轮询错误，显示不及时，话说能不能改成websocket来显示数据啊，不要轮询

### ISSUE THREAD

**Issue by aogg** [avwo/whistle#514]
![image](https://user-images.githubusercontent.com/8998031/98513339-a7c9d200-22a2-11eb-9b92-3dfc7a101c51.png)

**Comment by avwo** [comment]
你那边网络是不是很差，websocket也会有同样的问题

**Comment by aogg** [comment]
不差，刷新下就恢复正常，但还要刷新，会出现丢数据的情况

**Comment by avwo** [comment]
轮询不会丢数据的，看下什么原因导致的加载慢

**Comment by aogg** [comment]
经过的数据多了就慢啊，再加上轮询，数据都是一片一片的来
你是真不信websocket能提升体验吗？



![image](https://user-images.githubusercontent.com/8998031/100321993-89800800-2ffe-11eb-8120-0f247e21b3d8.png)

**Comment by aogg** [comment]
还有起码要做到拆分显示，列表只要显示地址等相关信息就好，然后返回结果还要等有操作的时候再显示，这样的优化起码能保证体验

**Comment by avwo** [comment]
道理都懂哈，自己试试就知道为什么别人要这么做。先看下为什么你这边请求响应这么慢，第一次遇到这种情况。

**Comment by aogg** [comment]
还有你会不会出现，如果转发的请求比较慢，这里为了保证顺序也会等待接口的返回才显示之后的接口的

**Comment by avwo** [comment]
轮询是按顺序的，具体加群有空私聊：462558941

**Comment by aogg** [comment]
按顺序的体验不好，会出现因为一个接口慢，导致之后的都不出现，这个可以优化下啊
