### ISSUE TITLE
当外网代理不支持 connect 隧道模式时，无法使用

### ISSUE THREAD

**Issue by pinghe** [avwo/whistle#517]
我的规则
```
a.mydomain.com:8888  b.mydomain.com:9999 proxy://myproxy
```
myproxy 是一个 http 代理服务器，不支持 connect 方法。

Network 面板中看到 Method 是 CONNECT，无法使用普通代理模式

**Comment by avwo** [comment]
开启拦截https：https://wproxy.org/whistle/webui/https.html 再试试 `a.mydomain.com:8888  b.mydomain.com:9999 internal-proxy://myproxy`

**Comment by pinghe** [comment]
已经开启了。  改为 internal-proxy ，看到 Method 还是 CONNECT，Result 还是显示的 502

**Comment by avwo** [comment]
截图

**Comment by pinghe** [comment]
![image](https://user-images.githubusercontent.com/377955/102168624-84aac780-3ecb-11eb-8c63-cb2b2cc1dfb2.png)

**Comment by avwo** [comment]
> 开启拦截https：https://wproxy.org/whistle/webui/https.html 再试试 `a.mydomain.com:8888 b.mydomain.com:9999 internal-proxy://myproxy`

这个设置了吗，先设置好再说

**Comment by pinghe** [comment]
设置了，如果在公网，a.mydomain.com:8888 b.mydomain.com:9999 没有问题。在内网，a.mydomain.com:8888 b.mydomain.com:9999 internal-proxy://myproxy 就成上面截图结果

**Comment by pinghe** [comment]
@avwo  issues被关闭了，是因为在新版本问题已经解决了吗？
