### ISSUE TITLE
resReplace

### ISSUE THREAD

**Issue by pinghe** [avwo/whistle#518]
看帮助文档没看懂。

我想请求某个页面url，将返回的页面内容中的 某个字符串替换为另一个字符串。

在ui的 values 中，单击create后出现的输入框中的值，是 key， 是 resReplace 的参数？包含 大小括号吗？
右边面板中的编辑框，如何指明要替换的字符串及被替换的字符串？

**Comment by pinghe** [comment]
谢谢。

如果要使用 values，values 应该如何设置

**Comment by pinghe** [comment]
a.mydomain.com:8888 internal-proxy://myproxy resReplace://(a=b) resReplace://(:8888=:9999)

没生效

**Comment by avwo** [comment]
替换 URL 和替换内容规则不一样：
``` txt
a.mydomain.com:8888 a.mydomain.com:9999
a.mydomain.com:9999 internal-proxy://myproxy resReplace://(a=b)
```
参考：
https://wproxy.org/whistle/rules/pathReplace.html
https://wproxy.org/whistle/rules/urlParams.html
https://wproxy.org/whistle/rules/rule/replace.html
