### ISSUE TITLE
chrome 环境下 使用whistle 无法捕获https请求 

### ISSUE THREAD

**Issue by NumerHero** [avwo/whistle#52]
chrome版本： "Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36"

whistle 版本： 1.4.20

错误信息： NET::ERR_CERT_AUTHORITY_INVALID

根证书已经安装

电脑也重启了

whistle restart -A 也试过了

tnpm i whistle -g 也尝试过了

目前的情况是 http 可以捕获 https 不行

**Comment by avwo** [comment]
重新安装下根证书：https://avwo.github.io/whistle/webui/https.html

**Comment by NumerHero** [comment]
之前已经尝试重新安装

**Comment by avwo** [comment]
RTX联系我下
