### ISSUE TITLE
weinre抓取问题

### ISSUE THREAD

**Issue by laishiwen1** [avwo/whistle#520]
![image](https://user-images.githubusercontent.com/17246694/102075135-c6426080-3e40-11eb-843d-327ba67fdd4b.png)
代理访问这个网址，不能抓取到weinre

![image](https://user-images.githubusercontent.com/17246694/102075250-f25de180-3e40-11eb-8199-42e302b5bdab.png)
此时通过访问anonymous的weinre已经捕获到clients

![image](https://user-images.githubusercontent.com/17246694/102075435-3650e680-3e41-11eb-8a06-b3a169a1f9c0.png)
![image](https://user-images.githubusercontent.com/17246694/102075527-5385b500-3e41-11eb-826d-1c88c2021a2b.png)
但是通过修改hash为设置weinre缺能捕获到对应的目标，但是在rules的却没有找到设置的weinre

**Comment by avwo** [comment]
![image](https://user-images.githubusercontent.com/11450939/102079815-5041f780-3e48-11eb-8f4a-d90800424b3f.png)

**Comment by laishiwen1** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "avwo/whistle"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月14日(星期一) 晚上8:10
收件人:&nbsp;"avwo/whistle"<whistle@noreply.github.com&gt;;
抄送:&nbsp;"Sven"<laishiwen467158536@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [avwo/whistle] weinre抓取问题 (#520)





 

 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

Whistle Web Debugger - Google Chrome 2020-12-15 13-00-29.mp4 (56.31M, 2021年01月14日 13:02 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=43323233742d42cb3a74ea2817300b180557075206000f061f070102031d0d0101561f5202535a1a5701045206515c5503040551310c39605a5b41475d5519605750127754524c50555740131c107e585d555e56117351455d5f571303000b071f03001e00051906011f02031c0200195f4206330c&code=22231097
