### ISSUE TITLE
[feature]让特定协议/域名的请求顶置，或聚类

### ISSUE THREAD

**Issue by p2227** [avwo/whistle#523]
现在的场景是，whistle抓包里面同时有http的和ws的请求，此时ws的请求不太希望和http的混在一起，不容易找到而且误清除掉。一但误清除了，重新建立连接比较麻烦。

目前我的操作是，把ws的请求标记一下(mark）然后只清楚没有标识的请求。有没有更加简便的操作？

![image](https://user-images.githubusercontent.com/4214942/102756289-98ae6780-43aa-11eb-8126-529318758da6.png)

**Comment by yogalin1993** [comment]
![image](https://user-images.githubusercontent.com/12657170/109496556-c65f0d80-7acb-11eb-9324-b338c4439722.png)
点击 Protocol 不就可以聚类么？

**Comment by p2227** [comment]
@yogalin1993 排序和聚类还是有区别的吧。相关issues https://github.com/avwo/whistle/issues/165

**Comment by avwo** [comment]
Duplicate of https://github.com/avwo/whistle/issues/165
