### ISSUE TITLE
weinre设置不生效

### ISSUE THREAD

**Issue by zengguangzhong** [avwo/whistle#524]
![image](https://user-images.githubusercontent.com/20290798/102761277-ab786a80-43b1-11eb-8b40-f33b104337ae.png)
![image](https://user-images.githubusercontent.com/20290798/102761330-baf7b380-43b1-11eb-82f6-4336d2171d37.png)

如以上两张图片所示，怎么刷新页面都发现没有捕获到。哪里配置错了吗？

**Comment by zengguangzhong** [comment]
系统是win10。node版本：12.18.0

**Comment by avwo** [comment]
按以下顺序操作：
1. 安装证书
2. 开启拦截https
3. 配置规则
4. 打开页面
