### ISSUE TITLE
Postman代理到whistle后，请求的body变为空

### ISSUE THREAD

**Issue by dennisleung** [avwo/whistle#525]
## 环境
- 系统版本：macOS Catalina 10.15.7 
- Postman版本：7.36.0 (7.36.0)
- whistle版本：2.6.0

## 问题描述
![image](https://user-images.githubusercontent.com/5787225/103072936-94c85280-4601-11eb-97d4-4d0c4ca663c2.png)
Postman设置代理到whistlle。

![image](https://user-images.githubusercontent.com/5787225/103073006-bde8e300-4601-11eb-9e72-abfcb5a06307.png)
![image](https://user-images.githubusercontent.com/5787225/103073416-92b2c380-4602-11eb-87fd-04df6949bda1.png)

使用Postman发送请求，whistle抓包查看body是空的，node层接收到body也是空的。关闭代理后正常。

## 期望结果
Postman配置代理后body能正常解析。

**Comment by avwo** [comment]
GET 请求按标准是没有请求内容，改成 post。
