### ISSUE TITLE
`Import Sessions` 不应该拒绝`json`扩展名的文件

### ISSUE THREAD

**Issue by penglei** [avwo/whistle#53]
选择 `Export Selected Sessions`，将请求导出为文件并修改扩展名为`json`，再通过`Import Sessions`导入，提示无法导入。

建议：导入请求时应该判断内容格式，而不是判断文件名(扩展名)

**Comment by avwo** [comment]
[更新下whistle](https://avwo.github.io/whistle/update.html)
