### ISSUE TITLE
希望values能够支持模板填充

### ISSUE THREAD

**Issue by 85204** [avwo/whistle#531]
```c
Access-Control-Allow-Origin: https://domaina.com
Access-Control-Allow-Credentials: true
```
```b
Access-Control-Allow-Origin: https://domainb.com
Access-Control-Allow-Credentials: true
```
/localhost\.charlesproxy\.com/ resHeaders://{c}

根据 chrome 安全策略目前跨域请求头必须要写精确，当需要多个域名时目前只能手动切换
有没有功能可以实现模板填充请求的环境变量
可填充的环境变量可以参考
http://nginx.org/en/docs/http/ngx_http_core_module.html#variables

**Comment by avwo** [comment]
可以用代替：
``` txt
localhost.charlesproxy.com resCors://enable
```
详见：https://github.com/avwo/whistle/blob/master/docs/zh/rules/resCors.md
