### ISSUE TITLE
请问www.ifeng.com resScript://{resScript.js}怎么修改响应内容？

### ISSUE THREAD

**Issue by veryguan** [avwo/whistle#533]
在配置页面的Rules里创建一个规则，右边规则内容为www.ifeng.com resScript://<C:\whistle\resScript.js>，然后这个resScript.js文件怎么修改响应内容？http://wproxy.org/whistle/rules/resScript.html里面有14项，哪项对应响应内容的呀？有没有范例？

**Comment by avwo** [comment]
https://github.com/avwo/whistle/blob/master/docs/zh/rules/resMerge.md
https://github.com/avwo/whistle/blob/master/docs/zh/rules/resReplace.md

**Comment by eric-gitta-moore** [comment]
能不能用 js 修改部分数据，然后根据 js 的返回值设置 response body

**Comment by avwo** [comment]
自己写个插件，参考这个：https://github.com/whistle-plugins/examples/tree/master/whistle.set-rules-according-body
