### ISSUE TITLE
自定义证书没有起作用

### ISSUE THREAD

**Issue by veryguan** [avwo/whistle#534]
fiddler的证书放在C:\certs下，w2 start -z C:\certs启动后在View custom certs info里是空的

**Comment by avwo** [comment]
证书格式可能不正确：
1. key 和 crt 两个文件名称要一致（不包含后缀），如：`a.key a.crt` 
2. 证书里面一定要包含 `DNS Name` 字段
![image](https://user-images.githubusercontent.com/11450939/108487939-c34d6b80-72da-11eb-9020-34c56791d41d.png)
