### ISSUE TITLE
【feature】希望在inspectors-JSONView面板支持对json节点右键全部收缩或全部收起

### ISSUE THREAD

**Issue by Rainbow-556** [avwo/whistle#535]
在json字段比较层次比较深时，要一层一层的去点开，略麻烦，希望能加上一键收起/展开的功能~

**Comment by avwo** [comment]
全部展开会有性能问题，可以用查看文本的方式替代：
![image](https://user-images.githubusercontent.com/11450939/104981057-dd2d3180-5a42-11eb-9122-84da3ce8db61.png)

全部合并点击 root 节点即可，或者通过右键合并上父节点：
![image](https://user-images.githubusercontent.com/11450939/104981130-051c9500-5a43-11eb-9a45-82d0e0a5e4dd.png)
