### ISSUE TITLE
启动问题

### ISSUE THREAD

**Issue by guimc233** [avwo/whistle#536]
![Screenshot_20210124_112739_com termux](https://user-images.githubusercontent.com/65482560/105620430-06313600-5e38-11eb-9bb8-5127deb9858c.jpg)

**Comment by fjqingyou** [comment]
遇到相同问题。

补充说明：运行在 android 的 termux 环境中！

**Comment by avwo** [comment]
w2 run 试试

**Comment by fjqingyou** [comment]
@avwo w2 run 实际测试后查看状态相同结果！

**Comment by avwo** [comment]
w2 run 可以正常启动吗

**Comment by fjqingyou** [comment]
并不能，跟 w2 start 是相同结果

**Comment by avwo** [comment]
可能 Android 上的 Node 版本有些功能不支持，我找台机器看下

**Comment by avwo** [comment]
目前看是因为 Temux 不支持通过 `child_process` 起子进程导致的，可以试试直接依赖 Whistle 启动：

``` js
// app.js
const startWhistle = require('whistle');

startWhistle();
```

> node app.js

Temux 功能限制较多，不太建议在上面运行 Whistle，，可以买云服务器部署 Whistle，这样手机也可以访问。

**Comment by altmangood** [comment]
我在termux上 chroot 启了个容器运行Ubuntu，然后安装node，再安装whistle，运行成功了。

没有root的手机我暂时没试。 有空试试proot看看
