### ISSUE TITLE
希望能新增一个二级代理功能

### ISSUE THREAD

**Issue by fjqingyou** [avwo/whistle#537]
期望某些请求直连；
某些请求走代理A；
某些请求走代理B。

简单来说，期望它具备请求分发管理功能。而分发的渠道根据配置是可以直连的，也可以是动态选择一个匹配的二级代理！

**Comment by avwo** [comment]
插件+proxy协议可以实现 https://github.com/avwo/whistle/blob/master/docs/zh/rules/proxy.md

**Comment by fjqingyou** [comment]
@avwo 感谢，问题确实得到了解决，不过使用中发现了个问题。

嗯。也许是我用法不对，还请指教

域名A proxy://host:prot/
域名B proxy://host:prot/
.....
域名N proxy://host:prot/

通篇配置下来，大量 proxy://host:prot/ 这种不易于维护，是否可以添加一个类似酱紫的
set 代理的别名变量 代理的配置

使用时只要
域名N 代理的别名变量 

后续万一需要修改。只要修改一个。就全部生效？不知道这个方案是否有可行性？

**Comment by avwo** [comment]
`proxy://host:prot 域名A 域名B 域名C ...` 或者用插件动态设置

**Comment by fjqingyou** [comment]
感谢！我研究研究！
