### ISSUE TITLE
插值问题

### ISSUE THREAD

**Issue by AndreGeng** [avwo/whistle#538]
我需要在用户请求html1时，从其中提取出内容content1, 然后请求template2, 把content1的内容插值到template2里再返回给用户，请问要如何配置呢？

**Comment by avwo** [comment]
参考下这个插件的实现：https://github.com/whistle-plugins/examples/tree/master/whistle.test-server

**Comment by AndreGeng** [comment]
👍，已解决。提交了个npm包[whistle.data-extractor](https://www.npmjs.com/package/whistle.data-extractor)，有类似需求的同学也可以参照下
