### ISSUE TITLE
[建议]命令行启动可带上rules的参数

### ISSUE THREAD

**Issue by IcyW** [avwo/whistle#539]
是否能通过命令行在w2 start时带上rules的参数？（也就是可以不在界面上进行配置）
方便通过脚本启动相应的代理配置。

谢谢。

**Comment by IcyW** [comment]
是不是可以通过`w2 add`实现？

https://wproxy.org/whistle/cli.html

**Comment by avwo** [comment]
`w2 add` 也行，也可以通过启动参数设置规则：
``` sh
w2 restart  -r '"ke.qq.com file://(test)\nwww.qq.com file://(abc)"'
```
其中 `"ke.qq.com file://(test)\nwww.qq.com file://(abc)"` 可以通过 `JSON.stringify(rules)` 获取

**Comment by Volankey** [comment]
w2 restart  -r '"ke.qq.com file://(test)\nwww.qq.com file://(abc)"'
这个好像没有用了

**Comment by avwo** [comment]
用最新版的 Whistle，打开 `Network/Tools/ToolBox`，输入规则点击 `ShadowRules`（如下图），将结果作为 `-r` 参数：
``` sh
w2 restart -r "ke.qq.com%20file%3A%2F%2F(test)%0Awww.qq.com%20file%3A%2F%2F(abc)"
```
![image](https://user-images.githubusercontent.com/11450939/126612169-0e8d9887-6ee8-46ad-af9e-55e65f8bf8bc.png)
