### ISSUE TITLE
如何实现nginx的 `proxy_set_header Host $host`

### ISSUE THREAD

**Issue by xinshangshangxin** [avwo/whistle#54]
有以下nginx配置, 因为部分程序代码依赖于Host, 所以需要更改host
```plain
server {
    listen 80;
    server_name www.example.com;
   location / {
        proxy_pass http://127.0.0.1:8888;
        proxy_redirect off;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
    }
}
```
1. 如果为 `www.example.com 127.0.0.1:8888`, 则发现host不正确

2. 如果设置规则为:
```
www.example.com 127.0.0.1:8888 hostname://www.example.com
```
则发现无法访问

3. 使用  `www.example.com 127.0.0.1:8888 req://{test.json}`
```
{
    "headers": {
        "Host": "http://www.example.com",
        "x-test": "123"
    }
}
```
发现 `x-test`设置了, `Host`未设置成功

4. 使用 `reqHeaders` 同上

**Comment by avwo** [comment]
`www.example.com 127.0.0.1:8888` 这种hosts的配置方式，请求头的host就是 `www.example.com`，用 `hostname://www.test.com` 也是可以改的host，在whistle Network界面上抓包看下就知道；请求头的host比较特殊，目前用 `req://xxx` 或 `reqHeaders://` 是改不了，这个确实不是很合理，后续版本做下优化

**Comment by xinshangshangxin** [comment]
ok
