### ISSUE TITLE
rawfile返回超时？

### ISSUE THREAD

**Issue by burst3166** [avwo/whistle#540]
想使用本地文件代替服务器结果
`api.ifeng.com/user/order/create rawfile://{test}`
test为values中的key，其值为
`HTTP/1.1 200 OK`
`
`
`{"status":{"code":1807,"msg":"微信统一下单失败"},"time":1613615909000}`

运行后，抓包显示正常，但是客户端返回超时？ 是使用方法不正确吗？

**Comment by avwo** [comment]
直接用file，rawfile 需要加content-length

**Comment by avwo** [comment]
重新安装 whistle 并重启
