### ISSUE TITLE
如何调试reqScript?

### ISSUE THREAD

**Issue by Germlin** [avwo/whistle#541]
能否在reqScript 中通过 `console.log`或其他方式打印信息，用于调试 reqScript。

**Comment by avwo** [comment]
reqScript 里面的 `console.log` 可以在界面的 `Network / Tools / Server` 里面查看
![image](https://user-images.githubusercontent.com/11450939/108946979-8a2a4800-769a-11eb-9537-7aeb11b41e40.png)

**Comment by Germlin** [comment]
感谢。解决了我的问题。

**Comment by crazier** [comment]
在reqscript里填写了 console.log语句，并没有在Server下看到相关日志，使用console.log有什么依赖吗？

**Comment by avwo** [comment]
要有请求匹配到该规则才会执行：
![image](https://user-images.githubusercontent.com/11450939/148145507-a08fad00-a404-43eb-b296-20b8371bfab7.png)
![image](https://user-images.githubusercontent.com/11450939/148145522-1cf895bb-fc9c-45d5-8dbb-9dc6d9cec399.png)
访问 `https://ke.qq.com`
![image](https://user-images.githubusercontent.com/11450939/148145558-8d4f8c12-f770-4e99-b8ed-79fc95561c3d.png)
