### ISSUE TITLE
http://local.whistlejs.com 无法访问

### ISSUE THREAD

**Issue by huozhiying** [avwo/whistle#542]
系统: MacBook Pro version 10.15.7
问题: http://127.0.0.1:8899可以访问，http://local.whistlejs.com 无法访问，已按照官方文档检查，确定whistle已启动

**Comment by avwo** [comment]
要配代理后才能用 http://local.whistlejs.com/ 访问

**Comment by forcs** [comment]
在哪里配这个代理？这个域名不是安装好后，w2 start启动了就可以访问的么？

**Comment by avwo** [comment]
系统或通过浏览器插件，看下文档

**Comment by forcs** [comment]
已经按照文档说明的步骤操作了，配置了代理，但local.whistlejs.com依然无法访问，同时配置的规则也不生效，还有什么办法可以补救？

**Comment by avwo** [comment]
手机还是 pc ，截图看下

**Comment by samllLuck** [comment]
![Uploading 771619172070_.pic_hd.jpg…]()
@avwo [我是MacOs10.15.7,也是同样的问题[](![781619172229_ pic_hd](https://user-images.githubusercontent.com/42127772/115855949-6c8d1b00-a45e-11eb-9cd2-246ea675d73d.jpg))](url)

**Comment by avwo** [comment]
这两个都要钩上
![image](https://user-images.githubusercontent.com/11450939/115858845-099d8300-a462-11eb-95d0-6020626ee639.png)

**Comment by samllLuck** [comment]
> 这两个都要钩上
> ![image](https://user-images.githubusercontent.com/11450939/115858845-099d8300-a462-11eb-95d0-6020626ee639.png)

当时刚装的时候，貌似不行，隔天就行了，哈哈，感谢大佬
