### ISSUE TITLE
请问优先级问题

### ISSUE THREAD

**Issue by B1anker** [avwo/whistle#543]
```
xxx.com/mediastyle/mobile 127.0.0.1
xxx.com/mediastyle/ ignore://*
```
![image](https://user-images.githubusercontent.com/17514962/109624065-b9e4be80-7b78-11eb-85fb-cf8bd7529e3b.png)
为啥https://xxx.com/mediastyle/mobile/xxx.css 匹配到了第二条而不是第一条呢？

**Comment by avwo** [comment]
这两个是不同的协议，可以同时生效，你这个可以改成：
``` txt
xxx.com/mediastyle/mobile 127.0.0.1
xxx.com/mediastyle/ ignore://* excludeFilter://xxx.com/mediastyle/mobile
```

**Comment by B1anker** [comment]
感谢

> 这两个是不同的协议，可以同时生效，你这个可以改成：
> 
> ```
> xxx.com/mediastyle/mobile 127.0.0.1
> xxx.com/mediastyle/ ignore://* excludeFilter://xxx.com/mediastyle/mobile
> ```

感谢
