### ISSUE TITLE
[feature]能否支持一键开启全局代理配置

### ISSUE THREAD

**Issue by henrycjchen** [avwo/whistle#544]
## 背景
目前使用 whistle 需要配合浏览器的代理插件使用，只能抓包浏览器请求，但如果想抓包其他软件，只能手动配置系统的网络代理

## 期望
希望 localhost:8899 whistle 管理平台支持一键开启/关闭系统代理功能

## 解决方案
目前了解到 win 下有个小工具可以通过指令开启/关闭代理，可以参考下[[小工具链接](https://www.systutorials.com/setproxy-%E4%B8%80%E4%B8%AA%E8%AE%BE%E7%BD%AEie%E4%BB%A3%E7%90%86%E7%9A%84%E5%B0%8F%E5%B7%A5%E5%85%B7/)]
手头没 mac，需要平台调研下了

**Comment by avwo** [comment]
后续可以提供一个设计代理的客户端，可以先试试这个：https://github.com/alibaba/lightproxy

**Comment by Zhantrywei** [comment]
我想请问下，我用whistle来代替switchhost，然后发现本地的node，发起的域名请求不走w2的代理，无法正确解析到对应的host，我这个需要怎么配置全局代理走w2？

**Comment by lizy0329** [comment]
> 我想请问下，我用whistle来代替switchhost，然后发现本地的node，发起的域名请求不走w2的代理，无法正确解析到对应的host，我这个需要怎么配置全局代理走w2？

在node中再设置一层代理，代理到 127.0.0.1:8899 里去

在微信开发者工具中本来只走系统代理，但其有一个选项是设置代理，将 开发者工具 proxy ip 设置 127.0.0.1:8899 就可以使用网页版 whistle。

**Comment by avwo** [comment]
Node 程序里面的请求可以用 https://github.com/avwo/lack-proxy 设置代理

**Comment by sunmaer** [comment]
> 后续可以提供一个设计代理的客户端，可以先试试这个：https://github.com/alibaba/lightproxy

大佬想问下这个目前有具体计划吗

**Comment by sunmaer** [comment]
> 后续可以提供一个设计代理的客户端，可以先试试这个：https://github.com/alibaba/lightproxy

@avwo 大佬，插件支持修改 network 顶部菜单吗，想写个插件支持一键设置系统代理，尝试了下发现 plugins 介绍里没有相关说明，麻烦大佬指导下。

**Comment by avwo** [comment]
有同事会开发一个客户端专门用来设置系统代理和安装证书，感兴趣的话到时拉你一起共建。

**Comment by sunmaer** [comment]
> 有同事会开发一个客户端专门用来设置系统代理和安装证书，感兴趣的话到时拉你一起共建。

好的，感谢

**Comment by lizy0329** [comment]
> 后续可以提供一个设计代理的客户端，可以先试试这个：https://github.com/alibaba/lightproxy

这个产品非常多BUG，核心人员离职，已处于废弃状态，目前不建议使用

**Comment by avwo** [comment]
> > 后续可以提供一个设计代理的客户端，可以先试试这个：https://github.com/alibaba/lightproxy
> 
> 这个产品非常多BUG，核心人员离职，已处于废弃状态，目前不建议使用

好吧，一些配套（如设置代理安装证书客户端，复杂场景的应用文档等）2022 年会逐步完善。

**Comment by LeezQ** [comment]
> > > 后续可以提供一个设计代理的客户端，可以先试试这个：https://github.com/alibaba/lightproxy
> > 
> > 
> > 这个产品非常多BUG，核心人员离职，已处于废弃状态，目前不建议使用
> 
> 好吧，一些配套（如设置代理安装证书客户端，复杂场景的应用文档等）2022 年会逐步完善。

有兴趣啊，开源吗？

**Comment by avwo** [comment]
@LeezQ 等设计好拉上你

**Comment by avwo** [comment]
更新 Whistle，新版支持通过命令行 `w2 proxy` 设置代理：https://wproxy.org/whistle/proxy.html

**Comment by Hujianboo** [comment]
> 更新 Whistle，新版支持通过命令行 `w2 proxy` 设置代理：https://wproxy.org/whistle/proxy.html

你好 我通过w2 proxy 开启全局代理，但是用node请求 仍然没有代理成功好像

**Comment by avwo** [comment]
Node 请求不走系统代理，可以试试：https://github.com/avwo/lack-proxy
