### ISSUE TITLE
Linux环境下，如何 安装根证书 ？

### ISSUE THREAD

**Issue by mutongwu** [avwo/whistle#545]
只看到window/mac环境
http://wproxy.org/whistle/webui/https.html

**Comment by avwo** [comment]
根据系统发行版本、浏览器名称百度下

**Comment by mutongwu** [comment]
> 根据系统发行版本、浏览器名称百度下

如果百度有用，我就不过来提问。（抱歉，本来这里提Issue的）。但是 官网文档 也确实缺少linux下安装证书的指导。
`sudo cp rootca.crt /etc/pki/ca-trust/source/anchors/
sudo update-ca-trust extract`
并没有能够成功。如果Linux的安装比mac/window还简单，还望指导下。

**Comment by avwo** [comment]
我也没在 linux 安装过根证书，不同发型版本及浏览器的安装方式不一样，你是什么系统版本（centos？），浏览器是chrome还是firefox，看下其他人有没有操作过。

**Comment by mutongwu** [comment]
centos，浏览器 Safari

**Comment by avwo** [comment]
你这个证书是要安装在手机啊
