### ISSUE TITLE
可以写插件动态存储 values么，有没有相关api提供

### ISSUE THREAD

**Issue by alipay404** [avwo/whistle#546]

**Comment by avwo** [comment]
参考这里返回 json 对象：https://github.com/Tencent/nohost/blob/master/lib/plugins/whistle.nohost/lib/rulesServer.js#L68

**Comment by alipay404** [comment]
> 参考这里返回 json 对象：https://github.com/Tencent/nohost/blob/master/lib/plugins/whistle.nohost/lib/rulesServer.js#L68

我的意思是动态将返回结构存储在 
![image](https://user-images.githubusercontent.com/11364516/111250032-9bd29000-8647-11eb-91b0-b70126238395.png)
whistle的 Values里面

**Comment by avwo** [comment]
应用场景是什么，这里存储的个数有限，不建议通过程序设置。

**Comment by alipay404** [comment]
> 应用场景是什么，这里存储的个数有限，不建议通过程序设置。

应用场景是自动化测试，然后mock数据，这样可以自动保存下所有的接口数据

**Comment by avwo** [comment]
可以用插件实现，插件不仅可以动态设置规则，且规则及 mock 数据存本地还是数据库都可以自主选择。

**Comment by alipay404** [comment]
> 可以用插件实现，插件不仅可以动态设置规则，且规则及 mock 数据存本地还是数据库都可以自主选择。

那插件内部可以获取到 values里面的东西么 ，类型  {xxx} 这种方法，然后在插件里通过参数获取到 values里面的内容

**Comment by avwo** [comment]
可以参考这个 https://github.com/Tencent/nohost/blob/master/lib/plugins/whistle.nohost/lib/rulesServer.js#L68
