### ISSUE TITLE
打开一个新页面出现无法代理的现象

### ISSUE THREAD

**Issue by Mikeccx** [avwo/whistle#547]
1.配置了一条代理规则，将线上的前端工程代理到本地。
2.触发一个跳转新页面功能，域名没变，只是路由变了，用新窗口打开。
3.新窗口没有代理上，浏览器中，可以通过重新点击switchyomega的代理，重新代理上，但是pc端应用无法通过这个方式解决。

**Comment by avwo** [comment]
设置系统代理试试
