### ISSUE TITLE
能不能支持透明代理，同时支持HTTP和HTTPS？

### ISSUE THREAD

**Issue by hhs66317** [avwo/whistle#549]

**Comment by avwo** [comment]
需要自己实现透明代理，然后把请求转到 Whistle 即可

**Comment by hhs66317** [comment]
直接在路由器上将目标端口为80和443端口的请求直接转发到Whistle的端口上就可以么

**Comment by avwo** [comment]
可以

**Comment by aogg** [comment]
> 需要自己实现透明代理，然后把请求转到 Whistle 即可

iptables直接转过来也接不了，麻烦支持下透明代理模式吧

让下面这个能成功同时，支持平时的规则，最少proxy这个支持下
iptables -t nat -I PREROUTING -p tcp -j DNAT --to-destination 192.168.1.12:8899

**Comment by avwo** [comment]
报什么错
