### ISSUE TITLE
建议可以通过brew安装

### ISSUE THREAD

**Issue by dashixiong91** [avwo/whistle#55]
如题，由于目前大多数人都是用nvm管理Node,如果要频繁切换node版本的话，会很麻烦

**Comment by avwo** [comment]
可以提供下完整的打包上传方案吗

**Comment by qianxinfeng** [comment]
@avwo 可以通过npm-packer（或者webpack）将所有依赖打包在一起,上传到homebrew仓库，这样就可以通过homebrew来安装了，具体的Formula描述文件可以参考yarn的实现：https://github.com/Homebrew/homebrew-core/blob/master/Formula/yarn.rb，
备注：yarn也是node项目，但是可以通过npm全局安装，也可以通过brew安装，所以理论上是可行的

**Comment by avwo** [comment]
好的，我研究下

**Comment by woxiqingxian** [comment]
如果能使用brew确实很诱惑，因为现在使用nvm管理Node，切换版本后使用 whistle 比较麻烦。

**Comment by avwo** [comment]
@echopi 有空看下

**Comment by echopi** [comment]
> @echopi 有空看下

好的

**Comment by echopi** [comment]
提了PR给 homebrew https://github.com/Homebrew/homebrew-core/pull/48268

**Comment by woxiqingxian** [comment]
> 提了PR给 homebrew [Homebrew/homebrew-core#48268](https://github.com/Homebrew/homebrew-core/pull/48268)

合并的请求被brew拒绝了？

**Comment by echopi** [comment]
合进去了，[见](https://github.com/Homebrew/homebrew-core/blob/master/Formula/whistle.rb)

```sh
# 杀whistle进程，卸载之前的命令
w2 stop
npm uin -g whistle

# brew 安装
brew update
brew install whistle
```

迟点再完善下文档

**Comment by avwo** [comment]
如何更新brew的whistle 版本，尽量跟npm的版本保持一致？

**Comment by echopi** [comment]
我写了个文档和脚本，等会提上来

**Comment by woxiqingxian** [comment]
已经使用上了！点赞！

**Comment by echopi** [comment]
文档：
* [brew install whistle 安装及更新文档](https://github.com/echopi/homebrew-whistle/blob/master/whistle-formula.md#%E5%A6%82%E4%BD%95%E5%AE%89%E8%A3%85)
* [如何更新homebrew官方whistle描述](https://github.com/echopi/homebrew-whistle#%E6%8F%90%E4%BA%A4pr%E6%9B%B4%E6%96%B0homebrew-whistle%E7%89%88%E6%9C%AC)
* [关于如何发布whistle到Homebrew](https://github.com/echopi/homebrew-whistle/blob/master/whistle-formula.md)

感兴趣的可以了解一下

**Comment by alanhg** [comment]
所以，arm64需要这样?
> arm64 平台尝试用 brew install node && npm i -g whistle && w2 start --init

手头没M1，没法测试

**Comment by avwo** [comment]
对的

**Comment by alanhg** [comment]
> @avwo 可以通过npm-packer（或者webpack）将所有依赖打包在一起,上传到homebrew仓库，这样就可以通过homebrew来安装了，具体的Formula描述文件可以参考yarn的实现：[https://github.com/Homebrew/homebrew-core/blob/master/Formula/yarn.rb，](https://github.com/Homebrew/homebrew-core/blob/master/Formula/yarn.rb%EF%BC%8C) 备注：yarn也是node项目，但是可以通过npm全局安装，也可以通过brew安装，所以理论上是可行的

更新下yarn参考地址
https://github.com/Homebrew/homebrew-core/blob/master/Formula/y/yarn.rb
