### ISSUE TITLE
Node 11 以上 Https Agent 默认被禁止问题

### ISSUE THREAD

**Issue by xiaomingplus** [avwo/whistle#552]
https://github.com/avwo/whistle/blob/2bc4138038eeae42f0bf3fe42cdd9d3915c401d4/lib/config.js#L862

Hi，想请问一下这里缓存问题具体指的是？

目前已经是14版本了，这里有没有办法修复一下，希望能复用socket。

谢谢！

**Comment by avwo** [comment]
会出现连接非正常中断问题，现在大部分请求走h2，默认就是长连接，还有如果只是内网请求短连接和长连接差异不是很大，

**Comment by xiaomingplus** [comment]
好吧，我再研究下。谢谢！
