### ISSUE TITLE
开发插件时候怎么用代码安装根证书呢？

### ISSUE THREAD

**Issue by Sercl** [avwo/whistle#554]
windows环境，尝试过启动参数，但是并没有生效
> w2 run -z C:\ssl

想着启动后下载whistleUI里提供的链接rootCA.crt，然后代码安装到windows下的**受信任的根证书办法机构**来实现。
![image](https://user-images.githubusercontent.com/35843500/114301154-0e734600-9af6-11eb-8522-fb7131458083.png)

或者有什么其他的方法和思路吗？
非常感谢

**Comment by avwo** [comment]
默认根证书在这个目录 `~/.WhistleAppData/.whistle/certs`，自定义根证书放 `~/.WhistleAppData/custom_certs`或者通过命令行参数 `-z dir` 指定

**Comment by Sercl** [comment]
> 默认根证书在这个目录`~/.WhistleAppData/.whistle/certs`，自定义根证书放或`~/.WhistleAppData/custom_certs`通过命令行参数`-z dir`指定

谢谢，我是windows平台，没有文档里的那个路径诶，使用参数-z 并没有生效

**Comment by avwo** [comment]
`${os.homedir()}/.WhistleAppData`

**Comment by avwo** [comment]
建议直接通过 `http://${options.config.host.}:${options.config.port}/cgi-bin/rootca` 下载
其中 `options` 为：
``` js
exports.xxxServer = (server, options) => {
  // ...
};
```

**Comment by Sercl** [comment]
> 建议直接通过 `http://${options.config.host.}:${options.config.port}/cgi-bin/rootca` 下载
> 其中 `options` 为：
> 
> ```js
> exports.xxxServer = (server, options) => {
>   // ...
> };
> ```

非常感谢大大，就是下载好的crt证书有什么方案可以通过Node进行安装到**受信任的根证书办法机构**吗（非手动安装）？查了相关资料并没有找到，是不只能通过注册表呢？

**Comment by avwo** [comment]
https://github.com/hxfdarling/cert-helper

**Comment by Sercl** [comment]
> https://github.com/hxfdarling/cert-helper

非常感谢，我找了好久没找到
