### ISSUE TITLE
请问怎么让whistle连接上游代理,比如要抓youtube,telegram之类的国外网站或软件

### ISSUE THREAD

**Issue by at89s52rc** [avwo/whistle#555]
请问怎么让whistle连接上游代理,比如要抓youtube,telegram之类的国外网站或软件

**Comment by avwo** [comment]
可以用 socks 协议

**Comment by at89s52rc** [comment]
能让whistle挂上系统代理,作为上层代理吗

**Comment by avwo** [comment]
手动设置系统代理，或者用 https://github.com/alibaba/lightproxy

**Comment by hellodword** [comment]
rules

`* socks://127.0.0.1:1080`
