### ISSUE TITLE
如何给插件弹窗中的按钮绑定事件呢

### ISSUE THREAD

**Issue by limaxmax** [avwo/whistle#556]
插件界面有一个button，一个textarea。我给button绑定了个事件，用来修改textarea的placeholder。
但是当我点击button后，textarea的placeholder并没有改变。
![image](https://user-images.githubusercontent.com/33023889/114701204-111fa680-9d55-11eb-8e78-c107bc198258.png)
![image](https://user-images.githubusercontent.com/33023889/114701600-999e4700-9d55-11eb-8f24-f3c89b911e64.png)

**Comment by avwo** [comment]
菜单是通过 iframe 加载的，试试 `$(selector, window.top)`

**Comment by limaxmax** [comment]
> 菜单是通过 iframe 加载的，试试 `$(selector, window.top)`
![image](https://user-images.githubusercontent.com/33023889/114821925-e46e9c00-9df3-11eb-89ed-ffef87ecfbf8.png)
很遗憾，好像还是获取不到

**Comment by limaxmax** [comment]
已解决，$(selector,window.top.document)[0]
