### ISSUE TITLE
关于抓完包之后的数据包筛选，请问一下是如何进行匹配规则组合使用的呢？

### ISSUE THREAD

**Issue by Phencxl** [avwo/whistle#557]
就是在搜索黑框那里如何组合使用过滤器？
比如说我既要筛选请求头里面包含XXX值，也要请求方法为"POST"的数据包。
总结下来的过滤规则就是: b:XXX 和 m:POST。
但是搜索黑框只能填写一行规则，那么分隔符应该使用什么呢？

![111](https://user-images.githubusercontent.com/25873923/114841076-0a06a000-9e0a-11eb-8366-7ed49f457f24.png)
![222](https://user-images.githubusercontent.com/25873923/114841133-1559cb80-9e0a-11eb-8881-4853ff72ab2b.png)

**Comment by avwo** [comment]
可以

**Comment by Phencxl** [comment]
> 可以

好的，谢谢您~！

**Comment by avwo** [comment]
更新下版本 `v2.6.13`

**Comment by Phencxl** [comment]
> 更新下版本 `v2.6.13`

好的，谢谢。

**Comment by LiarCoder** [comment]
@avwo 这个网络请求的筛选过滤功能使用频率我觉得还是挺高的，目前能做到一定程度的组合筛选。但还是有几点小建议：
1. 我看目前没有针对这些过滤条件的说明文档？导致我不知道该用什么关键字。
2. 这些可选关键字能不能有“输入提示”效果？方便选取。
	1. 就像 Rules 里选 Values 里的值时，我看就有候选项。
3. 是否可以像 Chrome DevTools 里的 network 的筛选功能看齐？
	1. 比如输入 `domain` 可以筛选指定域名下的请求（而且还可以列出可选的 domain 值）
	![Image](https://github.com/user-attachments/assets/78d42594-3841-4d37-9d68-57228d0ac93b)
	2. 比如输入 `-domain` 可以排除指定域名的请求（可以用正则）

**Comment by avwo** [comment]
> [@avwo](https://github.com/avwo) 这个网络请求的筛选过滤功能使用频率我觉得还是挺高的，目前能做到一定程度的组合筛选。但还是有几点小建议：
> 
> 1. ~我看目前没有针对这些过滤条件的说明文档？导致我不知道该用什么关键字。~ 我在 [是否有启动配置文件？ #13](https://github.com/avwo/whistle/issues/13) 里看到了相关描述
> 2. 这些可选关键字能不能有“输入提示”效果？方便选取。
>    
>    1. 就像 Rules 里选 Values 里的值时，我看就有候选项。
> 3. 是否可以像 Chrome DevTools 里的 network 的筛选功能看齐？
>    
>    1. 比如输入 `domain` 可以筛选指定域名下的请求（而且还可以列出可选的 domain 值）
>       ![Image](https://github.com/user-attachments/assets/78d42594-3841-4d37-9d68-57228d0ac93b)
>    2. 比如输入 `-domain` 可以排除指定域名的请求（可以用正则）

很好的建议，未来版本将逐步支持
