### ISSUE TITLE
is there a way to support  node manager 'volta' ?

### ISSUE THREAD

**Issue by EliazTray** [avwo/whistle#558]
I use [`volta`](https://volta.sh) to manage node version.
when i 

```bash
npm i whistle.chii -g
```
**it doesn't take effect in whistle's plugin panels.**

i found it had been installed in `volta` dir(not suitable for plugins dir).

then i found whistle support `NVM`(https://github.com/avwo/whistle/blob/master/lib/plugins/module-paths.js#L64)

so it may support volta too!

**Comment by avwo** [comment]
use `w2 i whistle.chii` instead of

**Comment by EliazTray** [comment]
> use `w2 i whistle.chii` instead of

good.

i solve it by `ln -s [relative path to ~/.WhistleAppData/plugins/node_modules/whistle.chii] whistle.chii`, but is's a little complex.(every plugin needs to do)

![image](https://user-images.githubusercontent.com/16015431/115329897-937cf000-a1c5-11eb-85bb-bb0373bdfdd9.png)

i missed it in [document](https://wproxy.org/whistle/options.html)...
