### ISSUE TITLE
界面上的 filter 不生效

### ISSUE THREAD

**Issue by hellodword** [avwo/whistle#561]
界面上的 [Filter](http://wproxy.org/whistle/webui/filter.html) 功能里填写不生效（可以看到 filter 的颜色变了），而右键 filter 则可以生效

```
$ w2 -V
2.6.14
$ node -v
v10.19.0
```

![image](https://user-images.githubusercontent.com/46193371/115991731-6a60c300-a5fc-11eb-8709-ac73f98dbaf3.png)

**Comment by avwo** [comment]
手动填的对存量请求不生效，可以用右键 Filter 试试

**Comment by hellodword** [comment]
> 手动填的对存量请求不生效，可以用右键 Filter 试试，或者直接在 Network 下方输入过滤，详见：[avwo/help#13](https://github.com/avwo/help/issues/13)

谢谢回复，

右键 filter 可以对存量请求生效，而手动填不生效，这种不一致感觉不太直观，而且右键 filter （可对存量请求生效）的选项太少，只有 exclude url/host，对于分析还是很不方便的，目前只能导出然后借助别的 mitm 工具（Charles、fiddler）来分析。。。

另外，我将请求 export 之后，设置 filter，然后 import，也没有生效，这个我觉得也有点不符合正常预期
