### ISSUE TITLE
【！！！】reqScript获取头部信息字段值不完整

### ISSUE THREAD

**Issue by Wennier** [avwo/whistle#562]
baidu.com/test/path/ reqScript://{reqScript.js}

reqScript.js
var str = JSON.stringify(headers['user-agent']) 

str是Mozilla/5.0，无法判断是pc还是mobile

**Comment by avwo** [comment]
不需要 `stringify` ，直接获取即可 `var str = headers['user-agent']`
![image](https://user-images.githubusercontent.com/11450939/116238050-7df26200-a793-11eb-8d83-6c96939fd109.png)
![image](https://user-images.githubusercontent.com/11450939/116238130-94002280-a793-11eb-8da6-f12320ae820d.png)
