### ISSUE TITLE
关于 whistle 源码的一点疑问

### ISSUE THREAD

**Issue by fengzilong** [avwo/whistle#563]
https://github.com/avwo/whistle/blob/6346927b34d150c7439ef921b49025aab01cd784/biz/webui/htdocs/src/js/data-center.js#L592

最近读了一部分 whistle 的源码，但是对上面这里的逻辑存在一些疑问

如果 `inited === true`，已经初始化过，使用 `lastRowId` 可以理解

但是为什么 `!count`（也就是 count === 0） 也需要传 `lastRowId` 呢 😂

我看服务端代码 cgi-bin 中 get-data 拿到 count 后也是用来取 logs 相关的数据，这里的 count 具体是什么含义呢？

如果改成

```js
lastRowId: inited  ? lastRowId : undefined, 
```

会有什么问题吗？ @avwo

**Comment by avwo** [comment]
前端：`var count = inited ? 20 : networkModal.getDisplayCount();` 
后台：
``` js
function getIds(startTime, count, lastRowId) {
  startTime = startTime || lastRowId; // count 为 0，且 ininted 为 false，则 startTime 为 null
  if (!startTime) {
    return ids.slice(-count);
  }
```

这里面隐藏一个功能，每次刷新页面会先加载之前在页面展示过的最新 60 条数据。

**Comment by fengzilong** [comment]
感谢大大详细的解答~
