### ISSUE TITLE
https 链接无法访问

### ISSUE THREAD

**Issue by cathaysia** [avwo/whistle#568]
在打开 whistle 后，无论是否打开 https 捕获，https链接都无法访问，但是 http 链接可以正常访问

chrome, firefox 已经导入证书

环境： kde + 系统代理

在访问 https 链接时，web debugger 没有任何调试信息，使用 `sudo strace -p `ps -A | grep node | awk '{print $1}'` -ewrite` 查看 whistle 也没有任何调试信息

chromium 提示

```
未连接到互联网代理服务器出现问题，或者地址有误。
请试试以下办法：

联系系统管理员
检查代理服务器地址
ERR_PROXY_CONNECTION_FAILED
```

firefox 

```
代理服务器拒绝连接

Firefox 尝试与您指定的代理服务器连接时被拒绝。

    请检查浏览器的代理服务器设置是否正确。
    请联系您的网络管理员以确认代理服务器工作正常。
```

**Comment by avwo** [comment]
系统代理怎么配的截图看下

**Comment by cathaysia** [comment]
![图片](https://user-images.githubusercontent.com/42114817/117943500-c63a8400-b33e-11eb-8f42-d69c15ef52e7.png)

**Comment by cathaysia** [comment]
emm, 抱歉，上次用的代理忘了关了
