### ISSUE TITLE
想使用crypto-js对某些数据加密, 有什么方案么

### ISSUE THREAD

**Issue by bugaio** [avwo/whistle#569]
情景:
想 替换 某个 接口中的  参数,  但是 参数 是要 进行 加密的, 
能不能 在whistle中 使用crypto  对 某个 数据 加密呢

**Comment by avwo** [comment]
用插件，参考如下项目：
1. 修改 URL：https://github.com/whistle-plugins/examples/blob/master/whistle.test-rules/lib/rulesServer.js
2. 修改内容：https://github.com/whistle-plugins/examples/tree/master/whistle.test-pipe
