### ISSUE TITLE
Proposal for English Intro and Docs - 英文版本介绍与文档

### ISSUE THREAD

**Issue by iFwu** [avwo/whistle#57]
Whistle是我用过对前端开发者来说最方便的调试工具之一，但是看到介绍文章并不多，也没有在社区流行开，我觉得可能和介绍、文档都是中文有关吧（看Issue也大多是国人）。
搜了一下，这样的工具其实应该很受社区欢迎才对，毕竟在mac上的抓包、特别是修改header等功能的软件很少，有的话也是像Charles这样用Java写的，打开速度比较慢，添加规则和使用也很不方便。
如果作者允许的话，我想参与README和文档的翻译，毕竟推广也是开源项目的重要组成部分之一。

**Comment by avwo** [comment]
非常欢迎，正需要有人来帮忙做这个事情，只有社区里面大家的帮助才能把whistle越做越好，中文文档后面也打算重整下，项目文档这块[Vue的文档](https://vuejs.org/)提供了一个标杆，你可以先按着你自己的想法，参考下 [whistle中文文档](https://avwo.github.io/whistle/)里面的用法，写个英文版的README提个[PR](https://github.com/avwo/whistle/pulls)，主要方便英文用户直接入门，更详细用法的英文文档我们再来拆分任务，让更多的人帮忙完善。

**Comment by avwo** [comment]
Duplicate of https://github.com/avwo/whistle/issues/393

**Comment by lizy0329** [comment]
> Whistle是我用过对前端开发者来说最方便的调试工具之一，但是看到介绍文章并不多，也没有在社区流行开，我觉得可能和介绍、文档都是中文有关吧（看Issue也大多是国人）。
> 搜了一下，这样的工具其实应该很受社区欢迎才对，毕竟在mac上的抓包、特别是修改header等功能的软件很少，有的话也是像Charles这样用Java写的，打开速度比较慢，添加规则和使用也很不方便。
> 如果作者允许的话，我想参与README和文档的翻译，毕竟推广也是开源项目的重要组成部分之一。

主要是文档不好，我第一次看的时候头大，还好坚持下来了

**Comment by avwo** [comment]
大家可以帮忙一起完善
