### ISSUE TITLE
Q: w2 支持根据 host 修改 url 内容吗？

### ISSUE THREAD

**Issue by cathaysia** [avwo/whistle#570]
具体内容是：

我需要将所有 host 为 github.com 的 url ，例如 `https://github.com/avwo/whistle.zip` 修改为 `https://ghproxy.com/https://github.com/avwo/whistle.zip` 主要是用来加速的。

例如对于 Fiddler 的替换规则是<sup>[1](https://github.com/microsoft/vcpkg/discussions/17535)</sup>： 

```c#
if(oSession.host == "github.com:443" || oSession.host == "raw.githubusercontent.com:443"){
    oSession.host = "ghproxy.com:443"
}
if(oSession.host == "github.com" || oSession.host == "raw.githubusercontent.com"){
    //oSession.host = "ghproxy.com"
    oSession.fullUrl = "https://ghproxy.com/https://" + oSession.url
}
``` 

w2 可以实现这种效果吗？在查阅文档后我发现 w2 虽然有匹配 url 的方式，但是似乎并没有办法拿到匹配到的 url。而且也没有提供 url 相关的字符串函数。

现在看来唯一的办法是开发一个插件？

**Comment by avwo** [comment]
配置url替换规则即可:
```
https://github.com/avwo/whistle.zip https://ghproxy.com/https://github.com/avwo/whistle.zip
```
大部分操作都可以找到相应的规则

**Comment by cathaysia** [comment]
感谢指导！ 我指导怎么弄了 :)
