### ISSUE TITLE
重启电脑后，whistle就失效了

### ISSUE THREAD

**Issue by xywai1993** [avwo/whistle#571]
whistle只能使用一次，重启电脑后就无法使用了，我看了系统证书，没发现有什么问题呀，大家有遇到过吗？

之前没有这个问题，可能是Mac更新后就出现这个问题了。

Mac 版本 ： 11.3.1 (20E241) 

有没有什么解决方案，我现在是卸载后重装，使用完之后又不行了。

**Comment by avwo** [comment]
证书无效，还是代理配置无效？

**Comment by xywai1993** [comment]
> 证书无效，还是代理配置无效？

就是在手机上无法连上代理服务器了

**Comment by avwo** [comment]
这个是你网络问题吧，看下是不是 pc 的 ip 变了

**Comment by xywai1993** [comment]
> 这个是你网络问题吧，看下是不是 pc 的 ip 变了

我确定我的PC的IP没有变，可就是手机无法连上，这个问题持续一个星期了。 我也希望是公司网络有问题，但是如果是网络问题那我就一头雾水，解决不了了。

**Comment by xywai1993** [comment]
> 这个是你网络问题吧，看下是不是 pc 的 ip 变了

有一个遇到了类似的问题 ，https://github.com/alibaba/lightproxy/issues/243

**Comment by avwo** [comment]
看下 `~/.WhistleAppData/.whistle/certs` 目录是不是被清空了。。。

**Comment by xywai1993** [comment]
> 看下 `~/.WhistleAppData/.whistle/certs` 目录是不是被清空了。。。

没有清空，有 root.crt 和 root.key

**Comment by avwo** [comment]
如果为空，重启 Whistle 会自动创建，看下修改时间，或者确认下网络是否是通的，你手机是否可以访问pc上的服务？

**Comment by xywai1993** [comment]
> 如果为空，重启 Whistle 会自动创建，看下修改时间，或者确认下网络是否是通的，你手机是否可以访问pc上的服务？

谢谢，我好像解决了。强杀程序重启就可以了， kill -9

**Comment by xywai1993** [comment]
但是有时候要强杀好几次，然后等待几分钟就可以了。 有点奇怪，可能还是我的电脑有问题，先忽略吧。

**Comment by xywai1993** [comment]
但是有时候要强杀好几次，然后等待几分钟就可以了。 有点奇怪，可能还是我的电脑有问题，先忽略吧。

**Comment by suedar** [comment]
> > 如果为空，重启 Whistle 会自动创建，看下修改时间，或者确认下网络是否是通的，你手机是否可以访问pc上的服务？
> 
> 谢谢，我好像解决了。强杀程序重启就可以了， kill -9

我也遇到了 请问怎么强杀程序 @xywai1993
