### ISSUE TITLE
[bug]  DELETE 请求被意外添加了 Transfer-Encoding 头

### ISSUE THREAD

**Issue by 1574242600** [avwo/whistle#573]
## 环境
whistle: v2.6.16

## 描述
所有 DELETE  HTTP 1.1 请求 (代理，Composer)，无论此前是否有 Transfer-Encoding 头，都被添加了 Transfer-Encoding 头（没有显示在 Inspectors）以及分块传输编码。

### 示例
原始的请求:  
![Screenshot_20210522_111253](https://user-images.githubusercontent.com/35765846/119213007-be24d600-baee-11eb-844b-3143301fd24c.png)
whistle发出的请求:
![Screenshot_20210522_111611](https://user-images.githubusercontent.com/35765846/119213063-22e03080-baef-11eb-8a1d-b83e34bfa451.png)

## 复现
使用任意方式通过 whistle 发送 DELETE HTTP 1.1 请求

## 可能相关的代码
https://github.com/avwo/whistle/blob/0ad8e9e5fdce9d547bfb2baff41ecdac88b829e5/lib/inspectors/res.js#L517-L543

**Comment by avwo** [comment]
你的问题会导致什么后果？`DELETE` 方法比较特殊，标准文档里面没有说明能不能携带 body，有些服务支持有些不支持，如 Node  就不支持 `DELETE` 方法带请求内容，上面的实现是为了规避此问题。

**Comment by 1574242600** [comment]
nginx 的 webdav 模块会检查 DELETE 请求的 Transfer-Encoding
https://github.com/nginx/nginx/blob/ecbe06b9fee57207d84be9ac39d1aa10b2d0fbd8/src/http/modules/ngx_http_dav_module.c#L315-L319
导致直接返回415

主要是修改了原始请求而 Inspectors 又没显示，这非常坑人  
还有没有其它会修改原始请求的地方？
