### ISSUE TITLE
values怎么不支持==判断的

### ISSUE THREAD

**Issue by aogg** [avwo/whistle#575]
if ('baidu.com' == 'baidu.com'){
	rules.push(host + ' proxy://172.18.0.6:8080');
}

还有麻烦values文档写全些，太简单了只有个快捷键操作，而且其他链接到values的链接都是错误的，都还在local.whistle这个域名

**Comment by aogg** [comment]
还有values里面的console.log到底打到哪里去了，我看tools没有啊

**Comment by avwo** [comment]
用 https://github.com/avwo/whistle/blob/master/docs/zh/rules/reqScript.md 或插件：https://github.com/avwo/whistle/blob/master/docs/zh/plugins.md
