### ISSUE TITLE
IPhoneX Https 不支持 Capture TUNNEL CONNECTs

### ISSUE THREAD

**Issue by fjqingyou** [avwo/whistle#577]
## 环境
手机设备 IPhoneX
w2 运行环境 MacOS Catalina 10.15.7
w2 启用了 HTTP/2 以及 Capture TUNNEL CONNECTs

## 确认手机设备已经安装了描述证书
![IMG_2492](https://user-images.githubusercontent.com/31087168/120273904-b41a8880-c2e1-11eb-844b-56ac05e9d0d8.PNG)

## 然而结果是
![IMG_2493](https://user-images.githubusercontent.com/31087168/120273937-bc72c380-c2e1-11eb-912a-39af6c894fda.PNG)

**Comment by fjqingyou** [comment]
确认在不启用 Capture TUNNEL CONNECTs 时。是能够正常访问的

**Comment by fjqingyou** [comment]
whistle@2.7.2

**Comment by avwo** [comment]
iOS安装证书后要到设置/关于里面点确认才行，具体看下文档

**Comment by fjqingyou** [comment]
确认已经在：设置->通用->描述文件->找到 whistle -> 状态已经是：已验证 打钩

**Comment by avwo** [comment]
![image](https://user-images.githubusercontent.com/11450939/120276426-3e182080-c2e5-11eb-8020-66b19cf25c96.png)

**Comment by fjqingyou** [comment]
哦。原来是我设置没搞完啊！谢谢！
