### ISSUE TITLE
升级后重启导致配置丢失

### ISSUE THREAD

**Issue by lndj** [avwo/whistle#58]
w2 restart -S xxx

升级1.5之后，原配置丢失了

**Comment by avwo** [comment]
`w2 restart -S xxx -C` 看看

**Comment by lndj** [comment]
试了下 现在回不去了

**Comment by avwo** [comment]
看下 `~/.WhistleAppData/.whistle/custom_dirs` 里面的 `xxx` 目录及其子目录有没有文件

**Comment by lndj** [comment]
![image](https://user-images.githubusercontent.com/9111083/29208061-1b42e742-7ebb-11e7-944d-a77fa7b85e87.png)
我已端口号命名的存储目录，现在看起来 rules file 下的 0.xx 1. xx 还在 内容没了

**Comment by avwo** [comment]
所有目录的数据都丢失了？

**Comment by lndj** [comment]
嗯..

**Comment by lndj** [comment]
`w2 start -S 8926 -p 8926 -C` 第一次启动是这样的

**Comment by avwo** [comment]
我这边的问题，先别用 `-C` 启动，晚点我发个版本fix掉

**Comment by lndj** [comment]
嗯 辛苦 你的意思是之前的数据还是在的是吧，之前在那个文件夹下呢？

**Comment by avwo** [comment]
更新下whistle到最新版本试试
```
npm i -g whistle --registry=https://registry.npm.taobao.org
w2 restart
```

**Comment by lndj** [comment]
`w2 restart` 会重启所有的吗 还是？

**Comment by avwo** [comment]
按你原来的方式

**Comment by lndj** [comment]
看起来是没问题了，但是之前的已经丢失了哈哈哈哈啊。辛苦～～～
