### ISSUE TITLE
Error: Parse Error: Duplicate Content-Length

### ISSUE THREAD

**Issue by t2krew** [avwo/whistle#580]
```plain
From: whistle@2.7.3
Node: v16.1.0
Date: 2021/6/7 下午12:05:30
Error: Parse Error: Duplicate Content-Length
    at TLSSocket.socketOnData 

- [ ] 

- [ ] (node:_http_client:487:22)

    at TLSSocket.emit (node:events:365:28)
    at addChunk (node:internal/streams/readable:314:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at TLSSocket.Readable.push (node:internal/streams/readable:228:10)
    at TLSWrap.onStreamRead (node:internal/stream_base_commons:190:23)
```

使用whistle代理的时候，遇到包这个错，请求响应直接502了；换charles代理是正常的。

请求/响应头里没有`Content-Length`。

##### 请求headers
![image](https://user-images.githubusercontent.com/5849474/120958548-8c686c00-c78a-11eb-9754-07203aca9ef4.png)

##### 响应headers
![image](https://user-images.githubusercontent.com/5849474/120958612-b15cdf00-c78a-11eb-81cc-c0473ca00615.png)

**Comment by avwo** [comment]
不要经过代理，用 Chrome 直接请求看下响应头，如果确实有两个 `Content-Length` 字段，说明响应内容不符合规范，Node 对这块要求比较严格。

**Comment by t2krew** [comment]
@avwo 用chrome请求也是没有content-length这个头的。

![image](https://user-images.githubusercontent.com/5849474/120968418-6dbea100-c79b-11eb-9e4c-84a66fc9f842.png)

**Comment by avwo** [comment]
不应该，url 方便发我看下吗

**Comment by PeterChen1997** [comment]
同样的问题 +1，在 request 和 response 中都没有 content-length

**Comment by avwo** [comment]
请求链接发我看下

**Comment by PeterChen1997** [comment]
> 请求链接发我看下

[
  {
    "startTime": 1624267871257,
    "id": "1624267871256-768",
    "url": "https://xxx.xxx.com/xxx/api/users/current?UDID=&_hostProductId=351&_productId=351&platform=mobile&version=6.40.0&timestamp=1624267871214",
    "req": {
      "method": "OPTIONS",
      "httpVersion": "1.1",
      "ip": "127.0.0.1",
      "port": "56318",
      "rawHeaderNames": {
        "connection": "Connection",
        "proxy-authorization": "Proxy-Authorization"
      },
      "headers": {
        "host": "xxx.xxx.com",
        "accept": "*/*",
        "access-control-request-method": "GET",
        "access-control-request-headers": "x-requested-with",
        "origin": "https://site-test.xxx.com",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-site",
        "sec-fetch-dest": "empty",
        "referer": "https://site-test.xxx.com/",
        "accept-encoding": "gzip",
        "accept-language": "zh-CN,zh;q=0.9"
      },
      "size": 0,
      "body": false,
      "rawHeaders": {
        "host": "xxx.xxx.com",
        "accept": "*/*",
        "access-control-request-method": "GET",
        "access-control-request-headers": "x-requested-with",
        "origin": "https://site-test.xxx.com",
        "user-agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36",
        "sec-fetch-mode": "cors",
        "sec-fetch-site": "same-site",
        "sec-fetch-dest": "empty",
        "referer": "https://site-test.xxx.com/",
        "accept-encoding": "gzip",
        "accept-language": "zh-CN,zh;q=0.9"
      }
    },
    "res": {
      "ip": "47.93.17.79",
      "port": 443,
      "rawHeaderNames": {},
      "statusCode": 502,
      "headers": {
        "content-type": "text/html; charset=utf8",
        "server": "whistle",
        "__lightproxy-host-ip__": "47.93.17.79",
        "__lightproxy-rules__": "none",
        "__lightproxy-real-url__": "https://xxx.xxx.com/xxx/api/users/current?UDID=&_hostProductId=351&_productId=351&platform=mobile&version=6.40.0&timestamp=1624267871214",
        "__lightproxy-help__": "See https://github.com/alibaba/lightproxy"
      },
      "size": 546,
      "body": "",
      "base64": "deleted",
      "rawHeaders": {
        "content-type": "text/html; charset=utf8",
        "server": "whistle",
        "__lightproxy-host-ip__": "47.93.17.79",
        "__lightproxy-rules__": "none",
        "__lightproxy-real-url__": "https://xxx.xxx.com/xxx/api/users/current?UDID=&_hostProductId=351&_productId=351&platform=mobile&version=6.40.0&timestamp=1624267871214",
        "__lightproxy-help__": "See https://github.com/alibaba/lightproxy"
      }
    },
    "rules": {},
    "rulesHeaders": {},
    "dnsTime": 1624267871266,
    "useH2": false,
    "requestTime": 1624267871296,
    "responseTime": 1624267871340,
    "endTime": 1624267871340,
    "method": "OPTIONS",
    "hostIp": "47.93.17.79",
    "clientIp": "127.0.0.1",
    "date": "2021/6/21 下午5:31:11.257",
    "clientPort": "56318",
    "serverPort": 443,
    "contentEncoding": "",
    "body": 546,
    "result": 502,
    "type": "text/html",
    "time": "83ms",
    "download": "0ms",
    "response": "44ms",
    "request": "30ms",
    "dns": "9ms",
    "protocol": "HTTPS",
    "hostname": "xxx.xxx.com",
    "path": "/xxx/api/users/current?UDID=&_hostProductId=351&_productId=351&platform=mobile&version=6.40.0&timestamp=1624267871214",
    "order": 23,
    "hide": false,
    "lost": true,
    "selected": true,
    "active": true,
    "filename": "current"
  }
]

**Comment by avwo** [comment]
直接在 whistle 上导出是看不到的，这种在 Node 解析 http 请求时就报错了，用 Chrome 不经过 Whistle 直接请求看下响应头

**Comment by PeterChen1997** [comment]
![image](https://user-images.githubusercontent.com/21072589/122754856-bfe8e180-d2c6-11eb-8f47-7e18ccf0edf2.png)
确实有这个问题，我看下，十分感谢

**Comment by PeterChen1997** [comment]
> 直接在 whistle 上导出是看不到的，这种在 Node 解析 http 请求时就报错了，用 Chrome 不经过 Whistle 直接请求看下响应头

看了下这块的接口不太好排查是哪一环出了问题，想问下在代理层我们有办法跳过这个问题吗..

**Comment by avwo** [comment]
无法跳过，除非自己解析 HTTP 请求，还是修复你们的业务代码（源码目录搜下 `content-length` 试试），尽量按标准来。

**Comment by PeterChen1997** [comment]
> 无法跳过，除非自己解析 HTTP 请求，还是修复你们的业务代码（源码目录搜下 `content-length` 试试），尽量按标准来。

嗯嗯主要是公司基建不太行，中间过了很多道业务方，短期内不太好处理..了解了感谢大佬
