### ISSUE TITLE
在使用threejs加载模型时，开启 log 导致加载速度巨幅增加，移动端崩溃

### ISSUE THREAD

**Issue by gyq348097872** [avwo/whistle#582]
react项目，在使用 threejs 加载 glb 模型时（使用 GLTFLoader），在不配置 log 的情况下，加载速度为 2~3s
<img width="268" alt="截屏2021-06-13 17 30 33" src="https://user-images.githubusercontent.com/24505486/121802034-102fc600-cc6d-11eb-9bb7-8f09bfb4d1e5.png">

当配置了 log 时（或采用 vconsole 注入的方式）
www.xxx.com log://
www.xxx.com jsPrepend://{vconsole.min.js}
www.xxx.com jsPrepend://{console.js}

在 chrome 上加载时间增加到了20多秒，在移动端直接 crash
<img width="267" alt="截屏2021-06-13 17 35 11" src="https://user-images.githubusercontent.com/24505486/121802145-b7acf880-cc6d-11eb-9854-81a5c9c809f2.png">

但是没有发现有报错，想麻烦帮忙定位一下

**Comment by avwo** [comment]
页面链接发我试下

**Comment by avwo** [comment]
更新下 whistle：https://github.com/avwo/whistle/blob/master/CHANGELOG.md#v275

**Comment by gyq348097872** [comment]
> 更新下 whistle：https://github.com/avwo/whistle/blob/master/CHANGELOG.md#v275

问题已解决，非常感谢
