### ISSUE TITLE
whistle升级到2.7版本后为啥取消rules旁边的小选项？

### ISSUE THREAD

**Issue by xiaowanzixll** [avwo/whistle#585]
![image](https://user-images.githubusercontent.com/21018415/122018891-db02af80-cdf5-11eb-8a54-0abcf321a872.png)

whistle升级到2.7版本后为啥取消rules旁边的小选项呢？之前的勾选项挺好用的啊，选中打勾挺方便，是否有选种规则看起来很清晰，为啥取消，如果不能恢复，问一下怎么恢复原来的老版本2.5.3

**Comment by avwo** [comment]
视觉上不好看，改用右键了，尽量用新版本。

**Comment by xiaowanzixll** [comment]
哦，原来改成这样，每次升级新功能，有图解吗？
![image](https://user-images.githubusercontent.com/21018415/122022282-06d36480-cdf9-11eb-802c-5e64aec49ce4.png)
原来有保留勾选项，只是升级了新功能不知道

**Comment by avwo** [comment]
有些显而易见的功能就没有放 CHANGELOG.md 里面：https://github.com/avwo/whistle/blob/master/CHANGELOG.md
