### ISSUE TITLE
weinre经常断线,很难使用

### ISSUE THREAD

**Issue by zyzweb** [avwo/whistle#589]
升级到最新版2.7.4,weinre经常检测不到target,作者推荐的https://github.com/liriliri/chii  插件也检测不到

**Comment by avwo** [comment]
这个跟版本没关系，哪个页面，用什么浏览器访问的。

**Comment by zyzweb** [comment]
![image](https://user-images.githubusercontent.com/41266834/122539110-cfafbe00-d059-11eb-8bb3-5b6f282dddf2.png)
ios14.3  safari浏览器  手机已经安装了whistle证书开启了https捕获

**Comment by zyzweb** [comment]
同样的链接在pc上可以用chii抓取到

**Comment by avwo** [comment]
是不是证书没安装好，需要到 Settings > General > About > Certificate Trust Testings 确认下：
![image](https://user-images.githubusercontent.com/11450939/122546027-1ead2180-d061-11eb-9554-e6306859f958.png)

**Comment by zyzweb** [comment]
确实是这个问题,完美解决,谢谢大佬
