### ISSUE TITLE
建议values编辑器增加语言选择和json折叠功能

### ISSUE THREAD

**Issue by mooring** [avwo/whistle#590]
1. 建议values编辑器增加语言选择 如 `javascript, json, yaml, xml , markdown`等，切换语言时，自动高亮
2. 对于返回数据特别长的情况下，现在查找功能有点弱，**查找很不方便**，也**不能折叠**，不如直接在编辑器部分增加个工具栏，希望有个按**缩进折叠**或者**语法折叠**
3. **values和rules支持分组**，方便管理，现在只能是以名称前辍来做类似分组，但名字一长就不好搞了

**Comment by avwo** [comment]
1. Values 里面的 key 加个后缀即可，如：`xxx.js`
2. 大文本建议反本地文件，Whistle 也支持从本地文件读取配置，这样也可以用 VS Code 等编辑器处理
3. 待定，还没想好，有 issue 跟着：https://github.com/avwo/whistle/issues/472

**Comment by mooring** [comment]
2 whistle和浏览器是同一个应用，在右侧标签访问页面devtool 面板复制数据，在左侧whistle中设置value, 然后再修改部分值，这样不离线浏览器就完成了回包内容，很方便，如果再开个vs code或者是在vs code中再新建个文件，并保存到本地，整个链路有些打断，不是那么连贯，而且有桌面，vs code, 浏览器多个应用间切换，不是那么高效

当然用vs code完全拥有了代码编辑器的各种能力，看大家怎么理解吧

**Comment by mooring** [comment]
1. 中的加扩展名已经用好久了，format的功能很赞，其实更需要的是在有语言高亮的基础上的，代码折叠，或者按缩进，或者按语法，都可以

**Comment by avwo** [comment]
好建议，后面可以尝试换 VS Code 的 `monaco-editor` 看看。

**Comment by LeezQ** [comment]
> 1. 对于返回数据特别长的情况下，现在查找功能有点弱，查找很不方便，也不能折叠，不如直接在编辑器部分增加个工具栏，希望有个按缩进折叠或者语法折叠
这个codemirror 应该也能支持的吧，我来看下。

**Comment by avwo** [comment]
重新安装 whistle 并重启
