### ISSUE TITLE
HTTPS页面，Custom Certs不能显示证书问题

### ISSUE THREAD

**Issue by ifooth** [avwo/whistle#591]
## 问题：
- 看过了这个https://github.com/avwo/whistle/issues/534 issue，里面表示必填是DNS Name
- 想问下能否优化下，只有CN(Common Name)，也可以显示呢？

## 原因：
- 看现在信任的证书链，根证书都是不带DNS Name的
![image](https://user-images.githubusercontent.com/1853121/123635039-bc68d380-d84d-11eb-8851-f00d6f86ab16.png)
- CN是规范显示的名称
- 而自定义证书的场景，一般更多直接定义一个根证书吧

## 需求：
看看能否支持下，多谢(我的理解是，只要是合法的，包含CN的都应该显示，如果有个点击详情，能显示证书的其他信息，就更完美了）

**Comment by avwo** [comment]
Chrome 浏览器要求证书必须有 DNS Name

**Comment by ifooth** [comment]
浏览器只要求证书链最下层包含DNS Name，看下图
![image](https://user-images.githubusercontent.com/1853121/123728909-ae0ace00-d8c6-11eb-9728-afd403eafd93.png)
github.com证书 是 whistle 自动生成的吧，貌似和自定义证书没有关系哦


我就放了一个根证书（根证书肯定是需要固定的，不想换个环境，手机或者电脑就重新设置下）

**Comment by ifooth** [comment]
补充下， 我自己有生成带域名的证书，使用是OK的。我觉得大家几次提这个issue，肯定是用到，但是使用的过程中，看到的没有预期内。

大家根据文档 http://wproxy.org/whistle/custom-certs.html，配置好证书，也能使用，会到页面check下，这个时候一看，发现不能显示，这个时候就懵了，也不知道啥问题。这个是和，应该要么日志报错，要么能正常显示比较符合预期的。

**Comment by avwo** [comment]
自定义根证书可以放 `~/.WhistleAppData/custom_certs` 试试， 且名字必须分别为 `root.key`、`root.crt`

**Comment by ifooth** [comment]
这个我知道的哈， 使用是正常的，只是显示问题，看上面我补充的评论。

**Comment by avwo** [comment]
大概明白你的意思，whistle 对自定义根证书也校验了 DNS Name ？确实是一个问题，下个版本修复。

**Comment by avwo** [comment]
你这边是下面两个问题吗？
1. 自定义证书（除根证书外）为什么要求带 DNS Name？
2. 如果自定义证书有问题，希望 Whistle 加载时能给个报错提醒？

**Comment by ifooth** [comment]
第一个问题：自定义根证书应该也可以在custom_certs显示

第二个问题测试了下，如果证书异常应该已经报错了，whistle 不能正常启动(预期内，如果能更加友好的提示最好)
![image](https://user-images.githubusercontent.com/1853121/123732115-00022280-d8cc-11eb-9756-1fda2d65e0cb.png)

nginx 证书报错如下图
![image](https://user-images.githubusercontent.com/1853121/123732736-eca38700-d8cc-11eb-92b1-bd0196dbfda5.png)

**Comment by ifooth** [comment]
可能问题没有沟通清楚， 最后补充下
- 其实就是`root证书`，没有在`Custom Certs`页面正常显示问题
- 这个其实不影响使用，因为很喜欢这个项目，还是提了个issue，希望能改进吧，感谢大佬一直更新。

**Comment by avwo** [comment]
更新下 Whistle 试试
