### ISSUE TITLE
根证书问题

### ISSUE THREAD

**Issue by wusanCL** [avwo/whistle#592]
安卓（meta40 pro）扫码下载根证书提示无法访问网址。
android chrome进入rootca.pro白屏
pc下载根证书没有问题（未验证是否可以抓包）

**Comment by avwo** [comment]
手机要先配置 Whistle 的代理才能下载

**Comment by wusanCL** [comment]
> 手机要先配置 Whistle 的代理才能下载

哦哦，酱，感谢
