### ISSUE TITLE
copy curl功能希望拷贝的是修改后的curl

### ISSUE THREAD

**Issue by eightHundreds** [avwo/whistle#594]
场景:
使用whistle将后端接口代理到指定的容器服务,比如 api.com -> api.containerName.com
排查问题时,想从whistle拷贝curl给后端,此时希望curl中的地址是api.containerName.com

**Comment by avwo** [comment]
直接 copy 替换后的 url 可能不是很直观，你可以 copy 出来用个文本编辑器手动改下。

**Comment by eightHundreds** [comment]
这不只是url的问题，改url很简单
但任何whistle操作符都有可能改到请求报文，包括header，body。
这时再要求手改，成本就不小了

**Comment by eightHundreds** [comment]
我认为这个需求是需要新的按钮(copy real curl),不是修改旧的.

**Comment by avwo** [comment]
更新下 Whistle，新版可以按住 Shift  + 点击 `Copy Xxx` 可以弹出编辑框，编辑后再点击 Copy 按钮即可。
