### ISSUE TITLE
使用SwitchyOmega开启https代理报错

### ISSUE THREAD

**Issue by xihangzhou** [avwo/whistle#595]
两个问题，请教作者：

1.
使用SwitchyOmega代理浏览器的https流量，配置如下：
![image](https://user-images.githubusercontent.com/47622010/123895516-87b26480-d992-11eb-95eb-cccd172a9c24.png)
访问任意一个https网站报错：
![image](https://user-images.githubusercontent.com/47622010/123895549-9567ea00-d992-11eb-9c65-66f42499e597.png)
但是如果把SwitchyOmega配置为http代理，则http和https的流量都能正常访问，并且能够抓到https的包并能查看内容：
![image](https://user-images.githubusercontent.com/47622010/123895688-cb0cd300-d992-11eb-892d-73e78588f381.png)
为什么会出现这样的情况呢？

2.
作者是怎样查看https的包内容的呢？我试了使用node隧道代理可以直接转发但是不能查看内容,开启一个https服务又不能用request事件监听代理的https流量。

十分感谢

**Comment by avwo** [comment]
![image](https://user-images.githubusercontent.com/11450939/123900405-97827680-d99b-11eb-835d-866de96c5165.png)
https://wproxy.org/whistle/webui/https.html

**Comment by xihangzhou** [comment]
> ![image](https://user-images.githubusercontent.com/11450939/123900405-97827680-d99b-11eb-835d-866de96c5165.png)
> https://wproxy.org/whistle/webui/https.html

我已经按照文档添加了根证书了。我的问题是为什么对于https的请求在switchOmyga中也要配置为http的代理协议而不能配置为https呢？

**Comment by xihangzhou** [comment]
在mac下如果全局代理https流量就可以。。这个可能是switchyOmega的原因
![image](https://user-images.githubusercontent.com/47622010/123910049-7d9d5f80-d9ac-11eb-8094-f90c6c6c7487.png)

**Comment by avwo** [comment]
代理协议和请求协议不一样，http 代理协议可以代理 http、https、websocket、http2、及 tcp 请求。

**Comment by alanhg** [comment]
> 代理协议和请求协议不一样，http 代理协议可以代理 http、https、websocket、http2、及 tcp 请求。

1. Whistle暴露的是代理协议+端口，即HTTP代理服务器。
2. Mac下的HTTP代理/SOCKS代理，我理解是按照请求协议分吧，假如只配置了HTTP代理，按理应该是不会代理WebSocket协议把，我理解还需要开启SOCKS，毕竟WS的底层协议还是TCP。

以上理解下，做测试发现，假如系统代理只配置了HTTP/HTTPS，没有配置SOCKS，还是可以正常捕获到WebSocket请求及RULE规则处理。


这么来说我这里的理解有误，请指教。
