### ISSUE TITLE
whistle拦截HTTPS是怎么实现的呢？

### ISSUE THREAD

**Issue by xihangzhou** [avwo/whistle#596]
请问作者大大是怎么样用node实现对于HTTPS的拦截并查看其内容的呢？我阅读了推荐的原理文章https://imququ.com/post/web-proxy-2.html，但是这个文章中对https的代理并不能生效。。。

**Comment by avwo** [comment]
这篇文章写得很清楚了，请求流程：https 请求 -> tunnel 代理 -> https server

**Comment by xihangzhou** [comment]
如果使用 tunnel 代理 的话只是建立了TCP连接并直接转发，那怎么拿到其中的HTTPS内容呢？

**Comment by avwo** [comment]
直接拿到的是加密后到数据，需要通过中间人解开，具体实现看下 Whistle 的源码。
