### ISSUE TITLE
想使用reqMerge协议，想替换请求body的某个字段的value，只能针对字符串类型的value才能操作吗？

### ISSUE THREAD

**Issue by xiaowanzixll** [avwo/whistle#597]
比如请求body是json格式{debug:false}

设置规则为：
请求url reqMerge://(debug=true)
结果请求的body：{"debug": "true"}

如果想替换value值false改成true，还有别的实现方式吗？

**Comment by avwo** [comment]
试试 `reqMerge://({debug:true})`

**Comment by xiaowanzixll** [comment]
谢谢！试了一下reqMerge://({debug:true})，确实可以哦，只是不太理解这种写法，没看到帮助文档有介绍。

**Comment by avwo** [comment]
`key=value` 是类似请求参数的写法，Whistle 把 value 都当成字符串，`{key:value}` 这个是 json 对象，直接 JSON.parse 出来的，具体参考，https://wproxy.org/whistle/data.html
