### ISSUE TITLE
动态脚本编程/whistle.mid (http-middleware-proxy)

### ISSUE THREAD

**Issue by lolimay** [avwo/whistle#598]
whistle 已经内置了很多协议，但是协议终归是有限的。对于一些特殊需求（如对服务端返回的数据进行二次加工处理或对请求参数进行某种特定的变换），这类动态的需求使用协议的规则去描述还是过于繁琐。

因此想借助 whistle 的插件能力实现一个 http-middleware-proxy（HTTP请求中间件代理）。其原理如下

```
client -> request -> [midModifiedRequest] -> targetServer -> response -> midModifiedResponse -> client
```

## 用法

预期的用法大概如下：

### 手动添加
1. 首先在 rules 中添加一条新规则

```bash
www.test.com/xxx mid://{test.mid.js}
```

2. 其次在 values 中新建一个新文件 `test.mid.js`

内容模板如下:

```javascript
exports. default = {
  // 在这里处理原 request 对象
  // 然后返回修改后的 request
  req(req, options) {
    console.log('proxy req', req)
    return req
  },
  // 在这里处理原 response 对象
  // 然后返回修改后的 response
  res(res) {
    console.log('proxy res', res)
    return res
  }
}
```

### 自动添加

或者在请求列表中的邮件菜单新建一个列表项，选中一个请求右键显示如 Action - Add Middleware Script，来自动为 `host/path` 添加中间件脚本。

## 实现

但是在具体实现时，还是遇到了很多困难。比如下面这个实现

```javascript
exports.server = (server, options) => {
  server.on('request', (req, res) => {
    const proxiedReq = middleware.req(req, options)
    const client = proxiedReq.request((svrRes) => {
      const proxiedRes = middleware.res(svrRes, options)
      proxiedRes.pipe(res)
    })
    req.pipe(client)
  })
}
```

会导致请求阻塞，还请大佬给予帮助，谢谢！

**Comment by avwo** [comment]
1. 看下是哪行代码阻塞了请求
2. 要把响应状态码和响应头也透传回去 `res.writeHead(svrRes.statusCode, svrRes.headers);`

**Comment by avwo** [comment]
参考插件实现：https://github.com/whistle-plugins/whistle.script
