### ISSUE TITLE
如何模拟ws推送消息delay x秒

### ISSUE THREAD

**Issue by Lstoryc** [avwo/whistle#599]
RT，尝试过 resDelay 并没效果

**Comment by avwo** [comment]
这个只对建立连接生效，想要操作里面推送数据有以下两种方式：
1. 插件实现：https://wproxy.org/whistle/plugins.html
2. 手动操作
![image](https://user-images.githubusercontent.com/11450939/124733645-f8cfba00-df46-11eb-8f3d-c17f4fc64c09.png)

**Comment by Lstoryc** [comment]
额 可能我没说清楚，
其实我需求是这样子：模拟ws弱网情况 -> 后端返回的ws心跳， 我想让他延迟几秒再收到

**Comment by avwo** [comment]
明白你的意思，需要等插件支持才行

**Comment by avwo** [comment]
用这个插件 https://github.com/whistle-plugins/whistle.script
