### ISSUE TITLE
为什么readme中的option说明里有-r参数，实际工程中却没有？

### ISSUE THREAD

**Issue by Nukker** [avwo/whistle#6]
需要持续集成进行使用，每次要替换rules文件，想用-r参数进行指定，为什么发现clone下来的工程没有这个功能呢？版本是V0.10.1
![image](https://cloud.githubusercontent.com/assets/3293510/16010836/8044eeaa-31b5-11e6-9f08-d42f51f263eb.png)

**Comment by avwo** [comment]
后来的版本把这个去掉了，可以通过在自定义插件的根目录加一个rules.txt文件，whistle加载插件时会自动加载这里面的规则（如果要动态修改rules.txt，记得要修改下package.json，比如加个时间字段`mtime`，这样whistle才会重新加载插件），可以参考：[自定义插件](https://github.com/avwo/whistle/wiki/%E8%87%AA%E5%AE%9A%E4%B9%89%E6%8F%92%E4%BB%B6)
