### ISSUE TITLE
服务端不主动关闭连接时，302无法跳转

### ISSUE THREAD

**Issue by kasonyang** [avwo/whistle#600]
**问题描述：**

服务端返回302状态码和Location，但是服务端没有主动关闭连接，使用whistle代理时，浏览器无法正常跳转。

不使用whistle代理则可以正常跳转。

**复现：**

不使用whistle代理，访问`http://kason.site:6680/redirect-test`会自动跳转到`kason.site`。

使用whistle代理，无法跳转。

**Comment by avwo** [comment]
这个 url 是你们业务的吗，响应有点问题，响应流没触发 `end` 事件，如果是的话让你们运维看下？
浏览器应该做了特殊处理，我这边试下能不能兼容处理。

**Comment by kasonyang** [comment]
我是在访问第三方站点时遇到的，里面的链接是我为了方便演示写的测试例子。


我的理解是，出现这个问题，主要是因为，服务端已经把头部信息返回来了(但是没有主动关闭连接)，但是whistle没能即时地把这些头部信息返回浏览器。

**Comment by avwo** [comment]
下个版本修复这个问题。

**Comment by avwo** [comment]
更新下 Whistle
