### ISSUE TITLE
默认配置存在安全性问题

### ISSUE THREAD

**Issue by kasonyang** [avwo/whistle#605]
whistle安装完后，默认支持通过非本地环回地址访问，在同一局域网内，可以通过IP打开他人的whistle管理界面，并修改他人的配置，配合whistle的url重定向到文件功能，在知道文件路径的情况下，可以通过构造规则随意访问他人机器上的文件，存在信息泄露的风险。

**Comment by avwo** [comment]
启动时可以加用户名密码  `w2 start -n test -w 123` 或者限定访问 ip，`w2 start -H 127.0.0.1`

**Comment by kasonyang** [comment]
对用户来说，如果没意识到这个风险的存在，应该更倾向于使用默认配置。
在没有指定H参数的情况下，默认只能通过127.0.0.1访问，会不会更好一些

**Comment by kasonyang** [comment]
还有是否可以支持ui和代理使用不同的H参数呢？有时候用户可能想只对外提供代理功能，但是不想对外提供ui

**Comment by avwo** [comment]
默认绑定 `127.0.0.1` 增加用户使用复杂度，会给一般用户带来更多的困扰；特殊用户可以通过设置用户名密码、防火墙、绑定指定网卡等方式限制其它人访问

**Comment by T97-coffee** [comment]
我觉得局域网默认能够访问是whistle的优点，在团队项目的场景非常灵活
