### ISSUE TITLE
The way for Linux import cert globally. Linux 全局导入证书的方式

### ISSUE THREAD

**Issue by cathaysia** [avwo/whistle#606]
According to https://www.archlinuxcn.org/ca-certificates-update/, for a globally impory for linux, just put cert file in `/etc/ca-certificates/trust-source/anchors/` , and then run `trust extract-compat` to update cert db.

Chinese 
根据 https://www.archlinuxcn.org/ca-certificates-update/, 可以通过将 cert 放到 `/etc/ca-certificates/trust-source/anchors/` ，然后执行 `trust extract-compat` 的方式将证书导入到全局

**Comment by avwo** [comment]
提个pr ，补充到文档里面 https://github.com/avwo/whistle/blob/master/docs/zh/webui/https.md

**Comment by cathaysia** [comment]
这个我没法找到帖子的确切时间，因此可能具有有限的适用范围，这个方式在 Archlinux 上测试通过，但是在 Fedora 34 上就变成了另外一个路径： `/etc/pki/ca-trust/source/anchors`，而且上述路径失效了。我需要一些时间在更多的发行版上做一些测试。为了方便起见，我只会在 docker 里做测试，通过检查 `trust list|grep whistle` 的结果来验证正确性
