### ISSUE TITLE
【BUG】多行配置语法不起作用

### ISSUE THREAD

**Issue by lolimay** [avwo/whistle#609]
![image](https://user-images.githubusercontent.com/32427260/127265688-06239e78-6b8d-4010-8097-9d14d7b5cb2a.png)

Node: v13.14.0
Whistle: v2.7.7

---

希望能支持 `\` 换行语法，如：

```bash
operatorURI pattern1 \
    pattern2 pattern3 \
    pattern4 \
    pattern5 pattern6 pattern7 \
    pattern8-part1 \
    pattern8-part2 \
    parttern9
```

这样在正则的时候只需根据行尾有无 `\` 来进行拼接，最后拼成单行配置即可。

**Comment by avwo** [comment]
上面的语法不支持吗

**Comment by lolimay** [comment]
不知道，比如 

```
line`
operatorURI pattern1
pattern2 pattern3 pattern4
`
```

则，只能识别出 pattern1

**Comment by avwo** [comment]
``` txt
line`
operatorURI pattern1
pattern2 pattern3 pattern4
`
```
等价于
``` txt
operatorURI pattern1 pattern2 pattern3 pattern4
```
我这边可以正常识别啊，把你的具体规则贴出来看下

**Comment by lolimay** [comment]
```
line`
service.example.com/a/openapi/c enable://gzip
statusCode://200 resCors:// resBody://{body.json} resHeaders://{headers}
`
```

**Comment by lolimay** [comment]
BTW，用插件解决了，对于这种复杂需求还是自己写插件更灵活一点。

**Comment by avwo** [comment]
> ```
> line`
> service.example.com/a/openapi/c enable://gzip
> statusCode://200 resCors:// resBody://{body.json} resHeaders://{headers}
> `
> ```
这个配置没问题，当然插件也可以，有个地方改下 `resCors://` -> `resCors://*`
