### ISSUE TITLE
没有走系统的DNS缓存，导致大量的DNS服务器请求

### ISSUE THREAD

**Issue by lndj** [avwo/whistle#61]
我们部署在公司内网的服务器，导致了对DNS服务器大量的请求，请问为什么没有走本地的DNS缓存？

**Comment by avwo** [comment]
这个是用Node自带的dns模块，估计默认配置没走你们自己的dns服务器，我看下能不能在Online里面提供个配置dns服务器的功能，

**Comment by avwo** [comment]
不对，它应该是直接请求dns服务器了，我看下怎么处理

**Comment by lndj** [comment]
嗯 应该是的，这边确认是没有走本地缓存，而且有个奇怪的现象。
![qqqq](https://user-images.githubusercontent.com/9111083/29460298-05cabb0c-845a-11e7-89fb-ef6cb094b1a2.png)
竟然绕过了第一个。。。

**Comment by lndj** [comment]
![11](https://user-images.githubusercontent.com/9111083/29460439-8b9e9974-845a-11e7-8451-1d1d9a0f1a98.png)
比较奇怪的是，竟然绕过了第一个....

**Comment by avwo** [comment]
周末更新个版本更改下whistle的dns缓存策略

**Comment by avwo** [comment]
[更新下whistle](https://avwo.github.io/whistle/update.html)：原来的DNS缓存有个定时任务去更新，所以发现DNS请求会比较多，v1.5.3版本开始去掉这个逻辑，改为缓存30秒，且可以通过启动参数  `w2 restart -c 60000`  来设置缓存的毫秒数
 ``

**Comment by lndj** [comment]
棒！ 试下先 。

**Comment by lndj** [comment]
嗯，试了下，缓存确认生效了。但是有个奇怪的问题，如图：

![image](https://user-images.githubusercontent.com/9111083/29566295-eb0d2e10-877b-11e7-810b-42531beb0502.png)

上面红框的地方，貌似每次请求dns服务器，都会成对抓到包，`ipv6` 和 `ipv4` 都是一样。

难道是 `node` 的 `dns` 模块的问题？

**Comment by avwo** [comment]
发出的端口都一样，看似是同一个请求，自己用原生node的DNS模块试下看看

**Comment by lndj** [comment]
再问下，缓存的的-c 的毫秒数貌似不是严格的按照这个来过期的？

**Comment by avwo** [comment]
会有几秒的误差

**Comment by lndj** [comment]
Thanks!

**Comment by forrestchang** [comment]
@avwo 新版本 `-c` DNS 缓存被干掉了，怎么解决？

**Comment by avwo** [comment]
一直支持的，时间单位是ms

**Comment by forrestchang** [comment]
@avwo 我看了一下代码，发现是支持的，但是文档上面没有更新。
