### ISSUE TITLE
如何在请求响应头中添加原始 Remote IP

### ISSUE THREAD

**Issue by HelKyle** [avwo/whistle#613]
使用 whistle 之后，Chrome Dev Tool 中的请求会展示 `Remote Address: [::1]:8899`，我想在请求 Response Header 中添加一个 x-remote-address 字段来标记请求经过 whistle 之后，`remote address` 是什么，这样就可以快速判断出请求代理配置是否生效。 而不是每次要去 Whistle 的 Network 面板查看。

看了文档，没找到正确的操作值，发 issue 求助大佬。

**Comment by avwo** [comment]
用类模板字符串：
```
* resHeaders://`x-remote-address=${serverIp}`
```
https://wproxy.org/whistle/data.html

**Comment by T97-coffee** [comment]
Great, that's what I want too

**Comment by alanhg** [comment]
没用模版字符串的话，


Network里哪里可以看到remote address了？
![image](https://github.com/avwo/whistle/assets/9245110/3f81738f-b61f-4403-8dd7-9c03286ea799)

**Comment by avwo** [comment]
看下 Overview 匹配到规则了吗
