### ISSUE TITLE
 http://rootca.pro  无法访问，iOS无法配置证书描述文件怎么处理

### ISSUE THREAD

**Issue by note4** [avwo/whistle#614]
http://rootca.pro 
 
 感觉这个网站没有运营了

`ping: cannot resolve rootca.pro: Unknown host`
 
 各位iOS设备是怎样装上证书的？

**Comment by avwo** [comment]
要先配 Whistle 的代理，才能访问

**Comment by note4** [comment]
> 要先配 Whistle 的代理，才能访问

可以了，谢谢大佬


应该是手机配置问题，电脑映射的局域网地址，iphone打不开 android 可以打开。但是iphone换了个wifi去访问那个局域网地址又可以了
