### ISSUE TITLE
通过插件解析请求并回显如何不影响实际请求？

### ISSUE THREAD

**Issue by TechToArt** [avwo/whistle#615]
请求使用了自定义的协议，为了方便调试，想用插件解析成可读的json形式，如何在不影响原始请求的情况下将解析后的json显示到whistle，参考example中的代码，但是会影响实际请求
https://github.com/whistle-plugins/examples/blob/master/whistle.test-server/lib/server.js

比如`res.end(body.toString('base64'));`，会把实际请求结果编码并显示，有没有办法不影响实际请求情况下将编码后的结果进行显示

**Comment by avwo** [comment]
参考：https://github.com/whistle-plugins/examples/tree/master/whistle.test-pipe

**Comment by TechToArt** [comment]
> 参考：https://github.com/whistle-plugins/examples/tree/master/whistle.test-pipe

感谢，已解决
