### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:8888

### ISSUE THREAD

**Issue by NuoHui** [avwo/whistle#617]
```
From: whistle@2.7.14
Node: v14.16.1
Date: 8/17/2021, 11:21:29 PM
Error: connect ECONNREFUSED 127.0.0.1:8888
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)


Reload this page
```

请问是什么原因

**Comment by avwo** [comment]
`127.0.0.1:8888` 服务没起来，或者换个本地 ip 访问看看

**Comment by zangbianxuegu** [comment]
或者改为 localhost:端口号 试试

**Comment by zouyunchong** [comment]
我也遇到了这个问题

**Comment by Qiaooowo** [comment]
因为你的::1:3333 没有起来  ::1默认指向了ipv6地址 应该你在启动项目的时候的host设置为了ipv4的<-loopback> 也就是0.0.0.0 而并没有监听ipv6的地址  你可以试试把host直接改成 ::1来同时监听v4和v6

> 我也遇到了这个问题 ![57BEFA1E-57C7-4F6A-828F-9E7E096F2F35](https://private-user-images.githubusercontent.com/56156285/321071082-49f3033a-4797-47e4-9b01-5f904810cd93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTUyMzYyMjEsIm5iZiI6MTcxNTIzNTkyMSwicGF0aCI6Ii81NjE1NjI4NS8zMjEwNzEwODItNDlmMzAzM2EtNDc5Ny00N2U0LTliMDEtNWY5MDQ4MTBjZDkzLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTA5VDA2MjUyMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI2OGI4OTQyMzE1ZTBhM2Y0MmE1NzE3ZDVmOGNjZTNjOTU5NTY2Mzg0Zjc1MzliOWUxZmY3MGY0MjRlYzE4MmMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.QOICA_qyk9zzfMHNxUGzjFWCGu0g5IPiSSxLDe_o-BU) 我的代理规则是 http:localhost:xxx 把localhost 改为本机ip, http:127.0.0.1:xxxx 即可

**Comment by w17612745587** [comment]
![image](https://github.com/avwo/whistle/assets/81396526/4de23c81-46ed-4eef-b301-96bdaa4e703d)

这个问题怎么解决啊，已经按照文档安装好证书了

**Comment by w17612745587** [comment]
```
From: whistle@2.9.71
Node: v20.12.0
Date: 2024/5/24 16:44:12
Error: connect ECONNREFUSED 127.0.0.1:8087
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)
    ```
    已经按照文档安装证书了，如何解决呢

**Comment by Qiaooowo** [comment]
> ```
> From: whistle@2.9.71
> Node: v20.12.0
> Date: 2024/5/24 16:44:12
> Error: connect ECONNREFUSED 127.0.0.1:8087
>     at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1605:16)
>     ```
>     已经按照文档安装证书了，如何解决呢
>     
>     
>     
> ```

看着是本地服务没起来
