### ISSUE TITLE
现在能不能导入在线hosts，然后可以定时自动更新？

### ISSUE THREAD

**Issue by syymo** [avwo/whistle#619]
类似于switchhosts的在线导入功能

现在能不能导入在线hosts，然后可以定时自动更新？

**Comment by avwo** [comment]
https://wproxy.org/whistle/rules/@.html

**Comment by avwo** [comment]
可以通过以下方式动态导入远程规则（远程规则变了会自动实时更新）：
``` txt
@url
@localFilePath
```
