### ISSUE TITLE
手机连接代理资源加载特别慢，导致页面白屏

### ISSUE THREAD

**Issue by sunmaer** [avwo/whistle#620]
大佬辛苦帮忙看下这个问题可能是什么原因，困扰很久了！
手机：iPhone12
电脑：MacBook Pro 11.4
Node版本：14.17.3
whistle版本：2.7.11
正常配置代理后，电脑上打开页面正常，手机连接后资源加载特别慢，可以看截图，导致手机浏览器中打开页面白屏，一直打不开，本地开发JS体积也比较大，最大的有20MB，其他几百Kb，加载一段时间后其他资源都能加载，20MB的js似乎直接加载不出来，电脑上同样的资源都是正常的。
![image](https://user-images.githubusercontent.com/18280125/130001117-15eee23b-3d0f-4eed-92a9-dde9ead9350f.png)
最大的资源抓包显示这个，content-length字段显示文件也只有200多K，好像被截断了，耗时那里一直显示“-”。
![image](https://user-images.githubusercontent.com/18280125/130004102-0e0b0841-101c-41f4-b19b-39eff657fd13.png)
![image](https://user-images.githubusercontent.com/18280125/130003311-8f131033-9e73-4151-814a-a6782b97449d.png)

下图是chrome同个资源的抓包，就是正常的。
![image](https://user-images.githubusercontent.com/18280125/130004366-ffa1d57a-fc8a-4d18-8c0d-1b2b91173f16.png)

**Comment by avwo** [comment]
加载本地文件吗，规则怎配的？

**Comment by sunmaer** [comment]
> 加载本地文件吗，规则怎配的？

**Comment by sunmaer** [comment]
> 加载本地文件吗，规则怎配的？

不小心点关闭了。本地前端项目，加载本地开发JS资源，有一个JS特别大，20MB，这个JS在电脑上加载是正常的，手机连接代理加载就是图中那样，单独请求这个js是正常的，整个项目里加载就不对，是因为超时吗，大佬

**Comment by avwo** [comment]
用电脑访问页面加载正常，手机访问加载很慢，是这样吗？

**Comment by avwo** [comment]
这个文件发我看下

**Comment by sunmaer** [comment]
> 这个文件发我看下
好的，大佬，我用手机连其他同事的whistle代理访问这个页面是正常的，是我的电脑开了什么限制吗
[vendor.1fcc75da.js.zip](https://github.com/avwo/whistle/files/7011818/vendor.1fcc75da.js.zip)

**Comment by avwo** [comment]
把 Whistle 的抓包也导出来看下

**Comment by sunmaer** [comment]
> 我这边长度计算是正常的，把 Whistle 的抓包也导出来看下

其他项目试了下正常，应该是这个项目的问题，我自己再看看，麻烦大佬了
