### ISSUE TITLE
Debug 模式下启动出错

### ISSUE THREAD

**Issue by xuchaobei** [avwo/whistle#622]
vscode 中，通过 「JavaScript Debug Terminal 」，执行启动命令，会在下面代码截图的分支中返回，导致启动无法正常完成。

debug 代码发现，记录error 的文件中的内容为：**Debugger attached.**  看起来是把命令行中输出的这条debug信息也认为是错误信息了。

![image](https://user-images.githubusercontent.com/5110783/130976609-1829b4fe-b498-4f67-8453-41e1805f5712.png)

**Comment by xuchaobei** [comment]
> ```js
> execSync(`./node_modules/whistle/bin/whistle.js  start  --port=8899`);
> ```
> 
> 改成
> 
> ```js
> execSync(`./node_modules/whistle/bin/whistle.js  run --inspect  --port=8899`);
> ```

试过，不起作用。
因为问题出在 ```./node_modules/whistle/bin/whistle.js``` 这个模块内的代码运行过程中。 上面的这种加--inspect 改法，只能影响  ```./node_modules/whistle/bin/whistle.js``` 这个模块的代码执行完成后的其他代码的运行模式，例如后续的请求被代理的相关代码，会处于 debug 模式运行。

**Comment by avwo** [comment]
判断下如果程序处于 debug 模式改用内联的方式引入 Whistle：
``` js
const isDebug = process.execArgv.some((cmd) => {
   cmd = cmd.split('=', 1)[0];
   return cmd === '--inspect' || cmd === '--inspect-brk';
});
if (isDebug) {
  require('whistle/bin/whistle');
} else {
  execSync(`./node_modules/whistle/bin/whistle.js  start  --port=8899`);
}
```

**Comment by xuchaobei** [comment]
> ```js
> require('whistle/bin/whistle');
> ```
`require('whistle/bin/whistle');` 这种使用方式无法传递 start  port 这些命令或参数吧？

**Comment by xuchaobei** [comment]
> 判断下如果程序处于 debug 模式改用内联的方式引入 Whistle：
> 
> ```js
> const isDebug = process.execArgv.some((cmd) => {
>    cmd = cmd.split('=', 1)[0];
>    return cmd === '--inspect' || cmd === '--inspect-brk';
> });
> if (isDebug) {
>   require('whistle/bin/whistle');
> } else {
>   execSync(`./node_modules/whistle/bin/whistle.js  start  --port=8899`);
> }
> ```

`require('whistle/bin/whistle');` 这种使用方式无法传递 start  port 这些命令或参数吧？

**Comment by avwo** [comment]
> require('whistle/bin/whistle'); 这种使用方式无法传递 start port 这些命令或参数吧？

可以，试试看就知道，不行的话自己设置下 `process.argv`

> 另外，isDebug 的判断，在vscode的「JavaScript Debug Terminal」中测试了下，也是不行的，execArgv 参数为空数组。

自己找下其它可以标示 debug 模式的属性

**Comment by xuchaobei** [comment]
通过设置 `process.argv`， `require('whistle/bin/whistle')` 可以执行。但是程序还是会走到第一个评论中，代码截图红框中的分支，即：仍然会因为 errorFile 中有 "Debugger attached. " 的内容，而认为存在error。 这时候 whistle 实际已经启动起来了，只是config 中只设置了_pid 字段，而没有设置 pid 字段。 

现在问题来了，在启动 whistle  后，我的代码还会调用 `use` 命令来设置 代理规则，而`use` 命令执行时，会判断config.pid 是否存在，如果不存在就认为 whisle 没有正确启动，直接返回，进而导致 代理规则 无法正确设置。

看了下 `start` 命令的源码，判断 whistle 是否是运行态，会先判断 config.pid  ，pid 不存在，还会根据判断config._pid 去判断。 `use`命令是否应该也采用同样的判断逻辑呢？

**Comment by avwo** [comment]
为什么会有 errorFile，你是不是写了 `console.error(xxx)`，`w2 use` 的用法只能遵循它的规则，可以自己想办法适配。

**Comment by xuchaobei** [comment]
> 为什么会有 errorFile，你是不是写了 `console.error(xxx)`，`w2 use` 的用法只能遵循它的规则，可以自己想办法适配。

errorFile， 指的是第一个评论里，代码截图中的第93行的 `errorFile`。

写了一个 Demo 来说明这个问题，Demo 中有详细的复现步骤，以及基于前面的讨论尝试的解决方法。
[Demo](https://github.com/xuchaobei/whistle-test)

**Comment by avwo** [comment]
如何判断 vscode 的调试模式，看下 https://github.com/nodejs/node/issues/9617 里面的方法支持不，之前的代码稍微改下：
``` js
// 自动判断是否处于 debug 模式
if (isDebug) {
  process.argv.push('run', '--inspect');
  require('whistle/bin/whistle');
} else {
  execSync(`./node_modules/whistle/bin/whistle.js  start  --port=8899`);
}
```
