### ISSUE TITLE
DNS Lookup Failed

### ISSUE THREAD

**Issue by huanqingli** [avwo/whistle#623]
DNS Lookup Failed
From: whistle@2.7.14
Node: v16.4.1
Date: 2021/8/30 下午3:59:53
Error: getaddrinfo ENOTFOUND apms.test.shopee.io
    at GetAddrInfoReqWrap.onlookup [as oncomplete] (node:dns:71:26)

**Comment by avwo** [comment]
你这个域名就没配 dns：
![image](https://user-images.githubusercontent.com/11450939/131369476-9e1de5e9-d38f-468f-b6ad-43c37da462a8.png)

**Comment by Ticoco** [comment]
怎么配置DNS呢！

**Comment by avwo** [comment]
不太建议自定义，用默认的即可，如果确实需要可以通过启动参数 https://github.com/avwo/whistle/blob/master/CHANGELOG.md#v272
