### ISSUE TITLE
#怎么转义

### ISSUE THREAD

**Issue by Xfront-end** [avwo/whistle#624]
url中有#号  会被当成注释符号 怎么转义呢?

**Comment by avwo** [comment]
hash 只是给前端页面用的，请求到服务端的 url 不会带上 hash，你要做什么？

**Comment by MrTree-wq** [comment]
同上问，代理一个静态页面到另外一个使用了Vue hash路由模式的页面这种场景怎么处理？

**Comment by avwo** [comment]
hash 部分只是给浏览器用的，不会发到后台

**Comment by mDunH** [comment]
同问，我们的项目前端采用的是hash路由，期望正则中带 # 号的请求转发到本地，否则不转发。
如: /xxx.com(?:(\/#.*)?)/i localhost:8080$1
但这样写的话，#号被当成注释符号，导致不生效，这种情况能处理吗

**Comment by avwo** [comment]
url 里面的 hash 是不会发出来的，你可以通过 jsPrepend 或 jsAppend 往页面注入 js 实现相应的逻辑
