### ISSUE TITLE
win11 安装报错

### ISSUE THREAD

**Issue by undefined9999** [avwo/whistle#626]
w2 : 无法将“w2”项识别为 cmdlet、函数、脚本文件或可运行程序的名称。请检查名称的拼写，如果包括路径，请确保路径正确，然
后再试一次

**Comment by undefined9999** [comment]
node v12.22.6  npm v6.14.15  操作系统版本 22000.176

**Comment by avwo** [comment]
![image](https://user-images.githubusercontent.com/11450939/132280626-1e3ae320-f1b6-4422-9b9c-efbf25438b35.png)
