### ISSUE TITLE
麻烦支持下这种写法，或者其他内部实现方式

### ISSUE THREAD

**Issue by aogg** [avwo/whistle#628]
http://lartern.whistle/breakwa11/gfw_whitelist/master/proxy.pac https://raw.githubusercontent.com/breakwa11/gfw_whitelist/master/proxy.pac  resReplace://`{"127.0.0.1:1080":"lartern:3128","\"SOCKS5":"\"PROXY"}`

* pac://http://lartern.whistle/breakwa11/gfw_whitelist/master/proxy.pac

**Comment by aogg** [comment]
```
http://lartern.whistle/breakwa11/gfw_whitelist/master/proxy.pac https://raw.githubusercontent.com/breakwa11/gfw_whitelist/master/proxy.pac  resReplace://`{"127.0.0.1:1080":"lartern:3128","\"SOCKS5":"\"PROXY"}`

* pac://http://lartern.whistle/breakwa11/gfw_whitelist/master/proxy.pac

```

**Comment by avwo** [comment]
自己用插件实现，内部规则的请求不会走回到 Whistle。
