### ISSUE TITLE
有些 App 不能通过代理访问，这种情况有没有办法能抓包？

### ISSUE THREAD

**Issue by tumayun** [avwo/whistle#63]
比如陆金所，里面的一些核心请求是不能通过代理访问的，这种有没有办法能抓包？
我尝试了一个方法，就是由 PC 开启一个 WIFI，手机连 PC WIFI，然后请求陆金所。
但是 whistle 只能抓到 PC 的请求，而手机的请求却抓不到，好像是网口不一样，这个能解决吗？

谢谢！

**Comment by avwo** [comment]
**连PC的Wifi热点后，手机也要配代理。**

一般来说iOS App发出的http或https请求默认都会走系统代理，但可能某些Android App的http或https请求不会走系统代理，这种情况只能root Android系统后设置全局代理，如果是自家的App区分下正式版和开发版本，开发版本支持设置代理或默认走系统代理即可。

**Comment by avwo** [comment]
用 VPN 软件设置 http 或 socks 代理试试

**Comment by gaoshijun1993** [comment]
@avwo ios上目前使用shadowrocket来切换代理,新建/切换代理服务器都非常好用,安卓上试了很多都感觉不好用,要么是不支持手动配置,要么是都只支持ss/ssr协议,有推荐的安卓客户端吗?
