### ISSUE TITLE
【疑问】代理接口返回数据特别慢

### ISSUE THREAD

**Issue by lolimay** [avwo/whistle#631]
在 Overview 中，`显示 32006ms(HTTPS -> HTTP)`，具体代表的是什么含义？

![image](https://user-images.githubusercontent.com/32427260/133542739-9f8c1026-82da-433c-981b-adee213bb5cb.png)

**Comment by avwo** [comment]
Whistle 有个功能，如果请求配了 host，且用 https 访问时，如果检测到服务端不支持 https，会自动转成 http，你这里 443 端口响应太慢了，导致这个检测过程很长，两种解决方案：
1. 把链接改成 http
2. 配个规则，手动把 https 请求转成 http，类似：`ke.qq.com/path/to http://ke.qq.com/path/to`

**Comment by lolimay** [comment]
按照解法2，手动把  https 请求转成 http 后，发现 request sent 的时间仍需要 18 秒。

![image](https://user-images.githubusercontent.com/32427260/133545071-6782dd05-5a7d-4973-afae-d73ecfef85bf.png)

有啥进一步的调试思路吗？比如 `w2 run --inspect` 后，应该在哪个位置打断点可以分析出发送缓慢的原因呢？

**Comment by lolimay** [comment]
我的理解是，这 18011 ms 中其实 whistle 还没有真正地发送请求，服务器响应实际上只花了 38ms + 4ms = 42 ms？如果我错了，请纠正我。

**Comment by avwo** [comment]
这种无法调试，就是数据发送出去很慢，可能是网络问题，比如限流，或者服务端接收数据就很慢。

**Comment by lolimay** [comment]
找到问题所在了：https://github.com/avwo/whistle/blob/ad031d8655ad0afb8ddbfa1d48cc2cfd64d4166d/lib/inspectors/res.js#L506-L519

这里重试的时间太长了 `16000ms`（怪不得我每次的发送时间都是大概是 16s 的倍数），改成 `500ms` 甚至 `50ms` 可以解决我的问题。但这种解决方案很明显不是很优雅。

-- 

我有个想法，既然在我这种场景下，创建 Socket 连接的失败率很高，为何 `whistle` 不直接复用一个或多个 TCP 连接，搞个 TCP 连接池，直接从池子里拿空闲的连接收发数据是不是会提高性能？

我在代码中看到 keepAlive, http.Agent 相关的字眼，好像这个连接复用行为是受 req 中的 keep-alive 请求头控制的。而且大佬似乎也有点顾虑：

> ### v0.9.2
> 
> bugfix：修复keepAlive可能导致请求无法响应的问题
> 
>  // node 11及以上版本缓存连接有问题，先禁掉
>  disableAgent = disableAgent || config.debug;
>  config.httpAgent = disableAgent ? false : createAgent(agentConfig);


或许，我们可以尝试提供一个 `whislte` 配置，比如说：

```conf
ke.qq.com/some/path keepAlive://{{ maxSockets: 10, keep: 5 * 60 * 1000 }}
```

这样可行吗？

**Comment by avwo** [comment]
及时改成 http 请求，为什么你这边的 socket 连接还会超时？

**Comment by lolimay** [comment]
> 及时改成 http 请求，为什么你这边的 socket 连接还会超时？

对，我断点到这里，转 http 规则的确生效了，用的确实是 `http.request`。
