### ISSUE TITLE
[Feature Request] whislte 支持 verbose 参数或环境变量，显示性能数据

### ISSUE THREAD

**Issue by lolimay** [avwo/whistle#633]
![image](https://user-images.githubusercontent.com/32427260/133597699-4d7e385c-9ed9-4196-b0ac-7541d0d84d51.png)

这样在用户可以通过

```
VERBOSE=1 w2 run 或 w2 run --verbose
```

启动 whistle，每当 whistle 代理一个匹配中规则的请求时，可以在控制台直接打印性能数据。
一个可能的实现如下：

https://github.com/avwo/whistle/pull/632/files#diff-690601aa16ece35c1983ef810a10ad3a3be292a1b2732cc8dc3642f4709f1516R1

**Comment by avwo** [comment]
用途是什么？

**Comment by lolimay** [comment]
> 用途是什么？

方便调试，类似 vim 和 zsh 都有工具来 profile 启动时间。whitle 也可以尝试提供一个 verbose 模式来显示每个请求中各个模块占用的时间，这样在出现请求时间过长时，可以快速定位是哪个模块的问题。

**Comment by avwo** [comment]
可以支持，我先看下怎么做比较好。

**Comment by avwo** [comment]
侵入代码太多，界面 Network 已经提供了请求的所有性能信息，可以通过开发插件获取抓包数据并在 console.log 里面，或者看看有没有第三方库通过运行时自动注入代码的方式实现。
