### ISSUE TITLE
乱码

### ISSUE THREAD

**Issue by jlu1314** [avwo/whistle#634]
请求能够成功抓取到，但是得到的响应都是乱码怎么办？

**Comment by avwo** [comment]
看下响应的 `content-type`，链接发我看下

**Comment by jlu1314** [comment]
> 看下响应的 `content-type`，链接发我看下

你好，是这个样子的！新手求指点。
![image](https://user-images.githubusercontent.com/65208073/134203195-c7978f3e-02a4-455b-af9b-1d6389618e03.png)

![image](https://user-images.githubusercontent.com/65208073/134203362-17409c2b-de6a-4275-a788-5260410fd65d.png)

**Comment by jlu1314** [comment]
> 请求导出发我看下。

[music163.txt](https://github.com/avwo/whistle/files/7207417/music163.txt)

**Comment by avwo** [comment]
内容可能加密了

**Comment by jlu1314** [comment]
> 内容可能加密了

好的，知道了，谢谢！
