### ISSUE TITLE
[Bug] Rules 正则匹配时 group 匹配存在问题

### ISSUE THREAD

**Issue by charles8xu** [avwo/whistle#635]
复现方式：
1）设置如下规则
![image](https://user-images.githubusercontent.com/6831013/134011932-41fe6de6-dc05-472c-9dfa-1a392d5e1b5b.png)
2）输入地址后，匹配出如下结果
![image](https://user-images.githubusercontent.com/6831013/134012117-23469df1-d256-4199-a0ce-7945332bc23a.png)
3）如果组匹配结果分割展示，则结果正常
![image](https://user-images.githubusercontent.com/6831013/134012331-cca45ac5-80dc-4472-94a6-78e64f0412a3.png)
![image](https://user-images.githubusercontent.com/6831013/134012405-fc958e1c-92a1-4e9d-b544-97510cad7d50.png)

**Comment by avwo** [comment]
已修复，重新安装下 Whistle 并重启 `w2 restart`
