### ISSUE TITLE
修改post请求的request payload？

### ISSUE THREAD

**Issue by chaserstrong** [avwo/whistle#638]
如题，请教下如何实现？
尝试使用reqWrite，似乎不行呀

**Comment by avwo** [comment]
试试 https://wproxy.org/whistle/rules/reqMerge.html

**Comment by chaserstrong** [comment]
我是这样子的请求，似乎用reqMerge不行诶
![image](https://user-images.githubusercontent.com/18061322/134347186-6ef308c2-1282-481a-bb1d-7f8a52141cf7.png)

**Comment by avwo** [comment]
试试看就知道了，支持请求 `content-type` 为表单或 json 格式，也可以用 http://wproxy.org/whistle/rules/resReplace.html 或安装插件 https://github.com/whistle-plugins/whistle.script

**Comment by chaserstrong** [comment]
@avwo 我刚试了下，确实是可以的。不知道为什么上午不行。 感谢~~~
