### ISSUE TITLE
功能布局建议

### ISSUE THREAD

**Issue by tomtrije** [avwo/whistle#64]
1、online、offline按钮移动到最左边，然后做个分隔线和现有菜单分隔开来
2、把固定功能的菜单项居左对齐放在现有的菜单栏上
3、把二级菜单项（随着功能切换产生变化的）居右对齐放在现有的菜单栏上（占据原online按钮的位置）

好处：
1、认知清晰，一级功能都在左边，二级功能都在右边
2、online按钮与一级功能有定位差异，隔离开来有助于识别

望采纳更新！！

**Comment by avwo** [comment]
非常感谢，后面2.0会对界面做些调整，可以参考你的一些建议。

**Comment by avwo** [comment]
[重新安装下whistle](https://avwo.github.io/whistle/update.html)，左上角有个箭头，点击可以切换到左侧为菜单的布局方式

**Comment by tomtrije** [comment]
给力，哈，看你头像更新了，总算想起来你是谁了……我是饮空，可以加我微信（tomtrije）
