### ISSUE TITLE
请教一下如果 resReplace 需要替换的 key 本身包含 "=" 或者 " " 空格，表达式应该怎么写

### ISSUE THREAD

**Issue by HelKyle** [avwo/whistle#640]
举个例子，我想把 JS 文件中的 `window.webpackJsonp = window.webpackJsonp` 修改成 `window.myWebpackJsonp = window.myWebpackJsonp`。

不能直接使用 `resReplace://(webpackJsonp=myWebpackJsonp)` 因为我只想改这个文件里面赋值这里的 webpackJsonp key，不修改其他地方。

**Comment by avwo** [comment]
参考下这：https://wproxy.org/whistle/data.html

**Comment by HelKyle** [comment]
好的，多谢
