### ISSUE TITLE
mac 下 https 抓包代理后协议变成 h2

### ISSUE THREAD

**Issue by M-smilexu** [avwo/whistle#643]
电脑：MacBook Pro (13-inch, M1, 2020) 
系统：macOS Big Sur
版本：11.5.1

### 代理配置

![image](https://user-images.githubusercontent.com/943468/137426996-8dc24580-8342-4f29-a5c8-090ae00f7418.png)
![image](https://user-images.githubusercontent.com/943468/137427032-9424770c-c6cb-498b-82d2-6e8ccf0791f7.png)
![image](https://user-images.githubusercontent.com/943468/137427098-0edefb52-1edf-4e9d-9585-30dd59992021.png)

### 代理效果

![image](https://user-images.githubusercontent.com/943468/137427170-2fbc6f37-1c14-425e-bd31-3d50f6d72fcd.png)

### 问题

接口访问不成功，一直处于 pending 状态

**Comment by avwo** [comment]
重新安装最新版（`v2.7.29`） Whistle 并重启 `w2 restart`
