### ISSUE TITLE
Response-Body自动附加内容的问题

### ISSUE THREAD

**Issue by Mrqqeat** [avwo/whistle#645]
![1](https://user-images.githubusercontent.com/12445017/138278184-7c937268-4655-446d-93b0-274f233d6065.png)

正常是没有后面这段的，但是使用代理后请求结果就自动加上了这一段，没有使用任何规则，而且测试使用resBody等等也不行...，求助。。

**Comment by avwo** [comment]
配了 weinre，看下 Overview 里面匹配哪些规则
