### ISSUE TITLE
加个html的预览模式吧

### ISSUE THREAD

**Issue by aogg** [avwo/whistle#648]
![image](https://user-images.githubusercontent.com/8998031/138386693-d2eee29a-05c5-4bbb-8126-ff1f70fdda71.png)

**Comment by LeezQ** [comment]
> 直接用 iframe 引入担心对父页面有副作用，比如整个页面被替换掉，所以目前只能支持在新窗口打开预览。 PS：如果你有想到解决方案，可以提 pr 或分享下

针对安全性，可以用这个属性： https://developer.mozilla.org/en-US/docs/Web/HTML/Element/iframe#attr-sandbox

**Comment by avwo** [comment]
需要禁止脚本执行和一些meta标签，这么一限制大部分界面没法看

**Comment by avwo** [comment]
暂时无法实现原因参见：https://juejin.cn/post/6998541496945213477
