### ISSUE TITLE
升级到最新版后，weinre失效

### ISSUE THREAD

**Issue by hxlniada** [avwo/whistle#65]
升级到最新的whistle后，weinre几乎不能使用了
dom节点到达一定的层次后加载不出来：
无论安卓还是ios，都不好使
换了很多个测试机，刷了很多遍，结果都一样
<img width="437" alt="machi 2017-09-09 15-05-07" src="https://user-images.githubusercontent.com/3838586/30237984-6d4b78da-9570-11e7-8aaa-b749524195f1.png">

**Comment by hxlniada** [comment]
Is there anyone out there, can anyone here me?

**Comment by avwo** [comment]
是个bug，晚上发个版本修复掉，明天重新安装下whistle即可

**Comment by avwo** [comment]
[重新安装下whistle](https://avwo.github.io/whistle/update.html)

**Comment by hxlniada** [comment]
@avwo 感谢！！！但是更新后发现问题还在。。。

**Comment by avwo** [comment]
手动清下缓存

**Comment by hxlniada** [comment]
没问题了，真心感谢
