### ISSUE TITLE
192.168.1.108这种内网IP地址 match not work?

### ISSUE THREAD

**Issue by alanhg** [avwo/whistle#653]
```
/192.168.1.108/ www.baidu.com
/108.160.132.49/ www.baidu.com
```

本地配置以上两条rule，第一条不work，第二条OK

Version: `2.7.20`

试了下朋友的机器第一条也work，所以并非whistle本身BUG/版本，我的问题是whistle有什么设置会影响这种情况吗。

**Comment by avwo** [comment]
抓包看下 Overview 匹配到哪些规则

**Comment by alanhg** [comment]
> 抓包看下 Overview 匹配到哪些规则

奇怪的是，不work的这个请求我在network下没看到。
