### ISSUE TITLE
whistle会自动stop

### ISSUE THREAD

**Issue by thisLkk** [avwo/whistle#654]
描述：
w2 start 启动后，然后访问一些网址（如163、百度等等），发现已经掉线，执行w2 status 提示whistle未启动。重新start后再次访问这些网址又自动掉线。
版本：
node-12.6.0（另一台机器这个版本是可以的）
whistle-2.5.11(新版本也不行)
SwitchyOmega-2.5.21

辛苦提供下解决思路吧

**Comment by avwo** [comment]
看下启动目录有没有 `whistle.log` 文件

**Comment by thisLkk** [comment]
刚找了命令行启动的目录，未搜索到log文件哦，我先升级到最新版本再试试

**Comment by avwo** [comment]
Node版本也升级下

**Comment by thisLkk** [comment]
好，我试试先

**Comment by thisLkk** [comment]
升级node14.17.0可以使用。
不过我疑惑的是另一台电脑12.16.0是没有问题的呀，
不明所以

**Comment by avwo** [comment]
我这边试了 Node 12.6 没问题的，不过低版本的 Node 有些有问题，可以看下以前的 issue，建议 Node 和 Whistle 尽量采用最新版本

**Comment by thisLkk** [comment]
好的，谢了~
