### ISSUE TITLE
自定义插件无法使用

### ISSUE THREAD

**Issue by zhaoychehe** [avwo/whistle#655]
需求是自动保存抓包数据。
我打算自定义插件实现此功能，但是自定义插件只能在plugins列表看到，抓包时并不会调用插件代码。
使用[autosave](https://github.com/whistle-plugins/whistle.autosave)可以执行，但是当我修改autosave名字后(修改了文件夹名和package.json-name)，又无法使用了。
是我开发插件的流程有问题，还是使用插件的方式有问题

**Comment by avwo** [comment]
请求是否执行插件的 hooks，需要通过配置规则指定：https://github.com/whistle-plugins/whistle.autosave/blob/master/rules.txt

https://wproxy.org/whistle/plugins.html

**Comment by zhaoychehe** [comment]
> 请求是否执行插件的钩子，需要通过配置规则指定：https://github.com/whistle-plugins/whistle.autosave/blob/master/rules.txt 开发文档：[https://wproxy.org/whistle/plugins .html](https://wproxy.org/whistle/plugins.html)

修改了rules.txt规则后可以了。感谢^_^
