### ISSUE TITLE
[Feature Request] Rules URL能够保存选中rule

### ISSUE THREAD

**Issue by alanhg** [avwo/whistle#659]
> 希望选中任何一个rule，URL可以做到有状态保存，这样在基于此开发工具，或者分享给他人时，能够更方便些。，

http://127.0.0.1:8899/#rules?s=ruleName

## Version
- v2.8.2

**Comment by avwo** [comment]
可以通过插件实现，类似分享抓包数据，但需要一个公共存储服务。

**Comment by alanhg** [comment]
..你可能误会我的意思了。
我的诉求只是

http://127.0.0.1:8899/#rules?s=ruleName

**Comment by avwo** [comment]
https://local.whistlejs.com/#rules?ruleName=test

**Comment by alanhg** [comment]
> https://local.whistlejs.com/#rules?ruleName=test
偶，那解决了，不过 http://127.0.0.1:8899/ WEB服务有bug，选中不同的rule，URL没有该参数。因此我也就没注意有这个参的支持

**Comment by avwo** [comment]
这个参数要手动加

**Comment by alanhg** [comment]
> 这个参数要手动加

问题是别人怎么知道有这个参数，只能源码？不友好。

**Comment by avwo** [comment]
文档没更新上，本来就是给第三方扩展使用的，可以看下 Nohost：https://github.com/Tencent/nohost
