### ISSUE TITLE
考虑打包成electron应用么？

### ISSUE THREAD

**Issue by ihipop** [avwo/whistle#66]
我觉得的目前技术选型完全可以考虑使用electron构造应用，就差这一步就是一个完整的App，现在使用浏览器管理的话会影响我同时调试网页的代理选择，需要开多个浏览器

**Comment by avwo** [comment]
electron可以考虑，等把websocket的功能加上，再着手开发客户端，客户端的话不会是简单打包web版，会充分利用客户端特有的功能，关注whistle的动态，弄好了也会开源给大家使用。

**Comment by avwo** [comment]
https://github.com/avwo/whistle/issues/378
