### ISSUE TITLE
The file size cannot exceed 64m

### ISSUE THREAD

**Issue by qq2519157** [avwo/whistle#661]
fiddler导出的saz文件大于64M，导入到whistle的时候提示不能大于64M，有办法调整这个限制吗？
![image](https://user-images.githubusercontent.com/24367208/141748710-5eccefb4-b2ad-4907-a1d4-18002e8fffc9.png)
![image](https://user-images.githubusercontent.com/24367208/141748783-9461e196-769a-47ab-81ab-c9ec709a1877.png)

**Comment by avwo** [comment]
前端界面限制没调整，应该可以支持 128m，下个版本解决。

**Comment by qq2519157** [comment]
好的
