### ISSUE TITLE
ios wifi连代理，好像websocket没代理到？

### ISSUE THREAD

**Issue by B1anker** [avwo/whistle#662]
这个要怎么处理？

**Comment by avwo** [comment]
浏览器的 websocket 请求，还是 app 或小程序的？

**Comment by B1anker** [comment]
> 浏览器的 websocket 请求，还是 app 或小程序的？

ios safari发起的websocket请求
ios 15.1
whistle 2.8.4

**Comment by B1anker** [comment]
![image](https://user-images.githubusercontent.com/17514962/142375437-34d1b2f9-bad2-452d-ad8b-b259642737d2.png)
数据线连mac safari看console
![image](https://user-images.githubusercontent.com/17514962/142375529-d73294aa-db42-435f-9981-a10433f68bb9.png)
代理配置

**Comment by avwo** [comment]
规则启用了吗，抓包发我看下

**Comment by B1anker** [comment]
> 规则启用了吗，抓包发我看下

启用了呀，抓不到包。。

**Comment by B1anker** [comment]
![image](https://user-images.githubusercontent.com/17514962/142378626-5c2020e1-f28e-4167-acfe-ececc9a664e7.png)

**Comment by avwo** [comment]
导出抓包我看下，还有这个设置了吗：http://wproxy.org/whistle/webui/https.html

**Comment by B1anker** [comment]
![image](https://user-images.githubusercontent.com/17514962/142378882-6cf59fe9-a2b0-4a8a-a4f0-114dba714654.png)
点击连接没反应，whistle抓包也是空的

**Comment by B1anker** [comment]
设置的了，手机safari可以访问本地接口，就是websocket不行，也抓不到包
![image](https://user-images.githubusercontent.com/17514962/142379318-a812ae81-6db9-46be-b1ad-01e9aec0d94a.png)

**Comment by B1anker** [comment]
![image](https://user-images.githubusercontent.com/17514962/142403463-3d97e283-220f-4878-95ac-882b07ed30b1.png)
这个关掉就好了，知道为啥吗……？

**Comment by avwo** [comment]
关掉哪个？

**Comment by gongpeione** [comment]
关掉 NSURLSession WebSocket 可解，应该和 iOS 15 默认开启 WebSocket-Extensions: permessage-deflate 相关。
Apple 讨论帖：https://developer.apple.com/forums/thread/685403

**Comment by avwo** [comment]
这个暂时无解，看下其他人有没有解决方法。

**Comment by xywai1993** [comment]
我好想遇到了同样的问题 ，不过我是在微信里面访问页面 ，

**Comment by xywai1993** [comment]
> 我好想遇到了同样的问题 ，不过我是在微信里面访问页面 ，

规则如下：
ws://demo.com:3000/  ws://192.168.1.156:3000/

是我配置错了嘛

**Comment by avwo** [comment]
@xywai1993 你这个是怎么回事，可以抓到包吗

**Comment by xywai1993** [comment]
> @xywai1993 你这个是怎么回事，可以抓到包吗

在本地浏览器访问是可以正常抓到包的。但是在手机微信上访问，就没法抓到ws协议的包，其他HTTP协议都是正常的

**Comment by avwo** [comment]
可能是同一个问题

**Comment by gongpeione** [comment]
请问这个 issue 关闭是表示新版已经解决了么？

**Comment by avwo** [comment]
升级 iOS 版本看看，我们这边的 iOS15 抓 ws 请求是正常的，微信的 ws 请求抓不到可能有两个原因：
1. 不支持自定义证书
2. 不支持系统代理

**Comment by PluLongzhu** [comment]
> 升级 iOS 版本看看，我们这边的 iOS15 抓 ws 请求是正常的，微信的 ws 请求抓不到可能有两个原因：
> 
> 1. 不支持自定义证书
> 2. 不支持系统代理

我用whistle的plgin chii进行远程调试，ios15下他的ws请求就是有问题的。你可以试试。关闭NSURLSession 后safari可以，但是我们的app内的wkwebview不行。不知道有没有解决方案。

**Comment by Siubaak** [comment]
https://www.mobiledebug.com/Help/help_11075.shtml

**Comment by dabing1022** [comment]
我 hook 了WKWebView的 WKPreferences 类，把 NSURLSession WebSocket 实验特性关闭了

> > 升级 iOS 版本看看，我们这边的 iOS15 抓 ws 请求是正常的，微信的 ws 请求抓不到可能有两个原因：
> > 
> > 1. 不支持自定义证书
> > 2. 不支持系统代理
> 
> 我用whistle的plgin chii进行远程调试，ios15下他的ws请求就是有问题的。你可以试试。关闭NSURLSession 后safari可以，但是我们的app内的wkwebview不行。不知道有没有解决方案。

**Comment by avwo** [comment]
综上解决方法如下 ：
打开 **`设置 > Safari浏览器 >（底部）高级> Experimental Features > 关闭 NSURLSession WebSocket`**

<img width="803" alt="image" src="https://user-images.githubusercontent.com/11450939/218485268-d4f13ca8-e489-42fe-a088-b715f122270f.png">

**Comment by latel** [comment]
👍

**Comment by modood** [comment]
我之前通过 ios wifi 配 http 代理，始终抓不到 websocket  的包

后来通过另一种方式，启用 Socks5 代理完美解决，手机直接使用小火箭配置就可以了，再也不用到 wifi 里配置了。

$ whistle --socksPort 8898 start

{
  "type" : "Socks5",
  "host" : "172.16.0.52",
  "port" : 8898,
  "obfs" : "none",
  "plugin" : "none",
  "user" : "",
  "password" : ""
}
