### ISSUE TITLE
为什么我抓新浪旗下的“一直播”APP时，抓到的返回结果是乱码？

### ISSUE THREAD

**Issue by Phencxl** [avwo/whistle#663]
![yizhibo](https://user-images.githubusercontent.com/25873923/142834374-0f5dc9b2-2a84-44ea-ae15-4480d6fb3e12.png)

如图所示，我抓回来的包，返回结果怎么是显示乱码的？

**Comment by avwo** [comment]
内容应该处理过，可能做了加密

**Comment by Phencxl** [comment]
> 内容应该处理过，可能很好看

请问，有办法解密吗？我想抓取它的直播链接，再下载回本地。安卓逆向我没学习过。

**Comment by avwo** [comment]
如果知道是怎么加解密的，可以通过插件来解：https://github.com/whistle-plugins/examples/tree/master/whistle.test-pipe
