### ISSUE TITLE
用whistle 抓包以后，http1.1 变成了 http2

### ISSUE THREAD

**Issue by ycvcb123** [avwo/whistle#664]
### 1. 用whislte抓包
![image](https://user-images.githubusercontent.com/15381888/143181138-298a4169-2bf6-4430-9191-fc61428a5574.png)

### 2. 但是看抓到包的内容还是http1.1
![image](https://user-images.githubusercontent.com/15381888/143181235-e5f93fe4-64f7-41a3-ba93-4acc1a5cd01f.png)

### 3. 不用whislte抓包，就变回了http1.1，这是咋回事啊

![image](https://user-images.githubusercontent.com/15381888/143181352-a27a5ce1-398a-4143-99c6-da73964fefa7.png)

**Comment by avwo** [comment]
浏览器直接请求：HTTPS 请求会先检查服务是否支持 HTTP2，如果支持采用 HTTP2，否则降级为 HTTP1.1
经过代理的请求：HTTPS 请求会先跟代理建立连接（支持HTTP2），代理也会先检查服务是否支持 HTTP2，如果支持采用 HTTP2，否则降级为 HTTP1.1
所以会出现上述情况是正常，一般不影响使用。
