### ISSUE TITLE
includeFilter://resH:content-type=html不生效

### ISSUE THREAD

**Issue by imadentive** [avwo/whistle#665]
就是想只代理html文件，不影响接口。
完整规则如下：
https://xxx.com/h5/ file:///Users/xxxxx/dist/h5/ includeFilter://resH:content-type=html

**Comment by avwo** [comment]
没有请求到服务器怎么知道这个请求是否是 html 请求，可以用下面的规则试试：
``` txt
https://xxx.com/h5/ resBody:///Users/xxxxx/dist/h5/ includeFilter://resH:content-type=html
```

**Comment by imadentive** [comment]
> 没有请求到服务器怎么知道这个请求是否是 html 请求，可以用下面的规则试试：
> 
> ```
> https://xxx.com/h5/ resBody:///Users/xxxxx/dist/h5/ includeFilter://resH:content-type=html
> ```

谢谢，还是没用，我再其他方法试试。

**Comment by avwo** [comment]
`resBody` 不会自动补齐路径，可以用下面的方式：
``` txt
^xxx.com/h5/** resBody://`/Users/xxxxx/dist/h5/$1` includeFilter://resH:content-type=html
```

**Comment by imadentive** [comment]
> *

感谢，这次可以了，学习了

**Comment by imadentive** [comment]
> `resBody` 不会自动补齐路径，可以用下面的方式：
> 
> ```
> ^xxx.com/h5/** resBody://`/Users/xxxxx/dist/h5/$1` includeFilter://resH:content-type=html
> ```

感谢，这次可以了，学习了
