### ISSUE TITLE
mac配置开机自启错误。

### ISSUE THREAD

**Issue by joker77877** [avwo/whistle#669]
![image](https://user-images.githubusercontent.com/62642184/144958874-16338478-1cc1-4f7b-a39d-300a72825e89.png)
打开whistle App是报以上错误。

**Comment by echopi** [comment]
看起来是zsh的PATH没有whistle命令，你打开zsh之后，check一下。一般正确配置PATH是可以正常启动whistle的，我的操作步骤你参考下：

1. 可执行文件，保存为比如 `autostart.sh` ，然后 `chmod +x autostart.sh`
```sh
#!/bin/zsh
whistle start
```
2. zsh下，检查是否有`whistle` 命令，然后mac添加可执行文件到启动项
3. 重启验证
