### ISSUE TITLE
一个ip 对应多个域名  只有部分生效

### ISSUE THREAD

**Issue by jiangwenbo737** [avwo/whistle#67]
如标题描述，192.168.191.1  a.cc.com  b.cc.com  c.cc.com，ip一对多，只有b.cc.com生效，用switchhost修改系统代理则全部都能生效

**Comment by avwo** [comment]
我这里没问题，你访问后在whistle的Network截图我看下，请求有没有匹配到

**Comment by jiangwenbo737** [comment]
![timline 20170913102042](https://user-images.githubusercontent.com/5274985/30356801-a027b372-986d-11e7-8deb-b77f24853596.png)

**Comment by echopi** [comment]
线上页面能提供一个吗
