### ISSUE TITLE
Copy As CURL 功能在v2.8.7没有找到，还请明示

### ISSUE THREAD

**Issue by wangyuyan666** [avwo/whistle#670]

**Comment by avwo** [comment]
Network 右键菜单 Copy

**Comment by wangyuyan666** [comment]
> Network 右键菜单 Copy

![Screen Shot 2021-12-13 at 10 51 22](https://user-images.githubusercontent.com/10361664/145745876-517358d1-f482-4dfc-b78a-e2ddd0467c64.png)
不知道为什么我的右键菜单是这样 ，这是正常的么 ？

**Comment by avwo** [comment]
要在列表里面采用自定义菜单
![image](https://user-images.githubusercontent.com/11450939/145746187-bf4c5415-7b57-456e-9fa2-ececed0e84ed.png)

**Comment by wangyuyan666** [comment]
> 要在列表里面采用自定义菜单 ![image](https://user-images.githubusercontent.com/11450939/145746187-bf4c5415-7b57-456e-9fa2-ececed0e84ed.png)

抱歉，找了一圈没有找到这个设置，请问这个自定义菜单的设置路径是什么 ？谢谢

**Comment by wangyuyan666** [comment]
@avwo 
抱歉打扰，请问如何设置可以实现上面的操作菜单？已查阅文档及各种设置相关，均没有找到。🙏。

**Comment by avwo** [comment]
鼠标放抓包数据上面，你放菜单上做什么？

**Comment by wangyuyan666** [comment]
![image](https://user-images.githubusercontent.com/10361664/146345764-dfbb7e86-6597-429b-8619-8fb0651ea02b.png)
也是一样的

**Comment by avwo** [comment]
你这个是什么浏览器

**Comment by wangyuyan666** [comment]
![image](https://user-images.githubusercontent.com/10361664/146348462-6b9c7483-8356-4bc6-8c4e-451386644de7.png)
Mac mini M1

**Comment by avwo** [comment]
看下会不会是 Chrome 插件导致的问题

**Comment by wangyuyan666** [comment]
唉，确实是，油猴插件的问题！！！
