### ISSUE TITLE
当content-type是application/octet-stream;时，生成的curl没有二进制数据

### ISSUE THREAD

**Issue by BigGress** [avwo/whistle#671]
请问下，当application/octet-stream这种情况，能否提供直接下载shell文件？？然后把body带上

**Comment by avwo** [comment]
可以把内容先下载到本地文件，再通过 curl 请求
![image](https://user-images.githubusercontent.com/11450939/146139229-d4b475e2-acdd-4946-bb93-be4a0921570b.png)

**Comment by BigGress** [comment]
@avwo 找到方法了
curl -X POST <request_url >--data-binary "@/file_path/xxxx"
