### ISSUE TITLE
Response data too large to show

### ISSUE THREAD

**Issue by Su-yj** [avwo/whistle#672]
如果响应的数据太大无法显示内容，是否能提供启动参数或配置可以自定义这个值？
![image](https://user-images.githubusercontent.com/37967623/146318346-49661d05-9039-4f1c-b660-1d37c3ff8e5b.png)

**Comment by avwo** [comment]
这个内容有多大？

**Comment by Su-yj** [comment]
大概1M多到2M左右的数据

**Comment by avwo** [comment]
gzip 完还这么大吗

**Comment by Su-yj** [comment]
是的，数据有点多

**Comment by avwo** [comment]
有现网链接吗

**Comment by Su-yj** [comment]
不好意思，这个提供不了。不过这个是json的数据

**Comment by avwo** [comment]
ok，下个版本加个开关 `enable://bigData` 方便用户对个别请求开启显示大数据

**Comment by avwo** [comment]
重新安装 Whistle 试试

**Comment by kevnio** [comment]
> ok，下个版本加个开关 `enable://bigData` 方便用户对个别请求开启显示大数据

请问这个开关怎么开

**Comment by bitqiang** [comment]
> > ok，下个版本加个开关 `enable://bigData` 方便用户对个别请求开启显示大数据
> 
> 请问这个开关怎么开

`* enable://bigData`
