### ISSUE TITLE
最近总是出现connect和abort

### ISSUE THREAD

**Issue by CalotteNeo** [avwo/whistle#673]
最近抓包发现失败率很高，已经装了证书且enableHTTPS，但是有很多请求会突然变成connect
![企业咚咚截图20211222151705](https://user-images.githubusercontent.com/26112248/147051577-c2fb65a7-4551-40bb-8a24-dae8d4a29845.png)
而且有很多请求在本地就被abort了，是最近突然这样的，有没有遇到类似问题的uu们？
![企业咚咚20211222151909](https://user-images.githubusercontent.com/26112248/147051710-112da4c1-8717-4a3e-bfb9-b47b06be384d.png)

**Comment by avwo** [comment]
502 看下响应内容是什么

**Comment by CalotteNeo** [comment]
![image](https://user-images.githubusercontent.com/26112248/147061622-e488722b-ad7f-466b-a7d6-d8795b6b9324.png)
![image](https://user-images.githubusercontent.com/26112248/147061700-d0318fad-7697-4c16-82d6-fbe0f213e5bf.png)
现在看到有两种内容

**Comment by avwo** [comment]
这种是你本机的网路问题

**Comment by CalotteNeo** [comment]
噢噢，您的意思是网络情况较差连接超时导致的502报错吗。
那aborted的原因一般是什么呢？也是网络问题吗？

**Comment by avwo** [comment]
aborted 一般有两种情况：
1. 客户端主动 abort（刷新页面，或客户端判断请求超时等）
2. whistle 自动 abort（连接超时，这个时间比较长）
