### ISSUE TITLE
可否支持 透明代理 模式？

### ISSUE THREAD

**Issue by hhs66317** [avwo/whistle#674]
我尝试用于透明代理，发现不可行

**Comment by avwo** [comment]
怎么试的？

**Comment by hhs66317** [comment]
路由器上把访问 80 和 443 的请求都转到 whistle 的端口上，80端口的 http 请求都是可以处理的，但是 443 就不行了

**Comment by avwo** [comment]
要装根证书，或者**不要**开启 `Capture TUNNEL CONNECTs`

**Comment by hhs66317** [comment]
测试环境：
1、路由器下面两台设备A、B
2、A是windows系统，安装了根证书
3、B是linux系统，安装了whistle
4、路由器会把A发往TCP443端口的请求转发到B中的whistle端口
5、从A对https://www.baidu.com发起请求

结果，A中无法正常访问 https://www.baidu.com ，也不能在 Whistle 中看到相关请求（无论是否开启 Capture TUNNEL CONNECTs ）

**Comment by hhs66317** [comment]
@avwo 

补充信息：直接从A中的浏览器中设置代理为B，然后请求 https://www.baidu.com 是可以正常访问的，而且也可以在 Whistle 中看到相关请求。证书没有问题

**Comment by HOWIE-CH** [comment]
@hhs66317 @avwo   也试过了，请求都转到 whistle 的端口上， http 可以，https 不行了，不知道有什么解决方案没

**Comment by avwo** [comment]
https 报什么错

**Comment by HOWIE-CH** [comment]
报错哪里看呢，whistle.log 吗
现象是 https 的请求在 Whistle 抓包界面 Network 里没有，whistle.log 这里也没日志

**Comment by avwo** [comment]
请求正常且Network 抓不到包，那就是请求没转过来

**Comment by HOWIE-CH** [comment]
@avwo  客户端那边的 https 请求是失败的，没数据的

**Comment by avwo** [comment]
加个规则看看：`* disable://capture`

**Comment by HOWIE-CH** [comment]
Rules - Default 里加 * disable://capture   和  Network - HTTPS 不勾选 Capture TUNNEL CONNECTs
这两个也试过了，现象是一样的，客户端 https 请求失败，whistle 上没抓到 https 的请求

**Comment by avwo** [comment]
那是路由器配的有问题，你再看看

**Comment by HOWIE-CH** [comment]
- 推测的原因：参考了网上的帖子，端口直接转发，客户端发来的包的目的地址直接改了，到 whistle 这后，不知道真正要到达的服务器地址，（使用 charles 抓包，会有 invalid first line in request 的报错）
- 解决方式：在 whistle 之前加一层重定向，使用工具是 redsocks2，即端口转发到 redsocks2 然后再到 whistle，就可以正常透明代理抓取 https
    +  whistle 里 Network - HTTPS 不勾选 Capture TUNNEL CONNECTs 的话，抓取 https 大部分都是 tunnel://ip 地址的，勾选的话，大部分就是正常 https 的域名了，可以正常查看请求了
