### ISSUE TITLE
证书不同

### ISSUE THREAD

**Issue by WarlockFish** [avwo/whistle#675]
当我在linux 的 firefox95 上使用 whistle 时 ，我设置了一个我的域名指向我的内网，同时这个域名在公网有注册（使用了nginx反向代理，可以正常访问），当我使用firefox本地访问该http域名时，正常，但是在访问访问 “https”时 总是返回 

```
You are attempting to import a cert with the same issuer/serial as an existing cert, but that is not the same cert.

Error code: SEC_ERROR_REUSED_ISSUER_AND_SERIAL

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```
不使用 whistle 的端口代理时，可正常访问，并加载 Cloudflare, Inc 证书
在firefox和linux中按照教程都加入了rootCA.crt证书

使用edge和chrome 时，正常加载 wproxy.org 证书，并访问该域名

**Comment by Wave-SYJ** [comment]
我也遇到了类似的问题，在firefox上，一部分https域名会报出如下错误：

> 您正试图导入一个与已存在证书相同颁发者和序列号但却不相同的证书。
错误代码：SEC_ERROR_REUSED_ISSUER_AND_SERIAL

不同的是，在我这里的chrome上也会报错，且是对所有的https域名报错：

> 攻击者可能会试图窃取您的信息（例如：密码、通讯内容或信用卡信息）。
NET::ERR_CERT_AUTHORITY_INVALID

点击“继续前往”后依然会报这个错误。

这个问题似乎是最近才出现的。在一两个星期之前至少firefox上没有出现问题。

**Comment by avwo** [comment]
Firefox 需要单独安装根证书，看文档 https://wproxy.org/whistle/webui/https.html

**Comment by WarlockFish** [comment]
> Firefox 需要单独安装根证书，看文档 https://wproxy.org/whistle/webui/https.html
 ##
我在firefox中单独安装了证书，
![avatar](https://user-images.githubusercontent.com/30708115/147844211-88594695-f57f-464f-8e22-edd24700b36f.png)

**Comment by WarlockFish** [comment]
我测试了浏览器的全局代理，发现爱奇艺可以访问，但是 知乎 不能访问。对这两个网站没有设置规则。

![2022-01-01_13-05](https://user-images.githubusercontent.com/30708115/147844333-24cf4436-6c9e-4899-b4a3-e6977676138c.png)
![2022-01-01_13-02](https://user-images.githubusercontent.com/30708115/147844336-1c7918de-48fa-42bf-b5b3-556344492a34.png)

**Comment by Wave-SYJ** [comment]
尝试了一下发现从 2.8.9 降级到 2.8.8 可以解决我 firefox 的问题，不过 chrome 依然没有解决。

**Comment by avwo** [comment]
重新安装下 Whistle，用最新版本 `>= v2.8.10`

**Comment by WarlockFish** [comment]
更新到 `2.8.10` 后，目前上述的`https`连接可以正常访问。
