### ISSUE TITLE
能否加一个配置同步功能

### ISSUE THREAD

**Issue by smartlii** [avwo/whistle#682]
现在在多个终端使用这个功能， 但是在某一端进行代理配置改动的时候，再另一端不能同步，时间长的话差异会非常大。 每次改动如果通过导出导入的方式的话，非常非常非常麻烦。

**Comment by avwo** [comment]
可以把配置放在一个远程服务并通过以下方式引入规则：

``` txt
@http://xxxx/path/to
```
参考：https://wproxy.org/whistle/rules/@.html

**Comment by smartlii** [comment]
> 可以把配置放在一个远程服务并通过以下方式引入规则：
> 
> ```
> @http://xxxx/path/to
> ```
> 
> 参考：https://wproxy.org/whistle/rules/@.html

感谢回复，虽然可以一定程度上解决问题， 但是操作的路径和成本还是很高的，后续是否可以有计划增加用户唯一标识来一键同步配置呢？

**Comment by avwo** [comment]
这个需要一个中间服务器，工作量不小，以后再看看，你也可以通过插件实现手动同步：https://github.com/whistle-plugins/examples/tree/master/whistle.test-sync
