### ISSUE TITLE
新建账号配置环境的https的 Capture TUNNEL CONNECTs不可选

### ISSUE THREAD

**Issue by tmacMcGrady** [avwo/whistle#685]

**Comment by avwo** [comment]
Nohost：https://github.com/Tencent/nohost ？

**Comment by tmacMcGrady** [comment]
嗯 我在nohost创建了新的账号 然后切换环境的时候 页面请求不到https的静态资源 js文件等502

**Comment by avwo** [comment]
Nohost 上考虑到这些账号是公共的，防止全局开启影响到其它用户，建议采用在环境里面配规则开启捕获：`* enable://capture`
