### ISSUE TITLE
[Feature] whislte values script support CommonJS modules

### ISSUE THREAD

**Issue by bilibiliou** [avwo/whistle#689]
When I write a rule `resScript`, I wanna `require`  node common modules which like `fs`, `os` etc
But current isnt support me to require modules

**Comment by bilibiliou** [comment]
![image](https://user-images.githubusercontent.com/12696061/151651063-39a0b604-425d-43a5-9925-b73b7589b707.png)

**Comment by avwo** [comment]
https://github.com/whistle-plugins/whistle.script
