### ISSUE TITLE
希望能支持纯数字ip到另一个ip的转发代理

### ISSUE THREAD

**Issue by RobertWu-TIBCO** [avwo/whistle#69]
非常感谢该工具！
此前公司一直使用Fiddler和Charles —— 特殊情况下也会使用Nginx或SSH（反）代理来完成一些任务（比如不同环境的切换）。
一直希望能做的更好。所以看到whistle就特别想试试。

这里提一个需求 ： "希望能支持纯数字ip到另一个ip的转发代理"， 举例说明下。
例子一： 公司大数据又一次问我，hadoop管理界面上显示的ip和href是172.17.x.x，直接点击跳转当然有问题，每次手动替换很麻烦啊，有办法没。（当时想过nginx直接返回302 url 以及它的http substitution模块和自定义油猴子脚本）
此处需求即可解释为配置好代理后，发往172.17.x.x的所有请求默认转发到一个公(当前局域网)网ip（如101.200.x.x）。
例子二：项目中有多个数据库地址，api地址，测试时都是公网ip，上线时是生产环境的局域网ip。如何能避免修改生产项目中的ip来做线下测试呢？

比如，试了下这样的rule来尝试例子一的答案，但Network详情收到Nginx 404错误 ：
host://101.200.x.x 172.17.0.13

不知道这样的需求是否广泛。但是感觉如果这样的需求都被加进来了，用好这个工具，处理很多代理相关的任务真的是如虎添翼了（比nginx，ssh能做的还要多了）！

**Comment by avwo** [comment]
这个配置 host://101.200.x.x 172.17.0.13 是没问题，http://172.17.0.13这个ip的请求都转到10.200.x.x这台机器了，是不是10.200这台机器的ngnix不支持172.17.0.13这个host的请求

**Comment by RobertWu-TIBCO** [comment]
非常感谢解疑！

使用其他机器多次测试，证实如下配置可行：
host://www.xxx.com 172.17.0.13
host://60.205.xx.xx 172.17.0.13
可以满足上述所提需求。
感觉之前报错是转发到nginx后找不到对应的路劲服务。 对nginx得专门再测试下了。
