### ISSUE TITLE
文件下载乱码，content-disposition请求头中中文乱码

### ISSUE THREAD

**Issue by alongite** [avwo/whistle#690]
发现代理后content-disposition中的中文乱码，curl没有问题
代理后：
![image](https://user-images.githubusercontent.com/21084335/153565717-633765d6-f183-4e36-8aa7-679fddf27655.png)
curl：
![image](https://user-images.githubusercontent.com/21084335/153565935-518ad859-39a7-45ad-9962-87b8718b1387.png)

**Comment by avwo** [comment]
Node 请求头只支持Latin1字符，可以把内容 encodeURIComponent 试试
