### ISSUE TITLE
w2 start, info: Cannot start whistle owned by root,Try to run command with `sudo`

### ISSUE THREAD

**Issue by abigting** [avwo/whistle#691]
一开始一切正常，能正常使用，有一次在w2 start前面加了sudo， sudo w2 start 之后,之后的指令都需要我加 sudo（不想加，因为要输密码），如果不加，服务正常启动，但是会提示我没权限 请问怎么恢复？
![image](https://user-images.githubusercontent.com/31980543/153586340-721bf894-e56b-4a61-84ae-b85123ef6340.png)

**Comment by avwo** [comment]
`npm uninstall -g whistle` 卸载重装，或用 `chmod` 修改下相关文件的权限

**Comment by abigting** [comment]
非常感谢 问题已解决
