### ISSUE TITLE
w2 stop不生效

### ISSUE THREAD

**Issue by abigting** [avwo/whistle#692]
执行 w2 stop之后，http://127.0.0.1:8899/#network还是能访问
![image](https://user-images.githubusercontent.com/31980543/153603257-094e5544-49ea-499c-85fe-03bcae94ee8f.png)
![image](https://user-images.githubusercontent.com/31980543/153603477-38b422a6-8fa3-4517-94e8-88bf71b92984.png)

**Comment by avwo** [comment]
执行 w2 status 看看

**Comment by abigting** [comment]
![image](https://user-images.githubusercontent.com/31980543/153606541-869c474a-2ddf-466f-a9f5-b2c743f06c0c.png)

**Comment by abigting** [comment]
![image](https://user-images.githubusercontent.com/31980543/153607131-1b47d15a-fa3e-4f1d-bf4d-471f8f31398e.png)

**Comment by junyiz** [comment]
可以考虑在 w2 status 里把进程 ID 显示出来

**Comment by avwo** [comment]
更新下 Whistle：https://wproxy.org/whistle/update.html
