### ISSUE TITLE
whistle总是自己挂掉

### ISSUE THREAD

**Issue by 1057Sc** [avwo/whistle#698]
挂掉了也在默认目录和环境变量配的目录中找不到官网说的whistle.log，没日志不知道是哪里的问题没发排查是跟哪个程序有冲突了，

**Comment by 1057Sc** [comment]
#
# Fatal error in , line 0
# Check failed: U_SUCCESS(status).
#
#
#
#FailureMessage Object: 0x7ff7bfef57e0

使用w2 run 看到了输出了这个错误

**Comment by avwo** [comment]
这种是 Node 底层报错，Node 版本是什么，换个版本看看

**Comment by 1057Sc** [comment]
> 这种是 Node 底层报错，Node 版本是什么，换个版本看看

周五搜了下那个报错后就升级了一下node，之前是node12，现在是node17，目前没发现会挂掉的情况~
