### ISSUE TITLE
安卓12根证书设置后还是提示证书有问题，httpcanary的根证书就没有问题

### ISSUE THREAD

**Issue by MiniOcean404** [avwo/whistle#699]
安卓12根证书设置后还是提示证书有问题，httpcanary的根证书就没有问题

通过以下命令生成.0结尾的根证书，并使用adb推送到了安卓设备上，httpcanary的根证书就可以正常抓包，但是whistle转换的就不行
`$ openssl x509 -inform PEM -subject_hash_old -in rootCA.crt | head -1

$ cat rootCA.crt > 77e83b46.0

$ openssl x509 -inform PEM -text -in rootCA.crt -out /dev/null >> 77e83b46.0`

**Comment by avwo** [comment]
这个根证书是你自己生成的吗？

**Comment by MiniOcean404** [comment]
whistle的.crt结尾的证书是使用命令生成.0结尾的根证书，

httpcanary是这个软件可以自动就导出.0结尾的证书，不需要.crt转换.0

**Comment by MiniOcean404** [comment]
根证书 您说的根证书是不是.crt结尾的， 这个证书是我从whistle下载得

**Comment by MiniOcean404** [comment]
> 这个根证书是你自己生成的吗？

根证书 您说的根证书是不是.crt结尾的， 这个证书是我从whistle下载得


whistle的.crt结尾的证书是使用命令生成.0结尾的根证书，

httpcanary是这个软件可以自动就导出.0结尾的证书，不需要.crt转换.0

**Comment by avwo** [comment]
这两种后缀的证书格式是一样的吗？

**Comment by MiniOcean404** [comment]
他的错误是个证书过期的问题

**Comment by avwo** [comment]
错误信息贴出来看下

**Comment by MiniOcean404** [comment]
![浏览器](https://user-images.githubusercontent.com/54238499/155483648-ed5d0457-a8bc-49d3-9abc-872c471e7c25.jpg)
![系统凭据](https://user-images.githubusercontent.com/54238499/155483664-a972a654-5728-4942-8230-e9ce67b06cf1.jpg)
![报错](https://user-images.githubusercontent.com/54238499/155483675-c6dc6ba5-e1fa-4b9b-a8cc-91fe479dae9a.jpg)

安卓系统里设置了证书，代理提示还是过期

**Comment by MiniOcean404** [comment]
我用谷歌浏览器提示 证书不可信，有效期时间过长，我算了一下有11年有效期

**Comment by MiniOcean404** [comment]
但是httpcanary这个软件提供的证书 也是11年

**Comment by avwo** [comment]
你的 Whistle 是什么版本，老版本确实有这个问题，用新版版本试试

**Comment by MiniOcean404** [comment]
2.9.1 挺新的了，我升级一下2.9.2试试

**Comment by MiniOcean404** [comment]
最新版还是不行

**Comment by avwo** [comment]
看下 android 12 是不是对证书有效期时间做了调整，我找台 Android 机器看下

**Comment by MiniOcean404** [comment]
httpcanary 提供的证书是 颁发时间2021.2.23 有效期至 2032.2.21
whistle 提供的证书是 颁发时间2021.2.23 有效期至 2032.2.23

**Comment by MiniOcean404** [comment]
我试试fiddler的证书去

**Comment by avwo** [comment]
修改下你本地的 whistle 代码 https://github.com/avwo/whistle/blob/master/lib/https/ca.js#L485 ，新增下面一行代码并重启试试：
``` js
cert.validity.notAfter.setDate(new Date().getDate() - 2);
```

**Comment by MiniOcean404** [comment]
提示改变了   变成了：此网站的安全证书已过期或还未生效。建议关闭此网页

**Comment by avwo** [comment]
跟这个问题类似 https://github.com/avwo/whistle/issues/316 ，估计策略又变了，你用的是什么手机

**Comment by avwo** [comment]
> 提示改变了 变成了：此网站的安全证书已过期或还未生效。建议关闭此网页

要新增一行，不是替换

**Comment by MiniOcean404** [comment]
我是小米手机k30 pro miui13系统，并且安卓12 ， 刚刚我测试了一下fiddler也是同样的问题，证书过期

**Comment by MiniOcean404** [comment]
新增之后变成了提示：该网站的安全证书有问题

**Comment by avwo** [comment]
修改后的代码截图我看下

**Comment by MiniOcean404** [comment]
![image](https://user-images.githubusercontent.com/54238499/155495692-7fc77a22-2cb4-449e-9bf1-3250e6c23f6a.png)

**Comment by avwo** [comment]
Node 什么版本

**Comment by MiniOcean404** [comment]
node v16.14.0

**Comment by avwo** [comment]
> ![image](https://user-images.githubusercontent.com/54238499/155495692-7fc77a22-2cb4-449e-9bf1-3250e6c23f6a.png)

修改后用pc浏览器访问看下证书的日期是不是对的

**Comment by avwo** [comment]
加下 QQ 群：462558941

**Comment by MiniOcean404** [comment]
我今天算是莫名其妙好了，我写一下让别人看下吧。我昨天就把小米手机分身账户删了，并且小小米手机里有 清除凭证 清除了所有凭证之后今天上班再使用就好了，但是小米手机浏览器还是仍然提示安全证书有问题， 谷歌和微信里面的浏览器都是没有问题的
