### ISSUE TITLE
能否增加配置支持指定配置文件路径

### ISSUE THREAD

**Issue by zhangjh** [avwo/whistle#7]
有没有办法做到支持指定配置文件路径？
经常由于重装系统时忘记备份whistleAppData目录，导致配置的hosts文件重装以后全部丢失。
希望能够有自定义配置文件路径的功能。

**Comment by avwo** [comment]
通过配置环境变量`WHISTLE_PATH`指定目录看看

**Comment by zhangjh** [comment]
可以！
