### ISSUE TITLE
默认36s的超时设置难以定位问题

### ISSUE THREAD

**Issue by coolriver** [avwo/whistle#70]
whistle有个默认的超时时间(36s)，在调试慢速接口时，请求会被干掉，在浏览器上看到请求失败，并且返回内容为空。但是在whistle的抓包详情里有超时信息。即使这样，如果只看chrome network和接口日志的话，很难发现请求失败是由于whistle的超时机制。

建议是否能将whistle里的超时信息以合适的方式让chrome 的network里也能看到？

* whistle versoin： 1.5.8
* chrome console： 
![image](https://user-images.githubusercontent.com/4986245/30737296-b6ecafe8-9fb8-11e7-8dab-29797f3ef942.png)

* chrome network response/preview:
![image](https://user-images.githubusercontent.com/4986245/30737053-c7f4530a-9fb7-11e7-9f59-1fdb283466a0.png)
* whistle response: 
![image](https://user-images.githubusercontent.com/4986245/30737178-463808c4-9fb8-11e7-8f66-25ff0d046024.png)

**Comment by coolriver** [comment]
试了一下配置 disable://timeout 
请求还是在1min的时候返回错误，这时chrome的response里能看到whistle的信息了：
![image](https://user-images.githubusercontent.com/4986245/30737793-616083ea-9fba-11e7-8024-47d6e4740de2.png)

**Comment by avwo** [comment]
默认超时还是有必要，不然可能会导致某些域名的请求连接无法释放而不断累积，最后导致该域名的请求无法访问。

[重新安装下whistle](https://avwo.github.io/whistle/update.html)，新版本把默认超时改为 `1min` 与IE浏览器的默认超时时间同步，如果需要更长的超时时间可以设置  `disable://timeout`  或通过启动参数 `w2 restart -t 600000` 修改默认超时时间(单位：毫秒)
