### ISSUE TITLE
script里面可以访问http请求吗

### ISSUE THREAD

**Issue by Mrqqeat** [avwo/whistle#700]
比如使用reqScript的时候，可以在脚本里面使用http之类的请求吗，因为想通过其他接口拿取一些数据来进行替换请求参数。
或者可以使用扩展包什么的，直接访问sql拿取也可以。。
还有个问题就是在脚本里面修改了values后可以进行保存吗。。我好像没找到保存的方法(

**Comment by avwo** [comment]
用插件：https://github.com/whistle-plugins/whistle.script

**Comment by Mrqqeat** [comment]
> 用插件：https://github.com/whistle-plugins/whistle.script
谢谢！完美解决！
