### ISSUE TITLE
[BUG]MAC在Node v16.14.0时抓包请求都会abort

### ISSUE THREAD

**Issue by Jamorx** [avwo/whistle#701]
排查了一下午，node版本切换为14.17.1就可以正常用了

<img width="1277" alt="WeChat3daf63c0e74fe4ae2c887d7fa3fb94c4" src="https://user-images.githubusercontent.com/48875344/155947764-a464b256-2c44-4303-907d-f65945c491ae.png">

**Comment by avwo** [comment]
更新下 Whistle 版本
