### ISSUE TITLE
当whistle作为浏览器请求代理时，哪些HTTPS站点会显示为whistle签发的证书

### ISSUE THREAD

**Issue by alanhg** [avwo/whistle#703]
我理解应该是whistle rules命中的站点才会显示为走whistle签发的证书吧。

但是测试了下并不是，发现比如我自己的站点并没有match任何rule，但是提示也是whistle签发。

<img width="900" alt="image" src="https://user-images.githubusercontent.com/9245110/157655911-c86b73fb-982f-406c-8194-3b5c93b6bc12.png">

但多数网站，比如google这些，我看还是正确的，没有被替换。

<img width="484" alt="image" src="https://user-images.githubusercontent.com/9245110/157656009-7f0e3dbe-1fa8-4e74-b0ca-13cba2d729ae.png">

## 版本信息
1. Whistle 2.8.5
2. Chrome 99.0.4844.51
3. MacOS Big Sur 11.6

**Comment by avwo** [comment]
只要解开 https 请求都是用自定义证书，跟规则没关系。

**Comment by alanhg** [comment]
> 只要解开 https 请求都是用自定义证书，跟规则没关系。

没理解你这句话的意思，那图2的为什么不是whistle证书。

**Comment by avwo** [comment]
图2 的请求在 Whistle 的 Network 显示是 https 请求吗？
https://wproxy.org/whistle/webui/https.html

**Comment by alanhg** [comment]
偶懂你意思了。这里是我的问题，我这里这些没有显示为whistle证书的直接原因是没有走whistle代理。

不过延伸下这个问题，Web 反Mitm的技术，比如HPKP，现在因为各种原因，浏览器不支持。如果以后Web这块支持了，那这招就不好使了。
