### ISSUE TITLE
whistle@2.9.3 版本在 node 的 v16.14.0 版本的情况下几分钟就得重启一次 whistle，电脑系统：Mac M1，MacOs 12.2

### ISSUE THREAD

**Issue by zhengpq** [avwo/whistle#704]

**Comment by zhengpq** [comment]
如题，这两天遇到的问题，需要频繁重启，不然几分钟就会挂掉

**Comment by avwo** [comment]
把日志  `~/.WhistleAppData/whistle.log` 文件发我

**Comment by avwo** [comment]
为什么要重启？

**Comment by zhengpq** [comment]
一段时间后就会

`[!] No running whistle.`

**Comment by zhengpq** [comment]
> 把日志 `~/.WhistleAppData/whistle.log` 文件发我

没有找到这个文件的地址

**Comment by avwo** [comment]
看下是不是被防火墙烂了

**Comment by zhengpq** [comment]
> 看下是不是被防火墙拦了

我试了一下重装之后就没有这个问题了
