### ISSUE TITLE
可不可以支持 json 文件里写注释

### ISSUE THREAD

**Issue by JoeBBChen** [avwo/whistle#706]
如题。
然后用 [json5](https://github.com/json5/json5) 格式化一下，再作为 response。

**Comment by avwo** [comment]
这个不具备通用性，不适合内置到 Whistle 里面，可以通过自定义插件实现，或者用 https://github.com/whistle-plugins/whistle.script

**Comment by avwo** [comment]
更新 Whistle，试下插件：https://github.com/whistle-plugins/whistle.json5

**Comment by teal-front** [comment]
![image](https://user-images.githubusercontent.com/5626638/160781855-02547140-aaff-4d10-897e-1ad318c87f28.png)
