### ISSUE TITLE
挂载上公司的vpn之后  手机就抓不了包

### ISSUE THREAD

**Issue by Lumoas** [avwo/whistle#707]

**Comment by Lumoas** [comment]
没有使用公司vpn之前 重启后 就可以抓包 一登上vpn就废了 不知道哪里出了问题

**Comment by avwo** [comment]
请求被 VPN 拦截了吧，是用 chrome 插件设置的代理吗

**Comment by Lumoas** [comment]
不是 就是手机设置wifi 手动设置代理

**Comment by Lumoas** [comment]
关键是我使用vpn 电脑可以浏览器抓包 却不能手机抓包 不知道问题出在哪里

**Comment by avwo** [comment]
电脑：请求 -> HTTP 代理 --> Whistle -> VPN
手机（VPN 和 HTTP 代理运行在手机外无法同时生效）：
  1. 请求 -> VPN-> VPN 服务器
  2. 请求 -> HTTP 代理 -> 电脑的 Whistle

**可以采用：手机 -> HTTP 代理 -> 电脑的 Whistle -> VPN**

**Comment by Lumoas** [comment]
那就很奇怪了 我同事他们 vpn和手机代理都可以共存 且没问题

**Comment by Lumoas** [comment]
我只想 手机 -> 电脑Whistle -> vpn这3者共存 可以做到吗

**Comment by avwo** [comment]
电脑可以开 vpn

**Comment by Lumoas** [comment]
大佬 并没有解决我的问题啊 电脑开启了vpn 我的手机就抓包失败了额

**Comment by avwo** [comment]
系统问题自己网上搜看看

**Comment by jungled2014** [comment]
问题没解决就强行close？

**Comment by jacksplwxy** [comment]
> 问题没解决就强行close？

对啊，人家欠你的，还要手把手教学

**Comment by acfasj** [comment]
```
# 加条规则就好了, 比如 VPN 在 7890 端口
* socks://127.0.0.1:7890
```
