### ISSUE TITLE
nvm-windows 安装的nodev12.9.0. 开启http2的时候提示The current version of Node.js cannot support HTTP/2.

### ISSUE THREAD

**Issue by xcsweb** [avwo/whistle#708]
nvm-windows 安装的nodev12.9.0. 开启http2的时候提示The current version of Node.js cannot support HTTP/2.
我直接新建了一个js文件，require(“http2”)，都是可以的。
![image](https://user-images.githubusercontent.com/20693737/159398955-8e78ef21-77ed-452a-9b01-cbc4d8def379.png)

![image](https://user-images.githubusercontent.com/20693737/159399170-86b8c169-d500-47a3-ab99-559dddff5dc8.png)
![image](https://user-images.githubusercontent.com/20693737/159399197-c9b63edc-4535-47c6-a068-3dfce051eb58.png)

**Comment by avwo** [comment]
低版本 Node 的 HTTP2 模块不是很稳定，建议用最新的 LTS 版本

**Comment by kenan2002** [comment]
我用node16也提示这个

**Comment by kenan2002** [comment]
分享一下我解决的过程：

一开始使用node10启动的whistle，然后后面无论如何切换node，都提示这个错误。后来发现只要切到新版node后再执行一次 `w2 restart` 就可以了

**Comment by avwo** [comment]
低版本不影响使用，只是不支持 http2
