### ISSUE TITLE
响应内容是html文本(包括含js渲染内容等)时候难以阅读

### ISSUE THREAD

**Issue by ihipop** [avwo/whistle#71]
默认
![image](https://user-images.githubusercontent.com/423077/30898266-17c398f4-a38d-11e7-881e-b519a5ec0156.png)
只有Json/ RAW/ TEXT/IMAGE VIEW，是否考虑出个HTML view和postman一样做个简单渲染

**Comment by avwo** [comment]
这个可以支持，下周发个版本加个`Preview` tab项，用于预览html等数据的渲染效果

**Comment by ihipop** [comment]
@avwo 半年了，还是没有Preview

**Comment by avwo** [comment]
之前尝试做过，但有些问题解决不了，比如[https://ke.qq.com/](https://ke.qq.com/) 会防内嵌，并通过js判断是否在top窗口，不是的话会自动在top窗口打开，导致whistle界面被替换。

现在的whistle已经加入右键功能，可以通过右键在新窗口打开对应页面，看下能不能缓解问题，html页面预览估计得等客户端才能支持。

**Comment by ihipop** [comment]
#66

**Comment by avwo** [comment]
[更新下whistle](http://wproxy.org/whistle/update.html)

**Comment by ihipop** [comment]
@avwo 您好，这次更新只是加了一个超链接跳转一下了。并没有预览作用，比如如果对方是post的内容。

至于您说的 ke.qq.com 防内嵌，您下这个codepen

https://codepen.io/anon/pen/ParOaO

里面的html结构就是 ke.qq.com 的首页响应的html内容 但是好像可以正常在底下预览。没出错么。

他是怎么做到的？
