### ISSUE TITLE
微信小程序无法抓包的问题

### ISSUE THREAD

**Issue by Snailmar** [avwo/whistle#710]
如题，代理后，微信小程序无法抓包，也拿不到相应的请求结果，其他app可以正常抓包，之前可以的，突然就不行了，whistle版本为最新版本

**Comment by hongchengfhc** [comment]
你是不是这个没配置完 http://wproxy.org/whistle/webui/https.html

**Comment by he426100** [comment]
看这个
[https://www.jianshu.com/p/f87512ed7b21](https://www.jianshu.com/p/f87512ed7b21)
