### ISSUE TITLE
死循环

### ISSUE THREAD

**Issue by lindaJNlinda** [avwo/whistle#712]
vite 版本 2.9
whistle 版本2.9.5
项目启动时 300 端口
配置的rules 为  https://sv.test.co.id   http://localhost:3000

手机端配置证书和代理 访问  https://sv.test.co.id   页面不停的刷新

**Comment by avwo** [comment]
`http://localhost:3000/` 这个服务返回什么

**Comment by lindaJNlinda** [comment]
返回我的页面
