### ISSUE TITLE
[plugin]uiserver中获取不到URL中的查询参数

### ISSUE THREAD

**Issue by alanhg** [avwo/whistle#714]
比如`http://local.whistlejs.com/whistle.remote-rules?remoteRules=https%3A%2F%2Fgist.githubusercontent.com%2Falanhg%2Fa950d216121002d5bb0fd1278789da75%2Fraw%2Fc8bdf23e05c9dc504ea393a0b373cb556df911d8%2Ftest-whistle.js`

在router中打印，发现没有拿到完整路径及查询参数

![image](https://user-images.githubusercontent.com/9245110/162563860-6c546941-6a04-44d7-995c-941142e6d82a.png)

![image](https://user-images.githubusercontent.com/9245110/162563879-ef3c6cd6-25c8-4926-b02e-ec854a716d98.png)

**Comment by avwo** [comment]
上述是正常的，请到插件会自动去掉 `whistle.xxx` 即： `whistle.xxx/path/to` -> `/path/to`

**Comment by alanhg** [comment]
> 上述是正常的，请到插件会自动去掉 `whistle.xxx` 即： `whistle.xxx/path/to` -> `/path/to`

查询参数呢，我现在想拿到URL中的查询参数。

**Comment by alanhg** [comment]
> 上述是正常的，请到插件会自动去掉 `whistle.xxx` 即： `whistle.xxx/path/to` -> `/path/to`

明白了，另外比如

`http://local.whistlejs.com/whistle.remote-rules?remoteRules=https%3A%2F%2Fgist.githubusercontent.com%2Falanhg%2Fa950d216121002d5bb0fd1278789da75%2Fraw%2Fc8bdf23e05c9dc504ea393a0b373cb556df911d8%2Ftest-whistle.js`

需要换成
`http://local.whistlejs.com/whistle.remote-rules/?remoteRules=https%3A%2F%2Fgist.githubusercontent.com%2Falanhg%2Fa950d216121002d5bb0fd1278789da75%2Fraw%2Fc8bdf23e05c9dc504ea393a0b373cb556df911d8%2Ftest-whistle.js`

根路径需要多个/，否则查询参数拿不到

**Comment by alanhg** [comment]
@avwo 还想问下， ctx.redirect我想重定向到`http://local.whistlejs.com/#rules`，发现不work，这个也正常吗
