### ISSUE TITLE
是否有办法在转发地址返回 502 时，fallback 到另外一个地址？

### ISSUE THREAD

**Issue by xuqingkuang** [avwo/whistle#717]
类似 nginx 的 fallback 参数，当目标转发地址服务未开启时，自动 fallback 到一个保底的地址？

```
    error_page 502 = @fallback;

    location @fallback {
      proxy_pass https://fallback.com;
    }
```
-----
目前需求是一个微前端工程，有大量子工程，但是开发只会启动其中少部分子工程的本地开发服务，大部分微前端工程 fallback 到保底的测试环境服务上。

这个感觉写个 server 插件比较合适， 在第一次 res 返回 502 时，需要通过 req 再次发起到 fallback 的请求，但目前 req 和 res 都耦合在一起，所以问一下怎么写比较合适？

**Comment by avwo** [comment]
可以把本地 server 直接集成到插件里面，在插件判断是否存在相应的资源，如果没有则调用 `req.passThrough()` 直接放过请求

**Comment by xuqingkuang** [comment]
> 可以把本地 server 直接集成到插件里面，在插件判断是否存在相应的资源，如果没有则调用 `req.passThrough()` 直接放过请求

如果存在本地资源，才需要 req.passThrough() 否则要 fallback 到兜底资源

现在不太确定的是兜底资源的 req/res 怎么覆盖掉原来的 req/res，接回到 resRead 服务上去。

**Comment by avwo** [comment]
如何判断本地资源是否存在？

**Comment by xuqingkuang** [comment]
> 如何判断本地资源是否存在？

本地是数个 webpack-dev-server 的调试服务，不同服务占据不同端口。

whistle 里配置好指定的路径到既定的端口，访问该路径时，就通过 whistle 尝试访问该端口。

服务如果开着就会返回 200 状态码，直接转发本地 webpack-dev-server 提供的服务就行；

如果服务没开，端口自然连不上，就要 fallback 到插件配置的兜底测试环境服务。

**Comment by avwo** [comment]
这些都是 get 请求，req 对象可以直接复用，res 对象等资源响应成功再操作。

**Comment by xuqingkuang** [comment]
> 这些都是 get 请求，req 对象可以直接复用，res 对象等资源响应成功再操作。

有办法 复用 req 对象，让它对不同的 url 发起请求吗？

目前看 https://github.com/whistle-plugins/examples/blob/master/whistle.test-server/lib/server.js#L10 要发起不同的请求需要用 client = req.request()，但是最下面 req.pipe(client) 又导致它只能对一个 client 进行 pipe。
----
另外还发现一个问题，在:

```js
try {
   client = req.request(url, () => throw new Error());
} catch (err) {
  // 不会执行到此，错误无法捕获
}
```

**Comment by xuqingkuang** [comment]
技术方案可能不太合适，还是保持现有方案好了。
