### ISSUE TITLE
请教一下，关于whistle rule的配置api

### ISSUE THREAD

**Issue by tangzixuan** [avwo/whistle#718]
请问whistle的配置界面中的rule的配置，可以通过whistle plugin进行默认配置嘛，whistle plugin的哪个api可以做这个事情呐，谢谢

**Comment by tangzixuan** [comment]
![截屏2022-04-15 02 49 48](https://user-images.githubusercontent.com/51657124/163457442-73c9d6a4-a65d-4092-807a-0499558733b6.png)
比如，我想把 www.test.com的请求都经过我写的mock-plugin来处理，现在似乎都需要手动配置一下，可以通过plugin的哪个api去设置，从而省去手动设置这一步可以嘛，谢谢

**Comment by avwo** [comment]
https://blog.csdn.net/qiwoo_weekly/article/details/123516031
https://wproxy.org/whistle/plugins.html

**Comment by tangzixuan** [comment]
收到，谢谢啦，感谢老哥
