### ISSUE TITLE
跨域问题

### ISSUE THREAD

**Issue by huangguangpo** [avwo/whistle#719]
react项目，在本地启动后，项目中用的是接口是https ，在使用whitle进行对接口数据的拦截报跨域
![image](https://user-images.githubusercontent.com/54012665/163530918-d71db7f5-7547-411b-b409-749861b6bcd5.png)
![image](https://user-images.githubusercontent.com/54012665/163531013-d0c8066f-d33b-4a39-94d3-a5af78529fb0.png)

**Comment by avwo** [comment]
可以在这条规则后面加 `resCors://*` 试试
https://wproxy.org/whistle/rules/resCors.html
