### ISSUE TITLE
希望支持指定后台访问端口

### ISSUE THREAD

**Issue by huzuli** [avwo/whistle#72]
默认启动服务用 `w2 start`，对应代理端口是8899，后台访问可以用8899或8900端口访问。

如果启动服务指定端口 `w2 start -p 8888`，对应代理端口是8888，后台访问端口也是8888。

希望有类似-p的功能，也能指定后台的访问端口。

**Comment by avwo** [comment]
[更新下whistle](https://avwo.github.io/whistle/update.html)，支持通过 `-P 9999` 参数来设置whistle的UI端口( 其中：`P` 为大写，小写的为设置代理端口)
