### ISSUE TITLE
w2 start -f 怎么用呢

### ISSUE THREAD

**Issue by AFeyman** [avwo/whistle#720]

**Comment by AFeyman** [comment]
w2 start -f是不是可以设置filter过滤呢，但是格式怎么写的

**Comment by avwo** [comment]
没有 `-f`，要过滤什么

**Comment by AFeyman** [comment]
> 没有`-f`，要过滤什么

`w2` start[run] -f file.js`： 加载过滤抓包数据的脚本
没有这个用法吗，想要启动的时候把network的过滤规则加上，只监听某个域名的请求

**Comment by avwo** [comment]
`-f` 是用于修改抓包数据，`-r` 用于设置 shadowRuels（不在 Rules 界面上显示）、 Rules 和 Values：
``` 
w2 restart  -r "* enable://hide excludeFilter://www.qq.com"
```
