### ISSUE TITLE
[bug] 代理 EventSource 无法收到推送消息

### ISSUE THREAD

**Issue by komomoo** [avwo/whistle#721]
现象：代理 EventSource 无法收到推送消息，去掉代理直接请求 localhost 正常

whistle代理规则：
```
stream.test.com http://localhost:9100
```

前端代码：
```js
        const source = new EventSource('https://stream.test.com/es');  // 无法收到推送消息
        // const source = new EventSource('http://localhost:9100/es');  // 使用localhost可以正常收到消息
        source.onopen = function(e) {
            console.log('---连接服务器成功');
        };
        source.onmessage = function(e) {
            const data = e.data;
            console.log('---收消息：', data);
        };
```

前后端实现代码参考：https://www.ruanyifeng.com/blog/2017/05/server-sent_events.html

**Comment by avwo** [comment]
还设置其它规则没，比如修改响应内容的规则

**Comment by komomoo** [comment]
> 还设置其它规则没，比如修改响应内容的规则

没有了。代理后可以正常建立连接，但是无法收到消息

**Comment by avwo** [comment]
Whistle & Node 分别什么版本？

**Comment by avwo** [comment]
<img width="728" alt="image" src="https://user-images.githubusercontent.com/11450939/164277244-00e4a14c-2c25-4717-9051-ab7f682c2199.png">

**Comment by komomoo** [comment]
破案了，有```* proxy://127.0.0.1:12639```配置就收不到消息，去掉就正常了

**Comment by fanxiaopa** [comment]
大佬，怎么解决的呢，我也是加了代理就接不到消息。去掉代理直接调后端接口就行

> 破案了，有`* proxy://127.0.0.1:12639`配置就收不到消息，去掉就正常了
