### ISSUE TITLE
 sourcemap动态无法匹配

### ISSUE THREAD

**Issue by Evashasha** [avwo/whistle#722]
示例：
/^https:\/\/test\.wawa\.li\.com\/yo\/static\/js\/(.*)\.js/ jsAppend://`(//# sourceMappingURL=http://127.0.0.1:8080${url.path.replace(/yo\/static\/js\/(.*)\.js/ig,static/js/$1.js.map)})`

无法本地文件匹配然后调试

**Comment by avwo** [comment]
`#` 表示注释，可以通过 内嵌的方式，或者 Values，或者本地文件绕过注释：
````
``` sourceMappingURL
//# sourceMappingURL=http://127.0.0.1:8080${url.path.replace(/yo\/static\/js\/(.*)\.js/ig,static/js/$1.js.map)}
```
^https://test.wawa.li.com/yo/static/js/*.js jsAppend://`{sourceMappingURL}`
````

**Comment by Evashasha** [comment]
> `#` 表示注释，可以通过 内嵌的方式，或者 Values，或者本地文件绕过注释：
> 
> ```
> ``` sourceMappingURL
> //# sourceMappingURL=http://127.0.0.1:8080${url.path.replace(/yo\/static\/js\/(.*)\.js/ig,static/js/$1.js.map)}
> ```
> ^https://test.wawa.li.com/yo/static/js/*.js jsAppend://`{sourceMappingURL}`
> ```

解决了，谢谢大佬🌹🌹话
