### ISSUE TITLE
post无法代理到本地，一直在请求中....

### ISSUE THREAD

**Issue by jiangshanglong** [avwo/whistle#724]
本地开发需要mock数据，将/cgi/mock/xxx 代理到本地http://127.0.0.1:3008/cgi/xxx，
1.浏览器调试一直显示在请求中
![1650676543](https://user-images.githubusercontent.com/20588463/164849449-086a6647-ade7-4bf9-92d3-b2eb19b81b4e.png)

2.直接用postman访问是可以成功的
![企业微信截图_16506766959990](https://user-images.githubusercontent.com/20588463/164851765-2aeaed05-c5be-4835-b1bf-02a0ade6e835.png)

**Comment by avwo** [comment]
post 接口转发到你本地服务的 get 接口？需要通过 `method://get` 显式的把请求装成 get，不然 post 请求里面的 body 发送出去，请求就没法结束。

**Comment by jiangshanglong** [comment]
mock数据的时候，有get和post请求，get请求是没问题，能顺利代理到本地相应的get请求，而post请求的发现一直在请求中，刚上面你说“post 请求里面的 body 发送出去，请求就没法结束”，对于post请求，还需要我这边配置点什么吗？

**Comment by jiangshanglong** [comment]
> 



> post 接口转发到你本地服务的 get 接口？需要通过 `method://get` 显式的把请求装成 get，不然 post 请求里面的 body 发送出去，请求就没法结束。

是post请求代理到本地的post请求，post请求的发现一直在请求中，刚上面你说“post 请求里面的 body 发送出去，请求就没法结束”，对于post请求，还需要我这边配置点什么吗？

**Comment by avwo** [comment]
`url mockUrl method://get`

**Comment by jiangshanglong** [comment]
> `url mockUrl method://get`

刚试了下，同时需要将本地api-mocker中的方法改为get，整个流程就跑通了。如果可以，能直接支持post更nice了~~
感谢大佬！

**Comment by avwo** [comment]
> > `url mockUrl method://get`
> 
> 刚试了下，同时需要将本地api-mocker中的方法改为get，整个流程就跑通了。如果可以，能直接支持post更nice了~~ 感谢大佬！

这个不是 whistle 限制的，是 http 协议规定且跟目标服务器实现有关，可以通过 whistle 规则改请求方法：https://wproxy.org/whistle/rules/method.html
