### ISSUE TITLE
get the port of whistle's proxy server in the whistle's plugins

### ISSUE THREAD

**Issue by ElmiraNa** [avwo/whistle#725]
Hi, I have a problem the wish anyone can help me.

I want to access the number of the port of the proxy, via the test server's plugin or any other plugin,  But it seems that there is no ability for that.
PS: I do not mean the value of this variable (oReq.clientPort.).

**Comment by avwo** [comment]
https://github.com/avwo/whistle/blob/master/lib/plugins/load-plugin.js#L2463
