### ISSUE TITLE
是暂时还不支持 IPV6 的转发吗？

### ISSUE THREAD

**Issue by fjqingyou** [avwo/whistle#726]
本地电脑用 ssh -L 隧道转发的方式连接的服务器Ipv6地址的38899端口，会在本地监听一份 ::1:38899

然后 whistle 进行配置

 Rules 中配置:
 operatorURI proxy://{proxy_define}

 Values 中 proxy_define 配置:
 [::1]:38899
 
 我用chrome浏览器不通过whistle直接访问 http://[::1]:38899 是可正常访问的！

 如果浏览器通过whistle，访问 operatorURI 匹配的规则的url时，实际测试并未按预期通过定义的地址连接。得到了以下结果：

Overview
Method | CONNECT
Status Code |  502
Status Message | Bad Gateway
Client IP | 127.0.0.1
Client Port | 64516
Server IP | 127.0.0.1
Server Port | 这里是空白的
其他信息应该比较不重要就不列举了!

请问是还不支持 IPV6？还是我的用法有误？

**Comment by avwo** [comment]
支持，带端口的 ipv6 标准用法需要加 `[]`，如: `[::1]:38899`

**Comment by fjqingyou** [comment]
确认我已经是附带了 [] 方式的写法了，一下是我的配置截图

Rules：
![QQ20220428-165506](https://user-images.githubusercontent.com/31087168/165716259-649752f0-8662-455f-bed6-dee67a232921.png)

Values:
![QQ20220428-165521](https://user-images.githubusercontent.com/31087168/165716331-837f7ae0-e455-4a1e-9202-5e1c5824a059.png)

实际跑起来结果
![QQ20220428-165424](https://user-images.githubusercontent.com/31087168/165716203-fd8961b0-353f-4265-b0fa-6c96deca74ab.png)

如果直接访问的话
![QQ20220428-165731](https://user-images.githubusercontent.com/31087168/165716556-9efadc2e-0d97-4949-a030-a90cd6a4e7be.png)

**Comment by avwo** [comment]
我这边是可以正常代理，是不是你防火墙或网络问题（proxy 也可以写成内联的模式 ` proxy://[::1]:38899`）
<img width="1597" alt="image" src="https://user-images.githubusercontent.com/11450939/165719605-4b09acbd-6494-4bbe-a74d-876020089307.png">

<img width="866" alt="image" src="https://user-images.githubusercontent.com/11450939/165719698-d7fe50bd-8315-4238-bd1c-baa993272ce0.png">

**Comment by fjqingyou** [comment]
实验了下，似乎是 MacOS 下 127.0.0.1 和 ::1 并不是等价的。

用 127.0.0.1 地址访问端口和 ::1 访问端口不一样的结果，不确定是不是这个导致的？

![QQ20220428-172207](https://user-images.githubusercontent.com/31087168/165721449-1d1df7ba-4554-4357-b1d9-59c7973e4f18.png)

**Comment by avwo** [comment]
应该是，Whistle 把他们都当成 `127.0.0.1`
