### ISSUE TITLE
无法实现https的hosts配置功能

### ISSUE THREAD

**Issue by anchel** [avwo/whistle#728]
rule配置如下：
https://test.anchel.com https://42.194.252.128

浏览器访问如下地址：
https://test.anchel.com/

请求截图：
![image](https://user-images.githubusercontent.com/5762114/167089056-8e176e44-efd2-4ab6-8dae-3d1b6d3a8ff0.png)

我的需求是以https访问test.anchel.com的时候，转到 42.194.252.128 这个ip去。
实际的现象是，协议变成了H2，导致请求ip的时候返回错误

**Comment by avwo** [comment]
请求转发和配置 host 不一样，改成 `https://test.anchel.com/  42.194.252.128` 试试

**Comment by anchel** [comment]
> 
rule 改成：
https://test.anchel.com/ 42.194.252.128

访问：
https://test.anchel.com/

![image](https://user-images.githubusercontent.com/5762114/167091327-2b6ba389-8c9a-4012-b253-41ec62a2bebe.png)
这样还是不对的，我是希望仍以https协议去连接 42.194.252.128 这个ip

**Comment by anchel** [comment]
> 

我重新整理下我的描述，我是想要hosts配置的功能，也就是访问 test.anchel.com 的ip是我指定的ip，不是dns解析的ip。不是想要请求转发这个功能，即不是想要访问 https://test.anchel.com/aaa/bbb 的时候，把请求url变成https://42.194.252.128/aaa/bbb，因为42.194.252.128这个ip部署的是nginx，会根据http header里面的host做不同处理。

**Comment by avwo** [comment]
这种你原来的配置就可以，试下其它页面看看

**Comment by anchel** [comment]
> 

不行的，我原来的配置，或者是用标准的操作系统配置hosts的写法：42.194.252.128 test.anchel.com

访问 https://test.anchel.com/ 的时候
还是如下的情况：
![image](https://user-images.githubusercontent.com/5762114/167094609-a9df19a3-2275-4d50-8182-6c64f32eee59.png)

**Comment by avwo** [comment]
`https://test.anchel.com/ http://42.194.252.128/`

**Comment by anchel** [comment]
> 

这样还是不行的。whistle在请求42.194.252.128的时候，不是用的https协议，而且请求头部里面的host字段不是 test.anchel.com，而是 42.194.252.128，看样子whistle支持不了我的需求。多谢帮忙

**Comment by avwo** [comment]
肯定可以支持，自己先搞清楚原理：https://juejin.cn/post/6844904040006942727

**Comment by logan70** [comment]
> > 
> 
> 这样还是不行的。whistle在请求42.194.252.128的时候，不是用的https协议，而且请求头部里面的host字段不是 test.anchel.com，而是 42.194.252.128，看样子whistle支持不了我的需求。多谢帮忙

@anchel 这里有什么解决方案吗？我碰到相同问题，到了node服务都会降为http

**Comment by avwo** [comment]
你node 服务是https的吗？

**Comment by logan70** [comment]
> 你node 服务是https的吗？

@avwo 是的，因为一些原因，本地开发需要https。找到解决方案了，加上这个请求头就可以了，koa和express如果没有特殊配置 [代理信任](https://expressjs.com/en/guide/behind-proxies.html) 相关内容，都是可以的， @anchel 看看是否一样的场景

```
xxx.com reqHeaders://(X-Forwarded-Proto=https)
```
