### ISSUE TITLE
使用中遇到了手机 qq 中截图的消息加载很慢问题

### ISSUE THREAD

**Issue by fjqingyou** [avwo/whistle#729]
不确定当前问题是我这边的个例，还是其他环境也是必现。

# 环境
MacOS 12.2.1
whistle 2.9.13
Android  vivo S7
QQ v8.8.88.7830

Win10也试过，存在同样的问题

# 重现步骤
电脑中启动 whistle，并在防火墙允许了监听的端口输入请求

android 系统设置中 wifi 的代理配置http代理指向同局域网电脑的 whistle。

android 中登录QQ。

电脑中登录另外一个QQ号，跟手机中的QQ有好友关系、或者群友关系。

从电脑中任意截图一个区域，将截图发给android的QQ。大小无所谓。一两百*一两百的就够。我这边测试是 191*104 的尺寸

这时android的QQ收到一条图片消息。但是卡在加载中。而且这个加载会非常非常慢。平常不通过代理只要瞬间出现的图。现在可能需要加载几十秒。甚至几分钟才能加载完毕

已经确认过如果不设置代理，直连使用时相同尺寸的其他截图时，是正常地很快加载完毕的！

**Comment by avwo** [comment]
抓捕看下对应请求的响应时间

**Comment by fjqingyou** [comment]
能力有限。whistle中开启  Capture TUNNEL CONNECTs 抓包。没能定位哪个请求是属于截图消息的。也许不是简单的 http 请求。恐怕是 qq 自有协议包装的请求
因为抓包列表中出现的都是几百毫秒就最高了。然而未发送图片和等到图片手机已经接收到显示几十秒甚至一两分钟的。没发现这种高ms的请求出现在列表中

**Comment by avwo** [comment]
图片应是用 https 请求抓包看看，我用 iphone 试了 ok。

**Comment by fjqingyou** [comment]
我这边测试步骤
从 IPhoneX 发送给 android -> android 端图裂了，加载失败
从 android 发送给 IPhoneX -> IPhoneX 成功了，很快出来

win10 端登陆 android 相同qq，保持手机电脑同时在线。让他们能同步消息，然后电脑端发送给 IPhoneX -> IPhoneX 正常接收，然而 android 自动同步的消息，有自己发送图片的标记提示加载中，但是加载很久后，图裂了，又是失败

之后去掉IPhoneX 的代理环境，然后在 http://127.0.0.1:8899/#network 中，清除掉旧的所有记录。IPhoneX开始发送图片给有代理环境的android，不论是图片开始接收，还是等到了提示加载失败，在 #network  这个里面并未发现新的请求记录。确认已经开启了 ‘Capture TUNNEL CONNECTs’ 复选框。并且确认 android 的 wifi 设置正确的代理地址与端口

**Comment by avwo** [comment]
关闭 `Capture TUNNEL CONNECTs` 正常吗，是不是 ssl pinning 问题

**Comment by fjqingyou** [comment]
已经确认。关闭该功能复选框后测试。相同结果。

**Comment by avwo** [comment]
那就是你电脑网络问题

**Comment by fjqingyou** [comment]
然而关闭android的wifi配置的代理。再次测试会几乎瞬间就加载成功。所以网络本身应该是没问题的！

**Comment by fjqingyou** [comment]
win10 是移动宽带
MacOS 是电信宽带

我在这两个环境下测试是一致的结果！

**Comment by avwo** [comment]
更新下 node 和 whistle 版本看看

**Comment by fjqingyou** [comment]
win10、macos 测试相同结果！请求超时，图裂的结果！
```
node --version
v18.2.0

w2 start
[i] whistle@2.9.17 started
[i] 1. use your device to visit the following URL list, gets the IP of the URL you can access:
       http://127.0.0.1:8899/
       http://192.168.1.103:8899/
       http://192.168.56.1:8899/
       http://192.168.196.109:8899/
       Note: If all the above URLs are unable to access, check the firewall settings
             For help see https://github.com/avwo/whistle
[i] 2. set the HTTP proxy on your device with the above IP & PORT(8899)
[i] 3. use Chrome to visit http://local.whistlejs.com/ to get started

```

**Comment by fjqingyou** [comment]
两种情况都测试过。并未发现值得怀疑的http请求。

看来这个问题只能暂时先放置了！

**Comment by avwo** [comment]
> 关闭 `Capture TUNNEL CONNECTs` 正常吗，是不是 ssl pinning 问题

严重怀疑是这个问题，你再跟 qq 的开发对下
