### ISSUE TITLE
开启whistle后，苹果商店无法访问

### ISSUE THREAD

**Issue by sneptune-love** [avwo/whistle#730]
问题描述：开启whistle后，苹果商店无法访问

期望：可以正常访问苹果商店

**Comment by avwo** [comment]
在 Default 里面配个规则 `disable://capture **.apple.com **.mzstatic.com **.icloud.com **.icloud.com.cn` 试试

**Comment by sneptune-love** [comment]
这样配置就可以了，谢谢！

我之前尝试在filter里面加入这些规则，但是不生效...

**Comment by MrTree-wq** [comment]
我也遇到同样的问题，但是按照如上配置没有作用node:v10.9.0,whistle:v2.9.38,iphone:13,ios:16.1.2

**Comment by avwo** [comment]
试试：`disable://capture ***.icloud.com** ***.microsoft.com ***.office.com ***.office365.cn ***.apple.com**  **.mzstatic.com`

**Comment by MrTree-wq** [comment]
ok,感谢
