### ISSUE TITLE
whistle 对于post body请求参数的匹配规则支持吗？

### ISSUE THREAD

**Issue by hfutyezi** [avwo/whistle#731]

**Comment by avwo** [comment]
``` txt
pattern operator includeFilter://b:pattern1 [includeFilter://b:pattern2 excludeFilter://b:pattern3]
```
https://wproxy.org/whistle/rules/filter.html
<img width="942" alt="image" src="https://user-images.githubusercontent.com/11450939/167592846-43771665-f052-476e-baa5-a15320f8dc35.png">
