### ISSUE TITLE
Why did I upload the certificate, but iOS showed that the red letter was not verified when installing the certificate.

### ISSUE THREAD

**Issue by izhuolin** [avwo/whistle#732]
Why did I upload the certificate, but iOS showed that the red letter was not verified when installing the certificate.

**Comment by avwo** [comment]
<img width="845" alt="image" src="https://user-images.githubusercontent.com/11450939/167967283-e9f23936-fd22-4542-8d90-ebea9b24faad.png">

**Comment by izhuolin** [comment]
Thank you for your reply.
