### ISSUE TITLE
Apple silicon runtime issue

### ISSUE THREAD

**Issue by chenrui333** [avwo/whistle#734]
- `bin/proxy/mac/Whistle` got introduced in [this commit](https://github.com/avwo/whistle/commit/c59e38a42cbb6fec2b625d6ae369263da5fc1362)i, but the binary was only built for x86_64

relates to https://github.com/Homebrew/homebrew-core/pull/101645

**Comment by avwo** [comment]
What to do? in fact it also works on M1 Pro.

**Comment by SMillerDev** [comment]
It might work on M1 because of rosetta, but that is not the same as it being a native binary.

**Comment by avwo** [comment]
@SMillerDev How to ignore checking for this file？

**Comment by SMillerDev** [comment]
Homebrew won't ignore the file since it would be broken for anyone using an ARM Mac. You could remove the file in the formula on ARM though.

**Comment by avwo** [comment]
Are there any reference examples?

**Comment by avwo** [comment]
> Homebrew won't ignore the file since it would be broken for anyone using an ARM Mac. You could remove the file in the formula on ARM though.

Are there any corresponding examples for reference?

**Comment by chenrui333** [comment]
I just removed the x86 specific binary in the homebrew build per [this PR](https://github.com/Homebrew/homebrew-core/pull/124856)
