### ISSUE TITLE
当安卓客户端 以protocol 协议为 http时，向后端 发起 websocket 请求，出现问题

### ISSUE THREAD

**Issue by azhuang321** [avwo/whistle#736]
例如：
请求连接为 `http://www.example.com`
请求头为
```text
GET /index.html HTTP/1.1
Host: www.example.com
Connection: upgrade
Upgrade: example/1, foo/2
```
向后端发起websocket请求
用 whistle 抓包 protocol 显示为 http  后端服务 显示 此次连接 连接成功后马上断开

但是同样的 请求  以fiddler 抓包 是能够正常连接后端的websocket服务 不断开的

不知道作者大大能否排查一下原因呢

**Comment by avwo** [comment]
我这边怎么重现？

**Comment by azhuang321** [comment]
> 

稍等 我看能否写个demo

**Comment by avwo** [comment]
这个是你们自定义的协议吗？
<img width="300" alt="image" src="https://user-images.githubusercontent.com/11450939/170633843-776ee952-15af-4d6a-aa1e-0d75fe0124a9.png">

**Comment by azhuang321** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Protocol_upgrade_mechanism

**Comment by azhuang321** [comment]
主要是这个

**Comment by azhuang321** [comment]
> 这个是你们自定义的协议吗？ <img alt="image" width="300" src="https://user-images.githubusercontent.com/11450939/170633843-776ee952-15af-4d6a-aa1e-0d75fe0124a9.png">

协议没有自定义  这个是网上找的 协议升级的 头

**Comment by avwo** [comment]
改成 `websocket` 就ok

**Comment by azhuang321** [comment]
> 改成 `websocket` 就ok

用 rules 改吗 

我尝试过 似乎不行 应该是脚本写错了

**Comment by azhuang321** [comment]
我也尝试过 handleRequest  但是不能修改protocol  也没通

**Comment by avwo** [comment]
这个请求是 app 发出来的吗，app 上改下

**Comment by azhuang321** [comment]
> 这个请求是 app 发出来的吗，app 上改下

就是app发出来的  但是 app是另一个团队写的 不好为了抓包叫他们改，因为使用是正常的 加上fiddler 是正常的  所以不好修改
这个只是我要解码 websocket中的protobuf 写的

**Comment by avwo** [comment]
你把demo 给我，下个版本支持

**Comment by azhuang321** [comment]
> 

好的  我先写个demo

**Comment by azhuang321** [comment]
@avwo 给不了demo  我用node写 但是复现不出这个效果
只能给截图了
这个是fiddler 是正常的
![image](https://user-images.githubusercontent.com/63149232/170714563-aff05408-77ec-4319-b3c1-983717500d02.png)

这个是whistle 似乎是直接 aborted 这个请求  
![image](https://user-images.githubusercontent.com/63149232/170715379-4e89b33c-7fa7-4a41-803b-b8595caeddfa.png)

![image](https://user-images.githubusercontent.com/63149232/170715308-a25868c5-3af3-4b24-9bf8-23d810af240a.png)

**Comment by azhuang321** [comment]
node 使用的是这个例子  [example](http://nodejs.cn/api/http.html#event-upgrade)

**Comment by azhuang321** [comment]
你好添加了

**Comment by azhuang321** [comment]
客户端 请求头不是标准的请求头,按照标准流程处理不了 这个只能自己修改了
