### ISSUE TITLE
手机无法访问电脑的8899

### ISSUE THREAD

**Issue by IAIAE** [avwo/whistle#737]
同一个wifi下，手机浏览器访问自己电脑whistle的8899，无法访问（但电脑浏览器可以访问。）

尝试手机连同事的whistle，可以访问。

所以不是网络问题~~~
切换了node版本和whistle版本，无果~~~

whistle有debug日志么？感觉无法访问是whistle无响应什么的~~~

**Comment by avwo** [comment]
https://github.com/avwo/whistle/blob/master/docs/i18n/zh/phone/ios.md

**Comment by lizy-CZ** [comment]
已经无数次被 windows 的防火墙坑了，切记需要全部关闭
