### ISSUE TITLE
如何获取单页应用hash模式路由的页面参数?

### ISSUE THREAD

**Issue by hua03** [avwo/whistle#738]
现在前端这块有许多应用是直接以下面这种hash模式路由放到线上，想要请教下怎么获取到问号后面的参数。

下面这种请求被[whistle](https://github.com/avwo/whistle)抓取后，只有 `/`, 而不是 `/#/network?abc=111`

```js
http://localhost:8080/#/network?abc=111
```

**Comment by avwo** [comment]
`hash` 不会发送到后台，且修改 hash 当前页面也不会重新发请求。

**Comment by hua03** [comment]
懂了，多谢指点。
