### ISSUE TITLE
开 whistle 后，二进制类型文件下载非常慢

### ISSUE THREAD

**Issue by RequireSun** [avwo/whistle#740]
如图我们 8.5M 的 wasm 文件下了将近两分钟，不开 whistle 的情况只需要十秒不到，我们对这个 wasm 文件没有任何代理修改内容的诉求（只是有可能会重定向），有办法可以让 whistle 跳过无关步骤么？

![image](https://user-images.githubusercontent.com/7576691/172549064-80db6697-a0fa-46a2-a500-1b2f1c98102a.png)

**Comment by avwo** [comment]
从截图看你的请求普遍响应比较慢：
1. 看 Whistle Network Overview 匹配哪些规则
2. 公司内部有对 Node 进程做限速吗
3. Node 什么版本，升级 Node 或 Whistle 试试

**Comment by RequireSun** [comment]
不好意思，我的电脑状态不是很稳定，关于：
1. 匹配规则：是空的，左侧 list 里是细体，不是粗体
![image](https://user-images.githubusercontent.com/7576691/172561301-cd6a529c-d2b7-4ab7-8b8e-2e41b991a947.png)
2. 这个怎么看，可以指导一下嘛，我电脑长期负载都比较高，平跑就是 60% 左右，开发项目期间基本一直维持 100% 左右
3. node 版本：16.15.0，whistle 版本 2.9.17
4. 关于整体比较慢的问题，下图是对比，我 disable cache 了之后在页面上分别 fetch 两次，第一次是开了 whistle 的，8.5MB 40 秒，第二次是关掉 whistle 的 7.4MB 4秒，第三次是我不服，又开了一下 whistle，又是 8.5MB 36秒
![image](https://user-images.githubusercontent.com/7576691/172562758-30fc757e-dafb-49a8-b914-a8ade2704114.png)
我看了下服务端返回，貌似走 whistle 的请求用的是 gzip 压缩，直接请求的用的是 br 压缩，是否跟这个有关系？

**Comment by RequireSun** [comment]
文中的静态资源地址：
https://lf16-web-buz.capcut.com/obj/capcut-web-buz-us/ies.lvve.editor.oversea/static/media/videoeditor.33e5ee2a.wasm

**Comment by RequireSun** [comment]
另外补充一些其它信息：
1. 我们公司默认是有网络代理的，不知道是不是经过 whistle 的请求没有走公司的网络代理
2. 公司有 github 扫描，不太方便直接把 cdn url 地址贴在这里，如果可以的话，我把地址发邮件给你
3. 我对比了一下两个请求的返回头：
    + gzip（走了 whistle）缺少的返回头：content-length
    + br（没走 whistle）缺少的返回头：vary

**Comment by avwo** [comment]
这个主要跟本机的网络和 cpu 有关系，在网络和 cpu 正常情况试试。

**Comment by RequireSun** [comment]
> 

啊，上面的截图就是在 cpu60% 的时候操作的。

**Comment by RequireSun** [comment]
是的，我的电脑在调试的时候 CPU 占用会不可避免地变高，有什么办法能让特定请求不走 body 处理流程么，这样这个请求就不会因为 CPU 占用太高而变慢了

**Comment by RequireSun** [comment]
还有个问题就是为什么 encoding-type 会被从 br 降级成 gzip，这个有办法解决么

**Comment by avwo** [comment]
node 不支持 br，所以降级，这个不影响功能。

**Comment by RequireSun** [comment]
> > 是的，我的电脑在调试的时候 CPU 占用会不可避免地变高，有什么办法能让特定请求不走 body 处理流程么，这样这个请求就不会因为 CPU 占用太高而变慢了
> 
> 肯定会影响，先排除这个因素测下。

我了解这个会影响，但是我上面 40s 的 case 就是在 cpu 60% 的情况下测试出来的，这种情况应该不会影响 whistle 了吧

**Comment by RequireSun** [comment]
> node 不支持 br，所以降级，这个不影响功能。

了解，那这个先不管了
