### ISSUE TITLE
走了whistle后，服务端无法拿到远程服务器的真实IP

### ISSUE THREAD

**Issue by uje** [avwo/whistle#741]
内网环境，在终端设备设置whistle代理后， 请求服务端的地址，服务端拿到的远程用户端IP为启动whistle的机器IP，无法拿到真实IP。建议whistle参考代理服务器规范，设置x-forwarded-for头，保证服务器能拿到真实的终端IP。

**Comment by avwo** [comment]
可以通过规则 `* enable://clientIp` 让 Whistle 带上 `x-forwarded-for` 头
