### ISSUE TITLE
无法访问谷歌

### ISSUE THREAD

**Issue by ifeisier** [avwo/whistle#742]
使用 chrome 插件连接了 127.0.0.1:8899 代理，但是我要怎么配置，能访问外网？

谢谢

**Comment by avwo** [comment]
你之前翻墙的代理是什么？

**Comment by ifeisier** [comment]
> 你之前翻墙的代理是什么？

![image](https://user-images.githubusercontent.com/89009057/173517153-0376365b-c35c-4f9e-83e8-142a2fbf3b40.png)

**Comment by avwo** [comment]
用的是 Socks5 代理协议吗？https://wproxy.org/whistle/rules/socks.html

**Comment by ifeisier** [comment]
等我试试

**Comment by ifeisier** [comment]
请问是这样配置吗？

![image](https://user-images.githubusercontent.com/89009057/173538680-3cd97d26-2764-468d-876b-bd8048e759e1.png)

![image](https://user-images.githubusercontent.com/89009057/173538731-b602a1ce-e43a-42b6-9b4e-06b30a66b1bd.png)

如果是，那么还是没法访问

**Comment by avwo** [comment]
不应该啊，会不会第一次比较慢，你多访问几次看看

**Comment by ifeisier** [comment]
> 不应该啊，会不会第一次比较慢，你多访问几次看看 Node 建议用最新的 LTS 版本

这是我刚下载的 Node JS 是最新的 LTS 版本。

什么情况？？我应该将你的代理设置为系统代理，还是将翻墙设置为系统代理？

**Comment by ifeisier** [comment]
莫名奇妙上不了网了 

![image](https://user-images.githubusercontent.com/89009057/173543942-1318ab21-28a3-4400-b664-de3d22923311.png)


直接运行的 

```
w2 start --init
[i] whistle@2.9.22 started
[i] 1. use your device to visit the following URL list, gets the IP of the URL you can access:
       http://127.0.0.1:8899/
       http://192.168.63.1:8899/
       http://192.168.91.1:8899/
       http://192.168.8.134:8899/
       Note: If all the above URLs are unable to access, check the firewall settings
             For help see https://github.com/avwo/whistle
[i] 2. set the HTTP proxy on your device with the above IP & PORT(8899)
[i] 3. use Chrome to visit http://local.whistlejs.com/ to get started
Setting global proxy (127.0.0.1:8899) successful.
Install root CA (http://127.0.0.1:8899/cgi-bin/rootca) successful
```

然后将我的翻墙设置为系统代理。

**Comment by avwo** [comment]
`pattern` 是匹配请求 url 的表达式，试试：`* socks://127.0.0.1:10808`
