### ISSUE TITLE
精确匹配如何同时匹配以斜杠结尾和无斜杠结尾的路径？

### ISSUE THREAD

**Issue by perqin** [avwo/whistle#743]
希望达到的效果：使用**一条**规则，匹配以下两个请求：
- https://www.example.com/sub-app
- https://www.example.com/sub-app/

同时，不匹配子路径的请求（例如https://www.example.com/sub-app/any-path ）。

不使用正则匹配的话，是否可以仅用一条规则来实现呢？精确匹配里是否可以使用类似正则中的问号这样的运算符呢？

（不使用正则匹配的原因是规则是动态生成的，用正则还需要考虑escaping，比较麻烦）

**Comment by avwo** [comment]
`https://www.example.com/sub-app operation`
