### ISSUE TITLE
Whistle don't follow redirects

### ISSUE THREAD

**Issue by alainhb2000** [avwo/whistle#744]
Hi, i have problems with requests that are redirected, with 301 status code, whistle doesn't follow the redirects.

**Comment by avwo** [comment]
Whistle just forwards requests, the client decides whether to redirect the request or not.

**Comment by alainhb2000** [comment]
Yes, I understand, but theres any method that makes Whistle follow the complete redirection and deliver the final response to the client?

**Comment by avwo** [comment]
custom plugin or https://github.com/whistle-plugins/whistle.script
