### ISSUE TITLE
Response header lost

### ISSUE THREAD

**Issue by zhouzongren** [avwo/whistle#748]
Some response lost when proxying, such as Transfer-Encoding: chunked，and name of response header are lowercased, why?
Version: [2.9.8](https://github.com/avwo/whistle/blob/master/CHANGELOG.md)

**Comment by avwo** [comment]
1. `Transfer-Encoding: chunked` http2 not supported : https://stackoverflow.com/questions/29486086/how-http2-http1-1-proxy-handle-the-transfer-encoding
2. name of response header are lowercased: https://evertpot.com/http-2-finalized/

**Comment by zhouzongren** [comment]
Thanks, its really helpful
