### ISSUE TITLE
请问可以进行网卡抓包吗？

### ISSUE THREAD

**Issue by zemelLeong** [avwo/whistle#749]
如题，由于有的软件似乎不走代理，抓不到数据包

**Comment by avwo** [comment]
可以查下有没有对应 vpn 软件可以将请求通过 http 代理的方式转到 Whistle

**Comment by zemelLeong** [comment]
谢谢，我配合Proxifier使用解决了软件不走代理抓不到的问题。
另外我想请问下MySQL的包能抓到吗？

**Comment by avwo** [comment]
可以，在程序加个代理 https://github.com/avwo/lack-proxy
