### ISSUE TITLE
部分请求抓不到

### ISSUE THREAD

**Issue by OverTree** [avwo/whistle#750]
APP 内嵌 H5 页面的加载、以及页面内发出的请求，抓不到，用的腾讯的 X5 内核

**Comment by avwo** [comment]
Android 还是 iOS？

**Comment by OverTree** [comment]
Android。现在关闭了 webview 的证书校验，好了

**Comment by OverTree** [comment]
iOS 有什么注意事项吗？

**Comment by avwo** [comment]
注意安装证书后要确认：
> iOS 10.3 之后需要手动信任自定义根证书，设置路径：Settings > General > About > Certificate Trust Testings

**Comment by listenecho** [comment]
> Android。现在关闭了 webview 的证书校验，好了

请教这个地方是手机设置关闭,还是代码层面关闭呢?

**Comment by avwo** [comment]
应该是代码层面
