### ISSUE TITLE
关于使用正式域名证书的疑问

### ISSUE THREAD

**Issue by fjqingyou** [avwo/whistle#751]
因为要使用的环境软件对好像对证书要求似乎比较高，同一个设备其他类似浏览器等软件能正常抓包的https，那个软件就是不认！

所以想着直接从线上在跑的正式版本的域名证书放到 ~/.WhistleAppData/custom_certs 里面，使用正式的证书，而不使用不被那个软件承认的 rootCA 签发的。

然而不论有没有放证书进入那个文件夹，都得到了以下相同的报错信息

``` log
errMsg: "request:fail native exception javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found. stack:com.android.org.conscrypt.ConscryptFileDescriptorSocket.startHandshake(ConscryptFileDescriptorSocket.java:231)"
```

我这个证书域名证书是在线上用在 nginx 的 pem + key 版本，因为看文档要求的是 crt 版本的。所以我通过下方这个做的转换
``` shell
openssl x509 -in 文件名是域名的名称.pem -out 文件名是域名的名称.crt
```

放进的 custom_certs 时是用 ‘文件名是域名的名称.crt’以及配套的 ‘文件名是域名的名称.key’

然后 w2 restart 方式启动的，请问是我的用法错误了吗？还是我遗漏是什么其他需要做的配置工作？

**Comment by avwo** [comment]
pem 也支持

**Comment by fjqingyou** [comment]
谢谢。现在回到家用 win11 确认使用 pem 时正常按预期工作，我明天回公司后，用公司的 MacOS 也测试下直接用pem的看看!

**Comment by fjqingyou** [comment]
在 MacOS 测试，一样是将 nginx 的 pem + key 文件，同样是 ‘域名’ + .key 以及 '域名' + .pem 的文件放到了 ~/.WhistleAppData/custom_certs/ 文件夹里面。在 MacOS 中并没有按预期抓包这个域名访问的 HTTPS 的请求，而是 tunnel:// 的请求

**Comment by avwo** [comment]
打开 `Network / HTTPS / View custom certs info` 看看证书是否加载正常，记得用最新的 Whistle

**Comment by fjqingyou** [comment]
成功了！确认是版本导致。
原先的是 whistle@2.9.13 失败，更新后用 whistle@2.9.25 正常工作了！

**Comment by fjqingyou** [comment]
感谢！
