### ISSUE TITLE
该证书并非来自可信的授权中心

### ISSUE THREAD

**Issue by huayan1** [avwo/whistle#752]
之前 安卓是正常使用的，现在发现安卓 微信浏览器 无法访问页面（白屏）（network 不跑请求）（红米 note 9 pro）

**Comment by huayan1** [comment]
MAC 端和 ios 手机端(微信浏览器 和 Safari)是正常的

安卓的自带浏览器 和 UC 浏览器 能显示  vConsole，页面不显示

**Comment by LJJCherry** [comment]
遇到了同样的问题，从上周五开始突然不行了

**Comment by LJJCherry** [comment]
我安卓升级了一下微信好了

**Comment by huayan1** [comment]
我现在的  安卓 微信版本是 8.0.22 最新的，但是 微信浏览器 进入  ，看不到任何请求

安卓的自带浏览器 和 UC 浏览器 能显示 vConsole，页面不显示（同域的图片可以显示，跨域的图片不显示）
