### ISSUE TITLE
上传文件的时候查看起来特别困难

### ISSUE THREAD

**Issue by aogg** [avwo/whistle#754]
webforms也没有数据
只有body有一行一行的包含的多余东西

不太友好，麻烦优化下

**Comment by avwo** [comment]
预期如何显示？

**Comment by avwo** [comment]
下个版本支持在 `Network / Inspectors / Request / WebForms / Body` 显示。

**Comment by aogg** [comment]
类似这样子，反正能好看点就好了，不过那种一行一行的也不要去掉

![](https://files.catbox.moe/8isuxq.jpg)

**Comment by avwo** [comment]
重新安装 whistle 并重启
