### ISSUE TITLE
配置无效

### ISSUE THREAD

**Issue by mahaoming** [avwo/whistle#755]
线上的域名是
https://console.polyv.net/live/index.html#/channel
多了/live这一级

尝试配置代理到本机上

配置如图
![1658025430219](https://user-images.githubusercontent.com/31064550/179381663-37784eb5-1068-4043-b6d4-3eaf1f013b32.png)

会报以下错误
![1658025419675](https://user-images.githubusercontent.com/31064550/179381647-aab9df47-41f2-42aa-9686-d87247dab96f.png)

**Comment by avwo** [comment]
路径问题，后面url也加一层 live 试试
