### ISSUE TITLE
如何过滤protocol为h2的请求，还有一个问题就是console不会打印对应的日志

### ISSUE THREAD

**Issue by 2zyyyyy** [avwo/whistle#757]
问题1:
![image](https://user-images.githubusercontent.com/16091322/180162527-0257d1b6-8e7d-4721-bb2c-45be4f6b72da.png)
问题2:
![image](https://user-images.githubusercontent.com/16091322/180162637-424729db-f806-444f-8baf-eb53920e4ebb.png)

![image](https://user-images.githubusercontent.com/16091322/180162669-3ad603e7-ea43-4df4-a1ed-83b48f09180c.png)

**Comment by avwo** [comment]
具体要实现什么功能？

**Comment by 2zyyyyy** [comment]
1.第一个过滤是看着请求有点多 就是想过滤掉
2.第二个console是要看对应页面的日志

**Comment by avwo** [comment]
可以在 Network / Settings 通过域名过滤，也可以通过规则 `pattern enable://hide` 隐藏
