### ISSUE TITLE
log打印时，搜索功能不太完善

### ISSUE THREAD

**Issue by cos2004** [avwo/whistle#758]
问题：配置了log://，在tools可以看到打印的日志。在下面输入框输入关键字搜索时也可过滤日志，但是后续打印的日志不能根据关键字过滤了，需要重新输入关键字并且enter

期望：希望输入关键字后，打印的日志可以一直过滤，直到清空搜索词

**Comment by avwo** [comment]
不需要回车，为防止卡顿做了 debouce，下个版本把时间间隔调小点

**Comment by avwo** [comment]
重新安装 whistle 并重启。
