### ISSUE TITLE
net::ERR_CERT_VALIDITY_TOO_LONG

### ISSUE THREAD

**Issue by w651662199** [avwo/whistle#759]
在调试androidwebview时，安装证书后，提示net::ERR_CERT_VALIDITY_TOO_LONG。查看原因是从2020年9月1日起，证书有效期不能超过13个月，所以无法调试成功，请问是否可以提供13月以内有效期的证书？

**Comment by avwo** [comment]
多久没更新 whistle 了，重新安装 whistle 并重启试试。

**Comment by w651662199** [comment]
> 

我新安装后显示的证书颁发时间是2021.7.25，有效期至2023.7.25，这个应该还是超过13个月的

**Comment by avwo** [comment]
难道策略又变了：https://github.com/avwo/whistle/issues/316 ，我看下

**Comment by avwo** [comment]
更新 whistle 试试
