### ISSUE TITLE
原始response是没有content-type的，经过script规则后，默认加Content-Type: application/octet-stream

### ISSUE THREAD

**Issue by huzuli** [avwo/whistle#76]
原始请求response的header为：
HTTP/1.1 200 OK
Server: nginx/1.8.1
Date: Sat, 30 Sep 2017 06:24:56 GMT
Content-Length: 2459
Connection: keep-alive
ICS-RunTime: 31
Set-Cookie: JSESSIONID=0MvRdZA_tQUeIZvok7aqrXhIPPht-Vjx069BGVUEWj0WfDr-dDwH!-2012227574; path=/; HttpOnly
X-Powered-By: Servlet/2.5 JSP/2.1
jdb-header-rid: 6442e40259cf38b8b179001a04523302

经过script规则后，response的header为：
HTTP/1.1 200 OK
server: nginx/1.8.1
date: Sat, 30 Sep 2017 06:25:27 GMT
connection: keep-alive
ics-runtime: 41
set-cookie: JSESSIONID=7J7RdgjcBP76nbxRxH8W8NkcvM5xU5yhNgIPo6AOgU8rx3pihhSp!-2012227574; path=/; HttpOnly
x-powered-by: Servlet/2.5 JSP/2.1
jdb-header-rid: 6442e40259cf38d7b179001a04523602
Content-Type: application/octet-stream
Transfer-Encoding: chunked

默认增加了Content-Type: application/octet-stream，导致抓包response body 展示不出来。

**Comment by avwo** [comment]
这个是[whistle.script](https://github.com/whistle-plugins/whistle.script)里面的koa设置的，koa会先判断用户有没有自定义type，没有的话会根据body的类型来判断，直至最后采用默认值 `type='bin'`。

你可以在执行 `next()` 后，手动修改下类型 `ctx.type='html'` 即可，或者更新下[whistle.script](https://github.com/whistle-plugins/whistle.script)，`next()` 前后都可以修改响应头。
