### ISSUE TITLE
ihpone手机下载安装证书并信任后提示证书不可信

### ISSUE THREAD

**Issue by TTcom** [avwo/whistle#760]
iPhone手机
手机版本：ios15.1
ihpone使用safari下载证书后 
1、通用->VPN与设备管理信任whistle证书
2、通用->关于本机->证书信任设置->开启whistle完全信任
safari打开百度页面提示此链接非私人连接
![20220727-185823](https://user-images.githubusercontent.com/29853303/181231243-95fa4776-e93f-4d71-aeea-27e15e9291a4.jpg)
![20220727-185818](https://user-images.githubusercontent.com/29853303/181231224-7009c9c0-8ccf-40b5-8823-65f205b30f59.jpg)

**Comment by avwo** [comment]
whistle 什么版本

**Comment by TTcom** [comment]
whistle 的版本是2.9.28

**Comment by TTcom** [comment]
> whistle 什么版本

whistle 的版本是2.9.28

**Comment by avwo** [comment]
1. 手机上的时间和电脑的时间是否一致
2. 证书安装且已确认：https://wproxy.org/whistle/webui/https.html
3. 看下顶部菜单栏 `HTTPS / View custom certs info`是否有使用自定义根证书

**Comment by TTcom** [comment]
> 1. 手机上的时间和电脑的时间是否一致
> 2. 证书安装且已确认：https://wproxy.org/whistle/webui/https.html
> 3. 看下顶部菜单栏 `HTTPS / View custom certs info`是否有使用自定义根证书

谢谢作者，电脑重启，并且重新安装证书后，一切正常了
