### ISSUE TITLE
设置 urlParams 规则，浏览器访问的 Url 没有变化

### ISSUE THREAD

**Issue by luoheqp** [avwo/whistle#761]
### 问题：
在 Rules 中设置了如下的规则，但在访问的时候没有生效
www.baidu.com urlParams://(test=1&token=0)

在 whistle 的 final url 中看到链接是有拼接上参数的，但浏览器的 location.href 还是原先的链接

### 尝试过的方式：
- 换浏览器，使用全局代理

### 期望
浏览器的 location.href 能带上 urlParams 设置的信息

希望大佬有空能麻烦看一下，非常感谢

**Comment by avwo** [comment]
这个改动只对后台生效，浏览器是感知不到的。要改变 `location.href` 可以用 redirect 重定向或通过 jsPrepend 注入 js 修改

**Comment by luoheqp** [comment]
已实现所需效果，感谢
