### ISSUE TITLE
启动两个实例，其中一个会自动挂掉

### ISSUE THREAD

**Issue by ArtistLu** [avwo/whistle#763]
不知道啥原因

**Comment by ArtistLu** [comment]
w2 start -S /home/www/whistle/8888 -C -p 8888
w2 start -S /home/www/whistle/9999 -C -p 9999
通过上面命令起两个实例其中一个会过一段时间挂掉

**Comment by avwo** [comment]
看下日志文件 `~/.WhistleAppData/whistle.log`
