### ISSUE TITLE
我想做个代理服务器，但是公网访问报错。

### ISSUE THREAD

**Issue by zhangyanrui** [avwo/whistle#764]
From: whistle@2.9.28
Node: v16.16.0
Host: e7f474a903f0
Date: 8/12/2022, 4:10:02 PM
Error: connect ECONNREFUSED 222.129.35.156:8899
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)

**Comment by avwo** [comment]
`ECONNREFUSED` 对应的服务没起来，看下 ip 和端口是不是正确的

**Comment by zhangyanrui** [comment]
解决了。不过我发现外网访问必须映射同样的 8899 端口才可以。如果映射成为其它接口是无法 work 的
