### ISSUE TITLE
whistle 是不是不能和 梯子、科学上网并存？

### ISSUE THREAD

**Issue by note4** [avwo/whistle#765]
好像一打开 V2ray 后 whistle 就不能用了

有没有什么办法可以解决，我想抓包一些境外网站的，比如我想抓包google.com，应该如何操作？

**Comment by avwo** [comment]
用 switchyomega 试试

**Comment by note4** [comment]
> 用 switchyomega 试试
这个好像也不能让 whistle 抓取要fq的域名数据

**Comment by avwo** [comment]
fq 是什么

**Comment by note4** [comment]
> fq 是什么

翻墙科学上网

**Comment by note4** [comment]
![image](https://user-images.githubusercontent.com/6513389/185888591-e67c43ba-956a-4fc8-bd1f-2ce4322868b7.png)
就是类似 Charles 的这个功能

**Comment by avwo** [comment]
你是怎么实现翻墙功能的

**Comment by note4** [comment]
> 你是怎么实现翻墙功能的

- macOS 使用 V2rayU + SwitchyOmega
- Android 使用 V2rayNG

**Comment by avwo** [comment]
SwitchyOmega 怎么配的

**Comment by note4** [comment]
> 

![image](https://user-images.githubusercontent.com/6513389/186093291-608a03ad-4c25-46fd-80e4-2f56e391a9b4.png)
常用这个80自动模式


![image](https://user-images.githubusercontent.com/6513389/186093432-61093b91-8d8b-4794-a278-cd3a6cef4373.png)
如果要抓数据会临时指定域名走whistle-8899或者 SwitchyOmega 全局走whistle-8899

**Comment by avwo** [comment]
`https://gitlab.com/gfwlist/gfwlist/raw/master/gfwlist.txt` 这个里面是什么规则？

**Comment by note4** [comment]
> https://gitlab.com/gfwlist/gfwlist/raw/master/gfwlist.tx

无法访问的域名名单，比如谷歌学术、维基百科等.....

**Comment by alanhg** [comment]
whistle是代理服务，本身并没有干预系统代理，梯子一般是会开启系统代理，所以肯定可以并存。

**Comment by avwo** [comment]
看下梯子走的是什么代理，如果是 socks5 可以在 whistle 配置规则：`* socks://ip:port`

**Comment by note4** [comment]
> 看下梯子走的是什么代理，如果是 socks5 可以在 whistle 配置规则：`* socks://ip:port`

可以了，谢谢老板。

最开始看文档没有理解规则和 socks 的意思。
理解以后，看来 SwitchyOmega 和 whistle 中的  socks 差不多😁

**Comment by yiresumenan** [comment]
如果是vmess类型的vpn呢@avwo

**Comment by avwo** [comment]
看下是不是也是用 socks5

**Comment by bighamD** [comment]
> > 看下梯子走的是什么代理，如果是 socks5 可以在 whistle 配置规则：`* socks://ip:port`
> 
> 可以了，谢谢老板。
> 
> 最开始看文档没有理解规则和 socks 的意思。 理解以后，看来 SwitchyOmega 和 whistle 中的 socks 差不多😁

怎么让vpn  和whistle代理共存 给个配置

**Comment by rexhang** [comment]
#### 比如clash_for_window：

![image](https://github.com/avwo/whistle/assets/14832793/880d65ca-a796-445c-8c1d-1f03457d8070)

### 会默认开启混合端口 **http + socks**，其他代理软件根据本身软件设置，一般都有单独设置socks设置或混合端口的。

然后开启了[SwitchyOmega](chrome-extension://padekgcemlokbadohgkifijomclgjgif/options.html#!/about)后在本地(http://local.whistlejs.com)[http://local.whistlejs.com]的**Rules**中配置 `* socks://127.0.0.1:7890` 或者 `* proxy://127.0.0.1:7890` 即可实现。

**Comment by note4** [comment]
> 如果是vmess类型的vpn呢@avwo

一样的，只取决 socks 和 http 之分
拿到端口搞定。
