### ISSUE TITLE
【插件开发】rulesServer无法获取请求body参数

### ISSUE THREAD

**Issue by qq89987112** [avwo/whistle#767]
1. 尝试getReqSession

可以获取到req.body 但是不稳定
文档上似乎也不推荐在getReqSession里返回规则

<img width="384" alt="image" src="https://user-images.githubusercontent.com/19517335/185652943-b8d87b01-b914-4089-a46a-581515033d02.png">

2. 其他方法
也许有其他方法？？但是调试了好像没看到有什么获取途径

**Comment by qq89987112** [comment]
请求在whistle network面板显示为post请求，真实请求也是post请求

插件req method为get，且没有body
通过getsession方法获取到的req method为post 且有 body

**Comment by avwo** [comment]
要用 `req.getReqSession` 或 `req.getSession` 才能获取请求的 body

**Comment by qq89987112** [comment]
> 

我是要在rulesServer插件里，通过post的参数来返回对应的rule。

然而实际上：通过getReqSession获取body的方案，测试后发现，getReqSession经常没有触发回调。 并且文档上似乎也不推荐在getReqSession里返回rule

**Comment by avwo** [comment]
不支持这种方式，可以试试 whistle.script 插件

**Comment by qq89987112** [comment]
<img width="773" alt="image" src="https://user-images.githubusercontent.com/19517335/187434147-951bfa7d-1ad4-4816-8fba-b40d8e460fd6.png">

不清楚 whistle.script 是哪儿个插件

**Comment by avwo** [comment]
https://github.com/whistle-plugins/whistle.script
