### ISSUE TITLE
导出har文件时请求体编码出现错误

### ISSUE THREAD

**Issue by 21281** [avwo/whistle#770]
请求体如果是二进制格式，导出的har文件，编码有可能出现错误，如下图的原始请求
![image](https://user-images.githubusercontent.com/92528593/186793605-66efdafe-cd18-48cf-99c2-4697e5d27384.png)
导出的har文件里变成乱码：
![image](https://user-images.githubusercontent.com/92528593/186793701-a8a0e253-05c6-4f7f-9097-7cc1523a3fde.png)
将har文件重新导入后内容已经不是原来的了，下图是重新导入后的请求
![image](https://user-images.githubusercontent.com/92528593/186793802-14d6ef8f-3396-4dd8-a1c9-2916ac879703.png)

版本：2.7.26

**Comment by avwo** [comment]
表单内容非纯文本类型导致的，下个版本修复。

**Comment by avwo** [comment]
重新安装 whistle
