### ISSUE TITLE
无法使用Https抓包

### ISSUE THREAD

**Issue by naiyizhang** [avwo/whistle#771]
开启Capture TUNNEL CONNECTs后，无法抓包，不开启的时候抓包正常，开启后无法无法翻墙，电脑和手机证书都已安装

**Comment by avwo** [comment]
电脑也不行吗，报什么错

**Comment by alanhg** [comment]
1. 证书安装后得确认下证书信任呗，如果证书不被信任，无法访问符合预期
2. 提问题要有完整信息，比如浏览器/平台系统/whistle版本/报错信息，这样节约repo贡献者大佬们的时间
