### ISSUE TITLE
http response header包含中文时，经过代理后乱码字符会额外编/解码

### ISSUE THREAD

**Issue by TwinkleSevenStream** [avwo/whistle#775]
### 问题背景
服务端执行报错时，会将错误内容使用UTF-8编码放到http response header中
whistle通过Chrome插件SwitchyOmega代理

#### 未经过代理的http response header（正常情况）
view source后可以显示为中文：
<img width="419" alt="image" src="https://user-images.githubusercontent.com/21072732/189053022-30363730-0b56-4a7a-9b3a-545b52c64c06.png">

view parsed的乱码为：
<img width="434" alt="image" src="https://user-images.githubusercontent.com/21072732/189087139-47857d63-0814-4142-9477-206b0ad6dbb2.png">

#### 经过代理的http response header（异常情况）
可以看见view source后变为乱码，且该乱码与未代理时view parsed中显示的乱码一致：
<img width="421" alt="image" src="https://user-images.githubusercontent.com/21072732/189052401-b5ae21d0-edfb-4e54-aa1d-fdef713551f8.png">

而在whistle抓包中可以看到也是这个乱码：
<img width="587" alt="image" src="https://user-images.githubusercontent.com/21072732/189053890-dda87547-7e5b-4617-8328-271bc9b251da.png">

#### 出现的原因
通过dencode.com解析乱码：
https://dencode.com/string/hex?v=70%2061%2072%2061%206D%2020%2069%206E%2076%2061%206C%2069%2064%203A%2020%20E5%209F%208E%20E5%20B8%2082%20E5%2090%208D%20E7%20A7%20B0%20E5%20B7%20B2%20E5%20AD%2098%20E5%209C%20A8&oe=ISO-8859-1&nl=crlf

对whistle抓包中出现的乱码，通过latin1编码后，再使用utf8解码就是正确的中文字符：
代码上就是直接这样处理：`decodeURIComponent(escape(headers['trpc-error-msg']))`
<img width="759" alt="image" src="https://user-images.githubusercontent.com/21072732/189054963-66b374b6-546b-48fd-95ee-0a453a1f19d1.png">
<img width="757" alt="image" src="https://user-images.githubusercontent.com/21072732/189055032-f7800a55-a3f7-408b-bb97-dbcf883e5e4f.png">

根据验证，实际上通过代理后会多进行了一次编码，代码解析时需要重复编/解码两次就可以正确解析中文：
`decodeURIComponent(escape(decodeURIComponent(escape(headers['trpc-error-msg']))))`

感觉可能是whistle抓包过程中多加了一层编码/解码的过程

**Comment by avwo** [comment]
Node 限制，请求头只能包含 latin1 字符
<img width="1070" alt="image" src="https://user-images.githubusercontent.com/11450939/189090500-3aba2693-f1fe-4702-bbbf-53f525386d1e.png">

**Comment by TwinkleSevenStream** [comment]
> Node 限制，请求头只能包含 latin1 字符 <img alt="image" width="1070" src="https://user-images.githubusercontent.com/11450939/189090500-3aba2693-f1fe-4702-bbbf-53f525386d1e.png">

所以只要是通过node代理的http请求，都会出现这种状况是嘛

**Comment by avwo** [comment]
对

**Comment by TwinkleSevenStream** [comment]
明白了，感谢大佬～
