### ISSUE TITLE
whistle希望部署在公网，但是害怕被人当做代理服务器，希望可以配置代理用户名和密码

### ISSUE THREAD

**Issue by BoomManPro** [avwo/whistle#776]
RT,这个功能现在支持吗?

**Comment by avwo** [comment]
试试插件 https://github.com/whistle-plugins/whistle.proxyauth ，抓包界面也设置下用户名密码 `w2 restart -n test -w 123`

**Comment by avwo** [comment]
怎么配置的，截图我看下

**Comment by BoomManPro** [comment]
启动命令: w2 run -n test -w 123

web配置 /./ whistle.proxyauth://test:123

![Snipaste_2022-09-08_23-47-00](https://user-images.githubusercontent.com/25561886/189167271-e74e6f60-7c81-4324-8650-5618cfc3f088.png)

**Comment by BoomManPro** [comment]
大佬有微信群吗，QQ群一直没通过

**Comment by avwo** [comment]
QQ 群满了，周末我增加下群人数上限

**Comment by BoomManPro** [comment]
已发送好友添加信息，求通过

**Comment by BoomManPro** [comment]
通过抓包和比对，发现是返回的http status code不同，代理服务器是407，而whistle是401，然后我做了一些硬编码修改，是否提个pr?

**Comment by avwo** [comment]
401 会让浏览器弹出登陆窗口，改 407 确定可以解决你的问题？

**Comment by avwo** [comment]
有没有弹出登陆对话框，截图我看下？

**Comment by avwo** [comment]
已修复，重新安装并重启：`npm i -g whistle && w2 restart`

**Comment by N3ophiliA** [comment]
请问大佬使用什么与公网的whistle建联？我用Android上的drony APP、chrome里的SwitchyOmega插件填写username和password，whistle里都没看到。

**Comment by avwo** [comment]
不清楚它们的实现逻辑，可以找找下它们的文档

**Comment by N3ophiliA** [comment]
感谢大佬的回复，我想听听BoomManPro  怎么说

**Comment by BoomManPro** [comment]
> 感谢大佬的回复，我想听听BoomManPro 怎么说

两个都是会弹窗，区别返回和识别的header不一样，代理需要的是407的标识，可以买个类似X代理的账号，看下抓包返回就行。

**Comment by N3ophiliA** [comment]
> > 感谢大佬的回复，我想听听BoomManPro 怎么说
> 
> 两个都是会弹窗，区别返回和识别的header不一样，代理需要的是407的标识，可以买个类似X代理的账号，看下抓包返回就行。

你描述的弹窗是用了https://github.com/whistle-plugins/whistle.proxyauth这个插件对嘛

**Comment by N3ophiliA** [comment]
> > 感谢大佬的回复，我想听听BoomManPro 怎么说
> 
> 两个都是会弹窗，区别返回和识别的header不一样，代理需要的是407的标识，可以买个类似X代理的账号，看下抓包返回就行。

如何做到不弹窗，直接用drony里设置的账号密码呢？你看看我这个问题 https://github.com/avwo/whistle/issues/772
