### ISSUE TITLE
关于自定义插件启动时机问题

### ISSUE THREAD

**Issue by fjqingyou** [avwo/whistle#778]
当前开发似乎是仅在触发了符合插件规则的请求了，插件才开始被加载执行 index.js

是否有办法在whistle启动，但是还未有客户端发起请求时，也进入插件的启动流程的做初始化等工作？

**Comment by avwo** [comment]
在插件根目录创建一个 `rules.txt` 文件，并在里面设置一个加载远程规则的规则（单独一行）：`@whistle.xxx`

**Comment by fjqingyou** [comment]
可以了，感谢！

**Comment by fjqingyou** [comment]
昨天测试的环境不够严谨，当时同时开启了两个浏览器，另一个浏览器后台请求触发了插件的规则，导致测试不完整！

今天排除了规则因素，在确保了没有任何程序通过whistle时，启动插件不按预期工作了。请问我的理解有错误。

我是在插件的根目录，即与 tsconfig.json 的同级目录中的rules.txt文件里面写入以下内容
```
@whistle.no-name-plugin-dev://

```
用开发模式启动，并未按预期执行index.js，等了好几分钟还是没反应了，向whistle发起了能触发规则的请求，index.js才被执行

**Comment by avwo** [comment]
去掉 `://`，保留 `@whistle.no-name-plugin-dev` 即可，相当于 `@whistle.no-name-plugin-dev/`

**Comment by fjqingyou** [comment]
可以了。感谢！
