### ISSUE TITLE
手机连电脑 wifi 热点，在配置了代理 ip 和端口之后，任然不能访问

### ISSUE THREAD

**Issue by LuckyWinty** [avwo/whistle#78]
根据 whistle 帮助文档的方法设置防火墙依然不能访问：
>  如果配置完代理，手机无法访问，可能是whistle所在的电脑防火墙限制了远程访问whistle的端口，关闭防火墙或者设置白名单： http://jingyan.baidu.com/article/870c6fc317cae7b03ee4be48.html

解决方案：
打开 Windows 防火墙，点击 “允许程序或功能通过 Windows 防火墙”，找到 Node.js 的所有进程（Node.js: Server-side JavaScript），勾选所有进程及进程里的 checkbox 即可。

**Comment by hgonlywj** [comment]
mac 测试 成功：
1、可以关闭系统的防火墙。https://jingyan.baidu.com/article/4ae03de31c278b3eff9e6b83.html

2、安装 whistle的Chrome插件，将端口写成8080，重启 whistle， whistle restart -p 8080

**Comment by zhishaofei3** [comment]
mark

**Comment by yt46767** [comment]
> 根据 whistle 帮助文档的方法设置防火墙依然不能访问：
> 
> > 如果配置完代理，手机无法访问，可能是whistle所在的电脑防火墙限制了远程访问whistle的端口，关闭防火墙或者设置白名单： http://jingyan.baidu.com/article/870c6fc317cae7b03ee4be48.html
> 
> 解决方案：
> 打开 Windows 防火墙，点击 “允许程序或功能通过 Windows 防火墙”，找到 Node.js 的所有进程（Node.js: Server-side JavaScript），勾选所有进程及进程里的 checkbox 即可。

thanks，it was solved by using your method.
