### ISSUE TITLE
ca证书名称问题

### ISSUE THREAD

**Issue by leon-W-yao** [avwo/whistle#783]
iphone用户下载ca证书之后，看到的证书名类似 whistle.2134544321.crt ， 这个证书名可以修改吗

**Comment by avwo** [comment]
可以自己生成 ca 证书，分别命名为 `root.crt` 和 `root.key`，并上传到`~./WhistleAppData/custom_cers` 重启 whistle 即可。

**Comment by avwo** [comment]
加一些随机数是为了支持同时安装多个 Whistle 根证书，你改这个的目的是什么？

**Comment by Misaaya** [comment]
想封装成ios程序，然后不让人知道是Whistle吧？

**Comment by avwo** [comment]
可以自己生成一个根证书，再上传到 `~/.WhistleAppData/custom_certs`

**Comment by avwo** [comment]
后续版本可以考虑放开让用户自定义证书配置

**Comment by leon-W-yao** [comment]
> 可以自己生成一个根证书，再上传到 `~/.WhistleAppData/custom_certs`



> 可以自己生成 ca 证书，分别命名为 `root.crt` 和 `root.key`，并上传到`~./WhistleAppData/custom_cers` 重启 whistle 即可。

谢谢

**Comment by leon-W-yao** [comment]
> WhistleAppData

单纯想自定义一个玩儿

**Comment by leon-W-yao** [comment]
> 想封装成ios程序，然后不让人知道是Whistle吧？

就是单纯想自定义一个证书玩儿

**Comment by leon-W-yao** [comment]
> 加一些随机数是为了支持同时安装多个 Whistle 根证书，你改这个的目的是什么？



> 
就是这个每次下载，都是加了一个随机数，我手机上就是一个新证书，证书信任列表那里已经一长串了，我想让证书名称固定


> 加一些随机数是为了支持同时安装多个 Whistle 根证书，你改这个的目的是什么？

**Comment by leon-W-yao** [comment]
> > 加一些随机数是为了支持同时安装多个 Whistle 根证书，你改这个的目的是什么？

> 就是这个每次下载，都是加了一个随机数，我手机上就是一个新证书，证书信任列表那里已经一长串了，我想让证书名称固定

**Comment by avwo** [comment]
随机数生成后就是固定的，目前是支持自定义根证书只是麻烦点
