### ISSUE TITLE
怎么突然不可用

### ISSUE THREAD

**Issue by aogg** [avwo/whistle#784]
手机代理不可用
电脑代理可用
命令行wget不可用
whistle界面请求可用

Whistle for Web Developers.
Version: [2.9.14](https://github.com/avwo/whistle/blob/master/CHANGELOG.md)
Latest version: [2.9.30](https://avwo.github.io/whistle/update.html)
Visit [http://wproxy.org](http://wproxy.org/?type=nodejs&version=2.9.14)

![图片](https://files.catbox.moe/vjjj31.png)

**Comment by aogg** [comment]
就算换成只有whistle，也不行

**Comment by avwo** [comment]
是不是防火墙问题，手机跟 nohost 是在同一个网络下吗

**Comment by aogg** [comment]
算了，好像重启电脑又没事了，很奇怪
