### ISSUE TITLE
通过npm i -g whistle && w2 start --init安装后，该如何卸载呢   没看到相关说明

### ISSUE THREAD

**Issue by Sakii1** [avwo/whistle#785]

**Comment by avwo** [comment]
`w2 proxy 0`

**Comment by XXC385** [comment]
> `w2 proxy 0`

使用此命令后执行`whistle help`发现whistle依然存在

**Comment by avwo** [comment]
`npm uninstall -g whistle`

**Comment by LeeRayno** [comment]
我现在这样操作之后只要不启动 w2 start 命令，系统的 teams 就没网络链接一直处于断线状态，但是其他的网页可以打开，这种是什么原因啊 @avwo

**Comment by avwo** [comment]
看下是不是设置了系统代理，或者执行 `w2 proxy 0` 后再看看
