### ISSUE TITLE
 whistle Error when create authorization

### ISSUE THREAD

**Issue by theWindFollowtheWillow** [avwo/whistle#787]
```
npx w2 start
npx w2 use --force
npx w2 proxy
```
使用项目中的whistle执行上述命令后，最后的proxy报错提示：Error when create authorization。如果使用全局的whistle启动代理就是正常的了，想问下这个是什么原因呢？

**Comment by avwo** [comment]
`w2 proxy` 需要输入 root 密码，估计用 npx 执行无法弹出密码界面

**Comment by theWindFollowtheWillow** [comment]
> 

已经安装过证书了，并且使用w2 proxy直接启动全局whistle时也没有要求输入密码，直接启动成功了

**Comment by avwo** [comment]
没必要用 npx，按正常流程走即可

**Comment by theWindFollowtheWillow** [comment]
> 没必要用 npx，按正常流程走即可

全局启动的话在使用项目内的配置不能获取到环境变量了

**Comment by avwo** [comment]
再试试
