### ISSUE TITLE
升级macos12.6后，启用代理，无法查看浏览器控制台断点里作用域变量值了

### ISSUE THREAD

**Issue by luckyKyle** [avwo/whistle#788]
大佬你好，经过多途径排查定位，升级到macos12.6之后， 已经无法看到断点里的变量，造成调试代码非常困难，盼修复！

<img width="1316" alt="代理console" src="https://user-images.githubusercontent.com/12181722/193183070-8d41b2fa-e1c8-4536-9311-ee7e306ee381.png">

正常情况下应该如下图所示

<img width="1203" alt="非代理console" src="https://user-images.githubusercontent.com/12181722/193183077-afc76614-0f09-4dcd-8958-85fdb4f717df.png">

这个是我目前的环境，浏览器已经将SwitchyOmega以外的插件都屏蔽掉了，中途也换过Edge浏览器来定位，也是遇到同样问题。

<img width="352" alt="企业微信截图_97bb934c-5656-4483-a77c-0ddaeef7ed67" src="https://user-images.githubusercontent.com/12181722/193183150-31249b46-4d9a-4b24-ac70-431139e04fed.png">

<img width="393" alt="企业微信截图_cb1613ed-3cdf-40dc-8b1e-87dbf86c53b8" src="https://user-images.githubusercontent.com/12181722/193183278-da6602af-5610-420e-8bf6-76dc5641a955.png">

**Comment by avwo** [comment]
这跟 whistle 有什么关系？

**Comment by luckyKyle** [comment]
> 
打扰啦！经定位是chrome版本问题，降到102.xx版本后没问题了。
