### ISSUE TITLE
use命令与-S同时使用，且路径里有“/”时，必crash

### ISSUE THREAD

**Issue by zgr0629** [avwo/whistle#789]
复现步骤：
```bash
w2 start -S /test/dir -p 8888
w2 use ./someRule.js -S /test/dir
```

报错：
```bash
No running whistle, execute `w2 start -S /test/newDir` to start whistle on the cli.
```

运行配置文件是：`~/.startingAppData/%23%252Ftest%252FnewDir%23`
但代码里要去读：`~/.startingAppData/%23%2Ftest%2FnewDir%23`

应该是里面的转义问题

版本：whistle@2.9.30

**Comment by avwo** [comment]
感谢反馈，是 bug，下个版本修复

**Comment by avwo** [comment]
重新安装 Whistle 并重启 `npm i -g whistle && w2 restart`
