### ISSUE TITLE
小米 4 - 无法安装证书

### ISSUE THREAD

**Issue by echopi** [avwo/whistle#79]
RT

**Comment by echopi** [comment]
参考 https://www.v2ex.com/t/328481：

1. 把证书(即 crt 文件)传到手机存储，注意不要通过小米自带的浏览器上传 crt 文件 
2. 设置---更多设置---系统安全---从存储设备安装--选择文件

**Comment by avwo** [comment]
也可以用Chrome浏览器或QQ浏览器下载后再按上述方式安装

**Comment by timshaw9791** [comment]
我也采用类似的方式把证书装上华为荣耀手机里了。

**Comment by avwo** [comment]
小米手机按上述方式安装证书时，可能出现 "启用文档" 的提示 

解决方法参考：http://www.miui.com/thread-10619448-1-1.html

**Comment by xuemingcoffeehuang** [comment]
oppo r15 如果从存储设备安装也失败，把rootCA.crt 转换成rootCA.cer即可，亲测有效！！转换方法，命令行使用openssl转换，如下：openssl x509 -in ca.crt -out server.cer -outform der

**Comment by Kinka** [comment]
照whistle文档的流程，安装提示失败后，就直接从`设置--更多设置--系统安全--从XX安装`，也可以。仍然是CRT扩展名，不用做其它修改。

**Comment by xuemingcoffeehuang** [comment]
> 照whistle文档的流程，安装提示失败后，就直接从`设置--更多设置--系统安全--从XX安装`，也可以。仍然是CRT扩展名，不用做其它修改。

其他android用你描述的这种方法都是没有问题的，唯独我这里有一台oppo r15无论如何都不行，于是只能做了一次转换crt -> cer

**Comment by marvin1023** [comment]
如果你的锁屏没有设置密码，那么请先设置锁屏的密码。因为后面安装需要“键入凭据存储的密码”。没有密码是安装不成功的。手机是小米 8SE

**Comment by avwo** [comment]
@marvin1023 也可以直接用Chrome安装
1. **设置好锁屏密码**（已设置忽略这步）
2. 手机配置好whistle代理，使用 chrome 浏览器 输入 rootca.pro 下载证书

**Comment by mengjie0320** [comment]
小米10，QQ浏览器下载证书（QQ、微信等方式传输会找不到文件）；设置 - 安全 - 更多安全设置 - 加密与凭据 - 安装证书 - CA证书 - 输入密码选择文件 - 证书安装（可能多试几次，一直在“CA证书 - 输入密码选择文件 - 证书安装”中循环，也不知道哪次成功了）

**Comment by HelKyle** [comment]
如果支持 USB 调试的话，可以直接用 adb 把证书推送到 sdcard 上

```bash
adb push "rootCA.crt" /sdcard/
```
