### ISSUE TITLE
Can I use display filter like wireshark ? 

### ISSUE THREAD

**Issue by sankred9527** [avwo/whistle#793]
eg: 
wireshark  have these display filter:
 
tcp.analysis.retransmission ---> only show tcp retransmission packet
ether src xx:xx:xx:xx:xx:xx   ---> only show the mac addr of xx.xx.xx.xx.xx.xx

How can I use such filter in whistle ?

**Comment by avwo** [comment]
Try typing in the search box under Network: `i:xx.xx.xx.xx.xx.xx`
for more: https://wproxy.org/whistle/webui/network.html

**Comment by sankhwang** [comment]
> Try typing in the search box under Network: `i:xx.xx.xx.xx.xx.xx` for more: https://wproxy.org/whistle/webui/network.html

Thanks , I  see it .

But the feature of whistle "network" is not as powerful as wireshark.  
I can use "tcp.analysis.retransmission" , "tcp.window_size"  in wireshark, but whistle can't . 

how can I add more powerful filter like wireshark to whistle ?  I can write some plugin for whistle

**Comment by latel** [comment]
你们2个chinese至于用英文交流吗 😄

**Comment by mozhuanzuojing** [comment]
> 你们2个chinese至于用英文交流吗 😄

哈哈，这是我俩年来看到最有意思的评论😂
