### ISSUE TITLE
delete rule too hard

### ISSUE THREAD

**Issue by QingshanLuoyue** [avwo/whistle#798]
in http://127.0.0.1:8080/ web page，the Rules in left bar 。

i want to delete all rules in a group，so i  select the group name and delete it；but the result is that group name has be deleted，leave the rule list。the rule list does not be deleted。

the whistle version is 2.9.30

**Comment by avwo** [comment]
暂不支持批量删除，后续版本可以考虑加上

**Comment by avwo** [comment]
重新安装 Whistle 并重启：`npm i -g whistle && w2 restart`
