### ISSUE TITLE
websocket 代理失效

### ISSUE THREAD

**Issue by xiangfengsu** [avwo/whistle#799]
我自己伪造了一些host ,比如 www.demo.com ,ws.demo.com 等,规则如下：
www.demo.com www.real.com //可以代理转发成功
ws.demo.com  ws.real.com  // websocket 无法代理转发成功

想问，是不是websocket 的地址不能伪造，必须是真实有效的，才能代理成功
<img width="493" alt="image" src="https://user-images.githubusercontent.com/9291534/194839792-df2a956d-f048-4061-9bd2-c19bd2084eab.png">

**Comment by avwo** [comment]
https://wproxy.org/whistle/webui/https.html

**Comment by xiangfengsu** [comment]
> 

我只要接口(http(s),websocket)的转发,不用抓取接口的展示，这个也需要配置证书吗？
<img width="503" alt="image" src="https://user-images.githubusercontent.com/9291534/194855398-769bcd4f-4aa4-4659-96f6-8abfd7e52da6.png">
<img width="460" alt="image" src="https://user-images.githubusercontent.com/9291534/194855457-646a3d48-0047-4192-ba44-638d9b48f712.png">

http的接口代理成功了，websocket 的转发怎么变成了tunnel 了?

**Comment by avwo** [comment]
看我发的文档，要开启拦截https

**Comment by xiangfengsu** [comment]
> 看我发的文档，要开启拦截https

本地mac 安装了证书可以了，但在linux 上怎么安装呢？问了一下运维，他说放哪个目录无所谓，把你用的服务指定一下路径就行了，类似于nginx 配置证书一样，所有我该怎么配置这个目录呢
<img width="896" alt="image" src="https://user-images.githubusercontent.com/9291534/195056797-ead28507-9dd4-4d57-8801-f8aee9f4db09.png">

**Comment by xiangfengsu** [comment]
我按照这篇教程安装了一下
https://blog.csdn.net/u012206617/article/details/109337614
<img width="962" alt="image" src="https://user-images.githubusercontent.com/9291534/195065412-46fe581f-4ff3-4514-ab61-ed93075a1791.png">
这个是执行结果，算是成功了吗？可是https还是无法抓取, mac 设置是成功的
<img width="771" alt="image" src="https://user-images.githubusercontent.com/9291534/195065512-43fc06f2-a2b8-4137-9219-7480e9a8d698.png">

**Comment by avwo** [comment]
要装在你浏览器所在的系统

**Comment by xiangfengsu** [comment]
好的，可以了，谢谢
