### ISSUE TITLE
建议在 Network 增加“暂停”按钮

### ISSUE THREAD

**Issue by yorts52** [avwo/whistle#80]
RT，暂停时 Network 不再新增新的记录

**Comment by avwo** [comment]
滚动条不要置底，列表就不会自动刷新，把滚动条稍微往上滚动就可以

**Comment by avwo** [comment]
[更新到最新版本](https://avwo.github.io/whistle/update.html)，可以**双击**顶层菜单栏的 `AutoRefresh`按钮停止当前页面的滚动刷新，或者**双击**顶层菜单栏的空白部分将滚动条置顶
