### ISSUE TITLE
我把whistle打包到了AUR上

### ISSUE THREAD

**Issue by ngdngdc** [avwo/whistle#800]
我把whistle[打包到了AUR上](https://aur.archlinux.org/packages/nodejs-whistle),但我没有在github找到合适的软件图标,自己修了一张又觉得效果不好,所以可以帮忙提供提供一张图标吗?

**Comment by avwo** [comment]
https://github.com/avwo/whistle/blob/master/biz/webui/htdocs/img/whistle.png
