### ISSUE TITLE
怎么实现多人共用一个证书呢？

### ISSUE THREAD

**Issue by LIUSUS** [avwo/whistle#801]
命令w2 start[run] -z certDir 没有达到多人使用同一个证书的效果，大佬们有踩过同样的坑吗？是怎么解决的呢？

**Comment by avwo** [comment]
应用场景是什么？

**Comment by LIUSUS** [comment]
准备基于现有的whistle代码，做一个mock数据的工具。  用来解决减化配置安装证书环节，每个手机仅需要安装一个证书，就可以通过切换代理IP随时在本机完成抓包，尤其是测试兼容or新手机

**Comment by avwo** [comment]
本地启动还是运行在服务端

**Comment by NMTor** [comment]
之前在群里咨询过类似的问题，需要在证书目录同时放.crt和.key两个配套文件
默认路径是在~/.WhistleAppData/.whistle/certs/

**Comment by avwo** [comment]
对，也可以通过界面 `HTTPS / View custom certs info` 上传，或者通过插件动态设置参考：https://github.com/whistle-plugins/whistle.sni-callback
