### ISSUE TITLE
请问有类似mitmproxy的websocket_message函数吗？只想观察浏览器和服务器之间的websocket frame中的通信数据并在本地decode 不需要做任何修改。

### ISSUE THREAD

**Issue by Pear-White** [avwo/whistle#802]
![websocket_message](https://user-images.githubusercontent.com/42296026/196623423-fe0a9570-13b1-439a-ab7c-4f5fe86516e7.PNG)

**Comment by Pear-White** [comment]
![websocket_message](https://user-images.githubusercontent.com/42296026/196623291-28f49edf-824a-4776-9f2d-5e7af1bdf2d9.PNG)

**Comment by avwo** [comment]
Network 可以看到
<img width="765" alt="image" src="https://user-images.githubusercontent.com/11450939/196690676-3e95d3c6-a09b-4a50-86f0-6f0a10958e35.png">

**Comment by Pear-White** [comment]
找到了。http-mitmproxy。npm里一搜就有
