### ISSUE TITLE
缺少files功能

### ISSUE THREAD

**Issue by PureWhiteo** [avwo/whistle#803]
新安装的whistle没有files功能
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/70749743/196656267-1042f627-ed8f-4ec7-a269-2fd6d194f8b6.png">

**Comment by avwo** [comment]
删掉了，可以先用本地文件替换，之前的 Files 功能比较鸡肋后面会有更好的替代方案

**Comment by PureWhiteo** [comment]
okok
