### ISSUE TITLE
Mac 通过 `w2 start --init` 启动后，无法访问部分 apple.com

### ISSUE THREAD

**Issue by dreamerblue** [avwo/whistle#804]
系统版本 12.5.1
启动时 whistle 自动安装了证书并配置了 8899 的系统代理，之后发现诸如翻译 api、Apple Music 都会报证书错误，如：

```
此服务器的证书无效。您可能正在连接到一个伪装成“sequoia.apple.com”的服务器，这会威胁到您的机密信息的安全。
```

**Comment by avwo** [comment]
ssl pinnig 问题，配个规则试试：`disable://capture ***.icloud.com** ***.microsoft.com ***.office.com ***.office365.cn ***.apple.com**`

**Comment by dreamerblue** [comment]
多谢！
