### ISSUE TITLE
复制出来的curl的-d参数中有\r\n问题

### ISSUE THREAD

**Issue by 18515381698** [avwo/whistle#806]
### as curl复制出的文本如下，看源码-d的值是通过json直接转义的，包含大量\r\n：
curl -X POST "http://api.weibo.cn/2/comments/build_comments?launchid=10000365--x&ul_hid=cb8e960b-df37-4afa-a01b-a6fc032cdf9a&ul_sid=cb8e960b-df37-4afa-a01b-a6fc032cdf9a&lang=zh_CN&sflag=1&cum=C8F98D36" -H "Host: api.weibo.cn" -H "X-Engine-Typ: 98.0.4758.87" -H "User-Agent: V1824BA_11_weibo_12.10.2_android" -H "X-Log-Uid: 7724810463" -H "X-Sessionid: 14aaa01e-5671-477f-a799-5e1fb89d5126" -H "Content-Type: multipart/form-data;boundary=------------1667384246646" -H "Connection: keep-alive" -d "--------------1667384246646\r\nContent-Disposition: form-data; name=\"is_push_open\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 1\r\n\r\n0\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"networktype\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 4\r\n\r\nwifi\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"is_mix\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 1\r\n\r\n1\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"max_id\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 1\r\n\r\n0\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"recommend_page\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 1\r\n\r\n1\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"orifid\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 6\r\n\r\n102803\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"is_show_bulletin\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 1\r\n\r\n2\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"uicode\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 8\r\n\r\n10000002\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"moduleID\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 3\r\n\r\n700\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"trim_user\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 1\r\n\r\n0\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"is_reload\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 1\r\n\r\n1\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"pick_info_enable\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 1\r\n\r\n1\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"wb_version\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 4\r\n\r\n5853\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"comment_sort_type\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 1\r\n\r\n0\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"is_encoded\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 1\r\n\r\n0\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"c\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 7\r\n\r\nandroid\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"s\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 8\r\n\r\n0974e80f\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"ft\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 1\r\n\r\n0\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"id\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 16\r\n\r\n4829480306609640\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"ua\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 48\r\n\r\nvivo-V1824BA__weibo__12.10.2__android__android11\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"wm\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 9\r\n\r\n3333_1001\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"aid\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 50\r\n\r\n01A9ZxFBalNOzoxpLqOzY0w4XZXPkZZNqtiZO77VYz21sIAiI.\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"ext\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 41\r\n\r\nrecommend_source:39|gid:G4829480306609640\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"fid\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 12\r\n\r\n232532_mblog\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"v_f\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 1\r\n\r\n2\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"v_p\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 2\r\n\r\n90\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"from\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 10\r\n\r\n10CA295010\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"gsid\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 90\r\n\r\n_2A25OXjNaDeRxGeFJ6VYZ8S7IzT-IHXVrSsGSrDV6PUJbj9AKLWXjkWpNfHBUoR-vwsDqyw9VFK_pQk6xF7gvoGaR\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"lfid\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 6\r\n\r\n102803\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"skin\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 7\r\n\r\ndefault\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"count\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 2\r\n\r\n20\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"oldwm\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 9\r\n\r\n3333_1001\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"style\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 1\r\n\r\n1\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"oriuicode\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 8\r\n\r\n10000495\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"ignore_inturrpted_error\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 4\r\n\r\ntrue\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"luicode\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 8\r\n\r\n10000495\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"android_id\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 16\r\n\r\n86dc44d66d166de3\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"fetch_level\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 1\r\n\r\n0\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"is_append_blogs\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 1\r\n\r\n1\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"request_type\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 7\r\n\r\ndefault\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"max_id_type\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 1\r\n\r\n0\r\n--------------1667384246646\r\nContent-Disposition: form-data; name=\"ul_ctime\"\r\nContent-Type: text/plain; charset=utf-8\r\nContent-Length: 13\r\n\r\n1667384246645\r\n--------------1667384246646--\r\n"

### 期望复制出来的内容能够将-d中的\r\n变成真正的换行，如下
curl -X POST "http://api.weibo.cn/2/comments/build_comments?launchid=10000365--x&ul_hid=cb8e960b-df37-4afa-a01b-a6fc032cdf9a&ul_sid=cb8e960b-df37-4afa-a01b-a6fc032cdf9a&lang=zh_CN&sflag=1&cum=C8F98D36" -H "Host: api.weibo.cn" -H "X-Engine-Typ: 98.0.4758.87" -H "User-Agent: V1824BA_11_weibo_12.10.2_android" -H "X-Log-Uid: 7724810463" -H "X-Sessionid: 14aaa01e-5671-477f-a799-5e1fb89d5126" -H "Content-Type: multipart/form-data;boundary=------------1667384246646" -H "Connection: keep-alive" -d "--------------1667384246646
Content-Disposition: form-data; name=\"is_push_open\"
Content-Type: text/plain; charset=utf-8
Content-Length: 1

0
--------------1667384246646
Content-Disposition: form-data; name=\"networktype\"
Content-Type: text/plain; charset=utf-8
Content-Length: 4

wifi
--------------1667384246646
Content-Disposition: form-data; name=\"is_mix\"
Content-Type: text/plain; charset=utf-8
Content-Length: 1

1
--------------1667384246646
Content-Disposition: form-data; name=\"max_id\"
Content-Type: text/plain; charset=utf-8
Content-Length: 1

0
--------------1667384246646
Content-Disposition: form-data; name=\"recommend_page\"
Content-Type: text/plain; charset=utf-8
Content-Length: 1

1
--------------1667384246646
Content-Disposition: form-data; name=\"orifid\"
Content-Type: text/plain; charset=utf-8
Content-Length: 6

102803
--------------1667384246646
Content-Disposition: form-data; name=\"is_show_bulletin\"
Content-Type: text/plain; charset=utf-8
Content-Length: 1

2
--------------1667384246646
Content-Disposition: form-data; name=\"uicode\"
Content-Type: text/plain; charset=utf-8
Content-Length: 8

10000002
--------------1667384246646
Content-Disposition: form-data; name=\"moduleID\"
Content-Type: text/plain; charset=utf-8
Content-Length: 3

700
--------------1667384246646
Content-Disposition: form-data; name=\"trim_user\"
Content-Type: text/plain; charset=utf-8
Content-Length: 1

0
--------------1667384246646
Content-Disposition: form-data; name=\"is_reload\"
Content-Type: text/plain; charset=utf-8
Content-Length: 1

1
--------------1667384246646
Content-Disposition: form-data; name=\"pick_info_enable\"
Content-Type: text/plain; charset=utf-8
Content-Length: 1

1
--------------1667384246646
Content-Disposition: form-data; name=\"wb_version\"
Content-Type: text/plain; charset=utf-8
Content-Length: 4

5853
--------------1667384246646
Content-Disposition: form-data; name=\"comment_sort_type\"
Content-Type: text/plain; charset=utf-8
Content-Length: 1

0
--------------1667384246646
Content-Disposition: form-data; name=\"is_encoded\"
Content-Type: text/plain; charset=utf-8
Content-Length: 1

0
--------------1667384246646
Content-Disposition: form-data; name=\"c\"
Content-Type: text/plain; charset=utf-8
Content-Length: 7

android
--------------1667384246646
Content-Disposition: form-data; name=\"s\"
Content-Type: text/plain; charset=utf-8
Content-Length: 8

0974e80f
--------------1667384246646
Content-Disposition: form-data; name=\"ft\"
Content-Type: text/plain; charset=utf-8
Content-Length: 1

0
--------------1667384246646
Content-Disposition: form-data; name=\"id\"
Content-Type: text/plain; charset=utf-8
Content-Length: 16

4829480306609640
--------------1667384246646
Content-Disposition: form-data; name=\"ua\"
Content-Type: text/plain; charset=utf-8
Content-Length: 48

vivo-V1824BA__weibo__12.10.2__android__android11
--------------1667384246646
Content-Disposition: form-data; name=\"wm\"
Content-Type: text/plain; charset=utf-8
Content-Length: 9

3333_1001
--------------1667384246646
Content-Disposition: form-data; name=\"aid\"
Content-Type: text/plain; charset=utf-8
Content-Length: 50

01A9ZxFBalNOzoxpLqOzY0w4XZXPkZZNqtiZO77VYz21sIAiI.
--------------1667384246646
Content-Disposition: form-data; name=\"ext\"
Content-Type: text/plain; charset=utf-8
Content-Length: 41

recommend_source:39|gid:G4829480306609640
--------------1667384246646
Content-Disposition: form-data; name=\"fid\"
Content-Type: text/plain; charset=utf-8
Content-Length: 12

232532_mblog
--------------1667384246646
Content-Disposition: form-data; name=\"v_f\"
Content-Type: text/plain; charset=utf-8
Content-Length: 1

2
--------------1667384246646
Content-Disposition: form-data; name=\"v_p\"
Content-Type: text/plain; charset=utf-8
Content-Length: 2

90
--------------1667384246646
Content-Disposition: form-data; name=\"from\"
Content-Type: text/plain; charset=utf-8
Content-Length: 10

10CA295010
--------------1667384246646
Content-Disposition: form-data; name=\"gsid\"
Content-Type: text/plain; charset=utf-8
Content-Length: 90

_2A25OXjNaDeRxGeFJ6VYZ8S7IzT-IHXVrSsGSrDV6PUJbj9AKLWXjkWpNfHBUoR-vwsDqyw9VFK_pQk6xF7gvoGaR
--------------1667384246646
Content-Disposition: form-data; name=\"lfid\"
Content-Type: text/plain; charset=utf-8
Content-Length: 6

102803
--------------1667384246646
Content-Disposition: form-data; name=\"skin\"
Content-Type: text/plain; charset=utf-8
Content-Length: 7

default
--------------1667384246646
Content-Disposition: form-data; name=\"count\"
Content-Type: text/plain; charset=utf-8
Content-Length: 2

20
--------------1667384246646
Content-Disposition: form-data; name=\"oldwm\"
Content-Type: text/plain; charset=utf-8
Content-Length: 9

3333_1001
--------------1667384246646
Content-Disposition: form-data; name=\"style\"
Content-Type: text/plain; charset=utf-8
Content-Length: 1

1
--------------1667384246646
Content-Disposition: form-data; name=\"oriuicode\"
Content-Type: text/plain; charset=utf-8
Content-Length: 8

10000495
--------------1667384246646
Content-Disposition: form-data; name=\"ignore_inturrpted_error\"
Content-Type: text/plain; charset=utf-8
Content-Length: 4

true
--------------1667384246646
Content-Disposition: form-data; name=\"luicode\"
Content-Type: text/plain; charset=utf-8
Content-Length: 8

10000495
--------------1667384246646
Content-Disposition: form-data; name=\"android_id\"
Content-Type: text/plain; charset=utf-8
Content-Length: 16

86dc44d66d166de3
--------------1667384246646
Content-Disposition: form-data; name=\"fetch_level\"
Content-Type: text/plain; charset=utf-8
Content-Length: 1

0
--------------1667384246646
Content-Disposition: form-data; name=\"is_append_blogs\"
Content-Type: text/plain; charset=utf-8
Content-Length: 1

1
--------------1667384246646
Content-Disposition: form-data; name=\"request_type\"
Content-Type: text/plain; charset=utf-8
Content-Length: 7

default
--------------1667384246646
Content-Disposition: form-data; name=\"max_id_type\"
Content-Type: text/plain; charset=utf-8
Content-Length: 1

0
--------------1667384246646
Content-Disposition: form-data; name=\"ul_ctime\"
Content-Type: text/plain; charset=utf-8
Content-Length: 13

1667384246645
--------------1667384246646--
"

### 后者是复制到shell中可用的格式

**Comment by avwo** [comment]
下个版本修复

**Comment by avwo** [comment]
更新 whistle 试试，貌似命令行会自动把 `\r\n` 换成 `\n`，对上传表单不建议使用这个生成 curl 命令，可以直接在 whistle 的 composer 里面测试

**Comment by 18515381698** [comment]
> 更新 whistle 试试，貌似命令行会自动把 `\r\n` 换成 `\n`，对上传表单不建议使用这个生成 curl 命令，可以直接在 whistle 的 composer 里面测试

拷贝出的curl主要是给后端同学调试用的，但是我没法限制他们使用何种工具。
更新后已经可以拷贝出可用curl了，非常感谢！
