### ISSUE TITLE
插件开发的例子能否提供一个同时修改url参数和body参数的例子

### ISSUE THREAD

**Issue by shahuwang** [avwo/whistle#807]
由于不太熟悉node.js的相关开发，照着插件开发的例子，使用pipe和server的例子，目前实现了请求body的修改、响应body的修改，目前还不知道怎么修改url里面的参数。

目前网上关于whistle插件开发的说明很少，一直没找到。因为调试的服务包含签名校验，所以修改了参数需要同时修改url里的签名参数，没找到修改请求参数和body的例子。

**Comment by avwo** [comment]
试试：
1. `rulesServer`：https://github.com/whistle-plugins/examples/tree/master/whistle.test-rules
2. `urlParams`: https://wproxy.org/whistle/rules/urlParams.html

**Comment by answer-huang** [comment]
> 试试：
> 
> 1. `rulesServer`：https://github.com/whistle-plugins/examples/tree/master/whistle.test-rules
> 2. `urlParams`: https://wproxy.org/whistle/rules/urlParams.html

你好, 我也遇到这个问题.
按照 rulesServer 阶段进行 urlParams 是可以做 url 替换了. 


但是遇到另一个问题:
在 rulesServer 阶段, 我希望拿到 body 体里面的参数, 从而计算签名.  可是 req.unsafe_getReqSession 方法的回调里面, 并没有返回 body 体.

**Comment by avwo** [comment]
直接用 server 参考这个 https://github.com/whistle-plugins/whistle.script
