### ISSUE TITLE
http2 请求头中部分字段缺失

### ISSUE THREAD

**Issue by casezhao** [avwo/whistle#808]
原始请求头字段
![image](https://user-images.githubusercontent.com/42054068/199942482-cfb6dde1-4759-4642-a2bc-ddecb9566919.png)
whistle代理后的请求头字段
![image](https://user-images.githubusercontent.com/42054068/199942241-d3e7e113-a2bd-4c96-a516-f977a3c6497c.png)
其中http2中新增特性部分没有被代理转发

**Comment by avwo** [comment]
那些字段带过去了，只是 whistle 把它们用 method url 显示出来
