### ISSUE TITLE
关于上游配置是否可以进一步提升高可用、灵活性？以及 values 是否可以支持灵活的动态内容

### ISSUE THREAD

**Issue by fjqingyou** [avwo/whistle#809]
当前配置上级代理我是通过 proxy://{proxy_define_default}  方式配合 values 定义。

不过这样有一个局限性，如果上游这个主机瘫痪等意料之外的情况发生。符合规则的请求都将无法完成！

所以萌生出了几个想法，还请大佬参考下是否有机会添加功能支持！

1、values 支持动态内容，例如支持特定规则的内容识别为js逻辑代码，通过调用执行得到动态的值。直接写或者指向一个js文件去执行等。进而可由用户js逻辑动态指定 value 的值；或者是根据某种规则动态地取得其他 values 中定义好的多个中的某一个值

2、proxy支持多上级路由。前一个失败后可顺序逐个尝试其他上游进行建立连接；或者是负载均衡方式均匀分配尝试机制，类似nginx的负载均衡。

**Comment by avwo** [comment]
可以试试：[https://github.com/whistle-plugins/whistle.vase](https://github.com/whistle-plugins/whistle.vase)。
Values 这块后续会优化，简化 mock 步骤，增加协作能力。

**Comment by fjqingyou** [comment]
感谢！我研究研究！

**Comment by avwo** [comment]
可以用插件实现，解析规则时直接执行 js 不可控，无法处理脚本的执行时间和异步异常
