### ISSUE TITLE
Mac系统：weinre下的console面板失效，没有打印任何内容

### ISSUE THREAD

**Issue by imadentive** [avwo/whistle#81]
Mac系统：weinre下的console面板失效，没有打印任何内容

**Comment by avwo** [comment]
weinre的脚本是在页面末尾注入的，所以页面初始化的console的内容不会打印到weinre的面板上，这部分可以采用[log](https://avwo.github.io/whistle/webui/log.html)来代替，更多内容可以参考：[利用whistle调试移动端页面
](http://imweb.io/topic/5981a34bf8b6c96352a59401)
