### ISSUE TITLE
whistle代理http3时为什么会降级至h2或者http1.1？

### ISSUE THREAD

**Issue by gemxx** [avwo/whistle#811]
如题，whistle及charles在代理 http3时，浏览器最终并不会使用http3，而是降级到h2或者http1.1，请问这是什么原因？

**Comment by avwo** [comment]
暂不支持 http3

**Comment by gemxx** [comment]
我理解h2 和 h3 协议栈底层的不同区别，可以大概描述一下whistle是如果做到的降级吗？

> 暂不支持 http3

**Comment by avwo** [comment]
服务端做了兼容，tcp 请求肯定只能走 h2 或 h1，如何区分 h2 和 h1，自己可以了解下 alpn 协议。

**Comment by gemxx** [comment]
> 

明白了，感谢
