### ISSUE TITLE
可否在界面上增加批量操作

### ISSUE THREAD

**Issue by haili042** [avwo/whistle#812]
![image](https://user-images.githubusercontent.com/8747955/201851750-c2c4ca0f-2b43-4396-8d33-9f632ccb998e.png)

如题, 界面上 Values 和 Rules 里只能一个个删, 比较麻烦, 大佬可否加个批量删除的按钮

**Comment by avwo** [comment]
先创建个分组，再通过删除分组实现批量删除

**Comment by avwo** [comment]
具体什么应用场景？

**Comment by haili042** [comment]
> 

values 和 rules 较多的情况下, 一条条操作比较麻烦

**Comment by avwo** [comment]
已支持，重新安装并重启试试

**Comment by haili042** [comment]
> 已支持，重新安装并重启试试

可以了, 谢谢大佬~
