### ISSUE TITLE
whistle不可使用如何排查

### ISSUE THREAD

**Issue by jayjliang** [avwo/whistle#813]
whistle升级到2.9.31，最近发现whistle经常会挂，表现就是所有请求没有响应，127.0.0.1:8899也访问不了，w2 restart后就好了，想问一下这种问题需要怎么排查，有没有什么调试模式或者日志可以看

**Comment by avwo** [comment]
1. 看下日志文件 `~/.WhistleAppData/whistle.log` 有没有异常信息
2. 更新 whistle 试试再观察试试
3. 如果还有问题，可以通过命令 `w2 run` 启动调试模式观察一段时间
