### ISSUE TITLE
Host 转发正则匹配

### ISSUE THREAD

**Issue by xiangfengsu** [avwo/whistle#814]
这种写法好像不支持，有解吗？

test-*.abc.com  real-*.xxx.com

比如 
test-1.abc.com 转发 real-1.xxx.com

test-2.abc.com 转发 real-2.xxx.com

**Comment by avwo** [comment]
试试：`test-*.abc.com real-$1.xxx.com`
域名、路径、正则、精确匹配、通配符匹配都支持：https://wproxy.org/whistle/pattern.html
还可以通过过滤器做更复杂的匹配：https://wproxy.org/whistle/rules/filter.html
