### ISSUE TITLE
reqScript 中rules.push 问题

### ISSUE THREAD

**Issue by xiangfengsu** [avwo/whistle#815]
```javascript
 var data = parseUrl(url);
if(data.query){
  const rule = '^www.test.com/abc/***  www.real.com/aaa/$1'
  rules.push(rule)
}


```
没有完全生效，css ，字体文件生效了，js 文件没有生效
我测试了一下，因为有判断条件，导致js 没有走新的rule（js是第一个加载的），css 和字体是在js的后面，rule生效了，就成功了

**Comment by xiangfengsu** [comment]
我仔细看了一下，是没有完全生效，css ，字体文件生效了，js 文件没有生效

**Comment by avwo** [comment]
规则是怎么配置的？

**Comment by avwo** [comment]
首先请求要匹配到改规则：
``` txt
www.test.com reqScript://js-filepath
```

**Comment by xiangfengsu** [comment]
> 

这个配置了，就是这么写的，我的需求是这样的，html的url后面拼接了query，如果query命中就走配置新规则，所以添加了 `if` 的判断，这样就会出现上面的情况，js 加载失败，但是css加载成功，我打印了log,请求是有序的，先请求html文件，在加载里面引用的js,css ,感觉js的加载在设置规则之前，导致无法加载，但是看log ，就是先请求的html，再请求资源，是不是reqScript设计就是 并行的，比如我在设置规则的同时，也在加载资源，导致规则还没生效，并行请求的资源无法匹配规则，所以无法加载

**Comment by xiangfengsu** [comment]
reqScript 中能不能存储全局变量，现在测试下来看，每个请求都会执行一次reqScript ，这样就无法存储变量，因为html的请求是第一个，我可以把获取的query 变量存起了，在后面的请求过来时再进行使用和判断，这样应该就可以了，但现在看来，变量是覆盖的

**Comment by avwo** [comment]
这个是无状态的，你可以自己写插件或试试 https://github.com/whistle-plugins/whistle.script

**Comment by xiangfengsu** [comment]
> 
whistle.script 也是无状态的吧, 我在最外层定义的`isInit` 还是被每次的请求覆盖了,怎么存全局变量呢


<img width="346" alt="image" src="https://user-images.githubusercontent.com/9291534/202607856-5e6bd5d5-966b-4781-ac7d-5e31a91c9085.png">

```javascript
const url = require('url');
var isInit = false
exports.handleRequestRules = (ctx) => {

  const myURL = new url.URL(ctx.fullUrl)
  console.log('isInit',isInit)

  if (myURL) {
    
    const basePath = myURL.searchParams.get('basePath')
    const projectVersion = myURL.searchParams.get('projectVersion')

    if (basePath && projectVersion) {
      
      isInit = true
      console.log('######',isInit)
    }
  }
};
```

**Comment by avwo** [comment]
可以通过设置 cookie 保持状态
