### ISSUE TITLE
whistle host 失效

### ISSUE THREAD

**Issue by candy-Tong** [avwo/whistle#816]
![image](https://user-images.githubusercontent.com/20377280/202433799-e5ac8384-30a2-4873-bc16-0a4050a4ed33.png)
从抓包中看，已经命中了 host 规则
但我 9.134.117.7:8081 并没有任何的服务
直接打开  9.134.117.7:8081 会返回 502
![image](https://user-images.githubusercontent.com/20377280/202434012-ea4a160e-ef56-4ab0-83aa-c8b0c849f767.png)
请求的内容，应该是没有配置代码，直接访问 `https://test.qf.woa.com/risk-graph-webh` 的内容

**Comment by avwo** [comment]
安装下插件 `tnpm i @tencent/whistle.txpac`

**Comment by candy-Tong** [comment]
谢谢~
