### ISSUE TITLE
想开发一个以请求头中信息作为pattern的proxy插件

### ISSUE THREAD

**Issue by N3ophiliA** [avwo/whistle#818]
现在whistle的代理设置是这种形式
pattern proxy://ip:port
我想要开发一个插件，能够实现根据请求头中的某一个信息作为pattern使用代理
header_xxx my_proxy://ip:port
问题：
1. 有没有相关的插件脚手架
2. 如果我基于whistle源代码改造，能否麻烦大佬给予一些提示

**Comment by avwo** [comment]
使用使用 filter，类似：
``` txt
pattern proxy://xxx includeFilter://reqH.xxx=regexp
```
pattern 为匹配请求 url 的表达式：https://wproxy.org/whistle/pattern.html
includeFilter 为过滤器：https://wproxy.org/whistle/rules/filter.html

**Comment by N3ophiliA** [comment]
> 使用使用 filter，类似：
> 
> ```
> pattern proxy://xxx includeFilter://reqH.xxx=regexp
> ```
> 
> pattern 为匹配请求 url 的表达式：https://wproxy.org/whistle/pattern.html includeFilter 为过滤器：https://wproxy.org/whistle/rules/filter.html

**Comment by N3ophiliA** [comment]
> 使用使用 filter，类似：
> 
> ```
> pattern proxy://xxx includeFilter://reqH.xxx=regexp
> ```
> 
> pattern 为匹配请求 url 的表达式：https://wproxy.org/whistle/pattern.html includeFilter 为过滤器：https://wproxy.org/whistle/rules/filter.html


感谢您的回复，很抱歉我回复的比较慢
在我的使用场景里，我可能要对reqH里的某一字段做拆分、判断等操作，感觉regexp操作不能满足我的需求，如果我想把代理这部分改造一下，我应该在哪部分代码下手呢？
我的读代码能力太弱了，能否麻烦作者大大指点一下，大致描述一下关键文件与方法即可，具体逻辑我自己再去琢磨。

**Comment by avwo** [comment]
选择其中一个：
1. https://github.com/whistle-plugins/whistle.script
2. https://github.com/whistle-plugins/examples/blob/master/whistle.test-rules/lib/rulesServer.js

**Comment by N3ophiliA** [comment]
> 选择其中一个：
> 
> 1. https://github.com/whistle-plugins/whistle.script
> 2. https://github.com/whistle-plugins/examples/blob/master/whistle.test-rules/lib/rulesServer.js

感谢，我去看一下

**Comment by N3ophiliA** [comment]
> 选择其中一个：
> 
> 1. https://github.com/whistle-plugins/whistle.script
> 2. https://github.com/whistle-plugins/examples/blob/master/whistle.test-rules/lib/rulesServer.js

感谢回复，
您是否 想让我通过https://github.com/whistle-plugins/whistle.script中的**设置规则**来为whistle扩展规则的处理能力。

但我不打算为whistle的配置处理请求的规则，我想通过代码实现一套比较自动化的代理配置。
我的场景可以简要概述为：
有10个username，有10个代理端口，我想要改造whistle（最好是通过插件，这样更便于维护），使whistle从请求头中拿到username，然后散列到0-9，使用固定的代理端口。

那这样我最直接的改造是不是应该在这里进行：
whistle/lib/tunnel.js
![7edb9159-fabe-4658-b692-22dd1e007d5c](https://user-images.githubusercontent.com/23702316/204241617-c4023f17-d109-4c62-8c9c-302dc2b81fa2.jpeg)

![image](https://user-images.githubusercontent.com/23702316/204242289-581e2e08-7178-444f-aa31-9c7d40e983a0.png)

**Comment by N3ophiliA** [comment]
> 选择其中一个：
> 
> 1. https://github.com/whistle-plugins/whistle.script
> 2. https://github.com/whistle-plugins/examples/blob/master/whistle.test-rules/lib/rulesServer.js

作者大大麻烦您有空看一眼我上一楼的描述↑。

**Comment by N3ophiliA** [comment]
方便提供一下qq群吗？

**Comment by avwo** [comment]
用插件就行，自己研究下：https://github.com/whistle-plugins/examples

**Comment by N3ophiliA** [comment]
> 用插件就行，自己研究下：https://github.com/whistle-plugins/examples

好的，感谢

**Comment by N3ophiliA** [comment]
> 用插件就行，自己研究下：https://github.com/whistle-plugins/examples

我研究了一下。现在给您描述一下，麻烦您看一下，我的思路是否正确：
我使用了whistle.test-rules—— rulesServer
![image](https://user-images.githubusercontent.com/23702316/204735596-126b396b-5135-4b81-8a3e-97ffeb79198f.png)

进行以下的实现：

`
module.exports = (server, options) => {
  server.on('request', (req, res) => {
    console.log('Someone visit rulesServer.')

    username = req.headers.xxxxxxxxx // 这里我省略了如何从headers里拿到username
    if (req.username == "1") {
      proxyRule = "* proxy://ip_1:port_1"
    }
    res.end(proxyRule);
  });
};`

我测试了一下是通的，想来您这里求证一下是否正确。

**Comment by avwo** [comment]
正确

**Comment by N3ophiliA** [comment]
感谢 ❤️
