### ISSUE TITLE
在插件中如何获取到 req.body?

### ISSUE THREAD

**Issue by bugaio** [avwo/whistle#819]
hello, 大佬, 
我 在尝试  编写一个 简易的插件  方便自己, 

在 load-plugin.js中 , 我看到 了 `httpServer.emit('request', req, res)`,

于是 就 跳转到了  我编写的 插件 的`server.js`, 

但是在 获取 req.body的时候 , 陷入了困难, 
可以 给一些 帮助或者 提示么, 

最好的问候, 谢谢

**Comment by avwo** [comment]
你拿 `req.body` 做什么？
1. 单纯拿抓包数据可以用：https://github.com/whistle-plugins/whistle.autosave/blob/master/lib/resStatsServer.js#L38
2. 如果想通过 `req.body` 做一些逻辑参考：https://github.com/whistle-plugins/whistle.set-req-len/blob/main/index.js#L19

**Comment by bugaio** [comment]
> 你拿 `req.body` 做什么？
> 
> 1. 单纯拿抓包数据可以用：https://github.com/whistle-plugins/whistle.autosave/blob/master/lib/resStatsServer.js#L38
> 2. 如果想通过 `req.body` 做一些逻辑参考：https://github.com/whistle-plugins/whistle.set-req-len/blob/main/index.js#L19

很感谢您的回复, 我想我知道该怎么做了
