### ISSUE TITLE
建议增加过滤域名的功能

### ISSUE THREAD

**Issue by axinge** [avwo/whistle#82]
建议增加过滤域名的功能，这样查看多个域名会方便很多，不用再找了

**Comment by avwo** [comment]
Network左下角有个输入框，直接输入域名后就可以：[Network](https://avwo.github.io/whistle/webui/network.html)

也可以在Settings里面设置固定的规则过滤：[Network Settings](https://avwo.github.io/whistle/webui/settings.html)
