### ISSUE TITLE
Web UI Help links `blank` should be `_blank`

### ISSUE THREAD

**Issue by vikyd** [avwo/whistle#824]
`blank` will open new url in next tab(replace url).

`_blank` will open new url in new tab(new).

ref: https://stackoverflow.com/questions/35703005/what-is-the-difference-between-target-blank-and-target-blank

<img width="1028" alt="image" src="https://user-images.githubusercontent.com/2208880/205538702-2503cb06-3a77-404b-b3fc-047bc722735c.png">

**Comment by avwo** [comment]
感谢反馈，已修复
