### ISSUE TITLE
默认配置存在安全风险

### ISSUE THREAD

**Issue by fooying** [avwo/whistle#825]
在当前https://www.npmjs.com/package/whistle、http://wproxy.org/whistle/install.html、Github Readme的安装和运行说明/教程中均为默认配置方案
该默认配置方案没有设置账号密码，存在安全风险
黑客在通过前置攻击进入同个网段后，可以直接扫描网络环境中开启whistle的服务，如以下banner信息中`x-server: whistle`可以作为指纹进行搜索，如https://www.zoomeye.org/searchResult?q=%22x-server%5C%3A%20whistle%22 可以找到在互联网上开放的相关服务
`HTTP/1.1 502 Bad Gateway
content-type: text/html; charset=utf8
x-server: whistle
Date: Thu, 01 Dec 2022 02:41:21 GMT
Connection: close

<pre>
From: whistle@2.9.18
Node: v16.15.0
Host: 10_0_12_10
Date: 2022/12/1 10:41:21
Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1187:16)

<a href="javascript:;" onclick="location.reload()">Reload this page</a>
</pre>`

由于没设置账号密码，黑客就可以盗取cookie，等于盗取其他用户身份，再进行下一步攻击(已在实际企业攻击演练中多次采用该方式绕过用户权限限制)

**Comment by avwo** [comment]
1. 错误信息里面没有返回 cookie 
2. 部署到外网要设置用户名和密码 `w2 restart -n name -w password`
没太看明白，能再详细点吗，或者有什么解决方案？

**Comment by fooying** [comment]
就是建议在相关文档和教程中的安装说明里默认-w或者做强提醒
因为当前相关教程教的默认都是没有让配置-w，很多跟着官方教程配置的都是没有设置密码，存在被黑客利用的风险
或者是否可以要求一定要配置-w？

**Comment by avwo** [comment]
个人电脑大部分是外网不可访问的，可能他们部署在公共服务器上了，文档里面可以加一些说明。

**Comment by avwo** [comment]
README 已补充安全设置
<img width="600" alt="image" src="https://user-images.githubusercontent.com/11450939/211039636-b5100c6c-435d-4d1f-8c3b-e829b91458ba.png">
