### ISSUE TITLE
reqWrite或resWrite在windows下面全路径改怎么填写呢

### ISSUE THREAD

**Issue by liaohongxing** [avwo/whistle#826]
reqWrite或resWrite在windows下面全路径改怎么填写呢， 能不能来个例子：

例如下面这个，没作用：
`
www.baidu.com resWrite://C:\Users\Aoc\Desktop\Temp\w2.log
`

**Comment by avwo** [comment]
试试 `www.baidu.com resWrite://C:\Users\Aoc\Desktop\Temp`

**Comment by avwo** [comment]
试试 `www.baidu.com resWrite://C:\Users\Aoc\Desktop\Temp\baidu.html`

**Comment by liaohongxing** [comment]
现在有了 ，这个必须要后缀正确吗

**Comment by avwo** [comment]
resWrite 会将响应内容写入指定的目录的对应 url 路径的文件，但这个页面是根路径请求，需要指定文件名称，如果用 `https://www.baidu.com/index.html` 访问就不用
