### ISSUE TITLE
js文件 map local 问题反馈

### ISSUE THREAD

**Issue by onistbin** [avwo/whistle#830]
<img width="596" alt="image" src="https://user-images.githubusercontent.com/8800751/208116554-25097dbe-0da4-4e99-b052-67b6aaa0ca72.png">

请教下为什么代理的js文件顶部都会插入这些代码，导致我的代理报错

**Comment by avwo** [comment]
是不是配了 `log://`，这个会自动注入一段 js

**Comment by avwo** [comment]
你可以在包含 `log://...` 的协议后面加过滤 ` includeFilter://resH.content-type=html`
