### ISSUE TITLE
规则前面的 部分 能 提取成变量么？

### ISSUE THREAD

**Issue by huayan1** [avwo/whistle#832]
``` localprefix
/Users/username/project
```

http://www.test.com/www/js/index.main.js file://${localprefix}/js/index.main.js
http://www.test.com/www/js/index3.main.js file://${localprefix}/js/index3.main.js
http://www.test.com/www/js/index3.main.css file://${localprefix}/js/index3.main.css

现在可以把规则后面的一部分提取成变量，前面的可以提取变量吗？

类似下面这种写法：
``` localprefix
/Users/username/project
```
``` remoteprefix
www.test.com/www
```

http://${remoteprefix}/js/index.main.js file://${localprefix}/js/index.main.js
http://${remoteprefix}/js/index3.main.js file://${localprefix}/js/index3.main.js
http://${remoteprefix}/js/index3.main.css file://${localprefix}/js/index3.main.css

或者说有其他方法提取变量，或者有其他 简洁的写法

**Comment by avwo** [comment]
试试：
```` txt
``` localprefix
/Users/username/project
```

http://www.test.com/www/js/index.main.js file://${localprefix}/js/index.main.js
http://www.test.com/www/js/index3.main.js file://${localprefix}/js/index3.main.js
http://www.test.com/www/js/index3.main.css file://${localprefix}/js/index3.main.css
````

**Comment by huayan1** [comment]
`
``` localprefix
/Users/username/project
```
``` remoteprefix
www.test.com/www
```

http://${remoteprefix}/js/index.main.js file://${localprefix}/js/index.main.js
http://${remoteprefix}/js/index3.main.js file://${localprefix}/js/index3.main.js
http://${remoteprefix}/js/index3.main.css file://${localprefix}/js/index3.main.css

`

规则后面的  localprefix  提起成变量了。

规则前面的 remoteprefix  这个可以用变量吗？

**Comment by avwo** [comment]
前面不支持，你可以用通配符 `*/js/ file://${localprefix}/js/` 或指定文件 `*/js/index3.main.js file://${localprefix}/js/index3.main.js`

**Comment by huayan1** [comment]
嗯，我试试通配符和正则~
