### ISSUE TITLE
如何在  values 里面配置一个json 文件的变量，然后在rules 里面引用呢，是引用里面的变量 ，不是指向这个文件

### ISSUE THREAD

**Issue by huayan1** [avwo/whistle#833]
values:
projec_a.json
{
   "local_path": "/Users/username/project/work/"
}

rules:
rule1:
http://www.test.com/content/js/index.main.js file://${projec_a.local_path}/js/index.main.js
... 多个匹配规则

rule2:
http://www.test.com/news/js/index.main.js file://${projec_a.local_path}/js/index.main.js
... 多个匹配规则

同项目 但是多个规则拆成 规则 文件了。

**Comment by avwo** [comment]
不一定放 Values，Rules 也可以内嵌一些简单的 Values：https://github.com/avwo/whistle/issues/832

**Comment by huayan1** [comment]
可能是想 比如  一个项目的  不同模块，如新闻模块，专题模块，

它们规则不在一个文件，但是想共享变量

**Comment by huayan1** [comment]
那我再问下，values 里面 的 json 格式

可以被 rules  引用里面的变量么？

**Comment by huayan1** [comment]
那我再问下，values 里面 的 json 格式

可以被 rules  引用里面的变量么？

**Comment by avwo** [comment]
不支持

**Comment by huayan1** [comment]
嗯，感谢回答~~
