### ISSUE TITLE
替换或新增响应body里json里的某个值，可以用resMerge或者resReplace写吗？

### ISSUE THREAD

**Issue by xiaowanzixll** [avwo/whistle#834]
响应json如下：
{
    "code": 0,
    "message": "",
    "data": {
        "nickname": "a",
        "usernewno": "45666",
        "phone_no": ""
    }
}

只想替换data下的nickname为bbbbb，如何写呢，用resMerge或resReplace只能写到code那层级，无法改写到data里面的值，是书写规则不对吗？应该怎么写？
使用规则https://xxxxxxx   resMerge://(nickname=a11)，结果返回是：
{
    "code": 0,
    "message": "",
    "data": {
        "nickname": "a",
        "usernewno": "1192381928",
        "phone_no": ""
    },
    "nickname": "a11"
}

**Comment by avwo** [comment]
resMerge://({data:{nickname:”555”})
