### ISSUE TITLE
是否能够实现 像charles一样的 breakpoint的功能呢?

### ISSUE THREAD

**Issue by bugaio** [avwo/whistle#836]
有使用过 charles的  断点功能,   针对某个请求 , 可以 设置  对请求/响应 添加断点,  然后 动态 修改 参数/响应值,  觉得很方便,  不知道坐着大大 能否 考虑 一下, 
像 临时 修改 某个请求,  断点还是  挺方便的

**Comment by avwo** [comment]
不支持断点，可通过配置规则代替：https://wproxy.org/whistle/rules/
