### ISSUE TITLE
jsonview里面的视图可以设置展开吗

### ISSUE THREAD

**Issue by Flying-Cabbage** [avwo/whistle#837]
能把整个json全部展开吗，现在是这样
![image](https://user-images.githubusercontent.com/54514945/210700591-75119b36-14f8-485f-8f1f-8e2bf00a0a3a.png)

我想一打开就变成这样，有能设置的地方吗
![image](https://user-images.githubusercontent.com/54514945/210700837-1fef1d70-cc58-44e5-9e56-e7aed72412ca.png)
****

**Comment by avwo** [comment]
重新安装 Whistle 并重启，可以通过右键菜单展开
<img width="379" alt="image" src="https://user-images.githubusercontent.com/11450939/211039022-6705fd83-065c-4219-8fcd-589ef514ec5c.png">
