### ISSUE TITLE
手机连接代理后，无网络

### ISSUE THREAD

**Issue by li1164267803** [avwo/whistle#838]
手机连接代理后，无网络，上午还可以，下午吃完饭在回家连接，就不行了，mac电脑，已经关闭了防火墙，使用的是谷歌浏览器，在浏览器上访问链接是可以的，手机代理后，不能上网

**Comment by avwo** [comment]
看下是不是你电脑的 ip 变了？

**Comment by li1164267803** [comment]
多次重新 `w2 start` 查看需要配置的代理ip地址都是一样的

**Comment by avwo** [comment]
根据启动输出的 url 在 pc 的浏览器上访问看看
