### ISSUE TITLE
[feature] exports:// 导出内容增加请求参数

### ISSUE THREAD

**Issue by lndj** [avwo/whistle#84]
目前的 `request` 内容只有header相关的信息，没有请求的参数信息

希望可以加上

**Comment by wenquanwz** [comment]
嗯，遇到同样的问题

**Comment by avwo** [comment]
下个版本加上，其实界面上可以操作：打开界面的Network，鼠标点击或Hover到Network按钮有下拉菜单，可以导入导出选中的抓包数据
