### ISSUE TITLE
whistle跟clash无法共存-win11

### ISSUE THREAD

**Issue by junbujianwpl** [avwo/whistle#841]
近期更新了几个whistle版本，最近发现whistle跟clash-for-windows不能共存，印象中之前是可以同时使用，从来没有发现whistle会自动退出的情况  
二者都是使用的系统代理模式
clash-for-windows版本，0.20.14
whistle版本，2.9.40

先开clash，好用。然后打开whstle，clash没有流量了
先开whistle，抓包好用。然后打开clash，whistle界面变灰，直接退出了

启动whistle的参数
```
w2 proxy 8888 -x '*baidu* *google* *baidu* *vscode* *micro* *trello* *visual*  *tab* *notion* *sogou* *gitee* *udesk* \n
*gstatic* *mousegesture* *staticj* *static* *msft* *assets*                     \n
'
w2 start -p 8888
```

或者如果clash不使用系统代理模式，有啥好推荐使用方式能共存

**Comment by avwo** [comment]
clashx 不要设置系统代理，通过在 whistle 配规则将请求代理到 clashx ：* socks://127.0.0.1:7890

**Comment by junbujianwpl** [comment]
> clashx 不要设置系统代理，通过在 whistle 配规则将请求代理到 clashx ：* socks://127.0.0.1:7890

试过这种方式，流量也过不去。在chrome里打开google，无法访问。在whistle里network也看不到访问google的记录。chrome没有配置任何代理。是还要在chrome里也设置代理，用SwitchOmega之类的么？ 理论上whistle已经是系统代理模式了，应该不用了吧。
![企业微信截图_16745249242803](https://user-images.githubusercontent.com/7966061/214196480-d7394610-2418-4cd3-9f14-9c8d1f1cc859.png)

![企业微信截图_1674524969464](https://user-images.githubusercontent.com/7966061/214196517-88e268a4-d660-448e-80d1-7b802ea4befe.png)

**Comment by junbujianwpl** [comment]
上面的问题解决了，就是bypass了谷歌等域名导致的访问谷歌时无法转发到clash进行访问。
现在又有另外一个问题。我开了todesk远程桌面软件，这个软件是一直开着的，宿主机会锁屏，我发现现在经常连不上，把宿主机解除锁屏然后又能连上了。whistle在锁屏状态下会停止工作么？或者长时间不操作电脑时会停止工作？是否是这个原因导致的  @avwo

**Comment by avwo** [comment]
1. 不要配 bypass，让请求都走 whistle，并在 whistle 新增一些规则：https://github.com/avwo/whistle/issues/730
2. 锁屏是否停止工作这个是系统决定的，看看系统是否可以配置

**Comment by junbujianwpl** [comment]
> 1. 不要配 bypass，让请求都走 whistle，并在 whistle 新增一些规则：[开启whistle后，苹果商店无法访问 #730](https://github.com/avwo/whistle/issues/730)
> 2. 锁屏是否停止工作这个是系统决定的，看看系统是否可以配置

可以了，感谢老板。  😂  win11记得之前设置过电源选项，不会睡眠的，可能自动更新之后又恢复了默认45分钟睡眠了
