### ISSUE TITLE
文档有误，最新版本好像不支持`fillter://`

### ISSUE THREAD

**Issue by tieniu1** [avwo/whistle#843]
最新版本好像不支持`fillter://`，只找到了 `includeFilter://` 和  `excludeFilter://`
<img width="1680" alt="image" src="https://user-images.githubusercontent.com/49060203/215936277-fbf29c0c-d3db-4c74-98cc-31002418fe7f.png">

**Comment by avwo** [comment]
支持但不建议使用，所以没有自动提醒，可以用语义更明确的 `excludeFilter://pattern`、`includeFilter://pattern`、 和 `ignore://protocol` 代替，文档问题欢迎提pr：https://github.com/avwo/whistle/tree/master/docs/zh
