### ISSUE TITLE
x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by RexHuang** [avwo/whistle#846]
docker pull failed with whistle as proxy, the same env, I can proxy with Fiddler.

$ docker pull nginx:1.23-alpine
Error response from daemon: Get https://registry-1.docker.io/v2/: x509: certificate signed by unknown authority

**Comment by avwo** [comment]
关掉捕获 HTTPS 试试，或者客户端安装下根证书
https://wproxy.org/whistle/webui/https.html
