### ISSUE TITLE
whistle全局代理的情况下，无法抓取到ip为192.168.xx.xx的http请求

### ISSUE THREAD

**Issue by jiechaoming** [avwo/whistle#847]
我有一个本地vue项目，向测试服务器发出去的都是192.168.xx.xx的http请求。倘若使用SwitchyOmega来开启代理，此时whistle是可以抓取到ip地址为192.168.xx.xx的请求。但若我不通过SwitchyOmega而是通过w2 proxy开启全局代理时，访问百度、GitHub时的请求可以正常被抓取，唯有ip地址为192.168.xx.xx的请求是无法被whistle抓取到，我想知道这个是whistle的问题，还是我哪里设置出错导致的。我尝试过关闭电脑防火墙等安全措施，但都是无效的。whistle的版本是最新的。

**Comment by avwo** [comment]
浏览器的 switchyomega 有切到系统代理吗？

**Comment by jiechaoming** [comment]
switchyomega有切换系统代理， 但switchyomega只是谷歌浏览器的插件而我已经开启了全局代理，我还把项目放在edge和Firefox上面，whistle在全局代理的情况下还是无法抓取到192.168.xx.xx的http请求。但我关闭whistle后，使用Charles来抓包，Charles是可以正常抓取到该请求的

**Comment by avwo** [comment]
这种应该是系统代理的问题，对比下系统代理设置的差异

**Comment by jiechaoming** [comment]
确实，我按照Charles的代理手动去配置了一下系统代理，然后就可以了。之后在直接通过w2 proxy来启动全局代理，也没啥问题了。困扰我这么久的问题，就莫名其妙解决了，至于原因是啥，不知道。淦！！！

**Comment by jiechaoming** [comment]
![image](https://user-images.githubusercontent.com/59103666/216946938-0ae1ef0f-5bd5-45ea-8a07-417855f091c2.png)
![image](https://user-images.githubusercontent.com/59103666/216947008-1d3b98d1-b988-4398-95ba-eff8746e336e.png)
whistle默认在这两个地方对本地请求做了限制，取消勾选并删除例外中的内容就没有问题了。
