### ISSUE TITLE
安装完证书，证书信任设置里面没有开启的地方

### ISSUE THREAD

**Issue by Han-YLun** [avwo/whistle#848]
ios版本：16
联系了苹果官方，官方说让联系证书提供方
<img width="702" alt="image" src="https://user-images.githubusercontent.com/44769070/217147143-2531baab-1af1-4932-bdc0-cbfe10e8bdd4.png">

**Comment by avwo** [comment]
按照这个操作：https://wproxy.org/whistle/webui/https.html

**Comment by Han-YLun** [comment]
是按照这个步骤操作的，但是证书信任页面没有需要打开的
![image](https://user-images.githubusercontent.com/44769070/217150523-252855da-286a-4ea2-8e9a-ccbe82f0ac88.png)

**Comment by avwo** [comment]
根证书没安装成功吧，看下 设置 > 通用 > VPN与设备管理

**Comment by Han-YLun** [comment]
![image](https://user-images.githubusercontent.com/44769070/217175935-8c8f06ca-301f-48eb-9aff-a99e78c2ed43.png)
![image](https://user-images.githubusercontent.com/44769070/217175963-a8cfc145-4198-48b1-b479-2f257bd4fa3d.png)

**Comment by avwo** [comment]
重启手机试试

**Comment by Han-YLun** [comment]
ios 16.1.1

**Comment by avwo** [comment]
有的，我手机就是ios16，最新版本为 16.3

**Comment by Han-YLun** [comment]
好的，我更新下版本试一下

**Comment by Han-YLun** [comment]
不行，更新到了最新的ios版本，还是没有

**Comment by avwo** [comment]
奇了怪，我这边升级到16.3也是ok的，你看下旁边的同事会不会也有这个问题

**Comment by Han-YLun** [comment]
不会，没有这个问题，我问了苹果官方，他们让我刷机看看😂

**Comment by twttghg** [comment]
我的也是  升级18.1 以后就这样  没有证书

**Comment by wangxuze123** [comment]
关闭密码 重新安装 
亲测有效
