### ISSUE TITLE
用ie访问我的项目的时候

### ISSUE THREAD

**Issue by cloudwarn** [avwo/whistle#85]
From: whistle@1.5.19
Node: v6.11.5
Date: 2017-10-30 14:35:01
Error: write EPROTO 101057795:error:140770FC:SSL routines:SSL23_GET_SERVER_HELLO:unknown protocol:openssl\ssl\s23_clnt.c:797:

    at exports._errnoException (util.js:1020:11)
    at WriteWrap.afterWrite (net.js:800:14)

**Comment by avwo** [comment]
看下是不是用https访问http服务？

**Comment by cloudwarn** [comment]
应该是的，如果是https访问http服务应该怎么处理，谢谢

**Comment by avwo** [comment]
配置个映射 `https://www.test.com http://www.test.com`

**Comment by cloudwarn** [comment]
已经解决了，十分感谢
