### ISSUE TITLE
w2 start成功后无法打开页面

### ISSUE THREAD

**Issue by a15218378694** [avwo/whistle#850]
配置了情景模式： whistle
![image](https://user-images.githubusercontent.com/29919045/219053355-3756eb87-337a-4d4b-bfe7-86f24fbc2f51.png)

![image](https://user-images.githubusercontent.com/29919045/219053224-aca272f6-7370-4db3-a48b-973934275b34.png)
然后任何页面都打不开了

**Comment by a15218378694** [comment]
> switchyomega 切到直接连接，试试以下哪个 url 可以访问 <img alt="image" width="357" src="https://user-images.githubusercontent.com/11450939/219059570-aaf867a0-aafb-426a-8140-8ea838875ffb.png">

都不行， 可否加下微信，15218378694， 或者你发你的，或者扫码加吧， 谢谢了， 我在另一台电脑是好的， 所以纳闷了， 有时候重启又行了
![mmqrcode1676509843883](https://user-images.githubusercontent.com/29919045/219233848-351010a2-eb67-48ff-bf7e-ae4b3d7c4481.png)

**Comment by avwo** [comment]
执行下 `w2 restart`

**Comment by a15218378694** [comment]
> 

执行了restart也不行， 重启也不行， 昨晚有一次重启倒是可以

**Comment by avwo** [comment]
Node 版本是什么

**Comment by a15218378694** [comment]
> 

我刚刚关了小米妙享互联和AIOT的一些自启动, 好了, 重启也是好的了, 感谢你的解答

**Comment by a15218378694** [comment]
> Node 版本是什么

现在一打开小米妙享，就是坏的，希望可以修复下吧

**Comment by avwo** [comment]
应该是小米妙选把端口抢占或者拦截了所有请求，whistle 无法控制第三方软件的行为。
