### ISSUE TITLE
res body太大时插件中res.base64为空

### ISSUE THREAD

**Issue by zxt5105515** [avwo/whistle#851]
测试发现res body大概1mb时，res.base64就是null了

复现方法：
安装 whistle 2.9.41
安装 whistle.view-md5 ：https://github.com/whistle-plugins/examples/tree/master/whistle.view-md5
测试抓个body较大请求，就能看到响应数据MD5 tab页提示 ”Body 为空“

测试url：
https://s2.best-wallpaper.net/wallpaper/3840x2160/1707/Strawberry-juicy-fruit_3840x2160.jpg

**Comment by avwo** [comment]
加条规则 `* enable://bigData`

**Comment by zxt5105515** [comment]
> 加条规则 `* enable://bigData`

解决了，我看现在限制是10mb，不过基本够用了
