### ISSUE TITLE
resH过滤条件不起作用

### ISSUE THREAD

**Issue by tangb4c** [avwo/whistle#852]
*/ enable://hide includeFilter://resH:Content-Type=image/

比如期望通过上面的规则，过滤所有的图片，实测无效。

**Comment by avwo** [comment]
`enable://hide` 只能在请求阶段起作用

**Comment by tangb4c** [comment]
那有办法过滤某一个指定MIME类型的请求吗，比如我想把图片全部隐藏掉。
我尝试了很多思路，都无法做到。
比如：http header的Accept不准，有的request里为*/*。
目前只能通过域名过滤的方式，都是case by case的。

**Comment by avwo** [comment]
目前只能在 Network 底部过滤
<img width="1000" alt="image" src="https://user-images.githubusercontent.com/11450939/220800666-b54170fd-bcce-4aab-905a-eb1c6ac33341.png">

**Comment by tangb4c** [comment]
好的，非常感谢avwo
