### ISSUE TITLE
windows电脑：post无法代理到本地的post请求，一直在请求中

### ISSUE THREAD

**Issue by jiangshanglong** [avwo/whistle#853]
页面需要代理到本地127的post请求上，如
/https:\/\/test-api.saasflow.cloud.tencent.com/ipaas/(.*$)/  http://127.0.0.1:7001/ipaas/$1
之前提问过这个问题(https://github.com/avwo/whistle/issues/724)，当时给出的解决方案是改用get:url mockUrl method://get
今天发现同事的macbook是可以直接代理到本地的post，请教一下大佬，这仅仅是windows系统的问题吗？

**Comment by avwo** [comment]
大概率是你本地服务的问题，你这个本地服务支持 post 请求吗

**Comment by avwo** [comment]
`/https://test-api.saasflow.cloud.tencent.com/ipaas/(.*$)/ http://127.0.0.1:7001/ipaas/$1` 这种配置可以简化为 `https://test-api.saasflow.cloud.tencent.com/ipaas/ http://127.0.0.1:7001/ipaas/`，针对路径匹配 Whistle 会自动补齐剩余的路径

**Comment by jiangshanglong** [comment]
> 大概率是你本地服务的问题，你这个本地服务支持 post 请求吗

本地服务支持post请求，用Fiddler代理是ok的，页面和配置感觉没whistle好用，还是希望whistle能多多支持一下
