### ISSUE TITLE
请教非标端口如何强制使用https抓包

### ISSUE THREAD

**Issue by J-XianSheng** [avwo/whistle#856]
![image](https://user-images.githubusercontent.com/16432909/224204671-2cfdb109-8bd9-4dba-9744-9b6c094f245f.png)

如图443端口可以正常抓取,非标端口能否通过配置强制按https协议抓包?

**Comment by avwo** [comment]
试试 `请求ip enable://capture`，不过证书不支持以ip为域名的请求

**Comment by J-XianSheng** [comment]
不行...还是抓不到

我是用socks代理抓的 有关不?

**Comment by avwo** [comment]
你这个不是 https 请求吧，可能只是普通的 tcp 请求

**Comment by J-XianSheng** [comment]
确认是https

**Comment by avwo** [comment]
有没有匹配到规则试试：
``` txt
* enable://capture
```

**Comment by J-XianSheng** [comment]
![image](https://user-images.githubusercontent.com/16432909/224225617-542352e8-e910-42a9-81c0-3bfe169ab87c.png)


![image](https://user-images.githubusercontent.com/16432909/224225540-6156a922-1b57-4232-933a-05b58512fbc3.png)

不行...加粗了..应该是匹配到规则了

**Comment by J-XianSheng** [comment]
```
curl -x "http://172.20.255.253:18080" https://appgo.189.cn:9200 -k
```
用http代理可以抓到
```
curl --socks5-hostname 172.20.255.253:11080 https://appgo.189.cn:9200 -k
```
用socks代理,好像是直接转发了



![image](https://user-images.githubusercontent.com/16432909/224228875-029e1689-48a1-4f82-8fda-6fc13f6d6dff.png)

有啥办法吗? 感谢

**Comment by avwo** [comment]
确实是 socks 代理特殊设置导致的，当前版本要开启需要通过插件才能强制开启较麻烦，
周末发个版本支持通过规则强制开启。

**Comment by J-XianSheng** [comment]
好的 感谢

**Comment by avwo** [comment]
已支持重新安装 Whistle 并重启：
``` sh
npm i -g whistle & w2 restart
```
