### ISSUE TITLE
www.baidu.com reqSpeed://1不起作用

### ISSUE THREAD

**Issue by 1livhuang** [avwo/whistle#858]
rules添加了[www.baidu.com](http://www.baidu.com/) reqSpeed://1，打开www.baidu.com，网速正常响应。
经测试，[www.baidu.com](http://www.baidu.com/) reqDelay://5000响应超时，所以只是reqSpeed有问题。
已经通过npm i -g whistle && w2 restart命令更新最新版本的了。就是无法生效reqSpeed。
node版本v18.13.0

**Comment by avwo** [comment]
看下是不是304

**Comment by 1livhuang** [comment]
希望后续可以做到支持，不同的method请求（不论是否有body)都有控制网速的需求存在。
