### ISSUE TITLE
HTTP2请求抓包后 http2相关的请求头信息全没显示出来

### ISSUE THREAD

**Issue by oicq1699** [avwo/whistle#859]
HTTP2请求抓包后，http2相关的请求头信息全没显示出来，例如：
:authority
:method: GET
:path: /
:scheme: https

这些信息都没了，排查问题时，本来就想看原始头信息，结果却没了

**Comment by avwo** [comment]
用http1的方式显示，在url和method里面

**Comment by avwo** [comment]
<img width="600" alt="image" src="https://user-images.githubusercontent.com/11450939/226187868-e5a2462f-95fd-4173-8873-6797a18ddfd0.png">
