### ISSUE TITLE
可以设置前置（上级 / Upstream）代理吗？

### ISSUE THREAD

**Issue by undirectlookable** [avwo/whistle#86]
所在网络需通过http代理连接，whistel文档中未找到相关设置，请求帮助，谢谢

**Comment by avwo** [comment]
看下这两个：[proxy](https://avwo.github.io/whistle/rules/proxy.html)、[socks](https://avwo.github.io/whistle/rules/socks.html)，或者直接配[host](https://avwo.github.io/whistle/rules/host.html)

**Comment by undirectlookable** [comment]
感谢这么快的回复。试了一下，如果为某个域名或者全部请求加上 proxy，那么对其进行请求替换时，就无法替换为本地的HTTP协议例如 `http://localhost/my/path`，因为代理服务器无法抓取到本地 `localhost`

**Comment by avwo** [comment]
应该是你Chrome的代理插件默认将locahost和127.0.0.1的请求加到直接请求的白名单里面，把它去掉就可以

**Comment by undirectlookable** [comment]
上面没有讲清楚，我的规则是这样的
```
http://example.com/a.js http://localhost:8080/a.js
/./ proxy://some-proxy.com:8080
```
我在浏览器中访问 `http://example.com/a.js` 期望返回 `http://localhost:8080/a.js` 的内容，其他请求通过代理服务器 `http://some-proxy.com:8080` 出去。
可见 localhot 是由 whistel 请求的，并不关浏览器的事情。然而如此配置后， `http://localhost:8080/a.js` 也会经由代理，导致请求失败。把代理那一行放在最前和最后都是一样的效果。

**Comment by avwo** [comment]
加条规则： `localhost 127.0.0.1` 或 `127.0.0.1 localhost`

**Comment by undirectlookable** [comment]
问题解决，非常感谢 🌹
