### ISSUE TITLE
关于docker升级

### ISSUE THREAD

**Issue by meteor0027** [avwo/whistle#864]
我在容器内部使用npm update -g whistle也可以进行升级，这种方式与npm i -g whistle升级有啥分别吗？我看文档里面没有update升级命令，update命令是在恩山论坛里面看到的
另外加Q群一直没通过，能通过下吗

**Comment by avwo** [comment]
都可以，哪个方便用哪个
https://stackoverflow.com/questions/12478679/npm-install-vs-update-whats-the-difference
