### ISSUE TITLE
在访问某些HTTPS网站的时候，抓不到包，要么403错误，要么其数据是伪造的

### ISSUE THREAD

**Issue by b1ghawk** [avwo/whistle#865]
目前大致能够判断出来，这些网站对TLS指纹进行了识别(比如常见的JA3指纹)，能否对这块处理一下呢？

**Comment by avwo** [comment]
给个开启TLS指纹的页面链接，有空我研究下

**Comment by LOpSSH** [comment]
> 给个开启TLS指纹的页面链接，有空我研究下

我这里有个触手可得的例子：
https://chat.openai.com/backend-api/conversation

您应该可以访问ChatGPT吧，试试获取这个回复接口的API，可以发现开启whistle代理之后，https无法获取(被CloudFlare的[MITMEngine](https://github.com/cloudflare/mitmengine)拦截下来了，)，关闭whistle之后，https可以正常工作。

<img width="954" alt="image" src="https://user-images.githubusercontent.com/30652540/224884420-0ceb82e6-9288-4e70-b166-128a827b3334.png">

**Comment by LOpSSH** [comment]
您可以试一下，关闭whistle的时候，直接点击
https://chat.openai.com/backend-api/conversation
会有如下结果：
<img width="593" alt="image" src="https://user-images.githubusercontent.com/30652540/224884846-732f7a52-c598-4605-a9bc-c8b43c98e3fd.png">

开启whistle之后再次点击，会有如下结果：
<img width="918" alt="image" src="https://user-images.githubusercontent.com/30652540/224884943-4cb6ca51-bb03-459a-93c9-9657f2084b6f.png">

**Comment by LOpSSH** [comment]
可以参考一下 [Github-uTLS](https://github.com/refraction-networking/utls) 和 [Github-naiveproxy](https://github.com/klzgrad/naiveproxy) ，谢谢…

**Comment by avwo** [comment]
> > 给个开启TLS指纹的页面链接，有空我研究下
> 
> 您可以试一下，关闭whistle的时候，直接点击 https://chat.openai.com/backend-api/conversation
> 
> 会有如下结果：
> 
> <img alt="image" width="593" src="https://user-images.githubusercontent.com/30652540/224884846-732f7a52-c598-4605-a9bc-c8b43c98e3fd.png">
> 
> 开启whistle之后再次点击，会有如下结果(被CloudFlare的[Github-MITMEngine](https://github.com/cloudflare/mitmengine)拦截下来了)：
> 
> <img alt="image" width="918" src="https://user-images.githubusercontent.com/30652540/224884943-4cb6ca51-bb03-459a-93c9-9657f2084b6f.png">

貌似可以正常访问了，如果还不行把 Node 升级下，tls 指纹暂只能自己开发插件适配
