### ISSUE TITLE
plugin 脚本<突然>跳过规则，走网络请求

### ISSUE THREAD

**Issue by q962** [avwo/whistle#867]
不知道原因，刚刚发现的。

脚本内容，指定 id 返回所有数据，否则发送随机数据内容。

同一个接口，同一个请求信息, url 只有 query 中 id 的区别。

随机的数据内容可以正常发送。

唯独 2w7 行的 json 突然跳过规则，走网络请求。

没有任何异常信息.

返回结果如下
```
<pre>
From: whistle@2.9.42
Node: v19.7.0
Host: pc
Date: 2023/3/20 21:29:20
Error: connect ECONNREFUSED 127.0.0.2:3000
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)
    at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17)


<a href="javascript:;" onclick="location.reload()">Reload this page</a>
</pre>
```

**Comment by q962** [comment]
不，我故意关闭了服务。
这个问题和服务无关，因为我要 mock 数据，不能走服务。

**Comment by q962** [comment]
[fail.txt](https://github.com/avwo/whistle/files/11018946/fail.txt)

**Comment by avwo** [comment]
不用 `whistle.script` 插件，自己实现一个看看：https://github.com/whistle-plugins/examples/tree/master/whistle.test-rules

**Comment by avwo** [comment]
<img width="300" alt="image" src="https://user-images.githubusercontent.com/11450939/226564907-3bc3702a-1db9-4f00-ac37-e58bb17396e1.png">
这个是什么意思

**Comment by q962** [comment]
json 数据有 2w7 行，整个脚本 700kB+

**Comment by avwo** [comment]
内容太大了无法内嵌到规则里面，可以写到一个临时文件再用 `* file://filepath` 替换
