### ISSUE TITLE
抓包请求头key字母大小写的问题

### ISSUE THREAD

**Issue by meteor0027** [avwo/whistle#868]
手机通过使用whistle代理抓包，有很多时候请求头中的参数名称字母全都变成了小写字母，包括非首字母大写的也会变成小写，和在手机上用app抓包的不一样，在手机app上抓到的是正常大小写字母的，请问whistle是否有对请求头参数名称全部小写化了？

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by avwo** [comment]
HTTP/2 请求响应头 key 都是小写

**Comment by meteor0027** [comment]
> 
看来的确是因为勾选了HTTP/2，我在HTTPS选项里面取消勾选 Enable HTTP/2后显示就正常了，但是我在Overview里面看显示是Http Version 1.1，如果取消Enable HTTP/2，会对抓包有其它影响吗？还是whistle自动按HTTP2处理HTTP1.1了？
![image](https://user-images.githubusercontent.com/24893142/227195934-e5a41ed9-a211-4f27-83e6-ac95497e9279.png)

**Comment by avwo** [comment]
不影响，但没必要取消，请求头本来就不区分大小写
