### ISSUE TITLE
rules 的匹配优先级

### ISSUE THREAD

**Issue by q962** [avwo/whistle#873]
我有一个 `whistle.script://data */data` 和 `*/data?id=111 tpl`  我无法 获得 `id=111` 的数据

我没有找到相关介绍

不过，看样子，是脚本的优先权最高。

**Comment by avwo** [comment]
overview 显示匹配到的规则是什么

**Comment by q962** [comment]
破案了。偷懒的做法，在脚本中使用 * 匹配规则。所以总是能匹配。

至于为什么要在全局 rules 中填写，是因为只需要填写一行，而 脚本需要三行：`判断；设置；return`

我的理解对 rules 排序，同一个path，优先匹配精确的。

**Comment by q962** [comment]
不对，刚有进行了测试。得出的结论时，优先使用脚本返回的 rules，所以当存在 * 时，意味着总是匹配。

但是第一步应该时匹配全局的rules，可是并没有。这块的逻辑故意提高脚本的优先级还是bug？

还是和书写的顺序有关？如果是，是否应该按照升序的顺序匹配。即使相同的path分散不同的行，排序也不应该打乱书写顺序。

**Comment by avwo** [comment]
按顺序来，优先级从上到下

**Comment by q962** [comment]
也就是手动维护优先级是把。

> 按顺序来，优先级从上到下

那么确实有问题。

因为我  `whistle.script://data */data` 放在最后。
