### ISSUE TITLE
作者大大，请教个问题，关于私有协议想通过 whistle 抓包，能否实现呢？或者基于 Node 额外定制开发是否可行？ 

### ISSUE THREAD

**Issue by zhoujingang** [avwo/whistle#876]
我在 closed 的 issues 下找到群号，申请加入了，辛苦大大审批一下

**Comment by avwo** [comment]
只要是 TCP 请求就可以

**Comment by zhoujingang** [comment]
<img width="1174" alt="WX20230407-114521@2x" src="https://user-images.githubusercontent.com/21023525/230551358-8bff803b-fabf-4f59-a7e2-aec92d764027.png">
现在标准协议的抓包 http\https 都正常，但是私有协议的只能抓到 connect ，后续请求抓不到

**Comment by avwo** [comment]
设置规则 `api.m.jd.com enable://inspect` 后看下 Inspectors / Frames

**Comment by zhoujingang** [comment]
<img width="1646" alt="image" src="https://user-images.githubusercontent.com/21023525/230559169-8b27dcfc-6e77-46d5-8147-4cd6596165f0.png">
Frames 面板内容，大佬，现在这个原因是什么呢

**Comment by avwo** [comment]
这个连接传输的数据不是用明文

**Comment by zhoujingang** [comment]
是的，需要解密，现在能不能支持这块能力呢，或者需要额外开发插件也行

**Comment by avwo** [comment]
需要自己开发插件

**Comment by zhoujingang** [comment]
大佬，能指点下方案不，我这边可以尝试下，后续其他人有需要可以直接用

**Comment by avwo** [comment]
参考：
https://github.com/whistle-plugins/whistle.custom-parser
https://github.com/whistle-plugins/examples/tree/master/whistle.test-pipe

**Comment by zhoujingang** [comment]
我这还有个点，刚才没有表达清楚，就是我在App 里的请求，不但抓包到，发出connect 请求后，后续结果也没有，app 内的数据都不展示。我理解如果仅仅是加密的问题，应该能抓到请求吧😦

**Comment by avwo** [comment]
没看明白的意思？
