### ISSUE TITLE
请问作者whistle会如何处理udp请求？

### ISSUE THREAD

**Issue by N3ophiliA** [avwo/whistle#877]

**Comment by avwo** [comment]
无法处理，接收不到udp请求

**Comment by N3ophiliA** [comment]
w2 start[run] --socksPort socksPort： 设置 socksv5 server 端口
通过这个命令开启socks5端口也接收不到udp请求吗？
这样是不是udp请求会进入whistle，但是因为whistle没有处理，所以udp请求会全部丢失。

**Comment by avwo** [comment]
对，不过 udp 请求一般不走代理

**Comment by N3ophiliA** [comment]
作者您提到的“ udp 请求一般不走代理”是指的使用http代理server吧，我看socks5能够代理udp请求。

**Comment by avwo** [comment]
socks5 支持代理 udp 请求没错，我的意思是很少有 socks5 客户端会转发 udp 请求，你自己先动手试试吧

**Comment by N3ophiliA** [comment]
好的，感谢作者。
请问对于udp有没有计划支持呀？

**Comment by avwo** [comment]
你先看下哪个 socks5 客户端能代理 udp 请求，找到再跟我说下

**Comment by N3ophiliA** [comment]
好的，我有消息与您同步。
