### ISSUE TITLE
请问作者whistle会如何处理udp请求？

### ISSUE THREAD

**Issue by N3ophiliA** [avwo/whistle#878]
看到这个历史issue【https://github.com/avwo/whistle/issues/792 】中提到，当前whistle应该还不支持解析udp数据。
那么现在whistle是怎么处理udp请求的呢？作为“tunnel”请求不进行任何解析，照常发出，* proxy://xxx规则对其可以生效吗？

**Comment by avwo** [comment]
https://github.com/avwo/whistle/issues/877
