### ISSUE TITLE
response中添加gzip后whistle报错

### ISSUE THREAD

**Issue by zhang142578** [avwo/whistle#879]
![image](https://user-images.githubusercontent.com/42526476/229013411-0c47ba61-cbbe-42d3-bc34-496a42a6f56c.png)
![image](https://user-images.githubusercontent.com/42526476/229013442-ab6f1949-54df-46a1-bf57-16519f8f5788.png)

**Comment by zhang142578** [comment]
这个bug貌似只有在新版本的node中出现，我尝试了node12.16.3后没有发现这个问题

**Comment by avwo** [comment]
通过 `enable://gzip` 添加都吗

**Comment by zhang142578** [comment]
请求里面带的，但是为什么请求里面会带上这个问题没有定位过，有的请求会带有的又不会，很奇怪，然后我尝试添加disable gzip也会解决这个问题，降级node到12但不添加disable gzip同样也可以解决问题

**Comment by avwo** [comment]
gzip 版本不兼容吧，链接发我看下

**Comment by zhang142578** [comment]
接口链接吗？ 这个不行啊... 内部的

**Comment by avwo** [comment]
暂时关闭，有遇到类似请求再处理
