### ISSUE TITLE
希望 HTTP Ressponse 中的数据可以直接导出成 json 文件

### ISSUE THREAD

**Issue by jinwei233** [avwo/whistle#88]
![image](https://user-images.githubusercontent.com/243645/32309152-92416504-bfc4-11e7-9c4f-547128ffd62f.png)

**Comment by avwo** [comment]
[更新下whistle](https://avwo.github.io/whistle/update.html)，鼠标hover到TextView或JSONView框中，右上角出现 `ViewAll`  按钮，hover到 `ViewAll` 会展示所有操作按钮，点击 `Download` 输入文件名称，或双击直接下载。
