### ISSUE TITLE
更新V2.9.44后点击响应体的save按钮实际打开的是mock弹窗

### ISSUE THREAD

**Issue by TANCANJIE** [avwo/whistle#881]
更新V2.9.44后点击响应体的save按钮实际打开的是mock弹窗，没有了之前的保存响应体文件

**Comment by avwo** [comment]
新版提供了快速 mock 的功能，你可以把里面的 Rules 删掉就等价于之前的 Save to Values
<img width="989" alt="image" src="https://user-images.githubusercontent.com/11450939/229391567-c6aa8f9a-f6bd-4d78-882e-ec467c323170.png">

**Comment by avwo** [comment]
新版添加了 `Save As Values` 按钮
