### ISSUE TITLE
能否在python代码里调用返回的抓包数据？

### ISSUE THREAD

**Issue by tmxd09887** [avwo/whistle#883]
一边抓包，一边把数据给python，这样可以实现吗？

谢谢

**Comment by avwo** [comment]
可以，两种方式：
正常流程：客户端 -> python
加入抓包功能：
1. 客户端 -> Whistle -> python - 内部请求 -> Whistle -> 服务器
2. 客户端 -> python -> Whistle -> python - 内部请求 -> Whistle -> 服务器

**Comment by tmxd09887** [comment]
抱歉， 我的意思是python自动化工具，启动客户端，然后抓包的数据返回python自动化工具。并不是python配合抓包上报数据的意思。

**Comment by avwo** [comment]
可以通过插件获取抓包数据，再将数据通过 python 暴露的接口传过去，参考：https://github.com/whistle-plugins/whistle.autosave
