### ISSUE TITLE
抓包只能抓取返回www，不能抓取api的接口，而且前端页面无法正常打开

### ISSUE THREAD

**Issue by janezeng123666** [avwo/whistle#884]
<img width="1138" alt="image" src="https://user-images.githubusercontent.com/129762462/230587011-70a6b64e-ccc1-49df-959e-aae08ade5360.png">
配置如下
<img width="1220" alt="image" src="https://user-images.githubusercontent.com/129762462/230587418-9d449eb5-4c08-452a-a59f-500ef84b54f4.png">
<img width="1019" alt="image" src="https://user-images.githubusercontent.com/129762462/230587937-f6c45984-8cc5-4f13-b8f2-eee84925d428.png">

**Comment by avwo** [comment]
命令行执行下：`w2 ca`
