### ISSUE TITLE
将钉钉的网络设置代理到 whistle 端口后登录提示网络异常

### ISSUE THREAD

**Issue by EpLiar** [avwo/whistle#885]
如图所示：

![image](https://user-images.githubusercontent.com/23559565/230629803-a6b0f54e-43fc-4185-87b3-255220c67cda.png)

设置地址和端口后，测试提示成功，登录提示网络异常

**Comment by EpLiar** [comment]
<img width="1110" alt="image" src="https://user-images.githubusercontent.com/23559565/230630024-3347057b-2e1e-43e0-8209-916917693706.png">

whistle 上展示的请求为测试代理时钉钉发出的

**Comment by avwo** [comment]
安装根证书了吗？如果没有在命令执行 `w2 ca` 后重启钉钉试试

**Comment by EpLiar** [comment]
<img width="762" alt="image" src="https://user-images.githubusercontent.com/23559565/230631243-2511d177-554d-4bfd-87ab-edd651c53184.png">

已确认安装 ca，依旧提示网络异常

**Comment by avwo** [comment]
那可能是钉钉设置了 ssl pinning

**Comment by EpLiar** [comment]
明白了，感谢回复
