### ISSUE TITLE
开了全局代理后 再开浏览器代理就代理不上

### ISSUE THREAD

**Issue by liufeisprit** [avwo/whistle#887]
w2 start --init之后 w2 proxy off 之后再开浏览器代理代理不上了

**Comment by avwo** [comment]
系统代理被关了，浏览器可以直接用 switchyomega 插件：https://wproxy.org/whistle/install.html

**Comment by liufeisprit** [comment]
用了这个插件的  whistle启动后发现还是连不上 抓不到请求

**Comment by avwo** [comment]
命令行执行 w2 ca

**Comment by liufeisprit** [comment]
发现是SwitchyOmega的问题 更新了下插件版本是可以了。
