### ISSUE TITLE
2.9.45 能否 publish ，比较依赖 .45 里面最新的特性

### ISSUE THREAD

**Issue by leslieJt** [avwo/whistle#888]
@avwo 
![image](https://user-images.githubusercontent.com/8391491/230826018-6d304d1f-cfaf-4841-ad49-046d2e35d14a.png)

**Comment by avwo** [comment]
预计今晚发布新版本，依赖哪些特性？

**Comment by leslieJt** [comment]
> 

新版会对 html 内容做校验是吧，只有实际返回内容为 html 格式才会去执行 htmlPrepend 是吧。
我们现在有些 ajax 接口，虽然数据是 json 但 http reponse 的 content-type 却是 html，导致 htmlPrepend 会作用到接口数据上。

**Comment by avwo** [comment]
已发布
