### ISSUE TITLE
w2启动反向代理后，访问该反向代理服务器时被w2的ui服务拦截

### ISSUE THREAD

**Issue by timshaw9791** [avwo/whistle#89]
如我根据git-book的 https://avwo.github.io/whistle/questions.html 中的第7条“如何实现反向代理的功能？”中所述，创建反向代理，例如 w2 restart -p 7070.
控制台提示，可以使用如下网址之一打开ui服务界面：
http://127.0.0.1:7070/
http://192.168.1.107:7070/
但当我
按照反向代理规则的说明新建如下rule并启用：（其中192.168.1.155为我本机的ip，我已经在8080端口开启一个web服务器）
localhost:7070 host://192.168.1.155:8080
192.168.1.155:7070 host://192.168.1.155:8080

结果，当我使用本机浏览器访问 http://localhost:7070/abc/ 时，能按预期返回被代理的8080端口的web服务器的结果，但当我使用 http://127.0.0.1:7070/abc/  或者 http://192.168.1.155:7070/abc/ 访问时则提示Cannot GET /abc

思考：
反向代理服务器角色和ui服务的url似乎是混在一起了，当前的ui服务使用的根上下文 http://127.0.0.1:7070/
建议:划出一个专用的上下文(context)比如 http://127.0.0.1:7070/whistle/ 给ui服务，当用户访问这个上下文时交给ui服务响应，其他上下文交给规则去处理（如反向代理规则等）

**Comment by avwo** [comment]
可以支持，周末发 `v1.6.0`，支持路径为:`http://localIP:whistlePort/_/xxx`的请求自动转成 :`http://localIP:whistlePort/xxx`，可以通过在whistle上配置规则 `localIP:whistlePort/xxx 127.0.0.1:6001` 实现反向代理的功能

**Comment by avwo** [comment]
[更新下whistle](https://avwo.github.io/whistle/update.html)

**Comment by aogg** [comment]
![image](https://user-images.githubusercontent.com/8998031/98186545-eb8ea580-1f49-11eb-914d-5ba166ff1eb4.png)
@avwo 还是没有正向代理成功，当前页面还是ui界面

启动命令是w2 start -p 80 -P 8999 -M keepXFF

**Comment by aogg** [comment]
还有反向代理的请求也会显示到network上吗
