### ISSUE TITLE
有个请求被提前终止的情况

### ISSUE THREAD

**Issue by fjqingyou** [avwo/whistle#890]
我遇到了个问题，不过我对 whistle 项目不太了解，只能将我发现的点反馈一下

环境
whistle 版本 2.9.46

whistle作为二级代理的存在，还有另外一个其他代理软件作为一级代理。请求先通过一级代理，再通过 CONNECT 将请求转发给 whistle 的二级代理。

whistle 在 vscode 中调试模式，以 run 参数方式启动，并在启动之前预先设置了几个调试断点

断点1： lib/util/patch.js 的 106 行
``` javascript
http.request = function (options) {
  var tunnelPath =
    options && options.method === 'CONNECT' && options.proxyTunnelPath;
  options = filterInvalidPath(options);
  if (!tunnelPath) {//在这里设置断点1
    return hackRequest(httpRequest, this, arguments, true);
  }
```
断点2、3：lib/https/index.js 的 1205 行 和 1213 行
``` javascript
          util.connect(
            {
              port: port,
              host: LOCALHOST,
              localAddress: LOCALHOST
            },
            function (err, s) {
              reqSocket = s;
              if (err || socket._hasError) {//在这里设置断点2
                return destroy(err);
              }
              tunnelTmplData.set(
                reqSocket.localPort + ':' + reqSocket.remotePort,
                getTunnelData(socket, clientIp, clientPort, isHttpH2)
              );
              receiveData = function (data) {
                clearTimeout(authTimer);//在这里设置断点3
                authTimer = null;
                socket.write(data);
                reqSocket.pipe(socket).pipe(reqSocket);
                socket.resume();
              };
              reqSocket.once('data', receiveData);
              reqSocket.write(chunk);
              abortIfUnavailable(reqSocket);
            }
          );
```

请求测试1：
````
客户端发起请求。
首先停留在 断点2 快速点继续运行（也尝试在这里等待5秒左右才点击继续运行，结果一致），
停留在 断点3 位置，再次快速的点击继续运行。 
客户端的请求已经被终止。断点1从未被触发过
````

请求测试2：
```
客户端发起请求
首先停留在 断点2 这次不急着点击继续运行了。我等待了大约10秒钟，没收集测试极限是多短的时间
停留在 断点1 的位置，再次快速点击继续运行。
客户端成功处理了本次请求。而断点3不曾触发过
```

**Comment by fjqingyou** [comment]
请问我还需要提供什么信息，可以更高效地辅助定位

**Comment by fjqingyou** [comment]
补充个特殊的点
测试1，不会在 Network 面板中留下任何信息
测试2，成功在 Network 面板中留下了请求的信息

**Comment by avwo** [comment]
导出抓包数据看下

**Comment by fjqingyou** [comment]
正常情况下走的是 测试1 的情况，不会在 Network 中留下信息。只能导出 测试2 的情况所产生的数据

[network.zip](https://github.com/avwo/whistle/files/11239724/network.zip)

**Comment by fjqingyou** [comment]
我尝试将 enable://capture  这个规则临时禁用掉，然后再次测试，成功处理了请求，然后排查后最终发现是根证书已经过期导致，重新安装whistle的根证书后正常工作了。

抱歉，耽误你时间了！

是否现在关闭这个 issue

**Comment by fjqingyou** [comment]
对了，因为证书导致失败的请求，是否也可以显示在Network中，方便以后排查？

**Comment by avwo** [comment]
Whistle 获取不到这部分信息，决定证书是否合法是浏览器做的

**Comment by fjqingyou** [comment]
我的意思是，例如访问 XXXX 的 https 站点的时候，浏览器不是先提交了一个 CONNECT 的明文请求给了 whistle，而非 https 的则直接明文。这部分的请求是否可在 network 记录。进而可以发现是不是客户端提前终止了请求之类的？

**Comment by a180285** [comment]
@avwo  确实，我在另一个 issue #904 下也遇到了类似的问题

就是 client 确实是尝试 TCP connect 了。但是在发送数据前主动断开了连接。
此时 UI network 页面没有任何提示。我一度以为没有产生任何连接， debug 了好久。直到加上 sniCallback 才看到确实有连接产生

希望 UI Network 页面能显示这种 TCP connect 信息。对后续 debug 应该会非常有帮助

**Comment by avwo** [comment]
已支持，更新下版本试试
