### ISSUE TITLE
无法使用抓包

### ISSUE THREAD

**Issue by huangguangpo** [avwo/whistle#892]
node 版本 16.17.0
已尝试多次重装whistle
运行 w2 start 后，可在浏览器访问 localhost:8899
但是无法访问 127.0.0.1:8899
导致后续的不管是设置系统代理 还是SwitchyOmega 都会导致页面无法访问。

**Comment by oliver-xie666** [comment]
试下本地hosts配置 `127.0.0.1 localhost`

**Comment by avwo** [comment]
`ping localhost` 看看
