### ISSUE TITLE
w2 无法代理

### ISSUE THREAD

**Issue by huangguangpo** [avwo/whistle#893]
node 版本 16.17.0
已尝试多次重装whistle
运行 w2 start 后，可在浏览器访问 localhost:8899
但是无法访问 127.0.0.1:8899
导致后续的不管是设置系统代理 还是SwitchyOmega 都会导致页面无法访问。

**Comment by huangguangpo** [comment]
![Snipaste_2023-04-17_16-25-11](https://user-images.githubusercontent.com/54012665/232428612-a3553c8a-44b5-4517-a598-e09d4dc9da69.png)

**Comment by huangguangpo** [comment]
![Snipaste_2023-04-17_16-24-49](https://user-images.githubusercontent.com/54012665/232428662-d3f2a73b-87ea-4127-9ac1-8d59be23b7c0.png)

**Comment by huangguangpo** [comment]
![Snipaste_2023-04-17_16-27-23](https://user-images.githubusercontent.com/54012665/232428771-39af9ee9-ce38-4f16-968f-c9e550f9cbfb.png)

**Comment by avwo** [comment]
试试 `w2 restart -p "127.0.0.1:8899"`

**Comment by avwo** [comment]
命令行执行 `w2 ca`

**Comment by huangguangpo** [comment]
OK
