### ISSUE TITLE
能否添加一个和fiddler类似的用户自定义注释功能

### ISSUE THREAD

**Issue by Winston1997** [avwo/whistle#894]
fiddler选择一批请求后，按m或者点击添加comments可以让用户自定义给请求批量添加注释，whistle能不能也加一个同样的功能，以便在遇到大规模请求抓包时好做注解

**Comment by avwo** [comment]
更新下 Whistle 和安装插件 whistle.comment：https://github.com/whistle-plugins/whistle.comment
