### ISSUE TITLE
如何将BODY参数提取为URL参数？

### ISSUE THREAD

**Issue by kajweb** [avwo/whistle#899]
现在我们的协议是 `a.com/api`
通过参数 `{ Action: 'xxx1', param: "test" }`、`{ Action: 'xxx2', param: "test2" }`区分请求到哪个后端控制器

我想将URL重定向，如
```
a.com/api   127.0.0.1/api/xxx1
a.com/api   127.0.0.1/api/xxx2
```
这类规则应该如何写？

**Comment by avwo** [comment]
``` txt
a.com/api   127.0.0.1/api/xxx1 includeFilter://b:/regexp1/i
a.com/api   127.0.0.1/api/xxx2 includeFilter://b:/regexp2/i
```
正则匹配的是 body 里面的原始内容，参考：https://wproxy.org/whistle/rules/filter.html

**Comment by kajweb** [comment]
这样看起来就需要为每条API配置一条规则了，有没有跟通用的方案？

**Comment by avwo** [comment]
你们请求的时候可以把部分body的参数放到 url

**Comment by kajweb** [comment]
好的，感谢
