### ISSUE TITLE
host 优先级没有 rule 高吗？

### ISSUE THREAD

**Issue by JimmyVV** [avwo/whistle#90]
我这里简单想将 一个 js 脚本从 rules 正则匹配中，抽出来，通过 host 进行映射。但实践中发现，host 的优先级比 rule 的优先级低，导致 host 不生效。或者说，我能通过 匹配 正则的顺序，实现映射的优先级吗？
比如：
```
/https?://example\.com/(.*\.(js|css|png|jpg|gif|jpeg|svg|blob).*)$/  file:///user/dev/$1
/^https?://example\.com/qq/sw\.js$/  10.100.64.201
```
这样，前面 pattern 优先级会高于第二个，从而实现路径的匹配。如果我想将第二个优先级提高，只需要把位置交换一下，实现：

```
/^https?://example\.com/qq/sw\.js$/  10.100.64.201
/https?://example\.com/(.*\.(js|css|png|jpg|gif|jpeg|svg|blob).*)$/  file:///user/dev/$1
```

或者说，现在 whistle 已经有现成的解决方案了？

**Comment by avwo** [comment]
rule和host是两个独立的规则，你这边的rule是用本地文件替换请求了，所以请求不会发到线上，设了host也没用；如果你想匹配某些规则请求中的部分不生效，可以用 [ignore](https://avwo.github.io/whistle/rules/ignore.html)：

	# 不需要正则，whistle会自动拼接剩余的路径(后面加不加 / 都可以)
	example.com file:///user/dev
	# 部分请求忽略file规则
	example.com/qq/sw.js 10.100.64.201 ignore://file

或者看下[xfile](https://avwo.github.io/whistle/rules/rule/xfile.html)，能不能满足你的需要，只要本地不存在就会自动请求线上资源，这时host也会生效。

**Comment by avwo** [comment]
还有很多情况不需要用正则匹配，可以参考下：[匹配方式](https://avwo.github.io/whistle/pattern.html)。
