### ISSUE TITLE
headerReplace 不生效

### ISSUE THREAD

**Issue by sunkeysun** [avwo/whistle#901]
cloud.tencent.com www.qq.com headerReplace://req.host:/.*/=proxy.cloud.tencent.com

配置以上规则， 请求到 www.qq.com  目标服务器的 host 头依旧是 www.qq.com，没有变成预期的 proxy.cloud.tencent.com
希望实现 转发请求的同时能够 指定 host 头

**Comment by avwo** [comment]
请求头的 `host` 字段比较特殊，可以用 `reqHeaders://host=proxy.cloud.tencent.com` 代替

**Comment by sunkeysun** [comment]
> 请求头的 host 比较特殊，可以用 `reqHeaders://host=proxy.cloud.tencent.com` 代替

好的，这种方式生效了，多谢
