### ISSUE TITLE
 socket connect timeout

### ISSUE THREAD

**Issue by WangXBruc** [avwo/whistle#902]
![image](https://github.com/avwo/whistle/assets/26540270/9fac41de-ddc5-4ca8-b1d7-a8889b1f64eb)
最近两年在使用 whistle 的时候，经常出现 socket connect timeout 报错，查看最近两年的 issues，有几个类似的问题，作者说是电脑网络问题然后关闭了，但我觉得肯定不是电脑网络问题，我身边使用 whistle 的人很多，大家都有这个问题。
而且，关闭 whistle 的情况下，网络很顺畅，开启 whistle，网络就时不时卡顿。
但是这个超时报错问题无法稳定复现，不定时就会出现一次，重启 whistle 就能解决，所以希望作者能帮忙看下。

**Comment by avwo** [comment]
有没有用 socks5 代理，用最新版本的 Whistle 试试（重新安装 Whistle 并重启）

**Comment by WangXBruc** [comment]
没有使用 socks5，我们是使用的 lightProxy，内嵌的whistle，版本升不上去。
![image](https://github.com/avwo/whistle/assets/26540270/d986bc59-f79d-41a0-8ace-7cc23ee2eda8)


> 有没有用 socks5 代理，用最新版本的 Whistle 试试（重新安装 Whistle 并重启）

**Comment by avwo** [comment]
直接用 whistle 观察一段时间看看，有问题再说
