### ISSUE TITLE
HTTPS 抓包下支付宝 iOS app 账单页经常无法加载

### ISSUE THREAD

**Issue by a180285** [avwo/whistle#904]
# 稳定复现流程 
* iOS 下上滑退出支付宝 app。并 kill app 后台
* 连接 whistle 拦截 HTTPS 
* 重新打开支付宝，进入‘我的’ - ‘账单’
* 发现无法加载

# 目前观察到的现象
* 如果连接 whistle 之前没有 kill 支付宝后台，则有概率可以打开‘账单’页面，偶尔可以正常解包 https 内容
* 通过 sni-callback 发现，在无法打开‘账单’的情况下，app 好像会不断重试连接：mgw.alipay.com ，感觉是 app 不知道什么原因主动断开了连接。可能都没有发送数据。（但是结合上面一条，偶尔能解包，就没有想明白问题出在哪里）

**Comment by avwo** [comment]
估计是 ssl pinning，或 tls 指纹问题

**Comment by a180285** [comment]
关掉 `Capture TUNNEL CONNECTS` 确实可以，但就不能 https 解包了。
我主要就是想 https 解包 app 账单这个请求。

你前面提到`估计是 ssl pinning，或 tls 指纹问题` 有什么解决，或者绕过。同时可以解包这个请求的办法吗

**Comment by avwo** [comment]
自己网上搜搜，比如找一个可以绕开 ssl pinning 的模拟器
