### ISSUE TITLE
如何在 tunnel 成功连接 10 s 后主动中断该连接

### ISSUE THREAD

**Issue by a180285** [avwo/whistle#905]
比如我希望在某个 tunnel 成功后，让其通信一段时间，但是希望在 10 s 之后主动中断这个 tunnel

有办法可能实现吗

**Comment by avwo** [comment]
可以通过页面右键菜单 abort，或者自己用插件接管请求

**Comment by a180285** [comment]
是的，通过 plugin 的话，可以帮忙提供一下大致思路吗？我看了一下 plugin 的说明页面。没有找到相关内容。

比如，我可以实现 plugin  的哪个接口，保存什么信息，然后 10 s 后可以通过调用哪个接口来 abort 这个连接。

抱歉，因为 JS 使用比较少。所以可能需要一些更多一些提示。

**Comment by avwo** [comment]
https://github.com/whistle-plugins/examples/blob/master/whistle.test-server/lib/server.js#L59
``` js
setTimeout(() => {
  socket.destroy();
}, 10000);
```

**Comment by a180285** [comment]
感谢，我后面参考试试呢

**Comment by a180285** [comment]
worked, thx
