### ISSUE TITLE
req.getReqSession、req.getSession 无响应

### ISSUE THREAD

**Issue by Foolyou** [avwo/whistle#907]
最新版 whistle + whistle.autosave 搭配使用时，无法保存数据。
经debug，发现是 getSession 一直没有返回。

<img width="981" alt="image" src="https://github.com/avwo/whistle/assets/6925615/07166dcc-f3b4-4d2d-a2fd-154b4a2a645d">

只有 `autosave request` 这条 log 打出来。

在自定义插件中调用 `getReqSession`  `getSession` 也没有响应。

**Comment by avwo** [comment]
Whistle 的 Network 可以看到抓包吗，看看 Overview 是否匹配了 `whistle.autosave`

**Comment by Foolyou** [comment]
![image](https://github.com/avwo/whistle/assets/6925615/eab342d9-547f-4ec7-bf39-19d8363756b9)
可以抓包，能看到 whistle.autosave 被匹配到了。

**Comment by Foolyou** [comment]
<img width="584" alt="image" src="https://github.com/avwo/whistle/assets/6925615/ddfb3a4d-d8d2-4453-a7f4-67ee16003ec7">
在 `whistle/lib/plugins/load-plugin.js` 的 req.getSession 方法中加 log 也是 getSession 函数回调未被执行。

**Comment by avwo** [comment]
新版没改动这块，我这边也是 ok 的，你看看 whistle.autosave 配置存储目录（目录要确保存在，不会自动创建）及启用自动保存抓包数据

**Comment by Foolyou** [comment]
目前追到的问题点在于 node 版本 v20.1.0 下，`requestSessions` 方法中调用 `requestData` 获取 `/cgi-bin/get-session`，而 `get-session` 返回的结果为空。

在 v18.15.0 下没有问题。

**Comment by Foolyou** [comment]
刚试过了，v20.2.0下也无此问题

**Comment by avwo** [comment]
Node 20.1.0 部分 API 有 breaking change，Whistle 下个版本做下兼容

**Comment by avwo** [comment]
重新安装 Whistle 并重启 `npm i -g whistle && w2 restart`

**Comment by t880216t** [comment]
nohost中使用，还是有此问题，版本如下：

Whistle for Web Developers.
Version: [2.9.102]

**Comment by avwo** [comment]
> nohost中使用，还是有此问题，版本如下：
> 
> Whistle for Web Developers. Version: [2.9.102]

Nohost Admin 里面 Whistle 插件是获取不到抓包数据，要安装在账号的实例里面才行
