### ISSUE TITLE
关于保存请求的body体到文件的问题

### ISSUE THREAD

**Issue by Mrqqeat** [avwo/whistle#912]
有一阵子没用过保存了，我记得之前直接在body的右上角有个download按钮点击就能下载下来。
新版本发现点击后是弹出一个窗口然后写入到value里，不知道怎么下载到文件，因为数据是二进制的，所以复制粘贴应该是行不通..

**Comment by Mrqqeat** [comment]
咋关了啊..

**Comment by avwo** [comment]
git 自动关的，更新下最新版本试试

**Comment by Mrqqeat** [comment]
> git 自动关的，更新下最新版本并重启试试

我更新到2.9.50版本了，但是在Response里面的download不知道要怎么将数据下载下来
![image](https://github.com/avwo/whistle/assets/12445017/45b08774-bac7-45cd-b1c3-945b0bc59c57)
我点击这个弹出来的窗口好像是只能存到value里面，但是从value里面export导出的话也不能只导出body数据

**Comment by avwo** [comment]
2.9.51

**Comment by Mrqqeat** [comment]
> 2.9.51

OK了，手动更新了一下可以了，谢谢
