### ISSUE TITLE
有多个http-proxy，麻烦支持下

### ISSUE THREAD

**Issue by aogg** [avwo/whistle#913]
有多个上级代理目前只能一个，需要别的端口负载均衡才能实现，麻烦支持下

**Comment by aogg** [comment]
https://v2.gost.run/load-balancing/
类似这样

**Comment by avwo** [comment]
用两种方式：
1. 通过命令行启动 `--cluster` 启动 cluster 模式，但不支持查看抓包
2. 用 nohost：https://github.com/Tencent/nohost
