### ISSUE TITLE
局域网能访问 其他人的 经过 whistle 代理后的请求吗。

### ISSUE THREAD

**Issue by wangyan666** [avwo/whistle#914]
局域网中，一台机器的某网页（如 192.168.11.1:3000） 使用 whistle 对请求/响应 进行修改（如修改了响应体），局域网访问 192.168.11.1:3000 看到的还是修改响应前的结果。
请问有无方法让局域网也能看到修改后的结果呢。

**Comment by avwo** [comment]
你是怎么修改的

**Comment by avwo** [comment]
可以把 whistle 作为局域网的公共服务
