### ISSUE TITLE
302重定向不跳转

### ISSUE THREAD

**Issue by Amilelne** [avwo/whistle#916]
访问原链接的时候，是个302请求，在回包里带了重定向的location，但是没有发起请求
http://mpvideo.qpic.cn/0bc3tmabyaaajaaas23lejsfbg6ddsnqahaa.f10102.mp4?dis_k=8254e49074f3c5a270588fe1b771fc7e&dis_t=1685501391&play_scene=10110&auth_info=Tbjmk7dxNbz3s/5XZobzustXdhdCNmYTNxlYJToKVBNzbjZWIkIVOQ==&auth_key=25f19610c9beb2adae8fbbe9c4d508bb&vid=wxv_2938483559076429827&format_id=10102&support_redirect=1&mmversion=15.0.2360

**Comment by avwo** [comment]
重定向跳转行为是浏览器做的，Whistle 默认只是透传，不做这些额外操作
