### ISSUE TITLE
whistle能否实现charles的map remote能力

### ISSUE THREAD

**Issue by nbutmickey** [avwo/whistle#917]
如下规则确实生效了，但是没有响应数据：
<img width="839" alt="image" src="https://github.com/avwo/whistle/assets/30484035/f5869059-4b29-4834-b2c5-89a92b02c33c">
url确实被改写了，但是请求被aborted掉了
<img width="1787" alt="image" src="https://github.com/avwo/whistle/assets/30484035/a5988762-4487-49c9-9ce2-e57bf807e1d6">

**Comment by nbutmickey** [comment]
想问下，我的配置规则是争取的吗

**Comment by nbutmickey** [comment]
想问下，我的配置规则是正确的吗

**Comment by avwo** [comment]
没问题

**Comment by nbutmickey** [comment]
感谢，问题已解决，重启以下电脑即可

**Comment by nbutmickey** [comment]
1、https相关数据包的抓取要配置正确
2、重启电脑即可
