### ISSUE TITLE
请教作者大大：能否像Chales一样只抓取某个https协议的请求？

### ISSUE THREAD

**Issue by Main12138** [avwo/whistle#918]
这边也是看了很久的文档。可能是我没找到对应的地方。请求指路！！！

![image](https://github.com/avwo/whistle/assets/77869583/6880a282-17ba-4efc-9112-56d187920ec6)

**Comment by avwo** [comment]
三种方式：
1. 隐藏抓包：`* enable://hide excludeFilter://www.baidu.com`
2. switchomega 配置白名单
3. 系统代理配置白名单 `w2 proxy -x "www.baidu.com"`

**Comment by Main12138** [comment]
感谢大佬的解答。我觉得我一开始没有描述清楚，再劳烦看下我的描述！
![image](https://github.com/avwo/whistle/assets/77869583/bcd6db98-8e73-4cb6-9f9d-b7d919cb9658)

**Comment by Main12138** [comment]
希望通过配置的方式来开启对部分请求的Https拦截功能

**Comment by avwo** [comment]
两种方式：
1. 开启全局捕获，通过 `disable://capture  www.baidu.com github.com`  禁用部分域名
2. 关闭全局捕获，通过  `enable://capture  www.baidu.com github.com`  开启部分域名

**Comment by Main12138** [comment]
成了。非常感谢！
