### ISSUE TITLE
抓请求的 host 是 tunnel://

### ISSUE THREAD

**Issue by ChanWahFung** [avwo/whistle#919]
![image](https://github.com/avwo/whistle/assets/42034811/eb289c7a-22f8-4be2-b5b2-9edc4f8d41ed)
这种情况怎么解决，手机的代理和证书都配置和安装了。部分的https请求能抓，但是有部分是截图的情况

**Comment by avwo** [comment]
部分客户端设置了 ssl pinning，如果不影响使用可以忽略这部分错误
