### ISSUE TITLE
whistle有类似SwitchHost远程拉取host的功能吗？有类似插件也行？

### ISSUE THREAD

**Issue by xiaowanzixll** [avwo/whistle#923]
whistle有类似SwitchHost远程拉取host的功能吗？有类似插件也行？
![image](https://github.com/avwo/whistle/assets/21018415/1b432fd3-69bd-4907-96ea-04972fff44c8)

**Comment by avwo** [comment]
https://wproxy.org/whistle/rules/@.html

**Comment by avwo** [comment]
10秒更新一次，手动保存规则会立即调用，如果想实时生效，需要自己开发插件，参考：https://github.com/whistle-plugins/examples/tree/master/whistle.test-rules

**Comment by xiaowanzixll** [comment]
我是在界面新建的规则，通过@http://xxx输入的，如果想确定一下whistle拉取的文件内容是啥，可以去哪里查看呢？

**Comment by avwo** [comment]
浏览器访问
