### ISSUE TITLE
resBody在chrome dev tools Network 的pesponse和preview中没有显示

### ISSUE THREAD

**Issue by dxcqcv** [avwo/whistle#925]
比如我有以下规则，然后我在`whistle`中`network`面板下的`inspectors`里的Body`中能看到拦截的返回，但在`chrome`的`network`中返回是空白的，这是为什么？

```rule
#/.*\/hitokoto/ resCors://*  statusCode://202 resBody://{ld_current.json} 
```

```value
//ld_current.json

{
  "code": "20001",
  "message": "Success123"
}
```

**Comment by avwo** [comment]
浏览器 Console 有报错吗

**Comment by dxcqcv** [comment]
> 浏览器 Console 有报错吗

没有，只是空白

**Comment by avwo** [comment]
应该是 `202`  这个响应状态码的问题，改成 `200` 或者将 `statusCode://202 resBody://{ld_current.json}` 改成 `file://{ld_current.json}`

**Comment by dxcqcv** [comment]
> 应该是 `202` 这个响应状态码的问题，改成 `200` 或者将 `statusCode://202 resBody://{ld_current.json}` 改成 `file://{ld_current.json}`

用`file://`是可以的，我只是好奇为什么`resBody://`会出现返回不出现的情况，返回码`202`是我特意改的，因为一开始我以为规则没有生效，用`200`也是返回不出现
