### ISSUE TITLE
PUT请求设置resSpeed不起作用

### ISSUE THREAD

**Issue by miloluojia** [avwo/whistle#926]
我配置了下面的规则，resSpeed分别设置了0，1，0.1，但是对实际的请求，速度没有变化
/https://oss-me-east-1.aliyuncs.com/pk-arab/.*/ resSpeed://0.1

尝试去mock了GET请求，就是正常的

**Comment by avwo** [comment]
有请求内容吗，reqSpeed 只会作用于请求内容，没有请求内容可以试试 `reqDelay`

**Comment by miloluojia** [comment]
邮件我已收到

**Comment by miloluojia** [comment]
邮件我已收到
