### ISSUE TITLE
抓包app内 https的时候报错

### ISSUE THREAD

**Issue by xiaohuaqqqq** [avwo/whistle#927]
抓包app内 https的时候报错，并且配置了代理之后无法正常访问
![A6982CA1-19F2-4765-B5FD-B6E6D66BC394](https://github.com/avwo/whistle/assets/136408575/2d747fe1-4712-423d-82f0-24d0536853aa) 
但是我抓包别的https时没问题，配置证书https都开启了

**Comment by avwo** [comment]
ssl pinning
