### ISSUE TITLE
求一个插件可以自定义Network中的列

### ISSUE THREAD

**Issue by bugaio** [avwo/whistle#928]
文档上说

> 可以通过 Network 抓包列表右键菜单 / Open / Source 获取想要的 Data Key，如：req.headers.accept 获取请求头 accept 的值，res.headers.x-server 获取响应头 x-server 的值

实际我上 想要一个 query  和 path的列

在  `/ Open / Source `拿到  `path`  包含 `query`,  
能否 有个插件能 可以对 `/ Open / Source `拿到的数据 再做处理后  添加到 新列上呢?

> 关于自己写插件,  本人着实有点菜,  就 ... 伸手党了

**Comment by avwo** [comment]
参考这个插件：https://github.com/whistle-plugins/examples/tree/master/whistle.retcode

**Comment by bugaio** [comment]
老板,  我尝试 使用 你参考 你推荐的 插件,  已经实现我想要的功能了,  
但是还有一点, 我希望能  和 NetWork上的 URL这一列一样, 可以 设置 `min-width`, 
我看了下 您的代码,  发现是 
> `lib/util/index.js`中
> `width: Math.min(360, Math.max(parseInt(column.width) || 120, 70))`
那能否支持  插件的列 设置 min-width呢?

**Comment by avwo** [comment]
除了 URL ，其它列的宽度不支持自适应，用户可以通过右键表头修改宽度
<img width="298" alt="image" src="https://github.com/avwo/whistle/assets/11450939/fad7564b-de0b-4d3e-b1ca-809654e1c8b0">
