### ISSUE TITLE
手机调试，请求报405 not allow 错误，关闭代理调试，又正常

### ISSUE THREAD

**Issue by Michaelooo** [avwo/whistle#93]
连接whistle调试手机H5,是后台的一个rq请求，路径都是对的，但是报405错误。
关闭了代理后，又可以正常返回。
百度了一些资料，不求甚解，求给些思路

**Comment by avwo** [comment]
请求url发我下，或者看下是不是中间用whistle改了请求的method

**Comment by Michaelooo** [comment]
@avwo 内网请求，没法发出去。不过，你说的这种可能我可以今天看下
