### ISSUE TITLE
DNS Lookup Failed

### ISSUE THREAD

**Issue by alanhg** [avwo/whistle#930]
![image](https://github.com/avwo/whistle/assets/9245110/22e61e72-9362-4d22-9770-ec113ddd66a8)

<img width="752" alt="image" src="https://github.com/avwo/whistle/assets/9245110/e001f04d-5bf3-4616-91a3-53420b9bfef4">

奇怪，为啥这些访问会报这个查询超时错.w2 start我并没有设置过DNS。

**Comment by avwo** [comment]
默认使用系统设置的 dns，重启电脑看看
