### ISSUE TITLE
whistle的请求替换和插件的功能不能同时起效

### ISSUE THREAD

**Issue by jomeswang** [avwo/whistle#931]
你好，我想咨询一个问题。就是我想使用whistle来使用本地的资源代理线上的域名，然后再基于本地的接口的返回相应再次去做修改，于是我使用制作了一个插件，在插件的rulesServer部分res.end('* https://127.0.0.1:8081/')返回了代理，并且在插件的server部分修改了接口的返回相应，但是实际用下来插件的server部分没有起效，想问一下有什么办法可以做到代理本地并修改代理的返回数据嘛

**Comment by jomeswang** [comment]
mark 一下 作者大大有空帮忙看一下哈 非常感谢～

**Comment by avwo** [comment]
参考这个插件：https://github.com/whistle-plugins/examples/tree/master/whistle.set-rules-according-body
