### ISSUE TITLE
我不想直接改动网络请求，但希望能把上行加密数据的解包结果显示在抓包界面，应该如何操作？

### ISSUE THREAD

**Issue by zhangyanrui** [avwo/whistle#932]
如题

**Comment by avwo** [comment]
参考这个：https://github.com/whistle-plugins/examples/tree/master/whistle.test-pipe

**Comment by zhangyanrui** [comment]
好的。谢谢，我试一下

**Comment by zhangyanrui** [comment]
> 参考这个：https://github.com/whistle-plugins/examples/tree/master/whistle.test-pipe

好的，谢谢！我试一下。
