### ISSUE TITLE
设置 socks server 模式，通过 socks 转发的请求默认走 tunnel，这个 tunnel 能被抓包解析吗

### ISSUE THREAD

**Issue by HOWIE-CH** [avwo/whistle#933]
问题：如题，设置 socks server 模式，看文档里的请求默认走 tunnel，这个 tunnel 能被解析吗
版本： whistle@2.9.52
启动命令：sudo w2 start -M socks --socksPort 8999
                  sudo w2 start -M "capture|socks" --socksPort 8999

**Comment by avwo** [comment]
1. 启动不需要 `sudo`
2. socks 代理需要通过规则 `* enable://capture` 开启捕获 HTTPS 请求

**Comment by HOWIE-CH** [comment]
嗯，通过规则 * enable://capture 可以捕获
但目前安卓手机没越狱没装证书，只需要抓http的就行，如果使用 * enable://capture ，手机里部分https的请求是失败的，设置只需要http的enable://capture就行
这个配置这么写么
/^http:.*/ enable://capture
http://*/ enable://capture
$http://*/ enable://capture
感觉这三种都没效果样的

**Comment by avwo** [comment]
tunnel 请求暂不支持通过请求协议过滤，你可以将所有请求 capture，再通过配置下面规则进行过滤：
``` txt
disable://capture domain1 domain2 domain3
```

**Comment by HOWIE-CH** [comment]
嗯嗯，好的，谢谢大佬
