### ISSUE TITLE
关于包名中的scope部分可以支持自定义嘛

### ISSUE THREAD

**Issue by jomeswang** [avwo/whistle#934]
<img width="848" alt="image" src="https://github.com/avwo/whistle/assets/56079587/2b9dcb18-8f5b-4d43-9c09-1fafc80ac43f">
问题如题，但看到文档中，只支持@org这一个形式，希望能够支持自定义scope～

**Comment by avwo** [comment]
目的是什么？npm 包就这两种形式

**Comment by jomeswang** [comment]
由于公司内部搭建了私有的npm仓库，规定scope不能与npm仓库的一致，而@org这一个scope已经被使用过了，没办法上传到公司内部的私有仓去，希望看看能不能稍微支持一下包名的自定义类似@test～

**Comment by jomeswang** [comment]
不好意思看错了 已解决～
