### ISSUE TITLE
为什么通过npm run start指令启动抓取不到任何请求

### ISSUE THREAD

**Issue by shaonianla1997** [avwo/whistle#935]
通过全局安装的w2可以正常抓取数据，但是通过npm run start在源代码中启动就抓不到数据

**Comment by avwo** [comment]
是不是端口不一样

**Comment by shaonianla1997** [comment]
> 是不是端口不一样

端口也是8899，把w2关了才从源码里启动的

**Comment by avwo** [comment]
`lsof -i:8899` 看下端口被哪个进程占用了

**Comment by shaonianla1997** [comment]
> `lsof -i:8899` 看下端口被哪个进程占用了

直接执行node bin/whistle.js run --init，可以正常抓包了
