### ISSUE TITLE
Why HTTPS > HTTP in my Protocol？

### ISSUE THREAD

**Issue by lizy-CZ** [avwo/whistle#939]
![image](https://github.com/avwo/whistle/assets/103976180/d657798c-7de7-4c14-a6a9-e3a7c97cca76)

**Comment by avwo** [comment]
配了 host，且 https 访问失败会自动切换到 http 请求，可以通过 `disable://auto2http` 关闭

**Comment by lizy-CZ** [comment]
Thank a lot
