### ISSUE TITLE
rulesFile:// 怎么读取Request Payload参数

### ISSUE THREAD

**Issue by imadentive** [avwo/whistle#94]
动态规则：rulesFile://中的body，到底有什么字段，不能console.log(body)查看具体的。我所有的接口，都是一样url，不同的是Request Payload中参数，但是不知道怎么读取。

**Comment by avwo** [comment]
有个全局变量body，可以获取请求数据，https://avwo.github.io/whistle/rules/rulesFile.html

**Comment by imadentive** [comment]
确定body里面有内容吗？
if (body) {
    rules.push('/./ reqDelay://30000');
}
if (body==‘’) {
    rules.push('/./ reqDelay://30000');
}都不执行

**Comment by avwo** [comment]
执行下 `console.log(body)`，并在Network -》Log-> Server里面看下有没有打印出来，whistle版本太老的话不支持，如果没有的话重新安装下whistle，并重启 `w2 restart`看看

**Comment by imadentive** [comment]
已升级到最新版。console.log(body==='')，打印true，说明是‘’。并不能读取Request Payload内容

**Comment by avwo** [comment]
get请求吧，打印下method

**Comment by imadentive** [comment]
方法是POST没错的

**Comment by avwo** [comment]
确定是我这边的问题，有个依赖没有更新，这周末发个版本fix掉

**Comment by imadentive** [comment]
Good,Thanks.
