### ISSUE TITLE
无法抓取数据，已经在手机安装并信任证书

### ISSUE THREAD

**Issue by WangJiu-czy** [avwo/whistle#940]
![image](https://github.com/avwo/whistle/assets/59927567/553a9071-e52e-4001-8963-d66852c7efde)

---
使用qx等代理软件可以正常抓取数据包，但是设置whistle为代理，打开需要抓包的网站提示NetWorkError: A networ error occurre.

**Comment by avwo** [comment]
导出抓包数据看下

**Comment by WangJiu-czy** [comment]
![image](https://github.com/avwo/whistle/assets/59927567/a6368bb7-5d8e-45b6-874e-e0fff63942e0)
重定向到这个红色 的请求之后就无法跳转，手机上的页面提示NetWorkError: A networ error occurre.

之前这个连接用的http就可以正常抓包，但现在使用的是https就出现这种情况。


使用AnyProxy也是同样的状况

## 导出红色这一行的数据
---
[
  {
    "id": "1689598362065-015",
    "url": "m.cdcd.plus:443",
    "startTime": 1689598368082,
    "rules": {},
    "req": {
      "ip": "125.94.168.176",
      "port": 18027,
      "method": "CONNECT",
      "httpVersion": "1.1",
      "headers": {
        "host": "m.cdcd.plus",
        "proxy-connection": "keep-alive",
        "connection": "keep-alive"
      },
      "rawHeaderNames": {
        "host": "Host",
        "proxy-connection": "Proxy-Connection",
        "connection": "Connection"
      },
      "rawHeaders": {
        "Host": "m.cdcd.plus",
        "Proxy-Connection": "keep-alive",
        "Connection": "keep-alive"
      }
    },
    "res": {
      "headers": {
        "x-server": "whistle"
      },
      "ip": "127.0.0.1",
      "statusCode": 502,
      "_hasError": true,
      "base64": "RnJvbTogd2hpc3RsZUAyLjkuNTMNCk5vZGU6IHYxNi4yMC4xDQpIb3N0OiBjenkNCkRhdGU6IDcvMTcvMjAyMywgODo1Mjo0OCBQTQ0KRXJyb3I6IHJlYWQgRUNPTk5SRVNFVAogICAgYXQgVENQLm9uU3RyZWFtUmVhZCAobm9kZTppbnRlcm5hbC9zdHJlYW1fYmFzZV9jb21tb25zOjIxNzoyMCk="
    },
    "isHttps": true,
    "rulesHeaders": {},
    "version": "2.9.53",
    "nodeVersion": "16.20.1",
    "endTime": 1689598368082,
    "responseTime": 1689598368082,
    "resError": true,
    "method": "CONNECT",
    "hostIp": "127.0.0.1",
    "clientIp": "125.94.168.176",
    "date": "2023/7/17 20:52:48.082",
    "clientPort": 18027,
    "contentEncoding": "",
    "body": " + ",
    "result": 502,
    "type": "",
    "time": "",
    "download": "",
    "response": "",
    "request": "",
    "dns": "",
    "protocol": "HTTP",
    "hostname": "Tunnel to",
    "path": "m.cdcd.plus:443",
    "order": 11,
    "hide": false,
    "lost": true,
    "selected": true,
    "active": true
  }
]
---

**Comment by WangJiu-czy** [comment]
我发现抓包的这个目标服务器ip 变成了127.0.0.1

**Comment by WangJiu-czy** [comment]
抓包没报红了，但是网页还是显示同样的错误
[
  {
    "id": "1689672349394-563",
    "url": "m.cdcd.plus:443",
    "startTime": 1689672349395,
    "rules": {
      "disable": {
        "files": null,
        "url": "disable://capture",
        "not": false,
        "name": "disable",
        "root": null,
        "isRegExp": false,
        "protocol": null,
        "pattern": "m.cdcd.plus/",
        "matcher": "disable://capture",
        "raw": "m.cdcd.plus disable://capture",
        "isDomain": true,
        "rawPattern": "m.cdcd.plus",
        "lineProps": {},
        "isTpl": false,
        "list": [
          {
            "files": null,
            "url": "disable://capture",
            "not": false,
            "name": "disable",
            "root": null,
            "isRegExp": false,
            "protocol": null,
            "pattern": "m.cdcd.plus/",
            "matcher": "disable://capture",
            "raw": "m.cdcd.plus disable://capture",
            "isDomain": true,
            "rawPattern": "m.cdcd.plus",
            "lineProps": {},
            "isTpl": false
          }
        ]
      },
      "plugin": {
        "files": null,
        "url": "whistle.autosave://none",
        "not": false,
        "name": "plugin",
        "root": "/usr/lib/node_modules/whistle.autosave",
        "wildcard": {
          "preMatch": {},
          "path": "/",
          "hasQuery": false,
          "isExact": false
        },
        "isRegExp": false,
        "protocol": null,
        "pattern": "*/",
        "matcher": "whistle.autosave://none",
        "raw": "* whistle.autosave://none",
        "isDomain": true,
        "rawPattern": "*",
        "lineProps": {},
        "isTpl": false,
        "list": [
          {
            "files": null,
            "url": "whistle.autosave://none",
            "not": false,
            "name": "plugin",
            "root": "/usr/lib/node_modules/whistle.autosave",
            "wildcard": {
              "preMatch": {},
              "path": "/",
              "hasQuery": false,
              "isExact": false
            },
            "isRegExp": false,
            "protocol": null,
            "pattern": "*/",
            "matcher": "whistle.autosave://none",
            "raw": "* whistle.autosave://none",
            "isDomain": true,
            "rawPattern": "*",
            "lineProps": {},
            "isTpl": false
          }
        ]
      }
    },
    "req": {
      "ip": "125.94.168.176",
      "port": 17294,
      "method": "CONNECT",
      "httpVersion": "1.1",
      "headers": {
        "host": "m.cdcd.plus",
        "proxy-connection": "keep-alive",
        "connection": "keep-alive",
        "x-forwarded-for": "125.94.168.176"
      },
      "rawHeaderNames": {
        "host": "Host",
        "proxy-connection": "Proxy-Connection",
        "connection": "Connection"
      },
      "rawHeaders": {
        "Host": "m.cdcd.plus",
        "Proxy-Connection": "keep-alive",
        "Connection": "keep-alive",
        "x-forwarded-for": "125.94.168.176"
      }
    },
    "res": {
      "headers": {
        "proxy-agent": "whistle"
      },
      "ip": "47.57.189.158",
      "port": "443",
      "rawHeaderNames": {
        "proxy-agent": "proxy-agent"
      },
      "statusCode": 200,
      "rawHeaders": {
        "proxy-agent": "whistle"
      }
    },
    "isHttps": true,
    "rulesHeaders": {},
    "version": "2.9.53",
    "nodeVersion": "16.20.1",
    "dnsTime": 1689672349395,
    "requestTime": 1689672349395,
    "endTime": 1689672349421,
    "responseTime": 1689672349421,
    "method": "CONNECT",
    "hostIp": "47.57.189.158",
    "clientIp": "125.94.168.176",
    "date": "2023/7/18 17:25:49.395",
    "clientPort": 17294,
    "serverPort": "443",
    "contentEncoding": "",
    "body": " + ",
    "result": 200,
    "type": "",
    "time": "26ms",
    "download": "0ms",
    "response": "26ms",
    "request": "0ms",
    "dns": "0ms",
    "protocol": "HTTP",
    "hostname": "Tunnel to",
    "path": "m.cdcd.plus:443",
    "order": 26,
    "hide": false,
    "lost": true,
    "selected": true,
    "active": true
  }
]
![image](https://github.com/avwo/whistle/assets/59927567/29cb79e7-a941-4c40-b5e5-20dc18d7c11b)

**Comment by avwo** [comment]
ssl pining 问题，具体自己网上搜下

**Comment by WangJiu-czy** [comment]
> ssl pining 问题，具体自己网上搜下

我刚刚去查了，但是基本都是说给手机安装框架模块，改app里面的证书。

但是我这个只是IOS微信里面打开的一个网页

**Comment by avwo** [comment]
重启微信试试

**Comment by WangJiu-czy** [comment]
> 重启微信试试

手机和微信都重启了，whistle服务也是重启了，但还是不行

**Comment by avwo** [comment]
配下面的规则试试，如果没问题就是 ssl pinnig：
``` txt
**.myqcloud.com disable://capture
```

**Comment by WangJiu-czy** [comment]
> 配下面的规则试试，如果没问题就是 ssl pinnig：
> 
> ``` txt
> 
> **.myqcloud.com disable://capture
> 
> ```

还是不行，我尝试使用surge抓包数据，找到跳转后的请求，就可以直接打开。

但是换了一个微信后就无法打开这个链接

不知道是不是网关的原因
