### ISSUE TITLE
whistle配置的 ignore 转发规则未生效

### ISSUE THREAD

**Issue by captainamari** [avwo/whistle#941]
whistle转发规则设置了以下3条：
```
www.test.com/ts:auth/tauth/info.ashx ignore://file|host
www.test.com/test-tools-api/autotest/tunnel ignore://file|host
www.test.com 127.0.0.1:8086
```

本地vue项目运行在 8086 端口，浏览器页面调试请求的接口是远程服务器的接口，apiUrl是：`www.test.com/test-tools-api/autotest/tunnel`，但是返回状态码502，抓包看到该请求server ip是127.0.0.1。

我的设置操作有：
1. 本地启动vue项目，运行在 127.0.0.1:8086
2. 电脑系统设置代理服务器：127.0.0.1:8087
3. 启动whistle，并运行在 8087 端口
4. 设置并应用上面的3条转发规则。

响应报错内容：
```
From: whistle@2.9.49
Node: v18.16.0
Host: PC1
Date: 2023/7/17 16:35:20
Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (node:net:1494:16)


<a href="javascript:;" onclick="location.reload()">Reload this page</a>
```

想问下这样设置对吗？为什么好像没有ignore具体路径下的请求？

**Comment by avwo** [comment]
抓包看下 Overview 匹配哪些规则了，如果有规则没匹配仔细看下匹配 URL 的表达式是否写对了

**Comment by captainamari** [comment]
抓包看是匹配到了ignore的转发规则的
![image](https://github.com/avwo/whistle/assets/109799765/420892b9-01d2-4a8e-8095-9e8cf8ddf0f2)

**Comment by tailgo** [comment]
> 抓包看是匹配到了ignore的转发规则的 ![image](https://user-images.githubusercontent.com/109799765/253934962-420892b9-01d2-4a8e-8095-9e8cf8ddf0f2.png)

![image](https://github.com/avwo/whistle/assets/15409302/30394168-b77f-4000-8f50-462afb0b8f83)
勾选下这个再看看

**Comment by avwo** [comment]
你这个没问题，ping 下请求域名看看 ip 是什么

**Comment by captainamari** [comment]
ping请求域名ip是127.0.0.1。
找到原因了，是我之前在host文件中设置了 `127.0.0.1 www.test.com` ，删掉之后能正常请求域名了。
感谢哈！
