### ISSUE TITLE
whistle无法抓到node发起的请求，这是为什么？如何解决

### ISSUE THREAD

**Issue by 779102260** [avwo/whistle#943]
代码如下：

```
// 引入http模块
const http = require('https');

// 目标URL
const url = 'https://www.baidu.com';

// 发起HTTP GET请求
http.get(url, (response) => {
  // 设置响应数据编码为UTF-8
  response.setEncoding('utf8');

  let data = '';

  // 当接收到数据时触发
  response.on('data', (chunk) => {
    data += chunk;
  });

  // 数据接收完成时触发
  response.on('end', () => {
    console.log('收到的数据：', data);
  });

}).on('error', (error) => {
  console.error('请求发生错误：', error.message);
});
```

正常浏览器的包是可以抓到的。
加了命令行代理后curl抓包可以抓到，但是node的还是不行
```
export https_proxy=https://127.0.0.1:8899;
export http_proxy=http://127.0.0.1:8899;
export all_proxy=socks5://127.0.0.1:8899;
export NODE_TLS_REJECT_UNAUTHORIZED=0
```

**Comment by avwo** [comment]
应该是 Node 请求不走系统代理，引入这个 npm 包试试：https://github.com/avwo/lack-proxy

**Comment by 779102260** [comment]
> 应该是 Node 请求不走系统代理，引入这个 npm 包试试：https://github.com/avwo/lack-proxy

大佬，这个包原理是啥，我看好像啥也没做
<img width="298" alt="image" src="https://github.com/avwo/whistle/assets/16102900/8a58967d-ceb6-4b61-b5e5-cecb09d2669d">

**Comment by 779102260** [comment]
> 应该是 Node 请求不走系统代理，引入这个 npm 包试试：https://github.com/avwo/lack-proxy

大佬牛批，但是为啥会不走系统代理，我是在网络设置的代理，按理说电脑里所有请求都走网络啊
<img width="670" alt="image" src="https://github.com/avwo/whistle/assets/16102900/0b8355e2-10bb-4f27-9dbe-1545a81f24b0">
