### ISSUE TITLE
本地抓不到

### ISSUE THREAD

**Issue by mydracula** [avwo/whistle#945]
系统代理都没问题
微信小程序或者网页随便抓就是本地请求都抓不了
不知道是用了vite代理的还是node请求的反正请求不了
![image](https://github.com/avwo/whistle/assets/71320199/e4b9df33-10b9-4416-8f12-42c633abe042)
话说这2个有什么区别
![image](https://github.com/avwo/whistle/assets/71320199/e02b3360-8b69-42ba-98cf-19afba544693)
这些我都能访问
![image](https://github.com/avwo/whistle/assets/71320199/59285069-789a-4225-9e54-0de83e29aec8)

**Comment by mydracula** [comment]
参考以前的issues去SwitchyOmega配置这个倒是可以抓到
```
<-loopback>
```
就是SwitchyOmega用系统代理不行很绝望啊

**Comment by avwo** [comment]
https://github.com/avwo/whistle/issues/943

**Comment by mydracula** [comment]
> #943

看过这个了 不知道怎么在vue中引入 😢

**Comment by mydracula** [comment]
> #943

顺便问一问这个是什么报错呢

```
<pre>From: whistle@2.9.55
Node: v16.20.1
Host: DESKTOP-OOT0U26
Date: 2023/7/26 14:17:49
Error: Parse Error: Invalid header value char
    at Socket.socketOnData (node:_http_client:534:22)
    at Socket.emit (node:events:513:28)
    at addChunk (node:internal/streams/readable:315:12)
    at readableAddChunk (node:internal/streams/readable:289:9)
    at Socket.Readable.push (node:internal/streams/readable:228:10)
    at TCP.onStreamRead (node:internal/stream_base_commons:190:23)


<a href="javascript:;" onclick="location.reload()">Reload this page</a>
</pre>
```

**Comment by avwo** [comment]
响应头有非 latin1 字符（比如中文字符），node 对 http 校验比较严格，稍有不满足标准的 http 请求就解析不了
