### ISSUE TITLE
whistle 依赖的 node-native-zip2 包没有提供 License 

### ISSUE THREAD

**Issue by jkzing** [avwo/whistle#946]
Hi @avwo, 

我们发现 whistle 使用的 node-native-zip2 包没有提供 License，我看到这个这个包也是你发布的，你介意给你发布的这个版本加上一个 License 文件吗（或者在你修改的这个版本的 GitHub 仓库中上传一个 LICENSE 文件也是可以的）

**Comment by jkzing** [comment]
PS：Modern.js 的 [plugin-proxy](https://github.com/web-infra-dev/modern.js/tree/main/packages/cli/plugin-proxy) 中使用了 whistle，用户在向我们反馈这个问题...

**Comment by avwo** [comment]
我看下怎么处理

**Comment by avwo** [comment]
下个版本会删除这个依赖包

**Comment by avwo** [comment]
已删除，用最新版本
