### ISSUE TITLE
如何在websocket插件里 send到服务器的时候 设置成 binary格式 而不是text

### ISSUE THREAD

**Issue by 519544044** [avwo/whistle#948]
原始websocket是 protobuf 格式的 二进制数据，通过插件转发 就变成 text类型了 （ res.send(data);），加了 opts也一样
参考一下文章写的
https://cloud.tencent.com/developer/article/1547476

exports.handleWebSocket  = async (ws, connect) => {
      // 将请求继续转发到目标后台，如果不加则直接响应
    const res = await connect();
      // 获取客户端的请求数据
    ws.on('message', (data) => {
      // 在script的Console打印出客户端发送的数据
      console.log(`Client: ${data}`);
       // 可以修改后再发送到Server
       res.send(data);
    });
      res.on('message', (data) => {
        // 在script的Console打印出服务端发送的数据
        console.log(`Server: ${data}`);
         // 可以修改后再发送到Server
         ws.send(data);
    });
    // 接收通过whistle.script页面Console的dataSource.emit('toSocketClient', {name: 'toSocketClient'})的数据
    ws.dataSource.on('toSocketClient', (data) => {
      ws.send(data);
    });
   // 接收通过whistle.script页面Console的dataSource.emit('toSocketServer', {name: 'toSocketClient'})的数据
      ws.dataSource.on('toSocketServer', (data) => {
      res.send(data);
    });
};

**Comment by avwo** [comment]
`opts` 设置属性 `opts.binary  = true` 试试
PS: 插件的问题不要在这提 issue

**Comment by 519544044** [comment]
好的 谢谢大佬
