### ISSUE TITLE
如何抓取小程序的ws包

### ISSUE THREAD

**Issue by gaocong1990** [avwo/whistle#95]
如何抓取小程序的ws包，手机微信小程序请求，在network里看不到任何请求

**Comment by avwo** [comment]
iOS应该是可以：
1. [安装HTTPS根证书并开启HTTPS拦截](https://avwo.github.io/whistle/webui/https.html)
2. 确认下浏览器上的HTTP和HTTPS请求是否可以正常抓包
3. 然后微信上试下HTTP和HTTPS请求

**Comment by jation** [comment]
http的请求在手机客户端小程序里运行环境可能是发不出去的，建议直接测https请求。
并且已验证https请求是可以捕获的。

**Comment by xu-xiang** [comment]
@avwo ios上测试  http https可以截取，但是websocket无法抓取。

**Comment by xu-xiang** [comment]
@gaocong1990 请问问题是否有解决了 是否有办法抓到移动端 ws 或 wss

**Comment by avwo** [comment]
手机安装根证书并开启https拦截了么，没有的话参考下这个：[安装根证书及开启https拦截](https://avwo.github.io/whistle/webui/https.html)

**Comment by xu-xiang** [comment]
@gaocong1990 https可以正常抓取。无法抓去ws或wss  怀疑是ios代理配置的限制，ios代理 可能根本就不会代理ws|wss

这边不知道你测试过没有  我试下来是不行的

**Comment by xu-xiang** [comment]
@avwo  上面@错了

**Comment by xiaobear250** [comment]
微信应该有自己的tcp协议，不同于ws，不然照说平常的微信聊天信息应该也可以获取得到才对。另外，像小程序也有ws的API，但实际上走的应该还是微信自己改造过的tcp协议，所以抓取不到。https://developers.weixin.qq.com/miniprogram/dev/api/network-socket.html#wxclosesocket

**Comment by godhh** [comment]
@xiaobear250 自己的tcp怎么链接第三方的websocket服务？
