### ISSUE TITLE
插件响应 413 Payload Too Large

### ISSUE THREAD

**Issue by zxt5105515** [avwo/whistle#951]
请求大概11mb，已经开了`* enable://bigData`，但它好像只支持10mb，有什么别的办法吗

**Comment by avwo** [comment]
看下响应头是哪个服务器返回的

**Comment by zxt5105515** [comment]
> 看下响应头是哪个服务器返回的

是自己写的插件服务
<img width="602" alt="image" src="https://github.com/avwo/whistle/assets/6982924/a5207b77-5a85-4de0-ab30-3d4a60a60529">

**Comment by zxt5105515** [comment]
解决了 ，是插件用的koa自己设置的上限，改了就好了
```
const app = new Koa()

app.use(bodyParser({
  'formLimit':'20mb',
  'jsonLimit':'20mb',
  'textLimit':'20mb',
}))
```
