### ISSUE TITLE
云服务器vscode远程开发环境使用whistle.protocol把所有的https转成http

### ISSUE THREAD

**Issue by shirleyYing** [avwo/whistle#952]
<img width="565" alt="image" src="https://github.com/avwo/whistle/assets/12593649/5d43d81d-4f39-4394-8c35-573530bbad1f">

使用vscode远程开发，在云机器上安装了whistle。所有代理和本地开发一模一样。但是所有https的请求protocol都会被转成http
导致项目中配置了域名代理的外部服务被拒绝，返回状态码403

对比本地开发。发现只有protocol这里有不同
<img width="541" alt="image" src="https://github.com/avwo/whistle/assets/12593649/5e136070-0fcd-49ea-a6b1-0a223e2f5ad0">

**Comment by avwo** [comment]
看下服务器为什么会返回 302

**Comment by shirleyYing** [comment]
https://cloud.tencent.com/login/wechat

**Comment by avwo** [comment]
导出抓包看下

**Comment by phoenixxyang** [comment]
最新版本whistle遇到同样问题，protocol栏显示HTTPS>HTTP。替换回2.9.30版本就没有问题了。

**Comment by avwo** [comment]
配了 host 或者是本地服务，对于访问失败的 https 请求whistle会自动转成 http，可以通过 `disable://auto2http` 禁用
