### ISSUE TITLE
抓取不到webscoket的数据包呢

### ISSUE THREAD

**Issue by staxiangbo** [avwo/whistle#953]
IOS手机上已经安装了证书，但在在whistle界面，只能看到HTTPS的请求，webscoket的请求都看不到呢

**Comment by avwo** [comment]
https://github.com/avwo/whistle/issues/662

**Comment by XiangBoa** [comment]
我用的whistle版本是2.9.56，想抓webscoket的请求，连这个scoket这个按钮都没有呢，需要怎么配置吗

**Comment by XiangBoa** [comment]
在Frames中，socket的请求是乱码的，麻烦请教一下，要如何处理这里的编码格式哦
[image]

**Comment by XiangBoa** [comment]
我抓APP的接口时，在规则里已经设置了mimo-test.mimo.immo log:// ，但是在console中看不到前端的打印内容呢
