### ISSUE TITLE
ios进不去rootca.pro，安装不了证书

### ISSUE THREAD

**Issue by CHENGCHANGHU** [avwo/whistle#955]
ios扫码rootca.pro，无法访问，配置了代理也不行。ios配置代理后无法访问网络，设置了用户和密码也无法访问网络

**Comment by avwo** [comment]
代理 ip 是不是搞错了

**Comment by CHENGCHANGHU** [comment]
ios配置的ip是mac的ip地址，端口用的8899

**Comment by avwo** [comment]
https://github.com/avwo/whistle/issues/737

**Comment by CHENGCHANGHU** [comment]
呃，防火墙也是关闭的

**Comment by CHENGCHANGHU** [comment]
可以了，重启了电脑
