### ISSUE TITLE
手机iphone跟电脑mac m1 处在同一wifi下，iphone配置了代理指向电脑的ip地址，端口8899，不能打开rootca.pro下载证书

### ISSUE THREAD

**Issue by HugoJuntaoChen** [avwo/whistle#956]

**Comment by HugoJuntaoChen** [comment]
<img width="670" alt="image" src="https://github.com/avwo/whistle/assets/53006225/9a90f394-e067-4573-a32b-a10c91bfe86f">

电脑在该wifi网络上配置了http代理和https代理，手机也无法访问

**Comment by avwo** [comment]
https://github.com/avwo/whistle/issues/955

**Comment by HugoJuntaoChen** [comment]
#955 ，我重启过几次了，还是不行，代理的ip是没错的，防火墙也是关闭的，手机访问http的网页，电脑的8899抓不到手机访问的http请求

**Comment by avwo** [comment]
是不是端口限制，`w2 restart -p 8100` 换个端口试试

**Comment by HugoJuntaoChen** [comment]
<img width="460" alt="image" src="https://github.com/avwo/whistle/assets/53006225/7b8b151d-4cba-4767-af12-a9728a58b09a">
<img width="468" alt="image" src="https://github.com/avwo/whistle/assets/53006225/51bb5090-acc3-48ae-affd-510574baa472">
![Uploading wecom-temp-39982-c13228efd6ecb34ae51b2100de8c0773.jpg…]()
