### ISSUE TITLE
导出为har，无法在edge中再次导入

### ISSUE THREAD

**Issue by aogg** [avwo/whistle#957]
![image](https://github.com/avwo/whistle/assets/8998031/7eca4448-c185-4178-9dfa-8ab923bcacfd)

**Comment by aogg** [comment]
这也意味着在别的支持har导入的api接口工具中，无法识别，麻烦支持下

**Comment by avwo** [comment]
把你导出的 har 发出来看下

**Comment by aogg** [comment]
好像重试了下又可以，可能刚选错文件了，只是我在多个工具中导入导出才能进去最终工具，搞乱了
