### ISSUE TITLE
I have a problem with dispatch.js

### ISSUE THREAD

**Issue by sebas8632** [avwo/whistle#96]
Hi, @avwo  do you have more information about dispatch.js? I was trying to use this, but in my CLI the project only shows me literally the line code that i wrote.

![imagen](https://user-images.githubusercontent.com/11086879/34174665-b3774b26-e4c7-11e7-8188-c212f7d8b9f7.png)

**Comment by echopi** [comment]
Hi @sebas8632, the `dispatch` operator is used when we need to change the reqest url params dynamically.  

Here is  [a demo]( http://121.40.72.148:8899/#rules ) about `dispatch`, hope it is helpful for understanding.

Or can you share you code?  so we can be more clear about the problems you are facing.

**Comment by sebas8632** [comment]
Hi @echopi , thanks for your response. I want  to redirect some urls dynamically through dispatch. 
I want to decide if redirect or not a host because the header parameter is true or not.

`
var isRedirect = headers['redirect'];

if(isRedirect == 1){
  //Here i want to do my redirect.
} else {
  //Here it lets to continue the normal navigation.
}

`

Do you know how to redirect dynamically an url?

**Comment by avwo** [comment]
Hi @sebas8632 , you can use [reqScript](https://avwo.github.io/whistle/rules/reqScript.html) instead of [dispatch](https://avwo.github.io/whistle/rules/dispatch.html), such as:

	www.test.com/demo reqScript://{checkRedirect.js}

the key `checkRedirect.js` in **[Values](http://121.40.72.148:8899/#values)**:

	if (headers['x-redirect']) {
		rules.push(`${headers.host} redirect://https://github.com`)
	} 

Here is a [demo](http://121.40.72.148:8899/#rules) about [reqScript](https://avwo.github.io/whistle/rules/reqScript.html)。

**Comment by sebas8632** [comment]
Hey @avwo  reqScript works really good, thanks.

I would like to ask you something else, i would like to have a pattern which works like a regular expression, for example:

`www.*.com reqScript://{checkRedirect.js}`

Do you know how to do that?

**Comment by avwo** [comment]
The whistle regular expression is the same as JavaScript:
```
/^[a-z]+:\/\/www\.[^./]+\.com[:/]/  reqScript://{checkRedirect.js}
```
Click [here](https://avwo.github.io/whistle/pattern.html) to see all whistle patterns. Now only Chinese documents are available, and English documents will be ready next month.

**Comment by sebas8632** [comment]
@avwo  i have a last question.

I have this code and i would like to use a module in checkRedirect.js.

```
var fs = require('fs');

if (headers.host != "www.marca.com") {

  fs.writeFile('file.txt', 'IS NOT MARCA', function (err){
    if (err) return console.log(err);
  });
	rules.push(`${headers.host} redirect://http://eltiempo.es`)
}
```


In checkRedirect.js  how do you use a module from npm like axios, fs or request?
