### ISSUE TITLE
麻烦加个搜索返回结果，和搜索请求参数的功能吧

### ISSUE THREAD

**Issue by aogg** [avwo/whistle#960]
抓包就是因为不知道，比如一个地方显示10.5，一个页面多个接口，就需要搜索才知道哪个

**Comment by aogg** [comment]
不搜索后端，只搜能看到的前端

**Comment by avwo** [comment]
底部输入框输入：`b:keyword`

**Comment by aogg** [comment]
1.b:pattern：pattern为正则或关键字，表示匹配请求内容（request body）
2.m:name：name为方法名称或正则表达式，表示匹配对应方法（request method）
3.i:ip：ip表示具体客户(服务)端ip或匹配ip的正则表达式
4.clientIp:ip：ip表示具体客户端ip或匹配ip的正则表达式
5.serverIp:ip：ip表示具体服务端ip或匹配ip的正则表达式
6.s:code：code表示响应状态码，或正则表达式
7.h:name=pattern：匹配请求或响应头字段 name，pattern为该字段对应值里面的关键字或正则表示
8.reqH:name=pattern：同上，但只会匹配请求头
9.resH:name=pattern：同上，但只会匹配响应头
10.*/cgi-*：表示匹配 xxx://x.y.z/cgi-.../...，具体可以参见[pattern](http://wproxy.org/whistle/pattern.html)里面的通配路径
