### ISSUE TITLE
不知道哪里搞错了，抓到的几乎都是 captureError

### ISSUE THREAD

**Issue by onwayboy** [avwo/whistle#961]
![image](https://github.com/avwo/whistle/assets/21093009/3f71c76d-b655-42b4-b234-efd75ba53916)

手机wifi设置代理后，很多包的状态码都是 captureError，app 无法正常使用
看端口是443来的，应该是https才对吧，怎么显示是http?

**Comment by avwo** [comment]
手机安装根证书了吗

**Comment by onwayboy** [comment]
安装的了

**Comment by avwo** [comment]
什么手机，仔细看下文档

**Comment by Mrchangchang** [comment]
我也碰到这个问题了，不过我这边有些https请求能抓到，很多都是 报 captureError

**Comment by avwo** [comment]
几种可能：
1. 没装 Whistle 根证书
2. 装了 Whistle 根证书没确认
3. ssl pinning
4. 证书指纹问题：https://github.com/avwo/whistle/issues/865

先确认下 1、2 点是否ok，对于 captureError 的请求如果不需要关注可以通过 `disable://capture 域名1 域名2 域名3` 设置不解析此域名的 https 请求

**Comment by pipihua666** [comment]
会不会是app没有添加信任用户自定义证书的权限?

**Comment by avwo** [comment]
> 会不会是app没有添加信任用户自定义证书的权限?

有可能，大部分是这种情况

**Comment by acfasj** [comment]
@avwo  ssl pinning 怎么绕过? 都是要看的请求没办法 disable://capture

**Comment by avwo** [comment]
这类请求无法解包，只能看到域名、端口、请求头 user-agent

**Comment by xiangshiming1992** [comment]
解决了么？我也遇到了这个问题，确定的是手机安装了证书 也勾选了开启https

**Comment by avwo** [comment]
iOS安装证书后还要手动确认下，看下文档

**Comment by xiangshiming1992** [comment]
这种低级的操作 我肯定是确认的呀

**Comment by crazyxhz** [comment]
这个软件现在还能用吗？ 和系统升级是不是有啥关系，现在全是 capture error 已安装根证书

**Comment by avwo** [comment]
iOS 18 吗？可以看下这个 issue：https://github.com/avwo/whistle/issues/1171

**Comment by AshleyFang** [comment]
第一次遇到的时候  重装证书好了
第二次遇到的时候  证书的二维码扫了但打不开

**Comment by avwo** [comment]
1. 手机未配代理情况下：可以切换 URL 换个二维码试试
2. 手机配置代理情况下：关闭代理，按 `1` 操作，看下哪个 `IP` 和 `PORT` 的二维码链接可以正常下载根证书，就用这个 `IP` 和 `PORT` 配置手机代理
