### ISSUE TITLE
SSL routines:ssl3_get_record:wrong version number

### ISSUE THREAD

**Issue by Henri-Zhang** [avwo/whistle#963]
<img width="1145" alt="image" src="https://github.com/avwo/whistle/assets/15962610/75780cf5-6600-4b21-8419-d0d929acb985">

**Comment by Henri-Zhang** [comment]
node版本换了几个也不行。

**Comment by avwo** [comment]
1. url 改成 http 试试
2. 试试配置规则 `域名 cipher://DH-RSA-AES256-GCM-SHA384`
