### ISSUE TITLE
whistle 怎么支持 webpack 热更新 ?

### ISSUE THREAD

**Issue by DaphnisLi** [avwo/whistle#965]

**Comment by avwo** [comment]
默认就支持

**Comment by DaphnisLi** [comment]
试了下，不支持。是我配置有问题吗，大佬能帮看下吗

**Comment by avwo** [comment]
你这个是调试 whistle 代码，还是通过 whistle 转发页面请求到 webpack？

**Comment by DaphnisLi** [comment]
> 你这个是调试 whistle 代码，还是通过 whistle 转发页面请求到 webpack？

是将本地的代码代理到线上进行调试，本地代码代理是ok的，但是修改代码后，webpack 热更新没用，只是本地重新构建了，页面没发生变化

**Comment by avwo** [comment]
抓包看下请求有没有发出去，有没有响应？

**Comment by DaphnisLi** [comment]
> 抓包看下请求有没有发出去，有没有响应？

热更新时抓到了这几个

![Uploading image.png…]()

**Comment by DaphnisLi** [comment]
> 抓包看下请求有没有发出去，有没有响应？

热更新时抓到了这几个

![image](https://github.com/avwo/whistle/assets/67792799/a981cdc2-7c08-4f25-95d5-675c645aacce)

**Comment by avwo** [comment]
用 chrome 抓包看看

**Comment by sedationh** [comment]
@DaphnisLi 
先在 localhost 下看看你热更新的请求情况，再根据请求情况配置热更新匹配规则
First look at your HMR request under localhost, and then configure the HMR matching rule according to the request situation

如
such as

```
^https://xxx.net/***hot-update*** http://127.0.0.1:9966/$1hot-update$2
```

**Comment by chiyu1996** [comment]
似乎是chrome修改了SSL规则，导致跟本地的webpack-dev-server 建立websocket链接失败 Failed to load resource: net::ERR_SSL_PROTOCOL_ERROR

**Comment by avwo** [comment]
不要用 ip 改用当前页面的域名试试
