### ISSUE TITLE
相同请求转发到whistle中出现captureError，但是转发到charles中却可以正常

### ISSUE THREAD

**Issue by luoweikingjj** [avwo/whistle#967]
如题，whistle当前版本是2.9.57，在whistle中不全是captureError，有些是成功的，如图1，证书是安装成功在Android模拟器中
![image](https://github.com/avwo/whistle/assets/7764890/7f04b2c2-ed34-495f-8252-53364404a47d)

### 出现captureError
![image](https://github.com/avwo/whistle/assets/7764890/81c1b7e9-58b6-42c1-976b-eeb4b2b8c5f0)
### 在charles中正常
![image](https://github.com/avwo/whistle/assets/7764890/1b96b250-2244-4c05-a998-4fda9124910d)

**Comment by avwo** [comment]
1. 根证书安装了吗？模拟器的浏览器也要安装根证书：https://wproxy.org/whistle/webui/https.html
2. 如果不想安装根证书，或者出现 ssl pinning 问题可以配置规则：`edge-mqtt.facebook.com disable://capture` 对指定域名的 https 请求不解析即可

**Comment by luoweikingjj** [comment]
证书是安装成功的，我同时安装了whistle和charles的根证书，如图1，在模拟器浏览器，whistle可以正常抓取到https的请求
![1692780270471](https://github.com/avwo/whistle/assets/7764890/934c8b88-78c2-4cf4-bae8-357f30a27186)
### 关于出现captureError的错误
打开的应用是Facebook，不仅是`edge-mqtt.facebook.com`这个域名，其他应用打开的请求也有出现此错误。如果ssl pinning的问题，那么charles也抓取不成功才对吧。
![1692780029322](https://github.com/avwo/whistle/assets/7764890/ed7bbdc6-75d5-4b28-a3a1-12e0161c0d87)

**Comment by avwo** [comment]
charles 那个也没解开请求，根 whistle 配置 `edge-mqtt.facebook.com disable://capture` 的效果一样

**Comment by luoweikingjj** [comment]
了解了，感谢大佬回复！Thanks♪(･ω･)ﾉ

**Comment by luoweikingjj** [comment]
了解了，感谢大佬回复！Thanks♪(･ω･)ﾉ

**Comment by luoweikingjj** [comment]
了解了，感谢大佬回复！Thanks♪(･ω･)ﾉ
