### ISSUE TITLE
无法解析http的接口，安卓下

### ISSUE THREAD

**Issue by aogg** [avwo/whistle#968]
![Uploading N3[]4[6J{58O)RZ~9YNKQ54.png…]()

估计是长链接

但charles是可以解析的，

**Comment by avwo** [comment]
https://wproxy.org/whistle/webui/https.html

**Comment by aogg** [comment]
![image](https://github.com/avwo/whistle/assets/8998031/987629b5-d0c4-4e52-b029-9a567e8ad161)
这是个http的请求，但因为安卓系统底层的原因，会出现whistle无法抓包的情况

**Comment by aogg** [comment]
![image](https://github.com/avwo/whistle/assets/8998031/8e324204-683a-4773-9cc6-9e4fa1afae57)

**Comment by aogg** [comment]
> * enable://capture

加了直接不显示

**Comment by avwo** [comment]
1. 是否安装根证书
2. 是否开启 `Capture TUNNEL CONNECTS`
3. 是否使用 socks 代理

**Comment by aogg** [comment]
是否安装根证书
这只是个http也需要安装证书？不是https，而且别人charles都没安装一样能抓到



是否开启 Capture TUNNEL CONNECTS
这个说的是这里的capture吗？要全局开启？我单个开启都没不成功enable://capture
```
w2 start[run] -M mode： 设置 whistle 启动模式，同时设置多个用 | 分隔开，如 -M "pureProxy|debug|multiEnv|capture|disableH2|network|rules|plugins"
prod： 使用 w2 run 默认启动的是开发模式，性能会有些影响，可以通过 prod 强制转成生产模式
pureProxy： 纯代理模式，对一些内置界面域名 local.whistlejs.com 也当初普通请求
debug： 调试模式，会禁用一些超时设置及 dnsCache（不建议使用）
multiEnv： 除了 Default 其它规则都不能启用，应用参见：** https://github.com/nohosts/nohost
capture： 默认开启 Capture TUNNEL CONNECTS
disableH2： 默认禁用 Enable HTTP/2
network： 配置界面只显示 Network，支持 network|rules 或 netowrk|plugins
rules： 配置界面只显示 Rules，支持 network|rules 或 rules|plugins，
plugins： 配置界面只显示 Plugins，支持 rules|plugins 或 netowrk|plugins
safe： 安全模式，禁用 rejectUnauthorized，如果服务端返回自定义证书会报错，默认忽略错误
notAllowedDisableRules： 不允许禁用规则
notAllowedDisablePlugins： 不允许禁用插件
socks： socks模式，通过socks转发的请求默认走tunnel
keepXFF： 是否自动带上 x-forwarded-for 请求头
buildIn： 插件是否使用跟主进程一样的 Node 版本，默认是全局 Node，一般用于打包 electron 应用时使用

```


是否使用 socks 代理
能看到connect就是已经http成功了，难道必须socks代理？

**Comment by avwo** [comment]
配置规则 `35.74.117.124 enable://inspect` 后再导出抓包我看下

**Comment by aogg** [comment]
> 配置规则 `35.74.117.124 enable://inspect` 后再导出抓包我看下

这个我之前也是试过的，后续找个能给你复现的？

反正随便找个http的网站，用安卓打开，用一段时间就会出现无法显示抓包信息的

真的重点是安卓

**Comment by avwo** [comment]
不科学啊，除非该请求不符合 http 格式
