### ISSUE TITLE
对于一个接口的返回，要同时设置两个规则mock，status code和 response body。要如何写规则呢？

### ISSUE THREAD

**Issue by Joeyteatea** [avwo/whistle#969]
对于一个接口的返回，要同时设置两个规则mock，status code和 response body。要如何写规则呢？

**Comment by avwo** [comment]
两种写法，哪个方便用哪个即可
写法一（本地替换，再通过替换响应码）：
``` txt
pattern file://xxx replaceStatus://500
```

写法二（直接响应，并设置响应内容，这种需要手动设置响应类型）：
``` txt
pattern resBody://xxx statusCode://500 resType://html
```

**Comment by Joeyteatea** [comment]
> 两种写法，哪个方便用哪个即可 写法一（本地替换，再通过替换响应码）：
> 
> ```
> pattern file://xxx replaceStatus://500
> ```
> 
> 写法二（直接响应，并设置响应内容，这种需要手动设置响应类型）：
> 
> ```
> pattern resBody://xxx statusCode://500 resType://html
> ```

谢谢~成功啦！
