### ISSUE TITLE
[feature]支持replay协议

### ISSUE THREAD

**Issue by C370228492** [avwo/whistle#970]
配置方式
http://xxxxx/yyy replay:2
功能和选中请求后右键=>ation => replay times相同
加上这个协议之后不需要人参与也可以实现replay目的

**Comment by avwo** [comment]
应用场景是什么？

**Comment by avwo** [comment]
这种用插件很容易实现，比如实现一个名为 `whistle.autoreplay` 的插件，然后配置规则：
``` txt
pattern whistle.autoreplay://2
```
如何实现可以参考：
1. 参考 https://github.com/whistle-plugins/whistle.autosave/blob/master/lib/resStatsServer.js 实现 `reqStatsServer` 及 `req.getReqSession(cb)`  方法获取请求数据
2. 通过插件里面的 `options.request` 方法循环重放
