### ISSUE TITLE
bug-经过charles代理转发到nohost，whistle界面上看不到https的connect记录

### ISSUE THREAD

**Issue by aogg** [avwo/whistle#972]
![image](https://github.com/avwo/whistle/assets/8998031/4f192929-fa90-4dcc-a5f6-88f855d885aa)
curl --trace-time -kvx localhost:8887 http://www.baidu.com
curl --trace-time -kvx localhost:8887 https://www.baidu.com

如果是https就看不到，http就能看到，是常规的CONNECT都看不到那种
![image](https://github.com/avwo/whistle/assets/8998031/cd5a8594-5645-4017-9ba4-47fed3de1a69)

![image](https://github.com/avwo/whistle/assets/8998031/70cc9ba2-701b-4a27-9b46-d9fd1157f3bb)

nohost容器还是新搭的，无规则
```
docker rm -f nohost-debug;\
docker run -d --name nohost-debug  --network common-all --restart=always -p 8199:8199 \
adockero/nohost -p 8199
```

**Comment by avwo** [comment]
用 whistle 转发

**Comment by aogg** [comment]
那还是有问题啊，非要再试下用whistle的吗

**Comment by Dddyqs** [comment]
大佬在哪里找到的nohost镜像啊，我也想在docker里玩玩

**Comment by avwo** [comment]
@aogg 更新下 nohost 试试

**Comment by avwo** [comment]
> 大佬在哪里找到的nohost镜像啊，我也想在docker里玩玩

看下这个 https://hub.docker.com/r/nohostjs/nohost

**Comment by avwo** [comment]
自己搞一个
