### ISSUE TITLE
replay请求增加请求间隔参数

### ISSUE THREAD

**Issue by Chankit8** [avwo/whistle#973]
受限于部分场景的频控，replay请求是否可以增加多个请求之间的时间间隔参数

**Comment by avwo** [comment]
可以选中要重放抓包数据，点击顶部菜单 `Replay` 手动控制发送间格，或者可以通过插件扩展右键菜单自己实现：
1. 添加右键菜单：https://github.com/whistle-plugins/examples/tree/master/whistle.test-menu
2. 重放请求：https://github.com/avwo/whistle/blob/master/assets/menu.html#L163
