### ISSUE TITLE
无法启用多规则

### ISSUE THREAD

**Issue by sonce** [avwo/whistle#974]
启用多规则的选项不可开启
![image](https://github.com/avwo/whistle/assets/887972/75bf412b-1882-4542-8aba-f78b26e0319f)

规则只有Default有Enable，其他规则没有Enable的菜单。
![image](https://github.com/avwo/whistle/assets/887972/dbcb352e-1cbd-4373-805d-13cf12cfb4d4)
![image](https://github.com/avwo/whistle/assets/887972/08aa4d35-960a-4aa9-81f4-b4ca2e18bdbb)

版本：
Nohost ： 1.5.13
Whistle ：2.9.56

**Comment by avwo** [comment]
nohost 上不支持启用其它规则
