### ISSUE TITLE
规则优先级顺序是怎么样的，怎么只匹配最模糊的

### ISSUE THREAD

**Issue by aogg** [avwo/whistle#976]
有两个匹配规则，但只匹配了最后一条

**.proxy_sslip.172.16.0.**.sslip.io proxy://aa.common-all:8888
**.proxy_sslip.**.sslip.io http://bb.common-all:80 reqHeaders://`host=${reqHeaders.host}`

**Comment by aogg** [comment]
http://default.crontab-ui.proxy_sslip.172.16.0.210.sslip.io/

访问这个域名

**Comment by aogg** [comment]
怎么会是越模糊优先级越高的

**Comment by avwo** [comment]
1. 默认优先级从上到下
2. proxy 和 host 协议比较特殊匹配的是 Final Url
3. 有些协议可以同时匹配多个如：reqHeaders，有些协议只能匹配一个如：host、proxy、file等

**Comment by aogg** [comment]
我排序了下，还是不行，应该以第一个匹配为准，proxy和host都是写在第二位置

**Comment by aogg** [comment]
最后还是靠excludeFilter，如果类似nginx的话，就是越精确越优先

**Comment by avwo** [comment]
截图看下

**Comment by avwo** [comment]
> 最后还是靠excludeFilter，如果类似nginx的话，就是越精确越优先

whitle 规则比较灵活，这个做不到
