### ISSUE TITLE
拦截请求后如何获取原始响应并在修改后继续返回

### ISSUE THREAD

**Issue by JasperrYang** [avwo/whistle#977]
例如我在代理 www.baidu.com 后，要在原始响应的基础上再继续添加 script 脚本。目前支持吗？该如何操作？

**Comment by avwo** [comment]
https://wproxy.org/whistle/rules/
<img width="500" alt="image" src="https://github.com/avwo/whistle/assets/11450939/e84100ce-7ff8-4b18-9b9f-c1edbf6bdd9e">
