### ISSUE TITLE
从body获取数据放入urlParams

### ISSUE THREAD

**Issue by sonce** [avwo/whistle#978]
请教下，

test.com includeFilter://b:/"Id":"(mock_\w+)"|"order_status_list":\["(\w*)"\]/i http://mock.cn/findorderlistquery urlParams://(shopId=$1&orderState=$2)

$1和$2都是空的。
是哪里不对吗？或者有其他什么办法？

**Comment by avwo** [comment]
需要用插件：https://github.com/whistle-plugins/examples/tree/master/whistle.set-rules-according-body

**Comment by avwo** [comment]
最新版 `v2.9.59`，重新安装并重启 Whistle，为了跟 url 的 pattern 做区分需要把 `$0`、`$1` 等改成 `$b0`、`$b1`。
