### ISSUE TITLE
network 面板增加右键菜单

### ISSUE THREAD

**Issue by littledu** [avwo/whistle#98]
经常的，想配置一个规则，是先抓一下请求，然后复制出请求 url 到 rules 面板进行配置，增加 右键 菜单功能，比如增加一个 `复制` 功能等等。

whistle 很赞，感谢做了如此强大的产品。

**Comment by avwo** [comment]
最新版本已经在Network、Rules、Values使用了自定义菜单：[点击这里更新whistle](https://avwo.github.io/whistle/update.html)

**Comment by littledu** [comment]
@avwo 赞
