### ISSUE TITLE
配置代理规则后手机浏览器可以访问 Google Play 网页但是 Google Play APP 无响应

### ISSUE THREAD

**Issue by note4** [avwo/whistle#981]
Rules
```
* socks://127.0.0.1:1080
```

手机装了证书，访问网站正常，部分app无法使用。

![image](https://github.com/avwo/whistle/assets/6513389/e09fc01a-1cb0-45c4-883d-085a17bed159)

**Comment by note4** [comment]
坚果云会提示无网络
![image](https://github.com/avwo/whistle/assets/6513389/438493a7-09e0-4f32-8beb-bd37161dc48c)

**Comment by avwo** [comment]
https://github.com/avwo/whistle/issues/961/

**Comment by note4** [comment]
> #961

几种可能：

> 没装 Whistle 根证书
> 装了 Whistle 根证书没确认
> ssl pinning
> 证书指纹问题：https://github.com/avwo/whistle/issues/865
> 先确认下 1、2 点是否ok，对于 captureError 的请求如果不需要关注可以通过 disable://capture 域名1 域名2 域名3 设置不解析此域名的 https 请求


如果使用 `disable://capture 域名1 域名2 域名3` 不会关注域名，那设置的代理有效吗？

**Comment by avwo** [comment]
`disable://capture` 只是无法查看和修改 url 路径及请求响应内容，请求还是会经过 whistle且跟这些内容无关的规则如：`host`、`proxy` 等还是能生效

**Comment by note4** [comment]
> disable://capture

是的，可以了。等下再试试 resSpeed 和 resDelay

刚才有翻到那条记录，没看懂。哈哈哈，还是要大神亲自指点，谢啦。

**Comment by note4** [comment]
```
* socks://127.0.0.1:1080
* resSpeed://100
* resDelay://8000

disable://capture *.googleapis.com *.googleusercontent.com *.google.com
```

好像 disable://capture  设定的域名，访问并没有受 resSpeed 和 resDelay 限制，依然秒开。

**Comment by avwo** [comment]
> ```
> * socks://127.0.0.1:1080
> * resSpeed://100
> * resDelay://8000
> 
> disable://capture *.googleapis.com *.googleusercontent.com *.google.com
> ```
> 
> 好像 disable://capture 设定的域名，访问并没有受 resSpeed 和 resDelay 限制，依然秒开。

resSpeed 对隧道代理不生效，resDelay 只在建立连接过程中生效，你把隧道代理连接通过`右键/Action/Abort` 后重新发请求试试

**Comment by note4** [comment]
`右键/Action/Abort `  中 `Abort` 选项为灰色，无法操作

**Comment by avwo** [comment]
试试 `disable://capture enable://inspect *.googleapis.com *.googleusercontent.com *.google.com`

**Comment by note4** [comment]
> 试试 `disable://capture enable://inspect *.googleapis.com *.googleusercontent.com *.google.com`

好像可以了，谢谢大佬
