### ISSUE TITLE
includeFilter://s 不生效

### ISSUE THREAD

**Issue by lfire** [avwo/whistle#982]
之前以下规则是生效的，近期发现不生效了
```
^https://test.xxx.com/abc/*** http://localhost:9527/index.html includeFilter://s:200 includeFilter://s:503
```
版本：[2.9.57](https://github.com/avwo/whistle/blob/master/CHANGELOG.md)

**Comment by avwo** [comment]
url 替换是在请求阶段完成的，这个时候根本还没有响应状态码

**Comment by lfire** [comment]
ok，好的，明白了，这之前可能有理解错误，谢谢了！

**Comment by avwo** [comment]
可以用 [replaceStatus](https://wproxy.org/whistle/rules/replaceStatus.html) + [resBody](https://wproxy.org/whistle/rules/resBody.html) 代替，也可以通过插件处理
