### ISSUE TITLE
redirect规则重定向后的链接包含#的部分内容会被注释

### ISSUE THREAD

**Issue by Chankit8** [avwo/whistle#983]
如设定以下重定向规则：
https://xxx.com/index.html redirect://https://xxx.com/index.html?_opentype_=newwebview&hl_immersive=1#/harvestRoom?back_type=close
实际会将“#/harvestRoom?back_type=close”这部分注释掉，重定向无效，能否特殊处理下

**Comment by avwo** [comment]
需要特殊处理，试试：·

    https://xxx.com/index.html redirect://{redirectUrl}
    ``` redirectUrl
    https://xxx.com/index.html?_opentype_=newwebview&hl_immersive=1#/harvestRoom?back_type=close
    ```
