### ISSUE TITLE
升级 win11 后无法代理 https

### ISSUE THREAD

**Issue by hayden-fr** [avwo/whistle#988]
操作系统：Microsoft Windows 11 家庭中文版 10.0.22621 暂缺 Build 22621
node版本：18.18.2
whistle版本：2.9.57

刚刚升级了 win11，也将 whistle 从 2.9.4 更新到了 2.9.5，目前有以下几个问题：
1. 无法通过  ip+port 的形式访问 web 端，也无法通过 ip+port 的形式进行代理，不管是使用 Proxy SwitchyOmega 还是系统代理都是这样；
2. 代理使用 localhost+port 进行配置后，可以正常代理，也可以通过 local.whistlejs.com 进行访问；
3. 无论使用哪种方式进行配置，https 网页都无法打开，正常网站走 whistle 代理后，在没有匹配规则的情况下是能指向原地址的；目前 http 能直接访问原请求，但 https 就直接无法访问了，whistle 管理端的 network 里面也没有任何记录，第一次链接时会出现下面这个图片的错误，之后不管怎么刷新都没有新的信息；

![image](https://github.com/avwo/whistle/assets/48267247/542847f2-03ed-4540-b6d1-ed96e4195ff5)

whistle 和 ca 证书都卸载重新安装过，连  .WhistleAppData 都删过，不知道是兼容问题还是我的系统设置问题（比如防火墙，我看了以下好像没有问题，不知道是不是我遗漏了什么），请教该怎么解决

**Comment by avwo** [comment]
这个错误应该是证书的问题，证书是通过执行命令行 `w2 ca` 安装的吗

**Comment by hayden-fr** [comment]
> 这个错误应该是证书的问题，证书是通过执行命令行 `w2 ca` 安装的吗

手工安装的，使用 `w2 ca` 报错 `Parse Error: Expected HTTP/`

**Comment by hayden-fr** [comment]
我找到问题了，系统更新后，好像更新了一部分软件，其中一个软件占用了`8899`端口，换了端口就一切正常了。
