### ISSUE TITLE
Using reqScript, how could i use external module like (fs, request or axios) in checkRedirect.js?

### ISSUE THREAD

**Issue by sebas8632** [avwo/whistle#99]
have this code and i would like to use a module in checkRedirect.js.

```
var fs = require('fs');

if (headers.host != "www.marca.com") {

  fs.writeFile('file.txt', 'IS NOT MARCA', function (err){
    if (err) return console.log(err);
  });
	rules.push(`${headers.host} redirect://http://eltiempo.es`)
}
```
Thanks.

**Comment by avwo** [comment]
whistle built-in rules can only get the data related to the request, if you need to get the system or remote data, you need to customize the whistle plug-in to achieve, or you can use the plug-in [whistle.script](https://github.com/whistle-plugins/whistle.script).
