### ISSUE TITLE
本地开发启用 HTTP2，开 whistle host 之后请求变得很慢

### ISSUE THREAD

**Issue by HelKyle** [avwo/whistle#991]
我这边本地开发使用 Vite， 开启 HTTPS、HTTP2，直接访问 https://localhost:3200/ ，不经过 whistle，447 个请求**耗时1.62s**

<img width="729" alt="image" src="https://github.com/avwo/whistle/assets/9882649/7a8e392d-e354-4d43-bde9-5736ed56a65d">

配置了 host 之后，使用域名访问，经过 whistle，同样**447 个请求，耗时 8.04s**

```
xxx.com 127.0.0.1:3200
```

<img width="690" alt="image" src="https://github.com/avwo/whistle/assets/9882649/fce8bdf1-7303-41b9-a554-ea575f8bf951">

Network 面板里看到代理后，protocol 已经是 H2 了，但是很有请求耗时到了 1s 以上，求助大佬看看有没有什么思路。

<img width="1198" alt="image" src="https://github.com/avwo/whistle/assets/9882649/1a8fedec-f736-425b-9013-bf8080a5aac4">

<img width="982" alt="image" src="https://github.com/avwo/whistle/assets/9882649/16093686-2293-4471-b0c7-5b6f8b7966ca">

<img width="1251" alt="image" src="https://github.com/avwo/whistle/assets/9882649/5f1cea99-44af-4fca-85a8-1b767164447e">

**Comment by HelKyle** [comment]
Node 版本：v14.18.2
whistle 版本：2.9.20

开启了 HTTP/2
<img width="303" alt="image" src="https://github.com/avwo/whistle/assets/9882649/273f418b-e99b-4176-8ad3-541584cedb6e">

**Comment by avwo** [comment]
并发请求太多导致的，升级 node 看看性能有没有提升

**Comment by HelKyle** [comment]
感谢大佬回复，我这边将 Node 升级到 v18.18.0， whistle 升级到最新版本 v2.9.57，问题依然存在，有办法通过启更多 worker 实例来优化吗？

**Comment by HelKyle** [comment]
whistle 这个工具非常好用👍🏻，只是好奇 whistle 并发请求慢的卡点是在哪里，直接访问 Vite 启动的 dev-server，也是 http2 速度是非常快的

**Comment by HelKyle** [comment]
发现是因为我开启了 Vite server.https 导致的，不是 whistle 的问题。

**Comment by FrankFang** [comment]
> 发现是因为我开启了 Vite server.https 导致的，不是 whistle 的问题。

说下怎么解决的？

**Comment by HelKyle** [comment]
> > 发现是因为我开启了 Vite server.https 导致的，不是 whistle 的问题。
> 
> 说下怎么解决的？

我是因为开了 vite 的 server-https 配置，关掉然后用 Node 14 启动 whistle 就可以了
https://vitejs.dev/config/server-options#server-https
