### ISSUE TITLE
resCors://*对部分请求无效？

### ISSUE THREAD

**Issue by dxcqcv** [avwo/whistle#992]
版本whistle@2.9.22

项目是nextjs 12写的，请求是Axios发的，大部分请求都能设置跨域并返回，但唯独一个Get请求不行，设置rules后只能看到Option请求，浏览器网络中显示跨域而且没有返回响应，具体如下图

![chrome_tkiVAE3fCW](https://github.com/avwo/whistle/assets/884046/0e03710f-e1fc-4400-a9c9-56ed2d4e0ba5)

![X21k973Snz](https://github.com/avwo/whistle/assets/884046/df12a527-1840-4b30-8d74-b954ac8638f4)
![chrome_mt6uiz9JL1](https://github.com/avwo/whistle/assets/884046/9ecf9486-1fd8-4aec-a001-15708b8acb86)
![chrome_8UD0WxdcC8](https://github.com/avwo/whistle/assets/884046/f2909cfa-2168-426f-bc23-0a071904a232)
![chrome_Jp8O00JreT](https://github.com/avwo/whistle/assets/884046/1cf80da6-e9e1-4ff0-9c64-7d7d07a2ea13)

**Comment by avwo** [comment]
用 `resCors://enable` 试试

**Comment by dxcqcv** [comment]
可以了，感谢
