### ISSUE TITLE
能否设置一个全局变量代表当前的ip地址啊

### ISSUE THREAD

**Issue by rexhang** [avwo/whistle#998]
能否设置一个全局变量代表当前的ip地址啊，因为每次连接公司wifi可能ip动态变化，有时候变了不知道，能否whistle内置一个ip全局变量直接使用这个变量配置rules就方便多了。望采纳

**Comment by avwo** [comment]
Rules 里面或 Values 里面设置键值对：
Rules:
````` txt
``` serverIp
1.1.1.1
```
`````
或 Values 创建 key：
`serverIp`
设置 Value：
``` txt
1.1.1.1
```

Rules 可以通过 `${serverIp}` 引用值：
``` txt
pattern host://${serverIp}:8080
# 或
pattern host://{serverIp} # 这种不支持拼接
```

**Comment by rexhang** [comment]
> Rules 里面或 Values 里面设置键值对： Rules:
> 
> ```
> ``` serverIp
> 1.1.1.1
> ```
> ```
> 
> 或 Values 创建 key： `serverIp` 设置 Value：
> 
> ```
> 1.1.1.1
> ```
> 
> Rules 可以通过 `${serverIp}` 引用值：
> 
> ```
> pattern host://${serverIp}:8080
> # 或
> pattern host://{serverIp} # 这种不支持拼接
> ```

只能以这种手动定义常量的形式获取IP吗？我看whistle web页面右上角的 【Online】按钮是可以获取到ip地址的，whistle能否直接提供IP变量，这样应对变化的IP，从而无需在IP变化的时候 要手动去 重新定义Values呢？

**Comment by avwo** [comment]
本地 ip 直接使用 `127.0.0.1`

**Comment by avwo** [comment]
也可以插件动态设置 `key-value`，例如实现一个名为 `whistle.xxx` 的插件，通过 `server` 提供接口 `cgi/rules` 返回以下内容：
```` txt
``` whistle.xxx/serverIp
${serverIp}
```
````
其中 `${serverIp}` 可以通过代码替换成真实的 ip，并在插件根目录创建一个 rules.txt 文件填入以下内容：
``` txt
@whistle.xxx/cgi/rules
```
这样就可以在规则里面通过 `${whistle.xxx/serverIp}` 或 `{whistle.xxx/serverIp}` 引入动态值
